### ISSUE TITLE
AssertionError: No inf checks were recorded for this optimizer.

### ISSUE THREAD

**Issue by eadnams22** [d8ahazard/sd_dreambooth_extension#1002]
### Kindly read the entire form below and fill it out with the requested information.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your
issue will be automatically closed._**

`
#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
Dreambooth revision: d4e2f7d5dc5c67cc6292c8b8137b688a43247c35
SD-WebUI revision: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8

Checking Dreambooth requirements...
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
[+] bitsandbytes version 0.35.4 installed.
[+] diffusers version 0.13.1 installed.
[+] transformers version 4.26.1 installed.
[+] xformers version 0.0.17.dev464 installed.

#######################################################################################################
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes
**Have you updated Dreambooth to the latest revision?**
Yes
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes
**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**
OK

**Describe the bug**

In normal Dreambooth training, late in the training, it occasionally breaks with the error: 

AssertionError: No inf checks were recorded for this optimizer.

**Provide logs**

Generating Samples:  33%|▎| 1/3 [00:01<00:02,  1.26s/it, inst_loss=0.0522, loss=0.0522, lr=1e-6, prior_loss=0, vram=22]Model dir set to: C:\Users\eadna\stable-diffusion-webui\models\dreambooth\csc 8bit
Steps:   0%|                  | 0/12470 [00:00<?, ?it/s, inst_loss=0.0522, loss=0.0522, lr=1e-6, prior_loss=0, vram=22]Traceback (most recent call last):
  File "C:\Users\eadna\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\ui_functions.py", line 555, in start_training
    result = main(use_txt2img=use_txt2img)
  File "C:\Users\eadna\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1133, in main
    return inner_loop()
  File "C:\Users\eadna\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 123, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "C:\Users\eadna\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1019, in inner_loop
    optimizer.step()
  File "C:\Users\eadna\stable-diffusion-webui\venv\lib\site-packages\accelerate\optimizer.py", line 134, in step
    self.scaler.step(self.optimizer, closure)
  File "C:\Users\eadna\stable-diffusion-webui\venv\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 339, in step
    assert len(optimizer_state["found_inf_per_device"]) > 0, "No inf checks were recorded for this optimizer."
AssertionError: No inf checks were recorded for this optimizer.
Steps:  80%|████ | 9984/12470 [00:01<00:00, 6802.41it/s, inst_loss=0.0522, loss=0.0522, lr=1e-6, prior_loss=0, vram=22]
Restored system models.

**Environment**

What OS?
Windows 10

If Windows - WSL or native?

Native

What GPU are you using?

RTX 3090

**Screenshots/Config**

I removed the concepts area, here's the rest.

{
    "adamw_weight_decay": 0.01,
    "attention": "default",
    "cache_latents": true,
    "clip_skip": 1,
    "concepts_path": "",
    "custom_model_name": "",
    "deis_train_scheduler": true,
    "deterministic": true,
    "ema_predict": true,
    "epoch": 0,
    "epoch_pause_frequency": 0,
    "epoch_pause_time": 0,
    "freeze_clip_normalization": true,
    "gradient_accumulation_steps": 1,
    "gradient_checkpointing": false,
    "gradient_set_to_none": true,
    "graph_smoothing": 50,
    "half_model": false,
    "train_unfrozen": true,
    "has_ema": false,
    "hflip": false,
    "infer_ema": false,
    "initial_revision": 0,
    "learning_rate": 1e-06,
    "learning_rate_min": 1e-06,
    "lifetime_revision": 0,
    "lora_learning_rate": 0.0002,
    "lora_model_name": "csc 8bit_0.pt",
    "lora_unet_rank": 4,
    "lora_txt_rank": 4,
    "lora_txt_learning_rate": 0.0002,
    "lora_txt_weight": 1,
    "lora_weight": 1,
    "lr_cycles": 1,
    "lr_factor": 0.5,
    "lr_power": 1,
    "lr_scale_pos": 0.5,
    "lr_scheduler": "constant_with_warmup",
    "lr_warmup_steps": 1000,
    "max_token_length": 75,
    "mixed_precision": "bf16",
    "model_name": "csc 8bit",
    "model_dir": "C:\\Users\\eadna\\stable-diffusion-webui\\models\\dreambooth\\csc 8bit",
    "model_path": "C:\\Users\\eadna\\stable-diffusion-webui\\models\\dreambooth\\csc 8bit",
    "num_train_epochs": 10,
    "offset_noise": 0,
    "optimizer": "8Bit Adam",
    "pad_tokens": true,
    "pretrained_model_name_or_path": "C:\\Users\\eadna\\stable-diffusion-webui\\models\\dreambooth\\csc 8bit\\working",
    "pretrained_vae_name_or_path": null,
    "prior_loss_scale": false,
    "prior_loss_target": 100.0,
    "prior_loss_weight": 0.5,
    "prior_loss_weight_min": 0.1,
    "resolution": 512,
    "revision": 0,
    "sample_batch_size": 13,
    "sanity_prompt": "",
    "sanity_seed": 420420.0,
    "save_ckpt_after": true,
    "save_ckpt_cancel": true,
    "save_ckpt_during": false,
    "save_ema": true,
    "save_embedding_every": 0,
    "save_lora_after": true,
    "save_lora_cancel": false,
    "save_lora_during": false,
    "save_preview_every": 1,
    "save_safetensors": true,
    "save_state_after": true,
    "save_state_cancel": true,
    "save_state_during": false,
    "scheduler": "DEISMultistep",
    "shuffle_tags": true,
    "snapshot": "",
    "split_loss": true,
    "src": "C:\\Users\\eadna\\stable-diffusion-webui\\models\\Stable-diffusion\\1_x\\v1-5-pruned.ckpt",
    "stop_text_encoder": 0.75,
    "strict_tokens": true,
    "tf32_enable": true,
    "train_batch_size": 2,
    "train_imagic": false,
    "train_unet": true,
    "use_concepts": false,
    "use_ema": true,
    "use_lora": false,
    "use_lora_extended": false,
    "use_subdir": true,
    "v2": false
}

**Comment by eadnams22** [comment]
Tried without TF32 as well, same result.

**Comment by SunShopsAdam** [comment]
Same, also on RTX 3090, also on Windows Native

**Comment by eadnams22** [comment]
@SunShopsAdam Hmm... Do you happen to have ControlNet installed and enabled?

**Comment by SunShopsAdam** [comment]
I sure do. It and DB update so frequently though I should have another branch for each...
