### ISSUE TITLE
Dreambooth will not launch on my pc.

### ISSUE THREAD

**Issue by Blendz101** [d8ahazard/sd_dreambooth_extension#1007]
Python revision: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Dreambooth revision: f51380b51c442b61636f0cb19855ca51bfb92919
SD-WebUI revision: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8

Checking Dreambooth requirements...

stderr: 'grep' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\Users\fb marketplace\Desktop\Stable-Diffusion-Main\stable-diffusion-webui\extensions\sd_dreambooth_extension\install.py", line 6, in <module>
    actual_install()
  File "C:\Users\fb marketplace\Desktop\Stable-Diffusion-Main\stable-diffusion-webui\extensions\sd_dreambooth_extension\postinstall.py", line 285, in actual_install
    run(f'"{sys.executable}" -m pip install -r "{req_file}" | grep -v "already satisfied"', f"Checking {name} requirements...",
  File "C:\Users\fb marketplace\Desktop\Stable-Diffusion-Main\stable-diffusion-webui\extensions\sd_dreambooth_extension\postinstall.py", line 22, in run
    raise RuntimeError(
RuntimeError: Couldn't install Dreambooth requirements.. Command: "C:\Users\fb marketplace\Desktop\Stable-Diffusion-Main\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install -r "C:\Users\fb marketplace\Desktop\Stable-Diffusion-Main\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt" | grep -v "already satisfied" Error code: 255

This is the error code
I am on the latest version of everything
Windows 11
I9-9900k
2080ti 11gb
I've tried everything I could which includes:
Restarting web ui
reinstalling web ui from scratch
reinstalling dreambooth directly from git using git clone
using an older version of dreambooth
ect.

**Comment by ArrowM** [comment]
should be fixed by #1009. Please update and try again.

**Comment by Blendz101** [comment]
thx
