### ISSUE TITLE
Error while attempting to train model: Input type (struct c10::Half) and bias type (float) should be the same

### ISSUE THREAD

**Issue by benjaminhmlucas** [d8ahazard/sd_dreambooth_extension#1011]
```
Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Commit hash: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
Installing requirements for Web UI
Skipping dreambooth installation.
Dreambooth revision is f51380b51c442b61636f0cb19855ca51bfb92919
Diffusers version is  0.14.0
Torch version is 1.13.1+cu117
Torch vision version is 0.14.1+cu117
```

I am training a model on pictures of my face.  The db_config.json file keeps getting the lora_model_name set to a '[]' list instead of a string, I have to change the file to read only for a moment and switch it back to fix this issue.  Train batch size keeps getting set to .75 (the error message says this needs to be a whole number) when I press the Performance Wizard button.  Then I am getting a "RuntimeError: Input type (struct c10::Half) and bias type (float) should be the same" error when I attempt to Train the model.  I am on Windows 11 and I have an Nvidia RTX 3080.

Logs:
```st
RuntimeError: Input type (struct c10::Half) and bias type (float) should be the same
Traceback (most recent call last):
  File "C:\Users\blucas\source\repos\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\ui_functions.py", line 657, in start_training
    result = main(use_txt2img=use_txt2img)
  File "C:\Users\blucas\source\repos\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1140, in main
    return inner_loop()
  File "C:\Users\blucas\source\repos\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 123, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "C:\Users\blucas\source\repos\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 198, in inner_loop
    count, instance_prompts, class_prompts = generate_classifiers(args, use_txt2img=use_txt2img,
  File "C:\Users\blucas\source\repos\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\utils\gen_utils.py", line 171, in generate_classifiers
    new_images = builder.generate_images(prompts, pbar)
  File "C:\Users\blucas\source\repos\stable-diffusion-webui\extensions\sd_dreambooth_extension\helpers\image_builder.py", line 234, in generate_images
    output = self.image_pipe(
  File "C:\Users\blucas\source\repos\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\blucas\source\repos\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 667, in __call__
    noise_pred = self.unet(
  File "C:\Users\blucas\source\repos\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\blucas\source\repos\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 576, in forward
    sample = self.conv_in(sample)
  File "C:\Users\blucas\source\repos\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\blucas\source\repos\stable-diffusion-webui\extensions-builtin\Lora\lora.py", line 182, in lora_Conv2d_forward
    return lora_forward(self, input, torch.nn.Conv2d_forward_before_lora(self, input))
  File "C:\Users\blucas\source\repos\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\blucas\source\repos\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (struct c10::Half) and bias type (float) should be the same
Generating class images 0/60::   0%|                                                            | 0/60 [00:02<?, ?it/s]
Restored system models.
```
db_config.json(modified slightly as mentioned above):
```json
{
    "adamw_weight_decay": 0.01,
    "attention": "default",
    "cache_latents": true,
    "clip_skip": 1,
    "concepts_list": [
        {
            "class_data_dir": "",
            "class_guidance_scale": 7.5,
            "class_infer_steps": 40,
            "class_negative_prompt": "",
            "class_prompt": "photo of a man",
            "class_token": "",
            "instance_data_dir": "C:\\Users\\blucas\\Pictures\\ben face",
            "instance_prompt": "photo of blucas",
            "instance_token": "",
            "is_valid": true,
            "n_save_sample": 1,
            "num_class_images_per": 5,
            "sample_seed": -1,
            "save_guidance_scale": 7.5,
            "save_infer_steps": 20,
            "save_sample_negative_prompt": "",
            "save_sample_prompt": "",
            "save_sample_template": ""
        }
    ],
    "concepts_path": "",
    "custom_model_name": "",
    "deis_train_scheduler": false,
    "deterministic": false,
    "ema_predict": false,
    "epoch": 0,
    "epoch_pause_frequency": 0,
    "epoch_pause_time": 60,
    "freeze_clip_normalization": false,
    "gradient_accumulation_steps": 1,
    "gradient_checkpointing": true,
    "gradient_set_to_none": true,
    "graph_smoothing": 50,
    "half_lora": false,
    "half_model": false,
    "train_unfrozen": false,
    "has_ema": false,
    "hflip": false,
    "infer_ema": false,
    "initial_revision": 0,
    "learning_rate": 2e-06,
    "learning_rate_min": 1e-06,
    "lifetime_revision": 0,
    "lora_learning_rate": 0.0002,
    "lora_model_name": "",
    "lora_unet_rank": 4,
    "lora_txt_rank": 4,
    "lora_txt_learning_rate": 0.0002,
    "lora_txt_weight": 1,
    "lora_weight": 1,
    "lr_cycles": 1,
    "lr_factor": 0.5,
    "lr_power": 1,
    "lr_scale_pos": 0.5,
    "lr_scheduler": "constant_with_warmup",
    "lr_warmup_steps": 0,
    "max_token_length": 75,
    "mixed_precision": "no",
    "model_name": "blucas",
    "model_dir": "C:\\Users\\blucas\\source\\repos\\stable-diffusion-webui\\models\\dreambooth\\blucas",
    "model_path": "C:\\Users\\blucas\\source\\repos\\stable-diffusion-webui\\models\\dreambooth\\blucas",
    "num_train_epochs": 150,
    "offset_noise": 0,
    "optimizer": "8Bit Adam",
    "pad_tokens": true,
    "pretrained_model_name_or_path": "C:\\Users\\blucas\\source\\repos\\stable-diffusion-webui\\models\\dreambooth\\blucas\\working",
    "pretrained_vae_name_or_path": "",
    "prior_loss_scale": false,
    "prior_loss_target": 100.0,
    "prior_loss_weight": 0.75,
    "prior_loss_weight_min": 0.1,
    "resolution": 512,
    "revision": 0,
    "sample_batch_size": 1,
    "sanity_prompt": "",
    "sanity_seed": 420420.0,
    "save_ckpt_after": true,
    "save_ckpt_cancel": false,
    "save_ckpt_during": false,
    "save_ema": true,
    "save_embedding_every": 25,
    "save_lora_after": true,
    "save_lora_cancel": false,
    "save_lora_during": false,
    "save_preview_every": 5,
    "save_safetensors": true,
    "save_state_after": false,
    "save_state_cancel": false,
    "save_state_during": false,
    "scheduler": "DEISMultistep",
    "shuffle_tags": true,
    "snapshot": "",
    "split_loss": true,
    "src": "C:\\Users\\blucas\\source\\repos\\stable-diffusion-webui\\models\\Stable-diffusion\\sd-v1-4.ckpt",
    "stop_text_encoder": 1,
    "strict_tokens": false,
    "tf32_enable": false,
    "train_batch_size": 1,
    "train_imagic": false,
    "train_unet": true,
    "use_concepts": false,
    "use_ema": false,
    "use_lora": true,
    "use_lora_extended": false,
    "use_subdir": true,
    "v2": false
}
```

**Comment by ebravofm** [comment]
I'm having the same issue on windows 10 with a NVIDIA 2060 SUPER

**Comment by ebravofm** [comment]
I was able to make it work by downgrading the extension to version 1.0.1 (run "git reset 43ae9d5 --hard" on the extension's folder ...stable-diffusion-webui\extensions\sd_dreambooth_extension).

**Comment by netsky84** [comment]
> I was able to make it work by downgrading the extension to version 1.0.1 (run "git reset [43ae9d5](https://github.com/d8ahazard/sd_dreambooth_extension/commit/43ae9d55531004f1dedaea7ac2443e9b16739913) --hard" on the extension's folder ...stable-diffusion-webui\extensions\sd_dreambooth_extension).

I've a NVIDIA 4080 on windows 11, I've trained a model and everything worked, then I tried to make another one but it kept giving me this error.
Thank you, now it works again

**Comment by ArrowM** [comment]
For future people finding this thread, please update to the latest version of main (d6490b47aa27ed06c6374658f3449478de1b8e5e) instead of using the git reset suggested by above
