### ISSUE TITLE
ValueError: batch_size should be a positive integer value, but got batch_size=0.75

### ISSUE THREAD

**Issue by arnebp** [d8ahazard/sd_dreambooth_extension#1019]
### Kindly read the entire form below and fill it out with the requested information.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your
issue will be automatically closed._**

`
Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Commit hash: ****************************************
Installing requirements for Web UI
Skipping dreambooth installation.
Dreambooth revision is ****************************************
Diffusers version is *.*.*.
Torch version is *.*.*.
Torch vision version is *.*.*.
`

Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
Installing requirements for Web UI

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: 19d27b622b0bd3245903d810c1b45538d286bedf
SD-WebUI revision: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8

Checking Dreambooth requirements...
['t', 't', '0', ')', '1', ')', '1', ')', 's', ')', 's', 's', '1', ':', '1', 'n', '7', ':', '7', 'e', '0', ':', '0', 's', '1', ':', '1', '1', '']
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
[+] bitsandbytes version 0.35.4 installed.
[+] diffusers version 0.13.1 installed.
[+] transformers version 4.26.1 installed.
[+] xformers version 0.0.17.dev464 installed.

#######################################################################################################

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yes

**Have you updated Dreambooth to the latest revision?**
yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**
ok

**Describe the bug**

(A clear and concise description of what the bug is)

**Provide logs**

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *
before* the crash occurred.

Traceback (most recent call last):
  File "C:\open\git\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\ui_functions.py", line 691, in start_training
    result = main(use_txt2img=use_txt2img)
  File "C:\open\git\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1140, in main
    return inner_loop()
  File "C:\open\git\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 123, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "C:\open\git\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 450, in inner_loop
    train_dataset = generate_dataset(
  File "C:\open\git\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\utils\gen_utils.py", line 71, in generate_dataset
    train_dataset = DbDataset(
  File "C:\open\git\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dataset\db_dataset.py", line 79, in __init__
    self.batch_sampler = torch.utils.data.BatchSampler(self, batch_size, drop_last=True)
  File "C:\open\git\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\sampler.py", line 232, in __init__
    raise ValueError("batch_size should be a positive integer value, "
ValueError: batch_size should be a positive integer value, but got batch_size=0.75

**Environment**

What OS?
Win 10 Enterprise

If Windows - WSL or native?
Native

What GPU are you using?
RTX 2070

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the
db_config.json file from /models/dreambooth/MODELNAME/db_config.json
[db_config.zip](https://github.com/d8ahazard/sd_dreambooth_extension/files/10891892/db_config.zip)

attached db

**Comment by arnebp** [comment]
Note, batch size is automatically set to .75 when using the 'Performance Wizard (WIP)' option

**Comment by Risto-Paasivirta** [comment]
I've noticed same thing, also the performance wizard might turn some slider like the "Step Ratio of Text Encoder Training" at the advanced tab into an empty value and then it complains about not being able to evaluate string.

Not a huge deal tho, I just go through the page and wiggle the broken sliders back into sensible values.

**Comment by ArrowM** [comment]
> Note, batch size is automatically set to .75 when using the 'Performance Wizard (WIP)' option

Hey, thanks for pointing this out. There have been quite a few issues of people getting weird values for the fields and I hadn't been able to figure it out until this comment.

**Comment by ArrowM** [comment]
Fixed in dev 5b5dd173493b5a590b41826a53165f27a15fc883, should be merged to main today or tomorrow.
