### ISSUE TITLE
TypeError: type str doesn't define __round__ method

### ISSUE THREAD

**Issue by arnebp** [d8ahazard/sd_dreambooth_extension#1021]
### Kindly read the entire form below and fill it out with the requested information.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your
issue will be automatically closed._**

`
Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: 19d27b622b0bd3245903d810c1b45538d286bedf
SD-WebUI revision: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8

Checking Dreambooth requirements...
['t', 't', '0', ')', '1', ')', '1', ')', 's', ')', 's', 's', '1', ':', '1', 'n', '7', ':', '7', 'e', '0', ':', '0', 's', '1', ':', '1', '1', '']
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
[+] bitsandbytes version 0.35.4 installed.
[+] diffusers version 0.13.1 installed.
[+] transformers version 4.26.1 installed.
[+] xformers version 0.0.17.dev464 installed.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
yup

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yup

**Have you updated Dreambooth to the latest revision?**
yup

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
yup

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**
ok

**Describe the bug**

Training fails with what looks to be a rather reproducible error

**Provide logs**

Traceback (most recent call last):
  File "C:\open\git\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\ui_functions.py", line 691, in start_training
    result = main(use_txt2img=use_txt2img)
  File "C:\open\git\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1140, in main
    return inner_loop()
  File "C:\open\git\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 123, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "C:\open\git\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 569, in inner_loop
    text_encoder_epochs = round(max_train_epochs * stop_text_percentage)
TypeError: type str doesn't define __round__ method

**Environment**

What OS?
Win10 Enterprise

If Windows - WSL or native?
Native

What GPU are you using?
RTX2070

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the
db_config.json file from /models/dreambooth/MODELNAME/db_config.json
[db_config.zip](https://github.com/d8ahazard/sd_dreambooth_extension/files/10892748/db_config.zip)

**Comment by s7e7v7e7n7** [comment]
same error;

...
Initializing bucket counter!
Traceback (most recent call last):
  File "D:\stable-diffusion-webui-master\extensions\sd_dreambooth_extension\dreambooth\ui_functions.py", line 691, in start_training
    result = main(use_txt2img=use_txt2img)
  File "D:\stable-diffusion-webui-master\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1140, in main
    return inner_loop()
  File "D:\stable-diffusion-webui-master\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 123, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "D:\stable-diffusion-webui-master\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 569, in inner_loop
    text_encoder_epochs = round(max_train_epochs * stop_text_percentage)
TypeError: type str doesn't define __round__ method

8GB RTX2070 MAX Q

**Comment by arnebp** [comment]
From the 'db_config.json' I observe that key 'stop_text_encoder' is now a str where it used to be a float

Now:
`  "stop_text_encoder": "8Bit Adam",`

Previously:
`  "stop_text_encoder": 0.75,`

**Comment by s7e7v7e7n7** [comment]
> From the 'db_config.json' I observe that key 'stop_text_encoder' is now a str where it used to be a float
> 
> Now: ` "stop_text_encoder": "8Bit Adam",`
> 
> Previously: ` "stop_text_encoder": 0.75,`

its solved thank you!

**Comment by ArrowM** [comment]
duplicate #1016
