### ISSUE TITLE
Are low VRAM systems supported?

### ISSUE THREAD

**Issue by arnebp** [d8ahazard/sd_dreambooth_extension#1024]
### Kindly read the entire form below and fill it out with the requested information.

Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
Installing requirements for Web UI

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: 19d27b622b0bd3245903d810c1b45538d286bedf
SD-WebUI revision: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8

Checking Dreambooth requirements...
['t', 't', '0', ')', '1', ')', '1', ')', 's', ')', 's', 's', '1', ':', '1', 'n', '7', ':', '7', 'e', '0', ':', '0', 's', '1', ':', '1', '1', '']
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
[+] bitsandbytes version 0.35.4 installed.
[+] diffusers version 0.13.1 installed.
[+] transformers version 4.26.1 installed.
[+] xformers version 0.0.17.dev464 installed.

#######################################################################################################

Launching Web UI with arguments: --xformers --medvram

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
yup

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yup

**Have you updated Dreambooth to the latest revision?**
yup

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
yup

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**
ok

**Describe the bug**

Looking through the [optimizations args of sd-web-ui](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Optimizations), it looks like arguments like --medvram and --lowvram should reduce vram allocation and allow training on older GPU. 

I observe that using these arguments do not affect [sd_dreambooth_extension](https://github.com/d8ahazard/sd_dreambooth_extension) that seems to allocate 8gb VRAM no matter how much I tweak according to the optimizations page. Is this by design or a bug?

I've tried using sd 1.5, 2.0-512 and 2.1-512

**Provide logs**

Traceback (most recent call last):
  File "C:\open\git\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 123, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "C:\open\git\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1017, in inner_loop
    accelerator.backward(loss)
  File "C:\open\git\stable-diffusion-webui\venv\lib\site-packages\accelerate\accelerator.py", line 1439, in backward
    self.scaler.scale(loss).backward(**kwargs)
  File "C:\open\git\stable-diffusion-webui\venv\lib\site-packages\torch\_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "C:\open\git\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "C:\open\git\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\function.py", line 267, in apply
    return user_fn(self, *args)
  File "C:\open\git\stable-diffusion-webui\venv\lib\site-packages\torch\utils\checkpoint.py", line 157, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "C:\open\git\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 10.00 MiB (GPU 0; 8.00 GiB total capacity; 7.17 GiB already allocated; 0 bytes free; 7.26 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Steps:   0%|                                                                                  | 0/2600 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "C:\open\git\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\ui_functions.py", line 691, in start_training
    result = main(use_txt2img=use_txt2img)
  File "C:\open\git\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1140, in main
    return inner_loop()
  File "C:\open\git\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 121, in decorator
    raise RuntimeError("No executable batch size found, reached zero.")
RuntimeError: No executable batch size found, reached zero.

**Environment**

What OS?
Win 10 Enterprise

If Windows - WSL or native?
Native

What GPU are you using?
RTX2070

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the
db_config.json file from /models/dreambooth/MODELNAME/db_config.json
[db_config.zip](https://github.com/d8ahazard/sd_dreambooth_extension/files/10895904/db_config.zip)

**Comment by arnebp** [comment]
From webui-users.bat:

```
set COMMANDLINE_ARGS=--xformers --medvram

set PYTORCH_CUDA_ALLOC_CONF=garbage_collection_threshold:0.9,max_split_size_mb:512
```

**Comment by andrei007999** [comment]
You can't train Dreambooth on 8 gigs.

Max you can train is Extended Lora.

**Comment by ArrowM** [comment]
Dreambooth (in general, not just the extension) requires quite a bit of VRAM. For lower VRAM, use Lora or Extended Lora.

**Comment by ArrowM** [comment]
> @andrei007999 several tuning guides indicate 8Gb GPU training as possible https://huggingface.co/docs/diffusers/training/dreambooth#training-on-a-8-gb-gpu
> 
> @ArrowM In my experience, using LoRa for faces leads to uncanny valley results, thus my request to look into low VRAM support excluding LoRa

This is with DeepSpeed, (which will be pretty slow), you should be able to use it with this extension though, by configuring accelerate `accelerate config`.
