### ISSUE TITLE
Can't use my previously generated .pt files; unclear on how to convert to .safetensors

### ISSUE THREAD

**Issue by mstan** [d8ahazard/sd_dreambooth_extension#1028]
### Kindly read the entire form below and fill it out with the requested information.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your
issue will be automatically closed._**

```
Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
Commit hash: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
Installing requirements for Web UI

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
Dreambooth revision: 19d27b622b0bd3245903d810c1b45538d286bedf
SD-WebUI revision: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8

Checking Dreambooth requirements...
['t', 't', '0', ')', '1', ')', '1', ')', 's', ')', 's', 's', '1', ':', '1', 'n', '7', ':', '7', 'e', '0', ':', '0', 's', '1', ':', '1', '1', '']
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
```

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes
**Have you updated Dreambooth to the latest revision?**
Yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes 
**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**
OK

**Describe the bug**
I created some LoRAs using this extension on an older hash of sd_dreambooth_extension. The commit hash was `eca1ba410be4c20115e7d4424891e25970bac379 `. The files were saved using a .pt and _txt.pt file. 

I have now updated both AUTOMATIC1111's web-ui and this extension to the latest versions (see above). However, my .pt LORAs don't work anymore. I always get either of the following errors when trying to use them as included LoRAs with the <lora:filename> syntax:

Either:
`AttributeError: 'list' object has no attribute 'items'` or `TypeError: pop expected at most 1 argument, got 2`

(A clear and concise description of what the bug is)

**Provide logs**

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *
before* the crash occurred.

```
Traceback (most recent call last):
  File "E:\StableDiffusion\AUTOMATIC1111\stable-diffusion-webui\modules\extra_networks.py", line 75, in activate
    extra_network.activate(p, extra_network_args)
  File "E:\StableDiffusion\AUTOMATIC1111\stable-diffusion-webui\extensions-builtin\Lora\extra_networks_lora.py", line 23, in activate
    lora.load_loras(names, multipliers)
  File "E:\StableDiffusion\AUTOMATIC1111\stable-diffusion-webui\extensions-builtin\Lora\lora.py", line 151, in load_loras
    lora = load_lora(name, lora_on_disk.filename)
  File "E:\StableDiffusion\AUTOMATIC1111\stable-diffusion-webui\extensions-builtin\Lora\lora.py", line 83, in load_lora
    sd = sd_models.read_state_dict(filename)
  File "E:\StableDiffusion\AUTOMATIC1111\stable-diffusion-webui\modules\sd_models.py", line 224, in read_state_dict
    sd = get_state_dict_from_checkpoint(pl_sd)
  File "E:\StableDiffusion\AUTOMATIC1111\stable-diffusion-webui\modules\sd_models.py", line 197, in get_state_dict_from_checkpoint
    pl_sd = pl_sd.pop("state_dict", pl_sd)
TypeError: pop expected at most 1 argument, got 2
```

**Environment**

What OS?
Windows

If Windows - WSL or native?
native

What GPU are you using?
Nvidia GTX 3080 TI

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the
db_config.json file from /models/dreambooth/MODELNAME/db_config.json

N/A

**Other Notes**

I have tried using some recent .safetensors files from civtai to see if that made a difference. It does. .safetensors formats are working just fine for LORA generation.

I also noticed that on the prior hash I was using, saving in .safetensors was even an option, but I don't see this option anywhere on the latest commit I'm on now.
![chrome_2023-03-06_15-24-43](https://user-images.githubusercontent.com/5354790/223280127-4aac6461-f995-49e6-8a8f-f7d1ef214dd7.png)
.

**Comment by gammagoat** [comment]
The .pt and _txt.pt files cannot be used in txt2img in a1111. With the new update to the extension, newly trained Loras will also generate a safetensors file that should work.

**Comment by mstan** [comment]
> The .pt and _txt.pt files cannot be used in txt2img in a1111. With the new update to the extension, newly trained Loras will also generate a safetensors file that should work.

That's interesting. I was incorporating LORAs generated with this extension in txt2img with a1111 commit hash 35419b274614984e2b511a6ad34f37e41481c809 just yesterday. Was that just a fluke?

I'd like to be able to take the .pt and _txt.pt files I have and convert them into a .safetensors format since .safetensors seems to work with a1111 txt2img. I have around 30 LORAs and am avoiding having to retrain all of them if it can be helped.

**Comment by gammagoat** [comment]
Interesting it worked with old version, I was not aware of that. Converting them would be possible, but I did not write the code to do it. It is not particularly hard, but it doesn't really make sense in the UI going forward. Can you program python. I can explain how to do it.

**Comment by mstan** [comment]
Not expecting a UI by any means. This feels like a one-off endeavor. I can program in JavaScript/Node fairly efficiently, but Python isn't a strong suit of mine. 

I suspect the libraries for parsing the libraries don't exist in Node; so I can make a best effort in Python.

**Comment by gammagoat** [comment]
The code that makes the Lora safetensors is here: https://github.com/d8ahazard/sd_dreambooth_extension/blob/main/lora_diffusion/extra_networks.py

The save_extra_networks method. 

If you look at where it is called during saving I. Here. https://github.com/d8ahazard/sd_dreambooth_extension/blob/main/dreambooth/train_dreambooth.py

You can see what needs to happen. You could probably hack generate_ckpt to also generate this, or generate this instead. You would also need to copy your .pt and ,_txt.pt files into the loras subdir of the model.

There have been a few people that have asked. Maybe I can take a look tomorrow and see if I can throw something together.

**Comment by mstan** [comment]
Giving it an eye. Feels a bit over my head at the moment. If I can assist during any script tests/iterations tomorrow, do let me know.

**Comment by mstan** [comment]
Added follow up, I'm running the latest training on a new model. You mentioned the following:
>  With the new update to the extension, newly trained Loras will also generate a safetensors file that should work.

Are you suggesting the new .pt files are interchangeable with .safetensors, or that I should also be seeing .safetensors LORAs alongside the .pt files?
![chrome_2023-03-06_21-32-35](https://user-images.githubusercontent.com/5354790/223330145-71d9c203-c765-40b1-9eca-cc00b69e9bf4.png)

I ensured this was checked , but I'm only seeing .pt files still. 

Can file a separate issue if necessary

**Comment by ArrowM** [comment]
> EDIT: Disregard. I see that it places them in the models/lora, not alongside the .pt files

So the ones in `models/lora` are working for you? Can the issue be closed?

**Comment by gammagoat** [comment]
Ok, I wrote a hack to accomplish this. It is in my fork here https://github.com/gammagoat/sd_dreambooth_extension/commit/3c5a393b820e9205c3e67f82d3467459de76d2fd

To use it do in the UI

- Copy your old .pt and _txt.pt file into the models\dreambooth\model_name\loras directory
- in the dreambooth tab, select your old model
- click "Load Settings"
- select the lora model you want to convert
- click save settings (this may not be needed, but it is safer)
- click the new Gen Lora for Extra Networks button.

It should create the new file under models/lora with a name that matches the lora file but with "_old.safetensors"

Let me know if it works

**Comment by mstan** [comment]
> So the ones in models/lora are working for you? Can the issue be closed?
To confirm, I attempting new generations with the most recent version, and originally was not seeing the properly generated .safetensors. This was un-related to any historically trained .pt LoRA files

> Let me know if it works
Followed instructions, converted all my legacy .pt files. Did a few test prompts on a couple of different models. It's all looking good! Considering this one done!
