### ISSUE TITLE
ModuleNotFoundError: No module named 'dreambooth.dreambooth'

### ISSUE THREAD

**Issue by XylitolJ** [d8ahazard/sd_dreambooth_extension#1046]
### Kindly read the entire form below and fill it out with the requested information.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your
issue will be automatically closed._**

`
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
Commit hash: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
stable-diffusion:web-automatic-3.0.0
Installing requirements for Web UI
Skipping dreambooth installation.
Dreambooth revision is ****************************************
Diffusers version is 1.5
Torch version is *.*.*.
Torch vision version is *.*.*.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
YES
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
YES
**Have you updated Dreambooth to the latest revision?**
YES
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
YES
**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**
OK

**Describe the bug**

ModuleNotFoundError: No module named 'dreambooth.dreambooth'

Stable Diffusion webui is running correctly, but everytime I try to install Dreambooth from the extension tab and restart, error would pop and I won't be able to see the tab. I have searched online for answer but in vain, so I come up for help.

**Provide logs**

2023-03-09T08:09:56.133995216Z ################################################################
2023-03-09T08:09:56.133998386Z Launching launch.py...
2023-03-09T08:09:56.134001426Z ################################################################
2023-03-09T08:09:56.166618016Z Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
2023-03-09T08:09:56.166630736Z Commit hash: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
2023-03-09T08:09:56.479972546Z /workspace/stable-diffusion-webui/venv/lib/python3.10/site-packages/traitlets/traitlets.py:3437: FutureWarning: --terminado_settings={"shell_command":["/bin/bash"]} for dict-traits is deprecated in traitlets 5.0. You can pass --terminado_settings <key=value> ... multiple times to add items to a dict.
2023-03-09T08:09:56.480007486Z   warn(
2023-03-09T08:09:56.480188237Z [W 2023-03-09 08:09:56.480 ServerApp] ServerApp.token config is deprecated in 2.0. Use IdentityProvider.token.
2023-03-09T08:09:56.485279035Z [I 2023-03-09 08:09:56.485 ServerApp] Package jupyterlab took 0.0000s to import
2023-03-09T08:09:56.486606835Z [I 2023-03-09 08:09:56.486 ServerApp] Package jupyter_archive took 0.0011s to import
2023-03-09T08:09:56.488256207Z [I 2023-03-09 08:09:56.488 ServerApp] Package jupyter_server_fileid took 0.0015s to import
2023-03-09T08:09:56.491275189Z [I 2023-03-09 08:09:56.491 ServerApp] Package jupyter_server_terminals took 0.0027s to import
2023-03-09T08:09:56.504400826Z [I 2023-03-09 08:09:56.504 ServerApp] Package jupyter_server_ydoc took 0.0128s to import
2023-03-09T08:09:56.504576377Z [I 2023-03-09 08:09:56.504 ServerApp] Package nbclassic took 0.0000s to import
2023-03-09T08:09:56.505539054Z [W 2023-03-09 08:09:56.505 ServerApp] A `_jupyter_server_extension_points` function was not found in nbclassic. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
2023-03-09T08:09:56.505822466Z [I 2023-03-09 08:09:56.505 ServerApp] Package notebook_shim took 0.0000s to import
2023-03-09T08:09:56.505828166Z [W 2023-03-09 08:09:56.505 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
2023-03-09T08:09:56.506252999Z [I 2023-03-09 08:09:56.506 ServerApp] jupyter_archive | extension was successfully linked.
2023-03-09T08:09:56.508947869Z [I 2023-03-09 08:09:56.508 ServerApp] jupyter_server_fileid | extension was successfully linked.
2023-03-09T08:09:56.511467098Z [I 2023-03-09 08:09:56.511 ServerApp] jupyter_server_terminals | extension was successfully linked.
2023-03-09T08:09:56.513896156Z [I 2023-03-09 08:09:56.513 ServerApp] jupyter_server_ydoc | extension was successfully linked.
2023-03-09T08:09:56.516981148Z [I 2023-03-09 08:09:56.516 ServerApp] jupyterlab | extension was successfully linked.
2023-03-09T08:09:56.519408836Z [I 2023-03-09 08:09:56.519 ServerApp] nbclassic | extension was successfully linked.
2023-03-09T08:09:56.520064631Z [I 2023-03-09 08:09:56.519 ServerApp] Writing Jupyter server cookie secret to /root/.local/share/jupyter/runtime/jupyter_cookie_secret
2023-03-09T08:09:56.768860755Z [I 2023-03-09 08:09:56.768 ServerApp] notebook_shim | extension was successfully linked.
2023-03-09T08:09:56.770029413Z /workspace/stable-diffusion-webui/venv/lib/python3.10/site-packages/traitlets/traitlets.py:1872: FutureWarning: ServerApp.preferred_dir config is deprecated in jupyter-server 2.0. Use FileContentsManager.preferred_dir instead
2023-03-09T08:09:56.770037533Z   return self._get_trait_default_generator(names[0])(self)
2023-03-09T08:09:56.807011156Z [W 2023-03-09 08:09:56.806 ServerApp] WARNING: The Jupyter server is listening on all IP addresses and not using encryption. This is not recommended.
2023-03-09T08:09:56.807556970Z [I 2023-03-09 08:09:56.807 ServerApp] notebook_shim | extension was successfully loaded.
2023-03-09T08:09:56.807868482Z [I 2023-03-09 08:09:56.807 ServerApp] jupyter_archive | extension was successfully loaded.
2023-03-09T08:09:56.807881242Z [I 2023-03-09 08:09:56.807 FileIdExtension] Configured File ID manager: ArbitraryFileIdManager
2023-03-09T08:09:56.808066583Z [I 2023-03-09 08:09:56.807 FileIdExtension] ArbitraryFileIdManager : Configured root dir: /
2023-03-09T08:09:56.808078733Z [I 2023-03-09 08:09:56.807 FileIdExtension] ArbitraryFileIdManager : Configured database path: /root/.local/share/jupyter/file_id_manager.db
2023-03-09T08:09:56.808377286Z [I 2023-03-09 08:09:56.808 FileIdExtension] ArbitraryFileIdManager : Successfully connected to database file.
2023-03-09T08:09:56.808385186Z [I 2023-03-09 08:09:56.808 FileIdExtension] ArbitraryFileIdManager : Creating File ID tables and indices with journal_mode = DELETE
2023-03-09T08:09:56.863196330Z [I 2023-03-09 08:09:56.862 FileIdExtension] Attached event listeners.
2023-03-09T08:09:56.863246250Z [I 2023-03-09 08:09:56.863 ServerApp] jupyter_server_fileid | extension was successfully loaded.
2023-03-09T08:09:56.864089177Z [I 2023-03-09 08:09:56.863 ServerApp] jupyter_server_terminals | extension was successfully loaded.
2023-03-09T08:09:56.864390879Z [I 2023-03-09 08:09:56.864 ServerApp] jupyter_server_ydoc | extension was successfully loaded.
2023-03-09T08:09:56.864822092Z [I 2023-03-09 08:09:56.864 LabApp] JupyterLab extension loaded from /workspace/stable-diffusion-webui/venv/lib/python3.10/site-packages/jupyterlab
2023-03-09T08:09:56.864828612Z [I 2023-03-09 08:09:56.864 LabApp] JupyterLab application directory is /workspace/stable-diffusion-webui/venv/share/jupyter/lab
2023-03-09T08:09:56.866889137Z [I 2023-03-09 08:09:56.866 ServerApp] jupyterlab | extension was successfully loaded.
2023-03-09T08:09:56.868485909Z 
2023-03-09T08:09:56.868503959Z   _   _          _      _
2023-03-09T08:09:56.868508889Z  | | | |_ __  __| |__ _| |_ ___
2023-03-09T08:09:56.868512489Z  | |_| | '_ \/ _` / _` |  _/ -_)
2023-03-09T08:09:56.868516059Z   \___/| .__/\__,_\__,_|\__\___|
2023-03-09T08:09:56.868519859Z        |_|
2023-03-09T08:09:56.868522969Z                                                                            
2023-03-09T08:09:56.868526129Z Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.
2023-03-09T08:09:56.868529379Z 
2023-03-09T08:09:56.868532329Z https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html
2023-03-09T08:09:56.868535399Z 
2023-03-09T08:09:56.868538219Z Please note that updating to Notebook 7 might break some of your extensions.
2023-03-09T08:09:56.868541319Z 
2023-03-09T08:09:56.868987843Z [I 2023-03-09 08:09:56.868 ServerApp] nbclassic | extension was successfully loaded.
2023-03-09T08:09:56.869369966Z [I 2023-03-09 08:09:56.869 ServerApp] Serving notebooks from local directory: /
2023-03-09T08:09:56.869374326Z [I 2023-03-09 08:09:56.869 ServerApp] Jupyter Server 2.4.0 is running at:
2023-03-09T08:09:56.869376266Z [I 2023-03-09 08:09:56.869 ServerApp] http://localhost:8888/lab?token=...
2023-03-09T08:09:56.869428296Z [I 2023-03-09 08:09:56.869 ServerApp]     http://127.0.0.1:8888/lab?token=...
2023-03-09T08:09:56.869430866Z [I 2023-03-09 08:09:56.869 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
2023-03-09T08:09:57.167116759Z Installing requirements for Web UI
2023-03-09T08:10:03.472896220Z Docker, returning.
2023-03-09T08:10:03.472928060Z Script path is 
2023-03-09T08:10:03.472934400Z 
2023-03-09T08:10:03.472938230Z Launching Web UI with arguments: --port 3000 --xformers --listen --enable-insecure-extension-access
2023-03-09T08:10:07.914361362Z Script path is 
2023-03-09T08:10:07.975009619Z Error loading script: api.py
2023-03-09T08:10:07.975187660Z Traceback (most recent call last):
2023-03-09T08:10:07.975210880Z   File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dataclasses/db_config.py", line 11, in <module>
2023-03-09T08:10:07.975218040Z     from extensions.sd_dreambooth_extension.dreambooth.utils.image_utils import get_scheduler_names
2023-03-09T08:10:07.975222180Z   File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/utils/image_utils.py", line 11, in <module>
2023-03-09T08:10:07.975226310Z     from diffusers.schedulers import KarrasDiffusionSchedulers
2023-03-09T08:10:07.975229550Z ModuleNotFoundError: No module named 'diffusers'
2023-03-09T08:10:07.975232900Z 
2023-03-09T08:10:07.975236001Z During handling of the above exception, another exception occurred:
2023-03-09T08:10:07.975239231Z 
2023-03-09T08:10:07.975242131Z Traceback (most recent call last):
2023-03-09T08:10:07.975245131Z   File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/api.py", line 27, in <module>
2023-03-09T08:10:07.975248581Z     from extensions.sd_dreambooth_extension.dreambooth.dataclasses.db_config import from_file, DreamboothConfig
2023-03-09T08:10:07.975251861Z   File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dataclasses/db_config.py", line 14, in <module>
2023-03-09T08:10:07.975255771Z     from dreambooth.dreambooth import shared  # noqa
2023-03-09T08:10:07.975258911Z ModuleNotFoundError: No module named 'dreambooth.dreambooth'
2023-03-09T08:10:07.975261901Z 
2023-03-09T08:10:07.975264701Z During handling of the above exception, another exception occurred:
2023-03-09T08:10:07.975267731Z 
2023-03-09T08:10:07.975270531Z Traceback (most recent call last):
2023-03-09T08:10:07.975273441Z   File "/workspace/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
2023-03-09T08:10:07.975276681Z     script_module = script_loading.load_module(scriptfile.path)
2023-03-09T08:10:07.975279741Z   File "/workspace/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
2023-03-09T08:10:07.975282991Z     module_spec.loader.exec_module(module)
2023-03-09T08:10:07.975285981Z   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2023-03-09T08:10:07.975304271Z   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-03-09T08:10:07.975308141Z   File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/api.py", line 37, in <module>
2023-03-09T08:10:07.975311641Z     from dreambooth.dreambooth import shared  # noqa
2023-03-09T08:10:07.975314731Z ModuleNotFoundError: No module named 'dreambooth.dreambooth'
2023-03-09T08:10:07.975317781Z 
2023-03-09T08:10:07.976102687Z Error loading script: main.py
2023-03-09T08:10:07.976262918Z Traceback (most recent call last):
2023-03-09T08:10:07.976274888Z   File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dataclasses/db_config.py", line 11, in <module>
2023-03-09T08:10:07.976281228Z     from extensions.sd_dreambooth_extension.dreambooth.utils.image_utils import get_scheduler_names
2023-03-09T08:10:07.976285228Z   File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/utils/image_utils.py", line 11, in <module>
2023-03-09T08:10:07.976289268Z     from diffusers.schedulers import KarrasDiffusionSchedulers
2023-03-09T08:10:07.976292618Z ModuleNotFoundError: No module named 'diffusers'
2023-03-09T08:10:07.976296008Z 
2023-03-09T08:10:07.976299018Z During handling of the above exception, another exception occurred:
2023-03-09T08:10:07.976302248Z 
2023-03-09T08:10:07.976305228Z Traceback (most recent call last):
2023-03-09T08:10:07.976308258Z   File "/workspace/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
2023-03-09T08:10:07.976311618Z     script_module = script_loading.load_module(scriptfile.path)
2023-03-09T08:10:07.976314748Z   File "/workspace/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
2023-03-09T08:10:07.976318019Z     module_spec.loader.exec_module(module)
2023-03-09T08:10:07.976321129Z   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2023-03-09T08:10:07.976324589Z   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-03-09T08:10:07.976328389Z   File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 7, in <module>
2023-03-09T08:10:07.976332039Z     from extensions.sd_dreambooth_extension.dreambooth.dataclasses.db_config import save_config, from_file
2023-03-09T08:10:07.976335379Z   File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dataclasses/db_config.py", line 14, in <module>
2023-03-09T08:10:07.976339439Z     from dreambooth.dreambooth import shared  # noqa
2023-03-09T08:10:07.976342559Z ModuleNotFoundError: No module named 'dreambooth.dreambooth'
2023-03-09T08:10:07.976345719Z 
2023-03-09T08:10:07.977288496Z Loading weights [4c86efd062] from /workspace/stable-diffusion-webui/models/Stable-diffusion/SDv1-5.ckpt
2023-03-09T08:10:08.934134888Z Creating model from config: /workspace/stable-diffusion-webui/configs/v1-inference.yaml
2023-03-09T08:10:08.934579391Z LatentDiffusion: Running in eps-prediction mode
2023-03-09T08:10:09.304000843Z DiffusionWrapper has 859.52 M params.
2023-03-09T08:10:13.860429362Z Applying xformers cross attention optimization.
2023-03-09T08:10:13.866036453Z Textual inversion embeddings loaded(0): 
2023-03-09T08:10:13.868258110Z Model loaded in 5.9s (load weights from disk: 0.9s, create model: 0.7s, apply weights to model: 1.5s, apply half(): 1.7s, load VAE: 0.8s, move model to device: 0.3s).
2023-03-09T08:10:14.186736347Z Running on local URL:  http://0.0.0.0:3000
2023-03-09T08:10:14.186759777Z 
2023-03-09T08:10:14.186765367Z To create a public link, set `share=True` in `launch()`.

**Environment**

Ubuntu 22.04.2 LTS

What GPU are you using?
RTX A5000

**Screenshots/Config**

![11111111111111](https://user-images.githubusercontent.com/16879990/223964072-d803b28a-865c-4065-8554-2da809125c85.jpg)

![image](https://user-images.githubusercontent.com/16879990/223964215-1431ebbc-9401-4d44-94b7-e0425a447036.png)

**Comment by Arilziem** [comment]
I'd assume the actual error is
`2023-03-09T08:10:07.975229550Z ModuleNotFoundError: No module named 'diffusers'`

So you seem to be missing dependencies.

Are you running the webui using the provided `webui-user-dreambooth.sh`? That should normally trigger the installation of necessary dependencies.

**Comment by XylitolJ** [comment]
> I'd assume the actual error is `2023-03-09T08:10:07.975229550Z ModuleNotFoundError: No module named 'diffusers'`
> 
> So you seem to be missing dependencies.
> 
> Are you running the webui using the provided `webui-user-dreambooth.sh`? That should normally trigger the installation of necessary dependencies.

Thank you for your suggest, the issue was solved

**Comment by LEv145** [comment]
I use https://github.com/AbdBarho/stable-diffusion-webui-docker and I get the same error

I use `environment` from `webui-user-dreambooth.sh` in `docker-compose`:
```py
    environment:
      - COMMANDLINE_ARGS=""
      - XFORMERS_PACKAGE="xformers==0.0.17.dev447"
      - REQS_FILE="/stable-diffusion-webui/extensions/sd_dreambooth_extension/requirements.txt"
```
But it doesn't solve the problem


But I found a solution, maybe it will be useful:
https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/Usage#extensions
