### ISSUE TITLE
Dreambooth tap grayed out and sd_dreambooth_extension fails to check for updates

### ISSUE THREAD

**Issue by armmine** [d8ahazard/sd_dreambooth_extension#1049]
### Kindly read the entire form below and fill it out with the requested information.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your
issue will be automatically closed._**

`
Python revision: 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Dreambooth revision: bff61c6b92b79ece2e140ee240e0628dd9a4ebef
SD-WebUI revision: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
[+] accelerate version 0.16.0 installed.
[+] bitsandbytes version 0.35.4 installed.
[+] diffusers version 0.13.1 installed.
[+] transformers version 4.26.1 installed.
[+] xformers version 0.0.17.dev464 installed.

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
YES
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
YES
**Have you updated Dreambooth to the latest revision?**
I can't
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
YES

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**
OK

**Describe the bug**
All buttons in the Dreambooth tap in SD-webui are grayed out. 
sd_dreambooth_extension fails to check for updates

**Provide logs**
Error checking updates for sd_dreambooth_extension:
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\ui_extensions.py", line 66, in check_updates
    ext.check_updates()
  File "D:\stable-diffusion-webui\modules\extensions.py", line 69, in check_updates
    for fetch in repo.remote().fetch("--dry-run"):
  File "D:\stable-diffusion-webui\venv\lib\site-packages\git\remote.py", line 1015, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress, kill_after_timeout=kill_after_timeout)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\git\remote.py", line 854, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\git\cmd.py", line 604, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v -- origin --dry-run
  stderr: 'fatal: couldn't find remote ref --dry-run'

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *
before* the crash occurred.

**Environment**

What OS?
Windows 10
If Windows - WSL or native?
Don't know
What GPU are you using?
1070ti

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the
db_config.json file from /models/dreambooth/MODELNAME/db_config.json

**Comment by ArrowM** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/8118 has been merged
