### ISSUE TITLE
No module named 'dreambooth'

### ISSUE THREAD

**Issue by yoshikizh** [d8ahazard/sd_dreambooth_extension#1051]
when I started the webui.bat
tip failed to install Dreambooth requirement, but below all installed

Checking Dreambooth requirements...
**Failed** to install Dreambooth requirements.
- [+] torch version 1.13.1+cu117 installed.
- [+] torchvision version 0.14.1+cu117 installed.
- [+] accelerate version 0.16.0 installed.
- [+] bitsandbytes version 0.35.4 installed.
- [+] diffusers version 0.13.1 installed.
- [+] transformers version 4.26.1 installed.
- [+] xformers version 0.0.17.dev464 installed.

Although it prompts an error, I can continue to use
However, the worrying thing still happened When I am trainning Lora

Model dir set to: D:\web\stable-diffusion-webui-master\full-download\stable-diffusion-webui(1)\stable-diffusion-webui\models\dreambooth\zhangweibo
Model dir set to: D:\web\stable-diffusion-webui-master\full-download\stable-diffusion-webui(1)\stable-diffusion-webui\models\dreambooth\zhangweibo
Initializing dreambooth training...
Traceback (most recent call last):
  File "D:\web\stable-diffusion-webui-master\full-download\stable-diffusion-webui(1)\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\ui_functions.py", line 678, in start_training
    from extensions.sd_dreambooth_extension.dreambooth.train_dreambooth import main  # noqa
  File "D:\web\stable-diffusion-webui-master\full-download\stable-diffusion-webui(1)\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 23, in <module>
    from tensorflow.python.framework.random_seed import set_seed as set_seed1
  File "D:\web\stable-diffusion-webui-master\full-download\stable-diffusion-webui(1)\stable-diffusion-webui\venv\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
ModuleNotFoundError: No module named 'tensorflow.python'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\web\stable-diffusion-webui-master\full-download\stable-diffusion-webui(1)\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\ui_functions.py", line 680, in start_training
    from dreambooth.dreambooth.train_dreambooth import main  # noqa
ModuleNotFoundError: No module named 'dreambooth'
Restored system models.

**Comment by Arilziem** [comment]
Try launching with webui-user-dreambooth.bat (copy it from the extension dir into main folder)

**Comment by gammagoat** [comment]
The real error is "ModuleNotFoundError: No module named 'tensorflow.python'". You do not have tensorflow installed in your venv.

The dreambooth.dreambooth error is just a oddity that happen when another import error occurs because of the current code structure.

**Comment by PuDood** [comment]
> 真正的错误是“ModuleNotFoundError：没有名为'tensorflow.python'的模块”。您的venv中没有安装张量流。
> 
> dreambooth.dreambooth 错误只是由于当前代码结构而发生另一个导入错误时发生的奇怪情况。

My error code is：Error executing callback ui_tabs_callback for F:\stable-diffusion-webui_23-03-10\extensions\sd_dreambooth_extension\scripts\main.py
Traceback (most recent call last):
  File "F:\stable-diffusion-webui_23-03-10\modules\script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "F:\stable-diffusion-webui_23-03-10\extensions\sd_dreambooth_extension\scripts\main.py", line 673, in on_ui_tabs
    change_log = gr.HTML(format_updates(), elem_id="change_log")
  File "F:\stable-diffusion-webui_23-03-10\extensions\sd_dreambooth_extension\scripts\main.py", line 651, in format_updates
    updates = check_updates()
  File "F:\stable-diffusion-webui_23-03-10\extensions\sd_dreambooth_extension\helpers\version_helper.py", line 58, in check_updates
    current = current_revision()
  File "F:\stable-diffusion-webui_23-03-10\extensions\sd_dreambooth_extension\helpers\version_helper.py", line 19, in current_revision
    return subprocess.run(['git', 'rev-parse', 'HEAD'], cwd=shared.extension_path, capture_output=True,
  File "F:\stable-diffusion-webui_23-03-10\python\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "F:\stable-diffusion-webui_23-03-10\python\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "F:\stable-diffusion-webui_23-03-10\python\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

The problem is that there is no dreamroom display card

**Comment by PuDood** [comment]
> Try launching with webui-user-dreambooth.bat (copy it from the extension dir into main folder)尝试使用webui-user-dreambooth.bat启动（将其从扩展目录复制到主文件夹）

report errors：Couldn't launch python  exit code: 9009

**Comment by Arilziem** [comment]
@PuDood You seem to be having a different issue. I don't think it's a bug but rather a problem with the installation, but if you need assistance, you can create a new topic in 'Discussion', with a full startup log. Thank you

**Comment by PuDood** [comment]
> @PuDood You seem to be having a different issue. I don't think it's a bug but rather a problem with the installation, but if you need assistance, you can create a new topic in 'Discussion', with a full startup log. Thank you @PuDood 您似乎遇到了不同的问题。我不认为这是一个错误，而是安装的问题，但如果你需要帮助，你可以在“讨论”中创建一个新的主题，并提供完整的启动日志。谢谢

It has been solved by chat gpt. Here is my complete error reporting code and solution:[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
Script path is F:\stable-diffusion-webui_23-03-10(1)\stable-diffusion-webui_23-03-10
Loading weights [89d59c3dde] from F:\stable-diffusion-webui_23-03-10(1)\stable-diffusion-webui_23-03-10\models\Stable-diffusion\final-pruned.ckpt
Creating model from config: F:\stable-diffusion-webui_23-03-10(1)\stable-diffusion-webui_23-03-10\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights found near the checkpoint: F:\stable-diffusion-webui_23-03-10(1)\stable-diffusion-webui_23-03-10\models\Stable-diffusion\final-pruned.vae.pt
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0):
Model loaded in 3.8s (load weights from disk: 1.3s, create model: 0.4s, apply weights to model: 0.7s, apply half(): 0.7s, load VAE: 0.6s).
'"git"' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'"git"' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Error executing callback ui_tabs_callback for F:\stable-diffusion-webui_23-03-10(1)\stable-diffusion-webui_23-03-10\extensions\openOutpaint-webUI-extension\scripts\main.py
Traceback (most recent call last):
  File "F:\stable-diffusion-webui_23-03-10(1)\stable-diffusion-webui_23-03-10\extensions\openOutpaint-webUI-extension\scripts\main.py", line 64, in add_tab
    update_app()
  File "F:\stable-diffusion-webui_23-03-10(1)\stable-diffusion-webui_23-03-10\extensions\openOutpaint-webUI-extension\scripts\main.py", line 55, in update_app
    run(f'"{git}" -C "' + os.path.join(scripts.basedir(), usefulDirs[0], usefulDirs[1]) +
  File "F:\stable-diffusion-webui_23-03-10(1)\stable-diffusion-webui_23-03-10\launch.py", line 97, in run
    raise RuntimeError(f"""{errdesc or 'Error running command'}.
RuntimeError: Error running command.
Command: "git" -C "F:\stable-diffusion-webui_23-03-10(1)\stable-diffusion-webui_23-03-10\extensions\openOutpaint-webUI-extension" submodule update --init --recursive --remote
Error code: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\stable-diffusion-webui_23-03-10(1)\stable-diffusion-webui_23-03-10\modules\script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "F:\stable-diffusion-webui_23-03-10(1)\stable-diffusion-webui_23-03-10\extensions\openOutpaint-webUI-extension\scripts\main.py", line 66, in add_tab
    update_app()
  File "F:\stable-diffusion-webui_23-03-10(1)\stable-diffusion-webui_23-03-10\extensions\openOutpaint-webUI-extension\scripts\main.py", line 55, in update_app
    run(f'"{git}" -C "' + os.path.join(scripts.basedir(), usefulDirs[0], usefulDirs[1]) +
  File "F:\stable-diffusion-webui_23-03-10(1)\stable-diffusion-webui_23-03-10\launch.py", line 97, in run
    raise RuntimeError(f"""{errdesc or 'Error running command'}.
RuntimeError: Error running command.
Command: "git" -C "F:\stable-diffusion-webui_23-03-10(1)\stable-diffusion-webui_23-03-10\extensions\openOutpaint-webUI-extension" submodule update --init --recursive --remote
Error code: 1

Error executing callback ui_tabs_callback for F:\stable-diffusion-webui_23-03-10(1)\stable-diffusion-webui_23-03-10\extensions\sd_dreambooth_extension\scripts\main.py
Traceback (most recent call last):
  File "F:\stable-diffusion-webui_23-03-10(1)\stable-diffusion-webui_23-03-10\modules\script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "F:\stable-diffusion-webui_23-03-10(1)\stable-diffusion-webui_23-03-10\extensions\sd_dreambooth_extension\scripts\main.py", line 673, in on_ui_tabs
    change_log = gr.HTML(format_updates(), elem_id="change_log")
  File "F:\stable-diffusion-webui_23-03-10(1)\stable-diffusion-webui_23-03-10\extensions\sd_dreambooth_extension\scripts\main.py", line 651, in format_updates
    updates = check_updates()
  File "F:\stable-diffusion-webui_23-03-10(1)\stable-diffusion-webui_23-03-10\extensions\sd_dreambooth_extension\helpers\version_helper.py", line 58, in check_updates
    current = current_revision()
  File "F:\stable-diffusion-webui_23-03-10(1)\stable-diffusion-webui_23-03-10\extensions\sd_dreambooth_extension\helpers\version_helper.py", line 19, in current_revision
    return subprocess.run(['git', 'rev-parse', 'HEAD'], cwd=shared.extension_path, capture_output=True,
  File "F:\stable-diffusion-webui_23-03-10(1)\stable-diffusion-webui_23-03-10\python\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "F:\stable-diffusion-webui_23-03-10(1)\stable-diffusion-webui_23-03-10\python\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "F:\stable-diffusion-webui_23-03-10(1)\stable-diffusion-webui_23-03-10\python\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

Image Browser: Database upgraded from version 5 to version 6
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 30.5s (import gradio: 3.7s, import ldm: 4.3s, other imports: 2.2s, list extensions: 1.9s, setup codeformer: 0.1s, load scripts: 4.1s, load SD checkpoint: 4.0s, create ui: 9.8s, gradio launch: 0.4s).

The answer to chat GPT: This error usually appears in Windows system. It indicates that your operating system cannot find the Git command. This may be because you have not installed Git correctly or there is no location for adding Git commands in your system path.
To fix this problem, you can try the following steps:
Check that Git is installed correctly. You can find the git.exe file in the Git installation directory. For example, by default, it is usually installed in C:  Program Files  Git or C:  Program Files (x86)  Git.
If Git is installed correctly, ensure that the location of Git has been added to the system path. You can add a path as follows:
Enter "Environment variables" in the Windows search bar and select "Edit system environment variables".
In the pop-up "System Properties" window, select the "Advanced" tab and click the "Environment Variables" button.
In the System Variables window, find the variable named Path and select the Edit button.
In the Edit Environment Variables window, select the New button and add the path where the Git command is located. For example, by default, it is usually C:  Program Files  Git  bin.
If Git is not installed correctly, please reinstall Git and ensure that the correct installation option is selected.
After completing the above steps, you should be able to use the Git command in the command line

**Comment by haitao1235** [comment]
Web UI no deram booth

**Comment by highjohnconquer** [comment]
Hi,

I've been having this issue as well. This appears within the UI: No module named 'tensorflow.python.framework.random_seed

I copied the bat file into the main drive

I've reinstalled several times.
