### ISSUE TITLE
can't create model

### ISSUE THREAD

**Issue by amandafanny** [d8ahazard/sd_dreambooth_extension#1064]
### Kindly read the entire form below and fill it out with the requested information.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your
issue will be automatically closed._**

`
Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Commit hash: ****************************************
Installing requirements for Web UI
Skipping dreambooth installation.
Dreambooth revision is ****************************************
Diffusers version is *.*.*.
Torch version is *.*.*.
Torch vision version is *.*.*.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**

**Have you updated Dreambooth to the latest revision?**

**Have you updated the Stable-Diffusion-WebUI to the latest version?**

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**

**Describe the bug**

(A clear and concise description of what the bug is)

**Provide logs**

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *
before* the crash occurred.

**Environment**

What OS?
colab
<img width="472" alt="image" src="https://user-images.githubusercontent.com/54808661/224604966-f55e5de9-3cef-428c-9183-df7a3dc07c30.png">

```
/content# uname
Linux
```
If Windows - WSL or native?

What GPU are you using?

```
/content# nvidia-smi
Mon Mar 13 04:14:01 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   51C    P0    25W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the
db_config.json file from /models/dreambooth/MODELNAME/db_config.json

error in  colab
```
No model name.
Model dir set to: models/dreambooth/f22 demo
Loading model from checkpoint.
Loading ckpt...
Pred and size are epsilon and 512, using config: /content/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/../configs/v1-training-default.yaml
v1 model loaded.
Trying to load: /content/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/../configs/v1-training-default.yaml
Converting unet...
```

**Comment by yuan6785** [comment]
memory limit, it's killed;    you need download from huggingface

**Comment by 78Alpha** [comment]
Could be semi-related to what I have been encountering, but it provides an error after the Converting Unet line.

```
Exception setting up output: 'model_ema.diffusion_modelinput_blocks00bias'
Traceback (most recent call last):
  File "H:\Utilities\CUDA\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\sd_to_diff.py", line 1208, in extract_checkpoint
    converted_unet_checkpoint, converted_ema_checkpoint = convert_ldm_unet_checkpoint(
  File "H:\Utilities\CUDA\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\sd_to_diff.py", line 323, in convert_ldm_unet_checkpoint
    ema_state_dict[key.replace(unet_key, "")] = checkpoint.pop(flat_ema_key)
KeyError: 'model_ema.diffusion_modelinput_blocks00bias'
Missing model directory, removing model: H:\Utilities\CUDA\stable-diffusion-webui\models\dreambooth\EpsilonBaseV1\working\unet
```

**Comment by ArrowM** [comment]
It's probably what yuan6785 said and not 78Alpha's issue. I bet you are hitting a memory limit or some quirk of google-collab.
