### ISSUE TITLE
memory error

### ISSUE THREAD

**Issue by yggdrasil75** [d8ahazard/sd_dreambooth_extension#1065]
### Kindly read the entire form below and fill it out with the requested information.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your
issue will be automatically closed._**

`
#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Dreambooth revision:
SD-WebUI revision:

Checking Dreambooth requirements...
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
[+] bitsandbytes version 0.35.4 installed.
[+] diffusers version 0.13.1 installed.
[+] transformers version 4.26.1 installed.
[+] xformers version 0.0.17.dev464 installed.

#######################################################################################################
![image](https://user-images.githubusercontent.com/17131496/224728572-c24b4a15-370b-4c92-ad3b-9a416efd465d.png)
it really didnt show the revision. might need another bug report for that alone though.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?** yep

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?** yep, twice

**Have you updated Dreambooth to the latest revision?** yep

**Have you updated the Stable-Diffusion-WebUI to the latest version?**

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**

**Describe the bug**
cant save model when training
(A clear and concise description of what the bug is)

When training, I reached 5 epoches (where I have it set to save) and get this error. the model does not complete saving.

**Provide logs**

Exception compiling checkpoint:                                                                                                                                                                                       | 0/3 [00:00<?, ?it/s]
Traceback (most recent call last):                                                                                                                                                                                 | 0/2306 [00:00<?, ?it/s]
  File "D:\creations\imagetraining\automatic\extensions\sd_dreambooth_extension\dreambooth\diff_to_sd.py", line 491, in compile_checkpoint
    safetensors.torch.save_file(safe_dict, checkpoint_path, json_dict)
  File "D:\creations\imagetraining\automatic\venv\lib\site-packages\safetensors\torch.py", line 71, in save_file
    serialize_file(_flatten(tensors), filename, metadata=metadata)
  File "D:\creations\imagetraining\automatic\venv\lib\site-packages\safetensors\torch.py", line 236, in _flatten
    return {
  File "D:\creations\imagetraining\automatic\venv\lib\site-packages\safetensors\torch.py", line 240, in <dictcomp>
    "data": _tobytes(v, k),
  File "D:\creations\imagetraining\automatic\venv\lib\site-packages\safetensors\torch.py", line 210, in _tobytes
    return data.tobytes()
MemoryError

**Environment**

What OS? windows 10

If Windows - WSL or native? native

What GPU are you using? 3090 and 1080 ti with accelerator enabled (appears to only use the 3090)

**Comment by Arilziem** [comment]
How much system RAM do you have, and how much of that is free when this happens? Can you please add your training settings? Ideally the text content of db_config.json

>  it really didnt show the revision. might need another bug report for that alone though.
I assume you downloaded a .zip from releases?

**Comment by yggdrasil75** [comment]
[db_config](https://gist.github.com/yggdrasil75/00a2f181f11e729916795f0183bea56b)
I have 96gb system ram.
I did not download a zip from release, I used git clone initially, and then later used the update extension button in testing.

**Comment by Arilziem** [comment]
Ok that is odd.

Since I have seen issues with this, can you try disabling saving the diffusion weight snapshots? `Saving > Diffusion weights` at the bottom, remove all checkboxes, save settings and then try again?

**Comment by yggdrasil75** [comment]
alright, this might partially be a system issue: does the included libraries support multiple numa nodes?

**Comment by Arilziem** [comment]
> but given that this is what allows resuming midway through a training session, does that not mean that resuming is no longer an option?

No, the weights will be saved regardless, so training can be resumed. Snapshots are just a way to save intermediate states, which allows you to roll back to a previous version if necessary.

> alright, this might partially be a system issue: does the included libraries support multiple numa nodes?

I don't know. PyTorch apparently supports it, but I don't think running multiple instances of the webui concurrently is a thing. Don't know anything about it, but given the issues here my guess would be that it can only access local memory? Quick search brought up [this](https://www.intel.com/content/www/us/en/developer/articles/technical/how-to-get-better-performance-on-pytorchcaffe2-with-intel-acceleration.html), so maybe there is a configuration thing you can do with `numactl --membind`? Or not using membind? Sorry, never dealt with numa before. But if you end up having 32 GB or less for one node that could well be it.

**Comment by yggdrasil75** [comment]
I will try that and run a few tests again. hopefully its some simple numa setting. will reply with results in the morning.

**Comment by yggdrasil75** [comment]
alright, I have tested that with wsl, and I also found that I had too small of a pagefile. fixing both of those and it saves properly. this probably could be closed since its a system issue, unique to my setup, but for those who have similar issues:
make sure numa is set for shared memory and that your pagefile is set to a large number or automatic.
