### ISSUE TITLE
Training: NameError: name 'str2optimizer32bit' is not defined

### ISSUE THREAD

**Issue by gmod64bit** [d8ahazard/sd_dreambooth_extension#1067]
```
Traceback (most recent call last):
  File "/home/shane/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 681, in start_training
    result = main(use_txt2img=use_txt2img)
  File "/home/shane/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1148, in main
    return inner_loop()
  File "/home/shane/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 123, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "/home/shane/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1034, in inner_loop
    optimizer.step()
  File "/home/shane/stable-diffusion-webui/venv/lib/python3.10/site-packages/accelerate/optimizer.py", line 134, in step
    self.scaler.step(self.optimizer, closure)
  File "/home/shane/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 341, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "/home/shane/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 288, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
  File "/home/shane/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 68, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/shane/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/optim/optimizer.py", line 140, in wrapper
    out = func(*args, **kwargs)
  File "/home/shane/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/shane/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py", line 265, in step
    self.update_step(group, p, gindex, pindex)
  File "/home/shane/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/shane/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py", line 458, in update_step
    F.optimizer_update_32bit(
  File "/home/shane/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/functional.py", line 658, in optimizer_update_32bit
    if optimizer_name not in str2optimizer32bit:
NameError: name 'str2optimizer32bit' is not defined
Steps:   0%|                                                      | 0/10700 [00:01<?, ?it/s]
Restored system models.

```

Arch Linux
Nvidia 2080ti

**Comment by yuan6785** [comment]
i slove this problem by  modify  sd_dreambooth_extension/requirements.txt
bitsandbytes==0.35.4  modify for   bitsandbytes-cuda111==0.26.0.post2

**Comment by venshine** [comment]
> i slove this problem by modify sd_dreambooth_extension/requirements.txt bitsandbytes==0.35.4 modify for bitsandbytes-cuda111==0.26.0.post2 restart webui , i'm ubuntu

It's well for me.

**Comment by liuyixin-louis** [comment]
bitsandbytes==0.35.4 works for me!
