### ISSUE TITLE
Unable to train with models created by extension

### ISSUE THREAD

**Issue by 78Alpha** [d8ahazard/sd_dreambooth_extension#1068]
### Kindly read the entire form below and fill it out with the requested information.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your
issue will be automatically closed._**

`
Python revision: 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Dreambooth revision: bff61c6b92b79ece2e140ee240e0628dd9a4ebef
SD-WebUI revision: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8

[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
[+] accelerate version 0.16.0 installed.
[+] bitsandbytes version 0.35.4 installed.
[+] diffusers version 0.13.1 installed.
[+] transformers version 4.26.1 installed.
[+] xformers version 0.0.17.dev464 installed.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**

Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**

Yes

**Have you updated Dreambooth to the latest revision?**

Yes (Reverted to older versions as well)

**Have you updated the Stable-Diffusion-WebUI to the latest version?**

Yes (reverted versions as well)

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**

OK

**Describe the bug**

Attempting to "Create Model" using a model trained with the extension fails.

**Provide logs**

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *
before* the crash occurred.

```
Converting unet...
Exception setting up output: 'model_ema.diffusion_modelinput_blocks00bias'
Traceback (most recent call last):
  File "H:\Utilities\CUDA\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\sd_to_diff.py", line 1208, in extract_checkpoint
    converted_unet_checkpoint, converted_ema_checkpoint = convert_ldm_unet_checkpoint(
  File "H:\Utilities\CUDA\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\sd_to_diff.py", line 323, in convert_ldm_unet_checkpoint
    ema_state_dict[key.replace(unet_key, "")] = checkpoint.pop(flat_ema_key)
KeyError: 'model_ema.diffusion_modelinput_blocks00bias'
Missing model directory, removing model: H:\Utilities\CUDA\stable-diffusion-webui\models\dreambooth\EpsilonBaseV1\working\unet
```

**Environment**

What OS?

WIndows

If Windows - WSL or native?

Native

What GPU are you using?

RTX 3090

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the
db_config.json file from /models/dreambooth/MODELNAME/db_config.json

N/A

**Comment by Eugeoter** [comment]
I met the same problem as you and I am also troubled by this. I don't know how to solve. :D

**Comment by Arilziem** [comment]
Does txt2img inference work with the model?

**Comment by ArrowM** [comment]
Your source model is probably messed up, do you have a link to the source?

**Comment by RLArt2022** [comment]
https://civitai.com/models/6424/chilloutmix I think that was the one I was tryin to train on last time

**Comment by ArrowM** [comment]
@78Alpha Please verify which model you actually had the issue with and post a link to the exact model. (It's impossible to troubleshoot without that). I checked a couple of the ema chillout models and they were missing the ema keys, which is weird. Please also include more of the console log (the part above what you sent).

**Comment by 78Alpha** [comment]
@ArrowM 

**Source model:** [](https://huggingface.co/Linaqruf/anything-v3.0) (Originally Trained from)
**Model Trained:** Dark-Skinned_87616.ckpt (non-remote model)
**Failed to Extract Models:** Dark-Skinned_87616.safetensors, Dark-Skinned_87616.ckpt

Source model was manually downloaded when it was a CKPT and have been extracting from that. I have never used the HUB option. This was my first time trying to train a model for a second cycle. The model that failed to Extract was the model that was trained with the extension (Dark-Skinned_87616). Other trained models have had the same issue.

Full output of a second attempt
```
venv "H:\Utilities\CUDA\stable-diffusion-webui\venv\Scripts\Python.exe"
Checking for accelerate
Accelerating
Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Commit hash: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2


#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Dreambooth revision: bff61c6b92b79ece2e140ee240e0628dd9a4ebef
SD-WebUI revision: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2

[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
[+] accelerate version 0.16.0 installed.
[+] bitsandbytes version 0.35.4 installed.
[+] diffusers version 0.13.1 installed.
[+] transformers version 4.26.1 installed.
[+] xformers version 0.0.17.dev464 installed.

#######################################################################################################

Launching Web UI with arguments: --deepdanbooru --xformers --no-half-vae --autolaunch --disable-nan-check --ckpt-dir I:CKPTModels --disable-safe-unpickle --vae-dir A:\CKPT\VAE --opt-channelslast
Script path is H:\Utilities\CUDA\stable-diffusion-webui
Loading weights [e41422ed6a] from I:CKPTModels\ZoeEpsilonV11_4500 + 0.5(0.5(Dark-Skinned_87616) + 0.5(EpsilonBaseV3_267008) - Anything-V3.0).ckpt
Creating model from config: I:CKPTModels\ZoeEpsilonV11_4500 + 0.5(0.5(Dark-Skinned_87616) + 0.5(EpsilonBaseV3_267008) - Anything-V3.0).yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: A:\CKPT\VAE\Anything-V3.0.vae.pt
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0):
Model loaded in 19.8s (load weights from disk: 15.7s, create model: 0.3s, apply weights to model: 0.5s, apply channels_last: 0.5s, apply half(): 0.5s, load VAE: 0.9s, move model to device: 0.6s, load textual inversion embeddings: 0.8s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 43.1s (import gradio: 1.1s, import ldm: 4.7s, other imports: 5.1s, list extensions: 0.3s, list SD models: 1.6s, setup codeformer: 0.2s, load scripts: 4.1s, load SD checkpoint: 19.9s, create ui: 5.9s, gradio launch: 0.2s).
Model dir set to: H:\Utilities\CUDA\stable-diffusion-webui\models\dreambooth\EpsilonBaseDBV1
Loading model from checkpoint.
Loading ckpt...
Pred and size are epsilon and 512, using config: H:\Utilities\CUDA\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\..\configs\v1-training-unfrozen.yaml
v1 model loaded.
Trying to load: H:\Utilities\CUDA\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\..\configs\v1-training-unfrozen.yaml
Converting unet...
Checkpoint I:CKPTModels\Anything-V3.0.ckpt has both EMA and non-EMA weights.
Saving EMA unet.
Converting vae...
Converting text encoder...
Saving text_encoder
Saving tokenizer
Checkpoint successfully extracted to H:\Utilities\CUDA\stable-diffusion-webui\models\dreambooth\EpsilonBaseDBV1\working
Restored system models.
Model dir set to: H:\Utilities\CUDA\stable-diffusion-webui\models\dreambooth\EpsilonBaseDBV1Step2
Loading model from checkpoint.
Loading ckpt...
Pred and size are epsilon and 512, using config: H:\Utilities\CUDA\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\..\configs\v1-training-unfrozen.yaml
v1 model loaded.
Trying to load: I:CKPTModels\Dark-Skinned\Dark-Skinned_87616.yaml
Converting unet...
Checkpoint I:CKPTModels\Dark-Skinned\Dark-Skinned_87616.ckpt has both EMA and non-EMA weights.
Exception setting up output: 'model_ema.diffusion_modelinput_blocks00bias'
Traceback (most recent call last):
  File "H:\Utilities\CUDA\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\sd_to_diff.py", line 1208, in extract_checkpoint
    converted_unet_checkpoint, converted_ema_checkpoint = convert_ldm_unet_checkpoint(
  File "H:\Utilities\CUDA\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\sd_to_diff.py", line 323, in convert_ldm_unet_checkpoint
    ema_state_dict[key.replace(unet_key, "")] = checkpoint.pop(flat_ema_key)
KeyError: 'model_ema.diffusion_modelinput_blocks00bias'
Missing model directory, removing model: H:\Utilities\CUDA\stable-diffusion-webui\models\dreambooth\EpsilonBaseDBV1Step2\working\unet
Restored system models.
```

**Comment by 78Alpha** [comment]
> @78Alpha the ckpt form of AnythingV3 is no longer available on that repo. Could you please try downloading and extracting one of the safetensor versions of AnythingV3 and report back?

The reference to anything V3 was that it was the base model used to train Dark skin. I updated my other reply.

The CKPT Anything extracts fine, but the models that are trained with the extension are having the extraction issue.

I can try retraining the model on one of the different AnythingV3's tonight.

**Comment by ArrowM** [comment]
> but the models that are trained with the extension are having the extraction issue.

ahh, I didn't understand this is what you meant before. I'll try to look into it

**Comment by LazyCat420** [comment]
I'm having the same issue with models i trained on 1.5 stable diffusion. I wanted to unfreeze the models and train on them again and got the same error about the missing unet dictionary. Didn't have this issue with ckpt only now with safetensor models. How can we save the files as ckpt instead of safe tensors in the dream booth extension?

**Comment by rodrigo-barraza** [comment]
I noticed that you cannot train as CKPTs anymore, only SAFETENSORs, and with this change, we cannot unfreeze the model to train any longer. I have ran into many people with the same issue. What is going on? How can we train as CKPTs, since it's obvious SAFETENSORs aren't working for this.

**Comment by rodrigo-barraza** [comment]
Alright, after spending two days training, and discovering I can't even unfreeze my model (or do much anything else with it), I looked into the code and this is how you fix it for anyone else interested:

Inside `sd_dreambooth_extension` go into `scripts` and open `main.py`.
Go to line `430`
Change the `value` of this line to `False`, and `visible` to `True`:
`db_save_safetensors = gr.Checkbox(label="Save in .safetensors format", value=True, visible=True)`

I'm not sure why this would be disabled in the UI, forcing everyone to use Safetensors when the functionality hasn't even been tested properly. Could you guys, PLEASE, not hide these types of options from the UI, that might break user-functionality? Thanks.

**Comment by ArrowM** [comment]
@rodrigo-barraza if the replacement of safetensors with ckpts is an issues both you and others have run into, a separate issue should be opened.

ckpt was replace with safetensor because of the security benefits of the newer format. To the best of my knowledge, they provide the exact same functionality. If you have any resources stating otherwise, (for example that ckpts can be unfrozen and safetensors cannot), please provide them.

From the feedback I've received, safetensors are working for the vast majority of users. If you are having issues with safetensors, please open an issue with as many details as possible like the exact model, environment details, and stacktraces.

**Comment by ArrowM** [comment]
Also, as a sanity check - I redownloaded https://huggingface.co/runwayml/stable-diffusion-v1-5/blob/main/v1-5-pruned.safetensors and created a Dreambooth model from it with `Extract EMA Weights` and `Unfreeze Model` checked. Both worked fine. So again, please continue to provide more details so we can debug these outlier issues.

**Comment by 78Alpha** [comment]
I converted the safetensor to CKPT and still had the same issue.

Other safetensor models extracted alright, ones not made by the extension or merged with base models.

**Comment by ArrowM** [comment]
@78Alpha I downloaded the trained model you posted and was able to reproduce the error, yay! I think I have an idea of what the issue is. Investigating rn....

**Comment by rodrigo-barraza** [comment]
@ArrowM Enabling/disabling it from the UI isn't an issue, it's a feature that was disabled on purpose, and even though there are security issues with ckpts (which 99.9% of people haven't experienced), this should not mean that the functionality should be hidden for those that wish to use it. Having messaging about the potential danger is how it should be done, rather than restrict user-functionality, especially when things haven't been tested properly.

Everyone is having issues converting safetensors to ckpts, which when done, the CKPT is still smaller than a native ckpt by about 600MB, which is very odd, as it's almost 20% of the native file size.

Details have already been provided in this thread, and is very easy to reproduce if following what others have mentioned in this thread.

**Comment by ArrowM** [comment]
@rodrigo-barraza we are discouraging the use of ckpt due to security concerns (as are most stable diffusion projects atm). We plan to keep ckpt deprecated, but the code is open source, so users are free to re-enable it like you have. Additionally, safetensor files should be the same size as ckpt when converted properly.

@78Alpha @LazyCat420 Alright, I think I fixed it with #1073. Please update your extension and let me know how it goes.

**Comment by ArrowM** [comment]
Excellent.

**Comment by TidusZanarkand** [comment]
Just follow the steps on " IF YOU ARE HAVING ISSUES WITH REQUIREMENTS AFTER INSTALLING, LOOK BELOW", on https://github.com/d8ahazard/sd_dreambooth_extension

**Comment by le-khang** [comment]
> Excellent.

I have encountered the same problem of a "Missing model directory..." error, despite having installed the latest version of Dreambooth. I have tried using multiple checkpoints and discovered that some checkpoints work while others don't. For instance, the oldest version of the aEros checkpoint (pruned version) works fine, but the two newer versions (noVAE version) produce the same error again. You can find these 3 checkpoints at https://civitai.com/models/3950/art-and-eros-aeros-a-tribute-to-beauty (below the name)
