### ISSUE TITLE
Incorrect version of xformers installed.Incorrect version of accelerate installed.

### ISSUE THREAD

**Issue by zsw667291** [d8ahazard/sd_dreambooth_extension#1077]
when I started the webui.bat
tip failed to install Dreambooth requirement, how can i do?
my env is win10 3080 cuda 11.7,torch 1.13.1

```st
Already up to date.
venv "D:\programs\Diffusion\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2
Installing requirements for Web UI
Base dir (auto1111) is: D:\programs\Diffusion\stable-diffusion-webui from D:\programs\Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\install.py
Ext dir already in path? D:\programs\Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension
['D:\\programs\\Diffusion\\stable-diffusion-webui\\repositories\\k-diffusion', 'D:\\programs\\Diffusion\\stable-diffusion-webui\\venv\\lib\\site-packages\\git\\ext\\gitdb', 'D:\\programs\\Diffusion\\stable-diffusion-webui', 'D:\\programs\\Diffusion\\stable-diffusion-webui\\extensions\\sd_dreambooth_extension', 'D:\\programs\\Diffusion\\stable-diffusion-webui', 'D:\\envs\\Python\\py_3.10.6\\python310.zip', 'D:\\envs\\Python\\py_3.10.6\\DLLs', 'D:\\envs\\Python\\py_3.10.6\\lib', 'D:\\envs\\Python\\py_3.10.6', 'D:\\programs\\Diffusion\\stable-diffusion-webui\\venv', 'D:\\programs\\Diffusion\\stable-diffusion-webui\\venv\\lib\\site-packages', 'D:\\programs\\Diffusion\\stable-diffusion-webui\\repositories\\stable-diffusion-stability-ai', 'D:\\programs\\Diffusion\\stable-diffusion-webui\\repositories\\taming-transformers', 'D:\\programs\\Diffusion\\stable-diffusion-webui\\repositories\\CodeFormer', 'D:\\programs\\Diffusion\\stable-diffusion-webui\\repositories\\BLIP']

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: 8e7277b7ec30801753e3591e0e1139b97ec88e56
SD-WebUI revision:

Checking Dreambooth requirements...
Failed to install Dreambooth requirements.
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
[!] xformers version 0.0.16rc425 installed.
[!] accelerate version 0.12.0 installed.
[!] bitsandbytes NOT installed.
[!] diffusers NOT installed.
[!] transformers version 4.25.1 installed.
Launch errors detected:
Incorrect version of xformers installed.
Incorrect version of accelerate installed.
bitsandbytes not installed.
diffusers not installed.
Incorrect version of transformers installed.

#######################################################################################################

Launching Web UI with arguments: --xformers
Exception importing api
Traceback (most recent call last):
  File "D:\programs\Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\api.py", line 27, in <module>
    from dreambooth.dataclasses.db_config import from_file, DreamboothConfig
  File "D:\programs\Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dataclasses\db_config.py", line 10, in <module>
    from dreambooth.utils.image_utils import get_scheduler_names  # noqa
  File "D:\programs\Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\utils\image_utils.py", line 11, in <module>
    from diffusers.schedulers import KarrasDiffusionSchedulers
ModuleNotFoundError: No module named 'diffusers'
Error loading script: main.py
Traceback (most recent call last):
  File "D:\programs\Diffusion\stable-diffusion-webui\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\programs\Diffusion\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\programs\Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py", line 7, in <module>
    from dreambooth.dataclasses.db_config import (
  File "D:\programs\Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dataclasses\db_config.py", line 10, in <module>
    from dreambooth.utils.image_utils import get_scheduler_names  # noqa
  File "D:\programs\Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\utils\image_utils.py", line 11, in <module>
    from diffusers.schedulers import KarrasDiffusionSchedulers
ModuleNotFoundError: No module named 'diffusers'

Loading weights [6ce0161689] from D:\programs\Diffusion\stable-diffusion-webui\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Creating model from config: D:\programs\Diffusion\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0):
Model loaded in 3.0s (create model: 0.3s, apply weights to model: 0.6s, apply half(): 0.6s, move model to device: 0.6s, load textual inversion embeddings: 0.7s).
Running on local URL:  http://127.0.0.1:7860
```

**Comment by ArrowM** [comment]
Please follow the issue template on the future. We are starting to be more strict with that. 

A1111 should have automatically installed those libraries as part of the startup process. However, if it didn't, you can follow either of the methods suggested by VeganMooseMeat.

Alternatively you could run this from the project base
```
. /venv/Scripts/activate
pip install -r ./extensions/sd_dreambooth_extension/requirements.txt`

**Comment by ArrowM** [comment]
Oh yeah, if you want to use xformers as the training memory attention you need to update it to a minimum version of 0.0.17.

We are still working out the quirks of how to handle the xformers install
