### ISSUE TITLE
Exception compiling checkpoint: stat: path should be string, bytes, os.PathLike or integer, not list

### ISSUE THREAD

**Issue by gordingus** [d8ahazard/sd_dreambooth_extension#1083]
### Discussed in https://github.com/d8ahazard/sd_dreambooth_extension/discussions/818
`Exception compiling checkpoint: stat: path should be string, bytes, os.PathLike or integer, not list`

Looks like it's having trouble understanding I unchecked LoRA. I change the .json as described in the issue post above, but when I click Generate again, it resets to the brackets.

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the
db_config.json file from /models/dreambooth/MODELNAME/db_config.json

### 3. Provide logs

```st
Exception compiling checkpoint: stat: path should be string, bytes, os.PathLike or integer, not list
Traceback (most recent call last):
  File "D:\Program Files\Visions of Chaos\Machine Learning Files\Text To Image\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\diff_to_sd.py", line 435, in compile_checkpoint
    lora_rev = apply_lora(config, unet_model, lora_file_name, "cpu", False)
  File "D:\Program Files\Visions of Chaos\Machine Learning Files\Text To Image\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\diff_to_sd.py", line 567, in apply_lora
    if not os.path.exists(lora_file_name):
  File "C:\Users\Gordingus\AppData\Local\Programs\Python\Python310\lib\genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not list
Duration: 00:00:03
```

### 4. Environment

What OS?
Windows native

What GPU are you using?
3090

**Comment by ArrowM** [comment]
I think ed9e595e64d72fdc34669c265c968db37a44230d should fix it when it gets merged to main (hopefully tomorrow)
