### ISSUE TITLE
DB installation problems

### ISSUE THREAD

**Issue by aiprompter69** [d8ahazard/sd_dreambooth_extension#1092]
## ⚠️If you do not follow the template, your issue may be closed without a response ⚠️
Kindly read and fill this form in its entirety.

### 1. Please find the following lines in the console and paste them below.

```
#######################################################################################################
Initializing Dreambooth : 

Python revision: 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Dreambooth revision: 1b8437cb7e3f2b963058caed0abf237a94add0c7
SD-WebUI revision: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2


[+] torch version 2.0.0+cu118 installed.
[+] torchvision version 0.15.1+cu118 installed.
[+] xformers version 0.0.17+b6be33a.d20230315 installed.
[+] accelerate version 0.17.1 installed.
[+] bitsandbytes version 0.35.4 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.27.1 installed.

#######################################################################################################
```

### 2. Describe the bug

I'm able to download DB from direct url/manually and get the full files related to. But the "Dreambooth" section doesn't appear in SD. I already tried : 

- Matching the requirements.txt files
- Reinstalling "venv" file
- Updating SD

### 3. Provide logs **(FULL STACKTRACE)**

venv "C:\Users\XXXX\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Commit hash: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2
Installing requirements for Web UI
Installing requirements for Batch Face Swap

Error running install.py for extension extensions\sd_dreambooth_extension.
Command: "C:\Users\XXXX\stable-diffusion-webui\venv\Scripts\python.exe" "extensions\sd_dreambooth_extension\install.py"
Error code: 1
stdout: Base dir (auto1111) is: C:\Users\XXXX\stable-diffusion-webui from C:\Users\XXXX\stable-diffusion-webui\extensions\sd_dreambooth_extension\install.py
Ext dir already in path? C:\Users\XXXX\stable-diffusion-webui\extensions\sd_dreambooth_extension
['C:\\Users\\XXXX\\stable-diffusion-webui\\repositories\\k-diffusion', 'C:\\Users\\XXXX\\stable-diffusion-webui\\venv\\lib\\site-packages\\git\\ext\\gitdb', 'C:\\Users\\XXXX\\stable-diffusion-webui', 'C:\\Users\\XXXX\\stable-diffusion-webui\\extensions\\sd_dreambooth_extension', 'C:\\Users\\XXXX\\stable-diffusion-webui', 'C:\\Users\\XXXX\\AppData\\Local\\Programs\\Python\\Python310\\python310.zip', 'C:\\Users\\XXXX\\AppData\\Local\\Programs\\Python\\Python310\\DLLs', 'C:\\Users\\XXXX\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\Users\\XXXX\\AppData\\Local\\Programs\\Python\\Python310', 'C:\\Users\\XXXX\\stable-diffusion-webui\\venv', 'C:\\Users\\XXXX\\stable-diffusion-webui\\venv\\lib\\site-packages', 'C:\\Users\\XXXX\\stable-diffusion-webui\\repositories\\stable-diffusion-stability-ai', 'C:\\Users\\XXXX\\stable-diffusion-webui\\repositories\\taming-transformers', 'C:\\Users\\XXXX\\stable-diffusion-webui\\repositories\\CodeFormer', 'C:\\Users\\XXXX\\stable-diffusion-webui\\repositories\\BLIP']

Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Dreambooth revision: 1b8437cb7e3f2b963058caed0abf237a94add0c7
SD-WebUI revision: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2

stderr: Traceback (most recent call last):
  File "C:\Users\XXXX\stable-diffusion-webui\extensions\sd_dreambooth_extension\postinstall.py", line 64, in pip_install
    output = subprocess.check_output(
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\XXXX\\stable-diffusion-webui\\venv\\Scripts\\python.exe', '-m', 'pip', 'install', 'albumentations~=1.3.0']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\XXXX\stable-diffusion-webui\extensions\sd_dreambooth_extension\install.py", line 35, in <module>
    actual_install()
  File "C:\Users\XXXX\stable-diffusion-webui\extensions\sd_dreambooth_extension\postinstall.py", line 51, in actual_install
    install_requirements()
  File "C:\Users\XXXX\stable-diffusion-webui\extensions\sd_dreambooth_extension\postinstall.py", line 90, in install_requirements
    pip_install([line])
  File "C:\Users\XXXX\stable-diffusion-webui\extensions\sd_dreambooth_extension\postinstall.py", line 72, in pip_install
    error_msg = grepexc.output.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 2647: invalid continuation byte

loading Smart Crop reqs from C:\Users\XXXX\stable-diffusion-webui\extensions\sd_smartprocess\requirements.txt
Checking Smart Crop requirements.

Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
Additional Network extension not installed, Only hijack built-in lora
LoCon Extension hijack built-in lora successfully
Installing openmim
Installing mmcv-full
Installing mmdet
Error loading script: ddetailer.py
Traceback (most recent call last):
  File "C:\Users\XXXX\stable-diffusion-webui\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\XXXX\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\XXXX\stable-diffusion-webui\extensions\ddetailer\scripts\ddetailer.py", line 61, in <module>
    startup()
  File "C:\Users\XXXX\stable-diffusion-webui\extensions\ddetailer\scripts\ddetailer.py", line 50, in startup
    run(f'"{python}" -m pip install mmdet', desc=f"Installing mmdet", errdesc=f"Couldn't install mmdet")
  File "C:\Users\XXXX\stable-diffusion-webui\launch.py", line 113, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install mmdet.
Command: "C:\Users\XXXX\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install mmdet
Error code: 1
stdout: Collecting mmdet
  Using cached mmdet-2.28.2-py3-none-any.whl (1.5 MB)
Requirement already satisfied: six in c:\users\XXXX\stable-diffusion-webui\venv\lib\site-packages (from mmdet) (1.16.0)Requirement already satisfied: numpy in c:\users\XXXX\stable-diffusion-webui\venv\lib\site-packages (from mmdet) (1.23.3)
Requirement already satisfied: scipy in c:\users\XXXX\stable-diffusion-webui\venv\lib\site-packages (from mmdet) (1.10.1)
Collecting pycocotools
  Using cached pycocotools-2.0.6.tar.gz (24 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting terminaltables
  Using cached terminaltables-3.1.10-py2.py3-none-any.whl (15 kB)
Requirement already satisfied: matplotlib in c:\users\XXXX\stable-diffusion-webui\venv\lib\site-packages (from mmdet) (3.7.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\XXXX\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mmdet) (1.4.4)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\XXXX\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mmdet) (3.0.9)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\XXXX\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mmdet) (4.39.2)
Requirement already satisfied: packaging>=20.0 in c:\users\XXXX\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mmdet) (23.0)
Requirement already satisfied: cycler>=0.10 in c:\users\XXXX\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mmdet) (0.11.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\XXXX\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mmdet) (2.8.2)
Requirement already satisfied: pillow>=6.2.0 in c:\users\XXXX\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mmdet) (9.4.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\XXXX\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mmdet) (1.0.7)
Building wheels for collected packages: pycocotools
  Building wheel for pycocotools (pyproject.toml): started
  Building wheel for pycocotools (pyproject.toml): finished with status 'error'
Failed to build pycocotools

stderr:   error: subprocess-exited-with-error

  Building wheel for pycocotools (pyproject.toml) did not run successfully.
  exit code: 1

  [16 lines of output]
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-310
  creating build\lib.win-amd64-cpython-310\pycocotools
  copying pycocotools\coco.py -> build\lib.win-amd64-cpython-310\pycocotools
  copying pycocotools\cocoeval.py -> build\lib.win-amd64-cpython-310\pycocotools
  copying pycocotools\mask.py -> build\lib.win-amd64-cpython-310\pycocotools
  copying pycocotools\__init__.py -> build\lib.win-amd64-cpython-310\pycocotools
  running build_ext
  cythoning pycocotools/_mask.pyx to pycocotools\_mask.c
  C:\Users\XXXX\AppData\Local\Temp\pip-build-env-al6vlccx\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\XXXX\AppData\Local\Temp\pip-install-f7vc9dxp\pycocotools_9f7a83ba0aa340d2a8bad20f5d080c2d\pycocotools\_mask.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  building 'pycocotools._mask' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycocotools
ERROR: Could not build wheels for pycocotools, which is required to install pyproject.toml-based projects

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: C:\Users\XXXX\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip

Exception importing api
Traceback (most recent call last):
  File "C:\Users\XXXX\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\api.py", line 27, in <module>
    from dreambooth.dataclasses.db_config import from_file, DreamboothConfig
  File "C:\Users\XXXX\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dataclasses\db_config.py", line 10, in <module>
    from dreambooth.utils.image_utils import get_scheduler_names  # noqa
  File "C:\Users\XXXX\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\utils\image_utils.py", line 11, in <module>
    from diffusers.schedulers import KarrasDiffusionSchedulers
ModuleNotFoundError: No module named 'diffusers'
Error loading script: main.py
Traceback (most recent call last):
  File "C:\Users\XXXX\stable-diffusion-webui\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\XXXX\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\XXXX\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py", line 7, in <module>
    from dreambooth.dataclasses.db_config import (
  File "C:\Users\XXXX\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dataclasses\db_config.py", line 10, in <module>
    from dreambooth.utils.image_utils import get_scheduler_names  # noqa
  File "C:\Users\XXXX\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\utils\image_utils.py", line 11, in <module>
    from diffusers.schedulers import KarrasDiffusionSchedulers
ModuleNotFoundError: No module named 'diffusers'

Error loading script: main.py
Traceback (most recent call last):
  File "C:\Users\XXXX\stable-diffusion-webui\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\XXXX\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\XXXX\stable-diffusion-webui\extensions\sd_smartprocess\scripts\main.py", line 3, in <module>
    from extensions.sd_smartprocess import smartprocess
  File "C:\Users\XXXX\stable-diffusion-webui\extensions\sd_smartprocess\smartprocess.py", line 15, in <module>
    from extensions.sd_smartprocess.clipinterrogator import ClipInterrogator
  File "C:\Users\XXXX\stable-diffusion-webui\extensions\sd_smartprocess\clipinterrogator.py", line 14, in <module>
    from models.blip import blip_decoder, BLIP_Decoder
  File "C:\Users\XXXX\stable-diffusion-webui\repositories\BLIP\models\blip.py", line 11, in <module>
    from models.vit import VisionTransformer, interpolate_pos_embed
  File "C:\Users\XXXX\stable-diffusion-webui\repositories\BLIP\models\vit.py", line 21, in <module>
    from fairscale.nn.checkpoint.checkpoint_activations import checkpoint_wrapper
ModuleNotFoundError: No module named 'fairscale'

Loading weights [5b2afec3d9] from C:\Users\XXXX\stable-diffusion-webui\models\Stable-diffusion\Realistic_Vision_V1.4-pruned-fp16.safetensors
Creating model from config: C:\Users\XXXX\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: C:\Users\XXXX\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt
Applying cross attention optimization (Doggettx).
Textual inversion embeddings loaded(1): betest
Model loaded in 4.8s (load weights from disk: 0.1s, create model: 0.3s, apply weights to model: 1.9s, apply half(): 0.5s, load VAE: 0.3s, move model to device: 0.4s, load textual inversion embeddings: 1.2s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Error executing callback app_started_callback for C:\Users\XXXX\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\api.py
Traceback (most recent call last):
  File "C:\Users\XXXX\stable-diffusion-webui\modules\script_callbacks.py", line 107, in app_started_callback
    c.callback(demo, app)
  File "C:\Users\XXXX\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\api.py", line 524, in dreambooth_api
    model_cfg: DreamboothConfig = Body(description="The config to save"),
NameError: name 'DreamboothConfig' is not defined

Startup time: 47.1s (import gradio: 2.5s, import ldm: 0.9s, other imports: 1.6s, list extensions: 2.9s, setup codeformer: 0.1s, load scripts: 20.9s, load SD checkpoint: 4.9s, create ui: 13.2s, gradio launch: 0.1s).

### 4. Environment

What OS? : Windows 10

If Windows - WSL or native? : NATIVE

What GPU are you using? : RTX 3080 Gigabyte-OC (v1)

**Comment by Fubu4u2** [comment]
try this

go to  \stable-diffusion-webui\extensions\sd_dreambooth_extension
type cmd in address bar
run the commands below 

git pull
pip install -r requirements.txt

double check requirements version.txt in webui folder matches requirements.txt in dreambooth folder

**Comment by oramonmoreira** [comment]
I had the same problem... try to update the dreambooth extension and compare the requirements... but didnt work...

here i had another problem, the xformers didnt find on start:


Successfully installed fastapi-0.90.1 starlette-0.23.1
Successfully installed gitpython-3.1.31

[+] torch version 2.0.0+cu118 installed.
[+] torchvision version 0.15.0+cu118 installed.
[+] xformers version 0.0.17+b6be33a.d20230315 installed.
[+] accelerate version 0.17.1 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.27.1 installed.
[+] bitsandbytes version 0.35.4 installed.


Launching Web UI with arguments:
C:\Users\Ramon\Desktop\stable\venv\lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(

No module 'xformers'. Proceeding without it.
Error loading script: ddetailer.py
Traceback (most recent call last):
  File "C:\Users\Ramon\Desktop\stable\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\Ramon\Desktop\stable\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Ramon\Desktop\stable\extensions\ddetailer\scripts\ddetailer.py", line 458, in <module>
    from mmdet.core import get_classes
  File "C:\Users\Ramon\Desktop\stable\venv\lib\site-packages\mmdet\core\__init__.py", line 3, in <module>
    from .bbox import *  # noqa: F401, F403
  File "C:\Users\Ramon\Desktop\stable\venv\lib\site-packages\mmdet\core\bbox\__init__.py", line 8, in <module>
    from .samplers import (BaseSampler, CombinedSampler,
  File "C:\Users\Ramon\Desktop\stable\venv\lib\site-packages\mmdet\core\bbox\samplers\__init__.py", line 12, in <module>
    from .score_hlr_sampler import ScoreHLRSampler
  File "C:\Users\Ramon\Desktop\stable\venv\lib\site-packages\mmdet\core\bbox\samplers\score_hlr_sampler.py", line 3, in <module>
    from mmcv.ops import nms_match
  File "C:\Users\Ramon\Desktop\stable\venv\lib\site-packages\mmcv\ops\__init__.py", line 3, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "C:\Users\Ramon\Desktop\stable\venv\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "C:\Users\Ramon\Desktop\stable\venv\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "C:\Users\Ramon\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _ext: Não foi possível encontrar o procedimento especificado.


Loading weights [1a189f0be6] from C:\Users\Ramon\Desktop\stable\models\Stable-diffusion\v1-5-pruned.safetensors
Creating model from config: C:\Users\Ramon\Desktop\stable\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
