### ISSUE TITLE
ModuleNotFoundError: import of xformers halted; None in sys.modules

### ISSUE THREAD

**Issue by rinh** [d8ahazard/sd_dreambooth_extension#1094]
```
#######################################################################################################
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Commit hash: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2
Installing requirements for Web UI


Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Dreambooth revision: 1b8437cb7e3f2b963058caed0abf237a94add0c7
SD-WebUI revision: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2


[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
[+] xformers version 0.0.17.dev476 installed.
[+] accelerate version 0.17.1 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.27.1 installed.
[+] bitsandbytes version 0.35.4 installed.

Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
Loading weights [6ce0161689] from E:\SD\stable-diffusion-webui\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Creating model from config: E:\SD\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (Doggettx).
Textual inversion embeddings loaded(9): @capo130xx, ba-noa, bukkakAI, corneo_covering_breasts_two_hands, corneo_paizuri, corneo_x_pasties, pureerosface_v1, SexyBlindfoldedWomen, spreadassms
Textual inversion embeddings skipped(2): 21charturnerv2, anthro
Model loaded in 3.8s (create model: 0.4s, apply weights to model: 0.7s, apply half(): 0.9s, move model to device: 0.7s, load textual inversion embeddings: 1.0s).
CUDA SETUP: Loading binary E:\SD\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 28.3s (import gradio: 2.4s, import ldm: 0.9s, other imports: 1.7s, list extensions: 0.3s, load scripts: 4.4s, load SD checkpoint: 4.0s, create ui: 14.4s, gradio launch: 0.2s).
Model dir set to: E:\SD\stable-diffusion-webui\models\dreambooth\yiyi
Wizard results:<br>Num Epochs: 150<br>Num instance images per class image: 5
Model dir set to: E:\SD\stable-diffusion-webui\models\dreambooth\yiyi
Wizard results:<br>Num Epochs: 150<br>Num instance images per class image: 5
Model dir set to: E:\SD\stable-diffusion-webui\models\dreambooth\yiyi 
Initializing dreambooth training...
The version of diffusers is less than or equal to 0.14.0. Performing monkey-patch...
Pre-processing images: classifiers_0: : 0it [00:00, ?it/s]
Nothing to generate.
Traceback (most recent call last):
  File "E:\SD\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\ui_functions.py", line 724, in start_training
    result = main(class_gen_method=class_gen_method)
  File "E:\SD\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1462, in main
    return inner_loop()
  File "E:\SD\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 119, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "E:\SD\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 296, in inner_loop
    import xformers
ModuleNotFoundError: import of xformers halted; None in sys.modules
Restored system models.
Duration: 00:00:10
#######################################################################################################
```

### 2. Describe the bug

When I finished training the model, the above error appeared.
 
### 4. Environment

What OS? 
windows
If Windows - WSL or native?
native
What GPU are you using?
GTX 1080 Ti

**Comment by rinh** [comment]
It was my mistake, I didn't use webui.bat when I started it.
