### ISSUE TITLE
Cannot train dreambooth because HFValidationError: Repo id Must use Alphanumeric Char

### ISSUE THREAD

**Issue by KaishanLam** [d8ahazard/sd_dreambooth_extension#1105]
Initializing dreambooth training...
Patching transformers to fix kwargs errors.
E:\Brian\stable-diffusion-webui\venv\lib\site-packages\transformers\generation_utils.py:24: FutureWarning: Importing GenerationMixin from src/transformers/generation_utils.py is deprecated and will be removed in Transformers v5. Import as from transformers import GenerationMixin instead.
warnings.warn(
Replace CrossAttention.forward to use default
Checking concept: {'max_steps': -1, 'instance_data_dir': 'E:\backup\Poniue\Twilighjt', 'class_data_dir': 'E:\backup\pony', 'instance_prompt': 'Digital art of TwiBot pony', 'class_prompt': 'Digital art of a pony', 'save_sample_prompt': '', 'save_sample_template': '', 'instance_token': '', 'class_token': '', 'num_class_images': 0, 'class_negative_prompt': '', 'class_guidance_scale': 7.5, 'class_infer_steps': 40, 'save_sample_negative_prompt': '', 'n_save_sample': 1, 'sample_seed': -1, 'save_guidance_scale': 7.5, 'save_infer_steps': 40}
Concept requires 0 images.
Traceback (most recent call last):
File "E:\Brian\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 362, in start_training
config, mem_record, msg = main(config, mem_record, use_subdir=use_subdir, lora_model=lora_model_name,
File "E:\Brian\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 515, in main
tokenizer = AutoTokenizer.from_pretrained(
File "E:\Brian\stable-diffusion-webui\venv\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 582, in from_pretrained
tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
File "E:\Brian\stable-diffusion-webui\venv\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 433, in get_tokenizer_config
resolved_config_file = cached_file(
File "E:\Brian\stable-diffusion-webui\venv\lib\site-packages\transformers\utils\hub.py", line 409, in cached_file
resolved_file = hf_hub_download(
File "E:\Brian\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 1022, in hf_hub_download
cache_dir, repo_folder_name(repo_id=repo_id, repo_type=repo_type)
File "E:\Brian\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils_validators.py", line 92, in _inner_fn
validate_repo_id(arg_value)
File "E:\Brian\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils_validators.py", line 142, in validate_repo_id
raise HFValidationError(
huggingface_hub.utils.validators.HFValidationError: Repo id must use alphanumeric chars or '-', '', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'E:\Brian\stable-diffusion-webui\models\dreambooth\TwiBot\working\tokenizer'
Training completed, reloading SD Model.

希望作者能尽快看到这个大部分人都出现的问题，期待你的回复，感谢。
I hope the author can read this question as soon as possible and look forward to your reply. Thank you.

**Comment by ArrowM** [comment]
1. please follow the Issue template
2. The error is
```st
huggingface_hub.utils.validators.HFValidationError: Repo id must use alphanumeric chars or '-', '', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'E:\Brian\stable-diffusion-webui\models\dreambooth\TwiBot\working\tokenizer'
Training completed, reloading SD Model.
```
You are using a model name that is invalid. This is a restriction from the huggingface library, not our extension. You may need to manually download model instead of using the built-in download.
