### ISSUE TITLE
cant update

### ISSUE THREAD

**Issue by yggdrasil75** [d8ahazard/sd_dreambooth_extension#1107]
raceback (most recent call last):
  File "D:\creations\imagetraining\automatic\extensions\sd_dreambooth_extension\dreambooth\ui_functions.py", line 724, in start_training
    result = main(class_gen_method=class_gen_method)
  File "D:\creations\imagetraining\automatic\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1462, in main
    return inner_loop()
  File "D:\creations\imagetraining\automatic\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 119, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "D:\creations\imagetraining\automatic\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1198, in inner_loop
    for step, batch in enumerate(train_dataloader):
  File "D:\creations\imagetraining\automatic\venv\lib\site-packages\accelerate\data_loader.py", line 378, in __iter__
    current_batch = next(dataloader_iter)
  File "D:\creations\imagetraining\automatic\venv\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "D:\creations\imagetraining\automatic\venv\lib\site-packages\torch\utils\data\dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\creations\imagetraining\automatic\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "D:\creations\imagetraining\automatic\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 612, in collate_fn
    pixel_values = torch.stack(pixel_values)
RuntimeError: stack expects each tensor to be equal size, but got [4, 96, 72] at entry 0 and [4, 96, 48] at entry 1
Steps:   0%|                                                                            | 0/1097890 [00:00<?, ?it/s]
Restored system models.
Duration: 00:18:53
Traceback (most recent call last):
  File "D:\creations\imagetraining\automatic\extensions\sd_dreambooth_extension\dreambooth\ui_functions.py", line 773, in reload_extension
    from postinstall import actual_install  # noqa
ModuleNotFoundError: No module named 'postinstall'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\creations\imagetraining\automatic\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\creations\imagetraining\automatic\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "D:\creations\imagetraining\automatic\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\creations\imagetraining\automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\creations\imagetraining\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\creations\imagetraining\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\creations\imagetraining\automatic\extensions\sd_dreambooth_extension\dreambooth\ui_functions.py", line 793, in update_extension
    reload_extension()
  File "D:\creations\imagetraining\automatic\extensions\sd_dreambooth_extension\dreambooth\ui_functions.py", line 775, in reload_extension
    from dreambooth.postinstall import actual_install  # noqa
ModuleNotFoundError: No module named 'dreambooth.postinstall'

**Comment by yggdrasil75** [comment]
all info needed for the template is in #1106 and #1102. @d8ahazard

**Comment by ArrowM** [comment]
Did not follow template
