### ISSUE TITLE
lora training issue CUDA out of memory 

### ISSUE THREAD

**Issue by sunyiwk** [d8ahazard/sd_dreambooth_extension#1116]
Additional Network extension not installed, Only hijack built-in lora
LoCon Extension hijack built-in lora successfully
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
Loading weights [fc2511737a] from I:\BaiduNetdiskDownload\stable-diffusion-webui_23-03-10\stable-diffusion-webui_23-03-10\models\Stable-diffusion\chilloutmix_NiPrunedFp32Fix.safetensors
Creating model from config: I:\BaiduNetdiskDownload\stable-diffusion-webui_23-03-10\stable-diffusion-webui_23-03-10\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0):
Model loaded in 1.6s (create model: 0.4s, apply weights to model: 0.6s, apply half(): 0.6s).
CUDA SETUP: Loading binary I:\BaiduNetdiskDownload\stable-diffusion-webui_23-03-10\stable-diffusion-webui_23-03-10\python\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Model dir set to: models\dreambooth\test
Model dir set to: models\dreambooth\test
Model dir set to: models\dreambooth\test
Model dir set to: models\dreambooth\test
Custom model name is my5photo
Initializing dreambooth training...
The version of diffusers is less than or equal to 0.14.0. Performing monkey-patch...
Pre-processing images: out: : 0it [00:00, ?it/s]
Nothing to generate.
Model dir set to: models\dreambooth\test
Found 80 reg images.
Preparing dataset...
Building prompts with strict tokens enabled.
Init dataset!
Preparing Dataset (With Caching)
Caching latents...:   0%|                                                                       | 0/96 [00:00<?, ?it/s]Loading cached latents...
Bucket 0 (128, 128, 0) - Instance Images: 16 | Class Images: 80 | Max Examples/batch:  32
Total Buckets 1 - Instance Images: 16 | Class Images: 80 | Max Examples/batch: 32
Caching latents...: 100%|███████████████████████████████████████████████████████████| 96/96 [00:00<00:00, 24060.54it/s]
Total images / batch: 32, total examples: 32
Caching latents...: 100%|███████████████████████████████████████████████████████████| 96/96 [00:00<00:00, 19250.97it/s]
Total dataset length (steps): 32
Initializing bucket counter!
  ***** Running training *****
  Num batches each epoch = 8
  Num Epochs = 150
  Batch Size Per Device = 4
  Gradient Accumulation steps = 4
  Total train batch size (w. parallel, distributed & accumulation) = 16
  Text Encoder Epochs: 112
  Total optimization steps = 2400
  Total training steps = 4800
  Resuming from checkpoint: False
  First resume epoch: 0
  First resume step: 0
  Lora: True, Optimizer: 8bit AdamW, Prec: fp16
  Gradient Checkpointing: False
  EMA: False
  UNET: True
  Freeze CLIP Normalization Layers: False
  LR: 5e-05
  LoRA Extended: True
  LoRA Text Encoder LR: 2.5e-05
  V2: False
Steps:   0%|                                                                                  | 0/4800 [00:00<?, ?it/s]OOM Detected, reducing batch/grad size to 2/2.
Traceback (most recent call last):
  File "I:\BaiduNetdiskDownload\stable-diffusion-webui_23-03-10\stable-diffusion-webui_23-03-10\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 119, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "I:\BaiduNetdiskDownload\stable-diffusion-webui_23-03-10\stable-diffusion-webui_23-03-10\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1229, in inner_loop
    noise_pred = unet(
  File "I:\BaiduNetdiskDownload\stable-diffusion-webui_23-03-10\stable-diffusion-webui_23-03-10\python\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "I:\BaiduNetdiskDownload\stable-diffusion-webui_23-03-10\stable-diffusion-webui_23-03-10\python\lib\site-packages\accelerate\utils\operations.py", line 489, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "I:\BaiduNetdiskDownload\stable-diffusion-webui_23-03-10\stable-diffusion-webui_23-03-10\python\lib\site-packages\torch\amp\autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "I:\BaiduNetdiskDownload\stable-diffusion-webui_23-03-10\stable-diffusion-webui_23-03-10\python\lib\site-packages\diffusers\models\unet_2d_condition.py", line 625, in forward
    sample = upsample_block(
  File "I:\BaiduNetdiskDownload\stable-diffusion-webui_23-03-10\stable-diffusion-webui_23-03-10\python\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "I:\BaiduNetdiskDownload\stable-diffusion-webui_23-03-10\stable-diffusion-webui_23-03-10\python\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 1891, in forward
    hidden_states = resnet(hidden_states, temb)
  File "I:\BaiduNetdiskDownload\stable-diffusion-webui_23-03-10\stable-diffusion-webui_23-03-10\python\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "I:\BaiduNetdiskDownload\stable-diffusion-webui_23-03-10\stable-diffusion-webui_23-03-10\python\lib\site-packages\diffusers\models\resnet.py", line 555, in forward
    hidden_states = self.conv1(hidden_states)
  File "I:\BaiduNetdiskDownload\stable-diffusion-webui_23-03-10\stable-diffusion-webui_23-03-10\python\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "I:\BaiduNetdiskDownload\stable-diffusion-webui_23-03-10\stable-diffusion-webui_23-03-10\extensions\sd_dreambooth_extension\lora_diffusion\lora.py", line 97, in forward
    + self.lora_up(self.dropout(self.lora_down(input))) * self.scale
  File "I:\BaiduNetdiskDownload\stable-diffusion-webui_23-03-10\stable-diffusion-webui_23-03-10\python\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "I:\BaiduNetdiskDownload\stable-diffusion-webui_23-03-10\stable-diffusion-webui_23-03-10\extensions-builtin\Lora\lora.py", line 182, in lora_Conv2d_forward
    return lora_forward(self, input, torch.nn.Conv2d_forward_before_lora(self, input))
  File "I:\BaiduNetdiskDownload\stable-diffusion-webui_23-03-10\stable-diffusion-webui_23-03-10\python\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "I:\BaiduNetdiskDownload\stable-diffusion-webui_23-03-10\stable-diffusion-webui_23-03-10\python\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 6.00 GiB total capacity; 5.29 GiB already allocated; 0 bytes free; 5.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Steps:   0%|                                                                                  | 0/4800 [00:02<?, ?it/s]
Pre-processing images: out: : 0it [00:00, ?it/s]
Nothing to generate.

**Comment by ElliottLester** [comment]
In case someone says you don't have enough VRAM I'm seeing this also on an A5500 it looks like it lasts longer and gets to iteration 10 before running out of VRAM.
Maybe there's a leak in the training loop?

################################################################
Launching launch.py...
################################################################
Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
Commit hash: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2
Installing requirements for Web UI
[auto-sd-paint-ext] Commit hash: 3b82fedf98f9fdb2b523f8d4eafe817e149383f2
[auto-sd-paint-ext] Auto-update disabled.
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:
Python revision: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
Dreambooth revision: da2e40415f1cb63cc4de46d6dc97eb8676c6e30c
SD-WebUI revision: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
[+] xformers version 0.0.17.dev464 installed.
[+] accelerate version 0.17.1 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.27.2 installed.
[+] bitsandbytes version 0.35.4 installed.
Launching Web UI with arguments: --listen --enable-insecure-extension-access --no-half --precision full --api
No module 'xformers'. Proceeding without it.
Loading weights [6ce0161689] from ./stable-diffusion-webui/models/Stable-diffusion/Stable-diffusion/v1-5-pruned-emaonly.safetensors
Creating model from config: ./stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (Doggettx).
Textual inversion embeddings loaded(5): <snip>
Model loaded in 8.2s (load weights from disk: 0.5s, create model: 0.6s, apply weights to model: 2.0s, load VAE: 3.9s, move model to device: 1.2s).
Running on local URL:  http://0.0.0.0:7860
To create a public link, set `share=True` in `launch()`.
Startup time: 18.6s (import gradio: 1.1s, import ldm: 0.8s, other imports: 1.5s, load scripts: 4.3s, load SD checkpoint: 8.3s, create ui: 2.1s, gradio launch: 0.1s, scripts app_started_callback: 0.2s).
Model dir set to: models/dreambooth/Test
Model dir set to: models/dreambooth/Test
Model dir set to: models/dreambooth/Test
Model dir set to: models/dreambooth/Test
Initializing dreambooth training...
The version of diffusers is less than or equal to 0.14.0. Performing monkey-patch...
Pre-processing images: classifiers_0: : 0it [00:00, ?it/s]                          
Nothing to generate.
Model dir set to: models/dreambooth/Test
Found 5 reg images.
Preparing dataset...
Init dataset!
Preparing Dataset (With Caching)
Caching latents...: 100%|██████████| 6/6 [00:00<00:00, 767.81it/s]
Loading cached latents...
Bucket 0 (512, 512, 0) - Instance Images: 1 | Class Images: 5 | Max Examples/batch:  2
Total Buckets 1 - Instance Images: 1 | Class Images: 5 | Max Examples/batch: 2
Total images / batch: 2, total examples: 2
Total dataset length (steps): 2
Initializing bucket counter!
  ***** Running training *****
  Num batches each epoch = 2
  Num Epochs = 150
  Batch Size Per Device = 1
  Gradient Accumulation steps = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Text Encoder Epochs: 112
  Total optimization steps = 150
  Total training steps = 300
  Resuming from checkpoint: False
  First resume epoch: 0
  First resume step: 0
  Lora: True, Optimizer: 8bit AdamW, Prec: bf16
  Gradient Checkpointing: False
  EMA: True
  UNET: True
  Freeze CLIP Normalization Layers: False
  LR: 0.0001
  LoRA Text Encoder LR: 5e-05
  V2: False
Steps:   0%|          | 0/300 [00:00<?, ?it/s, inst_loss=0, loss=0.177, lr=0.0001, prior_loss=0.236, vram=14.4]      Traceback (most recent call last):
  File "./stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 119, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "./stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1229, in inner_loop
    noise_pred = unet(
  File "./stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "./stable-diffusion-webui/venv/lib/python3.10/site-packages/accelerate/utils/operations.py", line 495, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "./stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "./stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 631, in forward
    sample = upsample_block(
  File "./stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "./stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/unet_2d_blocks.py", line 1813, in forward
    hidden_states = attn(
  File "./stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "./stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/transformer_2d.py", line 265, in forward
    hidden_states = block(
  File "./stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "./stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/attention.py", line 291, in forward
    attn_output = self.attn1(
  File "./stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "./stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/cross_attention.py", line 205, in forward
    return self.processor(
  File "./stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/cross_attention.py", line 314, in __call__
    attention_probs = attn.get_attention_scores(query, key, attention_mask)
  File "./stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/cross_attention.py", line 253, in get_attention_scores
    attention_probs = attention_scores.softmax(dim=-1)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 0; 23.68 GiB total capacity; 12.22 GiB already allocated; 400.12 MiB free; 12.24 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Steps:   3%|▎         | 10/300 [00:00<00:21, 13.35it/s, inst_loss=0, loss=0.177, lr=0.0001, prior_loss=0.236, vram=14.4]
Traceback (most recent call last):
  File "./stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 724, in start_training
    result = main(class_gen_method=class_gen_method)
  File "./stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1426, in main
    return inner_loop()
  File "./stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 117, in decorator
    raise RuntimeError("No executable batch size found, reached zero.")
RuntimeError: No executable batch size found, reached zero.

**Comment by ArrowM** [comment]
@sunyiwk
1. Please follow the issue template (that's the primary reason I am closing this)
2. You don't have enough VRAM for your configuration. Try disabling Extended Lora. 

@ElliottLester
You definitely have some other issue going on. Based on the logs, I'm guessing you have something else running on the device that is consuming a lot of VRAM. Please open a separate issue or ask on Discord.

**Comment by sunyiwk** [comment]
@ElliottLester I turned it off.   Extended Lora.
Have no effect

**Comment by ArrowM** [comment]
Set the text Encoder slider to 0

**Comment by sunyiwk** [comment]
Have no effect @ElliottLester
