### ISSUE TITLE
list index out of range when starting a training

### ISSUE THREAD

**Issue by isbkch** [d8ahazard/sd_dreambooth_extension#1127]
## ⚠️If you do not follow the template, your issue may be closed without a response ⚠️
Kindly read and fill this form in its entirety.

### 0. Initial troubleshooting
Please check each of these before opening an issue. If you've checked them, **delete this section of your bug report**. Have you:
- Updated the Stable-Diffusion-WebUI to the latest version?
- Updated Dreambooth to the latest revision?
- Completely restarted the stable-diffusion-webUI, not just reloaded the UI?
- Read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?

### 1. Please find the following lines in the console and paste them below.

```
#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.9
Dreambooth: latest from main branch
SD-WebUI: latest from main branch

[!] xformers NOT installed.
[!] torch version 1.12.1 installed.
[!] torchvision version 0.13.1 installed.
[+] accelerate version 0.18.0 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.

#######################################################################################################
```

### 2. Describe the bug

Starting a training throws the following error:

```st
Model dir set to: models/dreambooth/ohwx66
Duration: 00:00:00
Error completing request
Arguments: ('ohwx66', 'Native Diffusers') {}
Traceback (most recent call last):
  File "/Users/ilyas/Dev.nosync/ml/webui/extensions/sd_dreambooth_extension/dreambooth/utils/utils.py", line 190, in f
    except Exception as e:
  File "/Users/ilyas/Dev.nosync/ml/webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 692, in start_training
    if config.resolution <= 0:
TypeError: '<=' not supported between instances of 'str' and 'int'

Traceback (most recent call last):
  File "/Users/ilyas/Dev.nosync/ml/webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/ilyas/Dev.nosync/ml/webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1018, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/Users/ilyas/Dev.nosync/ml/webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 935, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: list index out of range
```
<img width="1840" alt="Screenshot 2023-03-26 at 8 30 24 PM" src="https://user-images.githubusercontent.com/216867/227814948-1a060621-67a7-4380-9be4-3945baf9c498.png">

<img width="1830" alt="Screenshot 2023-03-26 at 8 30 14 PM" src="https://user-images.githubusercontent.com/216867/227814954-b8948bd7-f759-4f56-92cf-091906f2ab39.png">

Below is my startup log as well

```st
webui ) ./webui.sh                                                                           (base)

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on ilyas user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Python 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:26:08) [Clang 14.0.6 ]
Commit hash: 64b7e8382377bb578d9740c061979776b214cfd9
Installing requirements for Web UI
Error running install.py for extension extensions/sd_dreambooth_extension.
Command: "/Users/ilyas/Dev.nosync/ml/webui/venv/bin/python3.10" "extensions/sd_dreambooth_extension/install.py"
Error code: 1
stdout: Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: 3324b6ab7fa661cf7d6b5ef186227dc5e8ad1878
# Requirement installation exception:
Ignoring tensorflow: markers 'sys_platform != "darwin" or platform_machine != "arm64"' don't match your environment
Collecting accelerate==0.17.1
Using cached accelerate-0.17.1-py3-none-any.whl (212 kB)
Requirement already satisfied: bitsandbytes==0.35.4 in ./venv/lib/python3.10/site-packages (from -r /Users/ilyas/Dev.nosync/ml/webui/extensions/sd_dreambooth_extension/requirements.txt (line 2)) (0.35.4)
Requirement already satisfied: dadaptation==1.5.0 in ./venv/lib/python3.10/site-packages (from -r /Users/ilyas/Dev.nosync/ml/webui/extensions/sd_dreambooth_extension/requirements.txt (line 3)) (1.5)
Requirement already satisfied: diffusers~=0.14.0 in ./venv/lib/python3.10/site-packages (from -r /Users/ilyas/Dev.nosync/ml/webui/extensions/sd_dreambooth_extension/requirements.txt (line 4)) (0.14.0)
Requirement already satisfied: discord-webhook~=1.1.0 in ./venv/lib/python3.10/site-packages (from -r /Users/ilyas/Dev.nosync/ml/webui/extensions/sd_dreambooth_extension/requirements.txt (line 5)) (1.1.0)
Collecting fastapi~=0.90.1
Using cached fastapi-0.90.1-py3-none-any.whl (56 kB)
Collecting gitpython~=3.1.31
Using cached GitPython-3.1.31-py3-none-any.whl (184 kB)
Requirement already satisfied: lion-pytorch~=0.0.7 in ./venv/lib/python3.10/site-packages (from -r /Users/ilyas/Dev.nosync/ml/webui/extensions/sd_dreambooth_extension/requirements.txt (line 8)) (0.0.7)
Collecting tensorboard~=2.12.0
Using cached tensorboard-2.12.0-py3-none-any.whl (5.6 MB)
Requirement already satisfied: tensorflow-macos==2.11.0 in ./venv/lib/python3.10/site-packages (from -r /Users/ilyas/Dev.nosync/ml/webui/extensions/sd_dreambooth_extension/requirements.txt (line 11)) (2.11.0)
Requirement already satisfied: tensorflow-metal in ./venv/lib/python3.10/site-packages (from -r /Users/ilyas/Dev.nosync/ml/webui/extensions/sd_dreambooth_extension/requirements.txt (line 12)) (0.7.1)
Requirement already satisfied: tqdm~=4.64.1 in ./venv/lib/python3.10/site-packages (from -r /Users/ilyas/Dev.nosync/ml/webui/extensions/sd_dreambooth_extension/requirements.txt (line 13)) (4.64.1)
Collecting transformers==4.26.1
Using cached transformers-4.26.1-py3-none-any.whl (6.3 MB)
Requirement already satisfied: packaging>=20.0 in ./venv/lib/python3.10/site-packages (from accelerate==0.17.1->-r /Users/ilyas/Dev.nosync/ml/webui/extensions/sd_dreambooth_extension/requirements.txt (line 1)) (23.0)
Requirement already satisfied: numpy>=1.17 in ./venv/lib/python3.10/site-packages (from accelerate==0.17.1->-r /Users/ilyas/Dev.nosync/ml/webui/extensions/sd_dreambooth_extension/requirements.txt (line 1)) (1.23.3)
Requirement already satisfied: torch>=1.4.0 in ./venv/lib/python3.10/site-packages (from accelerate==0.17.1->-r /Users/ilyas/Dev.nosync/ml/webui/extensions/sd_dreambooth_extension/requirements.txt (line 1)) (1.12.1)
Requirement already satisfied: pyyaml in ./venv/lib/python3.10/site-packages (from accelerate==0.17.1->-r /Users/ilyas/Dev.nosync/ml/webui/extensions/sd_dreambooth_extension/requirements.txt (line 1)) (6.0)
Requirement already satisfied: psutil in ./venv/lib/python3.10/site-packages (from accelerate==0.17.1->-r /Users/ilyas/Dev.nosync/ml/webui/extensions/sd_dreambooth_extension/requirements.txt (line 1)) (5.9.4)
Requirement already satisfied: keras<2.12,>=2.11.0 in ./venv/lib/python3.10/site-packages (from tensorflow-macos==2.11.0->-r /Users/ilyas/Dev.nosync/ml/webui/extensions/sd_dreambooth_extension/requirements.txt (line 11)) (2.11.0)
Requirement already satisfied: flatbuffers>=2.0 in ./venv/lib/python3.10/site-packages (from tensorflow-macos==2.11.0->-r /Users/ilyas/Dev.nosync/ml/webui/extensions/sd_dreambooth_extension/requirements.txt (line 11)) (23.3.3)
Requirement already satisfied: tensorflow-estimator<2.12,>=2.11.0 in ./venv/lib/python3.10/site-packages (from tensorflow-macos==2.11.0->-r /Users/ilyas/Dev.nosync/ml/webui/extensions/sd_dreambooth_extension/requirements.txt (line 11)) (2.11.0)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in ./venv/lib/python3.10/site-packages (from tensorflow-macos==2.11.0->-r /Users/ilyas/Dev.nosync/ml/webui/extensions/sd_dreambooth_extension/requirements.txt (line 11)) (0.4.0)
Requirement already satisfied: setuptools in ./venv/lib/python3.10/site-packages (from tensorflow-macos==2.11.0->-r /Users/ilyas/Dev.nosync/ml/webui/extensions/sd_dreambooth_extension/requirements.txt (line 11)) (65.5.0)
Requirement already satisfied: wrapt>=1.11.0 in ./venv/lib/python3.10/site-packages (from tensorflow-macos==2.11.0->-r /Users/ilyas/Dev.nosync/ml/webui/extensions/sd_dreambooth_extension/requirements.txt (line 11)) (1.15.0)
Requirement already satisfied: typing-extensions>=3.6.6 in ./venv/lib/python3.10/site-packages (from tensorflow-macos==2.11.0->-r /Users/ilyas/Dev.nosync/ml/webui/extensions/sd_dreambooth_extension/requirements.txt (line 11)) (4.5.0)
Requirement already satisfied: six>=1.12.0 in ./venv/lib/python3.10/site-packages (from tensorflow-macos==2.11.0->-r /Users/ilyas/Dev.nosync/ml/webui/extensions/sd_dreambooth_extension/requirements.txt (line 11)) (1.16.0)
INFO: pip is looking at multiple versions of dadaptation to determine which version is compatible with other requirements. This could take a while.
Collecting dadaptation==1.5.0
Using cached dadaptation-1.5-py3-none-any.whl
INFO: pip is looking at multiple versions of bitsandbytes to determine which version is compatible with other requirements. This could take a while.
Collecting bitsandbytes==0.35.4
Using cached bitsandbytes-0.35.4-py3-none-any.whl (62.5 MB)
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of accelerate to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install tensorboard~=2.12.0 and tensorflow-macos==2.11.0 because these package versions have conflicting dependencies.
The conflict is caused by:
The user requested tensorboard~=2.12.0
tensorflow-macos 2.11.0 depends on tensorboard<2.12 and >=2.11
To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: pip install --upgrade pip

stderr: Traceback (most recent call last):
  File "/Users/ilyas/Dev.nosync/ml/webui/extensions/sd_dreambooth_extension/install.py", line 35, in <module>
    actual_install()
  File "/Users/ilyas/Dev.nosync/ml/webui/extensions/sd_dreambooth_extension/postinstall.py", line 41, in actual_install
    install_requirements()
  File "/Users/ilyas/Dev.nosync/ml/webui/extensions/sd_dreambooth_extension/postinstall.py", line 87, in install_requirements
    raise grepexc
  File "/Users/ilyas/Dev.nosync/ml/webui/extensions/sd_dreambooth_extension/postinstall.py", line 75, in install_requirements
    pip_install("-r", req_file)
  File "/Users/ilyas/Dev.nosync/ml/webui/extensions/sd_dreambooth_extension/postinstall.py", line 53, in pip_install
    output = subprocess.check_output(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/ilyas/Dev.nosync/ml/webui/venv/bin/python3.10', '-m', 'pip', 'install', '-r', '/Users/ilyas/Dev.nosync/ml/webui/extensions/sd_dreambooth_extension/requirements.txt']' returned non-zero exit status 1.


Launching Web UI with arguments: --upcast-sampling --no-half-vae --use-cpu interrogate
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
No module 'xformers'. Proceeding without it.
==============================================================================
You are running torch 1.12.1.
The program is tested to work with torch 1.13.1.
To reinstall the desired version, run with commandline flag --reinstall-torch.
Beware that this will cause a lot of large files to be downloaded, as well as
there are reports of issues with training tab on the latest version.

Use --skip-version-check commandline argument to disable this check.
==============================================================================
Loading weights [77e392958a] from /Users/ilyas/Dev.nosync/ml/webui/models/Stable-diffusion/realisticVisionV13_v13.ckpt
Creating model from config: /Users/ilyas/Dev.nosync/ml/webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (InvokeAI).
Textual inversion embeddings loaded(0):
Model loaded in 2.7s (load weights from disk: 0.6s, create model: 0.6s, apply weights to model: 0.5s, apply half(): 0.4s, move model to device: 0.5s).
CUDA SETUP: Required library version not found: libsbitsandbytes_cpu.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
================================================================================

CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Required library version not found: libsbitsandbytes_cpu.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
================================================================================

CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 8.3s (import gradio: 1.0s, import ldm: 2.2s, other imports: 0.7s, load scripts: 0.6s, load SD checkpoint: 2.8s, create ui: 0.9s).
```

And this is the content of `pip freeze`

```st
webui ) pip freeze                                                                           (base)
absl-py==1.4.0
accelerate==0.17.1
addict==2.4.0
aenum==3.1.11
aiofiles==23.1.0
aiohttp==3.8.4
aiosignal==1.3.1
altair==4.2.2
antlr4-python3-runtime==4.9.3
anyio==3.6.2
astunparse==1.6.3
async-timeout==4.0.2
attrs==22.2.0
basicsr==1.4.2
beautifulsoup4==4.12.0
bitsandbytes==0.35.4
blendmodes==2022
boltons==23.0.0
brotlipy @ file:///Users/runner/miniforge3/conda-bld/brotlipy_1666764759924/work
cached-property @ file:///home/conda/feedstock_root/build_artifacts/cached_property_1615209429212/work
cachetools==5.3.0
certifi==2022.12.7
cffi @ file:///Users/runner/miniforge3/conda-bld/cffi_1671179893800/work
chardet==4.0.0
charset-normalizer @ file:///home/conda/feedstock_root/build_artifacts/charset-normalizer_1661170624537/work
clean-fid==0.1.29
click==8.1.3
clip @ git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1666700638685/work
conda==23.1.0
conda-package-handling @ file:///home/conda/feedstock_root/build_artifacts/conda-package-handling_1669907009957/work
conda_package_streaming @ file:///home/conda/feedstock_root/build_artifacts/conda-package-streaming_1669733752472/work
contourpy==1.0.7
cryptography @ file:///Users/runner/miniforge3/conda-bld/cryptography-split_1675828699498/work
cycler==0.11.0
dadaptation==1.5
deprecation==2.1.0
diffusers==0.14.0
discord-webhook==1.1.0
einops==0.4.1
entrypoints==0.4
facexlib==0.2.5
fastapi==0.90.1
ffmpy==0.3.0
filelock==3.10.4
filterpy==1.4.5
flatbuffers==23.3.3
font-roboto==0.0.1
fonts==0.0.3
fonttools==4.39.2
frozenlist==1.3.3
fsspec==2023.3.0
ftfy==6.1.1
future==0.18.3
gast==0.4.0
gdown==4.7.1
gfpgan==1.3.8
gitdb==4.0.10
GitPython==3.1.31
google-auth==2.16.3
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
gradio==3.16.2
grpcio==1.51.3
h11==0.12.0
h5py @ file:///Users/runner/miniforge3/conda-bld/h5py_1637964553571/work
httpcore==0.15.0
httpx==0.23.3
huggingface-hub==0.13.3
idna==2.10
imageio==2.26.1
importlib-metadata==6.1.0
inflection==0.5.1
Jinja2==3.1.2
jsonmerge==1.8.0
jsonschema==4.17.3
keras==2.11.0
kiwisolver==1.4.4
kornia==0.6.7
lark==1.1.2
lazy_loader==0.2
libclang==16.0.0
lightning-utilities==0.8.0
linkify-it-py==2.0.0
lion-pytorch==0.0.7
llvmlite==0.39.1
lmdb==1.4.0
lpips==0.1.4
Markdown==3.4.3
markdown-it-py==2.2.0
MarkupSafe==2.1.2
matplotlib==3.7.1
mdit-py-plugins==0.3.3
mdurl==0.1.2
multidict==6.0.4
networkx==3.0
numba==0.56.4
numpy==1.23.3
oauthlib==3.2.2
omegaconf==2.2.3
open-clip-torch @ git+https://github.com/mlfoundations/open_clip.git@bb6e834e9c70d9c27d0dc3ecedeebeaeb1ffad6b
opencv-python==4.7.0.72
opt-einsum==3.3.0
orjson==3.8.8
packaging==23.0
pandas==1.5.3
piexif==1.1.3
Pillow==9.4.0
pluggy @ file:///home/conda/feedstock_root/build_artifacts/pluggy_1667232663820/work
protobuf==3.19.6
psutil==5.9.4
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycosat @ file:///Users/runner/miniforge3/conda-bld/pycosat_1666836623787/work
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1636257122734/work
pycryptodome==3.17
pydantic==1.10.7
pyDeprecate==0.3.2
pydub==0.25.1
pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1672659226110/work
pyparsing==3.0.9
pyrsistent==0.19.3
PySocks @ file:///home/conda/feedstock_root/build_artifacts/pysocks_1661604839144/work
python-dateutil==2.8.2
python-multipart==0.0.6
pytorch-lightning==1.7.6
pytz==2023.2
PyWavelets==1.4.1
PyYAML==6.0
realesrgan==0.3.0
regex==2023.3.23
requests==2.28.2
requests-oauthlib==1.3.1
resize-right==0.0.2
rfc3986==1.5.0
rsa==4.9
ruamel.yaml @ file:///Users/runner/miniforge3/conda-bld/ruamel.yaml_1666827372049/work
ruamel.yaml.clib @ file:///Users/runner/miniforge3/conda-bld/ruamel.yaml.clib_1670412881259/work
safetensors==0.2.7
scikit-image==0.19.2
scipy==1.10.1
semantic-version==2.10.0
sentencepiece==0.1.97
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
smmap==5.0.0
sniffio==1.3.0
soupsieve==2.4
starlette==0.23.1
tb-nightly==2.12.0a20230126
tensorboard==2.11.2
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow-estimator==2.11.0
tensorflow-macos==2.11.0
tensorflow-metal==0.7.1
termcolor==2.2.0
tifffile==2023.3.21
timm==0.6.7
tokenizers==0.13.2
toolz @ file:///home/conda/feedstock_root/build_artifacts/toolz_1657485559105/work
torch==1.12.1
torchdiffeq==0.2.3
torchmetrics==0.11.4
torchsde==0.2.5
torchvision==0.13.1
tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1662214488106/work
trampoline==0.1.2
transformers==4.27.2
typing_extensions==4.5.0
uc-micro-py==1.0.1
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1673452138552/work
uvicorn==0.21.1
wcwidth==0.2.6
websockets==10.4
Werkzeug==2.2.3
wrapt==1.15.0
yapf==0.32.0
yarl==1.8.2
zipp==3.15.0
zstandard==0.19.0
```

### 4. Environment

Mac M1 Max - Ventura 13.2.1

**Comment by isbkch** [comment]
I run `git checkout dev` and started webui again, this is the startup log

```st
################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on ilyas user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Python 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:26:08) [Clang 14.0.6 ]
Commit hash: 64b7e8382377bb578d9740c061979776b214cfd9
Installing requirements for Web UI
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: 8a9136c1a1c0dc73bb4fb6f41936a8e4397e310e
Successfully installed accelerate-0.18.0 fastapi-0.90.1 gitpython-3.1.31 requests-2.28.2 starlette-0.23.1 transformers-4.26.1

Does your project take forever to startup?
Repetitive dependency installation may be the reason.
Automatic1111's base project sets strict requirements on outdated dependencies.
If an extension is using a newer version, the dependency is uninstalled and reinstalled twice every startup.

[!] xformers NOT installed.
[!] torch version 1.12.1 installed.
[!] torchvision version 0.13.1 installed.
[+] accelerate version 0.18.0 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.

#######################################################################################################
#                                       LIBRARY ISSUE DETECTED                                        #
#######################################################################################################
#
# torch is below the required 1.13.1+cu116 version.
# torchvision is below the required 0.14.1+cu116 version.
#
# Dreambooth may not work properly.
#
# TROUBLESHOOTING
# 1. Fully restart your project (not just the webpage)
# 2. Update your A1111 project and extensions
# 3. Dreambooth requirements should have installed automatically, but you can manually install them
#    by running the following 4 commands from the A1111 project root:
cd venv/Scripts
activate
cd ../..
pip install -r ./extensions/sd_dreambooth_extension/requirements.txt
#######################################################################################################

Launching Web UI with arguments: --upcast-sampling --no-half-vae --use-cpu interrogate
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
No module 'xformers'. Proceeding without it.
==============================================================================
You are running torch 1.12.1.
The program is tested to work with torch 1.13.1.
To reinstall the desired version, run with commandline flag --reinstall-torch.
Beware that this will cause a lot of large files to be downloaded, as well as
there are reports of issues with training tab on the latest version.

Use --skip-version-check commandline argument to disable this check.
==============================================================================
Exception importing api
Traceback (most recent call last):
  File "/Users/ilyas/Dev.nosync/ml/webui/extensions/sd_dreambooth_extension/scripts/api.py", line 28, in <module>
    from dreambooth.diff_to_sd import compile_checkpoint
  File "/Users/ilyas/Dev.nosync/ml/webui/extensions/sd_dreambooth_extension/dreambooth/diff_to_sd.py", line 21, in <module>
    from dreambooth.utils.model_utils import unload_system_models, \
  File "/Users/ilyas/Dev.nosync/ml/webui/extensions/sd_dreambooth_extension/dreambooth/utils/model_utils.py", line 9, in <module>
    from torch._dynamo.backends.debugging import aot_eager
ModuleNotFoundError: No module named 'torch._dynamo'
Error loading script: main.py
Traceback (most recent call last):
  File "/Users/ilyas/Dev.nosync/ml/webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/Users/ilyas/Dev.nosync/ml/webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/ilyas/Dev.nosync/ml/webui/extensions/sd_dreambooth_extension/scripts/main.py", line 11, in <module>
    from dreambooth.diff_to_sd import compile_checkpoint
  File "/Users/ilyas/Dev.nosync/ml/webui/extensions/sd_dreambooth_extension/dreambooth/diff_to_sd.py", line 21, in <module>
    from dreambooth.utils.model_utils import unload_system_models, \
  File "/Users/ilyas/Dev.nosync/ml/webui/extensions/sd_dreambooth_extension/dreambooth/utils/model_utils.py", line 9, in <module>
    from torch._dynamo.backends.debugging import aot_eager
ModuleNotFoundError: No module named 'torch._dynamo'

Loading weights [77e392958a] from /Users/ilyas/Dev.nosync/ml/webui/models/Stable-diffusion/realisticVisionV13_v13.ckpt
Creating model from config: /Users/ilyas/Dev.nosync/ml/webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (InvokeAI).
Textual inversion embeddings loaded(0):
Model loaded in 2.6s (load weights from disk: 0.6s, create model: 0.6s, apply weights to model: 0.4s, apply half(): 0.4s, move model to device: 0.5s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 7.3s (import gradio: 1.0s, import ldm: 2.2s, other imports: 0.7s, load scripts: 0.6s, load SD checkpoint: 2.7s, create ui: 0.1s).
```

**Comment by DarkVioletMoonRay** [comment]
Same errors. To add to this:
1. I'm also getting config errors when I create a model and also when I try to load the created models. 
_FileNotFoundError: [Errno 2] No such file or directory: 'models/dreambooth/Broken/db_config.json'
Can't load config!_
2. Also, one of the initial configs folder is in the wrong spot. I had to move it from "/content/stable-diffusion-webui/extensions/sd_dreambooth_extension" to "/content/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth" to get as far as I have.
