### ISSUE TITLE
Generate model from hub doesn't work

### ISSUE THREAD

**Issue by TheRealThor** [d8ahazard/sd_dreambooth_extension#1131]
## ⚠️If you do not follow the template, your issue may be closed without a response ⚠️
Kindly read and fill this form in its entirety.

### 0. Initial troubleshooting
Please check each of these before opening an issue. If you've checked them, **delete this section of your bug report**. Have you:
- Updated the Stable-Diffusion-WebUI to the latest version?
- Updated Dreambooth to the latest revision?
- Completely restarted the stable-diffusion-webUI, not just reloaded the UI?
- Read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?

### 1. Please find the following lines in the console and paste them below.

```
Initializing Dreambooth
Dreambooth revision: 3324b6ab7fa661cf7d6b5ef186227dc5e8ad1878
Successfully installed accelerate-0.17.1 fastapi-0.90.1 gitpython-3.1.31 google-auth-oauthlib-0.4.6 requests-2.28.2 starlette-0.23.1 tensorboard-data-server-0.6.1 transformers-4.26.1

Does your project take forever to startup?
Repetitive dependency installation may be the reason.
Automatic1111's base project sets strict requirements on outdated dependencies.
If an extension is using a newer version, the dependency is uninstalled and reinstalled twice every startup.

[+] xformers version 0.0.17+5eb0dbf.d20230327 installed.
[+] torch version 2.1.0.dev20230327 installed.
[+] torchvision version 0.16.0.dev20230327 installed.
[+] accelerate version 0.17.1 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.

Launching Web UI with arguments: --skip-torch-cuda-test --upcast-sampling --no-half-vae --use-cpu interrogate

#######################################################################################################
```

### 2. Describe the bug

Fresh install of webui via git with latest commit and lastest of this extension does not allow creating new model in the from hub (training tab). Used my hugging face access token. I tried not only with "dreambooth/stable-diffusion-v1-5" but other paths as well and the error (Repo id must be in the form 'repo_name' or 'namespace/repo_name) was the same. I guess something with coping from the model remote to local doesn't work. Maybe it tries to load the model before it was copied to its final path? I don't know.

used 

**Screenshots/Config**

```st
Model dir set to: models/dreambooth/stable-diffusion-v1-5
Found diffusion file: feature_extractor/preprocessor_config.json
Found model index: model_index.json
Found diffusion file: safety_checker/config.json
Found model: safety_checker/model.safetensors
Found diffusion file: safety_checker/pytorch_model.bin
Found diffusion file: scheduler/scheduler_config.json
Found diffusion file: text_encoder/config.json
Found model: text_encoder/model.safetensors
Found diffusion file: text_encoder/pytorch_model.bin
Found diffusion file: tokenizer/merges.txt
Found diffusion file: tokenizer/special_tokens_map.json
Found diffusion file: tokenizer/tokenizer_config.json
Found diffusion file: tokenizer/vocab.json
Found diffusion file: unet/config.json
Found diffusion file: unet/diffusion_pytorch_model.bin
Found model: unet/diffusion_pytorch_model.safetensors
Found model: v1-5-pruned-emaonly.ckpt
Found model: v1-5-pruned-emaonly.safetensors
Found model: v1-5-pruned.ckpt
Found model: v1-5-pruned.safetensors
Found inference file: v1-inference.yaml
Found diffusion file: vae/config.json
Found diffusion file: vae/diffusion_pytorch_model.bin
Found model: vae/diffusion_pytorch_model.safetensors
Diffusion files: ['feature_extractor/preprocessor_config.json', 'safety_checker/config.json', 'safety_checker/pytorch_model.bin', 'scheduler/scheduler_config.json', 'text_encoder/config.json', 'text_encoder/pytorch_model.bin', 'tokenizer/merges.txt', 'tokenizer/special_tokens_map.json', 'tokenizer/tokenizer_config.json', 'tokenizer/vocab.json', 'unet/config.json', 'unet/diffusion_pytorch_model.bin', 'vae/config.json', 'vae/diffusion_pytorch_model.bin']
Fetching files: ['safety_checker/model.safetensors', 'v1-inference.yaml']
                                                                                                                                                                           NO BLOBng 2 files:   0%|                                                                                                                               | 0/2 [00:00<?, ?it/s]
                                                                                                                                                                           NO BLOBng 2 files:  50%|███████████████████████████████████████████████████████████▌                                                           | 1/2 [00:01<00:01,  1.46s/it]
Fetching 2 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.37it/s]
Got model info.
Loading UNet from models/dreambooth/stable-diffusion-v1-5/working/unet
Exception loading unet!
Traceback (most recent call last):
  File "/Users/thor/Dev/AI/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 857, in _get_model_file
    model_file = hf_hub_download(
  File "/Users/thor/Dev/AI/stable-diffusion-webui/venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 112, in _inner_fn
    validate_repo_id(arg_value)
  File "/Users/thor/Dev/AI/stable-diffusion-webui/venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 160, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'models/dreambooth/stable-diffusion-v1-5/working/unet'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/thor/Dev/AI/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/sd_to_diff.py", line 1117, in extract_checkpoint
    unet = UNet2DConditionModel.from_pretrained(unet_dir)
  File "/Users/thor/Dev/AI/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 527, in from_pretrained
    model_file = _get_model_file(
  File "/Users/thor/Dev/AI/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 894, in _get_model_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like models/dreambooth/stable-diffusion-v1-5/working/unet is not the path to a directory containing a file named diffusion_pytorch_model.bin or 
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.
Pred and size are epsilon and 768, using config: /Users/thor/Dev/AI/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/../configs/v1-training-default.yaml
Restored system models.
```

### 4. Environment

What OS?

MacOS Ventura (Apple Silicon M2)

**Comment by ArrowM** [comment]
Did you read your own error?

> raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like models/dreambooth/stable-diffusion-v1-5/working/unet is not the path to a directory containing a file named diffusion_pytorch_model.bin or
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.
