### ISSUE TITLE
Training runs into errors while running on RTX 3060 - Laptop

### ISSUE THREAD

**Issue by greevak** [d8ahazard/sd_dreambooth_extension#1162]
Windows 10 latest, RTX 3060 on laptop, 6 GB vram
I optimised the settings of dreambooth to match my pc using the button "performance wizard", watched couple videos on youtube and they seemed to work fine for my GPU case.

Everything is updated, git and python and so on

My settings:
I have 150 images for traning set to my directories,
and around 1500 - 1600 regulation images.

![image](https://user-images.githubusercontent.com/38337258/229420722-fe3a875b-f555-482c-a79b-cf8cd7845738.png)

![image](https://user-images.githubusercontent.com/38337258/229420755-3923eef7-06c0-46be-a248-54ce0ff8538a.png)

Here is a complete text file of the command line window:

```
C:\Windows\system32>cd C:\Program Files\StableDif\stable-diffusion-webui

C:\Program Files\StableDif\stable-diffusion-webui>webui-user.bat

C:\Program Files\StableDif\stable-diffusion-webui>git pull
Already up to date.
venv "C:\Program Files\StableDif\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing requirements for Web UI


If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: 926ae204ef5de17efca2059c334b6098492a0641
Successfully installed accelerate-0.18.0 fastapi-0.94.1 gitpython-3.1.31 google-auth-oauthlib-0.4.6 requests-2.28.2 transformers-4.26.1

Does your project take forever to startup?
Repetitive dependency installation may be the reason.
Automatic1111's base project sets strict requirements on outdated dependencies.
If an extension is using a newer version, the dependency is uninstalled and reinstalled twice every startup.

[!] xformers NOT installed.
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
[+] accelerate version 0.18.0 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.

Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
Loading weights [e6415c4892] from C:\Program Files\StableDif\stable-diffusion-webui\models\Stable-diffusion\Realistic_Vision_V2.0.safetensors
Creating model from config: C:\Program Files\StableDif\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (Doggettx).
Textual inversion embeddings loaded(0):
Model loaded in 5.7s (load weights from disk: 0.5s, create model: 0.5s, apply weights to model: 1.6s, apply half(): 0.7s, move model to device: 0.9s, load textual inversion embeddings: 1.5s).
*Deforum ControlNet support: enabled*
CUDA SETUP: Loading binary C:\Program Files\StableDif\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 17.9s (import torch: 6.0s, import gradio: 0.6s, import ldm: 0.8s, other imports: 1.9s, setup codeformer: 0.1s, load scripts: 1.7s, load SD checkpoint: 5.8s, create ui: 0.9s, gradio launch: 0.1s).
Total images: 0
Total VRAM: 6
Wizard results:<br>Num Epochs: 150<br>Num instance images per class image: 5
Replacing flash attention in config to default
Wizard results:<br>Num Epochs: 150<br>Num instance images per class image: 5
Replacing flash attention in config to default
Wizard results:<br>Num Epochs: 150<br>Num instance images per class image: 5
Replacing flash attention in config to default
Wizard results:<br>Num Epochs: 150<br>Num instance images per class image: 5
Replacing flash attention in config to default
Wizard results:<br>Num Epochs: 150<br>Num instance images per class image: 5
Replacing flash attention in config to default
Replacing flash attention in config to default
Initializing dreambooth training...
The version of diffusers is less than or equal to 0.14.0. Performing monkey-patch...
Pre-processing images: person: : 0it [00:00, ?it/s]
Nothing to generate.
Found 750 reg images.
Preparing dataset...
Init dataset!
Preparing Dataset (With Caching)
Bucket 0 (512, 512, 0) - Instance Images: 150 | Class Images: 750 | Max Examples/batch:  300
Caching latents...: 100%|████████████████████████████████████████████████████████████| 900/900 [02:18<00:00,  6.63it/s]Saving cache!
Total Buckets 1 - Instance Images: 150 | Class Images: 750 | Max Examples/batch: 300
Caching latents...: 100%|████████████████████████████████████████████████████████████| 900/900 [02:19<00:00,  6.63it/s]
Total images / batch: 300, total examples: 300
Caching latents...: 100%|████████████████████████████████████████████████████████████| 900/900 [02:19<00:00,  6.47it/s]
Total dataset length (steps): 300
Initializing bucket counter!
  ***** Running training *****
  Num batches each epoch = 300
  Num Epochs = 150
  Batch Size Per Device = 1
  Gradient Accumulation steps = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Text Encoder Epochs: 112
  Total optimization steps = 22500
  Total training steps = 45000
  Resuming from checkpoint: False
  First resume epoch: 0
  First resume step: 0
  Lora: True, Optimizer: 8bit AdamW, Prec: bf16
  Gradient Checkpointing: False
  EMA: False
  UNET: True
  Freeze CLIP Normalization Layers: False
  LR: 0.0001
  LoRA Text Encoder LR: 5e-05
  V2: False
Steps:   0%|                                                                                 | 0/45000 [00:00<?, ?it/s]OOM Detected, reducing batch/grad size to 0/1.
```
```st
Traceback (most recent call last):
  File "C:\Program Files\StableDif\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 119, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "C:\Program Files\StableDif\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1169, in inner_loop
    noise_pred = unet(
  File "C:\Program Files\StableDif\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Program Files\StableDif\stable-diffusion-webui\venv\lib\site-packages\accelerate\utils\operations.py", line 495, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "C:\Program Files\StableDif\stable-diffusion-webui\venv\lib\site-packages\torch\amp\autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "C:\Program Files\StableDif\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 582, in forward
    sample, res_samples = downsample_block(
  File "C:\Program Files\StableDif\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Program Files\StableDif\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 837, in forward
    hidden_states = attn(
  File "C:\Program Files\StableDif\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Program Files\StableDif\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\transformer_2d.py", line 265, in forward
    hidden_states = block(
  File "C:\Program Files\StableDif\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Program Files\StableDif\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\attention.py", line 291, in forward
    attn_output = self.attn1(
  File "C:\Program Files\StableDif\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Program Files\StableDif\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\cross_attention.py", line 205, in forward
    return self.processor(
  File "C:\Program Files\StableDif\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\cross_attention.py", line 314, in __call__
    attention_probs = attn.get_attention_scores(query, key, attention_mask)
  File "C:\Program Files\StableDif\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\cross_attention.py", line 253, in get_attention_scores
    attention_probs = attention_scores.softmax(dim=-1)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 0; 6.00 GiB total capacity; 5.08 GiB already allocated; 0 bytes free; 5.12 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Steps:   0%|                                                                                 | 0/45000 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "C:\Program Files\StableDif\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\ui_functions.py", line 727, in start_training
    result = main(class_gen_method=class_gen_method)
  File "C:\Program Files\StableDif\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1371, in main
    return inner_loop()
  File "C:\Program Files\StableDif\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 117, in decorator
    raise RuntimeError("No executable batch size found, reached zero.")
RuntimeError: No executable batch size found, reached zero.
Restored system models.
Duration: 00:02:40
```

**Comment by ArrowM** [comment]
You're running out of VRAM. Switch to torch 2 or install xformers and use it for your memory attention.
If that doesn't get you under 6gb, set Step Ratio of Text Encoder Training to 0 (If you still want to train the text encoder, you can do it separately by unchecking Train UNET).
