### ISSUE TITLE
Exception training model: 'cannot import name 'get_optimizer'

### ISSUE THREAD

**Issue by Casvs** [d8ahazard/sd_dreambooth_extension#1165]
When I start the training "Exception training model: 'cannot import name 'get_optimizer' from 'dreambooth.optimization' (C:\AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\optimization.py)'."

Using version: 926ae204 (Fri Mar 31 15:12:45 2023)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\ui_functions.py", line 723, in start_training
    try:
  File "C:\AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 43, in <module>
    from dreambooth.optimization import UniversalScheduler, get_optimizer, get_noise_scheduler
ImportError: cannot import name 'get_optimizer' from 'dreambooth.optimization' (C:\AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\optimization.py)
Restored system models.
Duration: 00:00:01
Model dir set to: models\dreambooth\Cas_V1.5-Pruned_03-04-23
Model dir set to: models\dreambooth\Cas_V1.5-Pruned_03-04-23
Model dir set to: models\dreambooth\Cas_V1.5-Pruned_03-04-23
Initializing dreambooth training...
Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\ui_functions.py", line 721, in start_training
    status.textinfo = "Initializing dreambooth training..."
  File "C:\AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 43, in <module>
    from dreambooth.optimization import UniversalScheduler, get_optimizer, get_noise_scheduler
ImportError: cannot import name 'get_optimizer' from 'dreambooth.optimization' (C:\AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\optimization.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\ui_functions.py", line 723, in start_training
    try:
  File "C:\AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 43, in <module>
    from dreambooth.optimization import UniversalScheduler, get_optimizer, get_noise_scheduler
ImportError: cannot import name 'get_optimizer' from 'dreambooth.optimization' (C:\AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\optimization.py)
Restored system models.
Duration: 00:00:01

**Comment by ArrowM** [comment]
Follow the issue template. Post the full stacktrace
