### ISSUE TITLE
AMD rocm 5.4.2 issue <built-in function load_binary> returned NULL without setting an exception

### ISSUE THREAD

**Issue by krim404** [d8ahazard/sd_dreambooth_extension#1174]
Running on clean fresh install, only dream booth extension installed. Using torch rocm 5.4.2 on AMD (6900xt) Linux Ubuntu 22.04 LTS

see attached log:
```
Initializing bucket counter!
  ***** Running training *****
  Num batches each epoch = 6
  Num Epochs = 100
  Batch Size Per Device = 1
  Gradient Accumulation steps = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Text Encoder Epochs: 100
  Total optimization steps = 300
  Total training steps = 600
  Resuming from checkpoint: False
  First resume epoch: 0
  First resume step: 0
  Lora: False, Optimizer: Torch AdamW, Prec: fp16
  Gradient Checkpointing: True
  EMA: True
  UNET: True
  Freeze CLIP Normalization Layers: True
  LR: 5e-06
  V2: True
Steps:   0%|                                                                                                                                                                                          | 0/600 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/krim/GIT/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 727, in start_training
    result = main(class_gen_method=class_gen_method)
  File "/home/krim/GIT/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1371, in main
    return inner_loop()
  File "/home/krim/GIT/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 119, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "/home/krim/GIT/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1169, in inner_loop
    noise_pred = unet(
  File "/home/krim/GIT/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/krim/GIT/stable-diffusion-webui/venv/lib/python3.10/site-packages/accelerate/utils/operations.py", line 495, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/home/krim/GIT/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/krim/GIT/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/home/krim/GIT/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/home/krim/GIT/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 556, in forward
    t_emb = self.time_proj(timesteps)
  File "/home/krim/GIT/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/krim/GIT/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/embeddings.py", line 222, in forward
    def forward(self, timesteps):
  File "/home/krim/GIT/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/home/krim/GIT/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 2819, in forward
    return compiled_fn(full_args)
  File "/home/krim/GIT/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1222, in g
    return f(*args)
  File "/home/krim/GIT/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1898, in runtime_wrapper
    all_outs = call_func_with_args(
  File "/home/krim/GIT/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1247, in call_func_with_args
    out = normalize_as_list(f(args))
  File "/home/krim/GIT/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 248, in run
    return model(new_inputs)
  File "/home/krim/GIT/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 265, in run
    compiled_fn = cudagraphify_impl(model, new_inputs, static_input_idxs)
  File "/home/krim/GIT/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 320, in cudagraphify_impl
    model(list(static_inputs))
  File "/tmp/torchinductor_krim/xq/cxqqlwutwzuplluoktmemj63w363iojzltjm3s3avxbjioaget6s.py", line 113, in call
    triton__0.run(arg0_1, buf0, buf1, 160, grid=grid(160), stream=stream0)
  File "/home/krim/GIT/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_inductor/triton_ops/autotune.py", line 190, in run
    result = launcher(
  File "<string>", line 6, in launcher
  File "/home/krim/GIT/stable-diffusion-webui/venv/lib/python3.10/site-packages/triton/compiler.py", line 1944, in __getattribute__
    self._init_handles()
  File "/home/krim/GIT/stable-diffusion-webui/venv/lib/python3.10/site-packages/triton/compiler.py", line 1930, in _init_handles
    mod, func, n_regs, n_spills = hip_utils.load_binary(self.metadata["name"], self.asm["hsaco_path"], self.shared, device)
SystemError: <built-in function load_binary> returned NULL without setting an exception
```

sadly only found one person on reddit with the same problem. Sometimes the error precedes an `unable to find binary /llvm/bin/ld.lld` error.

has anyone an idea whats wrong?

**Comment by ArrowM** [comment]
It's a torch problem, so the PyTorch github is the best place to check

**Comment by krim404** [comment]
Unfortunately, I do not possess a sufficient level of expertise in Python to be able to provide the necessary information to the PyTorch repository as a bug report. I am not knowledgeable enough to understand what is happening here and i doubt that anyone from the PyTorch Community could debug it without knowing the code.

**Comment by N0repi** [comment]
I am experiencing the same error using cuda 11.8 on a RTX 3090. I'm also using the same OS as you. Which Torch version are you using?

**Comment by krim404** [comment]
i'm using torch 2 - the version automatically installed when asking pip to install torch.

**Comment by N0repi** [comment]
> i'm using torch 2 - the version automatically installed when asking pip to install torch.
> 
> ```
> [pip3] lion-pytorch==0.0.7
> [pip3] numpy==1.23.3
> [pip3] open-clip-torch==2.7.0
> [pip3] pytorch-lightning==1.9.4
> [pip3] pytorch-triton-rocm==2.0.1
> [pip3] torch==2.0.0+rocm5.4.2
> [pip3] torchdiffeq==0.2.3
> [pip3] torchmetrics==0.11.4
> [pip3] torchsde==0.2.5
> [pip3] torchvision==0.15.1+rocm5.4.2
> ```

So was I. I had no success using the nightly build of Torch either. I downgraded to torch 1.13.1 and cuda 11.7 and DreamBooth appears to be working okay.

**Comment by krim404** [comment]
i didnt use nightly, i use the stable version of the rocm 5.4.2 built version.

**Comment by krim404** [comment]
any chance to prevent it being auto-closed?

**Comment by krim404** [comment]
someone posted a possible "solution" - was unable to test it, yet:
https://github.com/pytorch/pytorch/issues/98707#issuecomment-1532961128
