### ISSUE TITLE
ValueError: None is of type: <class 'NoneType'> when saving ckpt

### ISSUE THREAD

**Issue by vgaggia** [d8ahazard/sd_dreambooth_extension#119]
Dreambooth revision is 4684f0faea19c243216eac2278a42fcfcbbd756b
Diffusers version is 0.8.0.dev0.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.

I'm using a data set of ~500 images, my advanced settings are as follows:
Unticked - Use CPU Only
Unticked - Don't cache latents
Ticked - Train Text Encoder
Ticked - Use 8bit Adam
Unticked - Center Crop
Unticked - Gradient Checkpointing
Unticked - Scale Learning Rate
Mixed Precision - FP16

one thing to note, is that only once it has managed to train without fp16, not sure why it worked once but since i restarted the program it hasn't worked since, when i wasn't using fp16 i didn't have the issue, the error i get happens whenever it's trying to save the ckpt

Not sure where the full logs are, but i'm sure this is enough:
Exception while training: None is of type: <class 'NoneType'>, but should be <class 'diffusers.modeling_utils.ModelMixin'>
 Allocated: 6.5GB
 Reserved: 11.9GB

Traceback (most recent call last):
  File "G:\Auto\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 955, in main
    save_weights(lifetime_step, save_model, save_img)
  File "G:\Auto\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 812, in save_weights
    pipeline = StableDiffusionPipeline.from_pretrained(
  File "G:\Auto\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipeline_utils.py", line 557, in from_pretrained
    raise ValueError(
ValueError: None is of type: <class 'NoneType'>, but should be <class 'diffusers.modeling_utils.ModelMixin'>

Windows 11 22621.819
Native
RTX 3090

**Comment by vgaggia** [comment]
I'd like to note that a couple updates ago i wasn't having this issue as well, so not I'm sure what's changed since then.

**Comment by vgaggia** [comment]
Update: i found that if i use bf16 for whatever reason it doesn't give me that error when saving the ckpt after training
