### ISSUE TITLE
Successfully trained model OOM on conversion

### ISSUE THREAD

**Issue by 78Alpha** [d8ahazard/sd_dreambooth_extension#12]
Using the CPU only options for training, it saves the model by using GPU VRAM. Currently using a 3070 with 8 GB VRAM and after 100 steps, when it went to save it gave an OOM.

`RuntimeError: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 0; 8.00 GiB total capacity; 7.20 GiB already allocated; 0 bytes free; 7.30 GiB reserved in total by PyTorch)...`

The VRAM was also not freed after failure and the training was stopped.

**Comment by d8ahazard** [comment]
Is there a line number anywhere?

I think I forgot to add my try/catch to this iteration which would help prevent complete decimation upon OOM. 

I'll take a look at the conversion bit and see how I can use the CPU to convert, should be doable.

**Comment by 78Alpha** [comment]
Giving it another run to see if catches again. Want to make extra sure that it wasn't a freak occurrence. I'll grab the line number if it fails again. Have to close the console to launch it again since I didn't run it from terminal.

**Comment by 78Alpha** [comment]
The full traceback

`Traceback (most recent call last):
  File "H:\Utilities\CUDA\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "H:\Utilities\CUDA\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "H:\Utilities\CUDA\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 256, in start_training
    trained_steps = main(config)
  File "H:\Utilities\CUDA\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 745, in main
    encoder_hidden_states = text_encoder(batch["input_ids"])[0]
  File "H:\Utilities\CUDA\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\Utilities\CUDA\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 733, in forward
    return self.text_model(
  File "H:\Utilities\CUDA\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\Utilities\CUDA\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 636, in forward
    hidden_states = self.embeddings(input_ids=input_ids, position_ids=position_ids)
  File "H:\Utilities\CUDA\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\Utilities\CUDA\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 165, in forward
    inputs_embeds = self.token_embedding(input_ids)
  File "H:\Utilities\CUDA\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\Utilities\CUDA\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\sparse.py", line 158, in forward
    return F.embedding(
  File "H:\Utilities\CUDA\stable-diffusion-webui\venv\lib\site-packages\torch\nn\functional.py", line 2199, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper__index_select)`

Line 745 in train_dreambooth.py

**Comment by d8ahazard** [comment]
> embedding return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse) RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

Do you have 'train text encoder" enabled in the advanced settings?

**Comment by ShinkoNet** [comment]
This works fine with shivram's version on 12GB vram even with text encoder enabled.
I suggest to halt training, clear VRAM, and reallocate it during the conversion process.
Right now a solution is to run diffuser's conversion script for models/dreambooth/(modelname) folder manually

in diffusers/scripts (download diffusers if you havent got it)

`convert_diffusers_to_original_stable_diffusion.py --model_path webui/models/dreambooth/(modelname) --checkpoint_path <model output path> --half`

**Comment by 78Alpha** [comment]
I did intend to do the conversion after, but might be good to add a note saying the saving in steps might not work for cards below 10 GB. Unless the conversion gets switched to CPU.

I can wait the 17 hours for a 1000 step CPU run to finish, but just have to remember to convert.

**Comment by 78Alpha** [comment]
Might have to do with the half precision switch. CPU training throws an error on fp16, but that means the model conversion is in full precision as well, causing the OOM. Could just be as simple as adding a switch for fp16 on model conversion, but I don't have the experience with tools like this to be certain.

**Comment by 78Alpha** [comment]
I found in a reinstall of the webui that the CKPT did show up, which was strange, So it does make it, it just stops the training.

**Comment by d8ahazard** [comment]
This should be resolved.
