### ISSUE TITLE
steps stuck at 1% when running training

### ISSUE THREAD

**Issue by shayvidas** [d8ahazard/sd_dreambooth_extension#1202]
I'm running into issues when training a new model
i am running on the steps, but steps is stuck at 0% for some reason
i have gigabyte geforce rtx4070ti 
and 64gb RAM

i have no idea why that is happening
i am not reaching my full vram in psu

i am just getting steps... like 1% for the past 25min

not sure what to do about it

here is my full log file
```

venv "O:\AI\OLD\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Commit hash: 7ba3923d5b494b7756d0b12f33acb3716d830b9a
Installing requirements for Web UI
loading Dreambooth reqs from O:\AI\OLD\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt
Checking Dreambooth requirements.
Checking torch and torchvision versions
Dreambooth revision is 65a4bdffc41b3ab44ec8262acce21c87d9a7fccf
Diffusers version is 0.8.0.dev0.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.
Copying 8Bit Adam files for Windows.

Launching Web UI with arguments: --xformers --autolaunch --theme dark --disable-safe-unpickle
Checkpoint protogenV22Anime_22.ckpt [5b85d125] not found; loading fallback ORIGINALANGELICAAEITBPERSON_500.ckpt [37aa8153]
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loading weights [37aa8153] from O:\AI\OLD\stable-diffusion-webui\models\Stable-diffusion\ORIGINALANGELICAAEITBPERSON_500.ckpt
Applying xformers cross attention optimization.
Model loaded.
Checkpoint protogenV22Anime_22.ckpt [5b85d125] not found; loading fallback ORIGINALANGELICAAEITBPERSON_500.ckpt [37aa8153]
Loaded a total of 0 textual inversion embeddings.
Embeddings:
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Starting Dreambooth training...
 VRAM cleared.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Loaded model.
 Allocated: 0.0GB
 Reserved: 0.0GB


===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA SETUP: Loading binary O:\AI\OLD\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
 Scheduler Loaded
 Allocated: 0.2GB
 Reserved: 0.2GB

Steps:   1%|▍                                                | 14/1500 [10:43<21:04:29, 51.06s/it, loss=0.286, lr=1e-6]



i'm running at windows 10

**Comment by tspecht** [comment]
Have the same - stuck before even the first step for me but identical otherwise. Running on an A10 and never had issues before. Were you able to fix this?

**Comment by adamdavidcole** [comment]
Yup, I'm having the exact same problem with a fresh install on linux. Stuck at 0% steps, but I can hear the GPU going, so I wonder if it's training and just not updating the UI?

Hopefully someone has a workaround 🙏 Thanks!

**Comment by adamdavidcole** [comment]
I tried downgrading to earlier releases but had the same problem. After letting the program hang for about 10 minuets, eventually I got an OOM error. I had DreamBooth running earlier this week on an older version of webui. I'm on a GPU with 24GB of VRAM so I'm not sure what the problem might be. Logs included if they're helpful. 


```
WARNING: Using default optimizer (AdamW from Torch)
Found 1950 reg images.
Preparing dataset...
Init dataset!
Preparing Dataset (With Caching)
Caching latents...:   0%|                                                                                                                                                                                                                     | 0/1976 [00:00<?, ?it/s]Loading cached latents...
Bucket 0 (512, 512, 0) - Instance Images: 26 | Class Images: 1950 | Max Examples/batch:   52                                                                                                                                                                          
Total Buckets 1 - Instance Images: 26 | Class Images: 1950 | Max Examples/batch:   52                                                                                                                                                                                  
Caching latents...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1976/1976 [00:00<00:00,  2.02it/s]
Total images / batch: 52, total examples: 52
Caching latents...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1976/1976 [00:00<00:00, 3960.19it/s]
Total dataset length (steps): 52
Initializing bucket counter!
  ***** Running training *****
  Num batches each epoch = 26
  Num Epochs = 150
  Batch Size Per Device = 2
  Gradient Accumulation steps = 2
  Total train batch size (w. parallel, distributed & accumulation) = 4
  Text Encoder Epochs: 112
  Total optimization steps = 3900
  Total training steps = 7800
  Resuming from checkpoint: False
  First resume epoch: 0
  First resume step: 0
  Lora: False, Optimizer: Torch AdamW, Prec: fp16
  Gradient Checkpointing: False
  EMA: True
  UNET: True
  Freeze CLIP Normalization Layers: False
  LR: 1e-06
  V2: False
Steps:   0%|                                                                                                                                                                                                                                  | 0/7800 [00:00<?, ?it/s][2023-05-05 16:07:18,652] torch._inductor.utils: [WARNING] not enough cuda cores to use max_autotune mode
OOM Detected, reducing batch/grad size to 1/1.
Traceback (most recent call last):
  File "/home/adamcole/dev/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 119, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "/home/adamcole/dev/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1233, in inner_loop
    accelerator.backward(loss)
  File "/home/adamcole/dev/stable-diffusion-webui/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1681, in backward
    self.scaler.scale(loss).backward(**kwargs)
  File "/home/adamcole/dev/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/adamcole/dev/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/adamcole/dev/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/home/adamcole/dev/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 2348, in backward
    out = call_compiled_backward()
  File "/home/adamcole/dev/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 2319, in call_compiled_backward
    CompiledFunction.compiled_bw = aot_config.bw_compiler(
  File "/home/adamcole/dev/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_dynamo/backends/common.py", line 38, in _wrapped_bw_compiler
    return eval_frame.disable(eval_frame.disable(bw_compiler)(*args, **kwargs))
  File "/home/adamcole/dev/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/home/adamcole/dev/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/adamcole/dev/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 441, in bw_compiler
    return inner_compile(
  File "/home/adamcole/anaconda3/envs/automatic/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/adamcole/dev/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_dynamo/debug_utils.py", line 595, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs)
  File "/home/adamcole/dev/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_inductor/debug.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/home/adamcole/anaconda3/envs/automatic/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/adamcole/dev/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 190, in compile_fx_inner
    compiled_fn = cudagraphify(
  File "/home/adamcole/dev/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/adamcole/dev/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 257, in cudagraphify
    return cudagraphify_impl(model, inputs, static_input_idxs)
  File "/home/adamcole/dev/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 320, in cudagraphify_impl
    model(list(static_inputs))
  File "/tmp/torchinductor_adamcole/c2/cc2iqgnynqw54n65gbpd3iarmxpuxuxfez2sizged5q5vdlrzduv.py", line 421, in call
    triton__4.run(buf13, buf8, 10240, 512, grid=grid(10240), stream=stream0)
  File "/home/adamcole/dev/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_inductor/triton_ops/autotune.py", line 182, in run
    self.autotune_to_one_config(*args, grid=grid)
  File "/home/adamcole/dev/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/adamcole/dev/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_inductor/triton_ops/autotune.py", line 169, in autotune_to_one_config
    timings = {
  File "/home/adamcole/dev/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_inductor/triton_ops/autotune.py", line 170, in <dictcomp>
    launcher: self.bench(launcher, *cloned_args, **kwargs)
  File "/home/adamcole/dev/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_inductor/triton_ops/autotune.py", line 151, in bench
    return do_bench(kernel_call, rep=40, fast_flush=True)
  File "/home/adamcole/dev/stable-diffusion-webui/venv/lib/python3.10/site-packages/triton/testing.py", line 162, in do_bench
    cache = torch.empty(int(256e6 // 4), dtype=[torch.int](http://torch.int/), device='cuda')
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 246.00 MiB (GPU 0; 23.65 GiB total capacity; 11.51 GiB already allocated; 116.69 MiB free; 17.42 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Steps:   0%|                                                                                                                                                                                                                                  | 0/7800 [09:06<?, ?it/s]
Pre-processing images: classifiers_0: : 0it [00:00, ?it/s]                                                                                                                                                                                                            
Nothing to generate.
OOM Detected, reducing batch/grad size to 0/1.
Traceback (most recent call last):
  File "/home/adamcole/dev/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 119, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "/home/adamcole/dev/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 372, in inner_loop
    ema_model = EMAModel(
  File "/home/adamcole/dev/stable-diffusion-webui/extensions/sd_dreambooth_extension/helpers/ema_model.py", line 41, in __init__
    [self.model.to](http://self.model.to/)(device, dtype=dtype)
  File "/home/adamcole/dev/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/home/adamcole/dev/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/adamcole/dev/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/adamcole/dev/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 6 more times]
  File "/home/adamcole/dev/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/home/adamcole/dev/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return [t.to](http://t.to/)(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 23.65 GiB total capacity; 11.76 GiB already allocated; 73.69 MiB free; 17.46 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "/home/adamcole/dev/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 727, in start_training
    result = main(class_gen_method=class_gen_method)
  File "/home/adamcole/dev/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1371, in main
    return inner_loop()
  File "/home/adamcole/dev/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 117, in decorator
    raise RuntimeError("No executable batch size found, reached zero.")
RuntimeError: No executable batch size found, reached zero.
Duration: 00:09:40
```

**Comment by adamdavidcole** [comment]
Some additional debugging statements:
I added some print statements and the code hangs in `train_dreambooth.py` at the line where we predict the noise residual `noise_pred = unet(...)`. The function never returns and the VRAM gradually goes up and eventually crashes with an OOM (after 5-10 minuets). 

If I use the `nose_pred=ema_model()` code path, I get the function to run but then get stuck at `accelerator.backward(loss)`. 

If anyone has found a workaround, please share!

**Comment by YReis** [comment]
I am currently having the same issue with my Ubuntu 22.04.2 LTS with 4090, but made a dualboot and seems to work fine on windows, that is my workaround for now

**Comment by zihaolucky** [comment]
Any updates?

**Comment by shehinfn** [comment]
Same issue still persists looks like someone merged a bad pr

**Comment by shehinfn** [comment]
> This issue is stale because it has been open 5 days with no activity. Remove stale label or comment or this will be closed in 5 days

Issue still exists need fixing

**Comment by njovy** [comment]
I am using RTX4090 as well and got stuck and never finished.

**Comment by parzoe** [comment]
Having the same issue, a few days ago things was working just fine
