### ISSUE TITLE
Error when using dev branch

### ISSUE THREAD

**Issue by allroundHim** [d8ahazard/sd_dreambooth_extension#1206]
commit hash
3d322839903b24c65f1e3ed2fe39eb5bbade9f0b
branch dev latest

### 1. Please find the following lines in the console and paste them below.

```
#######################################################################################################
Initializing Dreambooth
Dreambooth revision: 3d322839903b24c65f1e3ed2fe39eb5bbade9f0b
# Requirement installation exception:
WARNING: Ignoring invalid distribution -llow (f:\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution - (f:\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -llow (f:\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (f:\stable-diffusion-webui\venv\lib\site-packages)
Ignoring tensorboard: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
Ignoring tensorflow-macos: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
Ignoring tensorflow-metal: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
Requirement already satisfied: accelerate~=0.18.0 in f:\stable-diffusion-webui\venv\lib\site-packages (from -r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (0.18.0)
Requirement already satisfied: bitsandbytes==0.35.4 in f:\stable-diffusion-webui\venv\lib\site-packages (from -r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (0.35.4)
Requirement already satisfied: dadaptation~=1.5.0 in f:\stable-diffusion-webui\venv\lib\site-packages (from -r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 3)) (1.5)
Requirement already satisfied: diffusers~=0.15.1 in f:\stable-diffusion-webui\venv\lib\site-packages (from -r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (0.15.1)
Requirement already satisfied: discord-webhook~=1.1.0 in f:\stable-diffusion-webui\venv\lib\site-packages (from -r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 5)) (1.1.0)
Collecting fastapi~=0.94.1 (from -r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 6))
Using cached fastapi-0.94.1-py3-none-any.whl (56 kB)
Collecting gitpython~=3.1.31 (from -r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 7))
Using cached GitPython-3.1.31-py3-none-any.whl (184 kB)
Requirement already satisfied: lion-pytorch~=0.0.7 in f:\stable-diffusion-webui\venv\lib\site-packages (from -r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (0.0.7)
Collecting Pillow==9.5.0 (from -r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9))
Using cached Pillow-9.5.0-cp310-cp310-win_amd64.whl (2.5 MB)
Requirement already satisfied: tqdm~=4.64.1 in f:\stable-diffusion-webui\venv\lib\site-packages (from -r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (4.64.1)
Requirement already satisfied: tomesd~=0.1.2 in f:\stable-diffusion-webui\venv\lib\site-packages (from -r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 11)) (0.1.2)
Collecting transformers~=4.26.1 (from -r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 12))
Using cached transformers-4.26.1-py3-none-any.whl (6.3 MB)
Requirement already satisfied: tensorboard==2.12.2 in f:\stable-diffusion-webui\venv\lib\site-packages (from -r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 16)) (2.12.2)
Requirement already satisfied: tensorflow==2.12.0 in f:\stable-diffusion-webui\venv\lib\site-packages (from -r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 17)) (2.12.0)
Requirement already satisfied: absl-py>=0.4 in f:\stable-diffusion-webui\venv\lib\site-packages (from tensorboard==2.12.2->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 16)) (1.4.0)
Requirement already satisfied: grpcio>=1.48.2 in f:\stable-diffusion-webui\venv\lib\site-packages (from tensorboard==2.12.2->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 16)) (1.54.0)
Requirement already satisfied: google-auth<3,>=1.6.3 in f:\stable-diffusion-webui\venv\lib\site-packages (from tensorboard==2.12.2->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 16)) (2.17.3)
Requirement already satisfied: google-auth-oauthlib<1.1,>=0.5 in f:\stable-diffusion-webui\venv\lib\site-packages (from tensorboard==2.12.2->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 16)) (1.0.0)
Requirement already satisfied: markdown>=2.6.8 in f:\stable-diffusion-webui\venv\lib\site-packages (from tensorboard==2.12.2->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 16)) (3.4.3)
Requirement already satisfied: numpy>=1.12.0 in f:\stable-diffusion-webui\venv\lib\site-packages (from tensorboard==2.12.2->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 16)) (1.23.5)
Requirement already satisfied: protobuf>=3.19.6 in f:\stable-diffusion-webui\venv\lib\site-packages (from tensorboard==2.12.2->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 16)) (4.22.3)
Requirement already satisfied: requests<3,>=2.21.0 in f:\stable-diffusion-webui\venv\lib\site-packages (from tensorboard==2.12.2->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 16)) (2.25.1)
Requirement already satisfied: setuptools>=41.0.0 in f:\stable-diffusion-webui\venv\lib\site-packages (from tensorboard==2.12.2->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 16)) (63.2.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in f:\stable-diffusion-webui\venv\lib\site-packages (from tensorboard==2.12.2->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 16)) (0.7.0)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in f:\stable-diffusion-webui\venv\lib\site-packages (from tensorboard==2.12.2->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 16)) (1.8.1)
Requirement already satisfied: werkzeug>=1.0.1 in f:\stable-diffusion-webui\venv\lib\site-packages (from tensorboard==2.12.2->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 16)) (2.3.2)
Requirement already satisfied: wheel>=0.26 in f:\stable-diffusion-webui\venv\lib\site-packages (from tensorboard==2.12.2->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 16)) (0.40.0)
Requirement already satisfied: tensorflow-intel==2.12.0 in f:\stable-diffusion-webui\venv\lib\site-packages (from tensorflow==2.12.0->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 17)) (2.12.0)
Requirement already satisfied: astunparse>=1.6.0 in f:\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 17)) (1.6.3)
Requirement already satisfied: flatbuffers>=2.0 in f:\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 17)) (23.3.3)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in f:\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 17)) (0.4.0)
Requirement already satisfied: google-pasta>=0.1.1 in f:\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 17)) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in f:\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 17)) (3.8.0)
Requirement already satisfied: jax>=0.3.15 in f:\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 17)) (0.4.8)
Requirement already satisfied: libclang>=13.0.0 in f:\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 17)) (16.0.0)
Requirement already satisfied: opt-einsum>=2.3.2 in f:\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 17)) (3.3.0)
Requirement already satisfied: packaging in f:\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 17)) (23.1)
Requirement already satisfied: six>=1.12.0 in f:\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 17)) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in f:\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 17)) (2.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in f:\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 17)) (4.5.0)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in f:\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 17)) (1.14.1)
Requirement already satisfied: tensorflow-estimator<2.13,>=2.12.0 in f:\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 17)) (2.12.0)
Requirement already satisfied: keras<2.13,>=2.12.0 in f:\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 17)) (2.12.0)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in f:\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.12.0->tensorflow==2.12.0->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 17)) (0.31.0)
Requirement already satisfied: psutil in f:\stable-diffusion-webui\venv\lib\site-packages (from accelerate~=0.18.0->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (5.9.5)
Requirement already satisfied: pyyaml in f:\stable-diffusion-webui\venv\lib\site-packages (from accelerate~=0.18.0->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (6.0)
Requirement already satisfied: torch>=1.4.0 in f:\stable-diffusion-webui\venv\lib\site-packages (from accelerate~=0.18.0->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (2.0.0+cu118)
Requirement already satisfied: filelock in f:\stable-diffusion-webui\venv\lib\site-packages (from diffusers~=0.15.1->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (3.12.0)
Requirement already satisfied: huggingface-hub>=0.13.2 in f:\stable-diffusion-webui\venv\lib\site-packages (from diffusers~=0.15.1->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (0.14.1)
Requirement already satisfied: importlib-metadata in f:\stable-diffusion-webui\venv\lib\site-packages (from diffusers~=0.15.1->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (6.6.0)
Requirement already satisfied: regex!=2019.12.17 in f:\stable-diffusion-webui\venv\lib\site-packages (from diffusers~=0.15.1->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (2023.3.23)
Collecting requests<3,>=2.21.0 (from tensorboard==2.12.2->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 16))
Using cached requests-2.29.0-py3-none-any.whl (62 kB)
Requirement already satisfied: pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2 in f:\stable-diffusion-webui\venv\lib\site-packages (from fastapi~=0.94.1->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 6)) (1.10.7)
Requirement already satisfied: starlette<0.27.0,>=0.26.1 in f:\stable-diffusion-webui\venv\lib\site-packages (from fastapi~=0.94.1->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 6)) (0.26.1)
Requirement already satisfied: gitdb<5,>=4.0.1 in f:\stable-diffusion-webui\venv\lib\site-packages (from gitpython~=3.1.31->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 7)) (4.0.10)
Requirement already satisfied: colorama in f:\stable-diffusion-webui\venv\lib\site-packages (from tqdm~=4.64.1->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (0.4.6)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in f:\stable-diffusion-webui\venv\lib\site-packages (from transformers~=4.26.1->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 12)) (0.13.3)
Requirement already satisfied: smmap<6,>=3.0.1 in f:\stable-diffusion-webui\venv\lib\site-packages (from gitdb<5,>=4.0.1->gitpython~=3.1.31->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 7)) (5.0.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in f:\stable-diffusion-webui\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard==2.12.2->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 16)) (5.3.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in f:\stable-diffusion-webui\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard==2.12.2->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 16)) (0.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in f:\stable-diffusion-webui\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard==2.12.2->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 16)) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in f:\stable-diffusion-webui\venv\lib\site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard==2.12.2->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 16)) (1.3.1)
Requirement already satisfied: fsspec in f:\stable-diffusion-webui\venv\lib\site-packages (from huggingface-hub>=0.13.2->diffusers~=0.15.1->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (2023.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in f:\stable-diffusion-webui\venv\lib\site-packages (from requests<3,>=2.21.0->tensorboard==2.12.2->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 16)) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in f:\stable-diffusion-webui\venv\lib\site-packages (from requests<3,>=2.21.0->tensorboard==2.12.2->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 16)) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in f:\stable-diffusion-webui\venv\lib\site-packages (from requests<3,>=2.21.0->tensorboard==2.12.2->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 16)) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in f:\stable-diffusion-webui\venv\lib\site-packages (from requests<3,>=2.21.0->tensorboard==2.12.2->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 16)) (2022.12.7)
Requirement already satisfied: anyio<5,>=3.4.0 in f:\stable-diffusion-webui\venv\lib\site-packages (from starlette<0.27.0,>=0.26.1->fastapi~=0.94.1->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 6)) (3.6.2)
Requirement already satisfied: sympy in f:\stable-diffusion-webui\venv\lib\site-packages (from torch>=1.4.0->accelerate~=0.18.0->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (1.11.1)
Requirement already satisfied: networkx in f:\stable-diffusion-webui\venv\lib\site-packages (from torch>=1.4.0->accelerate~=0.18.0->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (3.1)
Requirement already satisfied: jinja2 in f:\stable-diffusion-webui\venv\lib\site-packages (from torch>=1.4.0->accelerate~=0.18.0->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (3.1.2)
Requirement already satisfied: MarkupSafe>=2.1.1 in f:\stable-diffusion-webui\venv\lib\site-packages (from werkzeug>=1.0.1->tensorboard==2.12.2->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 16)) (2.1.2)
Requirement already satisfied: zipp>=0.5 in f:\stable-diffusion-webui\venv\lib\site-packages (from importlib-metadata->diffusers~=0.15.1->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (3.15.0)
Requirement already satisfied: sniffio>=1.1 in f:\stable-diffusion-webui\venv\lib\site-packages (from anyio<5,>=3.4.0->starlette<0.27.0,>=0.26.1->fastapi~=0.94.1->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 6)) (1.3.0)
Requirement already satisfied: ml-dtypes>=0.0.3 in f:\stable-diffusion-webui\venv\lib\site-packages (from jax>=0.3.15->tensorflow-intel==2.12.0->tensorflow==2.12.0->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 17)) (0.1.0)
Requirement already satisfied: scipy>=1.7 in f:\stable-diffusion-webui\venv\lib\site-packages (from jax>=0.3.15->tensorflow-intel==2.12.0->tensorflow==2.12.0->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 17)) (1.10.1)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in f:\stable-diffusion-webui\venv\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard==2.12.2->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 16)) (0.5.0)
Requirement already satisfied: oauthlib>=3.0.0 in f:\stable-diffusion-webui\venv\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard==2.12.2->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 16)) (3.2.2)
Requirement already satisfied: mpmath>=0.19 in f:\stable-diffusion-webui\venv\lib\site-packages (from sympy->torch>=1.4.0->accelerate~=0.18.0->-r F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (1.3.0)
WARNING: Ignoring invalid distribution -llow (f:\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution - (f:\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -llow (f:\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (f:\stable-diffusion-webui\venv\lib\site-packages)
Installing collected packages: requests, Pillow, gitpython, transformers, fastapi
Attempting uninstall: requests
Found existing installation: requests 2.25.1
Uninstalling requests-2.25.1:
Successfully uninstalled requests-2.25.1
Attempting uninstall: Pillow
Found existing installation: Pillow 9.4.0
Uninstalling Pillow-9.4.0:
Successfully uninstalled Pillow-9.4.0
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'F:\\stable-diffusion-webui\\venv\\Lib\\site-packages\\~0l\\_imaging.cp310-win_amd64.pyd'
Check the permissions.

stderr: Traceback (most recent call last):
  File "F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\install.py", line 35, in <module>
    actual_install()
  File "F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\postinstall.py", line 41, in actual_install
    install_requirements()
  File "F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\postinstall.py", line 87, in install_requirements
    raise grepexc
  File "F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\postinstall.py", line 75, in install_requirements
    pip_install("-r", req_file)
  File "F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\postinstall.py", line 53, in pip_install
    output = subprocess.check_output(
  File "C:\Python310\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['F:\\stable-diffusion-webui\\venv\\Scripts\\python.exe', '-m', 'pip', 'install', '-r', 'F:\\stable-diffusion-webui\\extensions\\sd_dreambooth_extension\\requirements.txt']' returned non-zero exit status 1.

#######################################################################################################
```

### 2. Describe the bug
Iwant to use existing (nonsquare) images in classification image folder instead of generating them,
therefore, I switched to dev branch of the dreambooth according to this thread.
https://github.com/d8ahazard/sd_dreambooth_extension/issues/1180

But then it cannot allow me to create lora or continue training anymore

**Steps to reproduce the problem**
1.Switch to dev branch and pull
2.Create a new lora, or continue lora training
3.This happens

**What should have happened?**
It should allow me to continue training or creaking new lora

### 3. Provide logs

```
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py", line 1188, in <lambda>
    fn=lambda: check_progress_call_initial(),
  File "F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py", line 202, in check_progress_call_initial
    status.begin()
  File "F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\shared.py", line 224, in begin
    if self.status_handler:
AttributeError: 'DreamState' object has no attribute 'status_handler'
Duration: 00:00:00
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\utils\utils.py", line 184, in f
    status.begin()
  File "F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\shared.py", line 224, in begin
    if self.status_handler:
AttributeError: 'DreamState' object has no attribute 'status_handler'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\utils\utils.py", line 189, in f
    status.end()
  File "F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\shared.py", line 235, in end
    if self.status_handler:
AttributeError: 'DreamState' object has no attribute 'status_handler'
```

### 4. Environment

What OS?
Windows Native

What GPU are you using?
RTX 4070ti

**Comment by andypotato** [comment]
Same issue under WIndows 11 / Dev branch

**Comment by dsalvat1** [comment]
Same problem using Ubuntu 22.04

`  File "/home/dsalvat1/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", lin   
e 1075, in process_api result = await self.call_function(File "/home/dsalvat1/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 884, in call_function prediction = await anyio.to_thread.run_sync(File "/home/dsalvat1/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync return await get_asynclib().run_sync_in_worker_thread(File "/home/dsalvat1/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread return await future
  File "/home/dsalvat1/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_async 
io.py", line 867, in run result = context.run(func, *args)
  File "/home/dsalvat1/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/utils/util
s.py", line 198, in f
    status.end()
  File "/home/dsalvat1/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/shared.py" 
, line 235, in end
    if self.status_handler:                                 
AttributeError: 'DreamState' object has no attribute 'status_handler' `
