### ISSUE TITLE
Dreambooth failing to install or work

### ISSUE THREAD

**Issue by NaitorStudios** [d8ahazard/sd_dreambooth_extension#1211]
## ⚠️If you do not follow the template, your issue may be closed without a response ⚠️
Kindly read and fill this form in its entirety.

### 0. Initial troubleshooting
Please check each of these before opening an issue. If you've checked them, **delete this section of your bug report**. Have you:
- Updated the Stable-Diffusion-WebUI to the latest version? Yes
- Updated Dreambooth to the latest revision? Yes
- Completely restarted the stable-diffusion-webUI, not just reloaded the UI? Yes
- Read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)? Yes

### 1. Please find the following lines in the console and paste them below.
I can't find the lines bellow; it doesn't appear when I launch Stable Diffusion WebUI and I don't have a Dreambooth tab because it never initiated correctly.

```
#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: bd3fecc3d27d777a4e8f3206a0b16e852877dbad
SD-WebUI revision: 

[+] torch version 2.0.0+cu118 installed.
[+] torchvision version 0.15.1+cu118 installed.
[+] xformers version 0.0.17+b6be33a.d20230315 installed.
[+] accelerate version 0.17.1 installed.
[+] bitsandbytes version 0.35.4 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.27.1 installed.

#######################################################################################################
```

### 2. Describe the bug

After installing it, either through the extensions tab or manually, I get lots of errors when initializing WebUI, and it doesn't appear to be working.

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the
db_config.json file from /models/dreambooth/MODELNAME/db_config.json

### 3. Provide logs

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

```st
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 5ab7f213bec2f816f9c5644becb32eb72c8ffb89
Installing requirements


Error running install.py for extension D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\extensions\sd_dreambooth_extension.
Command: "D:\Program Files (Standalone)\Stable Diffusion WebUI\system\python\python.exe" "D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\extensions\sd_dreambooth_extension\install.py"
Error code: 1
stdout: If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: 926ae204ef5de17efca2059c334b6098492a0641
# Requirement installation exception:
Ignoring tensorboard: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
Ignoring tensorflow-macos: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
Ignoring tensorflow-metal: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
Requirement already satisfied: accelerate~=0.18.0 in d:\program files (standalone)\stable diffusion webui\system\python\lib\site-packages (from -r D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (0.18.0)
Collecting bitsandbytes==0.35.4
Using cached bitsandbytes-0.35.4-py3-none-any.whl (62.5 MB)
Collecting dadaptation~=1.5.0
Using cached dadaptation-1.5-py3-none-any.whl
Collecting diffusers~=0.14.0
Using cached diffusers-0.14.0-py3-none-any.whl (737 kB)
Collecting discord-webhook~=1.1.0
Using cached discord_webhook-1.1.0-py3-none-any.whl (12 kB)
Requirement already satisfied: fastapi~=0.94.1 in d:\program files (standalone)\stable diffusion webui\system\python\lib\site-packages (from -r D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\extensions\sd_dreambooth_extension\requirements.txt (line 6)) (0.94.1)
Collecting gitpython~=3.1.31
Using cached GitPython-3.1.31-py3-none-any.whl (184 kB)
Collecting lion-pytorch~=0.0.7
Using cached lion_pytorch-0.0.7-py3-none-any.whl (4.3 kB)
Requirement already satisfied: Pillow~=9.4.0 in d:\program files (standalone)\stable diffusion webui\system\python\lib\site-packages (from -r D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (9.4.0)
Collecting tqdm~=4.64.1
Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
Requirement already satisfied: transformers~=4.26.1 in d:\program files (standalone)\stable diffusion webui\system\python\lib\site-packages (from -r D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\extensions\sd_dreambooth_extension\requirements.txt (line 11)) (4.26.1)
Requirement already satisfied: tensorboard==2.12.0 in d:\program files (standalone)\stable diffusion webui\system\python\lib\site-packages (from -r D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (2.12.0)
Collecting tensorflow==2.12.0
Using cached tensorflow-2.12.0-cp310-cp310-win_amd64.whl (1.9 kB)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in d:\program files (standalone)\stable diffusion webui\system\python\lib\site-packages (from tensorboard==2.12.0->-r D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (0.7.0)
Requirement already satisfied: wheel>=0.26 in d:\program files (standalone)\stable diffusion webui\system\python\lib\site-packages (from tensorboard==2.12.0->-r D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (0.38.4)
Requirement already satisfied: protobuf>=3.19.6 in d:\program files (standalone)\stable diffusion webui\system\python\lib\site-packages (from tensorboard==2.12.0->-r D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (3.20.0)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in d:\program files (standalone)\stable diffusion webui\system\python\lib\site-packages (from tensorboard==2.12.0->-r D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (1.8.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in d:\program files (standalone)\stable diffusion webui\system\python\lib\site-packages (from tensorboard==2.12.0->-r D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (2.16.2)
Requirement already satisfied: requests<3,>=2.21.0 in d:\program files (standalone)\stable diffusion webui\system\python\lib\site-packages (from tensorboard==2.12.0->-r D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (2.25.1)
Requirement already satisfied: werkzeug>=1.0.1 in d:\program files (standalone)\stable diffusion webui\system\python\lib\site-packages (from tensorboard==2.12.0->-r D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (2.2.3)
Requirement already satisfied: absl-py>=0.4 in d:\program files (standalone)\stable diffusion webui\system\python\lib\site-packages (from tensorboard==2.12.0->-r D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (1.4.0)
Requirement already satisfied: markdown>=2.6.8 in d:\program files (standalone)\stable diffusion webui\system\python\lib\site-packages (from tensorboard==2.12.0->-r D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (3.4.1)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in d:\program files (standalone)\stable diffusion webui\system\python\lib\site-packages (from tensorboard==2.12.0->-r D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (0.4.6)
Requirement already satisfied: numpy>=1.12.0 in d:\program files (standalone)\stable diffusion webui\system\python\lib\site-packages (from tensorboard==2.12.0->-r D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (1.23.5)
Requirement already satisfied: setuptools>=41.0.0 in d:\program files (standalone)\stable diffusion webui\system\python\lib\site-packages (from tensorboard==2.12.0->-r D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (67.6.0)
Requirement already satisfied: grpcio>=1.48.2 in d:\program files (standalone)\stable diffusion webui\system\python\lib\site-packages (from tensorboard==2.12.0->-r D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (1.51.3)
Collecting tensorflow-intel==2.12.0
Using cached tensorflow_intel-2.12.0-cp310-cp310-win_amd64.whl (272.8 MB)
Collecting astunparse>=1.6.0
Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting wrapt<1.15,>=1.11.0
Using cached wrapt-1.14.1-cp310-cp310-win_amd64.whl (35 kB)
Collecting jax>=0.3.15
Using cached jax-0.4.8.tar.gz (1.2 MB)
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'done'
ERROR: Exception:
Traceback (most recent call last):
File "D:\Program Files (Standalone)\Stable Diffusion WebUI\system\python\lib\site-packages\pip\_internal\cli\base_command.py", line 160, in exc_logging_wrapper
status = run_func(*args)
File "D:\Program Files (Standalone)\Stable Diffusion WebUI\system\python\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
return func(self, options, args)
File "D:\Program Files (Standalone)\Stable Diffusion WebUI\system\python\lib\site-packages\pip\_internal\commands\install.py", line 419, in run
requirement_set = resolver.resolve(
File "D:\Program Files (Standalone)\Stable Diffusion WebUI\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
result = self._result = resolver.resolve(
File "D:\Program Files (Standalone)\Stable Diffusion WebUI\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 481, in resolve
state = resolution.resolve(requirements, max_rounds=max_rounds)
File "D:\Program Files (Standalone)\Stable Diffusion WebUI\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 373, in resolve
failure_causes = self._attempt_to_pin_criterion(name)
File "D:\Program Files (Standalone)\Stable Diffusion WebUI\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 213, in _attempt_to_pin_criterion
criteria = self._get_updated_criteria(candidate)
File "D:\Program Files (Standalone)\Stable Diffusion WebUI\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 204, in _get_updated_criteria
self._add_to_criteria(criteria, requirement, parent=candidate)
File "D:\Program Files (Standalone)\Stable Diffusion WebUI\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
if not criterion.candidates:
File "D:\Program Files (Standalone)\Stable Diffusion WebUI\system\python\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
return bool(self._sequence)
File "D:\Program Files (Standalone)\Stable Diffusion WebUI\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
return any(self)
File "D:\Program Files (Standalone)\Stable Diffusion WebUI\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
return (c for c in iterator if id(c) not in self._incompatible_ids)
File "D:\Program Files (Standalone)\Stable Diffusion WebUI\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
candidate = func()
File "D:\Program Files (Standalone)\Stable Diffusion WebUI\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
self._link_candidate_cache[link] = LinkCandidate(
File "D:\Program Files (Standalone)\Stable Diffusion WebUI\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 297, in __init__
super().__init__(
File "D:\Program Files (Standalone)\Stable Diffusion WebUI\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 162, in __init__
self.dist = self._prepare()
File "D:\Program Files (Standalone)\Stable Diffusion WebUI\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 231, in _prepare
dist = self._prepare_distribution()
File "D:\Program Files (Standalone)\Stable Diffusion WebUI\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 308, in _prepare_distribution
return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
File "D:\Program Files (Standalone)\Stable Diffusion WebUI\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 491, in prepare_linked_requirement
return self._prepare_linked_requirement(req, parallel_builds)
File "D:\Program Files (Standalone)\Stable Diffusion WebUI\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 577, in _prepare_linked_requirement
dist = _get_prepared_distribution(
File "D:\Program Files (Standalone)\Stable Diffusion WebUI\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 69, in _get_prepared_distribution
abstract_dist.prepare_distribution_metadata(
File "D:\Program Files (Standalone)\Stable Diffusion WebUI\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 48, in prepare_distribution_metadata
self._install_build_reqs(finder)
File "D:\Program Files (Standalone)\Stable Diffusion WebUI\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 118, in _install_build_reqs
build_reqs = self._get_build_requires_wheel()
File "D:\Program Files (Standalone)\Stable Diffusion WebUI\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 95, in _get_build_requires_wheel
return backend.get_requires_for_build_wheel()
File "D:\Program Files (Standalone)\Stable Diffusion WebUI\system\python\lib\site-packages\pip\_internal\utils\misc.py", line 701, in get_requires_for_build_wheel
return super().get_requires_for_build_wheel(config_settings=cs)
File "D:\Program Files (Standalone)\Stable Diffusion WebUI\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 166, in get_requires_for_build_wheel
return self._call_hook('get_requires_for_build_wheel', {
File "D:\Program Files (Standalone)\Stable Diffusion WebUI\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook
raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
File "D:\Program Files (Standalone)\Stable Diffusion WebUI\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
obj = import_module(mod_path)
File "importlib\__init__.py", line 126, in import_module
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 883, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "C:\Users\NaitorStudios\AppData\Local\Temp\pip-build-env-uyzuf8jb\overlay\Lib\site-packages\setuptools\__init__.py", line 15, in <module>
import setuptools.version
File "C:\Users\NaitorStudios\AppData\Local\Temp\pip-build-env-uyzuf8jb\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
from ._importlib import metadata
File "C:\Users\NaitorStudios\AppData\Local\Temp\pip-build-env-uyzuf8jb\overlay\Lib\site-packages\setuptools\_importlib.py", line 44, in <module>
import importlib.metadata as metadata  # noqa: F401
File "importlib\metadata\__init__.py", line 17, in <module>
File "importlib\metadata\_adapters.py", line 3, in <module>
File "email\message.py", line 15, in <module>
File "email\utils.py", line 29, in <module>
File "socket.py", line 51, in <module>
ModuleNotFoundError: No module named '_socket'
[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

stderr: Traceback (most recent call last):
  File "D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\extensions\sd_dreambooth_extension\install.py", line 35, in <module>
    actual_install()
  File "D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\extensions\sd_dreambooth_extension\postinstall.py", line 41, in actual_install
    install_requirements()
  File "D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\extensions\sd_dreambooth_extension\postinstall.py", line 87, in install_requirements
    raise grepexc
  File "D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\extensions\sd_dreambooth_extension\postinstall.py", line 75, in install_requirements
    pip_install("-r", req_file)
  File "D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\extensions\sd_dreambooth_extension\postinstall.py", line 53, in pip_install
    output = subprocess.check_output(
  File "subprocess.py", line 420, in check_output
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['D:\\Program Files (Standalone)\\Stable Diffusion WebUI\\system\\python\\python.exe', '-m', 'pip', 'install', '-r', 'D:\\Program Files (Standalone)\\Stable Diffusion WebUI\\webui\\extensions\\sd_dreambooth_extension\\requirements.txt']' returned non-zero exit status 2.




Launching Web UI with arguments: --xformers --no-half --no-half-vae
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
Civitai Helper: No setting file, use default
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
ControlNet v1.1.132
ControlNet v1.1.132
Exception importing api
Traceback (most recent call last):
  File "D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\extensions\sd_dreambooth_extension\scripts\api.py", line 27, in <module>
    from dreambooth.dataclasses.db_config import from_file, DreamboothConfig
  File "D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\extensions\sd_dreambooth_extension\dreambooth\dataclasses\db_config.py", line 10, in <module>
    from dreambooth.utils.image_utils import get_scheduler_names  # noqa
  File "D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\extensions\sd_dreambooth_extension\dreambooth\utils\image_utils.py", line 11, in <module>
    from diffusers.schedulers import KarrasDiffusionSchedulers
ModuleNotFoundError: No module named 'diffusers'
Error loading script: main.py
Traceback (most recent call last):
  File "D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\extensions\sd_dreambooth_extension\scripts\main.py", line 7, in <module>
    from dreambooth.dataclasses.db_config import (
  File "D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\extensions\sd_dreambooth_extension\dreambooth\dataclasses\db_config.py", line 10, in <module>
    from dreambooth.utils.image_utils import get_scheduler_names  # noqa
  File "D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\extensions\sd_dreambooth_extension\dreambooth\utils\image_utils.py", line 11, in <module>
    from diffusers.schedulers import KarrasDiffusionSchedulers
ModuleNotFoundError: No module named 'diffusers'

Loading weights [e6415c4892] from D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\models\Stable-diffusion\realisticVisionV20_v20.safetensors
Creating model from config: D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying xformers cross attention optimization.
Model loaded in 64.1s (load weights from disk: 4.3s, create model: 0.4s, apply weights to model: 56.7s, move model to device: 1.0s, load textual inversion embeddings: 1.8s).
*Deforum ControlNet support: enabled*
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Error executing callback app_started_callback for D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\extensions\sd_dreambooth_extension\scripts\api.py
Traceback (most recent call last):
  File "D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\modules\script_callbacks.py", line 108, in app_started_callback
    c.callback(demo, app)
  File "D:\Program Files (Standalone)\Stable Diffusion WebUI\webui\extensions\sd_dreambooth_extension\scripts\api.py", line 524, in dreambooth_api
    model_cfg: DreamboothConfig = Body(description="The config to save"),
NameError: name 'DreamboothConfig' is not defined

Startup time: 86.4s (import torch: 3.1s, import gradio: 0.8s, import ldm: 0.9s, other imports: 2.7s, list SD models: 0.2s, setup codeformer: 0.2s, load scripts: 9.7s, load SD checkpoint: 64.3s, create ui: 4.0s, gradio launch: 0.5s).

```

### 4. Environment

What OS? Windows

If Windows - WSL or native? Native

What GPU are you using? RTX 4080

**Comment by andypotato** [comment]
I'm seeing the same issue with both dev and dev-vlad branches. I'm on Windows 11 / RTX 3060 GPU

**Comment by wzgrx** [comment]
Uninstalling cannot solve this problem either

**Comment by dsalvat1** [comment]
"ModuleNotFoundError: No module named 'diffusers'" ??

**Comment by swumagic** [comment]
After each update, the requirements.txt must be modified as follows.   
extensions\sd_dreambooth_extension\requirements.txt。it run ok。

accelerate~=0.18.0
bitsandbytes==0.35.4
dadaptation~=3.1
diffusers~=0.16.1
discord-webhook~=1.1.0
fastapi~=0.94.1
gitpython~=3.1.31
lion-pytorch~=0.0.7
Pillow~=9.5.0
tqdm~=4.64.1
transformers~=4.25.1 # > 4.26.x causes issues (db extension #1110)
