### ISSUE TITLE
dreambooth training issue

### ISSUE THREAD

**Issue by garg-aayush** [d8ahazard/sd_dreambooth_extension#1219]
### 1. Please find the following lines in the console and paste them below.

```
#######################################################################################################
Initializing Dreambooth
Dreambooth revision: 926ae204ef5de17efca2059c334b6098492a0641
Successfully installed fastapi-0.94.1 gitpython-3.1.31 google-auth-oauthlib-0.4.6 requests-2.30.0 transformers-4.26.1

Does your project take forever to startup?
Repetitive dependency installation may be the reason.
Automatic1111's base project sets strict requirements on outdated dependencies.
If an extension is using a newer version, the dependency is uninstalled and reinstalled twice every startup.

[!] xformers NOT installed.
[+] torch version 2.0.0+cu118 installed.
[+] torchvision version 0.15.1+cu118 installed.
[+] accelerate version 0.18.0 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.
#######################################################################################################
```

### 2. Describe the bug

I am trying to run a dreambooth training using automatic1111 [dreambooth extension](https://github.com/d8ahazard/sd_dreambooth_extension) The dreambooth extension installation works perfectly fine.
However, when I try to run a training. The training abrutly ends with the following error:

```bash
# partial main error
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
automatic1111 commit: 5ab7f213bec2f816f9c5644becb32eb72c8ffb89.

### 3. Provide logs

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

```st
Initializing bucket counter!
  ***** Running training *****
  Num batches each epoch = 19
  Num Epochs = 100
  Batch Size Per Device = 1
  Gradient Accumulation steps = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Text Encoder Epochs: 0
  Total optimization steps = 1900
  Total training steps = 1900
  Resuming from checkpoint: False
  First resume epoch: 0
  First resume step: 0
  Lora: False, Optimizer: 8bit AdamW, Prec: no
  Gradient Checkpointing: False
  EMA: False
  UNET: True
  Freeze CLIP Normalization Layers: False
  LR: 2e-06
  V2: False
Steps:   0%|                                                                                                                                                            | 0/1900 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/aayush/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 727, in start_training
    result = main(class_gen_method=class_gen_method)
  File "/home/aayush/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1371, in main
    return inner_loop()
  File "/home/aayush/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 119, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "/home/aayush/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1233, in inner_loop
    accelerator.backward(loss)
  File "/home/aayush/stable-diffusion-webui/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1683, in backward
    loss.backward(**kwargs)
  File "/home/aayush/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/aayush/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/aayush/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/home/aayush/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 2348, in backward
    out = call_compiled_backward()
  File "/home/aayush/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 2319, in call_compiled_backward
    CompiledFunction.compiled_bw = aot_config.bw_compiler(
  File "/home/aayush/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_dynamo/backends/common.py", line 38, in _wrapped_bw_compiler
    return eval_frame.disable(eval_frame.disable(bw_compiler)(*args, **kwargs))
  File "/home/aayush/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/home/aayush/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/aayush/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 441, in bw_compiler
    return inner_compile(
  File "/home/aayush/miniconda3/envs/automate111/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/aayush/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_dynamo/debug_utils.py", line 595, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs)
  File "/home/aayush/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_inductor/debug.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/home/aayush/miniconda3/envs/automate111/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/aayush/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 190, in compile_fx_inner
    compiled_fn = cudagraphify(
  File "/home/aayush/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/aayush/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 257, in cudagraphify
    return cudagraphify_impl(model, inputs, static_input_idxs)
  File "/home/aayush/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 320, in cudagraphify_impl
    model(list(static_inputs))
  File "/tmp/torchinductor_aayush/zr/czrgmabju54635h3ub2gyshwdpw23myiorfldqot376o6wvgz7s4.py", line 188, in call
    buf4 = torch.ops.aten._scaled_dot_product_efficient_attention_backward.default(as_strided(buf0, (1, 8, 1024, 80), (655360, 80, 640, 1)), permute_3, permute_4, permute_5, getitem, getitem_1)
  File "/home/aayush/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_ops.py", line 287, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

### 4. Environment

OS: Ubuntu 20.04
GPU: RTX 4090

**Comment by Dwuuds** [comment]
same error here

**Comment by james-things** [comment]
Just built a new PC around a 4090 and also getting this error, when following the same setup that worked on my 1080Ti. Trying to work out what the actual problem is but the error gives little to go off of.

**Comment by garg-aayush** [comment]
I haven't been able to find a solution to this issue. However there is a workaround, if you downgrade you automate1111 to the `a9fed7`,  you are able to run dreambooth extension. 
Not the best of solutions, but kinda works!
