### ISSUE TITLE
creating model with inpainting checkpoint gives error

### ISSUE THREAD

**Issue by mixbag** [d8ahazard/sd_dreambooth_extension#122]
when i try to create a model with [stable-diffusion-inpainting](https://huggingface.co/runwayml/stable-diffusion-inpainting) checkpoint i run into error. The error is like this-

Traceback (most recent call last):
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 283, in run_predict
    output = await app.blocks.process_api(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 936, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 777, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\conversion.py", line 861, in extract_checkpoint
    unet.load_state_dict(converted_unet_checkpoint)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UNet2DConditionModel:
        size mismatch for conv_in.weight: copying a param with shape torch.Size([320, 9, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 4, 3, 3]).

**Comment by mykeehu** [comment]
The opening page reads:
It also adds several other features, including training multiple concepts simultaneously, and (Coming soon) Inpainting training.

So it is not yet necessary to train with the inpainting model. Otherwise I'm looking forward to it, because I would use it.

**Comment by mixbag** [comment]
Opps.
