### ISSUE TITLE
dependencies missing in requirements.txt

### ISSUE THREAD

**Issue by zpdDG4gta8XKpMCd** [d8ahazard/sd_dreambooth_extension#1225]
it looks like you guys never tried installing your extension on a blank `venv`

i don't know which exact versions are supposed to be but this is what i used to make this extension work

```
    xformers==0.0.17 # rather than xformers==0.0.17.dev447 like in webui-user-dreambooth.bat
    bitsandbytes=0.38.1
    diffusers==0.16.1
    discord_webhook==0.17.0
```

from `webui-user-dreambooth.bat`
```
set "XFORMERS_PACKAGE=xformers==0.0.17.dev447"
```
results
```
ERROR: Could not find a version that satisfies the requirement xformers==0.0.17.dev447 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.16rc424, 0.0.16rc425, 0.0.16, 0.0.17rc481, 0.0.17rc482, 0.0.17, 0.0.18, 0.0.19.dev523, 0.0.19.dev524, 0.0.19, 0.0.20.dev526, 0.0.20.dev527, 0.0.20.dev528)
ERROR: No matching distribution found for xformers==0.0.17.dev447
```

not sure where this comes from
```
[!] bitsandbytes NOT installed.

#######################################################################################################
#                                       LIBRARY ISSUE DETECTED                                        #
#######################################################################################################
#
# bitsandbytes not installed.
#
# Dreambooth may not work properly.
#
# TROUBLESHOOTING
# 1. Fully restart your project (not just the webpage)
# 2. Update your A1111 project and extensions
# 3. Dreambooth requirements should have installed automatically, but you can manually install them
#    by running the following 4 commands from the A1111 project root:
cd venv/Scripts
activate
cd ../..
pip install -r ./extensions/sd_dreambooth_extension/requirements.txt
#######################################################################################################
```

from `sd_dreambooth_extension\dreambooth\webhook.py`
```
Error loading script: main.py
Traceback (most recent call last):
  File "D:\sd\sdwi\modules\scripts.py", line 257, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\sd\sdwi\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\sd\sdwi\extensions\sd_dreambooth_extension\scripts\main.py", line 51, in <module>
    from dreambooth.webhook import save_and_test_webhook
  File "D:\sd\sdwi\extensions\sd_dreambooth_extension\dreambooth\webhook.py", line 6, in <module>
    import discord_webhook
ModuleNotFoundError: No module named 'discord_webhook'
```
from `sd_dreambooth_extension\dreambooth\utils\image_utils.py`
```
Error loading script: main.py
Traceback (most recent call last):
  File "D:\sd\sdwi\modules\scripts.py", line 257, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\sd\sdwi\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\sd\sdwi\extensions\sd_dreambooth_extension\scripts\main.py", line 7, in <module>
    from dreambooth.dataclasses.db_config import (
  File "D:\sd\sdwi\extensions\sd_dreambooth_extension\dreambooth\dataclasses\db_config.py", line 10, in <module>
    from dreambooth.utils.image_utils import get_scheduler_names  # noqa
  File "D:\sd\sdwi\extensions\sd_dreambooth_extension\dreambooth\utils\image_utils.py", line 11, in <module>
    from diffusers.schedulers import KarrasDiffusionSchedulers
ModuleNotFoundError: No module named 'diffusers'
```

**Comment by swumagic** [comment]
After each update, the requirements.txt must be modified as follows.   
extensions\sd_dreambooth_extension\requirements.txt。it run ok。

accelerate~=0.18.0
bitsandbytes==0.35.4
dadaptation~=3.1
diffusers~=0.16.1
discord-webhook~=1.1.0
fastapi~=0.94.1
gitpython~=3.1.31
lion-pytorch~=0.0.7
Pillow~=9.5.0
tqdm~=4.64.1
transformers~=4.25.1 # > 4.26.x causes issues (db extension #1110)
