### ISSUE TITLE
error while saving first checkpoint during training

### ISSUE THREAD

**Issue by rahulchhajer** [d8ahazard/sd_dreambooth_extension#1232]
Hello
i am facing below error just after start of training process probably while saving 1st checkpoint. error is:

Steps:   6%| | 320/5120 [[04:18](https://www.youtube.com/watch?v=QN1vdGhjcRc&t=258s)<[25:55](https://www.youtube.com/watch?v=QN1vdGhjcRc&t=1555s),  3.08it/s, inst_loss=0, loss=0.0115, lr=1e-6, prior_loss=0.0153, vTraceback (most recent call last):                                                  | 0/4 [[00:00](https://www.youtube.com/watch?v=QN1vdGhjcRc&t=0s)<?, ?it/s]
  File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 727, in start_training
    result = main(class_gen_method=class_gen_method)
  File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1371, in main
    return inner_loop()
  File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 119, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1331, in inner_loop
    check_save(True)
  File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 758, in check_save
    save_weights(
  File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 805, in save_weights
    s_pipeline = DiffusionPipeline.from_pretrained(
  File "/workspace/venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 847, in from_pretrained
    raise ValueError(
'
'
'
'
'
) is of type: <class 'torch._dynamo.eval_frame.OptimizedModule'>, but should be <class 'diffusers.models.modeling_utils.ModelMixin'>
Saving weights:   0%|                                                              | 0/4 [[00:01](https://www.youtube.com/watch?v=QN1vdGhjcRc&t=1s)<?, ?it/s]
Steps:   6%| | 320/5120 [[04:20](https://www.youtube.com/watch?v=QN1vdGhjcRc&t=260s)<[1:05:09](https://www.youtube.com/watch?v=QN1vdGhjcRc&t=3909s),  1.23it/s, inst_loss=0, loss=0.0115, lr=1e-6, prior_loss=0.0153, 
Restored system models.
Duration: [00:04:35](https://www.youtube.com/watch?v=QN1vdGhjcRc&t=275s)

pls help me out to overcome this

**Comment by fractaldna22** [comment]
for "stabilityai/sd-vae-ft-mse" for the vae *, ive been finding it
impossible for it to create the vae correctly unless using a pretrained one.
