### ISSUE TITLE
torch._dynamo.config.*

### ISSUE THREAD

**Issue by Robin-Collins** [d8ahazard/sd_dreambooth_extension#1246]
```
#######################################################################################################
Using TCMalloc: libtcmalloc.so.4
Python 3.10.6 (main, May 30 2023, 18:05:58) [GCC 12.2.0]
Version: v1.3.0
Commit hash: 20ae71faa8ef035c31aa3a410b707d792c8203a3
Installing requirements
If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: 926ae204ef5de17efca2059c334b6098492a0641
Successfully installed Pillow-9.4.0 fastapi-0.94.1 gitpython-3.1.31 google-auth-oauthlib-0.4.6 transformers-4.26.1

Does your project take forever to startup?
Repetitive dependency installation may be the reason.
Automatic1111's base project sets strict requirements on outdated dependencies.
If an extension is using a newer version, the dependency is uninstalled and reinstalled twice every startup.

[+] xformers version 0.0.17 installed.
[+] torch version 2.0.1+cu118 installed.
[+] torchvision version 0.15.2+cu118 installed.
[+] accelerate version 0.18.0 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.
```

### 2. Describe the bug

Attempting to train fails, does not complete first "step", does load class images

**Screenshots/Config**
{
    "adamw_weight_decay": 0.01,
    "adaptation_beta1": 0,
    "adaptation_beta2": 0,
    "adaptation_d0": 1e-08,
    "adaptation_eps": 1e-08,
    "attention": "xformers",
    "cache_latents": true,
    "clip_skip": 1,
    "concepts_list": [
        {
            "class_data_dir": "/home/tech/ai/ai_training/trixie_class",
            "class_guidance_scale": 7,
            "class_infer_steps": 20,
            "class_negative_prompt": "black and white photo, painting",
            "class_prompt": "photo of a female person, woman",
            "class_token": "",
            "instance_data_dir": "/home/tech/ai/ai_training/trixie",
            "instance_prompt": "photo of a zwx female person, woman",
            "instance_token": "",
            "is_valid": true,
            "n_save_sample": 4,
            "num_class_images_per": 10,
            "sample_seed": -1,
            "save_guidance_scale": 7,
            "save_infer_steps": 20,
            "save_sample_negative_prompt": "",
            "save_sample_prompt": "",
            "save_sample_template": ""
        }
    ],
    "concepts_path": "",
    "custom_model_name": "trixie_v1",
    "noise_scheduler": "DDPM",
    "deterministic": false,
    "ema_predict": false,
    "epoch": 0,
    "epoch_pause_frequency": 0,
    "epoch_pause_time": 0,
    "freeze_clip_normalization": false,
    "gradient_accumulation_steps": 2,
    "gradient_checkpointing": true,
    "gradient_set_to_none": true,
    "graph_smoothing": 50,
    "half_model": false,
    "train_unfrozen": false,
    "has_ema": false,
    "hflip": false,
    "infer_ema": false,
    "initial_revision": 0,
    "learning_rate": 2e-06,
    "learning_rate_min": 1e-06,
    "lifetime_revision": 0,
    "lora_learning_rate": 0.0001,
    "lora_model_name": null,
    "lora_unet_rank": 4,
    "lora_txt_rank": 4,
    "lora_txt_learning_rate": 5e-05,
    "lora_txt_weight": 1,
    "lora_weight": 1,
    "lr_cycles": 1,
    "lr_factor": 0.5,
    "lr_power": 1,
    "lr_scale_pos": 0.5,
    "lr_scheduler": "constant_with_warmup",
    "lr_warmup_steps": 500,
    "max_token_length": 75,
    "mixed_precision": "bf16",
    "model_name": "trixie",
    "model_dir": "/home/tech/ai/stable-diffusion-webui/models/dreambooth/trixie",
    "model_path": "/home/tech/ai/stable-diffusion-webui/models/dreambooth/trixie",
    "num_train_epochs": 100,
    "offset_noise": 0,
    "optimizer": "Torch AdamW",
    "pad_tokens": true,
    "pretrained_model_name_or_path": "/home/tech/ai/stable-diffusion-webui/models/dreambooth/trixie/working",
    "pretrained_vae_name_or_path": "",
    "prior_loss_scale": false,
    "prior_loss_target": 100.0,
    "prior_loss_weight": 0.75,
    "prior_loss_weight_min": 0.1,
    "resolution": 512,
    "revision": 0,
    "sample_batch_size": 4,
    "sanity_prompt": "",
    "sanity_seed": 420420.0,
    "save_ckpt_after": true,
    "save_ckpt_cancel": false,
    "save_ckpt_during": false,
    "save_ema": true,
    "save_embedding_every": 25,
    "save_lora_after": true,
    "save_lora_cancel": false,
    "save_lora_during": false,
    "save_lora_for_extra_net": false,
    "save_preview_every": 5,
    "save_safetensors": true,
    "save_state_after": false,
    "save_state_cancel": false,
    "save_state_during": false,
    "scheduler": "DEISMultistep",
    "shuffle_tags": true,
    "snapshot": "",
    "split_loss": true,
    "src": "/home/tech/ai/models/RPG-v4.ckpt",
    "stop_text_encoder": 0,
    "strict_tokens": false,
    "tf32_enable": false,
    "train_batch_size": 1,
    "train_imagic": false,
    "train_unet": true,
    "use_concepts": false,
    "use_ema": false,
    "use_lora": true,
    "use_lora_extended": false,
    "use_subdir": true,
    "v2": false
}
### 3. Provide logs

```st
Launching Web UI with arguments: --api --xformers --ckpt-dir /home/tech/ai/models --vae-path /home/tech/ai/models/vae-ft-mse-840000-ema-pruned.ckpt
2023-05-30 18:29:33.656329: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-30 18:29:34.202218: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: /home/tech/ai/stable-diffusion-webui/extensions/Stable-Diffusion-Webui-Civitai-Helper/setting.json
Civitai Helper: No setting file, use default
ControlNet v1.1.153
ControlNet v1.1.153
Loading weights [b400691d74] from /home/tech/ai/models/RPG-v4.ckpt
Creating model from config: /home/tech/ai/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights from commandline argument: /home/tech/ai/models/vae-ft-mse-840000-ema-pruned.ckpt
Textual inversion embeddings loaded(5): bad-picture-chill-75v, bad_prompt_version2-neg, easynegative, realisticvision-negative-embedding, style-psycho
Model loaded in 2.0s (load weights from disk: 0.7s, create model: 0.3s, apply weights to model: 0.4s, apply half(): 0.3s, load VAE: 0.1s, move model to device: 0.2s).
Applying optimization: xformers... done.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 8.8s (import torch: 1.9s, import gradio: 0.7s, import ldm: 0.5s, other imports: 0.4s, setup codeformer: 0.2s, load scripts: 3.3s, create ui: 1.2s, gradio launch: 0.3s).
Custom model name is trixie_v1
Initializing dreambooth training...
The version of diffusers is less than or equal to 0.14.0. Performing monkey-patch...
Pre-processing images: trixie_class: : 0it [00:00, ?it/s]                                                                                           
Nothing to generate.
Found 180 reg images.
Preparing dataset...
Init dataset!
Preparing Dataset (With Caching)
Caching latents...:   0%|                                                                                                   | 0/198 [00:00<?, ?it/s]Loading cached latents...
Bucket 0 (512, 512, 0) - Instance Images: 18 | Class Images: 180 | Max Examples/batch:  36                                                          
Caching latents...: 100%|████████████████████████████████████████████████████████████████████████████████████████| 198/198 [00:00<00:00, 154.73it/s]Saving cache!
Total Buckets 1 - Instance Images: 18 | Class Images: 180 | Max Examples/batch:  36                                                                 
Caching latents...: 100%|████████████████████████████████████████████████████████████████████████████████████████| 198/198 [00:00<00:00, 154.73it/s]
Total images / batch: 36, total examples: 36
Caching latents...: 100%|████████████████████████████████████████████████████████████████████████████████████████| 198/198 [00:00<00:00, 302.53it/s]
Total dataset length (steps): 36
Initializing bucket counter!
  ***** Running training *****
  Num batches each epoch = 36
  Num Epochs = 100
  Batch Size Per Device = 1
  Gradient Accumulation steps = 2
  Total train batch size (w. parallel, distributed & accumulation) = 2
  Text Encoder Epochs: 0
  Total optimization steps = 1800
  Total training steps = 3600
  Resuming from checkpoint: False
  First resume epoch: 0
  First resume step: 0
  Lora: True, Optimizer: Torch AdamW, Prec: bf16
  Gradient Checkpointing: True
  EMA: False
  UNET: True
  Freeze CLIP Normalization Layers: False
  LR: 0.0001
  V2: False
Steps:   0%|                                                                                                               | 0/3600 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/tech/ai/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 727, in start_training
    result = main(class_gen_method=class_gen_method)
  File "/home/tech/ai/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1371, in main
    return inner_loop()
  File "/home/tech/ai/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 119, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "/home/tech/ai/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1169, in inner_loop
    noise_pred = unet(
  File "/home/tech/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tech/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/accelerate/utils/operations.py", line 495, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/home/tech/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/tech/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/home/tech/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/home/tech/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 582, in forward
    sample, res_samples = downsample_block(
  File "/home/tech/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tech/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/unet_2d_blocks.py", line 828, in forward
    hidden_states = torch.utils.checkpoint.checkpoint(create_custom_forward(resnet), hidden_states, temb)
  File "/home/tech/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/tech/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/tech/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 81, in forward
    ctx.fwd_cpu_state = torch.get_rng_state()
  File "/home/tech/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 337, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/home/tech/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 404, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/home/tech/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "/home/tech/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "/home/tech/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/tech/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 324, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/tech/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 445, in transform_code_object
    transformations(instructions, code_options)
  File "/home/tech/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 311, in transform
    tracer.run()
  File "/home/tech/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1726, in run
    super().run()
  File "/home/tech/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 576, in run
    and self.step()
  File "/home/tech/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 540, in step
    getattr(self, inst.opname)(inst)
  File "/home/tech/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 342, in wrapper
    return inner_fn(self, inst)
  File "/home/tech/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 965, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/tech/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 474, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/tech/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_dynamo/variables/torch.py", line 368, in call_function
    return wrap_fx_proxy(
  File "/home/tech/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py", line 754, in wrap_fx_proxy
    return wrap_fx_proxy_cls(
  File "/home/tech/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py", line 812, in wrap_fx_proxy_cls
    assert "source" in options and options["source"] is not None
AssertionError: 

from user code:
   File "/home/tech/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/random.py", line 23, in get_rng_state
    return default_generator.get_state()

Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True

```

### 4. Environment

What OS?
Ubuntu 23.04 Linux

What GPU are you using?
RTX 3090

**Comment by Llugaes** [comment]
same issue with Ubuntu22.04 RTX4090
`line 23, in get_rng_state return default_generator.get_state() Set torch._dynamo.config.verbose=True for more information You can suppress this exception and fall back to eager by setting: torch._dynamo.config.suppress_errors = True`

**Comment by DanielXu123** [comment]
same problem ...
CentOS 7.9.2009(Core) 3090TI

**Comment by Robin-Collins** [comment]
bump

**Comment by codgodtao** [comment]
any update on here? i meet same problem!
