### ISSUE TITLE
[Bug]: Exception when attempting to install Dreambooth requirements.

### ISSUE THREAD

**Issue by Kayliii** [d8ahazard/sd_dreambooth_extension#1264]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When attempting to install the Dreambooth extension, the batchfile meant to install the requirements raises an exception.

### Steps to reproduce the problem

1. Install Dreambooth extension in the webui
2. Exit the webui
3. Run the provided `webui-user.bat` for installing the requirements

### Commit and libraries

N/A

### Command Line Arguments

Normally I use `--xformers --no-half --autolaunch --theme dark` but the crash occurs regardless of whether I use any arguments.

### Console logs

```Shell
ERROR: Exception:
Traceback (most recent call last):
  File "D:\sd.webui\system\python\lib\site-packages\pip\_internal\cli\base_command.py", line 169, in exc_logging_wrapper    status = run_func(*args)
  File "D:\sd.webui\system\python\lib\site-packages\pip\_internal\cli\req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "D:\sd.webui\system\python\lib\site-packages\pip\_internal\commands\install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "D:\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "D:\sd.webui\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "D:\sd.webui\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "D:\sd.webui\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "D:\sd.webui\system\python\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
    return bool(self._sequence)
  File "D:\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "D:\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "D:\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "D:\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "D:\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 293, in __init__
    super().__init__(
  File "D:\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "D:\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "D:\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 304, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "D:\sd.webui\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 516, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "D:\sd.webui\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 631, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "D:\sd.webui\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 69, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "D:\sd.webui\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 48, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "D:\sd.webui\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 118, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
  File "D:\sd.webui\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 95, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
  File "D:\sd.webui\system\python\lib\site-packages\pip\_internal\utils\misc.py", line 692, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
  File "D:\sd.webui\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "D:\sd.webui\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "D:\sd.webui\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Main\AppData\Local\Temp\pip-build-env-h0xsusrk\overlay\Lib\site-packages\setuptools\__init__.py", line 15, in <module>
    import setuptools.version
  File "C:\Users\Main\AppData\Local\Temp\pip-build-env-h0xsusrk\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
    from ._importlib import metadata
  File "C:\Users\Main\AppData\Local\Temp\pip-build-env-h0xsusrk\overlay\Lib\site-packages\setuptools\_importlib.py", line 44, in <module>
    import importlib.metadata as metadata  # noqa: F401
  File "importlib\metadata\__init__.py", line 17, in <module>
  File "importlib\metadata\_adapters.py", line 3, in <module>
  File "email\message.py", line 15, in <module>
  File "email\utils.py", line 29, in <module>
  File "socket.py", line 51, in <module>
ModuleNotFoundError: No module named '_socket'
```

### Additional information

I use Windows 11 Home, and I have an RTX 4070.

I also tried to modify the `requirements.txt` as follows, as was said in similar issues that have already been closed, but it didn't change anything:
```
accelerate~=0.18.0
bitsandbytes==0.35.4
dadaptation~=3.1
diffusers~=0.16.1
discord-webhook~=1.1.0
fastapi~=0.94.1
gitpython~=3.1.31
lion-pytorch~=0.0.7
Pillow~=9.5.0
tqdm~=4.64.1
transformers~=4.25.1 # > 4.26.x causes issues (db extension https://github.com/d8ahazard/sd_dreambooth_extension/issues/1110)
```

**Comment by ArrowM** [comment]
Having the Commits and Library section of the issue template is required. If your project doesn't launch to that point. Activate your python venv, and send the output of pip freeze and your python version

**Comment by Hadrien-Estela** [comment]
same error. cannot install dreambooth extension

**Comment by MarcRichet** [comment]
Same here, new fresh installation of SD,  change libs version to match to webUI one, or manual install of the extension doesn't work either,

**Comment by MarcRichet** [comment]
I found a solution to this problem : I delete totally the "System/python" folder, put a new one from AUTOMATIC1111 distrib 1.0.0 and run the the run.bat with the extension enabled

It's work now for me !

**Comment by luis-arellano** [comment]
got the same error now
