### ISSUE TITLE
[Bug]: Unable to use "Adan Dadaptation" Optimizer with "dadapt_with_warmup" Learning Rate Scheduler

### ISSUE THREAD

**Issue by ashleykleynhans** [d8ahazard/sd_dreambooth_extension#1270]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Enabling both "Adan Dadaptation" Optimizer and "dadapt_with_warmup" Learning Rate Scheduler results in "ValueError: Expected 1 lr_lambdas, but got 2".

### Steps to reproduce the problem

1. Set Learning Rate Scheduler to "dadapt_with_warmup".
2. Set Optimizer to "Adan Dadaptation".
3. Train model.
4. Observe error.

### Commit and libraries

```
Initializing Dreambooth
Dreambooth revision: 1566e3a793d03212177966a8d3718832f9d3109f
Successfully installed tensorboard-2.13.0
[+] xformers version 0.0.20 installed.
[+] torch version 2.0.1+cu118 installed.
[+] torchvision version 0.15.2+cu118 installed.
[+] accelerate version 0.19.0 installed.
[+] diffusers version 0.16.1 installed.
[+] transformers version 4.29.2 installed.
[+] bitsandbytes version 0.35.4 installed.
```

### Command Line Arguments

```Shell
--port 3000 \
  --listen \
  --no-hashing \
  --skip-python-version-check \
  --skip-torch-cuda-test \
  --enable-insecure-extension-access \
  --api \
  --skip-version-check \
  --skip-install \
  --ckpt-dir /workspace/stable-diffusion-webui/models/Stable-diffusion
```

### Console logs

```Shell
Traceback (most recent call last):
  File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 729, in start_training
    result = main(class_gen_method=class_gen_method)
  File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1546, in main
    return inner_loop()
  File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 119, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 585, in inner_loop
    lr_scheduler = UniversalScheduler(
  File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/optimization.py", line 533, in __init__
    self.scheduler = get_scheduler(
  File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/optimization.py", line 496, in get_scheduler
    return get_dadapt_with_warmup(
  File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/optimization.py", line 81, in get_dadapt_with_warmup
    return LambdaLR(optimizer, [unet_lambda, tenc_lambda], last_epoch=-1, verbose=False)
  File "/workspace/venv/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 218, in __init__
    raise ValueError("Expected {} lr_lambdas, but got {}".format(
ValueError: Expected 1 lr_lambdas, but got 2
```

**Comment by TheForgotten69** [comment]
Tried everything and got the same error

**Comment by ashleykleynhans** [comment]
This is still an issue and should not be closed.

**Comment by jj-a-li** [comment]
这个问题的确存在，不应该关闭

**Comment by LeroyDaydreamer** [comment]
As a temporary workaround I removed the text encoder parameter from the call of the torch optimizer: 

I changed dreambooth_extension/dreambooth/optimization.py", line 81 

`return LambdaLR(optimizer, [unet_lambda, tenc_lambda], last_epoch=-1, verbose=False)`

to

`return LambdaLR(optimizer, [unet_lambda], last_epoch=-1, verbose=False)`

This seems to work, obviously the text encoder can then not be trained.

**Comment by jj-a-li** [comment]
不训练text encoder,这不能算是修复了问题

**Comment by ashleykleynhans** [comment]
Still an issue, so please fix.
