### ISSUE TITLE
[Bug]: BFloat16 error during sample image generation

### ISSUE THREAD

**Issue by ashleykleynhans** [d8ahazard/sd_dreambooth_extension#1275]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

`RuntimeError: "triu_tril_cuda_template" not implemented for 'BFloat16'` error is returned during training which prevents sample image from being generated.  The training continues, but no sample images are generated throughout.

### Steps to reproduce the problem

1. Create a new model.
2. Configure the Dreambooth settings for the new model.
3. Ensure that sample preview images is set.
4. Start training.
5. Observe BFloat16 error when sample images are being generated, resulting in no sample images.

### Commit and libraries

Initializing Dreambooth
Dreambooth revision: dc413a14379b165355502d9f65856c40a4bb5b6f
[+] xformers version 0.0.20 installed.
[+] torch version 2.0.1+cu118 installed.
[+] torchvision version 0.15.2+cu118 installed.
[+] accelerate version 0.19.0 installed.
[+] diffusers version 0.16.1 installed.
[+] transformers version 4.29.2 installed.
[+] bitsandbytes version 0.35.4 installed.

### Command Line Arguments

```Shell
--listen \
  --no-hashing \
  --skip-python-version-check \
  --skip-torch-cuda-test \
  --enable-insecure-extension-access \
  --api \
  --skip-version-check \
  --skip-install
```

### Console logs

```Shell
Traceback (most recent call last): | 0/4 [00:00<?, ?it/s]
  File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1033, in save_weights
    s_image = s_pipeline(
  File "/workspace/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/venv/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 645, in __call__
    prompt_embeds = self._encode_prompt(
  File "/workspace/venv/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 357, in _encode_prompt
    prompt_embeds = self.text_encoder(
  File "/workspace/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/venv/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/workspace/venv/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 816, in forward
    return self.text_model(
  File "/workspace/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/venv/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 717, in forward
    causal_attention_mask = self._build_causal_attention_mask(
  File "/workspace/venv/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 760, in _build_causal_attention_mask
    mask.triu_(1)  # zero out the lower diagonal
RuntimeError: "triu_tril_cuda_template" not implemented for 'BFloat16'
```

**Comment by ashleykleynhans** [comment]
This still needs to be merged into the main branch.

**Comment by FurkanGozukara** [comment]
> This still needs to be merged into the main branch.

please merge people having issues

**Comment by ashleykleynhans** [comment]
Its merged into dev but not main.
