### ISSUE TITLE
Apple silicon Mac can not train lora on the latest release 

### ISSUE THREAD

**Issue by elisezhu123** [d8ahazard/sd_dreambooth_extension#1281]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

My Mac can train the lora model by this extension for the release publish in May1 40c0318 but after I update to the latest release, it can no longer training (but just show Refer to https://github.com/facebookresearch/xformers for more information on how to install xformers)

### Steps to reproduce the problem

1. cd to path
2. ./webui.sh 
3. dream booth 
4. train lora 
5. choose model setting add folders, add parameter with (lion, no default for optimizer) /(torch Adam also not work) 

### Commit and libraries

Initializing dreambooth training...
Pre-processing images: classifiers_0: : 58it [00:00, 630.71it/s]
We need a total of 110 class images.: : 48it [00:00, 7887.12it/s]00:00<?, ?it/s]
Generating 110 class images for training...
                                                                               Traceback (most recent call last): 0%|                   | 0/110 [00:00<?, ?it/s]
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 729, in start_training
    result = main(class_gen_method=class_gen_method)
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1548, in main
    return inner_loop()
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 119, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 246, in inner_loop
    count, instance_prompts, class_prompts = generate_classifiers(
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/utils/gen_utils.py", line 153, in generate_classifiers
    builder = ImageBuilder(
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/helpers/image_builder.py", line 110, in __init__
    self.image_pipe.enable_xformers_memory_efficient_attention()
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1448, in enable_xformers_memory_efficient_attention
    self.set_use_memory_efficient_attention_xformers(True, attention_op)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1474, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1464, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 227, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 223, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 223, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 223, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 220, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/attention.py", line 105, in set_use_memory_efficient_attention_xformers
    raise ModuleNotFoundError(
ModuleNotFoundError: Refer to https://github.com/facebookresearch/xformers for more information on how to install xformers
Generating class images 0/110::   0%|                   | 0/110 [00:01<?, ?it/s]
Restored system models.
Duration: 00:00:02
Custom model name is Anya_forger
Initializing dreambooth training...
Pre-processing images: classifiers_0: : 58it [00:00, 661.41it/s]
We need a total of 110 class images.: : 48it [00:00, 9929.31it/s]00:00<?, ?it/s]
Generating 110 class images for training...
                                                                               Traceback (most recent call last): 0%|                   | 0/110 [00:00<?, ?it/s]
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 729, in start_training
    result = main(class_gen_method=class_gen_method)
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1548, in main
    return inner_loop()
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 119, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 246, in inner_loop
    count, instance_prompts, class_prompts = generate_classifiers(
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/utils/gen_utils.py", line 153, in generate_classifiers
    builder = ImageBuilder(
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/helpers/image_builder.py", line 110, in __init__
    self.image_pipe.enable_xformers_memory_efficient_attention()
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1448, in enable_xformers_memory_efficient_attention
    self.set_use_memory_efficient_attention_xformers(True, attention_op)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1474, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1464, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 227, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 223, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 223, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 223, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 220, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/attention.py", line 105, in set_use_memory_efficient_attention_xformers
    raise ModuleNotFoundError(
ModuleNotFoundError: Refer to https://github.com/facebookresearch/xformers for more information on how to install xformers
Generating class images 0/110::   0%|                   | 0/110 [00:00<?, ?it/s]
Restored system models.
Duration: 00:00:02
Custom model name is Anya_forger
Initializing dreambooth training...
Pre-processing images: classifiers_0: : 58it [00:00, 654.46it/s]
We need a total of 110 class images.: : 48it [00:00, 9716.53it/s]00:00<?, ?it/s]
Generating 110 class images for training...
                                                                               Traceback (most recent call last): 0%|                   | 0/110 [00:00<?, ?it/s]
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 729, in start_training
    result = main(class_gen_method=class_gen_method)
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1548, in main
    return inner_loop()
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 119, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 246, in inner_loop
    count, instance_prompts, class_prompts = generate_classifiers(
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/utils/gen_utils.py", line 153, in generate_classifiers
    builder = ImageBuilder(
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/helpers/image_builder.py", line 110, in __init__
    self.image_pipe.enable_xformers_memory_efficient_attention()
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1448, in enable_xformers_memory_efficient_attention
    self.set_use_memory_efficient_attention_xformers(True, attention_op)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1474, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1464, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 227, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 223, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 223, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 223, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 220, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/attention.py", line 105, in set_use_memory_efficient_attention_xformers
    raise ModuleNotFoundError(
ModuleNotFoundError: Refer to https://github.com/facebookresearch/xformers for more information on how to install xformers
Generating class images 0/110::   0%|                   | 0/110 [00:00<?, ?it/s]
Restored system models.
Duration: 00:00:02

### Command Line Arguments

```Shell
cd path 
./webui.sh
```

### Console logs

```Shell
elise123@elise123deMacBook-Pro stable-diffusion-webui % ./webui.sh

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on elise123 user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Python 3.10.12 (main, Jun  7 2023, 00:38:32) [Clang 14.0.3 (clang-1403.0.22.14.1)]
Version: v1.3.2
Commit hash: baf6946e06249c5af9851c60171692c44ef633e0
Installing requirements

No module 'xformers'. Proceeding without it.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: dc413a14379b165355502d9f65856c40a4bb5b6f
Successfully installed accelerate-0.19.0 dadaptation-3.1 diffusers-0.16.1 fastapi-0.94.1 gitpython-3.1.31 google-auth-oauthlib-0.4.6 lion-pytorch-0.1.2 tensorboard-data-server-0.6.1 tqdm-4.65.0 transformers-4.29.2

Does your project take forever to startup?
Repetitive dependency installation may be the reason.
Automatic1111's base project sets strict requirements on outdated dependencies.
If an extension is using a newer version, the dependency is uninstalled and reinstalled twice every startup.

[!] xformers NOT installed.
[+] torch version 2.0.1 installed.
[+] torchvision version 0.15.2 installed.
[+] accelerate version 0.19.0 installed.
[+] diffusers version 0.16.1 installed.
[+] transformers version 4.29.2 installed.
[+] bitsandbytes version 0.35.4 installed.

Launching Web UI with arguments: --skip-torch-cuda-test --upcast-sampling --no-half-vae --use-cpu interrogate
No module 'xformers'. Proceeding without it.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
dirname:  /Users/elise123/Sites/stable-diffusion-webui/localizations
localizations:  {'zh_CN': '/Users/elise123/Sites/stable-diffusion-webui/extensions/sd-webui-bilingual-localization/localizations/zh_CN.json'}
2023-06-13 22:34:21,962 - ControlNet - INFO - ControlNet v1.1.224
ControlNet preprocessor location: /Users/elise123/Sites/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
2023-06-13 22:34:22,052 - ControlNet - INFO - ControlNet v1.1.224
Loading weights [cbfba64e66] from /Users/elise123/Sites/stable-diffusion-webui/models/Stable-diffusion/CounterfeitV30_v30.safetensors
Creating model from config: /Users/elise123/Sites/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Couldn't find VAE named vaedelicatecolcors_v10.pt; using None instead
Textual inversion embeddings loaded(2): EasyNegative, EasyNegativeV2
Model loaded in 1.9s (load weights from disk: 0.2s, create model: 0.5s, apply weights to model: 0.4s, apply half(): 0.2s, move model to device: 0.5s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 7.7s (import torch: 2.3s, import gradio: 0.5s, import ldm: 0.2s, other imports: 0.6s, load scripts: 3.2s, create ui: 0.5s, gradio launch: 0.4s).
 Custom model name is Anya_forger
Initializing dreambooth training...
Pre-processing images: classifiers_0: : 58it [00:00, 630.71it/s]
We need a total of 110 class images.: : 48it [00:00, 7887.12it/s]00:00<?, ?it/s]
Generating 110 class images for training...
                                                                               Traceback (most recent call last): 0%|                   | 0/110 [00:00<?, ?it/s]
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 729, in start_training
    result = main(class_gen_method=class_gen_method)
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1548, in main
    return inner_loop()
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 119, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 246, in inner_loop
    count, instance_prompts, class_prompts = generate_classifiers(
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/utils/gen_utils.py", line 153, in generate_classifiers
    builder = ImageBuilder(
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/helpers/image_builder.py", line 110, in __init__
    self.image_pipe.enable_xformers_memory_efficient_attention()
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1448, in enable_xformers_memory_efficient_attention
    self.set_use_memory_efficient_attention_xformers(True, attention_op)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1474, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1464, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 227, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 223, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 223, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 223, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 220, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/attention.py", line 105, in set_use_memory_efficient_attention_xformers
    raise ModuleNotFoundError(
ModuleNotFoundError: Refer to https://github.com/facebookresearch/xformers for more information on how to install xformers
Generating class images 0/110::   0%|                   | 0/110 [00:01<?, ?it/s]
Restored system models.
Duration: 00:00:02
Custom model name is Anya_forger
Initializing dreambooth training...
Pre-processing images: classifiers_0: : 58it [00:00, 661.41it/s]
We need a total of 110 class images.: : 48it [00:00, 9929.31it/s]00:00<?, ?it/s]
Generating 110 class images for training...
                                                                               Traceback (most recent call last): 0%|                   | 0/110 [00:00<?, ?it/s]
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 729, in start_training
    result = main(class_gen_method=class_gen_method)
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1548, in main
    return inner_loop()
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 119, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 246, in inner_loop
    count, instance_prompts, class_prompts = generate_classifiers(
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/utils/gen_utils.py", line 153, in generate_classifiers
    builder = ImageBuilder(
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/helpers/image_builder.py", line 110, in __init__
    self.image_pipe.enable_xformers_memory_efficient_attention()
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1448, in enable_xformers_memory_efficient_attention
    self.set_use_memory_efficient_attention_xformers(True, attention_op)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1474, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1464, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 227, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 223, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 223, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 223, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 220, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/attention.py", line 105, in set_use_memory_efficient_attention_xformers
    raise ModuleNotFoundError(
ModuleNotFoundError: Refer to https://github.com/facebookresearch/xformers for more information on how to install xformers
Generating class images 0/110::   0%|                   | 0/110 [00:00<?, ?it/s]
Restored system models.
Duration: 00:00:02
Custom model name is Anya_forger
Initializing dreambooth training...
Pre-processing images: classifiers_0: : 58it [00:00, 654.46it/s]
We need a total of 110 class images.: : 48it [00:00, 9716.53it/s]00:00<?, ?it/s]
Generating 110 class images for training...
                                                                               Traceback (most recent call last): 0%|                   | 0/110 [00:00<?, ?it/s]
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 729, in start_training
    result = main(class_gen_method=class_gen_method)
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1548, in main
    return inner_loop()
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 119, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 246, in inner_loop
    count, instance_prompts, class_prompts = generate_classifiers(
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/utils/gen_utils.py", line 153, in generate_classifiers
    builder = ImageBuilder(
  File "/Users/elise123/Sites/stable-diffusion-webui/extensions/sd_dreambooth_extension/helpers/image_builder.py", line 110, in __init__
    self.image_pipe.enable_xformers_memory_efficient_attention()
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1448, in enable_xformers_memory_efficient_attention
    self.set_use_memory_efficient_attention_xformers(True, attention_op)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1474, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1464, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 227, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 223, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 223, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 223, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 220, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/Users/elise123/Sites/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/attention.py", line 105, in set_use_memory_efficient_attention_xformers
    raise ModuleNotFoundError(
ModuleNotFoundError: Refer to https://github.com/facebookresearch/xformers for more information on how to install xformers
Generating class images 0/110::   0%|                   | 0/110 [00:00<?, ?it/s]
Restored system models.
Duration: 00:00:02
```

### Additional information

it can still train if I replace it back to my old commit on may 1 but the lartest commit failed no matter what I do

**Comment by elisezhu123** [comment]
my device is m1max 10 32 64gram 4t, it think it is not a memory issue

**Comment by kellan6** [comment]
Have you found a solution to this? Having the exact same problem.

**Comment by leucome** [comment]
Basically same issue on Linux with AMD GPU.  Is there somebody who can point out to were we can find the setting to make it use something else like it did before.
