### ISSUE TITLE
[Bug]: Ask for help to solve the problem, I really can't find any way to solve it. Do not understand where the problem lies?

### ISSUE THREAD

**Issue by 390104431** [d8ahazard/sd_dreambooth_extension#1285]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Error message output after creating the model

Missing model directory, removing model: D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\models\dreambooth\123\working\text_encoder
![image](https://github.com/d8ahazard/sd_dreambooth_extension/assets/89460287/77f4d580-8f4f-4084-b376-39cd70861a8e)

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### Commit and libraries

Starting at `Initializing Dreambooth` and ending several lines below at `[+] bitsandbytes version 0.35.4 installed.`.
Loading model from checkpoint.
Loading ckpt...
Pred and size are epsilon and 512, using config: D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd_dreambooth_extension\dreambooth\..\configs\v1-training-unfrozen.yaml
v1 model loaded.
Trying to load: D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd_dreambooth_extension\dreambooth\..\configs\v1-training-unfrozen.yaml
Converting unet...
Converting vae...
Converting text encoder...
Exception setting up output: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
Traceback (most recent call last):
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "ssl.py", line 513, in wrap_socket
  File "ssl.py", line 1071, in _create
  File "ssl.py", line 1342, in do_handshake
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "ssl.py", line 513, in wrap_socket
  File "ssl.py", line 1071, in _create
  File "ssl.py", line 1342, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd_dreambooth_extension\dreambooth\sd_to_diff.py", line 1290, in extract_checkpoint
    text_model = convert_ldm_clip_checkpoint(checkpoint)
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd_dreambooth_extension\dreambooth\sd_to_diff.py", line 622, in convert_ldm_clip_checkpoint
    text_model = CLIPTextModel.from_pretrained("openai/clip-vit-large-patch14")
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\transformers\modeling_utils.py", line 2472, in from_pretrained
    if has_file(pretrained_model_name_or_path, TF2_WEIGHTS_NAME, **has_file_kwargs):
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\transformers\utils\hub.py", line 610, in has_file
    r = requests.head(url, headers=headers, allow_redirects=False, proxies=proxies, timeout=10)
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\requests\api.py", line 100, in head
    return request("head", url, **kwargs)
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
Missing model directory, removing model: D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\models\dreambooth\123\working\text_encoder
Restored system models.
Duration: 00:00:15
Exception loading config: [Errno 2] No such file or directory: 'D:\\OPENAI\\sd-webui-aki-v4\\sd-webui-aki-v4\\models\\dreambooth\\123\\db_config.json'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
Traceback (most recent call last):
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd_dreambooth_extension\dreambooth\dataclasses\db_config.py", line 410, in from_file
    with open(config_file, 'r') as openfile:
Can't load config!
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\OPENAI\\sd-webui-aki-v4\\sd-webui-aki-v4\\models\\dreambooth\\123\\db_config.json'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
Traceback (most recent call last):
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1229, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1204, in validate_outputs
    raise ValueError(
ValueError: An event handler (load_model_params) didn't receive enough output values (needed: 10, received: 7).
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
Wanted outputs:
    [html, html, html, html, html, html, html, dropdown, dropdown, html]
Received outputs:
    ["", "", "", "", "", {'visible': True, 'choices': [], 'value': '', '__type__': 'generic_update'}, "Error loading model params: '123'."]

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.3.2
Commit hash: baf6946e06249c5af9851c60171692c44ef633e0
Installing requirements

If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: dc413a14379b165355502d9f65856c40a4bb5b6f
Successfully installed accelerate-0.19.0 fastapi-0.94.1 gitpython-3.1.31 transformers-4.29.2

Does your project take forever to startup?
Repetitive dependency installation may be the reason.
Automatic1111's base project sets strict requirements on outdated dependencies.
If an extension is using a newer version, the dependency is uninstalled and reinstalled twice every startup.

[+] xformers version 0.0.17 installed.
[+] torch version 2.0.0+cu118 installed.
[+] torchvision version 0.15.1+cu118 installed.
[+] accelerate version 0.19.0 installed.
[+] diffusers version 0.16.1 installed.
[+] transformers version 4.29.2 installed.
[+] bitsandbytes version 0.35.4 installed.

Launching Web UI with arguments: --theme dark --xformers --api --autolaunch
AUTOMATIC1111/stable-diffusion-webui packed by bilibili@秋葉aaaki 
本整合包完全免费，严禁倒卖。若您付费获得本软件请立刻举报商家。
[AddNet] Updating model hashes...

[AddNet] Updating model hashes...

2023-06-17 19:46:32,286 - ControlNet - INFO - ControlNet v1.1.224
ControlNet preprocessor location: D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd-webui-controlnet\annotator\downloads
2023-06-17 19:46:32,415 - ControlNet - INFO - ControlNet v1.1.224
Loading weights [e1441589a6] from D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\models\Stable-diffusion\Base Model\sd-v1.5.ckpt
Creating model from config: D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Textual inversion embeddings loaded(1): EasyNegative
Model loaded in 3.7s (load weights from disk: 1.7s, create model: 0.4s, apply weights to model: 0.5s, apply half(): 0.5s, move model to device: 0.6s).
Image Browser: ImageReward is not installed, cannot be used.
reading lora D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\models\Lora\Eastasian\eastasianDoll_v40.safetensors: AssertionError
Traceback (most recent call last):
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\extensions-builtin\Lora\lora.py", line 83, in __init__
    self.metadata = sd_models.read_metadata_from_safetensors(filename)
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\modules\sd_models.py", line 230, in read_metadata_from_safetensors
    assert metadata_len > 2 and json_start in (b'{"', b"{'"), f"{filename} is not a safetensors file"
AssertionError: D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\models\Lora\Eastasian\eastasianDoll_v40.safetensors is not a safetensors file
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Applying optimization: xformers... done.
CUDA SETUP: Loading binary D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 16.5s (import torch: 3.9s, import gradio: 0.9s, import ldm: 0.5s, other imports: 0.9s, setup codeformer: 0.2s, load scripts: 7.8s, create ui: 1.1s, gradio launch: 1.1s).
Loading model from checkpoint.
Loading ckpt...
Pred and size are epsilon and 512, using config: D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd_dreambooth_extension\dreambooth\..\configs\v1-training-unfrozen.yaml
v1 model loaded.
Trying to load: D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd_dreambooth_extension\dreambooth\..\configs\v1-training-unfrozen.yaml
Converting unet...
Converting vae...
Converting text encoder...
Exception setting up output: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
Traceback (most recent call last):
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "ssl.py", line 513, in wrap_socket
  File "ssl.py", line 1071, in _create
  File "ssl.py", line 1342, in do_handshake
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "ssl.py", line 513, in wrap_socket
  File "ssl.py", line 1071, in _create
  File "ssl.py", line 1342, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd_dreambooth_extension\dreambooth\sd_to_diff.py", line 1290, in extract_checkpoint
    text_model = convert_ldm_clip_checkpoint(checkpoint)
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd_dreambooth_extension\dreambooth\sd_to_diff.py", line 622, in convert_ldm_clip_checkpoint
    text_model = CLIPTextModel.from_pretrained("openai/clip-vit-large-patch14")
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\transformers\modeling_utils.py", line 2472, in from_pretrained
    if has_file(pretrained_model_name_or_path, TF2_WEIGHTS_NAME, **has_file_kwargs):
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\transformers\utils\hub.py", line 610, in has_file
    r = requests.head(url, headers=headers, allow_redirects=False, proxies=proxies, timeout=10)
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\requests\api.py", line 100, in head
    return request("head", url, **kwargs)
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
Missing model directory, removing model: D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\models\dreambooth\123\working\text_encoder
Restored system models.
Duration: 00:00:15
Exception loading config: [Errno 2] No such file or directory: 'D:\\OPENAI\\sd-webui-aki-v4\\sd-webui-aki-v4\\models\\dreambooth\\123\\db_config.json'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
Traceback (most recent call last):
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\extensions\sd_dreambooth_extension\dreambooth\dataclasses\db_config.py", line 410, in from_file
    with open(config_file, 'r') as openfile:
Can't load config!
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\OPENAI\\sd-webui-aki-v4\\sd-webui-aki-v4\\models\\dreambooth\\123\\db_config.json'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
Traceback (most recent call last):
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1229, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1204, in validate_outputs
    raise ValueError(
ValueError: An event handler (load_model_params) didn't receive enough output values (needed: 10, received: 7).
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
Wanted outputs:
    [html, html, html, html, html, html, html, dropdown, dropdown, html]
Received outputs:
    ["", "", "", "", "", {'visible': True, 'choices': [], 'value': '', '__type__': 'generic_update'}, "Error loading model params: '123'."]
```

### Additional information

Error message output after creating the model

Missing model directory, removing model: D:\OPENAI\sd-webui-aki-v4\sd-webui-aki-v4\models\dreambooth\123\working\text_encoder

**Comment by 390104431** [comment]
I will look at it once a day, I hope the author can help to see how to solve it

**Comment by CJohnDesign** [comment]
I also got this error

**Comment by mmmz28** [comment]
I encountered the same problem and the problem was located to sd_to_diff.py. Run failure at the bottom of the file (roughly on line 1292)
`            tokenizer_type = "CLIPTokenizer"
            if text_model_type == "FrozenOpenCLIPEmbedder":
                text_model = convert_open_clip_checkpoint(checkpoint)
                tokenizer = CLIPTokenizer.from_pretrained("stabilityai/stable-diffusion-2", subfolder="tokenizer")
            elif text_model_type == "FrozenCLIPEmbedder":
                text_model = convert_ldm_clip_checkpoint(checkpoint)
                **tokenizer = CLIPTokenizer.from_pretrained("openai/clip-vit-large-patch14")** # this is the problem
            else:
                text_config = create_ldm_bert_config(original_config)
                text_model = convert_ldm_bert_checkpoint(checkpoint, text_config)
                tokenizer = BertTokenizerFast.from_pretrained("bert-base-uncased")
                tokenizer_type = "BertTokenizerFast"`
I was going to refer [https://github.com/CompVis/stable-diffusion/issues/659] 。But in the evening the Internet was suddenly available, so I was able to download it 
 tokenizer = CLIPTokenizer.from_pretrained("openai/clip-vit-large-patch14") 了

**Comment by 390104431** [comment]
> 我也有这个错误

Have you solved it?

**Comment by HoseaGuo** [comment]
I got the same problem.

**Comment by RHSTD** [comment]
I got the same problem.

**Comment by zming333** [comment]
same problem

**Comment by zming333** [comment]
> same problem

work now. Connection repair by using a proxy
