### ISSUE TITLE
[Bug]: error on Training, An event handler (f) didn't receive enough output values

### ISSUE THREAD

**Issue by eliluong** [d8ahazard/sd_dreambooth_extension#1287]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I successfully created a model from source checkpoint runwayml/stable-diffusion-v1-5. I used Performance Wizard to get base settings, and then put in some information in Concepts and Saving. Then I click train, but it generates an error in the console (nothing appears in UI, and entire application is frozen and requires Docker reboot), as below.

db_config.json file:
```
{
    "weight_decay": 0.01,
    "attention": "xformers",
    "cache_latents": true,
    "clip_skip": 1,
    "concepts_list": [
        {
            "class_data_dir": "",
            "class_guidance_scale": 7.5,
            "class_infer_steps": 40,
            "class_negative_prompt": "",
            "class_prompt": "photo of a dog",
            "class_token": "dog",
            "instance_data_dir": "/data/training",
            "instance_prompt": "photo of zxw",
            "instance_token": "zxw",
            "is_valid": true,
            "n_save_sample": 1,
            "num_class_images_per": 0,
            "sample_seed": -1,
            "save_guidance_scale": 7.5,
            "save_infer_steps": 20,
            "save_sample_negative_prompt": "",
            "save_sample_prompt": "",
            "save_sample_template": ""
        }
    ],
    "concepts_path": "",
    "custom_model_name": "zxwmodel",
    "deterministic": false,
    "disable_class_matching": false,
    "disable_logging": false,
    "ema_predict": false,
    "epoch": 0,
    "epoch_pause_frequency": 0,
    "epoch_pause_time": 0,
    "freeze_clip_normalization": false,
    "gradient_accumulation_steps": 4,
    "gradient_checkpointing": false,
    "gradient_set_to_none": true,
    "graph_smoothing": 50,
    "half_model": false,
    "has_ema": false,
    "hflip": false,
    "infer_ema": false,
    "initial_revision": 0,
    "learning_rate": 2e-06,
    "learning_rate_min": 1e-06,
    "lifetime_revision": 0,
    "lora_learning_rate": 0.0001,
    "lora_model_name": "",
    "lora_txt_learning_rate": 5e-05,
    "lora_txt_rank": 4,
    "lora_txt_weight": 1,
    "lora_unet_rank": 4,
    "lora_weight": 1,
    "lora_use_buggy_requires_grad": false,
    "lr_cycles": 1,
    "lr_factor": 0.5,
    "lr_power": 1,
    "lr_scale_pos": 0.5,
    "lr_scheduler": "constant_with_warmup",
    "lr_warmup_steps": 0,
    "max_token_length": 75,
    "mixed_precision": "bf16",
    "model_dir": "/stable-diffusion-webui/models/dreambooth/lensa_custom",
    "model_name": "lensa_custom",
    "model_path": "/stable-diffusion-webui/models/dreambooth/lensa_custom",
    "noise_scheduler": "DDPM",
    "num_train_epochs": 100,
    "offset_noise": 0,
    "optimizer": "8bit AdamW",
    "pad_tokens": true,
    "pretrained_model_name_or_path": "/stable-diffusion-webui/models/dreambooth/lensa_custom/working",
    "pretrained_vae_name_or_path": "",
    "prior_loss_scale": false,
    "prior_loss_target": 100.0,
    "prior_loss_weight": 0.75,
    "prior_loss_weight_min": 0.1,
    "resolution": 512,
    "revision": 0,
    "sample_batch_size": 4,
    "sanity_prompt": "",
    "sanity_seed": 420420.0,
    "save_ckpt_after": true,
    "save_ckpt_cancel": false,
    "save_ckpt_during": false,
    "save_ema": true,
    "save_embedding_every": 25,
    "save_lora_after": true,
    "save_lora_cancel": false,
    "save_lora_during": false,
    "save_lora_for_extra_net": false,
    "save_preview_every": 5,
    "save_safetensors": true,
    "save_state_after": false,
    "save_state_cancel": false,
    "save_state_during": false,
    "scheduler": "DEISMultistep",
    "shared_diffusers_path": "",
    "shuffle_tags": true,
    "snapshot": "",
    "split_loss": true,
    "src": "runwayml/stable-diffusion-v1-5",
    "stop_text_encoder": 0.75,
    "strict_tokens": false,
    "dynamic_img_norm": false,
    "tenc_weight_decay": 0.01,
    "tenc_grad_clip_norm": 0,
    "tomesd": 0,
    "train_batch_size": 4,
    "train_imagic": false,
    "train_unet": true,
    "train_unfrozen": false,
    "txt_learning_rate": 2e-06,
    "use_concepts": false,
    "use_ema": true,
    "use_lora": false,
    "use_lora_extended": false,
    "use_shared_src": false,
    "use_subdir": true,
    "v2": false
}
```

### Steps to reproduce the problem

1. create model
2. train

### Commit and libraries

```
webui-docker-auto-1  | Initializing Dreambooth
webui-docker-auto-1  | Dreambooth revision: dc413a14379b165355502d9f65856c40a4bb5b6f
webui-docker-auto-1  | Successfully installed accelerate-0.19.0 bitsandbytes-0.35.4 dadaptation-3.1 diffusers-0.16.1 discord-webhook-1.1.0 fastapi-0.94.1 gitpython-3.1.31 lion-pytorch-0.1.2 tensorboard-2.13.0 transformers-4.29.2
webui-docker-auto-1  | [+] xformers version 0.0.21.dev544 installed.
webui-docker-auto-1  | [+] torch version 2.0.1+cu118 installed.
webui-docker-auto-1  | [+] torchvision version 0.15.2+cu118 installed.
webui-docker-auto-1  | [+] accelerate version 0.19.0 installed.
webui-docker-auto-1  | [+] diffusers version 0.16.1 installed.
webui-docker-auto-1  | [+] transformers version 4.29.2 installed.
webui-docker-auto-1  | [+] bitsandbytes version 0.35.4 installed.
```

(I am running [AbdBarho](https://github.com/AbdBarho)/[stable-diffusion-webui-docker](https://github.com/AbdBarho/stable-diffusion-webui-docker) with version [dc413a14](https://github.com/d8ahazard/sd_dreambooth_extension/commit/dc413a14379b165355502d9f65856c40a4bb5b6f) of Dreambooth extension):

version: [v1.3.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/20ae71faa8ef035c31aa3a410b707d792c8203a3)  •  python: 3.10.9  •  torch: 2.0.1+cu118  •  xformers: 0.0.21.dev544  •  gradio: 3.31.0  •  checkpoint: [c6bbc15e32](https://google.com/search?q=c6bbc15e3224e6973459ba78de4998b80b50112b0ae5b5c67113d56b4e366b19)

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
webui-docker-auto-1  | Total images: 16
webui-docker-auto-1  | Largest prime: 2
webui-docker-auto-1  | Best factors: (4, 4)
webui-docker-auto-1  | Total VRAM: 24
webui-docker-auto-1  | Duration: 00:00:00
webui-docker-auto-1  | Error completing request
webui-docker-auto-1  | Arguments: ('lensa_custom', 'Native Diffusers') {}
webui-docker-auto-1  | Traceback (most recent call last):
webui-docker-auto-1  |   File "/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/utils/utils.py", line 200, in f
webui-docker-auto-1  |     res = func(*args, **kwargs)
webui-docker-auto-1  |   File "/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 697, in start_training
webui-docker-auto-1  |     if config.resolution <= 0:
webui-docker-auto-1  | TypeError: '<=' not supported between instances of 'str' and 'int'
webui-docker-auto-1  |
webui-docker-auto-1  | Traceback (most recent call last):
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/gradio/routes.py", line 414, in run_predict
webui-docker-auto-1  |     output = await app.get_blocks().process_api(
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1326, in process_api
webui-docker-auto-1  |     data = self.postprocess_data(fn_index, result["prediction"], state)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1229, in postprocess_data
webui-docker-auto-1  |     self.validate_outputs(fn_index, predictions)  # type: ignore
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1204, in validate_outputs
webui-docker-auto-1  |     raise ValueError(
webui-docker-auto-1  | ValueError: An event handler (f) didn't receive enough output values (needed: 5, received: 3).
webui-docker-auto-1  | Wanted outputs:
webui-docker-auto-1  |     [dropdown, html, html, gallery, html]
webui-docker-auto-1  | Received outputs:
webui-docker-auto-1  |     [None, "", "<div class='error'>TypeError: &#x27;&lt;=&#x27; not supported between instances of &#x27;str&#x27; and &#x27;int&#x27;</div>"]
```

**Comment by eliluong** [comment]
Closing. Unable to do anything when downloading a model from Huggingface for some reason. Pointing it to existing model, such as `v1-5-pruned-emaonly.ckpt` works fine.
