### ISSUE TITLE
[Bug]: [Bug]: A matching Triton is not available, some optimizations will not be enabled. Error caught was: No module named 'triton'

### ISSUE THREAD

**Issue by swumagic** [d8ahazard/sd_dreambooth_extension#1297]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
K:\StableDiffusion\sdwebui\py310\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
loading stable diffusion model: ImportError
Traceback (most recent call last):
  File "K:\StableDiffusion\sdwebui\extensions\sd_dreambooth_extension\install.py", line 33, in <module>
    from postinstall import actual_install
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\StableDiffusion\sdwebui\extensions\sd_dreambooth_extension\postinstall.py", line 14, in <module>
    from dreambooth import shared
  File "<frozen importlib._bootstrap>", line 1078, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\StableDiffusion\sdwebui\extensions\sd_dreambooth_extension\dreambooth\shared.py", line 434, in <module>
    is_auto = load_auto_settings()
  File "K:\StableDiffusion\sdwebui\extensions\sd_dreambooth_extension\dreambooth\shared.py", line 46, in load_auto_settings
    sd_model = ws.sd_model
  File "K:\StableDiffusion\sdwebui\modules\shared.py", line 726, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "K:\StableDiffusion\sdwebui\modules\sd_models.py", line 422, in get_sd_model
    load_model()
  File "K:\StableDiffusion\sdwebui\modules\sd_models.py", line 439, in load_model
    from modules import lowvram, sd_hijack
  File "K:\StableDiffusion\sdwebui\modules\sd_hijack.py", line 5, in <module>
    import modules.textual_inversion.textual_inversion
  File "K:\StableDiffusion\sdwebui\modules\textual_inversion\textual_inversion.py", line 15, in <module>
    from modules import shared, devices, sd_hijack, processing, sd_models, images, sd_samplers, sd_hijack_checkpoint, errors
  File "K:\StableDiffusion\sdwebui\modules\processing.py", line 18, in <module>
    from modules.sd_hijack import model_hijack
ImportError: cannot import name 'model_hijack' from partially initialized module 'modules.sd_hijack' (most likely due to a circular import) (K:\StableDiffusion\sdwebui\modules\sd_hijack.py)
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Stable diffusion model failed to load
loading stable diffusion model: ImportError
Traceback (most recent call last):
  File "K:\StableDiffusion\sdwebui\extensions\sd_dreambooth_extension\install.py", line 33, in <module>
    from postinstall import actual_install
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\StableDiffusion\sdwebui\extensions\sd_dreambooth_extension\postinstall.py", line 14, in <module>
    from dreambooth import shared
  File "<frozen importlib._bootstrap>", line 1078, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\StableDiffusion\sdwebui\extensions\sd_dreambooth_extension\dreambooth\shared.py", line 436, in <module>
    load_vars()
  File "K:\StableDiffusion\sdwebui\extensions\sd_dreambooth_extension\dreambooth\shared.py", line 352, in load_vars
    is_auto = load_auto_settings()
  File "K:\StableDiffusion\sdwebui\extensions\sd_dreambooth_extension\dreambooth\shared.py", line 46, in load_auto_settings
    sd_model = ws.sd_model
  File "K:\StableDiffusion\sdwebui\modules\shared.py", line 726, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "K:\StableDiffusion\sdwebui\modules\sd_models.py", line 422, in get_sd_model
    load_model()
  File "K:\StableDiffusion\sdwebui\modules\sd_models.py", line 439, in load_model
    from modules import lowvram, sd_hijack
  File "K:\StableDiffusion\sdwebui\modules\sd_hijack.py", line 5, in <module>
    import modules.textual_inversion.textual_inversion
  File "K:\StableDiffusion\sdwebui\modules\textual_inversion\textual_inversion.py", line 15, in <module>
    from modules import shared, devices, sd_hijack, processing, sd_models, images, sd_samplers, sd_hijack_checkpoint, errors
  File "K:\StableDiffusion\sdwebui\modules\processing.py", line 18, in <module>
    from modules.sd_hijack import model_hijack
ImportError: cannot import name 'model_hijack' from partially initialized module 'modules.sd_hijack' (most likely due to a circular import) (K:\StableDiffusion\sdwebui\modules\sd_hijack.py)
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

### Steps to reproduce the problem

A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
K:\StableDiffusion\sdwebui\py310\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
loading stable diffusion model: ImportError

### Commit and libraries

Stable diffusion model failed to load
If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: dc413a14379b165355502d9f65856c40a4bb5b6f
[+] xformers version 0.0.19 installed.
[+] torch version 2.0.1+cu118 installed.
[+] torchvision version 0.15.2+cu118 installed.
[+] accelerate version 0.19.0 installed.
[+] diffusers version 0.17.1 installed.
[+] transformers version 4.29.2 installed.
[+] bitsandbytes version 0.35.4 installed.

### Command Line Arguments

```Shell
Launching Web UI with arguments: --medvram --theme dark --xformers --api --autolaunch
```

### Console logs

```Shell
Launching Web UI with arguments: --medvram --theme dark --xformers --api --autolaunch
```

### Additional information

Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]

Launching Web UI with arguments: --medvram --theme dark --xformers --api --autolaunch
AUTOMATIC1111/stable-diffusion-webui packed by bilibili@秋葉aaaki 

=================================================================================
You are running xformers 0.0.19.
The program is tested to work with xformers 0.0.20.
To reinstall the desired version, run with commandline flag --reinstall-xformers.

Use --skip-version-check commandline argument to disable this check.
=================================================================================
python_server_full_path:  K:\StableDiffusion\sdwebui\extensions\Auto-Photoshop-StableDiffusion-Plugin\server/python_server
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: K:\StableDiffusion\sdwebui\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
[-] ADetailer initialized. version: 23.7.1, num models: 8
logs_location: K:\StableDiffusion\sdwebui\extensions\miaoshouai-assistant\logs
[AddNet] Updating model hashes...
[AddNet] Updating model hashes...
dirname:  K:\StableDiffusion\sdwebui\localizations
localizations:  {'zh-Hans (Stable)': 'K:\\StableDiffusion\\sdwebui\\extensions\\stable-diffusion-webui-localization-zh_Hans\\localizations\\zh-Hans (Stable).json', 'zh-Hans (Testing)': 'K:\\StableDiffusion\\sdwebui\\extensions\\stable-diffusion-webui-localization-zh_Hans\\localizations\\zh-Hans (Testing).json', 'zh_CN': 'K:\\StableDiffusion\\sdwebui\\extensions\\stable-diffusion-webui-localization-zh_Hans\\localizations\\zh_CN.json', 'zh_TW': 'K:\\StableDiffusion\\sdwebui\\extensions\\stable-diffusion-webui-localization-zh_Hans\\localizations\\zh_TW.json'}
2023-07-04 06:53:44,624 - ControlNet - INFO - ControlNet v1.1.229
ControlNet preprocessor location: K:\StableDiffusion\sdwebui\extensions\sd-webui-controlnet\annotator\downloads
2023-07-04 06:53:44,850 - ControlNet - INFO - ControlNet v1.1.229
sd-webui-prompt-all-in-one background API service started successfully.
2023-07-04 06:53:52,153 - roop - INFO - roop v0.0.2
2023-07-04 06:53:52,155 - roop - INFO - roop v0.0.2
Loading weights [e6415c4892] from K:\StableDiffusion\sdwebui\models\Stable-diffusion\realisticVisionV20_v20.safetensors
Creating model from config: K:\StableDiffusion\sdwebui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Couldn't find VAE named vae-ft-mse-840000-ema-pruned.safetensors; using None instead
Textual inversion embeddings loaded(49): _shuimo_, advntr, AS-Young, AS-Young-neg, AS-Younger, AS-Youngest, bad-hands-5, bad-picture-chill-75v, bad_pictures, bad_prompt_version2-neg, BadNegAnatomyV1-neg, beautiful_mistake-6500, cloudport, duskametric15, duskametric15 (3900), EasyNegative, ghst-3000, isometric Dreams (Living Room), Isometric TI sets, isometric-ti-sets-pt-2, isometric_dreams, isometric_dreams (300), isometric_dreams (3500), isometric_dreams (6500), isometric_dreams (6800), isometric_dreams (7500), koh_pokimane, logo-with-face-on-shield, magicalinterior, negative_hand-neg, ng_deepnegative_v1_75t, opt-6000, PlanIt, pureerosface_v1, realisticvision-negative-embedding, RFKTR_fshnsta, style-bridal, style-empire, Style-Glass, style-nebmagic, style-paintmagic, style-psycho, style-rustmagic, style-swirlmagic, style-sylvamagic, tzuyu, ulzzang-6500-v1.1, verybadimagenegative_v1.3, yv0nn3
Textual inversion embeddings skipped(1): kc16-v1-4000
Model loaded in 3.2s (load weights from disk: 0.4s, create model: 0.7s, apply weights to model: 0.7s, apply half(): 0.5s, load textual inversion embeddings: 0.1s, calculate empty prompt: 0.7s).
Applying attention optimization: xformers... done.
*Deforum ControlNet support: enabled*
CUDA SETUP: Loading binary K:\StableDiffusion\sdwebui\py310\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.
auto-sd-paint-ext:INFO: Add --listen to COMMANDLINE_ARGS to enable usage as a remote backend.
2023-07-04 06:54:27,952 - main.py [line:47] - INFO: Add --listen to COMMANDLINE_ARGS to enable usage as a remote backend.
2023-07-04 06:54:28,854 - task_runner.py [line:464] - INFO: [AgentScheduler] Task queue is empty
2023-07-04 06:54:28,854 - api.py [line:29] - INFO: [AgentScheduler] Registering APIs
Startup time: 69.1s (import torch: 7.3s, import gradio: 1.8s, import ldm: 0.9s, other imports: 1.9s, setup codeformer: 0.2s, load scripts: 29.8s, create ui: 18.7s, gradio launch: 5.8s, app_started_callback: 2.6s).
preload_extensions_git_metadata for 73 extensions took 41.48s
2023-07-04 06:55:18,872 - _client.py [line:1729] - INFO: HTTP Request: POST http://127.0.0.1:7861/api/predict "HTTP/1.1 200 OK"
2023-07-04 06:55:18,877 - _client.py [line:1729] - INFO: HTTP Request: POST http://127.0.0.1:7861/api/predict "HTTP/1.1 200 OK"
2023-07-04 06:55:18,885 - _client.py [line:1729] - INFO: HTTP Request: POST http://127.0.0.1:7861/reset "HTTP/1.1 200 OK"
2023-07-04 06:55:18,886 - _client.py [line:1729] - INFO: HTTP Request: POST http://127.0.0.1:7861/reset "HTTP/1.1 200 OK"
2023-07-04 06:55:19,443 - _client.py [line:1729] - INFO: HTTP Request: POST http://127.0.0.1:7861/api/predict "HTTP/1.1 200 OK"
2023-07-04 06:55:19,450 - _client.py [line:1729] - INFO: HTTP Request: POST http://127.0.0.1:7861/reset "HTTP/1.1 200 OK"

**Comment by swumagic** [comment]
sdwebui\py310  CMD
1、https://pypi.org/project/cmake/#files
pip install cmake
2、https://huggingface.co/r4ziel/xformers_pre_built/tree/main
triton-2.0.0-cp310-cp310-win_amd64.whl  put in sdwebui\py310

sdwebui\py310  CMD
> python.exe -m pip install triton-2.0.0-cp310-cp310-win_amd64.whl
or .\venv\Scripts\python.exe -m pip install triton-2.0.0-cp310-cp310-win_amd64.whl

**Comment by swumagic** [comment]
it ok.I solved it myself, I searched for hours, refer to the above and you will come to thank me.

**Comment by swumagic** [comment]
M:\SD\sdwebui\py310\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
loading stable diffusion model: ImportError
Traceback (most recent call last):
  File "M:\SD\sdwebui\extensions\sd_dreambooth_extension\install.py", line 33, in <module>
    from postinstall import actual_install
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "M:\SD\sdwebui\extensions\sd_dreambooth_extension\postinstall.py", line 14, in <module>
    from dreambooth import shared
  File "<frozen importlib._bootstrap>", line 1078, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "M:\SD\sdwebui\extensions\sd_dreambooth_extension\dreambooth\shared.py", line 434, in <module>
    is_auto = load_auto_settings()
  File "M:\SD\sdwebui\extensions\sd_dreambooth_extension\dreambooth\shared.py", line 46, in load_auto_settings
    sd_model = ws.sd_model
  File "M:\SD\sdwebui\modules\shared.py", line 726, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "M:\SD\sdwebui\modules\sd_models.py", line 422, in get_sd_model
    load_model()
  File "M:\SD\sdwebui\modules\sd_models.py", line 439, in load_model
    from modules import lowvram, sd_hijack
  File "M:\SD\sdwebui\modules\sd_hijack.py", line 5, in <module>
    import modules.textual_inversion.textual_inversion
  File "M:\SD\sdwebui\modules\textual_inversion\textual_inversion.py", line 15, in <module>
    from modules import shared, devices, sd_hijack, processing, sd_models, images, sd_samplers, sd_hijack_checkpoint, errors
  File "M:\SD\sdwebui\modules\processing.py", line 18, in <module>
    from modules.sd_hijack import model_hijack
ImportError: cannot import name 'model_hijack' from partially initialized module 'modules.sd_hijack' (most likely due to a circular import) (M:\SD\sdwebui\modules\sd_hijack.py)
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Stable diffusion model failed to load
loading stable diffusion model: ImportError
Traceback (most recent call last):
  File "M:\SD\sdwebui\extensions\sd_dreambooth_extension\install.py", line 33, in <module>
    from postinstall import actual_install
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "M:\SD\sdwebui\extensions\sd_dreambooth_extension\postinstall.py", line 14, in <module>
    from dreambooth import shared
  File "<frozen importlib._bootstrap>", line 1078, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "M:\SD\sdwebui\extensions\sd_dreambooth_extension\dreambooth\shared.py", line 436, in <module>
    load_vars()
  File "M:\SD\sdwebui\extensions\sd_dreambooth_extension\dreambooth\shared.py", line 352, in load_vars
    is_auto = load_auto_settings()
  File "M:\SD\sdwebui\extensions\sd_dreambooth_extension\dreambooth\shared.py", line 46, in load_auto_settings
    sd_model = ws.sd_model
  File "M:\SD\sdwebui\modules\shared.py", line 726, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "M:\SD\sdwebui\modules\sd_models.py", line 422, in get_sd_model
    load_model()
  File "M:\SD\sdwebui\modules\sd_models.py", line 439, in load_model
    from modules import lowvram, sd_hijack
  File "M:\SD\sdwebui\modules\sd_hijack.py", line 5, in <module>
    import modules.textual_inversion.textual_inversion
  File "M:\SD\sdwebui\modules\textual_inversion\textual_inversion.py", line 15, in <module>
    from modules import shared, devices, sd_hijack, processing, sd_models, images, sd_samplers, sd_hijack_checkpoint, errors
  File "M:\SD\sdwebui\modules\processing.py", line 18, in <module>
    from modules.sd_hijack import model_hijack
ImportError: cannot import name 'model_hijack' from partially initialized module 'modules.sd_hijack' (most likely due to a circular import) (M:\SD\sdwebui\modules\sd_hijack.py)
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by swumagic** [comment]
but it run the bug.
