### ISSUE TITLE
[Bug]: Error when completing training "requested operation cannot be performed on a file"

### ISSUE THREAD

**Issue by DoctorDevMan** [d8ahazard/sd_dreambooth_extension#1301]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Completed training and received error message "The requested operation cannot be performed on a file with a user-mapped section open."

Tried restarting my computer and ensuring all other apps are closed and didn't run any other automatic1111 processes.

I'm not sure exactly which file the above error message is relating to. However I can confirm diffusion_pytorch_model.safetensors isn't updating and as a result training updates are lost and aren't included when clicking "generate CKPT"

### Steps to reproduce the problem

Open Dreambooth tab
Fill in Parameters
Click Train

### Commit and libraries

[+] xformers version 0.0.17 installed.
[+] torch version 2.0.1+cu118 installed.
[+] torchvision version 0.15.2+cu118 installed.
[+] accelerate version 0.19.0 installed.
[+] diffusers version 0.16.1 installed.
[+] transformers version 4.29.2 installed.
[+] bitsandbytes version 0.35.4 installed.

### Command Line Arguments

```Shell
@echo off



set PYTHON=E:\Programs\Dev\Python3-10-6\python.exe
set GIT=
set VENV_DIR=E:\Programs\Dev\stable-diffusion-webui\venv
set COMMANDLINE_ARGS= --force-cpu

call webui.bat

```

### Console logs

```Shell
venv "E:\Programs\Dev\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.4.0
Commit hash: 394ffa7b0a7fff3ec484bcd084e673a8b301ccc8
Installing requirements
Installing requirements for scikit_learn

Installing SD-CN-Animation requirement: scikit-image




#######################################################################################################
Initializing Civitai Link
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Civitai Link revision: 2dfc03c17304278ca0b456366cc7871a2af8377b
SD-WebUI revision: 394ffa7b0a7fff3ec484bcd084e673a8b301ccc8

Checking Civitai Link requirements...
[!] python-socketio[client] version 5.7.2 NOT installed.

#######################################################################################################

If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: dc413a14379b165355502d9f65856c40a4bb5b6f
Successfully installed accelerate-0.19.0 fastapi-0.94.1 gitpython-3.1.31 transformers-4.29.2


Does your project take forever to startup?
Repetitive dependency installation may be the reason.
Automatic1111's base project sets strict requirements on outdated dependencies.
If an extension is using a newer version, the dependency is uninstalled and reinstalled twice every startup.

[+] xformers version 0.0.17 installed.
[+] torch version 2.0.1+cu118 installed.
[+] torchvision version 0.15.2+cu118 installed.
[+] accelerate version 0.19.0 installed.
[+] diffusers version 0.16.1 installed.
[+] transformers version 4.29.2 installed.
[+] bitsandbytes version 0.35.4 installed.

Launching Web UI with arguments: --force-cpu
No module 'xformers'. Proceeding without it.
2023-07-05 21:47:05,349 - ControlNet - INFO - ControlNet v1.1.229
ControlNet preprocessor location: E:\Programs\Dev\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-07-05 21:47:06,846 - ControlNet - INFO - ControlNet v1.1.229
Civitai: API loaded
Loading weights [f92c6a679a] from E:\Programs\Dev\stable-diffusion-webui\models\Stable-diffusion\test3_420.safetensors
Creating model from config: E:\Programs\Dev\stable-diffusion-webui\models\Stable-diffusion\test3_420.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Textual inversion embeddings loaded(30): angry512, antonialastnamesd15, brielastnamdsd15, brila_noexist, caoimhelastnamesd15, charturner1-5v2, charturnerv2, cherrynobodysd15, chloenobodysd15, defiance512, deniselastnamesd15, dollienobodysd15, evelynnobodysd15, faithlastnamesd15, follynobodysd15, glorianobodysd15, gregnobodysd15, grin512, happy512, KimberlyNobodySD15, kristennobodysd15, laugh512, maranobodysd15, nervous512, rurinobodysd15, sad512, sashanobodysd15, shock512, smile512, yu-jinnobodysd15
Model loaded in 137.1s (load weights from disk: 3.4s, create model: 0.6s, apply weights to model: 129.1s, apply half(): 0.6s, move model to device: 0.7s, load textual inversion embeddings: 1.8s, calculate empty prompt: 0.9s).
Installing pywin32
Applying attention optimization: Doggettx... done.
CUDA SETUP: Loading binary E:\Programs\Dev\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Civitai: Check resources for missing preview images
Startup time: 189.1s (import torch: 5.1s, import gradio: 1.0s, import ldm: 0.6s, other imports: 4.5s, opts onchange: 0.1s, setup codeformer: 1.2s, list SD models: 1.3s, load scripts: 171.2s, initialize extra networks: 0.2s, create ui: 2.5s, gradio launch: 1.3s).
Civitai: Found 13 resources missing preview images
Civitai: No preview images found on Civitai
preload_extensions_git_metadata for 23 extensions took 4.73s
Initializing dreambooth training...
Pre-processing images: training: : 84it [00:00, 91.15it/s]
Nothing to generate.s: training: : 80it [00:00, 93.47it/s]                                      | 0/84 [00:00<?, ?it/s]
                                                                                                                       Found 0 reg images. 0%|                                                                          | 0/84 [00:00<?, ?it/s]
Preparing dataset...
Building prompts with strict tokens enabled.
Init dataset!
Preparing Dataset (With Caching)
                                                                                                                       Loading cached latents...|                                                                       | 0/84 [00:00<?, ?it/s]
Bucket 0 (768, 768, 0) - Instance Images: 84 | Class Images: 0 | Max Examples/batch:  84
Total Buckets 1 - Instance Images: 84 | Class Images: 0 | Max Examples/batch: 84

Total images / batch: 84, total examples: 84███████████████████████████████████████████| 84/84 [00:00<00:00,  3.12it/s]
                                                                                                                       Total dataset length (steps): 84
                  Initializing bucket counter!
Steps: 100%|███████████| 84/84 [1:08:27<00:00, 48.88s/it, inst_loss=0.0169, loss=0.0169, lr=5e-6, prior_loss=0, vram=1]Exception saving checkpoint/model: Error while serializing: IoError(Os { code: 1224, kind: Uncategorized, message: "The requested operation cannot be performed on a file with a user-mapped section open." })
Traceback (most recent call last):
  File "E:\Programs\Dev\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 883, in save_weights
    s_pipeline.save_pretrained(
  File "E:\Programs\Dev\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 607, in save_pretrained
    save_method(os.path.join(save_directory, pipeline_component_name), **save_kwargs)
  File "E:\Programs\Dev\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 319, in save_pretrained
    safetensors.torch.save_file(
  File "E:\Programs\Dev\stable-diffusion-webui\venv\lib\site-packages\safetensors\torch.py", line 232, in save_file
    serialize_file(_flatten(tensors), filename, metadata=metadata)
safetensors_rust.SafetensorError: Error while serializing: IoError(Os { code: 1224, kind: Uncategorized, message: "The requested operation cannot be performed on a file with a user-mapped section open." })
                                                                                                                       Model name: test3es:  33%|█████████████████████▎                                          | 1/3 [00:40<01:21, 40.76s/it]
Saving E:\Programs\Dev\stable-diffusion-webui\models\dreambooth\test3\logging\loss_plot_672.png
Saving E:\Programs\Dev\stable-diffusion-webui\models\dreambooth\test3\logging\ram_plot_672.png
Cleanup log parse.
                                                                                                                       Cleanup completed.                                                                                | 0/3 [00:00<?, ?it/s]
Steps: 100%|███████████| 84/84 [1:09:38<00:00, 49.74s/it, inst_loss=0.0169, loss=0.0169, lr=5e-6, prior_loss=0, vram=1]
  0%|                                                                                            | 0/3 [00:01<?, ?it/s]
Restored system models.
Duration: 01:11:36
```

**Comment by DoctorDevMan** [comment]
@d8ahazard Any ideas could this issue be related to my settings. Is there a specific configuration that could be used to prevent this issue when training with CPU?

**Comment by DoctorDevMan** [comment]
#936 Could this be related to changes/tweaks made for this issue?

**Comment by DoctorDevMan** [comment]
Using Lora appears to be a work around. No other settings seem to make a difference like setting a different name for the model. Is there a code change that could to remove the file lock before writing the main model?
