### ISSUE TITLE
[Bug]: manys DEBUG 

### ISSUE THREAD

**Issue by swumagic** [d8ahazard/sd_dreambooth_extension#1323]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

[2023-08-15 06:49:21,592][STATUS][sd] - [AgentScheduler] Task queue is empty
[2023-08-15 06:49:21,592][STATUS][sd] - [AgentScheduler] Registering APIs
[2023-08-15 06:49:21,800][DEBUG][api_t2v.py] - text2video extension for auto1111 webui
[2023-08-15 06:49:21,801][DEBUG][api_t2v.py] - Git commit: 20ead103
[2023-08-15 06:49:21,801][DEBUG][api_t2v.py] - Loading text2video API endpoints
[2023-08-15 06:49:21,819][DEBUG][api.py] - Loading Dreambooth API Endpoints.

### Steps to reproduce the problem

manys DEBUG 

### Commit and libraries

Initializing Dreambooth
Dreambooth revision: b4053defa6ae018b2ea56ac243aa55063f76fe0e
[+] xformers version 0.0.20 installed.
[+] torch version 2.0.1+cu118 installed.
[+] torchvision version 0.15.2+cu118 installed.
[+] accelerate version 0.21.0 installed.
[+] diffusers version 0.19.3 installed.
[+] transformers version 4.30.2 installed.
[+] bitsandbytes version 0.35.4 installed.
Installing requirements for TemporalKit extension

Checking ReActor requirements... Ok

Installing pyqt5 requirement for depthmap script

### Command Line Arguments

```Shell
Launching Web UI with arguments: --medvram --theme dark --port 7861 --xformers --opt-channelslast --api --autolaunch --server-name 192.168.50.66 --enable-insecure-extension-access --allow-code
```

### Console logs

```Shell
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.5.1
Commit hash: 68f336bd994bed5442ad95bad6b6ad5564a5409a
Installing requirements for Batch Face Swap

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
model ignore: C:\Users\dckf/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
model ignore: C:\Users\dckf/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\dckf/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\dckf/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
model ignore: C:\Users\dckf/.insightface\models\buffalo_l\w600k_r50.onnx recognition
set det-size: (640, 640)
Installing requirements for Face Editor

current transparent-background 1.2.3

[Auto-Photoshop-SD] Attempting auto-update...
[Auto-Photoshop-SD] switch branch to extension branch.
checkout_result: M	requirements.txt
Your branch is up to date with 'origin/master'.

[Auto-Photoshop-SD] Current Branch.
branch_result: * master

[Auto-Photoshop-SD] Fetch upstream.
fetch_result: 
[Auto-Photoshop-SD] Pull upstream.
pull_result: Already up to date.

If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: b4053defa6ae018b2ea56ac243aa55063f76fe0e
[+] xformers version 0.0.20 installed.
[+] torch version 2.0.1+cu118 installed.
[+] torchvision version 0.15.2+cu118 installed.
[+] accelerate version 0.21.0 installed.
[+] diffusers version 0.19.3 installed.
[+] transformers version 4.30.2 installed.
[+] bitsandbytes version 0.35.4 installed.
Installing requirements for TemporalKit extension

Checking ReActor requirements... Ok

Installing pyqt5 requirement for depthmap script
Launching Web UI with arguments: --medvram --theme dark --port 7861 --xformers --opt-channelslast --api --autolaunch --server-name 192.168.50.66 --enable-insecure-extension-access --allow-code
[2023-08-15 07:03:39,953][DEBUG][git.cmd] - Popen(['git', 'version'], cwd=K:\StableDiffusion\sdwebui, universal_newlines=False, shell=None, istream=None)
[2023-08-15 07:03:40,035][DEBUG][git.cmd] - Popen(['git', 'version'], cwd=K:\StableDiffusion\sdwebui, universal_newlines=False, shell=None, istream=None)
AUTOMATIC1111/stable-diffusion-webui packed by bilibili@秋葉aaaki 
本整合包完全免费，严禁倒卖。若您付费获得本软件请立刻举报商家。
python_server_full_path:  K:\StableDiffusion\sdwebui\extensions\Auto-Photoshop-StableDiffusion-Plugin\server/python_server
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: K:\StableDiffusion\sdwebui\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
model ignore: C:\Users\dckf/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
model ignore: C:\Users\dckf/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\dckf/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\dckf/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
model ignore: C:\Users\dckf/.insightface\models\buffalo_l\w600k_r50.onnx recognition
set det-size: (640, 640)
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
model ignore: C:\Users\dckf/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\dckf/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\dckf/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
model ignore: C:\Users\dckf/.insightface\models\buffalo_l\genderage.onnx genderage
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
model ignore: C:\Users\dckf/.insightface\models\buffalo_l\w600k_r50.onnx recognition
set det-size: (640, 640)
[AddNet] Updating model hashes...
[2023-08-15 07:03:54,958][DEBUG][filelock] - Attempting to acquire lock 2654400839200 on K:\StableDiffusion\sdwebui\extensions\sd-webui-additional-networks\hashes.json.lock
[2023-08-15 07:03:54,959][DEBUG][filelock] - Lock 2654400839200 acquired on K:\StableDiffusion\sdwebui\extensions\sd-webui-additional-networks\hashes.json.lock
[2023-08-15 07:03:54,960][DEBUG][filelock] - Attempting to release lock 2654400839200 on K:\StableDiffusion\sdwebui\extensions\sd-webui-additional-networks\hashes.json.lock
[2023-08-15 07:03:54,964][DEBUG][filelock] - Lock 2654400839200 released on K:\StableDiffusion\sdwebui\extensions\sd-webui-additional-networks\hashes.json.lock
[2023-08-15 07:03:54,965][DEBUG][filelock] - Attempting to acquire lock 2654289999808 on K:\StableDiffusion\sdwebui\extensions\sd-webui-additional-networks\hashes.json.lock
[2023-08-15 07:03:54,966][DEBUG][filelock] - Lock 2654289999808 acquired on K:\StableDiffusion\sdwebui\extensions\sd-webui-additional-networks\hashes.json.lock
[2023-08-15 07:03:54,970][DEBUG][filelock] - Attempting to release lock 2654289999808 on K:\StableDiffusion\sdwebui\extensions\sd-webui-additional-networks\hashes.json.lock
[2023-08-15 07:03:54,974][DEBUG][filelock] - Lock 2654289999808 released on K:\StableDiffusion\sdwebui\extensions\sd-webui-additional-networks\hashes.json.lock
[AddNet] Updating model hashes...
[2023-08-15 07:03:55,169][DEBUG][filelock] - Attempting to acquire lock 2654400567840 on K:\StableDiffusion\sdwebui\extensions\sd-webui-additional-networks\hashes.json.lock
[2023-08-15 07:03:55,170][DEBUG][filelock] - Lock 2654400567840 acquired on K:\StableDiffusion\sdwebui\extensions\sd-webui-additional-networks\hashes.json.lock
[2023-08-15 07:03:55,170][DEBUG][filelock] - Attempting to release lock 2654400567840 on K:\StableDiffusion\sdwebui\extensions\sd-webui-additional-networks\hashes.json.lock
[2023-08-15 07:03:55,175][DEBUG][filelock] - Lock 2654400567840 released on K:\StableDiffusion\sdwebui\extensions\sd-webui-additional-networks\hashes.json.lock
[2023-08-15 07:03:55,176][DEBUG][filelock] - Attempting to acquire lock 2654400569328 on K:\StableDiffusion\sdwebui\extensions\sd-webui-additional-networks\hashes.json.lock
[2023-08-15 07:03:55,176][DEBUG][filelock] - Lock 2654400569328 acquired on K:\StableDiffusion\sdwebui\extensions\sd-webui-additional-networks\hashes.json.lock
[2023-08-15 07:03:55,180][DEBUG][filelock] - Attempting to release lock 2654400569328 on K:\StableDiffusion\sdwebui\extensions\sd-webui-additional-networks\hashes.json.lock
[2023-08-15 07:03:55,184][DEBUG][filelock] - Lock 2654400569328 released on K:\StableDiffusion\sdwebui\extensions\sd-webui-additional-networks\hashes.json.lock
dirname:  K:\StableDiffusion\sdwebui\localizations
localizations:  {'zh-Hans (Stable)': 'K:\\StableDiffusion\\sdwebui\\extensions\\stable-diffusion-webui-localization-zh_Hans\\localizations\\zh-Hans (Stable).json', 'zh-Hans (Testing)': 'K:\\StableDiffusion\\sdwebui\\extensions\\stable-diffusion-webui-localization-zh_Hans\\localizations\\zh-Hans (Testing).json', 'zh_CN': 'K:\\StableDiffusion\\sdwebui\\extensions\\stable-diffusion-webui-localization-zh_Hans\\localizations\\zh_CN.json', 'zh_TW': 'K:\\StableDiffusion\\sdwebui\\extensions\\stable-diffusion-webui-localization-zh_Hans\\localizations\\zh_TW.json'}
2023-08-15 07:03:56,159 - ControlNet - INFO - ControlNet v1.1.238
ControlNet preprocessor location: K:\StableDiffusion\sdwebui\extensions\sd-webui-controlnet\annotator\downloads
2023-08-15 07:03:56,553 - ControlNet - INFO - ControlNet v1.1.238
Loading FABRIC v0.4.2
sd-webui-prompt-all-in-one background API service started successfully.
07:04:02 - ReActor - STATUS - Running v0.3.1b
[2023-08-15 07:04:02,925][DEBUG][api_t2v.py] - SD-Webui text2video API layer loaded
Loading weights [fc2511737a] from K:\StableDiffusion\sdwebui\models\Stable-diffusion\chilloutmix_NiPrunedFp32Fix.safetensors
Creating model from config: K:\StableDiffusion\sdwebui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.


[2023-08-15 07:04:39,249][DEBUG][markdown_it.rules_block.lheading] - entering lheading: StateBlock(line=11,level=0,tokens=36), 11, 15, False
[2023-08-15 07:04:39,249][DEBUG][markdown_it.rules_block.paragraph] - entering paragraph: StateBlock(line=11,level=0,tokens=36), 11, 15, False
[2023-08-15 07:04:39,249][DEBUG][markdown_it.rules_block.code] - entering code: StateBlock(line=13,level=0,tokens=39), 13, 15, False
[2023-08-15 07:04:39,249][DEBUG][markdown_it.rules_block.fence] - entering fence: StateBlock(line=13,level=0,tokens=39), 13, 15, False
[2023-08-15 07:04:39,249][DEBUG][markdown_it.rules_block.blockquote] - entering blockquote: StateBlock(line=13,level=0,tokens=39), 13, 15, False
[2023-08-15 07:04:39,249][DEBUG][markdown_it.rules_block.hr] - entering hr: StateBlock(line=13,level=0,tokens=39), 13, 15, False
[2023-08-15 07:04:39,250][DEBUG][markdown_it.rules_block.list] - entering list: StateBlock(line=13,level=0,tokens=39), 13, 15, False
[2023-08-15 07:04:39,250][DEBUG][markdown_it.rules_block.reference] - entering reference: StateBlock(line=13,level=0,tokens=39), 13, 15, False
[2023-08-15 07:04:39,250][DEBUG][markdown_it.rules_block.html_block] - entering html_block: StateBlock(line=13,level=0,tokens=39), 13, 15, False
[2023-08-15 07:04:39,250][DEBUG][markdown_it.rules_block.heading] - entering heading: StateBlock(line=13,level=0,tokens=39), 13, 15, False
[2023-08-15 07:04:39,250][DEBUG][markdown_it.rules_block.code] - entering code: StateBlock(line=14,level=0,tokens=42), 14, 15, False
[2023-08-15 07:04:39,250][DEBUG][markdown_it.rules_block.fence] - entering fence: StateBlock(line=14,level=0,tokens=42), 14, 15, False
[2023-08-15 07:04:39,250][DEBUG][markdown_it.rules_block.blockquote] - entering blockquote: StateBlock(line=14,level=0,tokens=42), 14, 15, False
[2023-08-15 07:04:39,250][DEBUG][markdown_it.rules_block.hr] - entering hr: StateBlock(line=14,level=0,tokens=42), 14, 15, False
[2023-08-15 07:04:39,250][DEBUG][markdown_it.rules_block.list] - entering list: StateBlock(line=14,level=0,tokens=42), 14, 15, False
[2023-08-15 07:04:39,250][DEBUG][markdown_it.rules_block.reference] - entering reference: StateBlock(line=14,level=0,tokens=42), 14, 15, False
[2023-08-15 07:04:39,250][DEBUG][markdown_it.rules_block.html_block] - entering html_block: StateBlock(line=14,level=0,tokens=42), 14, 15, False
[2023-08-15 07:04:39,250][DEBUG][markdown_it.rules_block.heading] - entering heading: StateBlock(line=14,level=0,tokens=42), 14, 15, False
[2023-08-15 07:04:39,250][DEBUG][markdown_it.rules_block.lheading] - entering lheading: StateBlock(line=14,level=0,tokens=42), 14, 15, False
[2023-08-15 07:04:39,250][DEBUG][markdown_it.rules_block.paragraph] - entering paragraph: StateBlock(line=14,level=0,tokens=42), 14, 15, False
Credits: 1011.36
Running on local URL:  http://192.168.50.66:7861
[2023-08-15 07:04:40,659][DEBUG][botocore.hooks] - Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
[2023-08-15 07:04:40,660][DEBUG][botocore.hooks] - Changing event name from before-call.apigateway to before-call.api-gateway
[2023-08-15 07:04:40,661][DEBUG][botocore.hooks] - Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
[2023-08-15 07:04:40,662][DEBUG][botocore.hooks] - Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
[2023-08-15 07:04:40,662][DEBUG][botocore.hooks] - Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
[2023-08-15 07:04:40,662][DEBUG][botocore.hooks] - Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
[2023-08-15 07:04:40,662][DEBUG][botocore.hooks] - Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
[2023-08-15 07:04:40,664][DEBUG][botocore.hooks] - Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
[2023-08-15 07:04:40,664][DEBUG][botocore.hooks] - Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
[2023-08-15 07:04:40,664][DEBUG][botocore.hooks] - Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
[2023-08-15 07:04:40,664][DEBUG][botocore.hooks] - Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
[2023-08-15 07:04:40,665][DEBUG][botocore.utils] - IMDS ENDPOINT: http://169.254.169.254/
[2023-08-15 07:04:40,666][DEBUG][botocore.credentials] - Looking for credentials via: env
[2023-08-15 07:04:40,667][DEBUG][botocore.credentials] - Looking for credentials via: assume-role
[2023-08-15 07:04:40,667][DEBUG][botocore.credentials] - Looking for credentials via: assume-role-with-web-identity
[2023-08-15 07:04:40,667][DEBUG][botocore.credentials] - Looking for credentials via: sso
[2023-08-15 07:04:40,667][DEBUG][botocore.credentials] - Looking for credentials via: shared-credentials-file
[2023-08-15 07:04:40,667][DEBUG][botocore.credentials] - Looking for credentials via: custom-process
[2023-08-15 07:04:40,667][DEBUG][botocore.credentials] - Looking for credentials via: config-file
[2023-08-15 07:04:40,667][DEBUG][botocore.credentials] - Looking for credentials via: ec2-credentials-file
[2023-08-15 07:04:40,667][DEBUG][botocore.credentials] - Looking for credentials via: boto-config
[2023-08-15 07:04:40,667][DEBUG][botocore.credentials] - Looking for credentials via: container-role
[2023-08-15 07:04:40,667][DEBUG][botocore.credentials] - Looking for credentials via: iam-role
[2023-08-15 07:04:41,674][DEBUG][botocore.utils] - Caught retryable HTTP exception while making metadata service request to http://169.254.169.254/latest/api/token: Connect timeout on endpoint URL: "http://169.254.169.254/latest/api/token"
Traceback (most recent call last):
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\botocore\httpsession.py", line 465, in send
    urllib_response = conn.urlopen(
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\urllib3\util\retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\urllib3\packages\six.py", line 770, in reraise
    raise value
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\urllib3\connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\urllib3\connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "http\client.py", line 1283, in request
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\botocore\awsrequest.py", line 94, in _send_request
    rval = super()._send_request(
  File "http\client.py", line 1329, in _send_request
  File "http\client.py", line 1278, in endheaders
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\botocore\awsrequest.py", line 123, in _send_output
    self.send(msg)
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\botocore\awsrequest.py", line 218, in send
    return super().send(str)
  File "http\client.py", line 976, in send
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\urllib3\connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<botocore.awsrequest.AWSHTTPConnection object at 0x0000026BE3952170>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\botocore\utils.py", line 456, in _fetch_metadata_token
    response = self._session.send(request.prepare())
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\botocore\httpsession.py", line 500, in send
    raise ConnectTimeoutError(endpoint_url=request.url, error=e)
botocore.exceptions.ConnectTimeoutError: Connect timeout on endpoint URL: "http://169.254.169.254/latest/api/token"
[2023-08-15 07:04:42,685][DEBUG][botocore.utils] - Caught retryable HTTP exception while making metadata service request to http://169.254.169.254/latest/meta-data/iam/security-credentials/: Connect timeout on endpoint URL: "http://169.254.169.254/latest/meta-data/iam/security-credentials/"
Traceback (most recent call last):
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\botocore\httpsession.py", line 465, in send
    urllib_response = conn.urlopen(
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\urllib3\util\retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\urllib3\packages\six.py", line 770, in reraise
    raise value
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\urllib3\connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\urllib3\connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "http\client.py", line 1283, in request
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\botocore\awsrequest.py", line 94, in _send_request
    rval = super()._send_request(
  File "http\client.py", line 1329, in _send_request
  File "http\client.py", line 1278, in endheaders
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\botocore\awsrequest.py", line 123, in _send_output
    self.send(msg)
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\botocore\awsrequest.py", line 218, in send
    return super().send(str)
  File "http\client.py", line 976, in send
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\urllib3\connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<botocore.awsrequest.AWSHTTPConnection object at 0x0000026BE3952680>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\botocore\utils.py", line 509, in _get_request
    response = self._session.send(request.prepare())
  File "K:\StableDiffusion\sdwebui\py310\lib\site-packages\botocore\httpsession.py", line 500, in send
    raise ConnectTimeoutError(endpoint_url=request.url, error=e)
botocore.exceptions.ConnectTimeoutError: Connect timeout on endpoint URL: "http://169.254.169.254/latest/meta-data/iam/security-credentials/"
[2023-08-15 07:04:42,687][DEBUG][botocore.utils] - Max number of attempts exceeded (1) when attempting to retrieve data from metadata service.
[2023-08-15 07:04:42,691][DEBUG][botocore.loaders] - Loading JSON file: K:\StableDiffusion\sdwebui\py310\lib\site-packages\botocore\data\endpoints.json
[2023-08-15 07:04:42,700][DEBUG][botocore.loaders] - Loading JSON file: K:\StableDiffusion\sdwebui\py310\lib\site-packages\botocore\data\sdk-default-configuration.json
[2023-08-15 07:04:42,700][DEBUG][botocore.hooks] - Event choose-service-name: calling handler <function handle_service_name_alias at 0x0000026994E0A320>
[2023-08-15 07:04:42,838][DEBUG][botocore.loaders] - Loading JSON file: K:\StableDiffusion\sdwebui\py310\lib\site-packages\botocore\data\sts\2011-06-15\service-2.json
[2023-08-15 07:04:43,015][DEBUG][botocore.loaders] - Loading JSON file: K:\StableDiffusion\sdwebui\py310\lib\site-packages\botocore\data\sts\2011-06-15\endpoint-rule-set-1.json.gz
[2023-08-15 07:04:43,017][DEBUG][botocore.loaders] - Loading JSON file: K:\StableDiffusion\sdwebui\py310\lib\site-packages\botocore\data\partitions.json
[2023-08-15 07:04:43,018][DEBUG][botocore.hooks] - Event creating-client-class.sts: calling handler <function add_generate_presigned_url at 0x0000026994D85C60>
[2023-08-15 07:04:43,019][DEBUG][botocore.endpoint] - Setting sts timeout as (60, 60)
[2023-08-15 07:04:43,020][DEBUG][botocore.loaders] - Loading JSON file: K:\StableDiffusion\sdwebui\py310\lib\site-packages\botocore\data\_retry.json
[2023-08-15 07:04:43,020][DEBUG][botocore.client] - Registering retry handlers for service: sts
[2023-08-15 07:04:43,021][DEBUG][botocore.hooks] - Event before-parameter-build.sts.GetCallerIdentity: calling handler <function generate_idempotent_uuid at 0x0000026994E0B7F0>
[2023-08-15 07:04:43,021][DEBUG][botocore.regions] - Calling endpoint provider with parameters: {'Region': 'aws-global', 'UseDualStack': False, 'UseFIPS': False, 'UseGlobalEndpoint': True}
[2023-08-15 07:04:43,021][DEBUG][botocore.regions] - Endpoint provider result: https://sts.amazonaws.com
[2023-08-15 07:04:43,021][DEBUG][botocore.regions] - Selecting from endpoint provider's list of auth schemes: "sigv4". User selected auth scheme is: "None"
[2023-08-15 07:04:43,021][DEBUG][botocore.regions] - Selected auth type "v4" as "v4" with signing context params: {'region': 'us-east-1', 'signing_name': 'sts'}
[2023-08-15 07:04:43,021][DEBUG][botocore.hooks] - Event before-call.sts.GetCallerIdentity: calling handler <function add_recursion_detection_header at 0x0000026994E0B490>
[2023-08-15 07:04:43,021][DEBUG][botocore.hooks] - Event before-call.sts.GetCallerIdentity: calling handler <function inject_api_version_header_if_needed at 0x0000026994E21090>
[2023-08-15 07:04:43,021][DEBUG][botocore.endpoint] - Making request for OperationModel(name=GetCallerIdentity) with params: {'url_path': '/', 'query_string': '', 'method': 'POST', 'headers': {'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8', 'User-Agent': 'Boto3/1.26.133 Python/3.10.11 Windows/10 Botocore/1.29.133'}, 'body': {'Action': 'GetCallerIdentity', 'Version': '2011-06-15'}, 'url': 'https://sts.amazonaws.com/', 'context': {'client_region': 'aws-global', 'client_config': <botocore.config.Config object at 0x0000026BE3952110>, 'has_streaming_input': False, 'auth_type': 'v4', 'signing': {'region': 'us-east-1', 'signing_name': 'sts'}}}
[2023-08-15 07:04:43,022][DEBUG][botocore.hooks] - Event request-created.sts.GetCallerIdentity: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x0000026BE39522F0>>
[2023-08-15 07:04:43,022][DEBUG][botocore.hooks] - Event choose-signer.sts.GetCallerIdentity: calling handler <function set_operation_specific_signer at 0x0000026994E0B6D0>

To create a public link, set `share=True` in `launch()`.
[2023-08-15 07:04:44,556][STATUS][sd] - [AgentScheduler] Task queue is empty
[2023-08-15 07:04:44,556][STATUS][sd] - [AgentScheduler] Registering APIs
[2023-08-15 07:04:44,801][DEBUG][api_t2v.py] - text2video extension for auto1111 webui
[2023-08-15 07:04:44,801][DEBUG][api_t2v.py] - Git commit: 8f0af8c9
[2023-08-15 07:04:44,801][DEBUG][api_t2v.py] - Loading text2video API endpoints
[2023-08-15 07:04:44,806][DEBUG][api.py] - Loading Dreambooth API Endpoints.
Startup time: 165.7s (launcher: 88.8s, import torch: 8.9s, import gradio: 1.6s, setup paths: 1.3s, other imports: 1.2s, setup codeformer: 0.1s, list SD models: 0.1s, load scripts: 49.0s, create ui: 10.3s, gradio launch: 2.8s, add APIs: 0.5s, app_started_callback: 0.8s).
```

**Comment by hzalbertcm** [comment]
I got same problem, there is too many DEBUG log after I synchronized the latest code. It even cause other module to print DEBUG level logs after dreambooth extension loaded. I tried to debug the code, and I found it caused by the code update in preload.py by commit  https://github.com/d8ahazard/sd_dreambooth_extension/commit/b4053defa6ae018b2ea56ac243aa55063f76fe0e
The following code snippet will set the global parent "root" logger's logging level to DEBUG, it causes all children logger's (which do not have logging level set explicitly)  logging level set to DEBUG.
```python
logging.basicConfig(format='[%(asctime)s][%(levelname)s][%(name)s] - %(message)s', level=logging.DEBUG)
``` 
Please fix this.

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
