### ISSUE TITLE
Dreambooth Tab not Showing [Bug]: 

### ISSUE THREAD

**Issue by JanHmmr** [d8ahazard/sd_dreambooth_extension#1331]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When trying to run Automatic1111 with Dreambooth it errors with: 

"NameError: name 'DreamboothConfig' is not defined" 
"ModuleNotFoundError: No module named 'diffusers'"
" Stable diffusion model failed to load"

Tried basically everything, more Info on the Bottom

### Steps to reproduce the problem

1. Go to sd.webui folder
2. Press run.bat
3. Errors occur

### Commit and libraries

Starting at `Initializing Dreambooth` and ending several lines below at `[+] bitsandbytes version 0.35.4 installed.`.

### Command Line Arguments

```Shell
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=--xformers --autolaunch --update-check --disable-safe-unpickle

call webui.bat
```

### Console logs

```Shell
*** Initializing Dreambooth
*** Dreambooth revision: 72ba64f9b6954f7f9fd2a4181ae8b88a715e1a28
*** # Requirement installation exception:
*** Ignoring tensorboard: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
*** Collecting accelerate~=0.21.0 (from -r C:\sd.webui\webui\extensions\sd_dreambooth_extension\requirements.txt (line 1))
*** Obtaining dependency information for accelerate~=0.21.0 from https://files.pythonhosted.org/packages/70/f9/c381bcdd0c3829d723aa14eec8e75c6c377b4ca61ec68b8093d9f35fc7a7/accelerate-0.21.0-py3-none-any.whl.metadata
*** Using cached accelerate-0.21.0-py3-none-any.whl.metadata (17 kB)
*** Collecting bitsandbytes==0.35.4 (from -r C:\sd.webui\webui\extensions\sd_dreambooth_extension\requirements.txt (line 2))
*** Using cached bitsandbytes-0.35.4-py3-none-any.whl (62.5 MB)
*** Collecting dadaptation==3.1 (from -r C:\sd.webui\webui\extensions\sd_dreambooth_extension\requirements.txt (line 3))
*** Using cached dadaptation-3.1.tar.gz (13 kB)
*** Installing build dependencies: started
*** Installing build dependencies: finished with status 'done'
*** Getting requirements to build wheel: started
*** Getting requirements to build wheel: finished with status 'done'
*** ERROR: Exception:
*** Traceback (most recent call last):
*** File "C:\sd.webui\system\python\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
*** status = run_func(*args)
*** File "C:\sd.webui\system\python\lib\site-packages\pip\_internal\cli\req_command.py", line 248, in wrapper
*** return func(self, options, args)
*** File "C:\sd.webui\system\python\lib\site-packages\pip\_internal\commands\install.py", line 377, in run
*** requirement_set = resolver.resolve(
*** File "C:\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
*** result = self._result = resolver.resolve(
*** File "C:\sd.webui\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
*** state = resolution.resolve(requirements, max_rounds=max_rounds)
*** File "C:\sd.webui\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve
*** self._add_to_criteria(self.state.criteria, r, parent=None)
*** File "C:\sd.webui\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
*** if not criterion.candidates:
*** File "C:\sd.webui\system\python\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
*** return bool(self._sequence)
*** File "C:\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
*** return any(self)
*** File "C:\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
*** return (c for c in iterator if id(c) not in self._incompatible_ids)
*** File "C:\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
*** candidate = func()
*** File "C:\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
*** self._link_candidate_cache[link] = LinkCandidate(
*** File "C:\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 293, in __init__
*** super().__init__(
*** File "C:\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
*** self.dist = self._prepare()
*** File "C:\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 225, in _prepare
*** dist = self._prepare_distribution()
*** File "C:\sd.webui\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 304, in _prepare_distribution
*** return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
*** File "C:\sd.webui\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 538, in prepare_linked_requirement
*** return self._prepare_linked_requirement(req, parallel_builds)
*** File "C:\sd.webui\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 653, in _prepare_linked_requirement
*** dist = _get_prepared_distribution(
*** File "C:\sd.webui\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 69, in _get_prepared_distribution
*** abstract_dist.prepare_distribution_metadata(
*** File "C:\sd.webui\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 48, in prepare_distribution_metadata
*** self._install_build_reqs(finder)
*** File "C:\sd.webui\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 118, in _install_build_reqs
*** build_reqs = self._get_build_requires_wheel()
*** File "C:\sd.webui\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 95, in _get_build_requires_wheel
*** return backend.get_requires_for_build_wheel()
*** File "C:\sd.webui\system\python\lib\site-packages\pip\_internal\utils\misc.py", line 697, in get_requires_for_build_wheel
*** return super().get_requires_for_build_wheel(config_settings=cs)
*** File "C:\sd.webui\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 166, in get_requires_for_build_wheel
*** return self._call_hook('get_requires_for_build_wheel', {
*** File "C:\sd.webui\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook
*** raise BackendUnavailable(data.get('traceback', ''))
*** pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
*** File "C:\sd.webui\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
*** obj = import_module(mod_path)
*** File "importlib\__init__.py", line 126, in import_module
*** File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
*** File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
*** File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
*** File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
*** File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
*** File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
*** File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
*** File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
*** File "<frozen importlib._bootstrap_external>", line 883, in exec_module
*** File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
*** File "C:\Users\Jan Hammer\AppData\Local\Temp\pip-build-env-mrkmd7xr\overlay\Lib\site-packages\setuptools\__init__.py", line 15, in <module>
*** import setuptools.version
*** File "C:\Users\Jan Hammer\AppData\Local\Temp\pip-build-env-mrkmd7xr\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
*** from ._importlib import metadata
*** File "C:\Users\Jan Hammer\AppData\Local\Temp\pip-build-env-mrkmd7xr\overlay\Lib\site-packages\setuptools\_importlib.py", line 45, in <module>
*** import importlib.metadata as metadata  # noqa: F401
*** File "importlib\metadata\__init__.py", line 17, in <module>
*** File "importlib\metadata\_adapters.py", line 3, in <module>
*** File "email\message.py", line 15, in <module>
*** File "email\utils.py", line 29, in <module>
*** File "socket.py", line 51, in <module>
*** ModuleNotFoundError: No module named '_socket'
***
*** stderr: A matching Triton is not available, some optimizations will not be enabled.
*** Error caught was: No module named 'triton'
*** C:\sd.webui\system\python\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
***   rank_zero_deprecation(
*** [2023-08-20 17:19:08,771][DEBUG][git.cmd] - Popen(['git', 'version'], cwd=C:\sd.webui\webui, universal_newlines=False, shell=None, istream=None)
*** [2023-08-20 17:19:08,884][DEBUG][git.cmd] - Popen(['git', 'version'], cwd=C:\sd.webui\webui, universal_newlines=False, shell=None, istream=None)
*** loading stable diffusion model: ImportError
*** Traceback (most recent call last):
***   File "C:\sd.webui\webui\extensions\sd_dreambooth_extension\install.py", line 33, in <module>
***     from postinstall import actual_install
***   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
***   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
***   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
***   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
***   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
***   File "C:\sd.webui\webui\extensions\sd_dreambooth_extension\postinstall.py", line 14, in <module>
***     from dreambooth import shared
***   File "<frozen importlib._bootstrap>", line 1078, in _handle_fromlist
***   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
***   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
***   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
***   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
***   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
***   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
***   File "C:\sd.webui\webui\extensions\sd_dreambooth_extension\dreambooth\shared.py", line 434, in <module>
***     is_auto = load_auto_settings()
***   File "C:\sd.webui\webui\extensions\sd_dreambooth_extension\dreambooth\shared.py", line 46, in load_auto_settings
***     sd_model = ws.sd_model
***   File "C:\sd.webui\webui\modules\shared.py", line 754, in sd_model
***     return modules.sd_models.model_data.get_sd_model()
***   File "C:\sd.webui\webui\modules\sd_models.py", line 439, in get_sd_model
***     load_model()
***   File "C:\sd.webui\webui\modules\sd_models.py", line 465, in load_model
***     from modules import lowvram, sd_hijack
***   File "C:\sd.webui\webui\modules\sd_hijack.py", line 5, in <module>
***     import modules.textual_inversion.textual_inversion
***   File "C:\sd.webui\webui\modules\textual_inversion\textual_inversion.py", line 16, in <module>
***     from modules import shared, devices, sd_hijack, processing, sd_models, images, sd_samplers, sd_hijack_checkpoint, errors, hashes
***   File "C:\sd.webui\webui\modules\processing.py", line 18, in <module>
***     from modules.sd_hijack import model_hijack
*** ImportError: cannot import name 'model_hijack' from partially initialized module 'modules.sd_hijack' (most likely due to a circular import) (C:\sd.webui\webui\modules\sd_hijack.py)
***
***
*** Stable diffusion model failed to load
*** loading stable diffusion model: ImportError
*** Traceback (most recent call last):
***   File "C:\sd.webui\webui\extensions\sd_dreambooth_extension\install.py", line 33, in <module>
***     from postinstall import actual_install
***   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
***   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
***   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
***   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
***   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
***   File "C:\sd.webui\webui\extensions\sd_dreambooth_extension\postinstall.py", line 14, in <module>
***     from dreambooth import shared
***   File "<frozen importlib._bootstrap>", line 1078, in _handle_fromlist
***   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
***   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
***   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
***   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
***   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
***   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
***   File "C:\sd.webui\webui\extensions\sd_dreambooth_extension\dreambooth\shared.py", line 436, in <module>
***     load_vars()
***   File "C:\sd.webui\webui\extensions\sd_dreambooth_extension\dreambooth\shared.py", line 352, in load_vars
***     is_auto = load_auto_settings()
***   File "C:\sd.webui\webui\extensions\sd_dreambooth_extension\dreambooth\shared.py", line 46, in load_auto_settings
***     sd_model = ws.sd_model
***   File "C:\sd.webui\webui\modules\shared.py", line 754, in sd_model
***     return modules.sd_models.model_data.get_sd_model()
***   File "C:\sd.webui\webui\modules\sd_models.py", line 439, in get_sd_model
***     load_model()
***   File "C:\sd.webui\webui\modules\sd_models.py", line 465, in load_model
***     from modules import lowvram, sd_hijack
***   File "C:\sd.webui\webui\modules\sd_hijack.py", line 5, in <module>
***     import modules.textual_inversion.textual_inversion
***   File "C:\sd.webui\webui\modules\textual_inversion\textual_inversion.py", line 16, in <module>
***     from modules import shared, devices, sd_hijack, processing, sd_models, images, sd_samplers, sd_hijack_checkpoint, errors, hashes
***   File "C:\sd.webui\webui\modules\processing.py", line 18, in <module>
***     from modules.sd_hijack import model_hijack
*** ImportError: cannot import name 'model_hijack' from partially initialized module 'modules.sd_hijack' (most likely due to a circular import) (C:\sd.webui\webui\modules\sd_hijack.py)
***
***
*** Stable diffusion model failed to load
*** [2023-08-20 17:19:10,822][DEBUG][git.cmd] - Popen(['git', 'cat-file', '--batch-check'], cwd=C:\sd.webui\webui\extensions\sd_dreambooth_extension, universal_newlines=False, shell=None, istream=<valid stream>)
*** Traceback (most recent call last):
***   File "C:\sd.webui\webui\extensions\sd_dreambooth_extension\install.py", line 35, in <module>
***     actual_install()
***   File "C:\sd.webui\webui\extensions\sd_dreambooth_extension\postinstall.py", line 41, in actual_install
***     install_requirements()
***   File "C:\sd.webui\webui\extensions\sd_dreambooth_extension\postinstall.py", line 87, in install_requirements
***     raise grepexc
***   File "C:\sd.webui\webui\extensions\sd_dreambooth_extension\postinstall.py", line 75, in install_requirements
***     pip_install("-r", req_file)
***   File "C:\sd.webui\webui\extensions\sd_dreambooth_extension\postinstall.py", line 53, in pip_install
***     output = subprocess.check_output(
***   File "subprocess.py", line 420, in check_output
***   File "subprocess.py", line 524, in run
*** subprocess.CalledProcessError: Command '['C:\\sd.webui\\system\\python\\python.exe', '-m', 'pip', 'install', '-r', 'C:\\sd.webui\\webui\\extensions\\sd_dreambooth_extension\\requirements.txt']' returned non-zero exit status 2.
You are up to date with the most recent release.
Launching Web UI with arguments: --xformers --autolaunch --update-check --disable-safe-unpickle
[2023-08-20 17:19:26,238][DEBUG][git.cmd] - Popen(['git', 'version'], cwd=C:\sd.webui\webui, universal_newlines=False, shell=None, istream=None)
[2023-08-20 17:19:26,356][DEBUG][git.cmd] - Popen(['git', 'version'], cwd=C:\sd.webui\webui, universal_newlines=False, shell=None, istream=None)
Loading weights [c0d1994c73] from C:\sd.webui\webui\models\Stable-diffusion\realisticVisionV51_v20Novae.safetensors
Creating model from config: C:\sd.webui\webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Model loaded in 4.7s (load weights from disk: 0.2s, create model: 0.4s, apply weights to model: 0.8s, apply half(): 0.7s, move model to device: 0.6s, load textual inversion embeddings: 1.0s, calculate empty prompt: 0.9s).
Exception importing api
Traceback (most recent call last):
  File "C:\sd.webui\webui\extensions\sd_dreambooth_extension\scripts\api.py", line 27, in <module>
    from dreambooth.dataclasses.db_config import from_file, DreamboothConfig
  File "C:\sd.webui\webui\extensions\sd_dreambooth_extension\dreambooth\dataclasses\db_config.py", line 12, in <module>
    from dreambooth.utils.image_utils import get_scheduler_names  # noqa
  File "C:\sd.webui\webui\extensions\sd_dreambooth_extension\dreambooth\utils\image_utils.py", line 11, in <module>
    from diffusers.schedulers import KarrasDiffusionSchedulers
ModuleNotFoundError: No module named 'diffusers'
[2023-08-20 17:19:33,346][DEBUG][api.py] - SD-Webui API layer loaded
*** Error loading script: main.py
    Traceback (most recent call last):
      File "C:\sd.webui\webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\sd.webui\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\sd.webui\webui\extensions\sd_dreambooth_extension\scripts\main.py", line 7, in <module>
        from dreambooth.dataclasses.db_config import from_file, save_config
      File "C:\sd.webui\webui\extensions\sd_dreambooth_extension\dreambooth\dataclasses\db_config.py", line 12, in <module>
        from dreambooth.utils.image_utils import get_scheduler_names  # noqa
      File "C:\sd.webui\webui\extensions\sd_dreambooth_extension\dreambooth\utils\image_utils.py", line 11, in <module>
        from diffusers.schedulers import KarrasDiffusionSchedulers
    ModuleNotFoundError: No module named 'diffusers'

---
Applying attention optimization: xformers... done.
[2023-08-20 17:19:33,777][DEBUG][markdown_it.rules_block.code] - entering code: StateBlock(line=0,level=0,tokens=0), 0, 1, False
[2023-08-20 17:19:33,777][DEBUG][markdown_it.rules_block.fence] - entering fence: StateBlock(line=0,level=0,tokens=0), 0, 1, False
[2023-08-20 17:19:33,779][DEBUG][markdown_it.rules_block.blockquote] - entering blockquote: StateBlock(line=0,level=0,tokens=0), 0, 1, False
[2023-08-20 17:19:33,779][DEBUG][markdown_it.rules_block.hr] - entering hr: StateBlock(line=0,level=0,tokens=0), 0, 1, False
[2023-08-20 17:19:33,780][DEBUG][markdown_it.rules_block.list] - entering list: StateBlock(line=0,level=0,tokens=0), 0, 1, False
[2023-08-20 17:19:33,780][DEBUG][markdown_it.rules_block.code] - entering code: StateBlock(line=0,level=2,tokens=2), 0, 1, False
[2023-08-20 17:19:33,781][DEBUG][markdown_it.rules_block.fence] - entering fence: StateBlock(line=0,level=2,tokens=2), 0, 1, False
[2023-08-20 17:19:33,781][DEBUG][markdown_it.rules_block.blockquote] - entering blockquote: StateBlock(line=0,level=2,tokens=2), 0, 1, False
[2023-08-20 17:19:33,781][DEBUG][markdown_it.rules_block.hr] - entering hr: StateBlock(line=0,level=2,tokens=2), 0, 1, False
[2023-08-20 17:19:33,782][DEBUG][markdown_it.rules_block.list] - entering list: StateBlock(line=0,level=2,tokens=2), 0, 1, False
[2023-08-20 17:19:33,782][DEBUG][markdown_it.rules_block.reference] - entering reference: StateBlock(line=0,level=2,tokens=2), 0, 1, False
[2023-08-20 17:19:33,783][DEBUG][markdown_it.rules_block.html_block] - entering html_block: StateBlock(line=0,level=2,tokens=2), 0, 1, False
[2023-08-20 17:19:33,783][DEBUG][markdown_it.rules_block.heading] - entering heading: StateBlock(line=0,level=2,tokens=2), 0, 1, False
[2023-08-20 17:19:33,784][DEBUG][markdown_it.rules_block.lheading] - entering lheading: StateBlock(line=0,level=2,tokens=2), 0, 1, False
[2023-08-20 17:19:33,784][DEBUG][markdown_it.rules_block.paragraph] - entering paragraph: StateBlock(line=0,level=2,tokens=2), 0, 1, False
[2023-08-20 17:19:34,023][DEBUG][markdown_it.rules_block.code] - entering code: StateBlock(line=0,level=0,tokens=0), 0, 1, False
[2023-08-20 17:19:34,023][DEBUG][markdown_it.rules_block.fence] - entering fence: StateBlock(line=0,level=0,tokens=0), 0, 1, False
[2023-08-20 17:19:34,025][DEBUG][markdown_it.rules_block.blockquote] - entering blockquote: StateBlock(line=0,level=0,tokens=0), 0, 1, False
[2023-08-20 17:19:34,025][DEBUG][markdown_it.rules_block.hr] - entering hr: StateBlock(line=0,level=0,tokens=0), 0, 1, False
[2023-08-20 17:19:34,025][DEBUG][markdown_it.rules_block.list] - entering list: StateBlock(line=0,level=0,tokens=0), 0, 1, False
[2023-08-20 17:19:34,026][DEBUG][markdown_it.rules_block.reference] - entering reference: StateBlock(line=0,level=0,tokens=0), 0, 1, False
[2023-08-20 17:19:34,026][DEBUG][markdown_it.rules_block.html_block] - entering html_block: StateBlock(line=0,level=0,tokens=0), 0, 1, False
[2023-08-20 17:19:34,027][DEBUG][markdown_it.rules_block.heading] - entering heading: StateBlock(line=0,level=0,tokens=0), 0, 1, False
[2023-08-20 17:19:34,027][DEBUG][markdown_it.rules_block.lheading] - entering lheading: StateBlock(line=0,level=0,tokens=0), 0, 1, False
[2023-08-20 17:19:34,027][DEBUG][markdown_it.rules_block.paragraph] - entering paragraph: StateBlock(line=0,level=0,tokens=0), 0, 1, False
```

### Additional information

I tried to reinstall everything, git pulling, deleting the venv, checking PATH , pip install diffusers

(using Python 3.10.6, Browser is Chrome and OS is Windows!)

**Comment by Lamxue** [comment]
The same problems. Anyone can help?

**Comment by dlebouc** [comment]
Same issue also

**Comment by dlebouc** [comment]
I just solved my issue by completely deleting the extension directory on my dive, relaunching automatic1111 webui then from webui reinstalling dreambooth extensions
