### ISSUE TITLE
[Bug]:  Exception training model: 'intercept_args() got an unexpected keyword argument 'multiprocessing_context''

### ISSUE THREAD

**Issue by joezk** [d8ahazard/sd_dreambooth_extension#1342]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

After generating the class images and before training started I recieved the following error in the web UI of A1111:
Exception training model: 'intercept_args() got an unexpected keyword argument 'multiprocessing_context''.

### Steps to reproduce the problem

Nothing special that I did

### Commit and libraries

Initializing dreambooth training...
Pre-processing images: bes train: : 39it [00:00, 207.26it/s]
Nothing to generate.s: bes train: : 21it [00:00, 209.81it/s]                                    | 0/39 [00:00<?, ?it/s]
                                                                                                                       Enabling xformers memory efficient attention for unet                                            | 0/39 [00:00<?, ?it/s]
Enabling xformers memory efficient attention for unet
                                                                                                                       Found 0 reg images. 0%|                                                                          | 0/39 [00:00<?, ?it/s]
Preparing dataset...
Init dataset!
Preparing Dataset (With Caching)
Bucket 0 (512, 512, 0) - Instance Images: 39 | Class Images: 0 | Max Examples/batch: 39
                                                                                                                       Saving cache!nts...: 100%|██████████████████████████████████████████████████████████████| 39/39 [00:02<00:00, 31.73it/s]
Total Buckets 1 - Instance Images: 39 | Class Images: 0 | Max Examples/batch: 39

Total images / batch: 39, total examples: 39███████████████████████████████████████████| 39/39 [00:02<00:00, 31.73it/s]
                                                                                                                       Total dataset length (steps): 39
                  Initializing bucket counter!
Traceback (most recent call last):
  File "G:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\ui_functions.py", line 729, in start_training
    result = main(class_gen_method=class_gen_method)
  File "G:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1552, in main
    return inner_loop()
  File "G:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 119, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "G:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 614, in inner_loop
    ) = accelerator.prepare(
  File "G:\stable-diffusion-webui\venv\lib\site-packages\accelerate\accelerator.py", line 1202, in prepare
    result = tuple(
  File "G:\stable-diffusion-webui\venv\lib\site-packages\accelerate\accelerator.py", line 1203, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "G:\stable-diffusion-webui\venv\lib\site-packages\accelerate\accelerator.py", line 1028, in _prepare_one
    return self.prepare_data_loader(obj, device_placement=device_placement)
  File "G:\stable-diffusion-webui\venv\lib\site-packages\accelerate\accelerator.py", line 1737, in prepare_data_loader
    prepared_data_loader = prepare_data_loader(
  File "G:\stable-diffusion-webui\venv\lib\site-packages\accelerate\data_loader.py", line 802, in prepare_data_loader
    dataloader = DataLoaderShard(
  File "G:\stable-diffusion-webui\venv\lib\site-packages\accelerate\data_loader.py", line 370, in __init__
    super().__init__(dataset, **kwargs)
TypeError: intercept_args() got an unexpected keyword argument 'multiprocessing_context'
Duration: 00:00:09
0it [00:01, ?it/s]
Restored system models.
Duration: 00:00:10

### Command Line Arguments

```Shell
set COMMANDLINE_ARGS=  --xformers
```

### Console logs

```Shell
i think no need
```

**Comment by dugemkakek** [comment]
did you solve it ?
