### ISSUE TITLE
[Bug]: Dreambooth extension doesn't create any model

### ISSUE THREAD

**Issue by StefSupertramp** [d8ahazard/sd_dreambooth_extension#1372]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Dreambooth gives an error once trying to create a new model, and when checking in Select/Model the model that was supposed to be created is not available. 

### Steps to reproduce the problem

1. Go to Dreambooth/Model/Create Tab
2. Assign a name to the model
3. Assign model type
4. Assign Source Checkpint(v1-5-pruned-emaonly.safetensors [16d91cc746]
5. Press "Create Model" button

### Commit and libraries

Starting at `Initializing Dreambooth` and ending several lines below at `[+] bitsandbytes version 0.35.4 installed.`.

### Command Line Arguments

```Shell
Not an expert, but I don't believe so.
```

### Console logs

```Shell
C:\Program Files (x86)\stable-diffusion-webui>git pull
Already up to date.
venv "C:\Program Files (x86)\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Installing requirements
False

===================================BUG REPORT===================================
================================================================================
The following directories listed in your path were found to be non-existent: {WindowsPath('tmp/restart')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.6.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary C:\Program Files (x86)\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local

===================================BUG REPORT===================================
================================================================================
The following directories listed in your path were found to be non-existent: {WindowsPath('tmp/restart')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.6.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary C:\Program Files (x86)\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local

===================================BUG REPORT===================================
================================================================================
The following directories listed in your path were found to be non-existent: {WindowsPath('tmp/restart')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.6.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary C:\Program Files (x86)\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local

===================================BUG REPORT===================================
================================================================================
The following directories listed in your path were found to be non-existent: {WindowsPath('tmp/restart')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.6.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary C:\Program Files (x86)\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: 1a1d1621086a4725fda1200256f319c845dc7a8a
Successfully installed accelerate-0.23.0 fastapi-0.94.1 transformers-4.32.1

[!] xformers NOT installed.
[+] torch version 2.0.1+cu118 installed.
[+] torchvision version 0.15.2+cu118 installed.
[+] accelerate version 0.23.0 installed.
[+] diffusers version 0.21.4 installed.
[+] transformers version 4.32.1 installed.
[+] bitsandbytes version 0.41.1 installed.
Launching Web UI with arguments: --disable-safe-unpickle
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
[-] ADetailer initialized. version: 23.9.3, num models: 9
2023-10-10 01:45:55,563 - ControlNet - INFO - ControlNet v1.1.410
ControlNet preprocessor location: C:\Program Files (x86)\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-10-10 01:45:55,627 - ControlNet - INFO - ControlNet v1.1.410
Loading weights [62e2993f1d] from C:\Program Files (x86)\stable-diffusion-webui\models\Stable-diffusion\epiCRealism-pureEvolution.safetensors
C:\Program Files (x86)\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py:301: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=False):
False

===================================BUG REPORT===================================
================================================================================
The following directories listed in your path were found to be non-existent: {WindowsPath('tmp/restart')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.6.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary C:\Program Files (x86)\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local

===================================BUG REPORT===================================
================================================================================
The following directories listed in your path were found to be non-existent: {WindowsPath('tmp/restart')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.6.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary C:\Program Files (x86)\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
Creating model from config: C:\Program Files (x86)\stable-diffusion-webui\configs\v1-inference.yaml

===================================BUG REPORT===================================
================================================================================
The following directories listed in your path were found to be non-existent: {WindowsPath('tmp/restart')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.6.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary C:\Program Files (x86)\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local

===================================BUG REPORT===================================
================================================================================
The following directories listed in your path were found to be non-existent: {WindowsPath('tmp/restart')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.6.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary C:\Program Files (x86)\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 32.5s (prepare environment: 25.9s, import torch: 2.1s, import gradio: 0.5s, setup paths: 0.5s, initialize shared: 0.2s, other imports: 0.4s, load scripts: 2.1s, create ui: 0.7s, gradio launch: 0.2s).
Applying attention optimization: Doggettx... done.
Model loaded in 3.2s (load weights from disk: 0.3s, create model: 0.5s, apply weights to model: 1.1s, load textual inversion embeddings: 0.6s, calculate empty prompt: 0.6s).
Extracting config from C:\Program Files (x86)\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\..\configs\v2-training-default.yaml
Extracting checkpoint from C:\Program Files (x86)\stable-diffusion-webui\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Something went wrong, removing model directory
Traceback (most recent call last):
  File "C:\Program Files (x86)\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\sd_to_diff.py", line 171, in extract_checkpoint
    pipe = StableDiffusionPipeline.from_single_file(
  File "C:\Program Files (x86)\stable-diffusion-webui\venv\lib\site-packages\diffusers\loaders.py", line 2308, in from_single_file
    pipe = download_from_original_stable_diffusion_ckpt(
  File "C:\Program Files (x86)\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\convert_from_ckpt.py", line 1233, in download_from_original_stable_diffusion_ckpt
    checkpoint = safe_load(checkpoint_path_or_dict, device="cpu")
  File "C:\Program Files (x86)\stable-diffusion-webui\venv\lib\site-packages\safetensors\torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer
Couldn't find C:\Program Files (x86)\stable-diffusion-webui\models\dreambooth\TestDreamBooth\working\unet
Unable to extract checkpoint!
Duration: 00:00:01
```

**Comment by klubkelli** [comment]
Same issue I posted about yesterday - same Cuda error I get at launch but mine ends with a win5 error. :(

https://github.com/d8ahazard/sd_dreambooth_extension/issues/1371

**Comment by sumingcheng** [comment]
If deleting the plugin still doesn't allow the application to launch, you can manually delete the venv folder and then reinstall the dependencies to get the project running.

**Comment by biollas** [comment]
Blah. Same error.

I figured the odds were about 75% that updating would break something :\

**Comment by StefSupertramp** [comment]
I fixed the problem doing a clean install of SD, I have a completely different error now though, so I believe I might have to do a new post.

**Comment by sertsessiz** [comment]
+1

**Comment by klubkelli** [comment]
It's been exactly a month, and still no resolve on this widespread issue.

**Comment by lorigami-jfh** [comment]
The CUDA SETUP BUG is caused by bitsandbytes and can be solved following the below troubleshooting:


Download https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl


Navigate to your SD's "venv/Scripts" directory For me this is "D:\SD\a1111\venv\Scripts" yours will be different depending where you installed SD.

Place the file you download into "venv/Scripts". You should now have that file located like this D:\SD\a1111\venv\Scripts\bitsandbytes-0.41.1-py3-none-win_amd64.whl (Obviously the part before venv\Scripts" will be different for you.)

Open COMMAND PROMPT

Navigate to that "venv/Scripts" directory.

You command prompt should say you are in "venv/Scripts"

Now type "activate" without the "s



You should now see "venv" in the command prompt.

You now want to type in "pip install bitsandbytes-0.41.1-py3-none-win_amd64.whl" without the "'s

Once this is finished type in "deactivate" without the "'s

Load your WebUI-user.bat as normal your done.

**Comment by SilverRider76** [comment]
> The CUDA SETUP BUG is caused by bitsandbytes and can be solved following the below troubleshooting:
> 
> Download https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl
> 
> Navigate to your SD's "venv/Scripts" directory For me this is "D:\SD\a1111\venv\Scripts" yours will be different depending where you installed SD.
> 
> Place the file you download into "venv/Scripts". You should now have that file located like this D:\SD\a1111\venv\Scripts\bitsandbytes-0.41.1-py3-none-win_amd64.whl (Obviously the part before venv\Scripts" will be different for you.)
> 
> Open COMMAND PROMPT
> 
> Navigate to that "venv/Scripts" directory.
> 
> You command prompt should say you are in "venv/Scripts"
> 
> Now type "activate" without the "s
> 
> You should now see "venv" in the command prompt.
> 
> You now want to type in "pip install bitsandbytes-0.41.1-py3-none-win_amd64.whl" without the "'s
> 
> Once this is finished type in "deactivate" without the "'s
> 
> Load your WebUI-user.bat as normal your done.

Tryied, not working for me. 
and doing a fresh install it tell me is already installed

**Comment by lorigami-jfh** [comment]
> > The CUDA SETUP BUG is caused by bitsandbytes and can be solved following the below troubleshooting:
> > Download https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl
> > Navigate to your SD's "venv/Scripts" directory For me this is "D:\SD\a1111\venv\Scripts" yours will be different depending where you installed SD.
> > Place the file you download into "venv/Scripts". You should now have that file located like this D:\SD\a1111\venv\Scripts\bitsandbytes-0.41.1-py3-none-win_amd64.whl (Obviously the part before venv\Scripts" will be different for you.)
> > Open COMMAND PROMPT
> > Navigate to that "venv/Scripts" directory.
> > You command prompt should say you are in "venv/Scripts"
> > Now type "activate" without the "s
> > You should now see "venv" in the command prompt.
> > You now want to type in "pip install bitsandbytes-0.41.1-py3-none-win_amd64.whl" without the "'s
> > Once this is finished type in "deactivate" without the "'s
> > Load your WebUI-user.bat as normal your done.
> 
> Tryied, not working for me. and doing a fresh install it tell me is already installed

Try to force reinstall with the argument: --force-reinstall

**Comment by SilverRider76** [comment]
> > > The CUDA SETUP BUG is caused by bitsandbytes and can be solved following the below troubleshooting:
> > > Download https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl
> > > Navigate to your SD's "venv/Scripts" directory For me this is "D:\SD\a1111\venv\Scripts" yours will be different depending where you installed SD.
> > > Place the file you download into "venv/Scripts". You should now have that file located like this D:\SD\a1111\venv\Scripts\bitsandbytes-0.41.1-py3-none-win_amd64.whl (Obviously the part before venv\Scripts" will be different for you.)
> > > Open COMMAND PROMPT
> > > Navigate to that "venv/Scripts" directory.
> > > You command prompt should say you are in "venv/Scripts"
> > > Now type "activate" without the "s
> > > You should now see "venv" in the command prompt.
> > > You now want to type in "pip install bitsandbytes-0.41.1-py3-none-win_amd64.whl" without the "'s
> > > Once this is finished type in "deactivate" without the "'s
> > > Load your WebUI-user.bat as normal your done.
> > 
> > 
> > Tryied, not working for me. and doing a fresh install it tell me is already installed
> 
> Try to force reinstall with the argument: --force-reinstall

Like I said, I do also a fresh install, and the package is already installed with the same version.
and I got the same error

**Comment by levicki** [comment]
This is caused by bitsandbytes linux version installed instead of windows version.

Easiest solution is to stop using dreambooth extension and switch to standalone [kohya_ss](https://github.com/bmaltais/kohya_ss) for training since the author of this extension does not seem to be interested in fixing any bugs that have been reported.

**Comment by SilverRider76** [comment]
> This is caused by bitsandbytes linux version installed instead of windows version.
> 
> Easiest solution is to stop using dreambooth extension and switch to standalone [kohya_ss](https://github.com/bmaltais/kohya_ss) for training since the author of this extension does not seem to be interested in fixing any bugs that have been reported.

ah, ok, so I'll try the method wrote before again.

**Comment by SilverRider76** [comment]
Worked!!!! thank you so much!

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by Dwuuds** [comment]
> This is caused by bitsandbytes linux version installed instead of windows version.
> 
> Easiest solution is to stop using dreambooth extension and switch to standalone [kohya_ss](https://github.com/bmaltais/kohya_ss) for training since the author of this extension does not seem to be interested in fixing any bugs that have been reported.
This is literally the best possible option. The Automatic1111 dreambooth plugin is essentially abandoned.

**Comment by d8ahazard** [comment]
How do you figure? Have you looked at the Dev branch?

**Comment by d8ahazard** [comment]
> This is caused by bitsandbytes linux version installed instead of windows version.
> 
> Easiest solution is to stop using dreambooth extension and switch to standalone [kohya_ss](https://github.com/bmaltais/kohya_ss) for training since the author of this extension does not seem to be interested in fixing any bugs that have been reported.

Made a special merge to main, just for you. ;)
