### ISSUE TITLE
[Bug]: bug>There is a conflict between the two plug-ins.MOV 2 MOV

### ISSUE THREAD

**Issue by swumagic** [d8ahazard/sd_dreambooth_extension#1383]
Bitsandbytes  is ok/
but it no ,why?help .tK y!

Traceback (most recent call last):
  File "J:\StableDiffusion\sdwebui\launch.py", line 48, in <module>
    main()
  File "J:\StableDiffusion\sdwebui\launch.py", line 44, in main
    start()
  File "J:\StableDiffusion\sdwebui\modules\launch_utils.py", line 436, in start
    webui.webui()
  File "J:\StableDiffusion\sdwebui\webui.py", line 64, in webui
    shared.demo = ui.create_ui()
  File "J:\StableDiffusion\sdwebui\modules\ui.py", line 1279, in create_ui
    with gr.TabItem(label, id=ifid, elem_id=f"tab_{ifid}"):
  File "J:\StableDiffusion\sdwebui\py310\lib\site-packages\gradio\layouts.py", line 221, in __init__
    BlockContext.__init__(self, elem_id=elem_id, **kwargs)
  File "J:\StableDiffusion\sdwebui\extensions\sd-webui-mov2mov\scripts\m2m_ui.py", line 603, in block_context_init
    on_ui_tabs()
  File "J:\StableDiffusion\sdwebui\extensions\sd-webui-mov2mov\scripts\m2m_ui.py", line 497, in on_ui_tabs
    editor = MovieEditor(id_part, init_mov, movie_frames)
UnboundLocalError: local variable 'movie_frames' referenced before assignment
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

--------

[程序崩溃，退出代码为 1 (0x00000001)]

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by d8ahazard** [comment]
Closed.
