### ISSUE TITLE
[error]: Unable to create model. Received 'ConnectionError' error.

### ISSUE THREAD

**Issue by wusongbai139** [d8ahazard/sd_dreambooth_extension#1384]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When I created a large model in the Dreamroom plugin of the StableDiffusion webui, it was not successfully created, And in the background, the message：

requests. exceptions. ConnectionError: HTTPSConnectionPool (host='raw. gitubusercontent. com', port=443): Max retries exceeded with URL:/CompVis/stable differentiation/main/configurations/table differentiation/v1-inference.yaml (Caused by NewConnectionError ('<urllib3. connection. HTTPSConnection object at 0x0000015AA6628D30>): Failed to establish a New connection: [Errno 11004] Getaddrinfo failed ')
Couldn't find H:  AIGC  SDqi  models  dreamroom  sd15  working  unet
Unable to extract checkpoint!
Duration: 00:00:03

and the number '512' appears on the 'output' in the derambooth of the webui interface

### Steps to reproduce the problem

1. Go to dreambooth extension
2. input：name[sd15]；model type : [v1x]；Source Checkpoint：[v1-5-pruned-emaonly.safetensors [6ce0161689]];
3. Press "create model"
4. The creation was not successful, and the number '512' appears on the 'output' in the derambooth of the webui interface

### Commit and libraries

Starting at `Initializing Dreambooth` and ending several lines below at `[+] bitsandbytes version 0.35.4 installed.`.

Dreambooth revision: 
Successfully installed accelerate-0.23.0 diffusers-0.21.4 fastapi-0.94.1 tensorboard-2.13.0 transformers-4.32.1
[+] xformers version 0.0.22.post7 installed.
[+] torch version 2.1.0+cu121 installed.
[+] torchvision version 0.16.0+cu121 installed.
[+] accelerate version 0.23.0 installed.
[+] diffusers version 0.21.4 installed.
[+] transformers version 4.32.1 installed.
[+] bitsandbytes version 0.41.1 installed.

### Command Line Arguments

```Shell
none
```

### Console logs

```Shell
Extracting config from H:\AIGC\SDqiu\extensions\sd_dreambooth_extension\dreambooth\..\configs\v1-training-default.yaml
Extracting checkpoint from H:\AIGC\SDqiu\models\Stable-diffusion\Realistic\v1-5-pruned-emaonly.safetensors
Something went wrong, removing model directory
Traceback (most recent call last):
  File "H:\AIGC\SDqiu\python\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "H:\AIGC\SDqiu\python\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "H:\AIGC\SDqiu\python\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\AIGC\SDqiu\python\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "H:\AIGC\SDqiu\python\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "H:\AIGC\SDqiu\python\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "H:\AIGC\SDqiu\python\lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "H:\AIGC\SDqiu\python\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x00000204B9630A00>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\AIGC\SDqiu\python\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "H:\AIGC\SDqiu\python\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "H:\AIGC\SDqiu\python\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /CompVis/stable-diffusion/main/configs/stable-diffusion/v1-inference.yaml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000204B9630A00>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\AIGC\SDqiu\extensions\sd_dreambooth_extension\dreambooth\sd_to_diff.py", line 171, in extract_checkpoint
    pipe = StableDiffusionPipeline.from_single_file(
  File "H:\AIGC\SDqiu\python\lib\site-packages\diffusers\loaders.py", line 2308, in from_single_file
    pipe = download_from_original_stable_diffusion_ckpt(
  File "H:\AIGC\SDqiu\python\lib\site-packages\diffusers\pipelines\stable_diffusion\convert_from_ckpt.py", line 1289, in download_from_original_stable_diffusion_ckpt
    original_config_file = BytesIO(requests.get(config_url).content)
  File "H:\AIGC\SDqiu\python\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "H:\AIGC\SDqiu\python\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "H:\AIGC\SDqiu\python\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "H:\AIGC\SDqiu\python\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "H:\AIGC\SDqiu\python\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /CompVis/stable-diffusion/main/configs/stable-diffusion/v1-inference.yaml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000204B9630A00>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))
Couldn't find H:\AIGC\SDqiu\models\dreambooth\11\working\unet
Unable to extract checkpoint!
Duration: 00:00:02
```

**Comment by wusongbai139** [comment]
I can access websites such as "Github" and "huggingface" normally

**Comment by WHUZhangYuhan** [comment]
Make sure your python environment is correct, the python environment under /venv/, and remember to download the requirment.txt plugin for Dreambooth into the python environment.

**Comment by Yannge** [comment]
I'm having the same problem, have you solved it yet?
