### ISSUE TITLE
[Bug]: W&B account prompt

### ISSUE THREAD

**Issue by pereriksson** [d8ahazard/sd_dreambooth_extension#1394]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Not sure if I am using this extension correctly, but my training always ends with the following output in the terminal. I am running it on a notebook so I cannot answer this prompt.

```
Total images / batch: 35, total examples: 35

100%|███████████████████████████████████████████| 35/35 [00:53<00:00,  1.41s/it]
0it [00:00, ?it/s]                                                              
0it [00:00, ?it/s]
0it [00:00, ?it/s]Initializing bucket counter!
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: 

```

### Steps to reproduce the problem

1. Run a simple model with two concepts with default settings
2. Press Train
3. Watch the terminal

### Commit and libraries

Dreambooth revision: c548ede6a3acb85d78650ff50ae583786b305f0e
Checking xformers...
Checking bitsandbytes...
Checking bitsandbytes (Linux)
Installing bitsandbytes
Error occurred: 
Usage:   
  /usr/local/bin/python -m pip install [options] <requirement specifier> [package-index-options] ...
  /usr/local/bin/python -m pip install [options] -r <requirements file> [package-index-options] ...
  /usr/local/bin/python -m pip install [options] [-e] <vcs project url> ...
  /usr/local/bin/python -m pip install [options] [-e] <local project path> ...
  /usr/local/bin/python -m pip install [options] <archive url/path> ...

no such option: --force-install

Checking Dreambooth requirements...
[Dreambooth] accelerate v0.21.0 is already installed.
[Dreambooth] dadaptation v3.1 is already installed.
[Dreambooth] diffusers v0.23.1 is already installed.
[Dreambooth] discord-webhook v1.3.0 is already installed.
[Dreambooth] fastapi is already installed.
[Dreambooth] gitpython v3.1.40 is not installed.
Successfully installed gitpython-3.1.40
[Dreambooth] pytorch_optimizer v2.12.0 is already installed.
[Dreambooth] Pillow is already installed.
[Dreambooth] tqdm is already installed.
[Dreambooth] tomesd v0.1.2 is already installed.
[Dreambooth] transformers v4.25.1 is already installed.
[Dreambooth] tensorboard v2.13.0 is already installed.
[!] xformers NOT installed.
[+] torch version 2.1.1 installed.
[+] torchvision version 0.16.1 installed.
[+] accelerate version 0.21.0 installed.
[+] diffusers version 0.23.1 installed.
[+] transformers version 4.30.2 installed.
[+] bitsandbytes version 0.41.2.post2 installed.

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
/notebooks/stable-diffusion-webui
Python 3.9.16 (main, Dec  7 2022, 01:11:51) 
[GCC 9.4.0]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Installing requirements
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: c548ede6a3acb85d78650ff50ae583786b305f0e
Checking xformers...
Checking bitsandbytes...
Checking bitsandbytes (Linux)
Installing bitsandbytes
Error occurred: 
Usage:   
  /usr/local/bin/python -m pip install [options] <requirement specifier> [package-index-options] ...
  /usr/local/bin/python -m pip install [options] -r <requirements file> [package-index-options] ...
  /usr/local/bin/python -m pip install [options] [-e] <vcs project url> ...
  /usr/local/bin/python -m pip install [options] [-e] <local project path> ...
  /usr/local/bin/python -m pip install [options] <archive url/path> ...

no such option: --force-install

Checking Dreambooth requirements...
[Dreambooth] accelerate v0.21.0 is already installed.
[Dreambooth] dadaptation v3.1 is already installed.
[Dreambooth] diffusers v0.23.1 is already installed.
[Dreambooth] discord-webhook v1.3.0 is already installed.
[Dreambooth] fastapi is already installed.
[Dreambooth] gitpython v3.1.40 is not installed.
Successfully installed gitpython-3.1.40
[Dreambooth] pytorch_optimizer v2.12.0 is already installed.
[Dreambooth] Pillow is already installed.
[Dreambooth] tqdm is already installed.
[Dreambooth] tomesd v0.1.2 is already installed.
[Dreambooth] transformers v4.25.1 is already installed.
[Dreambooth] tensorboard v2.13.0 is already installed.
[!] xformers NOT installed.
[+] torch version 2.1.1 installed.
[+] torchvision version 0.16.1 installed.
[+] accelerate version 0.21.0 installed.
[+] diffusers version 0.23.1 installed.
[+] transformers version 4.30.2 installed.
[+] bitsandbytes version 0.41.2.post2 installed.
Launching Web UI with arguments: --share --config /root/../datasets/stable-diffusion-classic-v2/768-v-ema.yaml --ckpt /root/../datasets/stable-diffusion-classic-v2/768-v-ema.ckpt
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
2023-11-24 17:51:00,426 - ControlNet - INFO - ControlNet v1.1.411
ControlNet preprocessor location: /notebooks/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
2023-11-24 17:51:00,816 - ControlNet - INFO - ControlNet v1.1.411
Loading weights [bfcaf07557] from /root/../datasets/stable-diffusion-classic-v2/768-v-ema.ckpt
Running on local URL:  http://127.0.0.1:7860
Creating model from config: /root/../datasets/stable-diffusion-classic-v2/768-v-ema.yaml
Running on public URL: https://a3fceda2514d7683ad.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
Startup time: 58.5s (prepare environment: 33.0s, import torch: 10.9s, import gradio: 1.0s, setup paths: 0.6s, initialize shared: 0.4s, other imports: 0.8s, setup codeformer: 0.2s, load scripts: 4.7s, create ui: 1.3s, gradio launch: 5.3s).
Applying attention optimization: Doggettx... done.
Model loaded in 12.8s (load weights from disk: 6.5s, create model: 0.2s, apply weights to model: 5.1s, apply half(): 0.1s, load textual inversion embeddings: 0.4s, calculate empty prompt: 0.2s).
Advanced elements visible: False
Exception loading config: [Errno 2] No such file or directory: '/notebooks/stable-diffusion-webui/models/dreambooth/agget2023_karin73/db_config.json'
Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dataclasses/db_config.py", line 511, in from_file
    with open(config_file, 'r') as openfile:
FileNotFoundError: [Errno 2] No such file or directory: '/notebooks/stable-diffusion-webui/models/dreambooth/agget2023_karin73/db_config.json'
Can't load config!
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1434, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1297, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1272, in validate_outputs
    raise ValueError(
ValueError: An event handler (load_model_params) didn't receive enough output values (needed: 11, received: 8).
Wanted outputs:
    [<gradio.layouts.Row object at 0x7fdd45c5bbb0>, html, html, html, html, html, html, html, dropdown, dropdown, html]
Received outputs:
    [{'visible': False, '__type__': 'generic_update'}, "", "", "", "", "", {'visible': True, 'choices': [], 'value': '', '__type__': 'generic_update'}, "Error loading model params: 'agget2023_karin73'."]
Exception loading config: [Errno 2] No such file or directory: '/notebooks/stable-diffusion-webui/models/dreambooth/agget2023_karin73/db_config.json'
Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dataclasses/db_config.py", line 511, in from_file
    with open(config_file, 'r') as openfile:
FileNotFoundError: [Errno 2] No such file or directory: '/notebooks/stable-diffusion-webui/models/dreambooth/agget2023_karin73/db_config.json'
Can't load config!
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.9/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.9/dist-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 605, in load_params
    ui_concept_list = data.concepts(4)
AttributeError: 'NoneType' object has no attribute 'concepts'
Exception loading config: [Errno 2] No such file or directory: '/notebooks/stable-diffusion-webui/models/dreambooth/agget2023_karin73/db_config.json'
Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dataclasses/db_config.py", line 511, in from_file
    with open(config_file, 'r') as openfile:
FileNotFoundError: [Errno 2] No such file or directory: '/notebooks/stable-diffusion-webui/models/dreambooth/agget2023_karin73/db_config.json'
Can't load config!
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.9/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.9/dist-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 605, in load_params
    ui_concept_list = data.concepts(4)
AttributeError: 'NoneType' object has no attribute 'concepts'
Advanced elements visible: True
Exception loading config: [Errno 2] No such file or directory: '/notebooks/stable-diffusion-webui/models/dreambooth/agget2023_karin73/db_config.json'
Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dataclasses/db_config.py", line 511, in from_file
    with open(config_file, 'r') as openfile:
FileNotFoundError: [Errno 2] No such file or directory: '/notebooks/stable-diffusion-webui/models/dreambooth/agget2023_karin73/db_config.json'
Duration: 00:00:00
Error completing request
Arguments: ('agget2023_karin73', 'Native Diffusers') {}
Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/utils/utils.py", line 273, in f
    res = func(*args, **kwargs)
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 689, in start_training
    if config.pretrained_vae_name_or_path == "":
AttributeError: 'NoneType' object has no attribute 'pretrained_vae_name_or_path'

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1434, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1297, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1272, in validate_outputs
    raise ValueError(
ValueError: An event handler (f) didn't receive enough output values (needed: 5, received: 3).
Wanted outputs:
    [dropdown, html, html, gallery, html]
Received outputs:
    [None, "", "<div class='error'>AttributeError: &#x27;NoneType&#x27; object has no attribute &#x27;pretrained_vae_name_or_path&#x27;</div>"]
Exception loading config: [Errno 2] No such file or directory: '/notebooks/stable-diffusion-webui/models/dreambooth/agget2023_karin73/db_config.json'
Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dataclasses/db_config.py", line 511, in from_file
    with open(config_file, 'r') as openfile:
FileNotFoundError: [Errno 2] No such file or directory: '/notebooks/stable-diffusion-webui/models/dreambooth/agget2023_karin73/db_config.json'
Initializing dreambooth training...

0it [00:00, ?it/s]
Pre-processing class images images.: : 0it [00:00, ?it/s]
0it [00:00, ?it/s]                                       
  0%|                                                    | 0/35 [00:00<?, ?it/s]
  0%|                                                    | 0/35 [00:00<?, ?it/s]
  0%|                                                    | 0/35 [00:00<?, ?it/s]
Processing concept 1/2:   0%|                            | 0/35 [00:00<?, ?it/s]
Pre-processing images: armchair:   0%|                   | 0/35 [00:00<?, ?it/s]
Pre-processing images: armchair:  17%|█▉         | 6/35 [00:00<00:00, 56.01it/s]
Processing concept 2/2:  20%|████                | 7/35 [00:00<00:00, 56.01it/s]
Pre-processing images: armchair:  20%|██▏        | 7/35 [00:00<00:00, 56.01it/s]
Pre-processing images: armchair:  37%|███▋      | 13/35 [00:00<00:00, 59.86it/s]
Pre-processing images: armchair:  60%|██████    | 21/35 [00:00<00:00, 65.38it/s]
Pre-processing images: armchair:  80%|████████  | 28/35 [00:00<00:00, 66.18it/s]
Pre-processing images: armchair: 100%|██████████| 35/35 [00:00<00:00, 62.55it/s]
100%|███████████████████████████████████████████| 35/35 [00:00<00:00, 62.55it/s]
  0%|                                                     | 0/5 [00:00<?, ?it/s]
Loading model components...:   0%|                        | 0/5 [00:00<?, ?it/s]
Loading model components...:   0%|                        | 0/5 [00:00<?, ?it/s]
Loading tokenizer...:   0%|                               | 0/5 [00:00<?, ?it/s]
Loading tokenizer...:  20%|████▏                | 1/5 [00:00<00:00, 1407.48it/s]Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 735, in start_training
    result = main(class_gen_method=class_gen_method)
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1830, in main
    return inner_loop()
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 126, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 329, in inner_loop
    tokenizer = AutoTokenizer.from_pretrained(
  File "/usr/local/lib/python3.9/dist-packages/transformers/models/auto/tokenization_auto.py", line 643, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/transformers/models/auto/tokenization_auto.py", line 487, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "/usr/local/lib/python3.9/dist-packages/transformers/utils/hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
  File "/usr/local/lib/python3.9/dist-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/usr/local/lib/python3.9/dist-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/notebooks/stable-diffusion-webui/models/dreambooth/agget2023_karin73/working/tokenizer'. Use `repo_type` argument if needed.
Loading tokenizer...:  20%|████▍                 | 1/5 [00:00<00:00, 186.25it/s]
Duration: 00:00:04
Duration: 00:00:05
Custom model name is agget2023_karin73
Initializing dreambooth training...

0it [00:00, ?it/s]
Pre-processing class images images.: : 0it [00:00, ?it/s]
0it [00:00, ?it/s]                                       
  0%|                                                    | 0/35 [00:00<?, ?it/s]
  0%|                                                    | 0/35 [00:00<?, ?it/s]
  0%|                                                    | 0/35 [00:00<?, ?it/s]
Processing concept 1/2:   0%|                            | 0/35 [00:00<?, ?it/s]
Pre-processing images: armchair:   0%|                   | 0/35 [00:00<?, ?it/s]
Pre-processing images: armchair:  17%|█▉         | 6/35 [00:00<00:00, 58.79it/s]
Processing concept 2/2:  20%|████                | 7/35 [00:00<00:00, 58.79it/s]
Pre-processing images: armchair:  20%|██▏        | 7/35 [00:00<00:00, 58.79it/s]
Pre-processing images: armchair:  34%|███▍      | 12/35 [00:00<00:00, 51.12it/s]
Pre-processing images: armchair:  54%|█████▍    | 19/35 [00:00<00:00, 55.57it/s]
Pre-processing images: armchair:  74%|███████▍  | 26/35 [00:00<00:00, 60.49it/s]
Pre-processing images: armchair:  94%|█████████▍| 33/35 [00:00<00:00, 61.03it/s]
100%|███████████████████████████████████████████| 35/35 [00:00<00:00, 61.03it/s]
  0%|                                                     | 0/5 [00:00<?, ?it/s]
Loading model components...:   0%|                        | 0/5 [00:00<?, ?it/s]
Loading model components...:   0%|                        | 0/5 [00:00<?, ?it/s]
Loading tokenizer...:   0%|                               | 0/5 [00:00<?, ?it/s]
Loading tokenizer...:  20%|████▏                | 1/5 [00:00<00:00, 1248.68it/s]Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 735, in start_training
    result = main(class_gen_method=class_gen_method)
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1830, in main
    return inner_loop()
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 126, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 329, in inner_loop
    tokenizer = AutoTokenizer.from_pretrained(
  File "/usr/local/lib/python3.9/dist-packages/transformers/models/auto/tokenization_auto.py", line 643, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/transformers/models/auto/tokenization_auto.py", line 487, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "/usr/local/lib/python3.9/dist-packages/transformers/utils/hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
  File "/usr/local/lib/python3.9/dist-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/usr/local/lib/python3.9/dist-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/notebooks/stable-diffusion-webui/models/dreambooth/agget2023_karin73/working/tokenizer'. Use `repo_type` argument if needed.
Loading tokenizer...:  20%|████▍                 | 1/5 [00:00<00:00, 506.37it/s]
Duration: 00:00:02
Duration: 00:00:03
Extracting config from /notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/../configs/v2-training-unfrozen-v.yaml
Extracting checkpoint from /root/../datasets/stable-diffusion-classic-v2/768-v-ema.ckpt
/usr/local/lib/python3.9/dist-packages/diffusers/configuration_utils.py:134: FutureWarning: Accessing config attribute `requires_safety_checker` directly via 'StableDiffusionPipeline' object attribute is deprecated. Please access 'requires_safety_checker' over 'StableDiffusionPipeline's config object instead, e.g. 'scheduler.config.requires_safety_checker'.
  deprecate("direct config name access", "1.0.0", deprecation_message, standard_warn=False)
Duration: 00:00:20
Updating scheduler name to: DDIM
Please check your dataset directories.
Duration: 00:00:00
Advanced elements visible: False
Custom model name is agget2023_karin73
Initializing dreambooth training...

0it [00:00, ?it/s]
Pre-processing class images images.: : 0it [00:00, ?it/s]
0it [00:00, ?it/s]                                       
  0%|                                                    | 0/35 [00:00<?, ?it/s]
  0%|                                                    | 0/35 [00:00<?, ?it/s]
  0%|                                                    | 0/35 [00:00<?, ?it/s]
Processing concept 1/2:   0%|                            | 0/35 [00:00<?, ?it/s]
Pre-processing images: armchair:   0%|                   | 0/35 [00:00<?, ?it/s]
Pre-processing images: armchair:  17%|█▉         | 6/35 [00:00<00:00, 59.05it/s]
Processing concept 2/2:  20%|████                | 7/35 [00:00<00:00, 59.05it/s]
Pre-processing images: armchair:  20%|██▏        | 7/35 [00:00<00:00, 59.05it/s]
Pre-processing images: armchair:  37%|███▋      | 13/35 [00:00<00:00, 60.95it/s]
Pre-processing images: armchair:  60%|██████    | 21/35 [00:00<00:00, 65.59it/s]
Pre-processing images: armchair:  83%|████████▎ | 29/35 [00:00<00:00, 67.54it/s]
100%|███████████████████████████████████████████| 35/35 [00:00<00:00, 67.54it/s]
  0%|                                                     | 0/5 [00:00<?, ?it/s]
Loading model components...:   0%|                        | 0/5 [00:00<?, ?it/s]
Loading model components...:   0%|                        | 0/5 [00:00<?, ?it/s]
Loading tokenizer...:   0%|                               | 0/5 [00:00<?, ?it/s]
Loading tokenizer...:  20%|████▏                | 1/5 [00:00<00:00, 1891.03it/s]
Loading text encoder...:  20%|████                | 1/5 [00:00<00:00, 10.42it/s]
Loading text encoder...:  40%|████████            | 2/5 [00:00<00:00, 20.80it/s]
Loading VAE...:  40%|███████████▌                 | 2/5 [00:05<00:08,  2.69s/it]
Loading unet...:  60%|████████████████▊           | 3/5 [00:07<00:04,  2.42s/it]
Loading unet...:  80%|██████████████████████▍     | 4/5 [00:10<00:02,  2.51s/it]
 80%|████████████████████████████████████         | 4/5 [00:11<00:02,  2.78s/it]
  0%|                                                     | 0/5 [00:00<?, ?it/s]
Loading dataset:   0%|                                    | 0/5 [00:00<?, ?it/s]Init dataset!
Preparing Dataset (With Caching)

Preparing Dataset (With Caching):   0%|                   | 0/5 [00:00<?, ?it/s]
  0%|                                                     | 0/5 [00:00<?, ?it/s]
  0%|                                                    | 0/35 [00:00<?, ?it/s]
Loading cached latents...:   0%|                         | 0/35 [00:00<?, ?it/s]
Loading cached latents...:   3%|▍                | 1/35 [00:04<02:46,  4.90s/it]
Loading cached latents...:   6%|▉                | 2/35 [00:06<01:34,  2.85s/it]
Loading cached latents...:   9%|█▍               | 3/35 [00:07<01:10,  2.20s/it]
Loading cached latents...:  11%|█▉               | 4/35 [00:09<00:58,  1.90s/it]
Loading cached latents...:  14%|██▍              | 5/35 [00:10<00:51,  1.73s/it]
Loading cached latents...:  17%|██▉              | 6/35 [00:12<00:47,  1.63s/it]
Loading cached latents...:  20%|███▍             | 7/35 [00:13<00:43,  1.57s/it]
Bucket 0 (768, 768, 0) - Instance Images:  7 | Class Images: 0 | Max Examples/batch:  7

Loading cached latents...:  20%|███▍             | 7/35 [00:13<00:43,  1.57s/it]
Loading cached latents...:  23%|███▉             | 8/35 [00:14<00:41,  1.53s/it]
Loading cached latents...:  26%|████▎            | 9/35 [00:16<00:38,  1.49s/it]
Loading cached latents...:  29%|████▌           | 10/35 [00:17<00:36,  1.47s/it]
Loading cached latents...:  31%|█████           | 11/35 [00:19<00:34,  1.46s/it]
Loading cached latents...:  34%|█████▍          | 12/35 [00:20<00:33,  1.45s/it]
Loading cached latents...:  37%|█████▉          | 13/35 [00:22<00:31,  1.44s/it]
Loading cached latents...:  40%|██████▍         | 14/35 [00:23<00:30,  1.43s/it]
Loading cached latents...:  43%|██████▊         | 15/35 [00:24<00:28,  1.43s/it]
Loading cached latents...:  46%|███████▎        | 16/35 [00:26<00:27,  1.43s/it]
Loading cached latents...:  49%|███████▊        | 17/35 [00:27<00:25,  1.43s/it]
Loading cached latents...:  51%|████████▏       | 18/35 [00:29<00:24,  1.43s/it]
Loading cached latents...:  54%|████████▋       | 19/35 [00:30<00:22,  1.43s/it]
Loading cached latents...:  57%|█████████▏      | 20/35 [00:32<00:21,  1.43s/it]
Loading cached latents...:  60%|█████████▌      | 21/35 [00:33<00:20,  1.44s/it]
Loading cached latents...:  63%|██████████      | 22/35 [00:34<00:18,  1.43s/it]
Loading cached latents...:  66%|██████████▌     | 23/35 [00:36<00:17,  1.43s/it]
Loading cached latents...:  69%|██████████▉     | 24/35 [00:37<00:15,  1.43s/it]
Loading cached latents...:  71%|███████████▍    | 25/35 [00:39<00:14,  1.43s/it]
Loading cached latents...:  74%|███████████▉    | 26/35 [00:40<00:12,  1.43s/it]
Loading cached latents...:  77%|████████████▎   | 27/35 [00:42<00:11,  1.43s/it]
Loading cached latents...:  80%|████████████▊   | 28/35 [00:43<00:09,  1.43s/it]
Loading cached latents...:  83%|█████████████▎  | 29/35 [00:44<00:08,  1.42s/it]
Loading cached latents...:  86%|█████████████▋  | 30/35 [00:46<00:07,  1.42s/it]
Loading cached latents...:  89%|██████████████▏ | 31/35 [00:47<00:05,  1.41s/it]
Loading cached latents...:  91%|██████████████▋ | 32/35 [00:49<00:04,  1.41s/it]
Loading cached latents...:  94%|███████████████ | 33/35 [00:50<00:02,  1.41s/it]
Loading cached latents...:  97%|███████████████▌| 34/35 [00:51<00:01,  1.41s/it]
Loading cached latents...: 100%|████████████████| 35/35 [00:53<00:00,  1.41s/it]
Bucket 1 (768, 768, 1) - Instance Images: 28 | Class Images: 0 | Max Examples/batch: 28

Loading cached latents...: 100%|████████████████| 35/35 [00:53<00:00,  1.41s/it]Saving cache!

Total Buckets 2 - Instance Images: 35 | Class Images: 0 | Max Examples/batch: 35

Loading cached latents...: 100%|████████████████| 35/35 [00:53<00:00,  1.41s/it]
Total images / batch: 35, total examples: 35

100%|███████████████████████████████████████████| 35/35 [00:53<00:00,  1.41s/it]
0it [00:00, ?it/s]                                                              
0it [00:00, ?it/s]
0it [00:00, ?it/s]Initializing bucket counter!
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice:
```

**Comment by CHNAICORP** [comment]
1. Today, when I ran the ./webui.sh of stable-diffusion-webui on the Linux system, the same problem as yours also occurred. Then I went to the `stable-diffusion-webui/extensions/sd_dreambooth_extension/postinstall.py` directory to view the source code and found this problem at line 246. As shown below.
![image](https://github.com/d8ahazard/sd_dreambooth_extension/assets/61525966/f1282154-0410-4906-8bd6-ed0273ccfe37)
2. The cause of the error is the Linux system environment: a non-existent option --force-install is used in the pip_install function. This option is not a valid option in the pip command, which is why the error message "no such option: --force-install" appears.
3. To solve this problem. I commented out line 246. Then add `pip_install("bitsandbytes==0.41.1")` and restart ./webui.sh to install bitsandbytes normally.
