### ISSUE TITLE
Whats wrong with that addon? can NOT start offline anymore

### ISSUE THREAD

**Issue by Username69992872** [d8ahazard/sd_dreambooth_extension#140]
Since the dreambooth extension is installed, its not possible to start stable-diffusion offline anymore, as its throwing error that depenencies are missing. So its like when being online it temp downloads those dependencies, but its doing that always again without saving local.

**Comment by Username69992872** [comment]
This may also be related to this problem: I am using a different temp directory set in launch.py, as on Windows stable-diffusion is saving EVERY generated image in the temp directory, without even deleting it, which is a big security issue and related to apache. So I changed that temp directory to a ramdisk, which is mounted on X: 
Looks like the dreambooth extension is saving something in that temp directory and cant, because it need premission for a different temp directory.
![cmd_wx387Kvxqw](https://user-images.githubusercontent.com/96194225/201445201-c980440c-92a5-4fcd-8fa6-3d5101aadbb1.png)

**Comment by neojam** [comment]
It's downloading diffusers every time you run the script, see:
https://github.com/d8ahazard/sd_dreambooth_extension/issues/128

Apparently you didn't let it do so last time, since your console says that you still running 0.3.0 diffusers.

**Comment by Username69992872** [comment]
I understand, so the problem is that it tries to download everytime when starting stable-diffusion, means offline mode with the dreambooth extension is not possible. Is that intended ? Any way to fix that ?

thx for the .bat tip!

**Comment by d8ahazard** [comment]
> I understand, so the problem is that it tries to download everytime when starting stable-diffusion, means offline mode with the dreambooth extension is not possible. Is that intended ? Any way to fix that ?
> 
> thx for the .bat tip!

I pushed an update yesterday that *should* use a local .yaml file when creating a new dreambooth model, so you *should* be able to run this in offline mode now if you apply the flags to the bat/sh file.

Please verify and close this if resolved. :D

**Comment by Username69992872** [comment]
Just tested with a fresh dreambooth extension install. Being online it starts, without internet connection it throws an error:

![cmd_5htpfFrLu3](https://user-images.githubusercontent.com/96194225/201532441-71204b68-e76b-4162-ba3f-77dd8681fbc6.png)

**Comment by d8ahazard** [comment]
Have you run it "online" once to download the required files?

**Comment by Username69992872** [comment]
yes I did

**Comment by d8ahazard** [comment]
Okay, just for you, I've added an option to specify a command-line flag to completely skip the install routine.

This, in conjunction with the yaml file being local, should now completely remove any online requirements, once you've installed the "new" requirements.txt file and Torch versions.

f946126

**Comment by neojam** [comment]
Thanks,
worked for Retirements, but did not work when creating new Model:

```
Creating dreambooth model folder: t44444
Checkpoint loaded from CheckpointInfo(filename='X:\\stable-diffusion-webui\\models\\Stable-diffusion\\sd\\sd-v1-5-pruned--a9263745.ckpt', title='sd\\sd-v1-5-pruned--a9263745.ckpt [a9263745]', hash='a9263745', model_name='sd_sd-v1-5-pruned--a9263745', config='X:\\stable-diffusion-webui\\repos
itories\\stable-diffusion\\configs/stable-diffusion/v1-inference.yaml')
Exception with the conversion: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like CompVis/stable-diffusion-safety-checker is not the path to a directory containing a config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
Traceback (most recent call last):
  File "X:\stable-diffusion-webui\venv\lib\site-packages\transformers\configuration_utils.py", line 616, in _get_config_dict
    resolved_config_file = cached_path(
  File "X:\stable-diffusion-webui\venv\lib\site-packages\transformers\utils\hub.py", line 284, in cached_path
    output_path = get_from_cache(
  File "X:\stable-diffusion-webui\venv\lib\site-packages\transformers\utils\hub.py", line 562, in get_from_cache
    raise ValueError(
ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "X:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\conversion.py", line 902, in extract_checkpoint
    safety_checker = StableDiffusionSafetyChecker.from_pretrained("CompVis/stable-diffusion-safety-checker")
  File "X:\stable-diffusion-webui\venv\lib\site-packages\transformers\modeling_utils.py", line 1833, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "X:\stable-diffusion-webui\venv\lib\site-packages\transformers\configuration_utils.py", line 534, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "X:\stable-diffusion-webui\venv\lib\site-packages\transformers\configuration_utils.py", line 561, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "X:\stable-diffusion-webui\venv\lib\site-packages\transformers\configuration_utils.py", line 649, in _get_config_dict
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like CompVis/stable-diffusion-safety-checker is not the path to a directory containing a config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

```

**Comment by ffdown** [comment]
> Thanks, worked for Retirements, but did not work when creating new Model:
> 
> ```
> Creating dreambooth model folder: t44444
> Checkpoint loaded from CheckpointInfo(filename='X:\\stable-diffusion-webui\\models\\Stable-diffusion\\sd\\sd-v1-5-pruned--a9263745.ckpt', title='sd\\sd-v1-5-pruned--a9263745.ckpt [a9263745]', hash='a9263745', model_name='sd_sd-v1-5-pruned--a9263745', config='X:\\stable-diffusion-webui\\repos
> itories\\stable-diffusion\\configs/stable-diffusion/v1-inference.yaml')
> Exception with the conversion: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like CompVis/stable-diffusion-safety-checker is not the path to a directory containing a config.json file.
> Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
> Traceback (most recent call last):
>   File "X:\stable-diffusion-webui\venv\lib\site-packages\transformers\configuration_utils.py", line 616, in _get_config_dict
>     resolved_config_file = cached_path(
>   File "X:\stable-diffusion-webui\venv\lib\site-packages\transformers\utils\hub.py", line 284, in cached_path
>     output_path = get_from_cache(
>   File "X:\stable-diffusion-webui\venv\lib\site-packages\transformers\utils\hub.py", line 562, in get_from_cache
>     raise ValueError(
> ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "X:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\conversion.py", line 902, in extract_checkpoint
>     safety_checker = StableDiffusionSafetyChecker.from_pretrained("CompVis/stable-diffusion-safety-checker")
>   File "X:\stable-diffusion-webui\venv\lib\site-packages\transformers\modeling_utils.py", line 1833, in from_pretrained
>     config, model_kwargs = cls.config_class.from_pretrained(
>   File "X:\stable-diffusion-webui\venv\lib\site-packages\transformers\configuration_utils.py", line 534, in from_pretrained
>     config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
>   File "X:\stable-diffusion-webui\venv\lib\site-packages\transformers\configuration_utils.py", line 561, in get_config_dict
>     config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
>   File "X:\stable-diffusion-webui\venv\lib\site-packages\transformers\configuration_utils.py", line 649, in _get_config_dict
>     raise EnvironmentError(
> OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like CompVis/stable-diffusion-safety-checker is not the path to a directory containing a config.json file.
> Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
> ```

same, how fix?
