### ISSUE TITLE
[Bug]:  ImportError: cannot import name 'StableDiffusionXLPipeline' from 'diffusers'

### ISSUE THREAD

**Issue by yincangshiwei** [d8ahazard/sd_dreambooth_extension#1400]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

ImportError: cannot import name 'StableDiffusionXLPipeline' from 'diffusers'

### Steps to reproduce the problem

Start Service

### Commit and libraries

last

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
Traceback (most recent call last):
  File "/root/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/api.py", line 32, in <module>
    from dreambooth.ui_functions import create_model, generate_samples, \
  File "/root/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 28, in <module>
    from dreambooth.sd_to_diff import extract_checkpoint
  File "/root/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/sd_to_diff.py", line 24, in <module>
    from diffusers import StableDiffusionXLPipeline, StableDiffusionPipeline
ImportError: cannot import name 'StableDiffusionXLPipeline' from 'diffusers' (/root/miniconda3/lib/python3.10/site-packages/diffusers/__init__.py)
*** Error loading script: main.py
    Traceback (most recent call last):
      File "/root/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/root/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/root/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 20, in <module>
        from dreambooth.ui_functions import (
      File "/root/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 28, in <module>
        from dreambooth.sd_to_diff import extract_checkpoint
      File "/root/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/sd_to_diff.py", line 24, in <module>
        from diffusers import StableDiffusionXLPipeline, StableDiffusionPipeline
    ImportError: cannot import name 'StableDiffusionXLPipeline' from 'diffusers' (/root/miniconda3/lib/python3.10/site-packages/diffusers/__init__.py)
```

**Comment by AvedisBaghdasarian** [comment]
What diffusers version are you running? (pip show diffusers)

ive got 0.15.0.dev and im seeing the same thing. There is no importable in diffusers by that name

```

import diffusers

print(dir(diffusers))

['AltDiffusionImg2ImgPipeline', 'AltDiffusionPipeline', 'AudioDiffusionPipeline', 'AudioPipelineOutput', 'AutoencoderKL', 'ConfigMixin', 'ControlNetModel', 'CycleDiffusionPipeline', 'DDIMInverseScheduler', 'DDIMPipeline', 'DDIMScheduler', 'DDPMPipeline', 'DDPMScheduler', 'DEISMultistepScheduler', 'DPMSolverMultistepScheduler', 'DPMSolverSinglestepScheduler', 'DanceDiffusionPipeline', 'DiTPipeline', 'DiffusionPipeline', 'DummyObject', 'EMAModel', 'EulerAncestralDiscreteScheduler', 'EulerDiscreteScheduler', 'FlaxAutoencoderKL', 'FlaxDDIMScheduler', 'FlaxDDPMScheduler', 'FlaxDPMSolverMultistepScheduler', 'FlaxDiffusionPipeline', 'FlaxKarrasVeScheduler', 'FlaxLMSDiscreteScheduler', 'FlaxModelMixin', 'FlaxPNDMScheduler', 'FlaxSchedulerMixin', 'FlaxScoreSdeVeScheduler', 'FlaxStableDiffusionImg2ImgPipeline', 'FlaxStableDiffusionInpaintPipeline', 'FlaxStableDiffusionPipeline', 'FlaxUNet2DConditionModel', 'HeunDiscreteScheduler', 'IPNDMScheduler', 'ImagePipelineOutput', 'KDPM2AncestralDiscreteScheduler', 'KDPM2DiscreteScheduler', 'KarrasVePipeline', 'KarrasVeScheduler', 'LDMPipeline', 'LDMSuperResolutionPipeline', 'LDMTextToImagePipeline', 'LMSDiscreteScheduler', 'Mel', 'ModelMixin', 'OnnxRuntimeModel', 'OnnxStableDiffusionImg2ImgPipeline', 'OnnxStableDiffusionInpaintPipeline', 'OnnxStableDiffusionInpaintPipelineLegacy', 'OnnxStableDiffusionPipeline', 'OnnxStableDiffusionUpscalePipeline', 'OptionalDependencyNotAvailable', 'PNDMPipeline', 'PNDMScheduler', 'PaintByExamplePipeline', 'PriorTransformer', 'RePaintPipeline', 'RePaintScheduler', 'SchedulerMixin', 'ScoreSdeVePipeline', 'ScoreSdeVeScheduler', 'SemanticStableDiffusionPipeline', 'StableDiffusionAttendAndExcitePipeline', 'StableDiffusionControlNetPipeline', 'StableDiffusionDepth2ImgPipeline', 'StableDiffusionImageVariationPipeline', 'StableDiffusionImg2ImgPipeline', 'StableDiffusionInpaintPipeline', 'StableDiffusionInpaintPipelineLegacy', 'StableDiffusionInstructPix2PixPipeline', 'StableDiffusionKDiffusionPipeline', 'StableDiffusionLatentUpscalePipeline', 'StableDiffusionOnnxPipeline', 'StableDiffusionPanoramaPipeline', 'StableDiffusionPipeline', 'StableDiffusionPipelineSafe', 'StableDiffusionPix2PixZeroPipeline', 'StableDiffusionSAGPipeline', 'StableDiffusionUpscalePipeline', 'StableUnCLIPImg2ImgPipeline', 'StableUnCLIPPipeline', 'Transformer2DModel', 'UNet1DModel', 'UNet2DConditionModel', 'UNet2DModel', 'UnCLIPImageVariationPipeline', 'UnCLIPPipeline', 'UnCLIPScheduler', 'UniPCMultistepScheduler', 'VQDiffusionPipeline', 'VQDiffusionScheduler', 'VQModel', 'VersatileDiffusionDualGuidedPipeline', 'VersatileDiffusionImageVariationPipeline', 'VersatileDiffusionPipeline', 'VersatileDiffusionTextToImagePipeline', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'configuration_utils', 'get_constant_schedule', 'get_constant_schedule_with_warmup', 'get_cosine_schedule_with_warmup', 'get_cosine_with_hard_restarts_schedule_with_warmup', 'get_linear_schedule_with_warmup', 'get_polynomial_decay_schedule_with_warmup', 'get_scheduler', 'image_processor', 'is_flax_available', 'is_inflect_available', 'is_k_diffusion_available', 'is_k_diffusion_version', 'is_librosa_available', 'is_onnx_available', 'is_scipy_available', 'is_torch_available', 'is_transformers_available', 'is_transformers_version', 'is_unidecode_available', 'loaders', 'logging', 'models', 'optimization', 'pipeline_utils', 'pipelines', 'requires_backends', 'schedulers', 'training_utils', 'utils']

```

**Comment by AvedisBaghdasarian** [comment]
I fixed it by just manually doing `pip install -r <extension location>/requirements.txt`
