### ISSUE TITLE
[Bug]: *** ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by swumagic** [d8ahazard/sd_dreambooth_extension#1425]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

*** Error running install.py for extension J:\StableDiffusion\sdwebui\extensions\sd_dreambooth_extension.
*** Command: "J:\StableDiffusion\sdwebui\py310\python.exe" "J:\StableDiffusion\sdwebui\extensions\sd_dreambooth_extension\install.py"
*** Error code: 1
*** stdout: If submitting an issue on github, please provide the full startup log for debugging purposes.
***
*** Initializing Dreambooth
*** Dreambooth revision: 22e5440e15eea1be6c8f8ce407d2d8c273b2cc9c
*** Checking xformers...
*** Checking bitsandbytes...
*** Checking bitsandbytes (Windows)
*** Virtual environment path: None
*** Could not find the virtual environment path. Skipping bitsandbytes installation.
*** Checking Dreambooth requirements...
*** [Dreambooth] accelerate v0.23.0 is already installed.
*** [Dreambooth] bitsandbytes v0.41.1 is already installed.
*** [Dreambooth] dadaptation v3.1 is already installed.
*** [Dreambooth] diffusers v0.23.1 is already installed.
*** [Dreambooth] discord-webhook v1.3.0 is already installed.
*** [Dreambooth] fastapi v0.94.1 is already installed.
*** [Dreambooth] gitpython v3.1.40 is already installed.
*** [Dreambooth] pytorch_optimizer v2.12.0 is already installed.
*** [Dreambooth] lion-pytorch v0.1.2 is already installed.
*** [Dreambooth] Pillow v9.5.0 is already installed.
*** [Dreambooth] tqdm v4.65.0 is already installed.
*** [Dreambooth] tomesd v0.1.3 is already installed.
*** [Dreambooth] google-auth-oauthlib v0.5 is already installed.
*** [Dreambooth] transformers v4.30.2 is already installed.
***
*** stderr: J:\StableDiffusion\sdwebui\py310\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
***   rank_zero_deprecation(
*** [2023-12-24 22:29:49,335][DEBUG][git.cmd] - Popen(['git', 'version'], cwd=J:\StableDiffusion\sdwebui, stdin=None, shell=False, universal_newlines=False)
*** [2023-12-24 22:29:49,377][DEBUG][git.cmd] - Popen(['git', 'version'], cwd=J:\StableDiffusion\sdwebui, stdin=None, shell=False, universal_newlines=False)
*** J:\StableDiffusion\sdwebui\extensions\sd_dreambooth_extension\dreambooth\shared.py:355: UserWarning: 'has_mps' is deprecated, please use 'torch.backends.mps.is_built()'
***   if getattr(torch, 'has_mps', False):
*** [2023-12-24 22:29:49,423][DEBUG][git.cmd] - Popen(['git', 'cat-file', '--batch-check'], cwd=J:\StableDiffusion\sdwebui\extensions\sd_dreambooth_extension, stdin=<valid stream>, shell=False, universal_newlines=False)
*** Traceback (most recent call last):
***   File "J:\StableDiffusion\sdwebui\extensions\sd_dreambooth_extension\install.py", line 35, in <module>
***     actual_install()
***   File "J:\StableDiffusion\sdwebui\extensions\sd_dreambooth_extension\postinstall.py", line 47, in actual_install
***     install_requirements()
***   File "J:\StableDiffusion\sdwebui\extensions\sd_dreambooth_extension\postinstall.py", line 136, in install_requirements
***     package, package_version = line.split(separator)
*** ValueError: too many values to unpack (expected 2)
ReActor preheating... Device: CUDA
loading WD14-tagger reqs from J:\StableDiffusion\sdwebui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt
Checking WD14-tagger requirements.
Faceswaplab : Use GPU requirements
Checking faceswaplab requirements
0.002231000000392669
Launching Web UI with arguments: --theme dark --xformers --api --autolaunch --enable-insecure-extension-access --allow-code
WARNING:tensorflow:From J:\StableDiffusion\sdwebui\py310\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

### Steps to reproduce the problem

bug

### Commit and libraries

1

### Command Line Arguments

```Shell
1
```

### Console logs

```Shell
Launching Web UI with arguments: --theme dark --xformers --api --autolaunch --enable-insecure-extension-access --allow-code
win11,4090RTX，3.10PYTHON，cuda11.8,TURCH2.1.2,XFORMERS0.0.23
```

**Comment by swumagic** [comment]
https://github.com/d8ahazard/sd_dreambooth_extension/commit/d8e01e1fd13dd4b6afadbb0382875f905ee5f429  
BUT MY PC run 2023.10.31Versions  is ok/  Versions updated after 10.31 cannot run.
