### ISSUE TITLE
[Bug]: what is AutoIntegrityCheck==0.1 in requirements.txt ?

### ISSUE THREAD

**Issue by So0ni** [d8ahazard/sd_dreambooth_extension#1429]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I got a failed installation.  

AutoIntegrityCheck seems not an open source package and I can't find any information about this package on github. 

<img width="1114" alt="image" src="https://github.com/d8ahazard/sd_dreambooth_extension/assets/21233257/77d20a20-2158-4454-9e3e-c542a02dfd26">

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### Commit and libraries

Starting at `Initializing Dreambooth` and ending several lines below at `[+] bitsandbytes version 0.35.4 installed.`.

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
Collecting AutoIntegrityCheck==0.1
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-hpar1py1/autointegritycheck_bb6b6d61d4c94121833157e1935da636/setup.py", line 27, in <module>
          ext_modules=cythonize(extensions),
        File "/root/stable-diffusion-webui/venv/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 973, in cythonize
          module_list, module_metadata = create_extension_list(
        File "/root/stable-diffusion-webui/venv/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 816, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "/root/stable-diffusion-webui/venv/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 114, in nonempty
          raise ValueError(error_msg)
      ValueError: 'AutoIntegrityCheck/validator.py' doesn't match any files
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

**Comment by d8ahazard** [comment]
You can disregard that. Was testing some things, didn't mean to push that
one. I've pulled it till it's published. ;)
