### ISSUE TITLE
[Bug]: Couldn't find D:\AI\stable-diffusion-webui\models\dreambooth\greyuimage\working\unet Unable to extract checkpoint!

### ISSUE THREAD

**Issue by kochien** [d8ahazard/sd_dreambooth_extension#1437]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

can not creat a model

windows

google chorme

### Steps to reproduce the problem

Open the dream booth option, enter the creation name, select the model base, and click Create

### Commit and libraries

Initializing Dreambooth
Dreambooth revision: 8207ccd85430fdfddcb4afa8589c88305be40f9c
Checking xformers...
Xformers is outdated, and automatic installation has been removed. Please install manually if desired.
Checking bitsandbytes...
Checking bitsandbytes (Windows)
Virtual environment path: D:\AI\stable-diffusion-webui\venv
Checking for D:\AI\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda111.dll
Found windows BNB DLL D:\AI\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda111.dll
Checking Dreambooth requirements...
Installed version of accelerate: 0.21.0
[Dreambooth] accelerate v0.21.0 is already installed.
Installed version of dadaptation: 3.2
[Dreambooth] dadaptation v3.2 is already installed.
Installed version of diffusers: 0.25.0
[Dreambooth] diffusers v0.25.0 is already installed.
Installed version of discord-webhook: 1.3.0
[Dreambooth] discord-webhook v1.3.0 is already installed.
Installed version of fastapi: 0.94.0
[Dreambooth] fastapi is already installed.
Installed version of gitpython: 3.1.32
[Dreambooth] gitpython v3.1.40 is not installed.
Successfully installed gitpython-3.1.41

Installed version of pytorch_optimizer: 2.12.0
[Dreambooth] pytorch_optimizer v2.12.0 is already installed.
Installed version of Pillow: 9.5.0
[Dreambooth] Pillow is already installed.
Installed version of tqdm: 4.66.1
[Dreambooth] tqdm is already installed.
Installed version of tomesd: 0.1.3
[Dreambooth] tomesd v0.1.2 is already installed.
Installed version of tensorboard: 2.13.0
[Dreambooth] tensorboard v2.13.0 is already installed.
[+] torch version 2.0.1+cu118 installed.
[+] torchvision version 0.15.2+cu118 installed.
[+] accelerate version 0.21.0 installed.
[+] diffusers version 0.25.0 installed.
[+] bitsandbytes version 0.41.2.post2 installed.
[!] xformers version 0.0.20 installed.
Launching Web UI with arguments: --xformers

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
bin D:\AI\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.dll
Style database not found: D:\AI\stable-diffusion-webui\styles.csv
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 24.1.0, num models: 9
ControlNet preprocessor location: D:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2024-01-10 21:20:55,739 - ControlNet - INFO - ControlNet v1.1.427
2024-01-10 21:20:55,799 - ControlNet - INFO - ControlNet v1.1.427
[sd-webui-freeu] Controlnet support: *enabled*
sd-webui-prompt-all-in-one background API service started successfully.
Loading weights [1a189f0be6] from D:\AI\stable-diffusion-webui\models\Stable-diffusion\v1-5-pruned.safetensors
Creating model from config: D:\AI\stable-diffusion-webui\configs\v1-inference.yaml
Running on local URL:  http://127.0.0.1:7860
Applying attention optimization: xformers... done.
Model loaded in 2.5s (load weights from disk: 0.6s, create model: 0.3s, apply weights to model: 1.4s).

To create a public link, set `share=True` in `launch()`.
Startup time: 32.8s (prepare environment: 21.3s, import torch: 1.8s, import gradio: 0.6s, setup paths: 0.7s, initialize shared: 0.1s, other imports: 0.3s, load scripts: 4.5s, create ui: 0.7s, gradio launch: 2.4s).
Advanced elements visible: False
Extracting config from D:\AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\..\configs\v1-training-unfrozen.yaml
Extracting checkpoint from D:\AI\stable-diffusion-webui\models\Stable-diffusion\v1-5-pruned.safetensors
Something went wrong, removing model directory
Traceback (most recent call last):
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\urllib3\connectionpool.py", line 777, in urlopen
    self._prepare_proxy(conn)
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\urllib3\connectionpool.py", line 1046, in _prepare_proxy
    conn.connect()
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\urllib3\connection.py", line 625, in connect
    self._tunnel()  # type: ignore[attr-defined]
  File "C:\Users\w\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 920, in _tunnel
    (version, code, message) = response._read_status()
  File "C:\Users\w\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\urllib3\connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\urllib3\connectionpool.py", line 777, in urlopen
    self._prepare_proxy(conn)
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\urllib3\connectionpool.py", line 1046, in _prepare_proxy
    conn.connect()
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\urllib3\connection.py", line 625, in connect
    self._tunnel()  # type: ignore[attr-defined]
  File "C:\Users\w\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 920, in _tunnel
    (version, code, message) = response._read_status()
  File "C:\Users\w\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\sd_to_diff.py", line 171, in extract_checkpoint
    pipe = StableDiffusionPipeline.from_single_file(
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\diffusers\loaders\single_file.py", line 263, in from_single_file
    pipe = download_from_original_stable_diffusion_ckpt(
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\convert_from_ckpt.py", line 1319, in download_from_original_stable_diffusion_ckpt
    original_config_file = BytesIO(requests.get(config_url).content)
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Couldn't find D:\AI\stable-diffusion-webui\models\dreambooth\greyuimage\working\unet
Unable to extract checkpoint!
Duration: 00:00:01
```

### Additional information

I tried SD1.5 and SDXL1.0, but they didn't work. In stable-diffusion-webui\models\dreambooth, my folder will be generated for a while, but it will disappear instantly.

**Comment by moteloumka** [comment]
got the same problem going on

**Comment by rmcc3** [comment]
Same problem. Any solution?

**Comment by moteloumka** [comment]
@rmcc3 honestly just use https://github.com/bmaltais/kohya_ss for lora or dream booth training. Would also recommend using comfy UI instead of automatic 1111, never really got any lags there.

**Comment by rmcc3** [comment]
> @rmcc3 honestly just use https://github.com/bmaltais/kohya_ss for lora or dream booth training. Would also recommend using comfy UI instead of automatic 1111, never really got any lags there.

Was trying that, but the training seems ungodly slow. Almost 50 hours to train a lora on my 4070 no matter what settings I try.

**Comment by moteloumka** [comment]
@rmcc3 hmmm that's strangely slow... takes maximum and hour on a 3090. Just in case, runpod has containers with kohya ss pre installed. You'd be able to train whatever you want in no time!
