### ISSUE TITLE
[Bug]:  Error running install.py for extension +TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by swumagic** [d8ahazard/sd_dreambooth_extension#1446]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

*** Error running install.py for extension M:\SD\sdwebui\extensions\sd_dreambooth_extension.
*** Command: "M:\SD\sdwebui\py310\python.exe" "M:\SD\sdwebui\extensions\sd_dreambooth_extension\install.py"
*** Error code: 1
*** stdout: If submitting an issue on github, please provide the full startup log for debugging purposes.
***
*** Initializing Dreambooth
*** Dreambooth revision: 71c3465b6c866050b147c58e2caf41984df2cf45
*** Checking xformers...
*** Checking bitsandbytes...
*** Checking bitsandbytes (Windows)
***
*** stderr: M:\SD\sdwebui\py310\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
***   rank_zero_deprecation(
*** [2024-01-24 05:58:53,434][DEBUG][git.cmd] - Popen(['git', 'version'], cwd=M:\SD\sdwebui, stdin=None, shell=False, universal_newlines=False)
*** [2024-01-24 05:58:53,556][DEBUG][git.cmd] - Popen(['git', 'version'], cwd=M:\SD\sdwebui, stdin=None, shell=False, universal_newlines=False)
*** [2024-01-24 05:58:53,688][DEBUG][git.cmd] - Popen(['git', 'cat-file', '--batch-check'], cwd=M:\SD\sdwebui\extensions\sd_dreambooth_extension, stdin=<valid stream>, shell=False, universal_newlines=False)
*** Traceback (most recent call last):
***   File "M:\SD\sdwebui\extensions\sd_dreambooth_extension\install.py", line 35, in <module>
***     actual_install()
***   File "M:\SD\sdwebui\extensions\sd_dreambooth_extension\postinstall.py", line 59, in actual_install
***     check_bitsandbytes()
***   File "M:\SD\sdwebui\extensions\sd_dreambooth_extension\postinstall.py", line 217, in check_bitsandbytes
***     if ";" in venv_path:
*** TypeError: argument of type 'NoneType' is not iterable

### Steps to reproduce the problem

SD1.7.0，python3.10.11,212+cu118,rtx4090,windows11

### Commit and libraries

 TypeError: argument of type 'NoneType' is not iterable

### Command Line Arguments

```Shell
Launching Web UI with arguments: --medvram --theme dark --xformers --api --autolaunch --enable-insecure-extension-access --allow-code
```

### Console logs

```Shell
*** Error running install.py for extension M:\SD\sdwebui\extensions\sd_dreambooth_extension.
*** Command: "M:\SD\sdwebui\py310\python.exe" "M:\SD\sdwebui\extensions\sd_dreambooth_extension\install.py"
*** Error code: 1
*** stdout: If submitting an issue on github, please provide the full startup log for debugging purposes.
***
*** Initializing Dreambooth
*** Dreambooth revision: 71c3465b6c866050b147c58e2caf41984df2cf45
*** Checking xformers...
*** Checking bitsandbytes...
*** Checking bitsandbytes (Windows)
***
*** stderr: M:\SD\sdwebui\py310\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
***   rank_zero_deprecation(
*** [2024-01-24 06:22:05,651][DEBUG][git.cmd] - Popen(['git', 'version'], cwd=M:\SD\sdwebui, stdin=None, shell=False, universal_newlines=False)
*** [2024-01-24 06:22:05,793][DEBUG][git.cmd] - Popen(['git', 'version'], cwd=M:\SD\sdwebui, stdin=None, shell=False, universal_newlines=False)
*** [2024-01-24 06:22:05,942][DEBUG][git.cmd] - Popen(['git', 'cat-file', '--batch-check'], cwd=M:\SD\sdwebui\extensions\sd_dreambooth_extension, stdin=<valid stream>, shell=False, universal_newlines=False)
*** Traceback (most recent call last):
***   File "M:\SD\sdwebui\extensions\sd_dreambooth_extension\install.py", line 35, in <module>
***     actual_install()
***   File "M:\SD\sdwebui\extensions\sd_dreambooth_extension\postinstall.py", line 59, in actual_install
***     check_bitsandbytes()
***   File "M:\SD\sdwebui\extensions\sd_dreambooth_extension\postinstall.py", line 217, in check_bitsandbytes
***     if ";" in venv_path:
*** TypeError: argument of type 'NoneType' is not iterable
```

**Comment by swumagic** [comment]
https://github.com/d8ahazard/sd_dreambooth_extension/commit/d8e01e1fd13dd4b6afadbb0382875f905ee5f429
BUT The update on October 30, 2023 can run normally.
Initializing Dreambooth
Dreambooth revision: d8e01e1fd13dd4b6afadbb0382875f905ee5f429
[+] xformers version 0.0.23.post1+cu118 installed.
[+] torch version 2.1.2+cu118 installed.
[+] torchvision version 0.16.2+cu118 installed.
[+] accelerate version 0.23.0 installed.
[+] diffusers version 0.25.1 installed.
[+] transformers version 4.30.2 installed.
[+] bitsandbytes version 0.41.1 installed.
