### ISSUE TITLE
[Bug]: TypeError: intercept_args() got an unexpected keyword argument 'multiprocessing_context'

### ISSUE THREAD

**Issue by Mikhael-Danilov** [d8ahazard/sd_dreambooth_extension#1462]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Error in extension (commit: 30bfbc289a1d90153a3e5a5ab92bf5636e66b210 ) while attempt to train LoRa,

### Steps to reproduce the problem

Select SDXL as base model
Specify dateset directory
Click Train

### Commit and libraries

Initializing Dreambooth
Dreambooth revision: 30bfbc289a1d90153a3e5a5ab92bf5636e66b210
Checking xformers...
Xformers is outdated, and automatic installation has been removed. Please install manually if desired.
Checking bitsandbytes...
Checking bitsandbytes (Linux)
Checking Dreambooth requirements...
Installed version of accelerate: 0.21.0
[Dreambooth] accelerate v0.21.0 is already installed.
Installed version of dadaptation: 3.2
[Dreambooth] dadaptation v3.2 is already installed.
Installed version of diffusers: 0.25.0
[Dreambooth] diffusers v0.25.0 is already installed.
Installed version of discord-webhook: 1.3.0
[Dreambooth] discord-webhook v1.3.0 is already installed.
Installed version of fastapi: 0.94.0
[Dreambooth] fastapi is already installed.
Installed version of gitpython: 3.1.32
[Dreambooth] gitpython v3.1.40 is not installed.
Successfully installed gitpython-3.1.42
Installed version of pytorch_optimizer: 2.12.0
[Dreambooth] pytorch_optimizer v2.12.0 is already installed.
Installed version of Pillow: 9.5.0
[Dreambooth] Pillow is already installed.
Installed version of tqdm: 4.65.0
[Dreambooth] tqdm is already installed.
Installed version of tomesd: 0.1.3
[Dreambooth] tomesd v0.1.2 is already installed.
Installed version of tensorboard: 2.13.0
[Dreambooth] tensorboard v2.13.0 is already installed.
[+] torch version 2.0.1+cu118 installed.
[+] torchvision version 0.15.2+cu118 installed.
[+] accelerate version 0.21.0 installed.
[+] diffusers version 0.25.0 installed.
[+] bitsandbytes version 0.41.2.post2 installed.
[!] xformers version 0.0.20 installed.

### Command Line Arguments

```Shell
--no-half --xformers --api
```

### Console logs

```Shell
Initializing dreambooth training...
WARNING:dreambooth.train_dreambooth:Wandb API key not set. Please set WANDB_API_KEY environment variable to use wandb.
Wandb API key not set. Please set WANDB_API_KEY environment variable to use wandb.
                  Loading latent cache...
358 cached latents
INFO:dreambooth.utils.gen_utils:Nothing to generate.6%|███████████████████████████████████           | 273/358 [00:00<00:00, 1457.08it/s]Nothing to generate.
Init dataset!set:   0%|                                                                                            | 0/1 [00:00<?, ?it/s]Preparing Dataset (With Caching)
Bucket  0 (720, 1448, 0) - Instance Images:  28 | Class Images: 0 | Max Examples/batch:  28
Bucket  1 (768, 1360, 0) - Instance Images:  33 | Class Images: 0 | Max Examples/batch:  33                                             
Bucket  2 (832, 1248, 0) - Instance Images:  42 | Class Images: 0 | Max Examples/batch:  42                                             
Bucket  3 (880, 1176, 0) - Instance Images:  51 | Class Images: 0 | Max Examples/batch:  51                                             
Bucket  4 (912, 1144, 0) - Instance Images:  45 | Class Images: 0 | Max Examples/batch:  45                                             
Bucket  5 (1024, 1024, 0) - Instance Images:  58 | Class Images: 0 | Max Examples/batch:  58                                            
Bucket  6 (1144, 912, 0) - Instance Images:  35 | Class Images: 0 | Max Examples/batch:  35                                             
Bucket  7 (1176, 880, 0) - Instance Images:  37 | Class Images: 0 | Max Examples/batch:  37                                             
Bucket  8 (1248, 832, 0) - Instance Images:  15 | Class Images: 0 | Max Examples/batch:  15                                             
Bucket  9 (1360, 768, 0) - Instance Images:   7 | Class Images: 0 | Max Examples/batch:   7                                             
Bucket 10 (1448, 720, 0) - Instance Images:   7 | Class Images: 0 | Max Examples/batch:   7                                             
Total Buckets 11 - Instance Images: 358 | Class Images: 0 | Max Examples/batch: 358                                                     
                                                                                                                                        
Total images / batch: 358, total examples: 358█████████████████████████████████████████████████████| 358/358 [00:00<00:00, 51856.64it/s]
                  Initializing bucket counter!
Traceback (most recent call last):                                                                                                      
  File "/home/mike/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 735, in start_training
    result = main(class_gen_method=class_gen_method)
  File "/home/mike/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 2003, in main
    return inner_loop()
  File "/home/mike/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 126, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "/home/mike/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 942, in inner_loop
    ) = accelerator.prepare(
  File "/home/mike/.local/lib/python3.10/site-packages/accelerate/accelerator.py", line 1202, in prepare
    result = tuple(
  File "/home/mike/.local/lib/python3.10/site-packages/accelerate/accelerator.py", line 1203, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "/home/mike/.local/lib/python3.10/site-packages/accelerate/accelerator.py", line 1028, in _prepare_one
    return self.prepare_data_loader(obj, device_placement=device_placement)
  File "/home/mike/.local/lib/python3.10/site-packages/accelerate/accelerator.py", line 1737, in prepare_data_loader
    prepared_data_loader = prepare_data_loader(
  File "/home/mike/.local/lib/python3.10/site-packages/accelerate/data_loader.py", line 802, in prepare_data_loader
    dataloader = DataLoaderShard(
  File "/home/mike/.local/lib/python3.10/site-packages/accelerate/data_loader.py", line 370, in __init__
    super().__init__(dataset, **kwargs)
TypeError: intercept_args() got an unexpected keyword argument 'multiprocessing_context'
```

**Comment by Mikhael-Danilov** [comment]
False alarm: it turns out to be conflict with https://github.com/SpenserCai/sd-webui-deoldify
