### ISSUE TITLE
[Bug]: User specified an unsupported autocast device_type 'mps'

### ISSUE THREAD

**Issue by Itz-terreur-mt** [d8ahazard/sd_dreambooth_extension#1488]
### Is there an existing issue for this?

- [x] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

The environment is macOS M1 Pro chip with Safari

After creating a model with dreambooth, when I want to train my model I have this error message : "User specified an unsupported autocast device_type 'mps''

### Steps to reproduce the problem

1. Go to stable diffusion webui
2. Activate the dream booth extension
3. Create a model and click train

### Commit and libraries

Initializing Dreambooth
Dreambooth revision: 1b3257b46bb03c6de3bcdfa079773dc040884fbd
Checking xformers...
Checking Dreambooth requirements...
[Dreambooth] bitsandbytes v0.43.0 is not installed.

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
Initializing dreambooth training...
WARNING:dreambooth.train_dreambooth:Wandb API key not set. Please set WANDB_API_KEY environment variable to use wandb.
                  0 cached latents
0it [00:00, ?it/s]                                             We need a total of 3100 class images.s: person_ddim: : 1562it [00:17, 89.34it/s]                 
Loading pipeline components...:  17%|██▏          | 1/6 [00:02<00:10,  2.12s/it]An error occurred while trying to fetch /Users/Tom/stable-diffusion-webui/models/dreambooth/absolute-tom/working/unet: Error no file named diffusion_pytorch_model.safetensors found in directory /Users/Tom/stable-diffusion-webui/models/dreambooth/absolute-tom/working/unet.
Loading pipeline components...:  67%|████████▋    | 4/6 [00:09<00:03,  1.78s/it]/Users/Tom/stable-diffusion-webui/venv/lib/python3.10/site-packages/transformers/models/clip/feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
An error occurred while trying to fetch /Users/Tom/stable-diffusion-webui/models/dreambooth/absolute-tom/working/vae: Error no file named diffusion_pytorch_model.safetensors found in directory /Users/Tom/stable-diffusion-webui/models/dreambooth/absolute-tom/working/vae.
Loading pipeline components...: 100%|█████████████| 6/6 [00:11<00:00,  1.84s/it]
Using scheduler: DEISMultistep::   0%|                 | 0/3100 [00:10<?, ?it/s]
Traceback (most recent call last):
  File "/Users/Tom/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 735, in start_training
    result = main(class_gen_method=class_gen_method)
  File "/Users/Tom/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 2003, in main
    return inner_loop()
  File "/Users/Tom/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 126, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "/Users/Tom/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 380, in inner_loop
    count, instance_prompts, class_prompts = generate_classifiers(
  File "/Users/Tom/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/utils/gen_utils.py", line 211, in generate_classifiers
    new_images = builder.generate_images(prompts, pbar)
  File "/Users/Tom/stable-diffusion-webui/extensions/sd_dreambooth_extension/helpers/image_builder.py", line 235, in generate_images
    with self.accelerator.autocast(), torch.inference_mode():
  File "/opt/homebrew/Cellar/python@3.10/3.10.15/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/Users/Tom/stable-diffusion-webui/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 2907, in autocast
    autocast_context = get_mixed_precision_context_manager(self.native_amp, cache_enabled=cache_enabled)
  File "/Users/Tom/stable-diffusion-webui/venv/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 1372, in get_mixed_precision_context_manager
    return torch.autocast(device_type=state.device.type, dtype=torch.float16, cache_enabled=cache_enabled)
  File "/Users/Tom/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 241, in __init__
    raise RuntimeError(
RuntimeError: User specified an unsupported autocast device_type 'mps'
Generating class images 0/3100::   0%|                 | 0/3100 [00:13<?, ?it/s]
Duration: 00:00:34
Duration: 00:00:36
```

### Additional information

I have already tried to completely uninstall and reinstall, it didn't work.
I have already tried to put transformers to version 4.38.1 instead of 4.38.2, it didn't work.

Sorry if the issue was solved elsewhere, I couldn't find it!
If you could help me! Thank you very much

**Comment by linjinze999** [comment]
same
