### ISSUE TITLE
AttributeError: 'Options' object has no attribute 'tag_drop_out'

### ISSUE THREAD

**Issue by jmattthew** [d8ahazard/sd_dreambooth_extension#170]
**Have you read the Readme?**
yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yes

**Have you updated Dreambooth to the latest revision?**
yes

**Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth**
Dreambooth revision is 5d8a331a142abe15516bec8f9a069241ed28c239
Diffusers version is 0.8.0.dev0.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.

**Describe the bug**
After clicking "train" in the webui, the initializing message appears, then "training complete" briefly flashes

**Provide logs**
2022-11-13T19:53:29.465836737Z     for step, batch in enumerate(train_dataloader):
2022-11-13T19:53:29.465839416Z   File "/venv/lib/python3.10/site-packages/accelerate/data_loader.py", line 348, in __iter__
2022-11-13T19:53:29.465842082Z     current_batch = next(dataloader_iter)
2022-11-13T19:53:29.465844640Z   File "/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
2022-11-13T19:53:29.465847482Z     data = self._next_data()
2022-11-13T19:53:29.465850158Z   File "/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 721, in _next_data
2022-11-13T19:53:29.465852854Z     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
2022-11-13T19:53:29.465855390Z   File "/venv/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
2022-11-13T19:53:29.465858281Z     data = [self.dataset[idx] for idx in possibly_batched_index]
2022-11-13T19:53:29.465860771Z   File "/venv/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
2022-11-13T19:53:29.465863657Z     data = [self.dataset[idx] for idx in possibly_batched_index]
2022-11-13T19:53:29.465866382Z   File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 455, in __getitem__
2022-11-13T19:53:29.465869098Z     example["instance_prompt"] = self.text_getter.create_text(instance_prompt, instance_text)   #TODO: show the final prompt of the image currently being trained in the ui
2022-11-13T19:53:29.465872252Z   File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 380, in create_text
2022-11-13T19:53:29.465874952Z     if shared.opts.tag_drop_out != 0:
2022-11-13T19:53:29.465877584Z   File "/workspace/stable-diffusion-webui/modules/shared.py", line 433, in __getattr__
2022-11-13T19:53:29.465880170Z     return super(Options, self).__getattribute__(item)
2022-11-13T19:53:29.465887044Z AttributeError: 'Options' object has no attribute 'tag_drop_out'
2022-11-13T19:53:29.475342434Z Traceback (most recent call last):
2022-11-13T19:53:29.475355648Z   File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 935, in main
2022-11-13T19:53:29.475358627Z     for step, batch in enumerate(train_dataloader):
2022-11-13T19:53:29.475360841Z   File "/venv/lib/python3.10/site-packages/accelerate/data_loader.py", line 348, in __iter__
2022-11-13T19:53:29.475363333Z     current_batch = next(dataloader_iter)
2022-11-13T19:53:29.475365830Z   File "/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
2022-11-13T19:53:29.475368390Z     data = self._next_data()
2022-11-13T19:53:29.475370664Z   File "/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 721, in _next_data
2022-11-13T19:53:29.475373153Z     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
2022-11-13T19:53:29.475375386Z   File "/venv/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
2022-11-13T19:53:29.475378022Z     data = [self.dataset[idx] for idx in possibly_batched_index]
2022-11-13T19:53:29.475380349Z   File "/venv/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
2022-11-13T19:53:29.475382962Z     data = [self.dataset[idx] for idx in possibly_batched_index]
2022-11-13T19:53:29.475385554Z   File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 455, in __getitem__
2022-11-13T19:53:29.475388193Z     example["instance_prompt"] = self.text_getter.create_text(instance_prompt, instance_text)   #TODO: show the final prompt of the image currently being trained in the ui
2022-11-13T19:53:29.475390938Z   File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 380, in create_text
2022-11-13T19:53:29.475393511Z     if shared.opts.tag_drop_out != 0:
2022-11-13T19:53:29.475395852Z   File "/workspace/stable-diffusion-webui/modules/shared.py", line 433, in __getattr__
2022-11-13T19:53:29.475398432Z     return super(Options, self).__getattribute__(item)
2022-11-13T19:53:29.475401934Z AttributeError: 'Options' object has no attribute 'tag_drop_out'
2022-11-13T19:53:29.585665416Z 
Steps:   0%|          | 0/500 [00:00<?, ?it/s]

**Environment**
What OS?
Debian GNU/Linux 10

What GPU are you using?
RTX 3090
16 vCPU 61 GB RAM

**Comment by strykerx** [comment]
I'm experiencing the same thing.

**Comment by sgsdxzy** [comment]
#168

**Comment by jmattthew** [comment]
I'm still getting the same error message.  I tried this:
- reinstalled the sd_dreambooth_extension.  got revision 60ef742dcdd791876a683ddd415576ec273d5c8e
- updated SD-WebUI via git pull, and got the message:  Updating ac08562..98947d1
- added to webui-user.sh:  export TORCH_COMMAND="pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116"
- restarted the webUI
