### ISSUE TITLE
AttributeError: 'UNet2DConditionModel' object has no attribute 'enable_gradient_checkpointing'

### ISSUE THREAD

**Issue by GForceWeb** [d8ahazard/sd_dreambooth_extension#18]
Just trying to Train my first model but can't seem to get it to run the training.

Here's the full log:

```
Starting Dreambooth training...
 VRAM cleared.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Loaded model.
 Allocated: 0.0GB
 Reserved: 0.0GB

Error completing request
Arguments: ('141234', 'I:\\Git\\AI\\Training\\1234\\data\\prepped\\', '', '1234', '*', '', '', 1.0, 7.5, 40.0, 0, 512, False, True, 1, 1, 1, 1000, 1, True, 5e-06, False, 'constant', 0, False, 0.9, 0.999, 0.01, 1e-08, 1, 200, 1000, 'no', True, '', False) {}
Traceback (most recent call last):
  File "I:\Git\AI\SDWebUI\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "I:\Git\AI\SDWebUI\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "I:\Git\AI\SDWebUI\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 256, in start_training
    trained_steps = main(config)
  File "I:\Git\AI\SDWebUI\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 539, in main
    unet.enable_gradient_checkpointing()
  File "I:\Git\AI\SDWebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'UNet2DConditionModel' object has no attribute 'enable_gradient_checkpointing'
```

Given I'm mostly using the default values I'm wondering if I'm just not formatting the file path correctly?

Running on Win11 with an RTX3080

**Comment by aniOfri** [comment]
i have the same issue

**Comment by GForceWeb** [comment]
Nevermind, fully restarting the Automatic1111 webui resovled this. It appears there were additional dependencies required that weren't loaded with the webui reload prompted after installing the extension.
