### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/notebooks/stable-diffusion-webui/models/dreambooth/disco640px/working/diffusion_pytorch_model.bin'

### ISSUE THREAD

**Issue by daniel5984** [d8ahazard/sd_dreambooth_extension#186]
Steps:  75%|████████▎  | 1500/2000 [19:58<06:05,  1.37it/s, loss=0.362, lr=5e-6]Successfully trained model for a total of True steps, converting to ckpt.
Exception saving checkpoint/model: [Errno 2] No such file or directory: '/notebooks/stable-diffusion-webui/models/dreambooth/disco640px/working/diffusion_pytorch_model.bin'
Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 937, in save_weights
    save_checkpoint(args.model_name, lifetime_step,
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 74, in save_checkpoint
    conversion.diff_to_sd(src_path, vae_path, out_file, use_half)
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/conversion.py", line 945, in diff_to_sd
    vae_state_dict = torch.load(vae_path, map_location="cpu")
  File "/notebooks/stable-diffusion-webui/modules/safe.py", line 102, in load
    return load_with_extra(filename, *args, **kwargs)
  File "/notebooks/stable-diffusion-webui/modules/safe.py", line 147, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/notebooks/stable-diffusion-webui/models/dreambooth/disco640px/working/diffusion_pytorch_model.bin'
[*] Weights saved at /notebooks/stable-diffusion-webui/models/dreambooth/disco640px
Steps:  78%|████████▌  | 1550/2000 [20:53<05:58,  1.26it/s, loss=0.362, lr=5e-6]
​

i get this error everytime it saves as checkpoint

**Comment by d8ahazard** [comment]
Fixed, had an issue with the path being passed to save checkpoint.
