### ISSUE TITLE
Torch installation error when starting server

### ISSUE THREAD

**Issue by Jonseed** [d8ahazard/sd_dreambooth_extension#187]
**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yes

**Have you updated Dreambooth to the latest revision?**
yes, I'm on commit 7e184a6cb95df776c2a1d86eea29321bff999899

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
yes, commit 98947d173e3f1667eba29c904f681047dea9de90

**Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth**
It doesn't show any of those lines.

**Describe the bug**
Error when booting up the server, after "installing requirements for WebUI":

```
Installing Installing Jinja2==3.1.2
Installing Installing requests==2.28.1

Error running install.py for extension extensions\sd_dreambooth_extension.
Command: "F:\repos\auto111\stable-diffusion-webui\venv\Scripts\python.exe" "extensions\sd_dreambooth_extension\install.py"
Error code: 1
stdout: loading Dreambooth reqs from F:\repos\auto111\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt
Checking Dreambooth requirements.
Checking torch and torchvision versions

stderr: Traceback (most recent call last):
  File "F:\repos\auto111\stable-diffusion-webui\extensions\sd_dreambooth_extension\install.py", line 25, in <module>
    run(f'"{sys.executable}" -m {torch_cmd}', "Checking torch and torchvision versions", "Couldn't install torch")
  File "F:\repos\auto111\stable-diffusion-webui\launch.py", line 34, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install torch.
Command: "F:\repos\auto111\stable-diffusion-webui\venv\Scripts\python.exe" -m "pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116"
Error code: 1
stdout: <empty>
stderr: F:\repos\auto111\stable-diffusion-webui\venv\Scripts\python.exe: Error while finding module specification for 'pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116' (ModuleNotFoundError: No module named 'pip install torch==1')
```

**Provide logs**
No crash, just errors during server bootup and installation.

**Environment**
What OS? Windows
If Windows - WSL or native? native
What GPU are you using? 3060 12GB

Why can't it install torch? It's installed before just fine.

**Comment by Jonseed** [comment]
If I skip the dreambooth installation using the skip install option, then I see this when booting up the server:

```
Installing Installing Jinja2==3.1.2
Installing Installing requests==2.28.1

Skipping dreambooth installation.
Dreambooth revision is 7e184a6cb95df776c2a1d86eea29321bff999899
Diffusers version is 0.7.2.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.
Copying 8Bit Adam files for Windows.
```

It looks like torch is already installed fine. So why does it show errors when set to check dreambooth installation?
