### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by LaikaSa** [d8ahazard/sd_dreambooth_extension#19]
I followed the example in Readme to try out multiple-concept option and got this error. All I did was directly copy-pasted the example with small changes in directory:
```
Starting Dreambooth training...
 VRAM cleared.
 Allocated: 0.0GB
 Reserved: 0.0GB

Trying to parse: [
    {
        "instance_prompt":      "photo of zwx dog",
        "class_prompt":         "photo of a dog",
        "instance_data_dir":    "E:/data/alvan",
        "class_data_dir":       "E:/data/dog"
    }
]
Error completing request
Arguments: ('DogSD1000', '', '', '*', '*', '', '', 1.0, 7.5, 40.0, 1500, 512, False, False, 1, 1, 1, 3000, 1, True, 5e-05, False, 'constant', 0, True, 0.9, 0.999, 0.01, 1e-08, 1, 500, 7000, 'fp16', False, '[\n    {\n        "instance_prompt":      "photo of zwx dog",\n        "class_prompt":         "photo of a dog",\n        "instance_data_dir":    "E:/data/alvan",\n        "class_data_dir":       "E:/data/dog"\n    }\n]', False) {}
Traceback (most recent call last):
  File "E:\Stable\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "E:\Stable\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "E:\Stable\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 256, in start_training
    trained_steps = main(config)
  File "E:\Stable\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 478, in main
    class_images_dir = Path(concept["class_data_dir"])
TypeError: string indices must be integers
```

**Comment by Jonseed** [comment]
I'm also seeing this error.

**Comment by d8ahazard** [comment]
I believe this is resolved. Feel free to open a new issue with the fancy new template if not.

**Comment by LaikaSa** [comment]
Thanks, just updated and it working now👍
