### ISSUE TITLE
New version says to "use_auth_token" when starting Training, after using Create Model

### ISSUE THREAD

**Issue by jrjustiss** [d8ahazard/sd_dreambooth_extension#201]
**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes
**Have you updated Dreambooth to the latest revision?**
Yes
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes
**Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth**

`Dreambooth revision is 60ef742dcdd791876a683ddd415576ec273d5c8e
Diffusers version is 0.7.2
Torch version is 1.12.1+cu116
Torch vision version is 0.13.1+cu+1116

**Describe the bug**
Training used to worked on yesterday's release, but not on today's. After successfully using Create Model, when I attempt to train I get the following error:

**Provide logs**
If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

Error completing request
Arguments: ('aromaF', '', 'D:\\Grabber Storage\\aroma_sensei\\futa\\solo\\birme-512x512', '', 'fanart of aromaF person', 'fanart of person', '', '', 1, 7.5, 40, 0, 512, False, True, 1, 1, 1, 3000, 1, True, 1e-06, False, 'constant', 0, True, 0.9, 0.999, 0.01, 1e-08, 1, 1000, 1000, 'fp16', True, '', False, True, '75', True, False) {}
Traceback (most recent call last):
  File "C:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1744, in from_pretrained
    resolved_vocab_files[file_id] = cached_path(
  File "C:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\transformers\utils\hub.py", line 284, in cached_path
    output_path = get_from_cache(
  File "C:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\transformers\utils\hub.py", line 502, in get_from_cache
    _raise_for_status(r)
  File "C:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\transformers\utils\hub.py", line 417, in _raise_for_status
    raise RepositoryNotFoundError(
transformers.utils.hub.RepositoryNotFoundError: 401 Client Error: Repository not found for url: https://huggingface.co/C:%5CStableDiffusion%5Cstable-diffusion-webui%5Cmodels%5Cdreambooth%5CaromaF%5Cworking%5Ctokenizer/resolve/main/vocab.json. If the repo is private, make sure you are authenticated.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\StableDiffusion\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "C:\StableDiffusion\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "C:\StableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 331, in start_training
    trained_steps = main(config)
  File "C:\StableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 645, in main
    tokenizer = CLIPTokenizer.from_pretrained(os.path.join(args.working_dir, "tokenizer"))
  File "C:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1762, in from_pretrained
    raise EnvironmentError(
OSError: C:\StableDiffusion\stable-diffusion-webui\models\dreambooth\aromaF\working\tokenizer is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True`.

**Environment**
What OS? Windows
If Windows - WSL or native? native
What GPU are you using? 3080 Ti

**Comment by d8ahazard** [comment]
Please update to the latest revision and try again.

**Comment by Prof-Cheese** [comment]
I tried with the latest version and got the exact same error, it seems that this error occurs when I specify the path to the VAE file and set the "Save Preview(s) Frequency" to a non-zero value.

Can you please confirm this phenomenon again?

**Comment by jrjustiss** [comment]
I no longer receive the auth token error, but now I get a CUDA out of memory on the same settings that previously worked.

**Comment by jrjustiss** [comment]
Added --xformers back into my webui-user.bat (previously this threw errors) and got it working.
