### ISSUE TITLE
RuntimeError: expected scalar type Half but found Float

### ISSUE THREAD

**Issue by rrweller** [d8ahazard/sd_dreambooth_extension#21]
I am receiving this error whenever I try running training, not sure what is going on. Running on a 3060 12GB

Starting Dreambooth training...
 VRAM cleared.
 Allocated: 0.9GB
 Reserved: 0.9GB

 Loaded model.
 Allocated: 0.9GB
 Reserved: 0.9GB

 Scheduler Loaded
 Allocated: 1.3GB
 Reserved: 1.3GB
Total target lifetime optimization steps = 2000
 CPU: False Adam: False, Prec: fp16, Prior: False, Grad: True, TextTr: False
 Allocated: 4.5GB
 Reserved: 4.6GB

Steps:   0%|                                                                                  | 0/2000 [00:00<?, ?it/s]Error completing request
Arguments: ('Auto1111Test', 'C:\\Users\\Riley\\Downloads\\TestModel', '', 'photo of test person', '*', '', '', 1.0, 7.5, 40.0, 0, 512, False, False, 1, 1, 1, 2000, 1, True, 5e-06, False, 'constant', 0, False, 0.9, 0.999, 0.01, 1e-08, 1, 500, 500, 'fp16', True, '', False) {}
Traceback (most recent call last):
  File "C:\Users\Riley\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\Riley\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "C:\Users\Riley\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 256, in start_training
    trained_steps = main(config)
  File "C:\Users\Riley\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 744, in main
    encoder_hidden_states = text_encoder(batch["input_ids"])[0]
  File "C:\Users\Riley\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Riley\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 722, in forward
    return self.text_model(
  File "C:\Users\Riley\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Riley\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 643, in forward
    encoder_outputs = self.encoder(
  File "C:\Users\Riley\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Riley\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 574, in forward
    layer_outputs = encoder_layer(
  File "C:\Users\Riley\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Riley\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 317, in forward
    hidden_states, attn_weights = self.self_attn(
  File "C:\Users\Riley\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Riley\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 257, in forward
    attn_output = torch.bmm(attn_probs, value_states)
RuntimeError: expected scalar type Half but found Float

Steps:   0%|                                                                                  | 0/2000 [00:03<?, ?it/s]

**Comment by anekii** [comment]
Getting the same errors on a 3080

**Comment by Blucknote** [comment]
Looks like this error appears when mixed precision set to fp16 or bf16. Setting to "no" allowed me to step forward but then OOM appears.

**Comment by zark119** [comment]
same problem on 3060 12gb

**Comment by rrweller** [comment]
This error still appears even after the fix

**Comment by kryztoval** [comment]
Can confirm, this is not fixed. I am getting the same error when setting it to no it says "RuntimeError: expected scalar type Half but found Float"

If I set it to fp16 I get an error saying "ValueError: Attempting to unscale FP16 gradients."

**Comment by rrweller** [comment]
@d8ahazard so you see this

**Comment by rrweller** [comment]
Update, I was able to get it working using the 182c76f branch and this guide (I'm on a 3060 12GB) https://echo.notable.app/1c17eae7f116e87ab81b2bb6dd1e1d7f9b505cc6e650c5d0742ca628ee2745c6
