### ISSUE TITLE
Unable to start training due to OSError: Missing CLIPTokenizer files.

### ISSUE THREAD

**Issue by Fairy-** [d8ahazard/sd_dreambooth_extension#217]
``` 
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)
Commit hash: 98947d173e3f1667eba29c904f681047dea9de90
Installing requirements for Web UI
loading Dreambooth reqs from C:\Users\XXX\Documents\repos\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt
Checking Dreambooth requirements.
Checking torch and torchvision versions
Dreambooth revision is 64c9929984f86ac04f45660957647605a49e72e4
Diffusers version is 0.7.2.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.
Copying 8Bit Adam files for Windows.
``` 

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?** Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?** Yes

**Have you updated Dreambooth to the latest revision?** Yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?** Yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
OK

**Describe the bug**

After entering all the training parameters and clicking "Train" I receive the Error below. The model was created with the current version.

**Provide logs**
```
Error completing request
Arguments: ('xxx', None, 'C:\\Users\\xxx\\Downloads\\trainmodels\\processed', 'C:\\Users\\xxx\\Documents\\repos\\stable-diffusion-webui\\regularization_images\\person', 'photo of xxx person', 'photo of a person', None, None, None, None, None, None, 1500, 512, None, True, 1, 1, None, 1200, 1, True, 1e-06, None, 'constant', 0, True, 0.9, 0.999, 0.01, 1e-08, 1, 5000, 5000, 'fp16', True, None, None, None, 75, None, None) {}
Traceback (most recent call last):
  File "C:\Users\xxx\Documents\repos\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\xxx\Documents\repos\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "C:\Users\xxx\Documents\repos\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 375, in start_training
    config, mem_record = main(config, mem_record)
  File "C:\Users\xxx\Documents\repos\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 564, in main
    tokenizer = CLIPTokenizer.from_pretrained(
  File "C:\Users\xxx\Documents\repos\stable-diffusion-webui\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1789, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'C:\Users\xxx\Documents\repos\stable-diffusion-webui\models\dreambooth\xxx\working'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'C:\Users\xxx\Documents\repos\stable-diffusion-webui\models\dreambooth\xxx\working' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.
```
**Environment**

What OS?
Windows - Native

What GPU are you using?
Nvidia 2080TI

**Comment by d8ahazard** [comment]
What source checkpoint are you using, and what is in the folder C:\Users\xxx\Documents\repos\stable-diffusion-webui\models\dreambooth\xxx\working\tokenizer ?
