### ISSUE TITLE
'Options' object has no attribute 'tag_drop_out'

### ISSUE THREAD

**Issue by siroco007** [d8ahazard/sd_dreambooth_extension#227]
Memory output: {'VRAM cleared.': '0.0/0.0GB', 'Loaded model.': '0.0/0.0GB', 'Scheduler Loaded': '0.3/0.4GB', "Exception while training: 'Options' object has no attribute 'tag_drop_out'": '4.0/4.1GB', 'CLEANUP: ': '4.0/4.1GB', 'Cleanup Complete.': '4.0/4.1GB', 'Training completed, reloading SD Model.': '0.0/0.0GB'}
Re-applying optimizations...
Returning result: Training finished. Total lifetime steps: 0

**Please find the following lines in the console and paste them below. _If you do not provide this information, your issue will be automatically closed._**

`
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 00:03:30) [MSC v.1933 64 bit (AMD64)]                                 
Commit hash: ac085628540d0ec6a988fad93f5b8f2154209571 
Installing requirements for Web UI
Skipping dreambooth installation.
Dreambooth revision is 4152085e974bd64f402cf13393e694acf2ccef78
Diffusers version is 0.7.2
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?** YES

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?** YES

**Have you updated Dreambooth to the latest revision?** YES

**Have you updated the Stable-Diffusion-WebUI to the latest version?** YES

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this. YES

**Describe the bug**

(A clear and concise description of what the bug is)  object has no attribute 'tag_drop_out

**Provide logs**

Traceback (most recent call last):
  File "F:\ai\stable-diffusion-webui.part1\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 919, in main
    for step, batch in enumerate(train_dataloader):
  File "F:\ai\stable-diffusion-webui.part1\stable-diffusion-webui\venv\lib\site-packages\accelerate\data_loader.py", line 376, in __iter__
    current_batch = next(dataloader_iter)
  File "F:\ai\stable-diffusion-webui.part1\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\dataloader.py", line 681, in __next__
    data = self._next_data()
  File "F:\ai\stable-diffusion-webui.part1\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "F:\ai\stable-diffusion-webui.part1\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "F:\ai\stable-diffusion-webui.part1\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "F:\ai\stable-diffusion-webui.part1\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 381, in __getitem__
    example["instance_prompt"] = self.text_getter.create_text(instance_prompt,
  File "F:\ai\stable-diffusion-webui.part1\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\finetune_utils.py", line 41, in create_text
    if shared.opts.tag_drop_out != 0:
  File "F:\ai\stable-diffusion-webui.part1\stable-diffusion-webui\modules\shared.py", line 433, in __getattr__
    return super(Options, self).__getattribute__(item)
AttributeError: 'Options' object has no attribute 'tag_drop_out'
 CLEANUP:
 Allocated: 4.0GB
 Reserved: 4.1GB

 Cleanup Complete.
 Allocated: 4.0GB
 Reserved: 4.1GB

Steps:   0%|                                                                                  | 0/5000 [00:02<?, ?it/s]
 Training completed, reloading SD Model.
 Allocated: 0.0GB
 Reserved: 0.0GB

Memory output: {'VRAM cleared.': '0.0/0.0GB', 'Loaded model.': '0.0/0.0GB', 'Scheduler Loaded': '0.3/0.4GB', "Exception while training: 'Options' object has no attribute 'tag_drop_out'": '4.0/4.1GB', 'CLEANUP: ': '4.0/4.1GB', 'Cleanup Complete.': '4.0/4.1GB', 'Training completed, reloading SD Model.': '0.0/0.0GB'}
Re-applying optimizations...
Returning result: Training finished. Total lifetime steps: 0

**Environment**

What OS? Windows 10

If Windows - WSL or native? native

What GPU are you using? tesla T4

**Screenshots/Config**
{
    "max_token_length": "75",
    "model_dir": "F:\\ai\\stable-diffusion-webui.part1\\stable-diffusion-webui\\models\\dreambooth\\gg",
    "pretrained_model_name_or_path": "F:\\ai\\stable-diffusion-webui.part1\\stable-diffusion-webui\\models\\dreambooth\\gg\\working",
    "class_guidance_scale": 7.5,
    "class_negative_prompt": "",
    "class_infer_steps": 40,
    "model_name": "gg",
    "scheduler": "ddim",
    "src": "4g.ckpt [925997e9]",
    "total_steps": 0,
    "revision": 0,
    "pretrained_vae_name_or_path": null,
    "instance_data_dir": "F:\\gg",
    "class_data_dir": "F:\\ai\\stable-diffusion-webui.part1\\stable-diffusion-webui\\models\\dreambooth\\gg\\classifiers",
    "instance_prompt": "photo of gg",
    "class_prompt": "photo of girl",
    "save_sample_prompt": "",
    "save_sample_negative_prompt": "",
    "n_save_sample": 1,
    "seed": 0,
    "save_guidance_scale": 7.5,
    "save_infer_steps": 40,
    "with_prior_preservation": false,
    "num_class_images": 0,
    "output_dir": "F:\\ai\\stable-diffusion-webui.part1\\stable-diffusion-webui\\models\\dreambooth\\gg",
    "resolution": 512,
    "center_crop": false,
    "train_text_encoder": true,
    "train_batch_size": 1,
    "sample_batch_size": 1,
    "num_train_epochs": 1,
    "max_train_steps": 5000,
    "gradient_accumulation_steps": 1,
    "gradient_checkpointing": true,
    "learning_rate": 5e-06,
    "scale_lr": false,
    "lr_scheduler": "constant",
    "lr_warmup_steps": 0,
    "use_8bit_adam": true,
    "adam_beta1": 0.9,
    "adam_beta2": 0.999,
    "adam_weight_decay": 0.01,
    "adam_epsilon": 1e-08,
    "max_grad_norm": 1,
    "save_preview_every": 500,
    "save_embedding_every": 500,
    "mixed_precision": "no",
    "not_cache_latents": true,
    "concepts_list": null,
    "use_cpu": false,
    "pad_tokens": true,
    "hflip": true,
    "use_ema": false,
    "prior_loss_weight": 1
}

**Comment by sgsdxzy** [comment]
Update your webui to latest.
See #168 #170

**Comment by siroco007** [comment]
> Update your webui to latest. See #168 #170

thank u very much!
