### ISSUE TITLE
xformers is still broken on windows.

### ISSUE THREAD

**Issue by Lukium** [d8ahazard/sd_dreambooth_extension#228]
## Kindly read this ENTIRE form and fill it out with the requested information. It may seem tedious, but it's even more tedious asking basic questions to ensure I'm not trying to troubleshoot a bug I've already fixed. Help me help you, answer all the questions and follow the steps below before posting.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your issue will be automatically closed._**

`
Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Commit hash: 98947d173e3f1667eba29c904f681047dea9de90
Installing requirements for Web UI
Skipping dreambooth installation.
Dreambooth revision is 4152085e974bd64f402cf13393e694acf2ccef78
Diffusers version is 0.7.2
Torch version is 1.12.1+cu116
Torch vision version is 0.13.1+cu116
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes

**Have you updated Dreambooth to the latest revision?**
Yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
OK

**Describe the bug**

Everything works well until xformers is enabled.

**Provide logs**

```
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Total VRAM: 24
Starting Dreambooth training...
 VRAM cleared.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Loaded model.
 Allocated: 0.0GB
 Reserved: 0.0GB

Caching latents: 100%|███████████████████████████████████████████████████████████████████| 7/7 [00:09<00:00,  1.33s/it]
 Scheduler Loaded
 Allocated: 0.0GB
 Reserved: 0.0GB

***** Running training *****
  Num examples = 7
  Num batches each epoch = 7
  Num Epochs = 72
  Instantaneous batch size per device = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Gradient Accumulation steps = 1
  Total optimization steps = 500
Steps:   0%|                                                                                   | 0/500 [00:00<?, ?it/s] Exception while training: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
 Allocated: 8.2GB
 Reserved: 19.9GB

Traceback (most recent call last):
  File "D:\stable-diffusion\Instances\sd-dreambooth\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 975, in main
    accelerator.backward(loss)
  File "d:\miniconda3\envs\sd-dreambooth\lib\site-packages\accelerate\accelerator.py", line 1190, in backward
    loss.backward(**kwargs)
  File "d:\miniconda3\envs\sd-dreambooth\lib\site-packages\torch\_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "d:\miniconda3\envs\sd-dreambooth\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "d:\miniconda3\envs\sd-dreambooth\lib\site-packages\torch\autograd\function.py", line 253, in apply
    return user_fn(self, *args)
  File "d:\miniconda3\envs\sd-dreambooth\lib\site-packages\xformers\ops.py", line 369, in backward
    ) = torch.ops.xformers.efficient_attention_backward_cutlass(
  File "d:\miniconda3\envs\sd-dreambooth\lib\site-packages\torch\_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
 Exception while training: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
 Allocated: 8.2GB
 Reserved: 20.0GB

Traceback (most recent call last):
  File "D:\stable-diffusion\Instances\sd-dreambooth\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 975, in main
    accelerator.backward(loss)
  File "d:\miniconda3\envs\sd-dreambooth\lib\site-packages\accelerate\accelerator.py", line 1190, in backward
    loss.backward(**kwargs)
  File "d:\miniconda3\envs\sd-dreambooth\lib\site-packages\torch\_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "d:\miniconda3\envs\sd-dreambooth\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "d:\miniconda3\envs\sd-dreambooth\lib\site-packages\torch\autograd\function.py", line 253, in apply
    return user_fn(self, *args)
  File "d:\miniconda3\envs\sd-dreambooth\lib\site-packages\xformers\ops.py", line 369, in backward
    ) = torch.ops.xformers.efficient_attention_backward_cutlass(
  File "d:\miniconda3\envs\sd-dreambooth\lib\site-packages\torch\_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
 Exception while training: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
 Allocated: 8.2GB
 Reserved: 20.0GB
```

Error then just keeps repeating for number of steps given until this:

```
 CLEANUP:
 Allocated: 8.2GB
 Reserved: 20.0GB

 Cleanup Complete.
 Allocated: 8.2GB
 Reserved: 20.0GB

Steps:   0%|                                                                                   | 0/500 [00:32<?, ?it/s]
 Training completed, reloading SD Model.
 Allocated: 0.0GB
 Reserved: 0.0GB

Memory output: {'VRAM cleared.': '0.0/0.0GB', 'Loaded model.': '0.0/0.0GB', 'Scheduler Loaded': '0.0/0.0GB', 'Exception while training: CUDA error: invalid argument\nCUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.': '8.2/20.0GB', 'CLEANUP: ': '8.2/20.0GB', 'Cleanup Complete.': '8.2/20.0GB', 'Training completed, reloading SD Model.': '0.0/0.0GB'}
Re-applying optimizations...
Returning result: Training finished. Total lifetime steps: 1000
```

**Environment**

What OS?
Windows 11

If Windows - WSL or native?
native

What GPU are you using?
RTX3090

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the db_config.json file from /models/dreambooth/MODELNAME/db_config.json

db_config.json:
```
{
    "max_token_length": "75",
    "model_dir": "D:\\stable-diffusion\\Instances\\sd-dreambooth\\models\\dreambooth\\CustomSD15MK2",
    "pretrained_model_name_or_path": "D:\\stable-diffusion\\Instances\\sd-dreambooth\\models\\dreambooth\\CustomSD15MK2\\working",
    "class_guidance_scale": 7.5,
    "class_negative_prompt": "",
    "class_infer_steps": 40,
    "model_name": "CustomSD15MK2",
    "scheduler": "ddim",
    "src": "sd-v1-5.ckpt [81761151]",
    "total_steps": 0,
    "revision": 1000,
    "pretrained_vae_name_or_path": null,
    "instance_data_dir": ".\\dataset",
    "class_data_dir": "D:\\stable-diffusion\\Instances\\sd-dreambooth\\models\\dreambooth\\CustomSD15MK2\\classifiers",
    "instance_prompt": "test",
    "class_prompt": "",
    "save_sample_prompt": "",
    "save_sample_negative_prompt": "",
    "n_save_sample": 1,
    "seed": 0,
    "save_guidance_scale": 7.5,
    "save_infer_steps": 40,
    "with_prior_preservation": false,
    "num_class_images": 0,
    "output_dir": "D:\\stable-diffusion\\Instances\\sd-dreambooth\\models\\dreambooth\\CustomSD15MK2",
    "resolution": 512,
    "center_crop": true,
    "train_text_encoder": true,
    "train_batch_size": 1,
    "sample_batch_size": 1,
    "num_train_epochs": 1,
    "max_train_steps": 500,
    "gradient_accumulation_steps": 1,
    "gradient_checkpointing": false,
    "learning_rate": 5e-06,
    "scale_lr": false,
    "lr_scheduler": "constant",
    "lr_warmup_steps": 0,
    "use_8bit_adam": false,
    "adam_beta1": 0.9,
    "adam_beta2": 0.999,
    "adam_weight_decay": 0.01,
    "adam_epsilon": 1e-08,
    "max_grad_norm": 1,
    "save_preview_every": 500,
    "save_embedding_every": 500,
    "mixed_precision": "no",
    "not_cache_latents": false,
    "concepts_list": null,
    "use_cpu": false,
    "pad_tokens": true,
    "hflip": true,
    "use_ema": true,
    "prior_loss_weight": 1,
    "tokenizer_name": null
}
```

**Comment by Slowly-Grokking** [comment]
try manually installing this build, or fork the repo and running the action to build a fresh one(what I did).
 I grabbed it from one of the discussions here about build actions.

https://github.com/ninele7/xfromers_builds/releases/tag/3393900949

**Comment by Lukium** [comment]
> That's weird, i have xformers enabled and im using Dreambooth fine. And yes i'm up to date too. I don't understand why xformers is causing so many people problems.

would you kindly walk me through your installation steps?

Here are mine:

1. Create conda environment with `conda create -n sd-dreambooth puthon=3.10 -y`
2. Install automatic1111 webui
3. install d8ahazard dreambooth extension
4. Move the extensions webui-user to root folder and run it
If done without xformers on = great, with xformers on = fail

Thanks

**Comment by Lukium** [comment]
Hmmm... interesting. That shouldn't matter but I'll give that a go.

Thanks for the quick reply!

**Comment by YakuzaSuske** [comment]
> Hmmm... interesting. That shouldn't matter but I'll give that a go.
> 
> Thanks for the quick reply!

No prob, i don't even know if i helped but sure.

**Comment by Lukium** [comment]
> > Hmmm... interesting. That shouldn't matter but I'll give that a go.
> > Thanks for the quick reply!
> 
> No prob, i don't even know if i helped but sure.

It gives me something to try

**Comment by YakuzaSuske** [comment]
For 
`stderr: ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'D:\\stable-diffusion\\Instances\\stable-diffusion-webui\\venv\\Lib\\site-packages\\~orch\\lib\\asmjit.dll'
Check the permissions.`

Do you have it installed on your C: drive?  Most have it on C: but i'm not sure if it makes a difference/
as for the permissions have check the folders permissions?
![Screenshot 2022-11-16 121027](https://user-images.githubusercontent.com/63294141/202233223-e07cd973-5efd-4db3-b094-7728694128e7.png)
 for `Shut down WebUI, then reload it using the existing webui-user.bat, NOT the one downloaded with the extension in extension folder? `
 
i have never used that Bat file to start Dreambooth, to my knowledge that's for debugging the offline thing, so it allows you to use Dreambooth with no wifi due to a bug, but you dont start Dreambooth with the bat file in the extensions folder. I might be wrong tho, but in my training and use of Dreambooth, i have never used the bat file in the extensions folder, just the normal SD bat file in the main folder. i think you also have to add in the main bat file `TORCH_COMMAND=pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116` once after the `set COMMANDLINE_ARGS=` if it install something then let it install then you can delete that line afterwards. if it can find the `.dll` file i copied mine here, not sure if that will help tho.
https://drive.google.com/file/d/1gNV29CxLszHnREK6s5aH794l45H16lJm/view?usp=sharing

**Comment by YakuzaSuske** [comment]
> > So as for my steps:
> > 
> > 1. Git clone Automatic
> > 2. Edit bat file, add `set COMMANDLINE_ARGS= --deepdanbooru --autolaunch --xformers`
> > 3. open webui, install Dreambooth extension, wait till it installs.
> > 4. Close everything and open Automatic1111 again, might install additional stuff
> > 5. Training.
> >    Should be simple as that.
> >    ( have never edited any files in the extension folder for dreambooth, just basic default install)
> 
> I really appreciate the info... I'm thinking maybe there's something in my overall environment that's breaking things. I wonder if it's the installation of miniconda (which registers itself as the overall system's python interpreter).
> 
> Thanks again!

Sure, i just hope there's something more i can help with, but to my knowledge thats all ive done. Just make sure you have python 10.6 and Git and that's it.

**Comment by Slowly-Grokking** [comment]
> I wonder if it's the installation of miniconda (which registers itself as the overall system's python executable).

I would bet that is the issue.   I've had problems with miniconda conflicting.  I'm sure there's a way to get all your environment variables in order, but I just removed miniconda.

**Comment by sampanes** [comment]
> So as for my steps:
> 
> 1. Git clone Automatic
> 2. Edit bat file, add `set COMMANDLINE_ARGS= --deepdanbooru --autolaunch --xformers`
> 3. open webui, install Dreambooth extension, wait till it installs.
> 4. Close everything and open Automatic1111 again, might install additional stuff
> 5. Training.
>    Should be simple as that.
>    ( have never edited any files in the extension folder for dreambooth, just basic default install)

this was super helpful (especially the detail of having python 10.6, didnt work until i jumped up from whatever to python 3.10.8)
I got an error,
Could not install packages due to an OSError: [WinError 5] Access is denied: *some directory*
restarted, got a different error
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\*mypath*\venv\\Lib\\site-packages\\bitsandbytes\\libbitsandbytes_cpu.dll'
but the web ui still launched and the dreambooth tab is present. going to have to check if it actually works now, just thought that was interesting

**Comment by d8ahazard** [comment]
Gif an update and go now. I broke the bitsandbytes dll bit, should be fixed with the latest commit.

**Comment by sampanes** [comment]
> Gif an update and go now. I broke the bitsandbytes dll bit, should be fixed with the latest commit.

worked!

**Comment by Lukium** [comment]
> > Gif an update and go now. I broke the bitsandbytes dll bit, should be fixed with the latest commit.
> 
> worked! (in dreambooth dir, git fetch, behind by one, git pull, ran sd webuser bat again and no errors!)

you're not getting errors anymore when using xformers? I'm still getting them even after another clean install...

**Comment by Lukium** [comment]
> > you're not getting errors anymore when using xformers? I'm still getting them even after another clean install...
> 
> No errors on startup (havent run dreambooth yet). and your clean install was using what python version? that was my main problem

oh, I can get a clean launch, no issues... the problem I have is when trying to train a model with --xformers enabled. Then it blows up with the following error:

```Traceback (most recent call last):
  File "D:\stable-diffusion\Instances\sd-dreambooth\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 975, in main
    accelerator.backward(loss)
  File "d:\miniconda3\envs\sd-dreambooth\lib\site-packages\accelerate\accelerator.py", line 1190, in backward
    loss.backward(**kwargs)
  File "d:\miniconda3\envs\sd-dreambooth\lib\site-packages\torch\_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "d:\miniconda3\envs\sd-dreambooth\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "d:\miniconda3\envs\sd-dreambooth\lib\site-packages\torch\autograd\function.py", line 253, in apply
    return user_fn(self, *args)
  File "d:\miniconda3\envs\sd-dreambooth\lib\site-packages\xformers\ops.py", line 369, in backward
    ) = torch.ops.xformers.efficient_attention_backward_cutlass(
  File "d:\miniconda3\envs\sd-dreambooth\lib\site-packages\torch\_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
 Exception while training: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by Lukium** [comment]
> > I wonder if it's the installation of miniconda (which registers itself as the overall system's python executable).
> 
> I would bet that is the issue. I've had problems with miniconda conflicting. I'm sure there's a way to get all your environment variables in order, but I just removed miniconda.

Not the issue apparently. I just finished a full clean Windows install. Installed nothing except Python 3.10.6 and GIT for Windows. Still no go for training with xformers on.

**Comment by Slowly-Grokking** [comment]
and you're definitely using mixed precision: fp16 with xformers?
Damn, IDK. The only thing i can think of that's different about my setup is I don't use "--deepdanbooru --autolaunch."

I used this xformers:
 https://github.com/Slowly-Grokking/xfromers_builds/releases/download/3442487431/xformers-0.0.15.dev0+8367685.d20221111-cp310-cp310-win_amd64.whl

**Comment by Lukium** [comment]
I think the key was probably that I wasn't using fp16 >.< Fail on my part for not knowing.

**Comment by d8ahazard** [comment]
NBD. That's why I added a nag feature to the UI.
