### ISSUE TITLE
install.py error after update

### ISSUE THREAD

**Issue by mykeehu** [d8ahazard/sd_dreambooth_extension#236]
## Kindly read this ENTIRE form and fill it out with the requested information. It may seem tedious, but it's even more tedious asking basic questions to ensure I'm not trying to troubleshoot a bug I've already fixed. Help me help you, answer all the questions and follow the steps below before posting.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your issue will be automatically closed._**

`
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 98947d173e3f1667eba29c904f681047dea9de90
Installing requirements for Web UI
Installing requirements for scikit_learn
Dreambooth revision is 23af331535bbc1bd07f711ce36f6244ac830dd4a
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes

**Have you updated Dreambooth to the latest revision?**
Yes, this is a problem :) I have 23af331535bbc1bd07f711ce36f6244ac830dd4a version

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Of course

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
OK

**Describe the bug**
After updating dreambooth via Automatic webui, I get an xformers error on the next startup. I have not loaded xformers.

**Provide logs**
Error running install.py for extension extensions\sd_dreambooth_extension.
Command: "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\Scripts\python.exe" "extensions\sd_dreambooth_extension\install.py"
Error code: 1
stdout: Installing requirements for Dreambooth

stderr: Traceback (most recent call last):
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\install.py", line 16, in <module>
    subprocess.run([{sys.executable}, "-m", "pip", "install", "-r", {req_file}],
  File "C:\Users\Mykee\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Mykee\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 835, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "C:\Users\Mykee\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1302, in _get_handles
    c2pwrite = msvcrt.get_osfhandle(stdout.fileno())
AttributeError: 'str' object has no attribute 'fileno'

loading Dreambooth reqs from H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_smartprocess\requirements.txt
Checking Smart Crop requirements.

Launching Web UI with arguments: --ui-config-file 1my/ui-config-my.json --ui-settings-file 1my/config-my.json --deepdanbooru --autolaunch --gradio-img2img-tool color-sketch
Error loading script: api.py
Traceback (most recent call last):
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\modules\scripts.py", line 164, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\api.py", line 9, in <module>
    from extensions.sd_dreambooth_extension.dreambooth import conversion, dreambooth
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\conversion.py", line 30, in <module>
    from extensions.sd_dreambooth_extension.dreambooth import xattention
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\xattention.py", line 8, in <module>
    from diffusers.models.attention import xformers
ImportError: cannot import name 'xformers' from 'diffusers.models.attention' (H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\attention.py)

Error loading script: main.py
Traceback (most recent call last):
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\modules\scripts.py", line 164, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py", line 3, in <module>
    from extensions.sd_dreambooth_extension.dreambooth import conversion, dreambooth
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\conversion.py", line 30, in <module>
    from extensions.sd_dreambooth_extension.dreambooth import xattention
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\xattention.py", line 8, in <module>
    from diffusers.models.attention import xformers
ImportError: cannot import name 'xformers' from 'diffusers.models.attention' (H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\attention.py)

**Environment**

What OS?
Windows

If Windows - WSL or native? Natíve

What GPU are you using? RTX 3060 12 GB

**Screenshots/Config**

**Comment by mykeehu** [comment]
After I turned off, uninstalled and reinstalled dreambooth, I got the same message:

Error running install.py for extension H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension.
Command: "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\Scripts\python.exe" "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\install.py"
Error code: 1
stdout: Installing requirements for Dreambooth

stderr: Traceback (most recent call last):
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\install.py", line 16, in <module>
    subprocess.run([{sys.executable}, "-m", "pip", "install", "-r", {req_file}],
  File "C:\Users\Mykee\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Mykee\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 835, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "C:\Users\Mykee\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1302, in _get_handles
    c2pwrite = msvcrt.get_osfhandle(stdout.fileno())
AttributeError: 'str' object has no attribute 'fileno'

**Comment by seihoukei** [comment]
I have the same of fresh install of webui and dreambooth.

**Comment by mykeehu** [comment]
As a temporary solution I reverted to version 1ccdc41:
`git reset --hard 1ccdc41`

**Comment by Harvester62** [comment]
I did a Bisect to go back to yesterday's last commit. I am still a novice with Git. Let's give the developer the time to fix it.

**Comment by mykeehu** [comment]
You just go into the stable-diffusion-webui\extensions\sd_dreambooth_extension folder, then run the command you just I wrote, and it will revert to an earlier release, which was fine. The latest one is the one that introduced the error.

**Comment by muiyu** [comment]
> git reset --hard 1ccdc41

It works for me, thanks!

**Comment by d8ahazard** [comment]
Sorry, it was early, I wasn't paying enough attention. Reverted, as we *are* using subprocess.run, the run command is just a wrapper from launch.py
