### ISSUE TITLE
Error while trying to start training - Can't load config

### ISSUE THREAD

**Issue by eddjrn** [d8ahazard/sd_dreambooth_extension#241]
The error occurs when starting training, I did a pull and now the console throws an error. The training worked fine before.

`
Python 3.10.6 ARM
Commit hash: 98947d173e3f1667eba29c904f681047dea9de90
Installing requirements for Web UI
Skipping dreambooth installation.
Dreambooth revision is 725d85ca5485246a430d2f31f624646d061e8104
Diffusers version is 0.7.2
Torch version is 1.14.0.dev20221101
Torch vision version is 0.15.0.dev20221101
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?** 
Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?** 
Yes

**Have you updated Dreambooth to the latest revision?** 
Yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
 Yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.** 
OK

**Describe the bug**

Creating the model works but when start training the model I get the following error in console (the path exists but the file config.json doesn't):

**Provide logs**

```
Starting Dreambooth training...
 VRAM cleared.
 Allocated: 0.0GB
 Reserved: 0.0GB

Error completing request
Arguments: ('fitnessruben', '', '/Users/eduardoreyes/Desktop/backups/Training images/Fitness Ruben/Processed', '/Users/eduardoreyes/Desktop/backups/Training images/Stable-Diffusion-Regularization-Images-person_ddim/person_ddim', 'photo of fitnessruben person', 'photo of a person', '', '', 1, 0, 7.5, 40, 0, 512, False, True, 1, 1, 1, 1200, 1, True, 1e-06, False, 'constant', 0, False, 0.9, 0.999, 0.01, 1e-08, 1, 5000, 6000, 'no', False, '', False, True, '75', True, False, '', 7.5, 40) {}
Traceback (most recent call last):
  File "/Users/eduardoreyes/Documents/stable-diffusion-webui/env/lib/python3.10/site-packages/transformers/configuration_utils.py", line 601, in _get_config_dict
    resolved_config_file = cached_path(
  File "/Users/eduardoreyes/Documents/stable-diffusion-webui/env/lib/python3.10/site-packages/transformers/utils/hub.py", line 297, in cached_path
    raise EnvironmentError(f"file {url_or_filename} not found")
OSError: file /Users/eduardoreyes/Documents/stable-diffusion-webui/models/dreambooth/fitnessruben/working/config.json not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/eduardoreyes/Documents/stable-diffusion-webui/modules/ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "/Users/eduardoreyes/Documents/stable-diffusion-webui/webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "/Users/eduardoreyes/Documents/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dreambooth.py", line 473, in start_training
    config, mem_record = main(config, mem_record)
  File "/Users/eduardoreyes/Documents/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 585, in main
    text_encoder = CLIPTextModel.from_pretrained(
  File "/Users/eduardoreyes/Documents/stable-diffusion-webui/env/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1764, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/Users/eduardoreyes/Documents/stable-diffusion-webui/env/lib/python3.10/site-packages/transformers/models/clip/configuration_clip.py", line 126, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/Users/eduardoreyes/Documents/stable-diffusion-webui/env/lib/python3.10/site-packages/transformers/configuration_utils.py", line 553, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/Users/eduardoreyes/Documents/stable-diffusion-webui/env/lib/python3.10/site-packages/transformers/configuration_utils.py", line 641, in _get_config_dict
    raise EnvironmentError(
OSError: Can't load config for '/Users/eduardoreyes/Documents/stable-diffusion-webui/models/dreambooth/fitnessruben/working'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/Users/eduardoreyes/Documents/stable-diffusion-webui/models/dreambooth/fitnessruben/working' is the correct path to a directory containing a config.json file
```

**Environment**

What OS?
Mac OS M1

What GPU are you using?
Integrated

**Screenshots/Config**

```
{
    "max_token_length": "75",
    "model_dir": "/Users/eduardoreyes/Documents/stable-diffusion-webui/models/dreambooth/fitnessruben",
    "pretrained_model_name_or_path": "/Users/eduardoreyes/Documents/stable-diffusion-webui/models/dreambooth/fitnessruben/working",
    "class_guidance_scale": 7.5,
    "class_negative_prompt": "",
    "class_infer_steps": 40,
    "model_name": "fitnessruben",
    "scheduler": "ddim",
    "src": "v1-5-pruned.ckpt [a9263745]",
    "total_steps": 0,
    "revision": 0,
    "pretrained_vae_name_or_path": null,
    "instance_data_dir": "/Users/eduardoreyes/Desktop/backups/Training images/Fitness Ruben/Processed",
    "class_data_dir": "/Users/eduardoreyes/Desktop/backups/Training images/Stable-Diffusion-Regularization-Images-person_ddim/person_ddim",
    "instance_prompt": "photo of fitnessruben person",
    "class_prompt": "photo of a person",
    "save_sample_prompt": "",
    "save_sample_negative_prompt": "",
    "n_save_sample": 1,
    "seed": 0,
    "save_guidance_scale": 7.5,
    "save_infer_steps": 40,
    "with_prior_preservation": false,
    "num_class_images": 0,
    "output_dir": "/Users/eduardoreyes/Documents/stable-diffusion-webui/models/dreambooth/fitnessruben",
    "resolution": 512,
    "center_crop": false,
    "train_text_encoder": true,
    "train_batch_size": 1,
    "sample_batch_size": 1,
    "num_train_epochs": 1,
    "max_train_steps": 1200,
    "gradient_accumulation_steps": 1,
    "gradient_checkpointing": true,
    "learning_rate": 1e-06,
    "scale_lr": false,
    "lr_scheduler": "constant",
    "lr_warmup_steps": 0,
    "use_8bit_adam": false,
    "adam_beta1": 0.9,
    "adam_beta2": 0.999,
    "adam_weight_decay": 0.01,
    "adam_epsilon": 1e-08,
    "max_grad_norm": 1,
    "save_preview_every": 5000,
    "save_embedding_every": 6000,
    "mixed_precision": "no",
    "not_cache_latents": false,
    "concepts_list": null,
    "use_cpu": false,
    "pad_tokens": true,
    "hflip": true,
    "use_ema": false,
    "prior_loss_weight": 1
}
```

**Comment by tkclimb** [comment]
Hi, you may be using older version of transformers(4.19.2) that is fixed by the requiement_version.txt in AUTOMATIC1111 SD WebUI, so please try to update by `pip install --upgrade transformers==4.22.1`. (you might see the cache update)
The detail of the problem is mentioned [here](https://github.com/CompVis/stable-diffusion/issues/302)

**Comment by d8ahazard** [comment]
> Hi, you may be using older version of transformers(4.19.2) that is fixed by the requiement_version.txt in AUTOMATIC1111 SD WebUI, so please try to update by `pip install --upgrade transformers==4.22.1`. (you might see the cache update) The detail of the problem is mentioned [here](https://github.com/CompVis/stable-diffusion/issues/302)

Good catch. I'll add logging the transformers version to the UI as well.

**Comment by lustfeind** [comment]
Just noticed that the CLIP function in SD needs transformers 4.19.2

**Comment by lustfeind** [comment]
Info: Interrogate CLIP only works with transformers 4.19.2 on M1 Mac. 
If you upgrade to 4.22.1 dreambooth works, but you lose interrogate CLIP

**Comment by eddjrn** [comment]
It got fixed with the comment of @tkclimb , thank you.

**Comment by eddjrn** [comment]
Fixed

**Comment by d8ahazard** [comment]
> 4.19.2

Nevermind, I found the problem...and fixed it.

Some time after 4.19.2, they decided to add a method which is supposed to validate that the kwargs for the model are actually valid for the model. But, if we try to change them to match what the documentation says, it throws a multitude of other errors.

So, instead of spending the next day trying to debug *why* it's breaking, the simple solution is to just monkey-patch the method that "validates" the kwargs to just pass.

As such, I've also pushed afc3980, which bumps the transformers version to the latest *and* patches out the breaking checker.
