### ISSUE TITLE
Exception while training: CUDA error: invalid argument CUDA kernel errors might be asynchronously reported

### ISSUE THREAD

**Issue by B-getty** [d8ahazard/sd_dreambooth_extension#242]
## Kindly read this ENTIRE form and fill it out with the requested information. It may seem tedious, but it's even more tedious asking basic questions to ensure I'm not trying to troubleshoot a bug I've already fixed. Help me help you, answer all the questions and follow the steps below before posting.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your issue will be automatically closed._**

`
Already up to date.
venv "C:\Users\Job\stable-diffusion-webui - 1111\venv\Scripts\Python.exe"
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Commit hash: 98947d173e3f1667eba29c904f681047dea9de90
Installing requirements for Web UI
Installing requirements for Dreambooth
Checking Dreambooth requirements.
Checking/upgrading existing torch/torchvision installation
Checking torch and torchvision versions
Dreambooth revision is d15cbc9d7293a61a39fab9533d1120722de26abc
Diffusers version is 0.7.2.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**

Yes.

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**

Yes.

**Have you updated Dreambooth to the latest revision?**

Yes.

**Have you updated the Stable-Diffusion-WebUI to the latest version?**

Yes.

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**

OK.

**Describe the bug**

Launching Web UI with arguments: --xformers --allow-code
Dreambooth API layer loaded
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loading weights [b8347bd3] from C:\Users\Job\stable-diffusion-webui - 1111\models\Stable-diffusion\HassansBlend1.3.ckpt
Global Step: 977315
Applying xformers cross attention optimization.
Model loaded.
Loaded a total of 70 textual inversion embeddings.
Embeddings: 
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Trying to parse: [{"instance_prompt": "a picture of a flibbetyflibb ", "class_prompt": "a photo of a person", "sample_prompt": "", "negative_prompt": "", "instance_data_dir": "A:\\Downloads\\Embedding materials\\fkibbety\\prepped\\squares\\PPed", "class_data_dir": "A:\\Downloads\\Embedding materials\\Class training - flib\\squared 512"}]
Trying to parse: [{"instance_prompt": "a picture of a flibbetyflibb", "class_prompt": "a photo of a person", "sample_prompt": "", "negative_prompt": "", "instance_data_dir": "A:\\Downloads\\Embedding materials\\fkibbety\\prepped\\squares\\PPed", "class_data_dir": "A:\\Downloads\\Embedding materials\\Class training - flib\\squared 512"}]
Starting Dreambooth training...
 VRAM cleared.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Loaded model.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Scheduler Loaded
 Allocated: 0.3GB
 Reserved: 0.4GB

***** Running training *****
  Num examples = 2000
  Num batches each epoch = 1000
  Num Epochs = 1
  Instantaneous batch size per device = 2
  Total train batch size (w. parallel, distributed & accumulation) = 2
  Gradient Accumulation steps = 1
  Total optimization steps = 800
Steps:   0%|                                                                                   | 0/800 [00:00<?, ?it/s] Exception while training: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
 Allocated: 4.7GB
 Reserved: 9.6GB

Traceback (most recent call last):
  File "C:\Users\Job\stable-diffusion-webui - 1111\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 981, in main
    accelerator.backward(loss)
  File "C:\Users\Job\stable-diffusion-webui - 1111\venv\lib\site-packages\accelerate\accelerator.py", line 1190, in backward
    loss.backward(**kwargs)
  File "C:\Users\Job\stable-diffusion-webui - 1111\venv\lib\site-packages\torch\_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "C:\Users\Job\stable-diffusion-webui - 1111\venv\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "C:\Users\Job\stable-diffusion-webui - 1111\venv\lib\site-packages\torch\autograd\function.py", line 253, in apply
    return user_fn(self, *args)
  File "C:\Users\Job\stable-diffusion-webui - 1111\venv\lib\site-packages\torch\utils\checkpoint.py", line 146, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "C:\Users\Job\stable-diffusion-webui - 1111\venv\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "C:\Users\Job\stable-diffusion-webui - 1111\venv\lib\site-packages\torch\autograd\function.py", line 253, in apply
    return user_fn(self, *args)
  File "C:\Users\Job\stable-diffusion-webui - 1111\venv\lib\site-packages\xformers\ops.py", line 369, in backward
    ) = torch.ops.xformers.efficient_attention_backward_cutlass(
  File "C:\Users\Job\stable-diffusion-webui - 1111\venv\lib\site-packages\torch\_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
 CLEANUP:
 Allocated: 4.5GB
 Reserved: 9.6GB

 Cleanup Complete.
 Allocated: 4.5GB
 Reserved: 9.6GB

Steps:   0%|                                                                                   | 0/800 [00:12<?, ?it/s]
 Training completed, reloading SD Model.
 Allocated: 0.0GB
 Reserved: 0.0GB

Memory output: {'VRAM cleared.': '0.0/0.0GB', 'Loaded model.': '0.0/0.0GB', 'Scheduler Loaded': '0.3/0.4GB', 'Exception while training: CUDA error: invalid argument\nCUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.': '4.7/9.6GB', 'CLEANUP: ': '4.5/9.6GB', 'Cleanup Complete.': '4.5/9.6GB', 'Training completed, reloading SD Model.': '0.0/0.0GB'}
Re-applying optimizations...
Returning result: Training finished. Total lifetime steps: 1

**Provide logs**

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

**Environment**

What OS? windows 10

If Windows - native

What GPU are you using?
 
 rtx 3090
 
**Screenshots/Config**

If the issue is specific to an error while training, please provide a screenshot of training parameters or the db_config.json file from /models/dreambooth/MODELNAME/db_config.json

{
    "max_token_length": 75,
    "model_dir": "C:\\Users\\Job\\stable-diffusion-webui - 1111\\models\\dreambooth\\flibbetyflibb",
    "pretrained_model_name_or_path": "C:\\Users\\Job\\stable-diffusion-webui - 1111\\models\\dreambooth\\flibbetyflibb\\working",
    "class_guidance_scale": 7.5,
    "class_negative_prompt": "",
    "class_infer_steps": 60,
    "model_name": "flibbetyflibb",
    "scheduler": "ddim",
    "src": "v1-5-pruned.ckpt [a9263745]",
    "total_steps": 0,
    "pretrained_vae_name_or_path,": "",
    "instance_data_dir": "A:\\Downloads\\Embedding materials\\fkibbety\\prepped\\squares\\PPed",
    "class_data_dir": "A:\\Downloads\\Embedding materials\\Class training - flibb\\squared 512",
    "instance_prompt": "a picture of a flibbetyflibb",
    "use_filename_as_label": false,
    "use_txt_as_label": false,
    "class_prompt": "a photo of a person",
    "save_sample_prompt": "",
    "save_sample_negative_prompt": "",
    "n_save_sample": 1,
    "save_guidance_scale": 7.5,
    "save_infer_steps": 35,
    "with_prior_preservation": true,
    "num_class_images": 2000,
    "output_dir": "C:\\Users\\Job\\stable-diffusion-webui - 1111\\models\\dreambooth\\flibbetyflibb",
    "working_dir": "C:\\Users\\Job\\stable-diffusion-webui - 1111\\models\\dreambooth\\flibbetyflibb\\working",
    "resolution": 512,
    "center_crop": false,
    "train_text_encoder": true,
    "train_batch_size": 2,
    "sample_batch_size": 1,
    "num_train_epochs": 1,
    "max_train_steps": 800,
    "gradient_accumulation_steps": 1,
    "gradient_checkpointing": true,
    "learning_rate": 5e-06,
    "scale_lr": false,
    "lr_scheduler": "constant",
    "lr_warmup_steps": 0,
    "use_8bit_adam": false,
    "adam_beta1": 0.9,
    "adam_beta2": 0.999,
    "adam_weight_decay": 0.01,
    "adam_epsilon": 1e-08,
    "max_grad_norm": 1,
    "save_preview_every": 25,
    "save_embedding_every": 100,
    "mixed_precision": "no",
    "not_cache_latents": true,
    "concepts_list": [
        {
            "instance_prompt": "a picture of a flibbetyflibb",
            "class_prompt": "a photo of a person",
            "sample_prompt": "",
            "negative_prompt": "",
            "instance_data_dir": "A:\\Downloads\\Embedding materials\\fkibbety\\prepped\\squares\\PPed",
            "class_data_dir": "A:\\Downloads\\Embedding materials\\Class training - flibb\\squared 512"
        }
    ],
    "use_cpu": false,
    "pad_tokens": true,
    "hflip": true,
    "prior_loss_weight": 1,
    "seed": null,
    "revision": 1,
    "pretrained_vae_name_or_path": null,
    "use_ema": null,
    "tokenizer_name": null
}
---------------------------------------------------

I've updated SD webui, dreambooth, and I've installed CUDA toolkit.  I've tried with and without xformers.

**Comment by B-getty** [comment]
Could someone at least tell me why my issue is going unaddressed?

**Comment by d8ahazard** [comment]
> Could someone at least tell me why my issue is going unaddressed?

Because unfortunately, out of all my mad skills, "cloning myself" is not yet one of them, so this "someone" of which you speak is really just me. 

This issue should be related to using xformers without fp16 and 8bit adam. Set precision to "fp16" and check "Use 8bit adam" in advanced settings before training, or run without the --xformers flag.

**Comment by d8ahazard** [comment]
Same issue as #48 #50 #115 etc.
