### ISSUE TITLE
Broken wizards with brand new model

### ISSUE THREAD

**Issue by Gman0909** [d8ahazard/sd_dreambooth_extension#245]
## Kindly read this ENTIRE form and fill it out with the requested information. It may seem tedious, but it's even more tedious asking basic questions to ensure I'm not trying to troubleshoot a bug I've already fixed. Help me help you, answer all the questions and follow the steps below before posting.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your issue will be automatically closed._**

`
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 98947d173e3f1667eba29c904f681047dea9de90
Installing requirements for Web UI
Installing requirements for scikit_learn

Installing requirements for Dreambooth
Checking Dreambooth requirements.
Checking/upgrading existing torch/torchvision installation
Checking torch and torchvision versions
Dreambooth revision is 725d85ca5485246a430d2f31f624646d061e8104
Diffusers version is 0.7.2.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**

YES

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**

YES

**Have you updated Dreambooth to the latest revision?**

YES

**Have you updated the Stable-Diffusion-WebUI to the latest version?**

YES

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**

OK

**Describe the bug**

After creating a new Dreambooth model and selecting it, clicking on either of the wizards results in an error (see below). 

However if I go into Settings and restart the interface, then back into Dreambooth training, and reselect the newly created model, the wizards work fine.

BUT, if I then tick the "use concepts list" checkbox and press the buttons, the wizards fail again.

I am guessing the model selection dropdown's list for the Dreambooth tab does not get properly refreshed when moving from the model creation tab to the training tab, AND/OR the concept list checkbox is somehow interfering with the wizards' ability to correctly populate the form.

**Provide logs**

`
Error loading params.
Traceback (most recent call last):
  File "E:\stable-diffusion\stable-diffusion-Automatic\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "E:\stable-diffusion\stable-diffusion-Automatic\venv\lib\site-packages\gradio\blocks.py", line 983, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "E:\stable-diffusion\stable-diffusion-Automatic\venv\lib\site-packages\gradio\blocks.py", line 913, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range
`

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

**Environment**

What OS? Windows 11

If Windows - WSL or native? Native

What GPU are you using? 2080Ti

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the db_config.json file from /models/dreambooth/MODELNAME/db_config.json

![image](https://user-images.githubusercontent.com/12699608/202482287-19832d5b-2090-4b26-8263-e6db7be25e79.png)

**Comment by d8ahazard** [comment]
This should be fixed with fabda49
