### ISSUE TITLE
MacOS is slow

### ISSUE THREAD

**Issue by marinohardin** [d8ahazard/sd_dreambooth_extension#251]
**Please find the following lines in the console and paste them below. _If you do not provide this information, your issue will be automatically closed._**

`
Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Commit hash: efb70649da409b395321aaa9e0f38e9ff1b93123
Installing requirements for Web UI
Skipping dreambooth installation.
Dreambooth revision is ****************************************
Diffusers version is 0.3.0
Torch version is 1.12.1
Torch vision version is 0.13.1
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**

Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes

**Have you updated Dreambooth to the latest revision?**
Yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
OK
**Describe the bug**

Dreambooth training is very slow on an M1 Pro MacBook Pro.  I get 3-4s/it for generating images, but 30s/it for Dreambooth training.  I suspect it is falling back to CPU when I use Dreambooth, as my GPU usage is almost zero. 

**Provide logs**

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

**Environment**

What OS?

MacOS Mavericks

What GPU are you using?
M1 Pro 16-core GPU

**Screenshots/Config**

When training starts I get this:

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================

CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
CUDA SETUP: Loading binary /Users/chardin/opt/miniconda3/envs/web-ui/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
Exception importing 8bit adam: dlopen(/Users/chardin/opt/miniconda3/envs/web-ui/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so, 0x0006): tried: '/Users/chardin/opt/miniconda3/envs/web-ui/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so' (not a mach-o file)
 Loaded dataset, moved vae and text encoder. 
 Allocated: 0.0GB 
 Reserved: 0.0GB 

 Cached latents if selected, cleaned up VAE. 
 Allocated: 0.0GB 
 Reserved: 0.0GB 

 Scheduler, EMA Loaded. 
 Allocated: 0.0GB 
 Reserved: 0.0GB 

***** Running training *****

**Comment by marinohardin** [comment]
After running 19 hours, it crashed on finish:

Generating samples: 100%|██████████████████████| 1/1 [02:42<00:00, 162.25s/it]
[*] Weights saved at /Users/chardin/gitdir/stable-diffusion-webui/models/dreambooth/JWLett
Generating samples: 100%|██████████████████████| 1/1 [02:40<00:00, 160.60s/it]
[*] Weights saved at /Users/chardin/gitdir/stable-diffusion-webui/models/dreambooth/JWLett
Steps:  97%|█████▊| 2437/2500 [19:21:23<27:16, 25.98s/it, loss=0.256, lr=5e-6]StSteps: 100%|██████| 2500/2500 [19:50:39<00:00, 26.87s/it, loss=0.257, lr=5e-6]Successfully trained model for a total of 2600 steps, converting to ckpt.
Exception saving checkpoint/model: [enforce fail at inline_container.cc:300] . unexpected pos 3492359232 vs 3492359120
Traceback (most recent call last):
  File "/Users/chardin/opt/miniconda3/envs/web-ui/lib/python3.10/site-packages/torch/serialization.py", line 380, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/Users/chardin/opt/miniconda3/envs/web-ui/lib/python3.10/site-packages/torch/serialization.py", line 604, in _save
    zip_file.write_record(name, storage.data_ptr(), num_bytes)
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chardin/gitdir/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 895, in save_weights
    save_checkpoint(args.model_name, args.pretrained_vae_name_or_path, args.revision,
  File "/Users/chardin/gitdir/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dreambooth.py", line 549, in save_checkpoint
    conversion.diff_to_sd(src_path, vae_path, out_file, use_half)
  File "/Users/chardin/gitdir/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/conversion.py", line 999, in diff_to_sd
    torch.save(state_dict, checkpoint_name)
  File "/Users/chardin/opt/miniconda3/envs/web-ui/lib/python3.10/site-packages/torch/serialization.py", line 379, in save
    with _open_zipfile_writer(opened_file) as opened_zipfile:
  File "/Users/chardin/opt/miniconda3/envs/web-ui/lib/python3.10/site-packages/torch/serialization.py", line 260, in __exit__
    self.file_like.write_end_of_file()
RuntimeError: [enforce fail at inline_container.cc:300] . unexpected pos 3492359232 vs 3492359120
libc++abi: terminating with uncaught exception of type c10::Error: [enforce fail at inline_container.cc:300] . unexpected pos 3492359232 vs 3492359120
frame #0: caffe2::serialize::ostream_write_func(void*, unsigned long long, void const*, unsigned long) + 200 (0x16173e5fc in libtorch_cpu.dylib)
frame #1: mz_zip_writer_add_mem_ex_v2 + 1544 (0x161738500 in libtorch_cpu.dylib)
frame #2: caffe2::serialize::PyTorchStreamWriter::writeRecord(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, void const*, unsigned long, bool) + 452 (0x16173f2b0 in libtorch_cpu.dylib)
frame #3: caffe2::serialize::PyTorchStreamWriter::writeEndOfFile() + 384 (0x16173f540 in libtorch_cpu.dylib)
frame #4: caffe2::serialize::PyTorchStreamWriter::~PyTorchStreamWriter() + 36 (0x16173f744 in libtorch_cpu.dylib)
frame #5: pybind11::class_<caffe2::serialize::PyTorchStreamWriter>::dealloc(pybind11::detail::value_and_holder&) + 88 (0x1079ed430 in libtorch_python.dylib)
frame #6: pybind11::detail::clear_instance(_object*) + 408 (0x107469a08 in libtorch_python.dylib)
frame #7: pybind11_object_dealloc + 20 (0x1074696a8 in libtorch_python.dylib)
frame #8: frame_dealloc + 772 (0x102fe0bb4 in python3.10)
frame #9: tb_dealloc + 304 (0x103160bbc in python3.10)
frame #10: OSError_clear + 280 (0x102fcb7d4 in python3.10)
frame #11: OSError_dealloc + 56 (0x102fcb4dc in python3.10)
frame #12: BaseException_dealloc + 220 (0x102fc9814 in python3.10)
frame #13: _PyEval_EvalFrameDefault + 22740 (0x1030e48dc in python3.10)
frame #14: _PyEval_Vector + 360 (0x1030dd6c0 in python3.10)
frame #15: call_function + 132 (0x1030ecc70 in python3.10)
frame #16: _PyEval_EvalFrameDefault + 16316 (0x1030e2fc4 in python3.10)
frame #17: _PyEval_Vector + 360 (0x1030dd6c0 in python3.10)
frame #18: call_function + 132 (0x1030ecc70 in python3.10)
frame #19: _PyEval_EvalFrameDefault + 16316 (0x1030e2fc4 in python3.10)
frame #20: _PyEval_Vector + 360 (0x1030dd6c0 in python3.10)
frame #21: _PyEval_EvalFrameDefault + 2416 (0x1030df978 in python3.10)
frame #22: _PyEval_Vector + 360 (0x1030dd6c0 in python3.10)
frame #23: _PyEval_EvalFrameDefault + 2416 (0x1030df978 in python3.10)
frame #24: _PyEval_Vector + 360 (0x1030dd6c0 in python3.10)
frame #25: _PyObject_VectorcallTstate.4665 + 96 (0x10310b0b8 in python3.10)
frame #26: context_run + 92 (0x10310af14 in python3.10)
frame #27: cfunction_vectorcall_FASTCALL_KEYWORDS + 84 (0x10301cc4c in python3.10)
frame #28: _PyEval_EvalFrameDefault + 2416 (0x1030df978 in python3.10)
frame #29: _PyEval_Vector + 360 (0x1030dd6c0 in python3.10)
frame #30: call_function + 132 (0x1030ecc70 in python3.10)
frame #31: _PyEval_EvalFrameDefault + 19368 (0x1030e3bb0 in python3.10)
frame #32: _PyEval_Vector + 360 (0x1030dd6c0 in python3.10)
frame #33: call_function + 132 (0x1030ecc70 in python3.10)
frame #34: _PyEval_EvalFrameDefault + 19368 (0x1030e3bb0 in python3.10)
frame #35: _PyEval_Vector + 360 (0x1030dd6c0 in python3.10)
frame #36: method_vectorcall + 388 (0x102fbc6d8 in python3.10)
frame #37: thread_run + 172 (0x1031da320 in python3.10)
frame #38: pythread_wrapper + 48 (0x103160064 in python3.10)
frame #39: _pthread_start + 148 (0x19229c26c in libsystem_pthread.dylib)
frame #40: thread_start + 8 (0x19229708c in libsystem_pthread.dylib)

./run_webui_mac.sh: line 50: 70942 Abort trap: 6           python webui.py --precision full --xformers --disable-safe-unpickle --no-half --no-half-vae --use-cpu Interrogate GFPGAN CodeFormer $@
/Users/chardin/opt/miniconda3/envs/web-ui/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
(web-ui) ➜  stable-diffusion-webui git:(master) ✗ CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
zsh: command not found: CUDA_SETUP:
(web-ui) ➜  stable-diffusion-webui git:(master) ✗ WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
zsh: no matches found: (anaconda)!
(web-ui) ➜  stable-diffusion-webui git:(master) ✗ CUDA SETUP: Loading binary /Users/chardin/opt/miniconda3/envs/web-ui/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
zsh: command not found: CUDA
(web-ui) ➜  stable-diffusion-webui git:(master) ✗ Exception importing 8bit adam: dlopen(/Users/chardin/opt/miniconda3/envs/web-ui/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so, 0x0006): tried: '/Users/chardin/opt/miniconda3/envs/web-ui/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so' (not a mach-o file)
zsh: bad pattern: dlopen(/Users/chardin/opt/miniconda3/envs/web-ui/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so, 0x0006):
(web-ui) ➜  stable-diffusion-webui git:(master) ✗  Loaded dataset, moved vae and text encoder. 
zsh: command not found: Loaded
(web-ui) ➜  stable-diffusion-webui git:(master) ✗  Allocated: 0.0GB 
zsh: command not found: Allocated:
(web-ui) ➜  stable-diffusion-webui git:(master) ✗  Reserved: 0.0GB 
zsh: command not found: Reserved:
(web-ui) ➜  stable-diffusion-webui git:(master) ✗ 
(web-ui) ➜  stable-diffusion-webui git:(master) ✗  Cached latents if selected, cleaned up VAE. 
zsh: command not found: Cached
(web-ui) ➜  stable-diffusion-webui git:(master) ✗  Allocated: 0.0GB 
zsh: command not found: Allocated:
(web-ui) ➜  stable-diffusion-webui git:(master) ✗  Reserved: 0.0GB 
zsh: command not found: Reserved:
(web-ui) ➜  stable-diffusion-webui git:(master) ✗ 
(web-ui) ➜  stable-diffusion-webui git:(master) ✗  Scheduler, EMA Loaded. 
zsh: command not found: Scheduler,
(web-ui) ➜  stable-diffusion-webui git:(master) ✗  Allocated: 0.0GB 
zsh: command not found: Allocated:
(web-ui) ➜  stable-diffusion-webui git:(master) ✗  Reserved: 0.0GB 
zsh: command not found: Reserved:

**Comment by marinohardin** [comment]
Ok so I'm a dummy on the out of disk space- I made it checkpoint way too often and filled up my drive, LOL.

But that only covers the second comment, not the first.  My Ryzen 2600X does 90 s/it when I run it on pure CPU.  My M1 Pro is clearly getting 20x higher performance when generating an image than when training in Dreambooth and is not using the GPU on dreambooth.

So the bug report still remains: Dreambooth is not using MPS / Metal and using CPU on MacOS.

**Comment by pallazola** [comment]
Me too! I'm on Mac Studio M1 Ultra. txt2img is much faster, and if I look at the GPU usage it is 100%. I can do dreambooth training with this extension but it takes hours and hours; 5-12 hours depending of number of images, settings. So yes I would love for this extension to implement mps to speed up the training. The GPU is barley being used. :( 
Thanks

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
