### ISSUE TITLE
Dreambooth training immidiately stops after start training

### ISSUE THREAD

**Issue by art-phony** [d8ahazard/sd_dreambooth_extension#262]
## Kindly read this ENTIRE form and fill it out with the requested information. It may seem tedious, but it's even more tedious asking basic questions to ensure I'm not trying to troubleshoot a bug I've already fixed. Help me help you, answer all the questions and follow the steps below before posting.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your issue will be automatically closed._**

```
Python 3.9.13 (main, May 23 2022, 22:01:06) 
[GCC 9.4.0]
Commit hash: ccd73fc186603b626d996b888d628ebb6b1a38d8
Installing gfpgan
Installing clip
Installing requirements for CodeFormer
Installing requirements for Web UI

Installing requirements for Dreambooth
Checking Dreambooth requirements.
Dreambooth revision is dd2d9aab1a3cb73d8b11e805197e01abd43933fa
Diffusers version is 0.7.2.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.
Transformers version is 4.24.0.
```

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes

**Have you updated Dreambooth to the latest revision?**
Yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
OK.  
Actually, I reset a whole environment (I completely deleted stable-diffusion-webui folder and clone repository & sd_dreambooth_extension again. I re-created new notebook in Paperspace gradient.)

**Describe the bug**

(A clear and concise description of what the bug is)
When I start dreambooth training, it instantly ends learning.

**Provide logs**

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

```
/notebooks/stable-diffusion-webui
Patching transformers to fix kwargs errors.
Dreambooth API layer loaded
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loading weights [1a7df6b8] from /notebooks/stable-diffusion-webui/models/Stable-diffusion/Anything-V3.0-pruned-fp32.ckpt
Applying xformers cross attention optimization.
Model loaded.
Loaded a total of 0 textual inversion embeddings.
Embeddings: 
Running on local URL:  http://127.0.0.1:7860/
Running on public URL: https://38de1c5e03120be9.gradio.app/

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
Loading concepts: [{'instance_prompt': 'yukimiku2018', 'class_prompt': 'girl', 'sample_prompt': '', 'negative_prompt': '', 'instance_data_dir': '/storage/DB-train/4_square_split_only', 'class_data_dir': '/storage/DB-train/girls'}]
Trying to parse: [{"instance_prompt": "yukimiku2018", "class_prompt": "girl", "sample_prompt": "", "negative_prompt": "", "instance_data_dir": "/storage/DB-train/4_square_split_only", "class_data_dir": "/storage/DB-train/girls"}]
Starting Dreambooth training...
 VRAM cleared. 
 Allocated: 0.0GB 
 Reserved: 0.0GB 

 Loaded model. 
 Allocated: 0.0GB 
 Reserved: 0.0GB 

msg
 CLEANUP:  
 Allocated: 0.0GB 
 Reserved: 0.0GB 

 Cleanup Complete. 
 Allocated: 0.0GB 
 Reserved: 0.0GB 

Error completing request
Arguments: ('dbtest2233', False, False, None, '/storage/DB-train/4_square_split_only', '/storage/DB-train/girls', 'yukimiku2018', 'girl', '', '', 1, 0, 7.5, 40, 100, 512, False, True, 1, 1, 1, 1000, 1, True, 5e-06, False, 'constant', 0, False, 0.9, 0.999, 0.01, 1e-08, 1, 500, 500, 'no', True, "[{'instance_prompt': 'yukimiku2018', 'class_prompt': 'girl', 'sample_prompt': '', 'negative_prompt': '', 'instance_data_dir': '/storage/DB-train/4_square_split_only', 'class_data_dir': '/storage/DB-train/girls'}]", False, True, '75', True, False, '', 7.5, 40) {}
Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/modules/ui.py", line 188, in f
    res = list(func(*args, **kwargs))
  File "/notebooks/stable-diffusion-webui/webui.py", line 57, in f
    res = func(*args, **kwargs)
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dreambooth.py", line 512, in start_training
    printm("Training completed, reloading SD Model.")
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dreambooth.py", line 539, in printm
    mem_record[msg] = f"{allocated},{cached}"
TypeError: 'str' object does not support item assignment
```

**Environment**

Linux, Ubuntu 20.04.4 LTS on Paperspace Gradient

```
# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
```
# python -c 'import torch; print(torch.version.cuda)'
11.6
# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_Mar__8_18:18:20_PST_2022
Cuda compilation tools, release 11.6, V11.6.124
Build cuda_11.6.r11.6/compiler.31057947_0
# nvidia-smi
Sat Nov 19 13:49:28 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.73.05    Driver Version: 510.73.05    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  Off  | 00000000:00:05.0 Off |                    0 |
| N/A   38C    P0    62W / 400W |   1139MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
```

This problem confirmed in A100-80G and A6000.

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the db_config.json file from /models/dreambooth/MODELNAME/db_config.json

/notebooks/stable-diffusion-webui/models/dreambooth/dbtest2233/db_config.json
```
{
    "max_token_length": "75",
    "model_dir": "/notebooks/stable-diffusion-webui/models/dreambooth/dbtest2233",
    "pretrained_model_name_or_path": "/notebooks/stable-diffusion-webui/models/dreambooth/dbtest2233/working",
    "class_guidance_scale": 7.5,
    "class_negative_prompt": "",
    "class_infer_steps": 40,
    "use_concepts": false,
    "half_model": false,
    "model_name": "dbtest2233",
    "scheduler": "ddim",
    "src": "Anything-V3.0-pruned-fp32.ckpt [1a7df6b8]",
    "total_steps": 0,
    "revision": 0,
    "pretrained_vae_name_or_path": null,
    "instance_data_dir": "/storage/DB-train/4_square_split_only",
    "class_data_dir": "/storage/DB-train/girls",
    "instance_prompt": "yukimiku2018",
    "class_prompt": "girl",
    "save_sample_prompt": "",
    "save_sample_negative_prompt": "",
    "n_save_sample": 1,
    "seed": 0,
    "save_guidance_scale": 7.5,
    "save_infer_steps": 40,
    "with_prior_preservation": true,
    "num_class_images": 100,
    "output_dir": "/notebooks/stable-diffusion-webui/models/dreambooth/dbtest2233",
    "resolution": 512,
    "center_crop": false,
    "train_text_encoder": true,
    "train_batch_size": 1,
    "sample_batch_size": 1,
    "num_train_epochs": 1,
    "max_train_steps": 1000,
    "gradient_accumulation_steps": 1,
    "gradient_checkpointing": true,
    "learning_rate": 5e-06,
    "scale_lr": false,
    "lr_scheduler": "constant",
    "lr_warmup_steps": 0,
    "use_8bit_adam": false,
    "adam_beta1": 0.9,
    "adam_beta2": 0.999,
    "adam_weight_decay": 0.01,
    "adam_epsilon": 1e-08,
    "max_grad_norm": 1,
    "save_preview_every": 500,
    "save_embedding_every": 500,
    "mixed_precision": "no",
    "not_cache_latents": true,
    "concepts_list": [
        {
            "instance_prompt": "yukimiku2018",
            "class_prompt": "girl",
            "sample_prompt": "",
            "negative_prompt": "",
            "instance_data_dir": "/storage/DB-train/4_square_split_only",
            "class_data_dir": "/storage/DB-train/girls"
        }
    ],
    "use_cpu": false,
    "pad_tokens": true,
    "hflip": true,
    "use_ema": false,
    "prior_loss_weight": 1
}
```

**Comment by d8ahazard** [comment]
Do an update once. I don't think I fixed this with that...but maybe. It's odd that there are no error messages in the log, or even the params for training. 

If you have any other errors in the log, please toss them in here as well.

**Comment by art-phony** [comment]
Thank you for reply! I completely reset my environment and start new Dreambooth training, then another error appers.
  (Still Dreambooth training ends instantly)

System and libraries
```
Python 3.9.13 (main, May 23 2022, 22:01:06) 
[GCC 9.4.0]
Commit hash: 828438b4a190759807f9054932cae3a8b880ddf1
Installing requirements for Web UI
Installing requirements for Dreambooth
Checking Dreambooth requirements.
Dreambooth revision is 0158ca18ddaff6e9c984fb1a7a434e6ac465e5c9
Diffusers version is 0.7.2.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.
Transformers version is 4.21.0.
```
  

Console log
```
/notebooks/stable-diffusion-webui
Patching transformers to fix kwargs errors.
Dreambooth API layer loaded
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loading weights [1a7df6b8] from /notebooks/stable-diffusion-webui/models/Stable-diffusion/Anything-V3.0-pruned-fp32.ckpt
Applying xformers cross attention optimization.
Model loaded.
Loaded a total of 0 textual inversion embeddings.
Embeddings: 
Running on local URL:  http://127.0.0.1:7860
Running on public URL: https://7923ebf542ea52ab.gradio.app

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
Loading concepts: [{'instance_prompt': 'yukimiku2018', 'class_prompt': 'girl', 'instance_data_dir': '/notebooks/training_data/dreambooth_training/4_letterbox_only', 'class_data_dir': '/notebooks/training_data/dreambooth_training/girl', 'instance_token': '', 'class_token': ''}]
Trying to parse: [{"instance_prompt": "yukimiku2018", "class_prompt": "girl", "instance_data_dir": "/notebooks/training_data/dreambooth_training/4_letterbox_only", "class_data_dir": "/notebooks/training_data/dreambooth_training/girl", "instance_token": "", "class_token": ""}]
Starting Dreambooth training...
 VRAM cleared. 
 Allocated: 0.0GB 
 Reserved: 0.0GB 

 Loaded model. 
 Allocated: 0.0GB 
 Reserved: 0.0GB 

 Loaded dataset, moved vae and text encoder. 
 Allocated: 0.3GB 
 Reserved: 0.3GB 

 Cached latents if selected, cleaned up VAE. 
 Allocated: 0.3GB 
 Reserved: 0.3GB 

 Scheduler, EMA Loaded. 
 Allocated: 4.0GB 
 Reserved: 4.1GB 

***** Running training *****
  Num examples = 200
  Num batches each epoch = 200
  Num Epochs = 5
  Instantaneous batch size per device = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Gradient Accumulation steps = 1
  Total optimization steps = 1000
   Training settings: CPU: False Adam: False, Prec: no, Prior: True, Grad: True, TextTr: True EM: False, LR: 5e-06 
 Allocated: 4.0GB 
 Reserved: 4.1GB 

Steps:   0%|                                           | 0/1000 [00:00<?, ?it/s] Exception while training: No operator found for this attention: AttentionOpDispatch(dtype=torch.float32, device=device(type='cuda', index=0), k=160, has_dropout=False, attn_bias_type=<class 'NoneType'>, kv_len=64, q_len=64, kv=160, batch_size=16, num_heads=1, has_custom_scale=False, requires_grad=True) 
 Allocated: 4.1GB 
 Reserved: 11.0GB 

Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1067, in main
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/diffusers/models/unet_2d_condition.py", line 318, in forward
    sample = self.mid_block(sample, emb, encoder_hidden_states=encoder_hidden_states)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/diffusers/models/unet_2d_blocks.py", line 401, in forward
    hidden_states = attn(hidden_states, encoder_hidden_states).sample
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/diffusers/models/attention.py", line 202, in forward
    hidden_states = block(hidden_states, context=encoder_hidden_states, timestep=timestep)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/diffusers/models/attention.py", line 404, in forward
    hidden_states = self.attn1(norm_hidden_states) + hidden_states
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/xattention.py", line 116, in forward
    hidden_states = self._memory_efficient_attention_xformers(query, key, value)
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/xattention.py", line 177, in _memory_efficient_attention_xformers
    hidden_states = xformers.ops.memory_efficient_attention(query, key, value, attn_bias=None)
  File "/usr/local/lib/python3.9/dist-packages/xformers/ops/memory_efficient_attention.py", line 956, in memory_efficient_attention
    op = AttentionOpDispatch.from_arguments(
  File "/usr/local/lib/python3.9/dist-packages/xformers/ops/memory_efficient_attention.py", line 821, in op
    raise NotImplementedError(f"No operator found for this attention: {self}")
NotImplementedError: No operator found for this attention: AttentionOpDispatch(dtype=torch.float32, device=device(type='cuda', index=0), k=160, has_dropout=False, attn_bias_type=<class 'NoneType'>, kv_len=64, q_len=64, kv=160, batch_size=16, num_heads=1, has_custom_scale=False, requires_grad=True)
 Exception while training: No operator found for this attention: AttentionOpDispatch(dtype=torch.float32, device=device(type='cuda', index=0), k=160, has_dropout=False, attn_bias_type=<class 'NoneType'>, kv_len=64, q_len=64, kv=160, batch_size=16, num_heads=1, has_custom_scale=False, requires_grad=True) 
 Allocated: 4.1GB 
 Reserved: 11.0GB 

Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1067, in main
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/diffusers/models/unet_2d_condition.py", line 318, in forward
    sample = self.mid_block(sample, emb, encoder_hidden_states=encoder_hidden_states)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/diffusers/models/unet_2d_blocks.py", line 401, in forward
    hidden_states = attn(hidden_states, encoder_hidden_states).sample
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/diffusers/models/attention.py", line 202, in forward
    hidden_states = block(hidden_states, context=encoder_hidden_states, timestep=timestep)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/diffusers/models/attention.py", line 404, in forward
    hidden_states = self.attn1(norm_hidden_states) + hidden_states
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/xattention.py", line 116, in forward
    hidden_states = self._memory_efficient_attention_xformers(query, key, value)
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/xattention.py", line 177, in _memory_efficient_attention_xformers
    hidden_states = xformers.ops.memory_efficient_attention(query, key, value, attn_bias=None)
  File "/usr/local/lib/python3.9/dist-packages/xformers/ops/memory_efficient_attention.py", line 956, in memory_efficient_attention
    op = AttentionOpDispatch.from_arguments(
  File "/usr/local/lib/python3.9/dist-packages/xformers/ops/memory_efficient_attention.py", line 821, in op
    raise NotImplementedError(f"No operator found for this attention: {self}")
NotImplementedError: No operator found for this attention: AttentionOpDispatch(dtype=torch.float32, device=device(type='cuda', index=0), k=160, has_dropout=False, attn_bias_type=<class 'NoneType'>, kv_len=64, q_len=64, kv=160, batch_size=16, num_heads=1, has_custom_scale=False, requires_grad=True)
 Exception while training: No operator found for this attention: AttentionOpDispatch(dtype=torch.float32, device=device(type='cuda', index=0), k=160, has_dropout=False, attn_bias_type=<class 'NoneType'>, kv_len=64, q_len=64, kv=160, batch_size=16, num_heads=1, has_custom_scale=False, requires_grad=True) 
 Allocated: 4.1GB 
 Reserved: 11.0GB 

Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1067, in main
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/diffusers/models/unet_2d_condition.py", line 318, in forward
    sample = self.mid_block(sample, emb, encoder_hidden_states=encoder_hidden_states)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/diffusers/models/unet_2d_blocks.py", line 401, in forward
    hidden_states = attn(hidden_states, encoder_hidden_states).sample
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/diffusers/models/attention.py", line 202, in forward
    hidden_states = block(hidden_states, context=encoder_hidden_states, timestep=timestep)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/diffusers/models/attention.py", line 404, in forward
    hidden_states = self.attn1(norm_hidden_states) + hidden_states
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/xattention.py", line 116, in forward
    hidden_states = self._memory_efficient_attention_xformers(query, key, value)
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/xattention.py", line 177, in _memory_efficient_attention_xformers
    hidden_states = xformers.ops.memory_efficient_attention(query, key, value, attn_bias=None)
  File "/usr/local/lib/python3.9/dist-packages/xformers/ops/memory_efficient_attention.py", line 956, in memory_efficient_attention
    op = AttentionOpDispatch.from_arguments(
  File "/usr/local/lib/python3.9/dist-packages/xformers/ops/memory_efficient_attention.py", line 821, in op
    raise NotImplementedError(f"No operator found for this attention: {self}")
NotImplementedError: No operator found for this attention: AttentionOpDispatch(dtype=torch.float32, device=device(type='cuda', index=0), k=160, has_dropout=False, attn_bias_type=<class 'NoneType'>, kv_len=64, q_len=64, kv=160, batch_size=16, num_heads=1, has_custom_scale=False, requires_grad=True)
 Exception while training: No operator found for this attention: AttentionOpDispatch(dtype=torch.float32, device=device(type='cuda', index=0), k=160, has_dropout=False, attn_bias_type=<class 'NoneType'>, kv_len=64, q_len=64, kv=160, batch_size=16, num_heads=1, has_custom_scale=False, requires_grad=True) 
 Allocated: 4.1GB 
 Reserved: 11.0GB 

Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1067, in main
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/diffusers/models/unet_2d_condition.py", line 318, in forward
    sample = self.mid_block(sample, emb, encoder_hidden_states=encoder_hidden_states)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/diffusers/models/unet_2d_blocks.py", line 401, in forward
    hidden_states = attn(hidden_states, encoder_hidden_states).sample
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/diffusers/models/attention.py", line 202, in forward
    hidden_states = block(hidden_states, context=encoder_hidden_states, timestep=timestep)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/diffusers/models/attention.py", line 404, in forward
    hidden_states = self.attn1(norm_hidden_states) + hidden_states
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/xattention.py", line 116, in forward
    hidden_states = self._memory_efficient_attention_xformers(query, key, value)
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/xattention.py", line 177, in _memory_efficient_attention_xformers
    hidden_states = xformers.ops.memory_efficient_attention(query, key, value, attn_bias=None)
  File "/usr/local/lib/python3.9/dist-packages/xformers/ops/memory_efficient_attention.py", line 956, in memory_efficient_attention
    op = AttentionOpDispatch.from_arguments(
  File "/usr/local/lib/python3.9/dist-packages/xformers/ops/memory_efficient_attention.py", line 821, in op
    raise NotImplementedError(f"No operator found for this attention: {self}")
NotImplementedError: No operator found for this attention: AttentionOpDispatch(dtype=torch.float32, device=device(type='cuda', index=0), k=160, has_dropout=False, attn_bias_type=<class 'NoneType'>, kv_len=64, q_len=64, kv=160, batch_size=16, num_heads=1, has_custom_scale=False, requires_grad=True)
 Exception while training: No operator found for this attention: AttentionOpDispatch(dtype=torch.float32, device=device(type='cuda', index=0), k=160, has_dropout=False, attn_bias_type=<class 'NoneType'>, kv_len=64, q_len=64, kv=160, batch_size=16, num_heads=1, has_custom_scale=False, requires_grad=True) 
 Allocated: 4.1GB 
 Reserved: 11.0GB 

Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1067, in main
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/diffusers/models/unet_2d_condition.py", line 318, in forward
    sample = self.mid_block(sample, emb, encoder_hidden_states=encoder_hidden_states)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/diffusers/models/unet_2d_blocks.py", line 401, in forward
    hidden_states = attn(hidden_states, encoder_hidden_states).sample
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/diffusers/models/attention.py", line 202, in forward
    hidden_states = block(hidden_states, context=encoder_hidden_states, timestep=timestep)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/diffusers/models/attention.py", line 404, in forward
    hidden_states = self.attn1(norm_hidden_states) + hidden_states
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/xattention.py", line 116, in forward
    hidden_states = self._memory_efficient_attention_xformers(query, key, value)
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/xattention.py", line 177, in _memory_efficient_attention_xformers
    hidden_states = xformers.ops.memory_efficient_attention(query, key, value, attn_bias=None)
  File "/usr/local/lib/python3.9/dist-packages/xformers/ops/memory_efficient_attention.py", line 956, in memory_efficient_attention
    op = AttentionOpDispatch.from_arguments(
  File "/usr/local/lib/python3.9/dist-packages/xformers/ops/memory_efficient_attention.py", line 821, in op
    raise NotImplementedError(f"No operator found for this attention: {self}")
NotImplementedError: No operator found for this attention: AttentionOpDispatch(dtype=torch.float32, device=device(type='cuda', index=0), k=160, has_dropout=False, attn_bias_type=<class 'NoneType'>, kv_len=64, q_len=64, kv=160, batch_size=16, num_heads=1, has_custom_scale=False, requires_grad=True)
 CLEANUP:  
 Allocated: 4.0GB 
 Reserved: 11.0GB 

 Cleanup Complete. 
 Allocated: 4.0GB 
 Reserved: 4.1GB 

 Training completed, reloading SD Model. 
 Allocated: 4.0GB 
 Reserved: 4.1GB 

Memory output: {'VRAM cleared.': '0.0,0.0', 'Loaded model.': '0.0,0.0', 'Loaded dataset, moved vae and text encoder.': '0.3,0.3', 'Cached latents if selected, cleaned up VAE.': '0.3,0.3', 'Scheduler, EMA Loaded.': '4.0,4.1', '  Training settings: CPU: False Adam: False, Prec: no, Prior: True, Grad: True, TextTr: True EM: False, LR: 5e-06': '4.0,4.1', "Exception while training: No operator found for this attention: AttentionOpDispatch(dtype=torch.float32, device=device(type='cuda', index=0), k=160, has_dropout=False, attn_bias_type=<class 'NoneType'>, kv_len=64, q_len=64, kv=160, batch_size=16, num_heads=1, has_custom_scale=False, requires_grad=True)": '4.1,11.0', 'CLEANUP: ': '4.0,11.0', 'Cleanup Complete.': '4.0,4.1', 'Training completed, reloading SD Model.': '4.0,4.1'}
Re-applying optimizations...
Returning result: Training finished. Total lifetime steps: 0 
```

. I completely reset my environment and start new

**Comment by art-phony** [comment]
Sorry, maybe new error occurs by xformers, not by your dreambooth script. I'll still digging around.

**Comment by art-phony** [comment]
Maybe "fp16" option works well. I'll report again when I have confident with that.

**Comment by d8ahazard** [comment]
This should be resolved, I think. I've added checks for xformers and instructions if it's being used to ensure this error doesn't occur.

**Comment by art-phony** [comment]
Thank you. I updated sd_dreambooth_extention to the latest version, and confirmed warning message.
Maybe just fp16 is needed and 8bit Adam is not necessary, but anyway, it works now!
