### ISSUE TITLE
cross_attention_dim must be specified for CrossAttnDownBlock2D

### ISSUE THREAD

**Issue by aZeottaff** [d8ahazard/sd_dreambooth_extension#267]
full error below;

Loading concepts: [{'instance_prompt': 'photo of tealcc person', 'class_prompt': 'photo of person', 'instance_data_dir': 'C:\\Users\\jirih\\Downloads\\tealc', 'class_data_dir': 'C:\\Users\\jirih\\Documents\\GitHub\\stable-diffusion-webui\\models\\dreambooth\\Tealc\\classifiers_concept_0', 'instance_token': '', 'class_token': ''}]
Starting Dreambooth training...
 VRAM cleared.
 Allocated: 0.0GB
 Reserved: 0.0GB

Error completing request
Arguments: ('Tealc', False, False, '', 'C:\\Users\\jirih\\Downloads\\tealc', '', 'photo of tealcc person', 'photo of person', 'Description', '', '', '', '', 1, 0, 7.5, 40, 156, 512, True, True, 1, 1, 1, 1200, -2, True, 1e-06, False, 'constant', 0, True, 0.9, 0.999, 0.01, 1e-08, 1, 0, 0, 'fp16', True, '', False, True, '75', True, False, '', 7.5, 40) {}
Traceback (most recent call last):
  File "C:\Users\jirih\Documents\GitHub\stable-diffusion-webui\modules\ui.py", line 188, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\jirih\Documents\GitHub\stable-diffusion-webui\webui.py", line 57, in f
    res = func(*args, **kwargs)
  File "C:\Users\jirih\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 522, in start_training
    config, mem_record = main(config, mem_record)
  File "C:\Users\jirih\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 591, in main
    vae=AutoencoderKL.from_pretrained(
  File "C:\Users\jirih\Documents\GitHub\stable-diffusion-webui\venv\lib\site-packages\diffusers\modeling_utils.py", line 451, in from_pretrained
    model, unused_kwargs = cls.from_config(
  File "C:\Users\jirih\Documents\GitHub\stable-diffusion-webui\venv\lib\site-packages\diffusers\configuration_utils.py", line 174, in from_config
    model = cls(**init_dict)
  File "C:\Users\jirih\Documents\GitHub\stable-diffusion-webui\venv\lib\site-packages\diffusers\configuration_utils.py", line 444, in inner_init
    init(self, *args, **init_kwargs)
  File "C:\Users\jirih\Documents\GitHub\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\vae.py", line 544, in __init__
    self.encoder = Encoder(
  File "C:\Users\jirih\Documents\GitHub\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\vae.py", line 94, in __init__
    down_block = get_down_block(
  File "C:\Users\jirih\Documents\GitHub\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 64, in get_down_block
    raise ValueError("cross_attention_dim must be specified for CrossAttnDownBlock2D")
ValueError: cross_attention_dim must be specified for CrossAttnDownBlock2D

**Comment by d8ahazard** [comment]
Please use the supplied templates, they exist for a reason.
