### ISSUE TITLE
Tokenizer problem?

### ISSUE THREAD

**Issue by DangCLE** [d8ahazard/sd_dreambooth_extension#270]
## Kindly read this ENTIRE form and fill it out with the requested information. It may seem tedious, but it's even more tedious asking basic questions to ensure I'm not trying to troubleshoot a bug I've already fixed. Help me help you, answer all the questions and follow the steps below before posting.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your issue will be automatically closed._**

`
Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Commit hash: ****************************************
Installing requirements for Web UI
Skipping dreambooth installation.
Dreambooth revision is ****************************************
Diffusers version is *.*.*.
Torch version is *.*.*.
Torch vision version is *.*.*.
`
venv "C:\ai\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 828438b4a190759807f9054932cae3a8b880ddf1
Installing requirements for Web UI
Installing requirements for Dreambooth
Checking Dreambooth requirements.
Checking/upgrading existing torch/torchvision installation
Checking torch and torchvision versions
Dreambooth revision is 0158ca18ddaff6e9c984fb1a7a434e6ac465e5c9
Diffusers version is 0.7.2.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.
Transformers version is 4.21.0.

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?** 
yes

**Have you updated Dreambooth to the latest revision?**

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**

**Describe the bug** 
after inputting all the info in the fields i get a message about the tokenizer

(A clear and concise description of what the bug is)

**Provide logs**
Error completing request
Arguments: ('dang', False, False, '', 'C:\\Users\\Thomas Dang\\Documents\\training files\\dang', 'C:\\Users\\Thomas Dang\\Documents\\training files\\person', 'photo of dang person', 'photo of person', 'Description', 'dang', 'dang', '', '', 1, 0, 7.5, 40, 1500, 512, False, True, 1, 1, 1, 1200, 1, True, 1e-06, True, 'constant', 0, True, 0.9, 0.999, 0.01, 1e-08, 1, 5000, 5000, 'no', True, '', False, True, '75', True, False, '', 7.5, 40) {}
Traceback (most recent call last):
  File "C:\ai\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "C:\ai\stable-diffusion-webui\webui.py", line 57, in f
    res = func(*args, **kwargs)
  File "C:\ai\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 522, in start_training
    config, mem_record = main(config, mem_record)
  File "C:\ai\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 658, in main
    tokenizer = CLIPTokenizer.from_pretrained(
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1789, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'C:\ai\stable-diffusion-webui\models\dreambooth\dang\working'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'C:\ai\stable-diffusion-webui\models\dreambooth\dang\working' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

**Environment**

What OS? 

If Windows - WSL or native? Native i think its just windows

What GPU are you using? 3080

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the db_config.json file from /models/dreambooth/MODELNAME/db_config.json

{
    "max_token_length": "75",
    "model_dir": "C:\\ai\\stable-diffusion-webui\\models\\dreambooth\\dang",
    "pretrained_model_name_or_path": "C:\\ai\\stable-diffusion-webui\\models\\dreambooth\\dang\\working",
    "class_guidance_scale": 7.5,
    "class_negative_prompt": "",
    "class_infer_steps": 40,
    "use_concepts": false,
    "half_model": false,
    "file_prompt_contents": "Description",
    "instance_token": "dang",
    "class_token": "dang",
    "model_name": "dang",
    "scheduler": "ddim",
    "src": "sd-v1-4-full-ema.ckpt [06c50424]",
    "total_steps": 0,
    "revision": 0,
    "pretrained_vae_name_or_path": null,
    "instance_data_dir": "C:\\Users\\Thomas Dang\\Documents\\training files\\dang",
    "class_data_dir": "C:\\Users\\Thomas Dang\\Documents\\training files\\person",
    "instance_prompt": "photo of dang person",
    "class_prompt": "photo of person",
    "save_sample_prompt": "",
    "save_sample_negative_prompt": "",
    "n_save_sample": 1,
    "seed": 0,
    "save_guidance_scale": 7.5,
    "save_infer_steps": 40,
    "with_prior_preservation": true,
    "num_class_images": 1500,
    "output_dir": "C:\\ai\\stable-diffusion-webui\\models\\dreambooth\\dang",
    "resolution": 512,
    "center_crop": false,
    "train_text_encoder": true,
    "train_batch_size": 1,
    "sample_batch_size": 1,
    "num_train_epochs": 1,
    "max_train_steps": 1200,
    "gradient_accumulation_steps": 1,
    "gradient_checkpointing": true,
    "learning_rate": 1e-06,
    "scale_lr": true,
    "lr_scheduler": "constant",
    "lr_warmup_steps": 0,
    "use_8bit_adam": true,
    "adam_beta1": 0.9,
    "adam_beta2": 0.999,
    "adam_weight_decay": 0.01,
    "adam_epsilon": 1e-08,
    "max_grad_norm": 1,
    "save_preview_every": 5000,
    "save_embedding_every": 5000,
    "mixed_precision": "no",
    "not_cache_latents": true,
    "concepts_list": [
        {
            "instance_prompt": "photo of dang person",
            "class_prompt": "photo of person",
            "instance_data_dir": "C:\\Users\\Thomas Dang\\Documents\\training files\\dang",
            "class_data_dir": "C:\\Users\\Thomas Dang\\Documents\\training files\\person",
            "instance_token": "dang",
            "class_token": "dang"
        }
    ],
    "use_cpu": false,
    "pad_tokens": true,
    "hflip": true,
    "use_ema": false,
    "prior_loss_weight": 1
}

**Comment by d8ahazard** [comment]
Check your /models/dreambooth/dang/working folder - is there anything in the "tokenizer" subdirectory?

**Comment by DangCLE** [comment]
i dont have a tokenizer subdirectory

**Comment by DangCLE** [comment]
the folder is empty

**Comment by d8ahazard** [comment]
Create a new checkpoint. I suspect you had some kind of error extracting the original.

**Comment by DangCLE** [comment]
when i go to create it says i dont have enough memory and something about cuda now. Do i not have enough vram?

Creating dreambooth model folder: dang
Checkpoint loaded from CheckpointInfo(filename='C:\\ai\\stable-diffusion-webui\\models\\Stable-diffusion\\sd-v1-4-full-ema.ckpt', title='sd-v1-4-full-ema.ckpt [06c50424]', hash='06c50424', model_name='sd-v1-4-full-ema', config='C:\\ai\\stable-diffusion-webui\\repositories\\stable-diffusion\\configs/stable-diffusion/v1-inference.yaml')
Checkpoint C:\ai\stable-diffusion-webui\models\Stable-diffusion\sd-v1-4-full-ema.ckpt has both EMA and non-EMA weights.
In this conversion only the non-EMA weights are extracted. If you want to instead extract the EMA weights (usually better for inference), please make sure to add the `--extract_ema` flag.
Traceback (most recent call last):
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 982, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 824, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\ai\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\conversion.py", line 944, in extract_checkpoint
    pipe = pipe.to(map_location)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipeline_utils.py", line 220, in to
    module.to(torch_device)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 927, in to
    return self._apply(convert)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  [Previous line repeated 4 more times]
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 602, in _apply
    param_applied = fn(param)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 925, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 12.00 GiB total capacity; 11.12 GiB already allocated; 0 bytes free; 11.28 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Creating dreambooth model folder: dang
Exception with the conversion: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 12.00 GiB total capacity; 11.13 GiB already allocated; 0 bytes free; 11.29 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "C:\ai\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\conversion.py", line 851, in extract_checkpoint
    checkpoint = torch.load(checkpoint_info[0], map_location=map_location)["state_dict"]
  File "C:\ai\stable-diffusion-webui\modules\safe.py", line 102, in load
    return load_with_extra(filename, *args, **kwargs)
  File "C:\ai\stable-diffusion-webui\modules\safe.py", line 147, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 1049, in _load
    result = unpickler.load()
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 1019, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 1001, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 973, in restore_location
    return default_restore_location(storage, str(map_location))
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 157, in _cuda_deserialize
    return obj.cuda(device)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\torch\_utils.py", line 78, in _cuda
    return torch._UntypedStorage(self.size(), device=torch.device('cuda')).copy_(self, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 12.00 GiB total capacity; 11.13 GiB already allocated; 0 bytes free; 11.29 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):

**Comment by Kire221** [comment]
Restart WebUI (maybe restart your PC, I did that). Then, you can run the tab CREATE MODEL. Now, run the Train Tab. I recommend using fp16 and xformers (for me, I can't run in another way using a 3080 12GB).

**Comment by d8ahazard** [comment]
Yes, please update the UI, then the extension, the restart the webUI entirely to ensure the proper updates are installed.

Provide the new output of the log on startup listing the various versions of the packages installed.
You should be good to go with the latest update.

**Comment by samomar** [comment]
I'm training 1600 steps (ETA 16 minutes) on a 3080 10GB and its working fine after I **disabled** Train EMA and Train Text Encoder

Use 8bit Adam

Memory Attention
xformers

Mixed Precision = 'fp16'


I just monitored the GPU and realized it's not that the software is having memory management issues, it's that it maxes out and tries to allocate more but then fails, tweak your settings until you reach a good threshold.

My full settings:
![nQQKRSa](https://user-images.githubusercontent.com/8659480/204198322-f761c756-2cdd-4aab-acad-ee133750fcff.png)
![V4gkOcj](https://user-images.githubusercontent.com/8659480/204203403-80fbb44d-03bf-43a3-b209-eacf4a8d84ca.png)
