### ISSUE TITLE
Unable to lbuild concepts

### ISSUE THREAD

**Issue by Gman0909** [d8ahazard/sd_dreambooth_extension#280]
## Kindly read this ENTIRE form and fill it out with the requested information. It may seem tedious, but it's even more tedious asking basic questions to ensure I'm not trying to troubleshoot a bug I've already fixed. Help me help you, answer all the questions and follow the steps below before posting.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your issue will be automatically closed._**

`
Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Dreambooth revision is 58bb667b0ac3aa048bd5a99a3bd8d1e3634eae9d
Args: ['extensions\\sd_dreambooth_extension\\install.py']
[*] Diffusers version is 0.7.2.
[*] Torch version is 1.12.1+cu116.
[*] Torch vision version is 0.13.1+cu116.
[*] Transformers version is 4.21.0.
[*] Xformers
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**

yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yes
**Have you updated Dreambooth to the latest revision?**
yes
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
yes
**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
OK
**Describe the bug**

Something changed in the concepts_list.json format that makes things no longer work.

If I include the new instance_token and class_token fields, i get "unable to lbuild tokens" as an error when initiating training.

If on the  other hand i add them in, I get this:

`
Traceback (most recent call last):
  File "E:\stable-diffusion\stable-diffusion-Automatic\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "E:\stable-diffusion\stable-diffusion-Automatic\webui.py", line 57, in f
    res = func(*args, **kwargs)
  File "E:\stable-diffusion\stable-diffusion-Automatic\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 556, in start_training
    config, mem_record = main(config, mem_record)
  File "E:\stable-diffusion\stable-diffusion-Automatic\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 752, in main
    train_dataset = DreamBoothDataset(
  File "E:\stable-diffusion\stable-diffusion-Automatic\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 386, in __init__
    inst_img_path = [(x, concept["instance_prompt"], concept["instance_token"], concept["class_token"], self.text_getter.read_text(x)) for x in
  File "E:\stable-diffusion\stable-diffusion-Automatic\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 386, in <listcomp>
    inst_img_path = [(x, concept["instance_prompt"], concept["instance_token"], concept["class_token"], self.text_getter.read_text(x)) for x in
KeyError: 'instance_token'

'

**Provide logs**

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

**Environment**

What OS?

If Windows - WSL or native?

What GPU are you using?

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the db_config.json file from /models/dreambooth/MODELNAME/db_config.json

**Comment by Kylescher1** [comment]
what was the fix to this issue?

**Comment by Andreilys** [comment]
Having the same issue here
