### ISSUE TITLE
runtimeerror: cuda out of memory on rtx 3060 12gb

### ISSUE THREAD

**Issue by Kittingsl** [d8ahazard/sd_dreambooth_extension#287]
**Please find the following lines in the console and paste them below. _If you do not provide this information, your issue will be automatically closed._**

`
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 98947d173e3f1667eba29c904f681047dea9de90
Installing requirements for Web UI
Error running install.py for extension extensions\sd_dreambooth_extension.
Command: "H:\AI\stable-diffusion-webui\venv\Scripts\python.exe" "extensions\sd_dreambooth_extension\install.py"
Error code: 1
stdout: Installing requirements for Dreambooth
Checking Dreambooth requirements.
Checking torch and torchvision versions

stderr: Traceback (most recent call last):
  File "H:\AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\install.py", line 27, in <module>
    run(f'"{sys.executable}" -m {torch_cmd}', "Checking torch and torchvision versions", "Couldn't install torch")
  File "H:\AI\stable-diffusion-webui\launch.py", line 34, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install torch.
Command: "H:\AI\stable-diffusion-webui\venv\Scripts\python.exe" -m "pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116"
Error code: 1
stdout: <empty>
stderr: H:\AI\stable-diffusion-webui\venv\Scripts\python.exe: Error while finding module specification for 'pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116' (ModuleNotFoundError: No module named 'pip install torch==1')

Launching Web UI with arguments: --ckptfix --xformers
Patching transformers to fix kwargs errors.
Dreambooth API layer loaded
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loading weights [d5eeebde] from H:\AI\stable-diffusion-webui\models\Stable-diffusion\berrymix test 2.ckpt
Applying xformers cross attention optimization.
Model loaded.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yes
**Have you updated Dreambooth to the latest revision?**
yes
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
yes
**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**

**Describe the bug**

runtime erro, cuda out of memory everytime i try to click the orange "train model" button. it tries for a few seconds, spits out a long list of errors and then just tells me "training finished. total lifetime steps 0"

**Provide logs**

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
CUDA SETUP: Loading binary H:\AI\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
Exception importing 8bit adam: argument of type 'WindowsPath' is not iterable
 Loaded dataset, moved vae and text encoder.
 Allocated: 0.2GB
 Reserved: 0.2GB

 Cached latents if selected, cleaned up VAE.
 Allocated: 0.2GB
 Reserved: 0.2GB

 Scheduler, EMA Loaded.
 Allocated: 3.8GB
 Reserved: 3.9GB

***** Running training *****
  Num examples = 314
  Num batches each epoch = 314
  Num Epochs = 4
  Instantaneous batch size per device = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Gradient Accumulation steps = 1
  Total optimization steps = 1000
   Training settings: CPU: False Adam: False, Prec: fp16, Prior: True, Grad: True, TextTr: True EM: False, LR: 1e-06
 Allocated: 3.8GB
 Reserved: 3.9GB

Steps:   0%|                                                                                  | 0/1000 [00:00<?, ?it/s] Exception while training: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 12.00 GiB total capacity; 11.12 GiB already allocated; 0 bytes free; 11.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 Allocated: 11.1GB
 Reserved: 11.3GB

Traceback (most recent call last):
  File "H:\AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1111, in main
    optimizer.step()
  File "H:\AI\stable-diffusion-webui\venv\lib\site-packages\accelerate\optimizer.py", line 134, in step
    self.scaler.step(self.optimizer, closure)
  File "H:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 338, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "H:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 285, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
  File "H:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\optim\lr_scheduler.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "H:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\optim\optimizer.py", line 113, in wrapper
    return func(*args, **kwargs)
  File "H:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "H:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\optim\adamw.py", line 148, in step
    state['exp_avg_sq'] = torch.zeros_like(p, memory_format=torch.preserve_format)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 12.00 GiB total capacity; 11.12 GiB already allocated; 0 bytes free; 11.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 Exception while training: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 12.00 GiB total capacity; 11.12 GiB already allocated; 0 bytes free; 11.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 Allocated: 11.1GB
 Reserved: 11.3GB

Traceback (most recent call last):
  File "H:\AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1047, in main
    for step, batch in enumerate(train_dataloader):
  File "H:\AI\stable-diffusion-webui\venv\lib\site-packages\accelerate\data_loader.py", line 383, in __iter__
    current_batch = send_to_device(current_batch, self.device)
  File "H:\AI\stable-diffusion-webui\venv\lib\site-packages\accelerate\utils\operations.py", line 130, in send_to_device
    return recursively_apply(_send_to_device, tensor, device, non_blocking, test_type=_has_to_method)
  File "H:\AI\stable-diffusion-webui\venv\lib\site-packages\accelerate\utils\operations.py", line 90, in recursively_apply
    {
  File "H:\AI\stable-diffusion-webui\venv\lib\site-packages\accelerate\utils\operations.py", line 91, in <dictcomp>
    k: recursively_apply(
  File "H:\AI\stable-diffusion-webui\venv\lib\site-packages\accelerate\utils\operations.py", line 98, in recursively_apply
    return func(data, *args, **kwargs)
  File "H:\AI\stable-diffusion-webui\venv\lib\site-packages\accelerate\utils\operations.py", line 123, in _send_to_device
    return t.to(device, non_blocking=non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 12.00 GiB total capacity; 11.12 GiB already allocated; 0 bytes free; 11.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 Exception while training: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 12.00 GiB total capacity; 11.12 GiB already allocated; 0 bytes free; 11.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 Allocated: 11.1GB
 Reserved: 11.3GB

Traceback (most recent call last):
  File "H:\AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1047, in main
    for step, batch in enumerate(train_dataloader):
  File "H:\AI\stable-diffusion-webui\venv\lib\site-packages\accelerate\data_loader.py", line 383, in __iter__
    current_batch = send_to_device(current_batch, self.device)
  File "H:\AI\stable-diffusion-webui\venv\lib\site-packages\accelerate\utils\operations.py", line 130, in send_to_device
    return recursively_apply(_send_to_device, tensor, device, non_blocking, test_type=_has_to_method)
  File "H:\AI\stable-diffusion-webui\venv\lib\site-packages\accelerate\utils\operations.py", line 90, in recursively_apply
    {
  File "H:\AI\stable-diffusion-webui\venv\lib\site-packages\accelerate\utils\operations.py", line 91, in <dictcomp>
    k: recursively_apply(
  File "H:\AI\stable-diffusion-webui\venv\lib\site-packages\accelerate\utils\operations.py", line 98, in recursively_apply
    return func(data, *args, **kwargs)
  File "H:\AI\stable-diffusion-webui\venv\lib\site-packages\accelerate\utils\operations.py", line 123, in _send_to_device
    return t.to(device, non_blocking=non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 12.00 GiB total capacity; 11.12 GiB already allocated; 0 bytes free; 11.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 Exception while training: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 12.00 GiB total capacity; 11.12 GiB already allocated; 0 bytes free; 11.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 Allocated: 11.1GB
 Reserved: 11.3GB

Traceback (most recent call last):
  File "H:\AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1047, in main
    for step, batch in enumerate(train_dataloader):
  File "H:\AI\stable-diffusion-webui\venv\lib\site-packages\accelerate\data_loader.py", line 383, in __iter__
    current_batch = send_to_device(current_batch, self.device)
  File "H:\AI\stable-diffusion-webui\venv\lib\site-packages\accelerate\utils\operations.py", line 130, in send_to_device
    return recursively_apply(_send_to_device, tensor, device, non_blocking, test_type=_has_to_method)
  File "H:\AI\stable-diffusion-webui\venv\lib\site-packages\accelerate\utils\operations.py", line 90, in recursively_apply
    {
  File "H:\AI\stable-diffusion-webui\venv\lib\site-packages\accelerate\utils\operations.py", line 91, in <dictcomp>
    k: recursively_apply(
  File "H:\AI\stable-diffusion-webui\venv\lib\site-packages\accelerate\utils\operations.py", line 98, in recursively_apply
    return func(data, *args, **kwargs)
  File "H:\AI\stable-diffusion-webui\venv\lib\site-packages\accelerate\utils\operations.py", line 123, in _send_to_device
    return t.to(device, non_blocking=non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 12.00 GiB total capacity; 11.12 GiB already allocated; 0 bytes free; 11.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 CLEANUP:
 Allocated: 11.1GB
 Reserved: 11.3GB

 Cleanup completed.
 Allocated: 11.1GB
 Reserved: 11.3GB

 Cleanup Complete.
 Allocated: 11.1GB
 Reserved: 11.3GB

Steps:   0%|                                                                                  | 0/1000 [00:19<?, ?it/s]
 Training completed, reloading SD Model.
 Allocated: 0.0GB
 Reserved: 7.6GB

Memory output: {'VRAM cleared.': '0.0,0.0', 'Cleanup completed.': '11.1,11.3', 'Loaded model.': '0.0,0.0', 'Loaded dataset, moved vae and text encoder.': '0.2,0.2', 'Cached latents if selected, cleaned up VAE.': '0.2,0.2', 'Scheduler, EMA Loaded.': '3.8,3.9', '  Training settings: CPU: False Adam: False, Prec: fp16, Prior: True, Grad: True, TextTr: True EM: False, LR: 1e-06': '3.8,3.9', 'Exception while training: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 12.00 GiB total capacity; 11.12 GiB already allocated; 0 bytes free; 11.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF': '11.1,11.3', 'CLEANUP: ': '11.1,11.3', 'Cleanup Complete.': '11.1,11.3', 'Training completed, reloading SD Model.': '0.0,7.6'}
Re-applying optimizations...
Returning result: Training finished. Total lifetime steps: 0

**Environment**

What OS?
windows 10
If Windows - WSL or native?
native
What GPU are you using?
rtx 3060 gainward pegasus 12gb https://www.gainward.com/main/vgapro.php?id=1108&lang
**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the db_config.json file from /models/dreambooth/MODELNAME/db_config.json

**Comment by Yeecy-sketch** [comment]
I am also experiencing this on my Geforce RTX 3060 GAMING OC 12G on Debian 11.
Uploaded my log to paste.ee if needed: https://paste.ee/p/WL6ER
Only options i changed apart from *Instance prompt*, *Dataset Directory* and *Class prompt* is *Mixed Precision* to *fp16* and *Use 8 bit Adam* to *True*

**Comment by d8ahazard** [comment]
Relaunch the webUI again. If this fails, take a look at the example webui-user-dreambooth.bat file for how to force the CUDA version.

**Comment by Yeecy-sketch** [comment]
Hi, I attempted to force the CUDA version on a fresh install of the WebUI, This time it did report this in the startup:
*[\*] Torch version is 1.12.1+cu116.*
*[\*] Torch vision version is 0.13.1+cu116.*

It still runs into *RuntimeError: CUDA out of memory.* After a few seconds.
Logs: https://paste.ee/p/mwY3u

**Comment by d8ahazard** [comment]
For a 12GB GPU, you need 8Bit Adam, xformers, fp16 precision, and possibly to disable text encoder and EMA training as well. You could also try the fancy new flash_attention memory which doesn't require xformers.

**Comment by Kittingsl** [comment]
> Relaunch the webUI again. If this fails, take a look at the example webui-user-dreambooth.bat file for how to force the CUDA version.

my webui-user-dreambooth.bat file doesnt say anything about how to force the cuda version. it just has the info on how to get torch and torchvision

**@echo off**

**set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=
set "TORCH_COMMAND=pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116"
set "REQS_FILE=.\extensions\sd_dreambooth_extension\requirements.txt"
:: Uncomment below to skip trying to install automatically on launch.
:: set "DREAMBOOTH_SKIP_INSTALL=True"**

**call webui.bat**

this is all that is in the webui dreambooth bat and i havent found any other file named like that in the extensions folder

**Comment by Kittingsl** [comment]
my bad i didnt know that buton closes this thread like that im still somewhat new to github

**Comment by Yeecy-sketch** [comment]
> For a 12GB GPU, you need 8Bit Adam, xformers, fp16 precision, and possibly to disable text encoder and EMA training as well. You could also try the fancy new flash_attention memory which doesn't require xformers.

it works using the options with the *flash_attention* memory. Thank you!

**Comment by d8ahazard** [comment]
Could you kindly share your entire config that you used to get it to work?
I will incorporate that into the wizard.

**Comment by Yeecy-sketch** [comment]
I changed (Other than the *instance Prompt*, *Dataset Directory*, *Class Prompt*, *Classification Dataset Directory* and *Total Number of Class/Reg Images*):
Train Text Encoder: false
Memory Attention: flash_attention
Use 8-bit Adam: true
Mixed Precision: fp16

Uploaded the config also file as txt (if needed):
[db_config.txt](https://github.com/d8ahazard/sd_dreambooth_extension/files/10071673/db_config.txt)

**Comment by CypherQube** [comment]
> I changed (Other than the _instance Prompt_, _Dataset Directory_, _Class Prompt_, _Classification Dataset Directory_ and _Total Number of Class/Reg Images_): Train Text Encoder: false Memory Attention: flash_attention Use 8-bit Adam: true Mixed Precision: fp16
> 
> Uploaded the config file also as txt (if needed): [db_config.txt](https://github.com/d8ahazard/sd_dreambooth_extension/files/10071673/db_config.txt)

I was having issues on my 3060 until I unchecked "don't cache latents" I kept train text encoder on & it worked. Note: I still used 8-bit Adam, fp16 & used --xformers argument. I haven't tried flash_attention_memory. My point is though I would always get errors if "don't cache latents" was checked

**Comment by CypherQube** [comment]
> For a 12GB GPU, you need 8Bit Adam, xformers, fp16 precision, and possibly to disable text encoder and EMA training as well. You could also try the fancy new flash_attention memory which doesn't require xformers.

Just curious could you use both xformers & flash_attention_memory?

**Comment by d8ahazard** [comment]
I've adjusted the built-in wizard to try and reflect these settings, can anybody give it a try and let me know how it works?

**Comment by d8ahazard** [comment]
> File "C:\Users\digic\SuperSD\stable-diffusion-webui\modules\safe.py", line 62, in find_class
> raise Exception(f"global '{module}/{name}' is forbidden")
> Exception: global 'torch/BFloat16Storage' is forbidden

FWIW, it'd help both of us a lot if you did open a separate issue and fill out the logs. Bonus points for sharing your training params or config, as I can then see what you've got enabled and disabled and make an educated guess as to what's changed.

If I had to guess without seeing any of this useful info, I'd wager it's probably the addition of training EMA? IDK.

The bf16 issue is technically the fault of the main WebUI, as it's got a "safe pickle" module that likes to bitch if it encounters anything not used by the main UI. YoloV5 models, for example, or in your case, torc/BFloat16Storage. 

I've never bothered trying bf16 because I thought it was only on Ampere GPUs or something like that, but if it's better than FP16, I can definitely look into how to properly fix the issue...if it were an official issue. ;)

Also, it could be one of two things - either I need to add my own extension to the safe_pickle call that allows bf16, or don't pass bf16 to the bit that builds the final checkpoint. Another point where the full log would be helpful.


Last - as we now *know* that we can train without OOM on 12GB cards and since I haven't heard anything from @Kittingsl in a few days, I'm going to close this so I can focus on other current issues. OP can re-open or create a new issue if they need further assistance.

**Comment by chakalakasp** [comment]
Hey, all hail the pickle jar, it helps keep the malware at bay :)

A Reddit thread re: bf16, BTW — https://www.reddit.com/r/MachineLearning/comments/vndtn8/d_mixed_precision_training_difference_between/
