### ISSUE TITLE
You have passed a non-standard module None. We cannot verify whether it has the correct type

### ISSUE THREAD

**Issue by daanpol** [d8ahazard/sd_dreambooth_extension#29]
I have installed Dreambooth with all the requirements into Automatic1111's folder by using the Extensions. 

After creating a model and setting everything up according to the manual I get this error:

Starting Dreambooth training...
 VRAM cleared.
 Allocated: 0.9GB
 Reserved: 0.9GB

You have passed a non-standard module None. We cannot verify whether it has the correct type
{'freq_shift', 'downsample_padding', 'block_out_channels', 'norm_num_groups', 'act_fn', 'out_channels', 'sample_size', 'mid_block_scale_factor', 'attention_head_dim', 'flip_sin_to_cos', 'down_block_types', 'in_channels', 'cross_attention_dim', 'center_input_sample', 'up_block_types', 'layers_per_block', 'norm_eps'} was not found in config. Values will be initialized to default values.
Error completing request
Arguments: ('dcmpol', 'C:\\Users\\daanp\\OneDrive\\Desktop\\DreamBooth\\Image files\\dcmpol\\processed 512', '', 'a photo of a man dcmpol', 'a photo of a man', 'a portrait of dcmpol, 35mm , magic hour', '', 1.0, 7.5, 40.0, 180, 512, False, True, 1, 1, 1, 1800, 1, True, 5e-06, False, 'constant', 0, True, 0.9, 0.999, 0.01, 1e-08, 1, 300, 3000, 'fp16', True, '', False) {}
Traceback (most recent call last):
  File "C:\Users\daanp\OneDrive\Desktop\SUPER SD 2.0 Dependencies\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\daanp\OneDrive\Desktop\SUPER SD 2.0 Dependencies\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "C:\Users\daanp\OneDrive\Desktop\SUPER SD 2.0 Dependencies\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 256, in start_training
    trained_steps = main(config)
  File "C:\Users\daanp\OneDrive\Desktop\SUPER SD 2.0 Dependencies\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 486, in main
    pipeline = StableDiffusionPipeline.from_pretrained(
  File "C:\Users\daanp\OneDrive\Desktop\SUPER SD 2.0 Dependencies\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipeline_utils.py", line 383, in from_pretrained
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "C:\Users\daanp\OneDrive\Desktop\SUPER SD 2.0 Dependencies\stable-diffusion-webui\venv\lib\site-packages\diffusers\modeling_utils.py", line 301, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named diffusion_pytorch_model.bin found in directory C:\Users\daanp\OneDrive\Desktop\SUPER SD 2.0 Dependencies\stable-diffusion-webui\models\dreambooth\dcmpol\working\safety_checker.

How can I fix this?

**Comment by d8ahazard** [comment]
> C:\Users\daanp\OneDrive\Desktop\SUPER SD 2.0 Dependencies\stable-diffusion-webui\models\dreambooth\dcmpol\working\safety_checker

Have you restarted the webUI after installation? There is an install script that runs and bumps the versions of some of the required packages - presently, this doesn't happen automagically. Try restarting the webUI and try again, please.

**Comment by daanpol** [comment]
I did and I get this on startup:

Already up to date.
venv "C:\Stable Diffusion\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Commit hash: ac085628540d0ec6a988fad93f5b8f2154209571
Installing requirements for Web UI
Error running install.py for extension sd_dreambooth_extension.
Command: "C:\Stable Diffusion\stable-diffusion-webui\venv\Scripts\python.exe" "extensions\sd_dreambooth_extension\install.py"
Error code: 1
stdout: Installing requirements for Dreambooth

stderr: Traceback (most recent call last):
  File "C:\Stable Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\install.py", line 9, in <module>
    run_pip(f"install -r {reqs}", "requirements for Dreambooth")
  File "C:\Stable Diffusion\stable-diffusion-webui\launch.py", line 63, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "C:\Stable Diffusion\stable-diffusion-webui\launch.py", line 34, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install requirements for Dreambooth.
Command: "C:\Stable Diffusion\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install -r C:\Stable Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt --prefer-binary
Error code: 1
stdout: <empty>
stderr: ERROR: Invalid requirement: 'Diffusion\\stable-diffusion-webui\\extensions\\sd_dreambooth_extension\\requirements.txt'
Hint: It looks like a path. File 'Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt' does not exist.




Launching Web UI with arguments: --api --port 32400 --cors-allow-origins=https://www.painthua.com --theme=dark --xformers --force-enable-xformers --opt-split-attention
Error loading script: main.py
Traceback (most recent call last):
  File "C:\Stable Diffusion\stable-diffusion-webui\modules\scripts.py", line 170, in load_scripts
    exec(compiled, module.__dict__)
  File "C:\Stable Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py", line 3, in <module>
    from dreambooth import conversion, dreambooth
  File "C:\Stable Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\conversion.py", line 26, in <module>
    from dreambooth.dreambooth import get_db_models
  File "C:\Stable Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 10, in <module>
    from dreambooth.train_dreambooth import main
  File "C:\Stable Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 20, in <module>
    from accelerate import Accelerator
ModuleNotFoundError: No module named 'accelerate'

LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loading weights [81761151] from C:\Stable Diffusion\stable-diffusion-webui\models\Stable-diffusion\v1-5-pruned-emaonly.ckpt
Global Step: 840000
Applying xformers cross attention optimization.
Model loaded.
Loaded a total of 0 textual inversion embeddings.
Embeddings:
Running on local URL:  http://127.0.0.1:32400

To create a public link, set `share=True` in `launch()`.

**Comment by daanpol** [comment]
I seem to have found the issue. If there is any space in your installation folders, dreambooth will not be able to install it's own dependencies. It also gave me an error related to the wrong cuda version being used for pytorch. Fixed it with this command: conda install pytorch torchvision cudatoolkit=10.2 -c pytorch
