### ISSUE TITLE
ImportError: cannot import name 'is_xformers_available' from 'diffusers.utils.import_utils' (/usr/local/lib/python3.7/dist-packages/diffusers/utils/import_utils.py)

### ISSUE THREAD

**Issue by OccultMC** [d8ahazard/sd_dreambooth_extension#293]
## Kindly read this ENTIRE form and fill it out with the requested information. It may seem tedious, but it's even more tedious asking basic questions to ensure I'm not trying to troubleshoot a bug I've already fixed. Help me help you, answer all the questions and follow the steps below before posting.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your issue will be automatically closed._**

Error loading script: api.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    compiled = compile(text, path, 'exec')
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/api.py", line 14
    db_half_model: bool = False,
                               ^
SyntaxError: invalid syntax

Error loading script: main.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 3, in <module>
    from extensions.sd_dreambooth_extension.dreambooth import conversion, dreambooth
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/conversion.py", line 27, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.dreambooth import get_db_models, printm
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dreambooth.py", line 14, in <module>
    from diffusers.utils.import_utils import is_xformers_available
ImportError: cannot import name 'is_xformers_available' from 'diffusers.utils.import_utils' (/usr/local/lib/python3.7/dist-packages/diffusers/utils/import_utils.py)

`
Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Commit hash: idk what this is
Installing requirements for Web UI
Skipping dreambooth installation.
Dreambooth revision is ****************************************
Diffusers version is *.*.*.
Torch version is *.*.*.
Torch vision version is *.*.*.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**

**Have you updated Dreambooth to the latest revision?**
Yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**

OK

**Describe the bug

See Above, that's as much as I have.
I just pulled the latest about 5 mins ago

(A clear and concise description of what the bug is)

**Provide logs**

Error loading script: api.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    compiled = compile(text, path, 'exec')
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/api.py", line 14
    db_half_model: bool = False,
                               ^
SyntaxError: invalid syntax

Error loading script: main.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 3, in <module>
    from extensions.sd_dreambooth_extension.dreambooth import conversion, dreambooth
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/conversion.py", line 27, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.dreambooth import get_db_models, printm
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dreambooth.py", line 14, in <module>
    from diffusers.utils.import_utils import is_xformers_available
ImportError: cannot import name 'is_xformers_available' from 'diffusers.utils.import_utils' (/usr/local/lib/python3.7/dist-packages/diffusers/utils/import_utils.py)

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

**Environment**

What OS?
Colab 
If Windows - WSL or native?

What GPU are you using?

v100

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the db_config.json file from /models/dreambooth/MODELNAME/db_config.json

**Comment by sgsdxzy** [comment]
> `Python 3.9.12 (main, Apr 4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)] Commit hash: idk what this is Installing requirements for Web UI Skipping dreambooth installation. Dreambooth revision is **************************************** Diffusers version is *.*.*. Torch version is *.*.*. Torch vision version is *.*.*.`

Don't just ignore it, it is the most important part.
You should be getting logs like
![image](https://user-images.githubusercontent.com/1655353/203240415-729702c5-fed8-45d5-ae25-3eb715e624fd.png)
Try to find these versions, or we can't know what is happening.

**Comment by OccultMC** [comment]
Where can I find this?

**Comment by sgsdxzy** [comment]
I don't know how Colab works, but it should be in your stdout/stderr, and console output. If Colab doesn't provide console, you may need to find how to direct Colab stdout to a file.

**Comment by d8ahazard** [comment]
> Python 3.9.12 (main, Apr 4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)] Commit hash: idk what this is Installing requirements for Web UI Skipping dreambooth installation. Dreambooth revision is **************************************** Diffusers version is *.*.*. Torch version is *.*.*. Torch vision version is *.*.*.

It should be at the top of your console output in collab when you start running it. Most likely, you need to set the requirements file in webui-user.sh so that it installs the right diffusers/transformers versions on first launch, or re-launch the webui.

**Comment by FedericoCampe8** [comment]
I have the same issue and this is my output
`Error loading script: api.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    compiled = compile(text, path, 'exec')
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/api.py", line 14
    db_half_model: bool = False,
                               ^
SyntaxError: invalid syntax

Error loading script: main.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 3, in <module>
    from extensions.sd_dreambooth_extension.dreambooth import conversion, dreambooth
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/conversion.py", line 27, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.dreambooth import get_db_models, printm
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dreambooth.py", line 14, in <module>
    from diffusers.utils.import_utils import is_xformers_available
ImportError: cannot import name 'is_xformers_available' from 'diffusers.utils.import_utils' (/usr/local/lib/python3.7/dist-packages/diffusers/utils/import_utils.py)
`

**Comment by laplace-daemon** [comment]
I'm getting the same `is_xformers_available` error.

**Comment by d8ahazard** [comment]
Fixed with 56d3815
