### ISSUE TITLE
Exception when enable "Pad Tokens" and disable "Don't Cache Latents"

### ISSUE THREAD

**Issue by db9e36e7** [d8ahazard/sd_dreambooth_extension#302]
commit c589a3596ade64228de8a7851f50c2470c7a76aa

Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "D:\stable-diffusion-webui\webui.py", line 57, in f
    res = func(*args, **kwargs)
  File "D:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 527, in start_training
    config, mem_record = main(config, mem_record)
  File "D:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 927, in main
    train_dataset, train_dataloader = cache_latents(False, vae)
  File "D:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 915, in cache_latents
    text_encoder_cache.append(text_encoder(d_batch["input_ids"])[0])
  File "D:\stable-diffusion-webui\venv\Lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\stable-diffusion-webui\venv\Lib\site-packages\transformers\models\clip\modeling_clip.py", line 728, in forward
    return self.text_model(
  File "D:\stable-diffusion-webui\venv\Lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\stable-diffusion-webui\venv\Lib\site-packages\transformers\models\clip\modeling_clip.py", line 638, in forward
    bsz, seq_len = input_shape
ValueError: too many values to unpack (expected 2)

**Comment by sgsdxzy** [comment]
Having the same issue.
I can confirm 83ed4599e4c44e6919430a0b6edf160d04e8e662 is working correctly, so probably 340657300b8ce1fb40a02a4ffc87759346fec206 introduced the bug.

**Comment by d8ahazard** [comment]
> Having the same issue. I can confirm [83ed459](https://github.com/d8ahazard/sd_dreambooth_extension/commit/83ed4599e4c44e6919430a0b6edf160d04e8e662) is working correctly, so probably [3406573](https://github.com/d8ahazard/sd_dreambooth_extension/commit/340657300b8ce1fb40a02a4ffc87759346fec206) introduced the bug.

It'll be a non-issue whenever I drop the next release.

Working on completely re-doing the concepts inputs as well as creating a new dataloader that not only handles multiple concepts separately, but also ensures we will be able to add resolution bucketing int he future.

But, when the new dataloader is released, the whole "shuffle after epoch" thing will be removed, as the data will more or less be continuously shuffled as it is fetched or cached.

**Comment by d8ahazard** [comment]
Give it a go now, I've released the new dataloader. Might not fix the problem, but at the very least, I know how to debug it now. ;)

**Comment by d8ahazard** [comment]
This is resolved.
