### ISSUE TITLE
No module named 'accelerate'

### ISSUE THREAD

**Issue by shelly-luo** [d8ahazard/sd_dreambooth_extension#305]
Have you read the Readme?

yes

Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?

yes

Have you updated Dreambooth to the latest revision?

yes

Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth

and i have not the dreambooth tab

Provide logs
If a crash has occurred, please provide the entire stack trace from the log, including the last few log messages before the crash occurred.

Environment
MAC OS

What GPU are you using?
Apple M1

Requirement already satisfied: accelerate in ./miniforge3/lib/python3.10/site-packages (0.14.0)
Requirement already satisfied: pyyaml in ./miniforge3/lib/python3.10/site-packages (from accelerate) (6.0)
Requirement already satisfied: numpy>=1.17 in ./miniforge3/lib/python3.10/site-packages (from accelerate) (1.23.4)
Requirement already satisfied: torch>=1.4.0 in ./miniforge3/lib/python3.10/site-packages (from accelerate) (1.13.0)
Requirement already satisfied: psutil in ./miniforge3/lib/python3.10/site-packages (from accelerate) (5.9.4)
Requirement already satisfied: packaging>=20.0 in ./miniforge3/lib/python3.10/site-packages (from accelerate) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in ./miniforge3/lib/python3.10/site-packages (from packaging>=20.0->accelerate) (3.0.9)
Requirement already satisfied: typing-extensions in ./miniforge3/lib/python3.10/site-packages (from torch>=1.4.0->accelerate) (4.4.0)

Error loading script: api.py
Traceback (most recent call last):
  File "/Volumes/home/Drive/AI/M1/stable-diffusion-webui/modules/scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/Volumes/home/Drive/AI/M1/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/Volumes/home/Drive/AI/M1/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/api.py", line 9, in <module>
    from extensions.sd_dreambooth_extension.dreambooth import conversion, dreambooth
  File "/Volumes/home/Drive/AI/M1/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/conversion.py", line 27, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.dreambooth import get_db_models, printm
  File "/Volumes/home/Drive/AI/M1/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dreambooth.py", line 12, in <module>
    from accelerate.logging import get_logger
ModuleNotFoundError: No module named 'accelerate'

Error loading script: main.py
Traceback (most recent call last):
  File "/Volumes/home/Drive/AI/M1/stable-diffusion-webui/modules/scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/Volumes/home/Drive/AI/M1/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/Volumes/home/Drive/AI/M1/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 3, in <module>
    from extensions.sd_dreambooth_extension.dreambooth import conversion, dreambooth
  File "/Volumes/home/Drive/AI/M1/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/conversion.py", line 27, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.dreambooth import get_db_models, printm
  File "/Volumes/home/Drive/AI/M1/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dreambooth.py", line 12, in <module>
    from accelerate.logging import get_logger
ModuleNotFoundError: No module named 'accelerate'

**Comment by d8ahazard** [comment]
You need to restart your webUI and ensure it's on the latest version.
