### ISSUE TITLE
PIL.UnidentifiedImageError: cannot identify image file '/home/stable/stable-diffusion-webui/requirements_versions.txt'

### ISSUE THREAD

**Issue by entmike** [d8ahazard/sd_dreambooth_extension#31]
If you do not (or forget to) set a **Classification dataset directory** (which says optional), after the classification images are generated, the training routine will fail (presumably because the directory was not set):

```
Traceback (most recent call last):
  File "/home/stable/stable-diffusion-webui/modules/ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "/home/stable/stable-diffusion-webui/webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "/home/stable/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dreambooth.py", line 256, in start_training
    trained_steps = main(config)
  File "/home/stable/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 719, in main
    for step, batch in enumerate(train_dataloader):
  File "/home/stable/stable-diffusion-webui/venv/lib/python3.8/site-packages/accelerate/data_loader.py", line 357, in __iter__
    next_batch = next(dataloader_iter)
  File "/home/stable/stable-diffusion-webui/venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/home/stable/stable-diffusion-webui/venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/stable/stable-diffusion-webui/venv/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/stable/stable-diffusion-webui/venv/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/stable/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 360, in __getitem__
    class_image = Image.open(class_path)
  File "/home/stable/stable-diffusion-webui/venv/lib/python3.8/site-packages/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file '/home/stable/stable-diffusion-webui/requirements_versions.txt'
```

Should/would it be possible to default this value to something?  I can work around it now that I know that the 2 parameters together are required, but currently it might be seen as a bit unintuitive/confusing.

**Comment by d8ahazard** [comment]
Good catch. Fixed with 0eb3f73.
