### ISSUE TITLE
Issue with pruned model checkpoints

### ISSUE THREAD

**Issue by ye7iaserag** [d8ahazard/sd_dreambooth_extension#322]
Whenever I start training with a `pruned` model checkpoint, I get the following error 

```
 Traceback (most recent call last):
   File "/app/modules/ui.py", line 185, in f
     res = list(func(*args, **kwargs))
   File "/app/webui.py", line 57, in f
     res = func(*args, **kwargs)
   File "/app/extensions/sd_dreambooth_extension/dreambooth/dreambooth.py", line 527, in start_training
     config, mem_record = main(config, mem_record)
   File "/app/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 650, in main
     vae=AutoencoderKL.from_pretrained(
   File "/usr/local/lib/python3.10/site-packages/diffusers/modeling_utils.py", line 471, in from_pretrained
     for param_name, param in state_dict.items():
 AttributeError: 'NoneType' object has no attribute 'items'
```

I set `Total Number of Class/Reg Images` to zero to avoid this issue with diffusers
But then I get the same error with transformers

```
Traceback (most recent call last):
  File "/app/modules/ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "/app/webui.py", line 57, in f
    res = func(*args, **kwargs)
  File "/app/extensions/sd_dreambooth_extension/dreambooth/dreambooth.py", line 527, in start_training
    config, mem_record = main(config, mem_record)
  File "/app/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 728, in main
    text_encoder = CLIPTextModel.from_pretrained(
 File "/usr/local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2088, in from_pretrained
s   loaded_state_dict_keys = [k for k in state_dict.keys()]
AttributeError: 'NoneType' object has no attribute 'keys'
```

- It might be an issue with models that were converted from pruned checkpoints and those do not have `state_dict`.
- It might be something wrong that happenes in the conversion process.

Now I do not know what actually happens in the `pruning` process or what get cleaned from the model but when I copied the contents from stable diffusion 1.5 pytorch model to the `working` folder the error stopped showing

Btw, I have latest webui and dreambooth versions.
Also this seems related to https://github.com/d8ahazard/sd_dreambooth_extension/issues/82 somehow

**Comment by ye7iaserag** [comment]
Suddenly started to work normally... even on pruned checkpoints closing the issue
