### ISSUE TITLE
RTX 3080 10GB Out of memory when trying to train a new model

### ISSUE THREAD

**Issue by MrMarble** [d8ahazard/sd_dreambooth_extension#326]
**Please find the following lines in the console and paste them below. _If you do not provide this information, your issue will be automatically closed._**

```
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 828438b4a190759807f9054932cae3a8b880ddf1
Installing requirements for Web UI
Dreambooth revision is c589a3596ade64228de8a7851f50c2470c7a76aa
Args: ['extensions\\sd_dreambooth_extension\\install.py']
[*] Diffusers version is 0.7.2.
[*] Torch version is 1.12.1+cu116.
[*] Torch vision version is 0.13.1+cu116.
[*] Transformers version is 4.21.0.
[*] Xformers
```

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes
**Have you updated Dreambooth to the latest revision?**
Yes
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**

Ok. I just downloaded it for the first time, should be updated

**Describe the bug**

I'm trying to train my own model using some photos of my wife. I created the model following the README and then tried to train it but it crashes.

I tried the default configuration without Adam8, no mixed precision and memory attention default, I also tried with xformers without luck.
Copied this settings https://github.com/d8ahazard/sd_dreambooth_extension/issues/287#issuecomment-1324349822 but nothing

Always get the same error: `RuntimeError: CUDA out of memory. Tried to allocate 38.00 MiB (GPU 0; 10.00 GiB total capacity; 9.16 GiB already allocated; 0 bytes free; 9.26 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

**Provide logs**

```
Starting Dreambooth training...
 VRAM cleared.
 Allocated: 0.0GB
 Reserved: 0.0GB

Replace CrossAttention.forward to use FlashAttention
 Loaded model.
 Allocated: 0.0GB
 Reserved: 0.0GB


===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA SETUP: Loading binary F:\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
 Cleanup completed.
 Allocated: 0.2GB
 Reserved: 0.2GB

 Scheduler, EMA Loaded.
 Allocated: 3.8GB
 Reserved: 3.9GB

***** Running training *****
  Num examples = 22
  Num batches each epoch = 22
  Num Epochs = 100
  Shuffle After Epoch = False
  Instantaneous batch size per device = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Gradient Accumulation steps = 1
  Total optimization steps = 2200
   Training settings: CPU: False Adam: True, Prec: fp16, Prior: False, Grad: True, TextTr: True EM: False, LR: 1.72e-06
 Allocated: 3.8GB
 Reserved: 3.9GB

Steps:   0%|                                                                                  | 0/2200 [00:00<?, ?it/s] Exception while training: CUDA out of memory. Tried to allocate 38.00 MiB (GPU 0; 10.00 GiB total capacity; 9.16 GiB already allocated; 0 bytes free; 9.26 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 Allocated: 9.2GB
 Reserved: 9.3GB

Traceback (most recent call last):
  File "F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1179, in main
    optimizer.step()
  File "F:\stable-diffusion-webui\venv\lib\site-packages\accelerate\optimizer.py", line 134, in step
    self.scaler.step(self.optimizer, closure)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 338, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 285, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\torch\optim\lr_scheduler.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\torch\optim\optimizer.py", line 113, in wrapper
    return func(*args, **kwargs)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\optim\optimizer.py", line 263, in step
    self.init_state(group, p, gindex, pindex)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\optim\optimizer.py", line 393, in init_state
    state["state1"] = torch.zeros_like(
RuntimeError: CUDA out of memory. Tried to allocate 38.00 MiB (GPU 0; 10.00 GiB total capacity; 9.16 GiB already allocated; 0 bytes free; 9.26 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 CLEANUP:
 Allocated: 9.2GB
 Reserved: 9.3GB

 Cleanup completed.
 Allocated: 9.2GB
 Reserved: 9.3GB

 Cleanup Complete.
 Allocated: 9.2GB
 Reserved: 9.3GB

Steps:   0%|                                                                                  | 0/2200 [00:09<?, ?it/s]
 Training completed, reloading SD Model.
 Allocated: 0.0GB
 Reserved: 7.5GB

Memory output: {'VRAM cleared.': '0.0/0.0GB', 'Loaded model.': '0.0/0.0GB', 'Cleanup completed.': '9.2/9.3GB', 'Scheduler, EMA Loaded.': '3.8/3.9GB', '  Training settings: CPU: False Adam: True, Prec: fp16, Prior: False, Grad: True, TextTr: True EM: False, LR: 1.72e-06': '3.8/3.9GB', 'Exception while training: CUDA out of memory. Tried to allocate 38.00 MiB (GPU 0; 10.00 GiB total capacity; 9.16 GiB already allocated; 0 bytes free; 9.26 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF': '9.2/9.3GB', 'CLEANUP: ': '9.2/9.3GB', 'Cleanup Complete.': '9.2/9.3GB', 'Training completed, reloading SD Model.': '0.0/7.5GB'}
Re-applying optimizations...
Returning result: Training finished. Total lifetime steps: 0
```

**Environment**

Windows 11

If Windows - WSL or native?
Native

What GPU are you using?
RTX 3080 FE 10GB
**Screenshots/Config**
```json
{
    "max_token_length": "75",
    "model_dir": "F:\\stable-diffusion-webui\\models\\dreambooth\\Susana",
    "pretrained_model_name_or_path": "F:\\stable-diffusion-webui\\models\\dreambooth\\Susana\\working",
    "class_guidance_scale": 7.5,
    "class_negative_prompt": "",
    "class_infer_steps": 40,
    "use_concepts": false,
    "half_model": true,
    "file_prompt_contents": "Description",
    "instance_token": "",
    "class_token": "",
    "shuffle_after_epoch": false,
    "db_attention": "default",
    "model_name": "Susana",
    "scheduler": "ddim",
    "src": "sd-v1-4.ckpt [7460a6fa]",
    "total_steps": 0,
    "revision": 0,
    "pretrained_vae_name_or_path": null,
    "instance_data_dir": "F:\\stable-diffusion-webui\\training\\susana",
    "class_data_dir": "",
    "instance_prompt": "photo of susana",
    "class_prompt": "photo of a woman",
    "save_sample_prompt": "",
    "save_sample_negative_prompt": "",
    "n_save_sample": 1,
    "seed": 0,
    "save_guidance_scale": 7.5,
    "save_infer_steps": 40,
    "with_prior_preservation": false,
    "num_class_images": 0,
    "output_dir": "F:\\stable-diffusion-webui\\models\\dreambooth\\Susana",
    "resolution": 512,
    "center_crop": false,
    "train_text_encoder": true,
    "train_batch_size": 1,
    "sample_batch_size": 1,
    "num_train_epochs": 1,
    "max_train_steps": 2200,
    "gradient_accumulation_steps": 1,
    "gradient_checkpointing": true,
    "learning_rate": 1.72e-06,
    "scale_lr": false,
    "lr_scheduler": "constant",
    "lr_warmup_steps": 0,
    "attention": "flash_attention",
    "use_8bit_adam": true,
    "adam_beta1": 0.9,
    "adam_beta2": 0.999,
    "adam_weight_decay": 0.01,
    "adam_epsilon": 1e-08,
    "max_grad_norm": 1,
    "save_preview_every": 500,
    "save_embedding_every": 500,
    "mixed_precision": "fp16",
    "not_cache_latents": true,
    "concepts_list": [
        {
            "instance_prompt": "photo of susana",
            "class_prompt": "photo of a woman",
            "instance_data_dir": "F:\\stable-diffusion-webui\\training\\susana",
            "class_data_dir": "F:\\stable-diffusion-webui\\models\\dreambooth\\Susana\\classifiers_concept_0",
            "instance_token": "",
            "class_token": ""
        }
    ],
    "use_cpu": false,
    "pad_tokens": true,
    "hflip": true,
    "use_ema": false,
    "prior_loss_weight": 1
}
```

**Comment by leppie** [comment]
> TextTr: True

That is never going to work on a 10GB GPU, believe me, I have tried.

**Comment by MrMarble** [comment]
> > TextTr: True
> 
> That is never going to work on a 10GB GPU, believe me, I have tried. 

That was it! Man I've changed everything else but that...
Disabling `Train text encoder` made it work, I'm able to train my model, thank you!

**Comment by d8ahazard** [comment]
@MrMarble With the latest version, I've updated the "performance wizard" so that it tries to set the proper settings for a 10GB GPU. 

Can you please try it out if you have a moment and let me know if it sets the proper params, or if I need to adjust something?

**Comment by MrMarble** [comment]
> @MrMarble With the latest version, I've updated the "performance wizard" so that it tries to set the proper settings for a 10GB GPU. 
> 
> Can you please try it out if you have a moment and let me know if it sets the proper params, or if I need to adjust something?

Sure! Give me a couple of minutes and I'll try

**Comment by ExponentialML** [comment]
@MrMarble 
https://github.com/d8ahazard/sd_dreambooth_extension/blob/0ec2d8e3a1fa70691a1a3d6f6d6f9890a804405c/dreambooth/dreambooth.py#L342

Simply replace the `_` with `clip_input=None`
Should work thereafter.
