### ISSUE TITLE
Broken with latest commits due to arguments qty

### ISSUE THREAD

**Issue by dx777** [d8ahazard/sd_dreambooth_extension#33]
Since Pad tokens and horizontal flip was added, number of arguments is now more, then expected:
```

2022-11-08T17:33:57.993890639Z Arguments: ('shivamOrangeBag', '/workspace/input/', '', 'photo of a sks bag', 'photo of a bag', '', '', 1.0, 7.5, 40.0, 0, 512, False, True, 1, 4, 1, 300, 1, True, 5e-06, False, 'constant', 0, False, 0.9, 0.999, 0.01, 1e-08, 1, 100, 0, 'no', True, '', False, True, True) {}
2022-11-08T17:33:57.994184812Z Traceback (most recent call last):
2022-11-08T17:33:57.994203030Z   File "/workspace/stable-diffusion-webui/modules/ui.py", line 185, in f
2022-11-08T17:33:57.994213769Z     res = list(func(*args, **kwargs))
2022-11-08T17:33:57.994222961Z   File "/workspace/stable-diffusion-webui/webui.py", line 55, in f
2022-11-08T17:33:57.994232061Z     res = func(*args, **kwargs)
2022-11-08T17:33:57.994240759Z TypeError: start_training() takes 36 positional arguments but 38 were given
```

**Comment by entmike** [comment]
I think this commit fixed it.  https://github.com/d8ahazard/sd_dreambooth_extension/commit/afef533adb8df5723a39e5263aa8c8674e81a796

**Comment by Jonseed** [comment]
I'm on the latest commit (262cebaa25c51486b400f2890ebc8e3f646d8707) and I still see this error.

**Comment by Jonseed** [comment]
Do I need to recreate the model?

**Comment by Jonseed** [comment]
Oh, I just had to restart the server. No more error.
