### ISSUE TITLE
TypeError: dumb_safety() got an unexpected keyword argument 'clip_input'

### ISSUE THREAD

**Issue by zakinp** [d8ahazard/sd_dreambooth_extension#344]
**I got this problem when using dreambooth extension:**

Error completing request
Arguments: ('naifix',) {}
Traceback (most recent call last):
  File "/root/autodl-tmp/stable-diffusion-webui/modules/ui.py", line 169, in f
    res = list(func(*args, **kwargs))
  File "/root/autodl-tmp/stable-diffusion-webui/webui.py", line 58, in f
    res = func(*args, **kwargs)
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 598, in f
    res = func(*args, **kwargs)
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dreambooth.py", line 491, in start_training
    config, mem_record = main(config, mem_record)
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 528, in main
    images = concept_pipeline(example["prompt"], num_inference_steps=concept.class_infer_steps,
  File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 523, in __call__
    image, has_nsfw_concept = self.run_safety_checker(image, device, text_embeddings.dtype)
  File "/root/miniconda3/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 324, in run_safety_checker
    image, has_nsfw_concept = self.safety_checker(
TypeError: dumb_safety() got an unexpected keyword argument 'clip_input'

  0%|                                                                                                                                                                                     | 0/190 [00:26<?, ?it/s]
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/blocks.py", line 983, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/blocks.py", line 913, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range

The version of webui and dreambooth extension are all up-to-date.

**Comment by chakalakasp** [comment]
Having same issue.  RTX 3090, latest update.

**Comment by d8ahazard** [comment]
This is resolved with 1913bc7
