### ISSUE TITLE
Concept json file not working

### ISSUE THREAD

**Issue by mrgreaper** [d8ahazard/sd_dreambooth_extension#349]
## Kindly read this ENTIRE form and fill it out with the requested information. It may seem tedious, but it's even more tedious asking basic questions to ensure I'm not trying to troubleshoot a bug I've already fixed. Help me help you, answer all the questions and follow the steps below before posting.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your issue will be automatically closed._**

`
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
Commit hash: bb11bee22ab02aa2fb5b96baa9be8103fff19e6a
Installing requirements for Web UI

Checking Dreambooth requirements...
Checking/upgrading existing torch/torchvision installation
Checking torch and torchvision versions
Dreambooth revision is a66a2d6bca536207ca3154324f73a5cd43a65cb4
[X] bitsandbytes version 0.35.0 installed.
[X] diffusers version 0.8.1 installed.
[X] transformers version 4.21.0 installed.
[X] torch version 1.12.1+cu116 installed.
[X] torchvision version 0.13.1+cu116 installed.
[*] xformers version 0.0.14.dev0 installed.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**

have used the json with no issue before, but i did check the example to see if there was a change... i did add the max_steps when it first errored with that...which suggests its reading the file.

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**

yes

**Have you updated Dreambooth to the latest revision?**

yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**

yes

**Describe the bug**

It does not appear to be reading the concept json

Exception opening concepts JSON.
Traceback (most recent call last):
```
  File "D:\AIArt\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\db_config.py", line 168, in __init__
    self.concepts_list.append(Concept(input_dict=concept))
  File "D:\AIArt\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\db_config.py", line 332, in __init__
    self.file_prompt_contents = input_dict["file_prompt_contents"]
KeyError: 'file_prompt_contents'
Please configure some concepts.
Traceback (most recent call last):
  File "D:\AIArt\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "D:\AIArt\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 983, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\AIArt\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 924, in postprocess_data
    prediction_value = postprocess_update_dict(
  File "D:\AIArt\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 424, in postprocess_update_dict
    prediction_value = block.get_specific_update(update_dict)
  File "D:\AIArt\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 265, in get_specific_update
    generic_update = cls.update(**generic_update)
AttributeError: type object 'TabItem' has no attribute 'update'
Please configure some concepts.
```

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

**Environment**

What OS?
windows 10
If Windows - WSL or native?
not sure
What GPU are you using?
3090
**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the db_config.json file from /models/dreambooth/MODELNAME/db_config.json

**Comment by mrgreaper** [comment]
`[
    {
		"instance_prompt":      "photo of JoshDnDFriend man",
        "class_prompt":         "photo of a man",
		"save_sample_prompt": "photo of JoshDnDFriend",
        "save_sample_negative_prompt":      "blurry,monochrome",
        "instance_data_dir":    "D:/Training/Josh",
        "class_data_dir":       "D:/Training/personMale",
		"instance_token": "JoshDnDFriend",
        "class_token": "a man, man",
		"class_negative_prompt": "",
		"max_steps": 1200,
		"num_class_images": 2000,
		"class_infer_steps": 40,
		"n_save_sample": 1,
		"sample_seed": -1,
		"class_guidance_scale": 7.5,
		"save_guidance_scale": 7.5,
        "save_infer_steps": 40,
		"file_prompt_contents": ""
    },
	{
		"instance_prompt":      "photo of CraigDnDFriend man",
        "class_prompt":         "photo of a man",
		"save_sample_prompt": "photo of CraigDnDFriend",
        "save_sample_negative_prompt":      "blurry,monochrome",
        "instance_data_dir":    "D:/Training/craig",
        "class_data_dir":       "D:/Training/personMale",
		"instance_token": "CraigDnDFriend",
        "class_token": "a man, man",
		"class_negative_prompt": "",
		"max_steps": -1,
		"num_class_images": 2000,
		"class_infer_steps": 40,
		"n_save_sample": 1,
		"sample_seed": -1,
		"class_guidance_scale": 7.5,
		"save_guidance_scale": 7.5,
        "save_infer_steps": 40,
		"file_prompt_contents": ""
    },
    {
        "instance_prompt":      "photo of DavidEastwickMe man",
        "class_prompt":         "photo of a man",
		"save_sample_prompt": "photo of DavidEastwickMe",
        "save_sample_negative_prompt":      "blurry,monochrome",
        "instance_data_dir":    "D:/Training/DavidEastwickMe",
        "class_data_dir":       "D:/Training/personMale",
		"instance_token": "DavidEastwickMe",
        "class_token": "a man, man",
		"class_negative_prompt": "",
		"max_steps": -1,
		"num_class_images": 2000,
		"class_infer_steps": 40,
		"n_save_sample": 1,
		"sample_seed": -1,
		"class_guidance_scale": 7.5,
		"save_guidance_scale": 7.5,
        "save_infer_steps": 40,
		"file_prompt_contents": ""
    }
]`

That is my current Json file...it is training but its also not training.... like the results are very very wrong. 
tested on 2.0 and on models i have successfully trained before with the same json (just added the extra lines from the example including ones i was sure were optional before) 

Samples bellow are from a model i have trained before with the old json, this is how they are looking with the new json
![image](https://user-images.githubusercontent.com/2314200/204435756-b514ce9f-eccb-47c9-8bb3-c08edbacf495.png)

bellow is the samples from the old training session
![image](https://user-images.githubusercontent.com/2314200/204435965-108504da-fc19-4976-bd0a-aad8516cfc23.png)

I am guessing I have the json wrong?

**Comment by mrgreaper** [comment]
hmmm i cant get even the new concept web ui to work right. Is there a way to roll it back to before the ui was completly changed?

**Comment by mrgreaper** [comment]
YAY training working again 
![image](https://user-images.githubusercontent.com/2314200/204678433-22fdffbc-a369-4846-b6e6-bb0aa54bf40b.png)

Ok so it now thinks I am the Penguin...but thats better than it thinking I am a house lol

Still curious if I got my json file right.... never really could understand what the filenames bit means or does or is lol (yes i have read the wiki...still none the wiser...but if it works it works :) )

**Comment by mrgreaper** [comment]
ok no concepts file still isnt working right.
"max_steps": 1200,
it seems to be ignoring that.

I have 3 concepts in my json, I trianed to 6000 steps found the best step for each concept, and then set max steps accordingly. but it sjust seems to keep training each one

**Comment by mrgreaper** [comment]
> Max steps is a unique count per concept. So if you have, say 12 images for one concept, 30 for another, and 40 for your third, the _total_ steps would be 1200 + 3000 + 4000, so 8200k total steps. But, with the new dataloader, each epoch is still only training 12 steps for concept 1, 30 for 2, 40 for 3, so one step per instance image, so it should basically train all concepts evenly until the end of training.
> 
> I like spreadsheets, so I made this:
> 
> ![image](https://user-images.githubusercontent.com/1633844/204846733-580c72ee-73d8-40ad-91d6-d75f7ea8f147.png)
> 
> The first column is the current epoch, or iteration of "all" the images. Second, third, and fourth columns are our initial number of steps that go to each image per epoch, with the total number of steps.
> 
> While I fudged these numbers a bit just to have something to work with, you can see that by 6k steps, the smaller dataset has only been trained for only about half of our requisite 1200 steps, which means that 12k steps is probably the total amount required to train all concepts.
> 
> Don't feel bad, it hurts my brain too. I'm re-working the wizard now to take this logic into account, as currently, I'm returning waaay too many steps per concept, I think.

I think i went cross eyed.

I let training finish on the tests I was doing but I worked out the step count by seeing at what step they each resulted in a good result on the first run. 

The numbers bellow are made up as I am at work with out access to my pc.
So ran training with all three in the concept and max steps set on each to -1
concept 1 became good at 1200 steps
Concept 2 became good at 1500 steps
concept 3 became good at 1800 steps.

I set the Max_steps accordingly in each concept, set training steps to 2k steps and ran it. From what you are saying max steps is not max steps but a fraction of the total max steps if added up? ...nope I have gone cross eyed again.... I dont get this.

Ok change of tacts.

If i train a model on one concept until it results in perfection, then train the resulting model on the next concept until it reaches perfection, then train the resulting model on the third and final concept... each time only doing one concept... would that damage the model? is there a max times you can train before the model is broken ?

**Comment by mrgreaper** [comment]
So i tested if i could train one concept, take the resulting model and train the next concept...this would have allowed me to train each one to perfection....

I trained with just me until I was perfected (token DavidEastwickME)

I then took the new model above into dreambooth create a model as the source model and trained my mate craig until he was perfected (token CraigDnDFriend)

I then tried to generate craig using his token with the newly trained model... perfect
I tried to generate me with my token in that same model, I got craig... 
so it had overwritten my token with craig...that cant be right? is that a bug or just how dreambooth is?
