### ISSUE TITLE
AttributeError: 'DreamboothConfig' object has no attribute 'revision'

### ISSUE THREAD

**Issue by entmike** [d8ahazard/sd_dreambooth_extension#35]
Just did a new `git pull` like 5 minutes ago since it looks like you are actively working things, hope that this is ok to report:

Now when training, as soon as first preview image render attempts, I get this error:

```
Traceback (most recent call last):
  File "/home/stable/stable-diffusion-webui/modules/ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "/home/stable/stable-diffusion-webui/webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "/home/stable/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dreambooth.py", line 265, in start_training
    trained_steps = main(config)
  File "/home/stable/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 829, in main
    revision=args.revision,
AttributeError: 'DreamboothConfig' object has no attribute 'revision'
```

**Comment by d8ahazard** [comment]
Do another, I just fixed this. ;)

**Comment by Wakzor** [comment]
Im still getting this error after updating
