### ISSUE TITLE
Options' object has no attribute 'tag_drop_out'

### ISSUE THREAD

**Issue by rrweller** [d8ahazard/sd_dreambooth_extension#350]
## Kindly read this ENTIRE form and fill it out with the requested information. It may seem tedious, but it's even more tedious asking basic questions to ensure I'm not trying to troubleshoot a bug I've already fixed. Help me help you, answer all the questions and follow the steps below before posting.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your issue will be automatically closed._**

`
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 0b5dcb3d7ce397ad38312dbfc70febe7bb42dcc3
Installing requirements for Web UI
Checking Dreambooth requirements...
Checking torch and torchvision versions
Dreambooth revision is a66a2d6bca536207ca3154324f73a5cd43a65cb4
[X] bitsandbytes version 0.35.0 installed.
[X] diffusers version 0.8.1 installed.
[X] transformers version 4.21.0 installed.
[X] torch version 1.12.1+cu116 installed.
[X] torchvision version 0.13.1+cu116 installed.
[*] xformers version 0.0.14.dev0 installed.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes

**Have you updated Dreambooth to the latest revision?**
Yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
OK

**Describe the bug**
I am receiving the error "AttributeError: 'Options' object has no attribute 'tag_drop_out'" when starting training. I read previous closed issues saying to update the WebUI. I fully reinstalled the WebUI by deleting the folder and doing a fresh git clone, I still receive the error. I launched the WebUI using the supplied webui-user-dreambooth.bat file. I am on Windows 10.

(A clear and concise description of what the bug is)

**Provide logs**

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

`
***** Running training *****
  Num examples = 22
  Num batches each epoch = 22
  Num Epochs = 137
  Instantaneous batch size per device = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Gradient Accumulation steps = 1
  Total optimization steps = 3000
   Training settings: CPU: False Adam: True, Prec: fp16, Grad: True, TextTr: True EM: False, LR: 3e-06
 Allocated: 3.8GB
 Reserved: 3.9GB

Steps:   0%|                                                                                                       | 0/3000 [00:00<?, ?it/s] Exception while training: 'Options' object has no attribute 'tag_drop_out'
 Allocated: 3.8GB
 Reserved: 3.9GB

Traceback (most recent call last):
  File "F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 965, in main
    for step, batch in enumerate(train_dataloader):
  File "F:\stable-diffusion-webui\venv\lib\site-packages\accelerate\data_loader.py", line 376, in __iter__
    current_batch = next(dataloader_iter)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\dataloader.py", line 681, in __next__
    data = self._next_data()
  File "F:\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "F:\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "F:\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\SuperDataset.py", line 168, in __getitem__
    example["instance_prompt"] = self.text_getter.create_text(instance_prompt,
  File "F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\finetune_utils.py", line 64, in create_text
    if shared.opts.tag_drop_out != 0:
  File "F:\stable-diffusion-webui\modules\shared.py", line 462, in __getattr__
    return super(Options, self).__getattribute__(item)
AttributeError: 'Options' object has no attribute 'tag_drop_out'
`

**Environment**

What OS?

Native Windows 10 LTSB

If Windows - WSL or native?

What GPU are you using?

RTX 3060 12GB

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the db_config.json file from /models/dreambooth/MODELNAME/db_config.json

**Comment by d8ahazard** [comment]
You need to update your Stable-Diffusion WebUI. tag_drop_out is a somewhat recent addition.

**Comment by echo1001** [comment]
@d8ahazard Just a FYI, PR 4886 on automatic's repo removed these config parameters. It may need to be implemented in the dreambooth UI.

**Comment by Merijeek** [comment]
Sorry, but I've hit this same issue. I've done a web-ui update (and even added the git pull to my webui-user.bat) and am still hitting the same thing. My startup:

E:\NEWSD\stable-diffusion-webui>webui-user.bat
Already up to date.
venv "E:\NEWSD\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 0b5dcb3d7ce397ad38312dbfc70febe7bb42dcc3
Installing requirements for Web UI
Installing requirements for scikit_learn

Checking Dreambooth requirements...
Checking/upgrading existing torch/torchvision installation
Checking torch and torchvision versions
Dreambooth revision is d49c1b3ab7d7463f5c1a91ebd3061c0b16638ac4
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.8.1 installed.
[+] transformers version 4.21.0 installed.
[+] torch version 1.12.1+cu116 installed.
[+] torchvision version 0.13.1+cu116 installed.
[ ] xformers version 0.0.14.dev0 installed.

Launching Web UI with arguments:
Patching transformers to fix kwargs errors.
Dreambooth API layer loaded
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights [74f4c61c] from E:\NEWSD\stable-diffusion-webui\models\Stable-diffusion\redshift-diffusion-v1.ckpt
Applying cross attention optimization (Doggettx).
Model loaded.
Loaded a total of 4 textual inversion embeddings.
Embeddings: liiv-v3-neg, liiv-v3, liv4-neg, liv4
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

My attempt to train in Dreambooth:


To create a public link, set `share=True` in `launch()`.
Starting Dreambooth training...
 Cleanup completed.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Allocated 0.0/2.0GB
 Reserved: 0.0/2.0GB

Replace CrossAttention.forward to use default
 Cleanup completed.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Loaded model.
 Allocated: 0.0GB
 Reserved: 0.0GB


===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA SETUP: Loading binary E:\NEWSD\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
 Cleanup completed.
 Allocated: 0.2GB
 Reserved: 0.2GB

 Scheduler, EMA Loaded.
 Allocated: 3.8GB
 Reserved: 3.9GB

***** Running training *****
  Num examples = 31
  Num batches each epoch = 31
  Num Epochs = 33
  Instantaneous batch size per device = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Gradient Accumulation steps = 1
  Total optimization steps = 1000
   Training settings: CPU: False Adam: True, Prec: fp16, Grad: True, TextTr: True EM: False, LR: 1.72e-06
 Allocated: 3.8GB
 Reserved: 3.9GB

Steps:   0%|                                                                                  | 0/1000 [00:00<?, ?it/s] Exception while training: 'Options' object has no attribute 'tag_drop_out'
 Allocated: 3.8GB
 Reserved: 3.9GB

Traceback (most recent call last):
  File "E:\NEWSD\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 981, in main
    for step, batch in enumerate(train_dataloader):
  File "E:\NEWSD\stable-diffusion-webui\venv\lib\site-packages\accelerate\data_loader.py", line 376, in __iter__
    current_batch = next(dataloader_iter)
  File "E:\NEWSD\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\dataloader.py", line 681, in __next__
    data = self._next_data()
  File "E:\NEWSD\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "E:\NEWSD\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\NEWSD\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\NEWSD\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\SuperDataset.py", line 168, in __getitem__
    example["instance_prompt"] = self.text_getter.create_text(instance_prompt,
  File "E:\NEWSD\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\finetune_utils.py", line 64, in create_text
    if shared.opts.tag_drop_out != 0:
  File "E:\NEWSD\stable-diffusion-webui\modules\shared.py", line 462, in __getattr__
    return super(Options, self).__getattribute__(item)
AttributeError: 'Options' object has no attribute 'tag_drop_out'
 CLEANUP:
 Allocated: 3.8GB
 Reserved: 3.9GB

 Cleanup completed.
 Allocated: 3.8GB
 Reserved: 3.9GB

 Cleanup Complete.
 Allocated: 3.8GB
 Reserved: 3.9GB

Steps:   0%|                                                                                  | 0/1000 [00:00<?, ?it/s]
 Training completed, reloading SD Model.
 Allocated: 0.0GB
 Reserved: 3.8GB

Memory output: {'Training completed, reloading SD Model.': '0.0/3.8GB'}
 Restored system models.
 Allocated: 2.0GB
 Reserved: 3.8GB

Returning result: Training finished. Total lifetime steps: 0

**Comment by d8ahazard** [comment]
I am so irritated right now. Fixed with b041f9f
