### ISSUE TITLE
Manual_seed expected a long, but got NoneType

### ISSUE THREAD

**Issue by dx777** [d8ahazard/sd_dreambooth_extension#36]
```
Steps:  33%|███▎      | 100/300 [01:04<01:43,  1.93it/s, loss=0.0873, lr=5e-6]You have passed `None` for safety_checker to disable its functionality in <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'>. Note that this might lead to problems when using <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> and is not recommended.
2022-11-08T18:06:02.195544028Z You have disabled the safety checker for <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
2022-11-08T18:06:02.294639436Z Error completing request
2022-11-08T18:06:02.294676939Z Arguments: ('shivamOrangeBag', '/workspace/input/', '', 'photo of a sks bag', 'photo of a bag', '', '', 1.0, 7.5, 40.0, 0, 512, False, True, 1, 4, 1, 300, 1, True, 5e-06, False, 'constant', 0, False, 0.9, 0.999, 0.01, 1e-08, 1, 100, 0, 'no', True, '', False, True, True) {}
2022-11-08T18:06:02.295402196Z Traceback (most recent call last):
2022-11-08T18:06:02.295416418Z   File "/workspace/stable-diffusion-webui/modules/ui.py", line 185, in f
2022-11-08T18:06:02.295438063Z     res = list(func(*args, **kwargs))
2022-11-08T18:06:02.295447088Z   File "/workspace/stable-diffusion-webui/webui.py", line 55, in f
2022-11-08T18:06:02.295455958Z     res = func(*args, **kwargs)
2022-11-08T18:06:02.295464711Z   File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dreambooth.py", line 265, in start_training
2022-11-08T18:06:02.295474084Z     trained_steps = main(config)
2022-11-08T18:06:02.295482708Z   File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 856, in main
2022-11-08T18:06:02.295491955Z     g_cuda = torch.Generator(device=accelerator.device).manual_seed(args.seed)
2022-11-08T18:06:02.295500592Z RuntimeError: manual_seed expected a long, but got NoneType
2022-11-08T18:06:02.295509563Z 
2022-11-08T18:06:02.304687607Z 
Steps:  33%|███▎      | 100/300 [01:05<02:10,  1.54it/s, loss=0.0873, lr=5e-6]
```

Happens when I want to generate a thumbnail every 100 steps

**Comment by d8ahazard** [comment]
This has been resolved.
