### ISSUE TITLE
I don't think this version is working anymore

### ISSUE THREAD

**Issue by jnpatrick99** [d8ahazard/sd_dreambooth_extension#360]
**Please find the following lines in the console and paste them below. _If you do not provide this information, your issue will be automatically closed._**

`
Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Commit hash: [1d7d341](https://github.com/d8ahazard/sd_dreambooth_extension/commit/1d7d34110005e7930b589546ff5d82ce16cdcadd)
Installing requirements for Web UI
Skipping dreambooth installation.
Dreambooth revision is 1d7d34110005e7930b589546ff5d82ce16cdcadd
Diffusers version is 0.8.1
Torch version is 1.12.1+cu116
Torch vision version is 0.13.1+cu116
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?** yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?** yes

**Have you updated Dreambooth to the latest revision?** yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?** yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.** OK

**Describe the bug**

I just updated to the most recent version and trained on a specific person. There were no errors, the process seemed to have gone through smoothly. But when I tried to generate an image using a prompt like "photo of a akhakjha" it gave me generic images of various persons. Nothing from my the source images.

I'm not sure how how to use concepts, or [filewords] - the docs are confusing, so I just filled in all the fields, no json, no filewords.

The previous version (from like 1-2 weeks ago) worked perfectly.

**Provide logs**

no crashes

**Environment**

Windows

If Windows - WSL or native? Native

What GPU are you using? RTX 3090

Thank you!

**Comment by jnpatrick99** [comment]
I realized I'm getting the following error

```
Traceback (most recent call last):
  File "E:\Projects\stable-disco-webui-local-hypernetworks\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 990, in main
    text_encoder.train()
  File "E:\Projects\stable-disco-webui-local-hypernetworks\venv\lib\site-packages\accelerate\data_loader.py", line 384, in __iter__
    next_batch = next(dataloader_iter)
  File "E:\Projects\stable-disco-webui-local-hypernetworks\venv\lib\site-packages\torch\utils\data\dataloader.py", line 681, in __next__
    data = self._next_data()
  File "E:\Projects\stable-disco-webui-local-hypernetworks\venv\lib\site-packages\torch\utils\data\dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "E:\Projects\stable-disco-webui-local-hypernetworks\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\Projects\stable-disco-webui-local-hypernetworks\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\Projects\stable-disco-webui-local-hypernetworks\extensions\sd_dreambooth_extension\dreambooth\SuperDataset.py", line 156, in __getitem__
   concept = self.concepts_list[c_index]
IndexError: list index out of range
```

**Comment by jnpatrick99** [comment]
I realized I'm getting the following error

```
Traceback (most recent call last):
  File "E:\.......\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 990, in main
    text_encoder.train()
  File "E:\.......\venv\lib\site-packages\accelerate\data_loader.py", line 384, in __iter__
    next_batch = next(dataloader_iter)
  File "E:\.......\venv\lib\site-packages\torch\utils\data\dataloader.py", line 681, in __next__
    data = self._next_data()
  File "E:\.......\venv\lib\site-packages\torch\utils\data\dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "E:\.......\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\.......\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\.......\extensions\sd_dreambooth_extension\dreambooth\SuperDataset.py", line 156, in __getitem__
   concept = self.concepts_list[c_index]
IndexError: list index out of range
```

**Comment by Trauter1** [comment]
I can confirm the same thing. I'm going to post some examples and settings  when I get home.

**Comment by FranciscoFornell** [comment]
I have the exact same problem training faces. Tried 2 times yesterday after the latest update, first with 2 concepts and then with just one with the same result. On a 3080ti, windows native, with mixed precision fl16, 8bit Adam, and flash attention. The same error in the log if I scroll up, but the training continues… It just doesn't seem to have learned anything after it finishes. 🤷‍♂️

**Comment by FranciscoFornell** [comment]
An update in case it helps: I don't think it's because of that error in the log. I discovered that if I disable "don't cache latents" I don't get that error anymore, but still it doesn't learn anything. I keep getting random images. Not even persons, I even get landscapes, cars... whatever.

**Comment by Trauter1** [comment]
Dreambooth trained on cutesexyrobutts artist if you want comparison. All done with the same dataset/settings except the one mentioned.
![xy_grid-0949-3343106271-Owzmaxehx, masterpiece, best quality, 1girl, hatsune miku, solo, skirt, twintails, necktie, shirt, sleeveless, blush, tattoo, br](https://user-images.githubusercontent.com/83187970/204567458-b0457893-b1da-4296-8f60-cae11b11b32b.png)
Before superdataset commits. Trained with 0.000001 [zero-close to zero bleeding] 8k steps
![xy_grid-0948-3343106271-vavantyeujv, masterpiece, best quality, 1girl, hatsune miku, solo, skirt, twintails, necktie, shirt, sleeveless, blush, tattoo,](https://user-images.githubusercontent.com/83187970/204567778-e49ba7c6-eb30-41bb-a97b-4afaf8707553.png)
On newest commit. 0.000001, with 0.15 prior loss weight. [Heavy amount of bleeding/ style looks nothing like the artist] 8k steps
![xy_grid-0947-3343106271-erwqgnz, masterpiece, best quality, 1girl, hatsune miku, solo, skirt, twintails, necktie, shirt, sleeveless, blush, tattoo, brea](https://user-images.githubusercontent.com/83187970/204568024-c208b567-6af7-4cd4-8386-e128055d36f9.png)
Newest commit. 2e-6, with 1.0 prior loss weight[No training done] 8k steps
![chrome_2Z9znunH3E](https://user-images.githubusercontent.com/83187970/204569424-d6757668-cf47-4c4a-8986-be5d5ae88a97.png)
Could we get a bit more explanation about Filewords tab, and how it works with examples, what kind of effect does it have on training/results and how does it interact with prompt tab, because the short descriptions are a bit vague to me.

**Comment by ReflectionRip** [comment]
I have also been unable to produce any noticeable training for the last couple of days. Ever since I updated to the 3 concepts tabs version. It appears to be training, but using my instance prompt does nothing.

**Comment by YakuzaSuske** [comment]
i have this same issue.
This images was created using the latest build and trained on latest build.
![image](https://user-images.githubusercontent.com/63294141/204598832-1a6c92e0-ff0b-4a42-b347-20649b4bf82b.png)
But this image was created using the "Don't loop forever OOM" and trained on that build.
![image](https://user-images.githubusercontent.com/63294141/204598992-3f25ebc3-e228-4d17-b507-c9b31be65f19.png)
Same settings, same dataset, same everything, different build. I also noticed when finished training, it doesn't auto build the ckpt, i have to click manually the generate ckpt.

**Comment by Humanoidme** [comment]
Same problem here. attempted a number of times but not converging

**Comment by ReflectionRip** [comment]
Reverted back to the Nov21 build and was able to train again. I haven't checked at what version training stopped, but after Nov21 superdataset was added.

**Comment by d8ahazard** [comment]
Just pushed f604af2 that reverts the text encoder changes that seem to be breaking stuff. Tested with and without caching latents, all seem to be fine.

**Comment by Humanoidme** [comment]
how do you revert back? thanks

**Comment by Humanoidme** [comment]
okay, i replaced all the listed files from f604af in the folder

**Comment by jnpatrick99** [comment]
> Just pushed [f604af2](https://github.com/d8ahazard/sd_dreambooth_extension/commit/f604af2a6152a1f4db2feb3989b23038d8a5ada1) that reverts the text encoder changes that seem to be breaking stuff. Tested with and without caching latents, all seem to be fine.

Thank you! It's fixed on my end.
