### ISSUE TITLE
Can't create model.

### ISSUE THREAD

**Issue by afrofail** [d8ahazard/sd_dreambooth_extension#362]
Error completing request
Arguments: ('abc, 'sd-v1-4.ckpt [06c50424]', 'pndm', 'runwayml/stable-diffusion-v1-5', '', False) {}
Traceback (most recent call last):
  File "M:\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "M:\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "M:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\conversion.py", line 824, in extract_checkpoint
    config = DreamboothConfig(new_model_name, scheduler=scheduler_type, src=checkpoint_path)
  File "M:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\db_config.py", line 113, in __init__
    models_path = shared.cmd_opts.dreambooth_models_path
AttributeError: 'Namespace' object has no attribute 'dreambooth_models_path'

Traceback (most recent call last):
  File "M:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "M:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 983, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "M:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 913, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range

Anyone with this issue?

**Comment by d8ahazard** [comment]
Please use the issue tracker. It asks important questions and ensures you've done simple debugging steps first before posting issues...like updating the WebUI to the latest version and restarting it.

In this case, I'd guess that your UI is out of date, and so is missing the preload function for extensions that injects the missing variable into shared opts. Or, maybe you need to restart the UI. 

Either way, do the above, and if you still have an issue, use the templates. They're there to help us both.
