### ISSUE TITLE
Loading Parameters from previous session non functional

### ISSUE THREAD

**Issue by mike4llison** [d8ahazard/sd_dreambooth_extension#373]
## Kindly read this ENTIRE form and fill it out with the requested information. It may seem tedious, but it's even more tedious asking basic questions to ensure I'm not trying to troubleshoot a bug I've already fixed. Help me help you, answer all the questions and follow the steps below before posting.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your issue will be automatically closed._**

`
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Commit hash: 4b3c5bc24bffdf429c463a465763b3077fe55eb8
Installing requirements for Web UI

Checking Dreambooth requirements...
Checking/upgrading existing torch/torchvision installation
Checking torch and torchvision versions
Dreambooth revision is f604af2a6152a1f4db2feb3989b23038d8a5ada1
[+] bitsandbytes version 0.35.0 installed.
[ ] diffusers version 0.9.0 installed.
[+] transformers version 4.21.0 installed.
[+] torch version 1.12.1+cu116 installed.
[+] torchvision version 0.13.1+cu116 installed.
[!] xformers NOT installed.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**

  Yes, the section is unfortunately out of date.

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**

  Yes, several times and restarted PC

**Have you updated Dreambooth to the latest revision?**

  Yes, Daily

**Have you updated the Stable-Diffusion-WebUI to the latest version?**

  Yes, Daily

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**

  OK, But yes Really.

**Describe the bug**

When trying to load parameters from a previous training session from a previous commit (Prior to the overhaul, I, unfortunately, don't have the time to dive into which commit it was.) I am met with an error the prevents loading of the parameters. It loads the parameters from anything newer that was created with no problems.

**Provide logs**

Exception loading config: 'max_steps'
Traceback (most recent call last):
  File "D:\Github\Automatic1111\extensions\sd_dreambooth_extension\dreambooth\db_config.py", line 289, in from_file
    concept = Concept(input_dict=concept_dict)
  File "D:\Github\Automatic1111\extensions\sd_dreambooth_extension\dreambooth\db_config.py", line 346, in __init__
    self.max_steps = input_dict["max_steps"]
KeyError: 'max_steps'
Can't load config!
Traceback (most recent call last):
  File "D:\Github\Automatic1111\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "D:\Github\Automatic1111\venv\lib\site-packages\gradio\blocks.py", line 982, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "D:\Github\Automatic1111\venv\lib\site-packages\gradio\blocks.py", line 824, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Github\Automatic1111\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Github\Automatic1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\Github\Automatic1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\Github\Automatic1111\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 395, in load_params
    for key in data.__dict__:
AttributeError: 'NoneType' object has no attribute '__dict__'

**Environment**

  Windows XI

If Windows - WSL or native?

  Native

What GPU are you using?

  RTX 3090

**Screenshots/Config**

{"model_name": "stylewoman", "scheduler": "ddim", "src": "v1-5-4GB-emaonly.ckpt [81761151]", "total_steps": 6003, "pretrained_model_name_or_path": "stylewoman", "instance_data_dir": "C:\\Users\\mike4\\Desktop\\Work\\Everyai\\512x512\\dream", "class_data_dir": "D:\\Github\\SD-Regularization-Images-Style-Dreambooth\\style_ddim", "instance_prompt": "", "use_filename_as_label": true, "use_txt_as_label": false, "class_prompt": "*", "save_sample_prompt": "digital illustrated portrait. beautiful rzacvll woman. everyai style", "save_sample_negative_prompt": "", "n_save_sample": 1, "save_guidance_scale": 7.5, "save_infer_steps": 60, "with_prior_preservation": true, "num_class_images": 1500, "output_dir": "D:\\Github\\SD-A1111\\models\\dreambooth\\stylewoman", "working_dir": "D:\\Github\\SD-A1111\\models\\dreambooth\\stylewoman\\working", "resolution": 512, "center_crop": false, "train_text_encoder": true, "train_batch_size": 1, "sample_batch_size": 1, "num_train_epochs": 2, "max_train_steps": 2000, "gradient_accumulation_steps": 1, "gradient_checkpointing": true, "learning_rate": 1e-06, "scale_lr": false, "lr_scheduler": "constant", "lr_warmup_steps": 0, "use_8bit_adam": false, "adam_beta1": 0.9, "adam_beta2": 0.999, "adam_weight_decay": 0.01, "adam_epsilon": 1e-08, "max_grad_norm": 1, "save_preview_every": 100, "save_embedding_every": 10000, "mixed_precision": "no", "not_cache_latents": true, "concepts_list": [{"instance_prompt": "", "class_prompt": "*", "instance_data_dir": "C:\\Users\\mike4\\Desktop\\Work\\Everyai\\512x512\\dream", "class_data_dir": "D:\\Github\\SD-Regularization-Images-Style-Dreambooth\\style_ddim"}], "use_cpu": false, "pad_tokens": true, "hflip": true, "prior_loss_weight": 1, "seed": 0}

**I do appreciate the time and effort that you're putting into this extension, thank you very much. It makes training so much easier.** 

[db_config.json.txt](https://github.com/d8ahazard/sd_dreambooth_extension/files/10118250/db_config.json.txt)

**Comment by mike4llison** [comment]
Hi @d8ahazard Any ideas about this issue?

**Comment by d8ahazard** [comment]
I've pushed a new version. Give it a go, post a new log if you're still having issues, please.

**Comment by mike4llison** [comment]
@d8ahazard It works perfectly now. thank you so much DataHazard :)
