### ISSUE TITLE
Can't train models anymore since recent update

### ISSUE THREAD

**Issue by Jamayyy** [d8ahazard/sd_dreambooth_extension#377]
## Kindly read this ENTIRE form and fill it out with the requested information. It may seem tedious, but it's even more tedious asking basic questions to ensure I'm not trying to troubleshoot a bug I've already fixed. Help me help you, answer all the questions and follow the steps below before posting.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your issue will be automatically closed._**

`
Python 3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0]
Commit hash: 64c7b7975cedeb2aaa1a9c8eb4a479fc575843f8
Installing requirements for Web UI
Installing requirements for Dreambooth
Checking Dreambooth requirements.
Dreambooth revision is c589a3596ade64228de8a7851f50c2470c7a76aa
Args: ['extensions/sd_dreambooth_extension/install.py']
[*] Diffusers version is 0.7.2.
[*] Torch version is 1.12.1.
[*] Torch vision version is 0.13.1.
[*] Transformers version is 4.21.0.
[*] Xformers
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yes
**Have you updated Dreambooth to the latest revision?**
yes
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
yes
**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
OK
**Describe the bug**
About 2 or 3 days ago, the dreambooth UI has changed significantly. Ever since then, I can't train models anymore.
I can create a model. But then when I go to the "Train Model" tab and enter the same parameters that worked before the UI update, I just see the loading bar for a second and then it goes away and nothing happens. In the log I can see that config.json is missing from the working folder. Well I just clicked on "create model" before this, so the config.json should be there, but it's not (I checked).

**Provide logs**
```
2022-11-30T15:41:56.027622343Z Error completing request
2022-11-30T15:41:56.027643600Z Arguments: ('MODELNAME', False, False, '', 'dreambooth/dataset-MODELNAME', 'dreambooth/classification-anime', 'MODELNAMEgravity anime girl', 'anime girl', 'Description', '', '', '', '', 1, 0, 7.5, 40, 3108, 576, True, True, 1, 1, 1, 5000, 1, True, 1.3e-06, False, 'constant', 0, 'default', True, 0.9, 0.999, 0.01, 1e-08, 1, 100, 2000, 'no', True, '', False, True, '75', True, False, '', 7.5, 40, False) {}
2022-11-30T15:41:56.031889135Z Traceback (most recent call last):
2022-11-30T15:41:56.031899670Z   File "/venv/lib/python3.10/site-packages/transformers/configuration_utils.py", line 601, in _get_config_dict
2022-11-30T15:41:56.031901683Z     resolved_config_file = cached_path(
2022-11-30T15:41:56.031903001Z   File "/venv/lib/python3.10/site-packages/transformers/utils/hub.py", line 297, in cached_path
2022-11-30T15:41:56.031904357Z     raise EnvironmentError(f"file {url_or_filename} not found")
2022-11-30T15:41:56.031905608Z OSError: file /workspace/stable-diffusion-webui/models/dreambooth/MODELNAME/working/config.json not found
2022-11-30T15:41:56.031906925Z 
2022-11-30T15:41:56.031908004Z During handling of the above exception, another exception occurred:
2022-11-30T15:41:56.031909183Z 
2022-11-30T15:41:56.031910223Z Traceback (most recent call last):
2022-11-30T15:41:56.031911320Z   File "/workspace/stable-diffusion-webui/modules/ui.py", line 185, in f
2022-11-30T15:41:56.031912561Z     res = list(func(*args, **kwargs))
2022-11-30T15:41:56.031913762Z   File "/workspace/stable-diffusion-webui/webui.py", line 56, in f
2022-11-30T15:41:56.031914965Z     res = func(*args, **kwargs)
2022-11-30T15:41:56.031916137Z   File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dreambooth.py", line 527, in start_training
2022-11-30T15:41:56.031917447Z     config, mem_record = main(config, mem_record)
2022-11-30T15:41:56.031918575Z   File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 724, in main
2022-11-30T15:41:56.031919879Z     text_encoder = CLIPTextModel.from_pretrained(
2022-11-30T15:41:56.031920977Z   File "/venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1764, in from_pretrained
2022-11-30T15:41:56.031922188Z     config, model_kwargs = cls.config_class.from_pretrained(
2022-11-30T15:41:56.031929679Z   File "/venv/lib/python3.10/site-packages/transformers/models/clip/configuration_clip.py", line 126, in from_pretrained
2022-11-30T15:41:56.031931318Z     config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
2022-11-30T15:41:56.031932617Z   File "/venv/lib/python3.10/site-packages/transformers/configuration_utils.py", line 553, in get_config_dict
2022-11-30T15:41:56.031933862Z     config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
2022-11-30T15:41:56.031935051Z   File "/venv/lib/python3.10/site-packages/transformers/configuration_utils.py", line 641, in _get_config_dict
2022-11-30T15:41:56.031936467Z     raise EnvironmentError(
2022-11-30T15:41:56.031937982Z OSError: Can't load config for '/workspace/stable-diffusion-webui/models/dreambooth/MODELNAME/working'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/workspace/stable-diffusion-webui/models/dreambooth/MODELNAME/working' is the correct path to a directory containing a config.json file
```
If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

**Environment**

What OS?
Docker container (some Linux, I'm not sure) on [runpod.io](https://www.runpod.io/)
If Windows - WSL or native?

What GPU are you using?
RTX 3090
**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the db_config.json file from /models/dreambooth/MODELNAME/db_config.json
![download](https://user-images.githubusercontent.com/52106450/204850013-54e07a32-58aa-4753-9b9f-fc5aae1c35ff.jpg)

**Comment by dx777** [comment]
@Jamayyy  you should cd to /workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension
and then run git pull

**Comment by d8ahazard** [comment]
Updating via the UI alone is not enough, you need to restart the entire app to bump your transformers/diffusers version. If this doesn't work, refer to the webui-user-dreambooth.sh file for how to force the requirements.txt from dreambooth on startup.

**Comment by dx777** [comment]
@Jamayyy I run this extension on Runpod every day, if you look into the logs when it's not launching after the update - you will find what's missing. 

Overall you have to run several commands, to make it work:
git pull on the main sdwebui directory to update AUTOMATIC1111 to the latest version
pip install safetensors

git pull on /workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/ (Until you do that, you will see an "Unknown" status in the web UI when you try to update it through there. Because .git/FETCH_HEAD is missing.

If you missing "Dreambooth" tab in webUI, after doingso, then cd to /workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/ and run 
pip install -r requirements.txt

**Comment by dx777** [comment]
@Jamayyy I don't have safetensors problem on restarting the pod, only if I do "reset the pod". Or increase the volume size, it also reset it. 
Yeah, you can try to add this. Just use the one from the previous commits, otherwise, it will show as the latest version.
