### ISSUE TITLE
TypeError: start_training() takes 36 positional arguments but 38 were given

### ISSUE THREAD

**Issue by Celarye** [d8ahazard/sd_dreambooth_extension#38]
When I try to start the model trainer, the console returns this:

`Traceback (most recent call last):
  File "C:\Users\celar\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\celar\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
TypeError: start_training() takes 36 positional arguments but 38 were given`

I am using the standard settings.

**Comment by dx777** [comment]
Update the extension to the latest version, it was resolved in https://github.com/d8ahazard/sd_dreambooth_extension/commit/afef533adb8df5723a39e5263aa8c8674e81a796

**Comment by Celarye** [comment]
Ok, tyvm!

**Comment by Celarye** [comment]
Now I have this new error:

`Traceback (most recent call last):
  File "C:\Users\celar\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\celar\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "C:\Users\celar\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 265, in start_training
    trained_steps = main(config)
  File "C:\Users\celar\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 632, in main
    train_dataloader = torch.utils.data.DataLoader(
  File "C:\Users\celar\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\dataloader.py", line 353, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "C:\Users\celar\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\sampler.py", line 107, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0`

**Comment by dx777** [comment]
It clearly sais that you need to have number of samples more than 0...

**Comment by Celarye** [comment]
Oh my bad, forgot to change that one after the restart.

**Comment by dugemkakek** [comment]
> Oh my bad, forgot to change that one after the restart.

so what did you change ? i encounter a same problem
