### ISSUE TITLE
When I create a model, the console displays this error, which master can solve it. IndexError: tuple index out of range

### ISSUE THREAD

**Issue by bohaibo** [d8ahazard/sd_dreambooth_extension#384]
When I create a model, the console displays this error, which master can solve it

Checkpoint loaded from CheckpointInfo(filename='C:\\Users\\Administrator\\Desktop\\stable-diffusion-webui\\models\\Stable-diffusion\\sd-v1-5-inpainting.ckpt', title='sd-v1-5-inpainting.ckpt [3e16efc8]', hash='3e16efc8', model_name='sd-v1-5-inpainting', config='C:\\Users\\Administrator\\Desktop\\stable-diffusion-webui\\v1-inference.yaml')
Exception with the conversion: Error(s) in loading state_dict for UNet2DConditionModel:
        size mismatch for conv_in.weight: copying a param with shape torch.Size([320, 9, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 4, 3, 3]).
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\conversion.py", line 932, in extract_checkpoint
    unet.load_state_dict(converted_unet_checkpoint)
  File "C:\Users\Administrator\Desktop\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UNet2DConditionModel:
        size mismatch for conv_in.weight: copying a param with shape torch.Size([320, 9, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 4, 3, 3]).
Error completing request
Arguments: ('haibo', 'sd-v1-5-inpainting.ckpt [3e16efc8]', 'ddim', 'runwayml/stable-diffusion-v1-5', '', False) {}
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\conversion.py", line 932, in extract_checkpoint
    unet.load_state_dict(converted_unet_checkpoint)
  File "C:\Users\Administrator\Desktop\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UNet2DConditionModel:
        size mismatch for conv_in.weight: copying a param with shape torch.Size([320, 9, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 4, 3, 3]).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\Administrator\Desktop\stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\conversion.py", line 968, in extract_checkpoint
    del pipe
UnboundLocalError: local variable 'pipe' referenced before assignment

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\Administrator\Desktop\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 983, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\Administrator\Desktop\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 913, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range

**Comment by d8ahazard** [comment]
See the above.
