### ISSUE TITLE
Ckpt generation problem and status bar bug

### ISSUE THREAD

**Issue by mykeehu** [d8ahazard/sd_dreambooth_extension#386]
**Please find the following lines in the console and paste them below. _If you do not provide this information, your issue will be automatically closed._**

`
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 4b3c5bc24bffdf429c463a465763b3077fe55eb8
Installing requirements for Web UI

Installing requirements for scikit_learn

Checking Dreambooth requirements...
Checking/upgrading existing torch/torchvision installation
Checking torch and torchvision versions
Dreambooth revision is c2fc683ebcf4db23cfce22626aa6a7b565994c96
[+] bitsandbytes version 0.35.0 installed.
[ ] diffusers version 0.9.0 installed.
[+] transformers version 4.21.0 installed.
[+] torch version 1.12.1+cu116 installed.
[+] torchvision version 0.13.1+cu116 installed.
[ ] xformers version 0.0.14.dev0 installed.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes

**Have you updated Dreambooth to the latest revision?**
Yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
Ok

**Describe the bug**
I started a workout with 1000 steps, saving 500 steps. I got this error when generating the 500 ckpt, but it created the model:

> H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\diffusers\utils\deprecation_utils.py:35: FutureWarning: The configuration file of this scheduler: DDIMScheduler {
>   "_class_name": "DDIMScheduler",
>   "_diffusers_version": "0.9.0",
>   "beta_end": 0.012,
>   "beta_schedule": "scaled_linear",
>   "beta_start": 0.00085,
>   "clip_sample": false,
>   "num_train_timesteps": 1000,
>   "prediction_type": "epsilon",
>   "set_alpha_to_one": false,
>   "steps_offset": 0,
>   "trained_betas": null
> }
>  is outdated. `steps_offset` should be set to 1 instead of 0. Please make sure to update the config accordingly as leaving `steps_offset` might led to incorrect results in future versions. If you have downloaded this checkpoint from the Hugging Face Hub, it would be very nice if you could open a Pull request for the `scheduler/scheduler_config.json` file
>   warnings.warn(warning + message, FutureWarning)

When I reached 1000 steps, I got two ckpt files: a 0 and a 500. I generated a ckpt, which already had the number 1000. I continued the training, but set the save per step to 250. At 1250 I saw no save (maybe it overwrote 1000?), at 1500 it saved a 1250 ckpt. Probably slipped the numbering from checkpoint when saving a cycle. The generated ckpt hash is the same for all models!

![image](https://user-images.githubusercontent.com/6390413/205145825-5a58aaa1-bfd2-4b98-b49a-ba781740dd85.png)

So you might want to check the ckpt generation because there is something very wrong with it. My whole training session went to waste, rendering the model and the project useless.

It's just a bonus that the status bar above the preview runs to 100% after the first ckpt is saved, while it continues to work in the background.

![image](https://user-images.githubusercontent.com/6390413/205141925-452d6d06-a1e3-43ab-a068-f6fcb44833cc.png)

**Environment**

What OS? Windows 10

If Windows - WSL or native? Native

What GPU are you using? RTX 3060 12 GB

**Screenshots/Config**

{
    "adam_beta1": 0.9,
    "adam_beta2": 0.999,
    "adam_epsilon": 1e-08,
    "adam_weight_decay": 0.01,
    "attention": "xformers",
    "center_crop": false,
    "concepts_path": "",
    "gradient_accumulation_steps": 1,
    "gradient_checkpointing": true,
    "half_model": true,
    "hflip": false,
    "learning_rate": 1e-06,
    "lr_scheduler": "constant",
    "lr_warmup_steps": 0,
    "max_grad_norm": 1,
    "max_token_length": 75,
    "max_train_steps": 1000,
    "mixed_precision": "fp16",
    "model_dir": "H:\\Stable-Diffusion-Automatic\\stable-diffusion-webui\\models\\dreambooth\\1base",
    "model_name": "1base",
    "not_cache_latents": true,
    "num_train_epochs": 1,
    "pad_tokens": true,
    "pretrained_model_name_or_path": "H:\\Stable-Diffusion-Automatic\\stable-diffusion-webui\\models\\dreambooth\\1base\\working",
    "pretrained_vae_name_or_path": "",
    "prior_loss_weight": 1,
    "resolution": 512,
    "revision": 2000,
    "sample_batch_size": 1,
    "save_embedding_every": 250,
    "save_preview_every": 250,
    "scale_lr": false,
    "scheduler": "euler-ancestral",
    "src": "model-v1-5-pruned-emaonly.ckpt [81761151]",
    "train_batch_size": 1,
    "train_text_encoder": true,
    "use_8bit_adam": true,
    "use_concepts": false,
    "use_cpu": false,
    "use_ema": true,
    "v2": false,
    "concepts_list": [
        {
            "max_steps": -1,
            "instance_data_dir": "H:\\Stable-Diffusion-Automatic\\Dreambooth\\1basepix",
            "class_data_dir": "V:\\Programok\\!AI cuccok\\Stable Diffusion web UI - Automatic1111\\Dreambooth cuccok\\Templates for training\\Class-Regularization images 2 - JoePenna\\person_ddim",
            "file_prompt_contents": "Description",
            "instance_prompt": "a photo of 1base person",
            "class_prompt": "a photo of a person",
            "save_sample_prompt": "1base, a babe in restaurant in white dress",
            "save_sample_template": "",
            "instance_token": "",
            "class_token": "",
            "num_class_images": 120,
            "class_negative_prompt": "",
            "class_guidance_scale": 7,
            "class_infer_steps": 50,
            "save_sample_negative_prompt": "blurry, fat",
            "n_save_sample": 1,
            "sample_seed": -1,
            "save_guidance_scale": 7,
            "save_infer_steps": 50
        }
    ]
}

**Comment by unnamedplugins** [comment]
> The generated ckpt hash is the same for all models!
Do you have the logs of the run?  This can happen if your loss becomes `loss: nan` during training, where the training looks like it is progressing but the generated models after that point will all have the same hash.  If that's the case, it's "expected" in the sense that something about your learning rate, data set, or other settings caused your training session to become invalid.

**Comment by mykeehu** [comment]
I'm sorry, but I deleted the project and the model afterwards, because I didn't keep it in the end, it's completely useless. However, I used these settings for my previous models, except for the scheduler, which was ddim before. All other parameters are the same.

**Comment by d8ahazard** [comment]
So, the hash being the same is something I've noticed recently, and I think it has something to do with the order in which the final state_dict is being constructed. It's on my radar of things to investigate, because I think I know how to fix it, I just need to experiment a bit more.

The status bar updating has been fixed in my WIP v2 branch, which is what I've been focusing on the past few days. 

With the help of the good folks at huggingface, I think I'm *almost* ready to add V2 support, and then I can look at the checkpoint hash issue.

And, FWIW, for what I understand, the hash isn't a "full" hash of the model, only the first N bytes, so it is most likely changing, you can't tell because the Unet is packed at the end of the file, versus the beginning. Or something like that...

**Comment by mykeehu** [comment]
I tried it now with ddim samler and the same error occurred. I only changed LR and step number in the parameters. How can I generate a new hash for the model afterwards?

**Comment by leppie** [comment]
@d8ahazard  The ckpt generation problem is due to the config not getting updated/saved before calling `compile_checkpoint`. 

I made a quick patch for myself locally, but sure there is a better way. (note: all the useless code in `save_checkpoint` I `removed).

```diff
diff --git a/dreambooth/conversion.py b/dreambooth/conversion.py
index f29b336..3085904 100644
--- a/dreambooth/conversion.py
+++ b/dreambooth/conversion.py
@@ -1006,7 +1006,7 @@ def extract_checkpoint(new_model_name: str, checkpoint_path: str, scheduler_type
            src, has_ema, status
 
 
-def compile_checkpoint(model_name):
+def compile_checkpoint(model_name, total_steps: int):
     shared.state.textinfo = "Compiling checkpoint."
     shared.state.job_no = 0
     shared.state.job_count = 2
@@ -1021,7 +1021,7 @@ def compile_checkpoint(model_name):
 
         config = from_file(model_name)
         half = config.half_model
-        total_steps = config.revision
+
         if total_steps == 0:
             shared.state.textinfo = "You should probably train the model first...compiling..."
         shared.state.job_no = 1
@@ -1030,7 +1030,7 @@ def compile_checkpoint(model_name):
             "dreambooth", model_name, "working")
         out_file = os.path.join(models_path, f"{model_name}_{total_steps}.ckpt")
         try:
-            diff_to_sd(src_path, vae_path, out_file, config.revision, half)
+            diff_to_sd(src_path, vae_path, out_file, total_steps, half)
             shared.state.job_no = 2
             msg = f"Saved checkpoint to {out_file}"
         except Exception as e:
diff --git a/dreambooth/dreambooth.py b/dreambooth/dreambooth.py
index 8d4c2ac..5d3eaad 100644
--- a/dreambooth/dreambooth.py
+++ b/dreambooth/dreambooth.py
@@ -534,13 +534,5 @@ def get_full_repo_name(model_id: str, organization: Optional[str] = None, token:
 
 def save_checkpoint(model_name: str, total_steps: int):
     print(f"Successfully trained model for a total of {total_steps} steps, converting to ckpt.")
-    ckpt_dir = shared.cmd_opts.ckpt_dir
-    models_path = os.path.join(paths.models_path, "Stable-diffusion")
-    if ckpt_dir is not None:
-        models_path = ckpt_dir
-    src_path = os.path.join(
-        os.path.dirname(cmd_dreambooth_models_path) if cmd_dreambooth_models_path else paths.models_path, "dreambooth",
-        model_name, "working")
-    out_file = os.path.join(models_path, f"{model_name}_{total_steps}.ckpt")
-    conversion.compile_checkpoint(model_name)
+    conversion.compile_checkpoint(model_name, total_steps)
     sd_models.list_models()
```

**Comment by mykeehu** [comment]
@leppie I tested it now on a wrongly trained model (with the wrong hash code). I rewrote the two files and then restarted the SD. I then loaded the parameters and clicked Generate ckpt and got this:
`Error completing request
Arguments: ('onoffbj1style',) {}
Traceback (most recent call last):
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
TypeError: compile_checkpoint() missing 1 required positional argument: 'total_steps'`

**Comment by leppie** [comment]
@mykeehu I really didn't test it for stability :D I never test just generating the checkpoint without training. Oopsie.

**Comment by mykeehu** [comment]
I pass, because I'm not a programmer, I wrote this in conversion.py:

Line 1009: 
`def compile_checkpoint(model_name, total_steps = None):`

and put back line 1024: 
` total_steps = config.revision`

so I generated the ckpt, but unfortunately I didn't solve the hash problem :(

**Comment by leppie** [comment]
> so I generated the ckpt, but unfortunately I didn't solve the hash problem :(

Yes, this wont solve the hash issue.

Sorry, I kinda hijacked the issue, thinking you had the same.

**Comment by Jonseed** [comment]
The hash replication is an issue within the SD repo, and there are several PRs there to deal with it.

**Comment by Jonseed** [comment]
I also see the `steps_offset` error

**Comment by mykeehu** [comment]
Thanks, will try it as soon as the [OOM bug is fixed](https://github.com/d8ahazard/sd_dreambooth_extension/issues/437) :)

**Comment by mykeehu** [comment]
This bug fixed :)
