### ISSUE TITLE
Can't train a model, got OOM in step 0/1100

### ISSUE THREAD

**Issue by Eduardogdss** [d8ahazard/sd_dreambooth_extension#388]
## Kindly read this ENTIRE form and fill it out with the requested information. It may seem tedious, but it's even more tedious asking basic questions to ensure I'm not trying to troubleshoot a bug I've already fixed. Help me help you, answer all the questions and follow the steps below before posting.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your issue will be automatically closed._**

`
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 4b3c5bc24bffdf429c463a465763b3077fe55eb8
Installing requirements for Web UI
Checking Dreambooth requirements...
Checking torch and torchvision versions
Dreambooth revision is c2fc683ebcf4db23cfce22626aa6a7b565994c96
[+] bitsandbytes version 0.35.0 installed.
[ ] diffusers version 0.9.0 installed.
[+] transformers version 4.21.0 installed.
[+] torch version 1.12.1+cu116 installed.
[+] torchvision version 0.13.1+cu116 installed.
[!] xformers NOT installed.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**

* Yep

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**

* Yep

**Have you updated Dreambooth to the latest revision?**

* Yep

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
* Yep

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**

**Describe the bug**

When i start the training, it wont get after the step 0/1000, i get an OOM error and crashes saying that training is finished.

```

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA SETUP: Loading binary C:\new\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
C:\new\stable-diffusion-webui\venv\lib\site-packages\diffusers\utils\deprecation_utils.py:35: FutureWarning: It is deprecated to pass a pretrained model name or path to `from_config`.If you were trying to load a scheduler, please use <class 'diffusers.schedulers.scheduling_ddpm.DDPMScheduler'>.from_pretrained(...) instead. Otherwise, please make sure to pass a configuration dictionary instead. This functionality will be removed in v1.0.0.
  warnings.warn(warning + message, FutureWarning)
 Cleanup completed.
 Allocated: 0.2GB
 Reserved: 0.2GB

 Scheduler, EMA Loaded.
 Allocated: 3.8GB
 Reserved: 3.9GB

***** Running training *****
  Num examples = 17
  Num batches each epoch = 17
  Num Epochs = 59
  Instantaneous batch size per device = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Gradient Accumulation steps = 1
  Total optimization steps = 1000
   Training settings: CPU: False Adam: True, Prec: fp16, Grad: True, TextTr: True EM: False, LR: 1.72e-06
 Allocated: 3.8GB
 Reserved: 3.9GB

Steps:   0%|                                                                                  | 0/1000 [00:00<?, ?it/s] Exception while training: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 6.00 GiB total capacity; 5.20 GiB already allocated; 0 bytes free; 5.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 Allocated: 4.2GB
 Reserved: 5.3GB

Traceback (most recent call last):
  File "C:\new\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 989, in main
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "C:\new\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\new\stable-diffusion-webui\venv\lib\site-packages\accelerate\utils\operations.py", line 491, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "C:\new\stable-diffusion-webui\venv\lib\site-packages\torch\amp\autocast_mode.py", line 12, in decorate_autocast
    return func(*args, **kwargs)
  File "C:\new\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 367, in forward
    sample = upsample_block(
  File "C:\new\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\new\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 1250, in forward
    hidden_states = torch.utils.checkpoint.checkpoint(
  File "C:\new\stable-diffusion-webui\venv\lib\site-packages\torch\utils\checkpoint.py", line 235, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "C:\new\stable-diffusion-webui\venv\lib\site-packages\torch\utils\checkpoint.py", line 96, in forward
    outputs = run_function(*args)
  File "C:\new\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 1243, in custom_forward
    return module(*inputs, return_dict=return_dict)
  File "C:\new\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\new\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\attention.py", line 219, in forward
    hidden_states = block(hidden_states, context=encoder_hidden_states, timestep=timestep)
  File "C:\new\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\new\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\attention.py", line 486, in forward
    hidden_states = self.ff(self.norm3(hidden_states)) + hidden_states
  File "C:\new\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\new\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\attention.py", line 672, in forward
    hidden_states = module(hidden_states)
  File "C:\new\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\new\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\attention.py", line 698, in forward
    return hidden_states * self.gelu(gate)
  File "C:\new\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\attention.py", line 692, in gelu
    return F.gelu(gate)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 6.00 GiB total capacity; 5.20 GiB already allocated; 0 bytes free; 5.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 CLEANUP:
 Allocated: 3.9GB
 Reserved: 5.3GB

 Cleanup completed.
 Allocated: 3.9GB
 Reserved: 4.0GB

 Cleanup Complete.
 Allocated: 3.9GB
 Reserved: 4.0GB

Steps:   0%|                                                                                  | 0/1000 [00:10<?, ?it/s]
 Training completed, reloading SD Model.
 Allocated: 0.0GB
 Reserved: 3.8GB

Memory output: {'Training completed, reloading SD Model.': '0.0/3.8GB'}
 Restored system models.
 Allocated: 2.0GB
 Reserved: 3.8GB

Returning result: Training finished. Total lifetime steps: 0
```

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

**Environment**

What OS?

Windows 11

If Windows - WSL or native?

Native

What GPU are you using?

1660 TI 6GB

**Screenshots/Config**

![image](https://user-images.githubusercontent.com/54519554/205154658-4ebb313a-bfc0-4a64-81b3-7e5f01c30ac8.png)
![image](https://user-images.githubusercontent.com/54519554/205154699-2059cf15-4443-47c2-8ddc-a0351f7f5368.png)
![image](https://user-images.githubusercontent.com/54519554/205154745-3cf13e6e-7ffa-4691-97d7-0a98977fd411.png)
![image](https://user-images.githubusercontent.com/54519554/205154800-a0b481af-9b70-4aea-ad85-91664a66a210.png)
![image](https://user-images.githubusercontent.com/54519554/205154867-df171dbd-313a-4213-ab82-1d75828a0a5c.png)
![image](https://user-images.githubusercontent.com/54519554/205154939-0bda1a6e-351c-4798-99f7-670c19efc77a.png)

If the issue is specific to an error while training, please provide a screenshot of training parameters or the db_config.json file from /models/dreambooth/MODELNAME/db_config.json

**Comment by unnamedplugins** [comment]
Try unchecking `Train Text Encoder` and see if that helps.  If it does not, then you don't have enough GPU memory to run dreambooth with 512 resolution images (or at all) - unfortunately dreambooth requires a lot of memory to run.  You could decrease the resolution of your training images but the results will likely not be very good.  Another alternative is you could try running it in CPU mode, but the speed of your training will be extremely slow.

**Comment by d8ahazard** [comment]
You have 6GB of vram. The only way you're going to train is by using "CPU Only", and that's only if you have enough RAM. 

Unfortunately, there is nothing I can do here, even running on an 8GB GPU is a massive stretch. Sorry.

**Comment by Eduardogdss** [comment]
Thanks for the support, the only way now is running on colab
