### ISSUE TITLE
Various error when installing

### ISSUE THREAD

**Issue by eranmahalu** [d8ahazard/sd_dreambooth_extension#39]
Hi there, I tried to install the Dreambooth extension and got these following errors, can you please help?

"Error loading script: main.py
Traceback (most recent call last):
File "E:_AI_\SD\Local\stable-diffusion-webui\modules\scripts.py", line 155, in load_scripts
exec(compiled, module.dict)
File "E:_AI_\SD\Local\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py", line 3, in from dreambooth import conversion, dreambooth
File "E:_AI_\SD\Local\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\conversion.py", line 26, in
from dreambooth.dreambooth import get_db_models
File "E:_AI_\SD\Local\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 10, in
from dreambooth.train_dreambooth import main
File "E:_AI_\SD\Local\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 20, in
from accelerate import Accelerator
ModuleNotFoundError: No module named 'accelerate'"

Thanks so much

**Comment by d8ahazard** [comment]
You need to restart the *entire* application after installing to get it to properly install all the dependencies.

**Comment by agarzon** [comment]
> You need to restart the _entire_ application after installing to get it to properly install all the dependencies.

I did as you said. I got the same error.
![image](https://user-images.githubusercontent.com/339828/200733603-d3304039-5daf-48d8-a344-2394ce710acb.png)

**Comment by dhstsw** [comment]
same

**Comment by DevHawk83** [comment]
Have the same issues (actually it is tow, the failling installation from requirements prompt AND the missing accelerate module)

1) Fix Requirements: Your folder path must not have spaces => change folder structure OR adapt install.py to use os.path.normpath(os.path.join ...)

2) Missing accelerate module: 
> run your local Python terminal and pip  install accelerate==0.13.2
> copy \Python\Lib\site-packages\accelerate to SD\venv\Lib\site-packages

**Comment by agarzon** [comment]
> **1) Fix Requirements:**
> 
> * Your folder path must not have spaces => change folder structure

That actually fixed my issue, Thanks ! 🚀

**Comment by d8ahazard** [comment]
The issue with spaces in the path to requirements.txt is now resolved.
