### ISSUE TITLE
Error When trying to resume Training or retrain a model

### ISSUE THREAD

**Issue by dugemkakek** [d8ahazard/sd_dreambooth_extension#391]
## Kindly read this ENTIRE form and fill it out with the requested information. It may seem tedious, but it's even more tedious asking basic questions to ensure I'm not trying to troubleshoot a bug I've already fixed. Help me help you, answer all the questions and follow the steps below before posting.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your issue will be automatically closed._**

`
Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Commit hash: 4b3c5bc24bffdf429c463a465763b3077fe55eb8
Installing requirements for Web UI
Skipping dreambooth installation.
Dreambooth revision is c2fc683ebcf4db23cfce22626aa6a7b565994c96
Diffusers version is 0.9.0
Torch version is 1.12.1+cu116
Torch vision version is 0.13.1+cu116
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes
**Have you updated Dreambooth to the latest revision?**
Yes
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes
**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
OK
**Describe the bug**

hi, i got an error while trying to resume a training of an model with a parameter of steps 26000/30000 steps, got a  error num_samples of 0, but my dataset directory has an files in it,

**Provide logs**

Error completing request
Arguments: ('Twice11', False) {}
Traceback (most recent call last):
  File "F:\Programs\Stable-Diffuser\stable-diffusion-webui-master\SD-Web-Ui-Clone\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "F:\Programs\Stable-Diffuser\stable-diffusion-webui-master\SD-Web-Ui-Clone\stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "F:\Programs\Stable-Diffuser\stable-diffusion-webui-master\SD-Web-Ui-Clone\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 510, in start_training
    config, mem_record, msg = main(config, mem_record)
  File "F:\Programs\Stable-Diffuser\stable-diffusion-webui-master\SD-Web-Ui-Clone\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 725, in main
    train_dataloader = torch.utils.data.DataLoader(
  File "F:\Programs\Stable-Diffuser\stable-diffusion-webui-master\SD-Web-Ui-Clone\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\dataloader.py", line 353, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "F:\Programs\Stable-Diffuser\stable-diffusion-webui-master\SD-Web-Ui-Clone\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\sampler.py", line 107, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0

Traceback (most recent call last):
  File "F:\Programs\Stable-Diffuser\stable-diffusion-webui-master\SD-Web-Ui-Clone\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "F:\Programs\Stable-Diffuser\stable-diffusion-webui-master\SD-Web-Ui-Clone\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 983, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "F:\Programs\Stable-Diffuser\stable-diffusion-webui-master\SD-Web-Ui-Clone\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 913, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range

**Environment**

What OS?

Windows 10

What GPU are you using?

RTX 3060 12 Gigs

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the db_config.json file from /models/dreambooth/MODELNAME/db_config.json

![1](https://user-images.githubusercontent.com/36304188/205282837-57308e05-fb16-4e10-9f84-8130d0c1a726.PNG)
![2](https://user-images.githubusercontent.com/36304188/205282854-ce5db848-78f0-4da3-85b7-1c0aa56c0c97.PNG)

theres 9 concept list with the same setting but different dataset directory but the same classifier folder

**Comment by d8ahazard** [comment]
Can you try with the latest version, please. I've updated a lot, and it's hard to say whether or not your issue still exists. :P

**Comment by dugemkakek** [comment]
hi, thans for the hardwork maintaining an updating dreambooth, but the issues still there, i tried to change the config json. 
![SS1](https://user-images.githubusercontent.com/36304188/206613241-039fb934-7398-4811-9c81-ecad752b4c68.PNG)
![SS2](https://user-images.githubusercontent.com/36304188/206613245-3cfe1d3a-f29d-49cc-b2b3-6b592d5060d4.PNG)

seems like this issue only comes up when i tried to use multiple concepts (more than 3 in the tab available in the dreambooth webui menu, currently im trying to train 9 person at once) but when im not using the config.json for concept list, training resumed normaly
