### ISSUE TITLE
How to use this extension in auto1111?

### ISSUE THREAD

**Issue by Abul22** [d8ahazard/sd_dreambooth_extension#4]
installed with the 'Install from URL' -- ran it and it installed and downloaded the reqs for dreambooth , but can't see any part of the gradio interface to use it?

**Comment by d8ahazard** [comment]
Haven't tried with "install from URL" yet, but I believe you need to enable the extension after installing?

**Comment by Lalimec** [comment]
i used Install from url and it works like a charm. Did u restart the ui?
![image](https://user-images.githubusercontent.com/65521426/200358717-df104ba7-e64d-4a4e-a0c6-48be0240a83d.png)
![image](https://user-images.githubusercontent.com/65521426/200358603-68c00d55-0431-4e59-877b-b6ee9a6e4ef5.png)

**Comment by d8ahazard** [comment]
> I have no idea what I am doing wrong. Any advice would be appreciated.
> 
> Error completing request Arguments: ('Me', '/home/kyle/Documents/Photo Training/People/kylecs/Output', '', 'kylecsdb', 'person', '', '', 1.0, 7.5, 40.0, 0, 512, False, False, 1, 1, 1, 1000, 1, True, 5e-06, False, 'constant', 0, False, 0.9, 0.999, 0.01, 1e-08, 1, 250, 500, 'no', True, '/home/kyle/Documents/Photo Training/People/kylecs/json', False) {} Traceback (most recent call last): File "/home/kyle/stable-diffusion-webui/modules/ui.py", line 185, in f res = list(func(*args, **kwargs)) File "/home/kyle/stable-diffusion-webui/webui.py", line 54, in f res = func(*args, **kwargs) File "/home/kyle/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dreambooth.py", line 261, in start_training trained_steps = main(config) File "/home/kyle/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 455, in main with open(args.concepts_list, "r") as f: IsADirectoryError: [Errno 21] Is a directory: '/home/kyle/Documents/Photo Training/People/kylecs/json'

I think you have a typo in the input for your subjects.json:

/home/kyle/Documents/Photo Training/People/kylecs/json

should maybe be:

/home/kyle/Documents/Photo Training/People/kylecs.json ?

**Comment by KyleShallow** [comment]
> 

Thank you for the response, I tried that but unfortunately it did not work this time.
I am new at this I will have to go to youtube again and find some tutorials to see where I went wrong. 

Thank you for the help.

**Comment by d8ahazard** [comment]
> > 
> 
> Thank you for the response, I tried that but unfortunately it did not work this time. I am new at this I will have to go to youtube again and find some tutorials to see where I went wrong.
> 
> Thank you for the help.

If you're only training one subject, then you don't need the json.

**Comment by d8ahazard** [comment]
> > 
> 
> Thank you for the response, I tried that but unfortunately it did not work this time. I am new at this I will have to go to youtube again and find some tutorials to see where I went wrong.
> 
> Thank you for the help.

So, the issue with loading JSON from file was that you have a space in your path, which I've now fixed. Please confirm and close, else I'll close this in a day or so.

**Comment by dathide** [comment]
Just wanted to say thanks d8ahazard for your work on this repo. I've been wanting Dreambooth in A1111 for at least a few weeks.

**Comment by Abul22** [comment]
Can confirm I got mine showing up correct after a pull on auto and then reinstalling the extension.

Unfortunatly my 12G 3060 on windows runs out of vram with GPU -- but CPU appears to work :)

Legend for your work! Thanks

**Comment by KyleShallow** [comment]
> > > 
> > 
> > 
> > Thank you for the response, I tried that but unfortunately it did not work this time. I am new at this I will have to go to youtube again and find some tutorials to see where I went wrong.
> > Thank you for the help.
> 
> So, the issue with loading JSON from file was that you have a space in your path, which I've now fixed. Please confirm and close, else I'll close this in a day or so.

I am still struggling after trying your suggestion I am getting this as an error even without a JSON

File "/home/kyle/stable-diffusion-webui/venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 136, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/home/kyle/stable-diffusion-webui/models/dreambooth/kylecsdb/working/tokenizer'. Use `repo_type` argument if needed.

sorry for the trouble

**Comment by KyleShallow** [comment]
I am an Idiot I had the wrong model loaded as the and It would not run because of that.
Is there a reason that I can not train on a specific model?

**Comment by d8ahazard** [comment]
> Installing Requirements for Dreambooth
> [!] Not using xformers memory efficient attention.
> Diffusers version is 0.8.0.dev0.

The middle line (Not using xformers) indicates that the diffusers library is indeed the custom one from ShivamShiaro, and you do not have xformers installed. You can enable it using the --xformers command line arg in your launcher.

As the initial issue is resolved, I'm going to close this. 

Feel free to open a new one if you have other issues.
