### ISSUE TITLE
Unable to parse config.json while generating preview image

### ISSUE THREAD

**Issue by CORRUPTOR2037** [d8ahazard/sd_dreambooth_extension#41]
Traceback (most recent call last):
  File "E:\stable-diffusion-webui\venv\lib\site-packages\transformers\configuration_utils.py", line 601, in _get_config_dict
    resolved_config_file = cached_path(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\transformers\utils\hub.py", line 300, in cached_path
    raise ValueError(f"unable to parse {url_or_filename} as a URL or as a local path")
ValueError: unable to parse E:\stable-diffusion-webui\models\dreambooth\default\working\config.json as a URL or as a local path

**Comment by d8ahazard** [comment]
Could you please reproduce and post the error above what you pasted?

**Comment by CORRUPTOR2037** [comment]
Tried again with latest commits, now it cannot find db_config.json
Steps:
1. using torch 1.13.0+cu117
2. create model from menu with default settings using SD 1.4 (1.5 pruned is not working because of other error)
3. launch training

generated model folder structure
![изображение](https://user-images.githubusercontent.com/27880217/200746961-99d53620-fc35-4140-b496-89cea9b4874b.png)

**Comment by P4l1ndr0m** [comment]
Having same error using latest commit.
"Don't cache latents" : unchecked
"Train Text Encoder" : unchecked
"Use 8bit Adam" : checked
"Gradient Checkpointing" : checked

**Comment by Jonseed** [comment]
I'm also seeing this error.

**Comment by Jonseed** [comment]
The strange thing is that I didn't use a config.json file, and didn't enter one into the UI, so why is it looking for one?

**Comment by Jonseed** [comment]
If I make a config.json file, just so there is one there when it goes looking for it, matching the parameters that I put in the UI, I get other errors...

**Comment by Jonseed** [comment]
There is a pytorch_model.bin file but it is found in one subfolder deeper at F:\repos\auto111\stable-diffusion-webui\models\dreambooth\training1\working\text_encoder 

Is it looking in the wrong place for the pytorch_model.bin file?

**Comment by Jonseed** [comment]
If I copy the pytorch_model.bin file from the text_encoder subfolder into the working directory, and rerun training, I get this error:

```
Traceback (most recent call last):
  File "F:\repos\auto111\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "F:\repos\auto111\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "F:\repos\auto111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 265, in start_training
    trained_steps = main(config)
  File "F:\repos\auto111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 909, in main
    save_weights(lifetime_step, save_model, save_img)
  File "F:\repos\auto111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 766, in save_weights
    text_enc_model = CLIPTextModel.from_pretrained(args.working_dir, subfolder="text_encoder")
  File "F:\repos\auto111\stable-diffusion-webui\venv\lib\site-packages\transformers\modeling_utils.py", line 2024, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
TypeError: CLIPTextModel.__init__() got an unexpected keyword argument 'subfolder'

Steps: 100%|███████████| 100/100 [01:30<00:00,  1.10it/s, loss=0.0742, lr=5e-6]
```

Looks like there could be a problem in train_dreambooth.py in using the argument 'subfolder'? I'm going to try editing that out, and rerun training...

**Comment by Jonseed** [comment]
And now I'm at a dead end. After rerunning training this time I get a long list of size mismatch errors, dozens of them, of this sort...

```
        size mismatch for text_model.encoder.layers.11.layer_norm2.bias: copying a param with shape torch.Size([768]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for text_model.final_layer_norm.weight: copying a param with shape torch.Size([768]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for text_model.final_layer_norm.bias: copying a param with shape torch.Size([768]) from checkpoint, the shape in current model is torch.Size([512]).

Steps: 100%|███████████| 100/100 [01:48<00:00,  1.08s/it, loss=0.0742, lr=5e-6]
```

Anything else I should try?

**Comment by LiamDavisonGates** [comment]
I was having the same error. I checked Train Text Encoder and then it worked for me. Don't know if that helps

**Comment by Talent-Lost** [comment]
> I was having the same error. I checked Train Text Encoder and then it worked for me. Don't know if that helps

Damn, my 3080 doesn't have enough vram to run with that checked.

**Comment by d8ahazard** [comment]
This should now be resolved. Feel free to open a new issue with the template if I'm mistaken.

**Comment by djdookie** [comment]
I have the same problem:
`ValueError: unable to parse [somelocalpath]\working\config.json as a URL or as a local path`
And that's correct. There is no file called config.json in that folder, which was created in the create model step. Only in the subfolders I see different config.json files with different content.
So what can I do to solve this?

**Comment by alessandro893** [comment]
> If I copy the pytorch_model.bin file from the text_encoder subfolder into the working directory, and rerun training, I get this error:
> 
> ```
> Traceback (most recent call last):
>   File "F:\repos\auto111\stable-diffusion-webui\modules\ui.py", line 185, in f
>     res = list(func(*args, **kwargs))
>   File "F:\repos\auto111\stable-diffusion-webui\webui.py", line 54, in f
>     res = func(*args, **kwargs)
>   File "F:\repos\auto111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 265, in start_training
>     trained_steps = main(config)
>   File "F:\repos\auto111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 909, in main
>     save_weights(lifetime_step, save_model, save_img)
>   File "F:\repos\auto111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 766, in save_weights
>     text_enc_model = CLIPTextModel.from_pretrained(args.working_dir, subfolder="text_encoder")
>   File "F:\repos\auto111\stable-diffusion-webui\venv\lib\site-packages\transformers\modeling_utils.py", line 2024, in from_pretrained
>     model = cls(config, *model_args, **model_kwargs)
> TypeError: CLIPTextModel.__init__() got an unexpected keyword argument 'subfolder'
> 
> Steps: 100%|███████████| 100/100 [01:30<00:00,  1.10it/s, loss=0.0742, lr=5e-6]
> ```
> 
> Looks like there could be a problem in train_dreambooth.py in using the argument 'subfolder' on line 766? I'm going to try editing that out, and rerun training...

update torch to 1.13.1
