### ISSUE TITLE
Unable to install from automatic1111

### ISSUE THREAD

**Issue by TheMindExpansionNetwork** [d8ahazard/sd_dreambooth_extension#412]
Hello family having issues getting dreambooth on local machine.

Keep getting error listed below

using automatic1111 installer on a windows 10PC

venv "H:\AI\NEWEST TEST\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 44c46f0ed395967cd3830dd481a2db759fda5b3b
Installing requirements for Web UI
Launching Web UI with arguments: --xformers
Loading config from: H:\AI\NEWEST TEST\stable-diffusion-webui\models\Stable-diffusion\768-v-ema.yaml
LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
Loading weights [2c02b20a] from H:\AI\NEWEST TEST\stable-diffusion-webui\models\Stable-diffusion\768-v-ema.ckpt
Applying xformers cross attention optimization.
Model loaded.
Loaded a total of 0 textual inversion embeddings.
Embeddings:
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Closing server running on port: 7860
Reloading extensions
Reloading custom scripts
Error loading script: api.py
Traceback (most recent call last):
  File "H:\AI\NEWEST TEST\stable-diffusion-webui\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "H:\AI\NEWEST TEST\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "H:\AI\NEWEST TEST\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\api.py", line 9, in <module>    from extensions.sd_dreambooth_extension.dreambooth import conversion, dreambooth
  File "H:\AI\NEWEST TEST\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\conversion.py", line 28, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.dreambooth import get_db_models, printm, reload_system_models, \
  File "H:\AI\NEWEST TEST\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 13, in <module>
    from diffusers import StableDiffusionPipeline, EulerAncestralDiscreteScheduler
ImportError: cannot import name 'EulerAncestralDiscreteScheduler' from 'diffusers' (H:\AI\NEWEST TEST\stable-diffusion-webui\venv\lib\site-packages\diffusers\__init__.py)

Error loading script: main.py
Traceback (most recent call last):
  File "H:\AI\NEWEST TEST\stable-diffusion-webui\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "H:\AI\NEWEST TEST\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "H:\AI\NEWEST TEST\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py", line 3, in <module>
    from extensions.sd_dreambooth_extension.dreambooth import conversion, dreambooth
  File "H:\AI\NEWEST TEST\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\conversion.py", line 28, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.dreambooth import get_db_models, printm, reload_system_models, \
  File "H:\AI\NEWEST TEST\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 13, in <module>
    from diffusers import StableDiffusionPipeline, EulerAncestralDiscreteScheduler
ImportError: cannot import name 'EulerAncestralDiscreteScheduler' from 'diffusers' (H:\AI\NEWEST TEST\stable-diffusion-webui\venv\lib\site-packages\diffusers\__init__.py)

Reloading modules: modules.ui
Refreshing Model List
Restarting Gradio
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?** Yes sure have

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**Bunch of times

**Have you updated Dreambooth to the latest revision?**Just setting up

**Have you updated the Stable-Diffusion-WebUI to the latest version?**As today

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**ok all good thank you

**Describe the bug**

Error as listed above.

**Provide logs**

No crash goes to next stage just error when I disable dreambooth goes away

**Environment**

What OS?

windows 10

What GPU are you using? 1080TI 

![image](https://user-images.githubusercontent.com/77267159/205486789-5e69e8bd-2be6-43f5-bc7e-088c41fed201.png)

Thank you for the help let me know need anything

**Comment by ww3950460** [comment]
Unable to install from automatic1111

**Comment by ww3950460** [comment]
the same problem..

**Comment by TheMindExpansionNetwork** [comment]
We will figure it out going to dive a bit deeper

Got kiddo thinking test user then go from there something not somewhere lol

**Comment by ww3950460** [comment]
lol

**Comment by d8ahazard** [comment]
Please use the issue templates when submitting an issue. 99% chance your issue will be resolved if you follow the steps there.

**Comment by mpatzner** [comment]
Actually getting the same error after upgrading to 47cce57fe84f318eba85a1b8c0d9908f0643f1eb on Mac OS Ventura 13.0.1 (22A400).
```
Python 3.10.6 (main, Oct  7 2022, 15:17:36) [Clang 12.0.0 ]
```
Let me know if you need more info than that. This leads to the extension not being loaded at all.
