### ISSUE TITLE
RuntimeError: expected scalar type Half but found Float

### ISSUE THREAD

**Issue by NapalmCandy** [d8ahazard/sd_dreambooth_extension#414]
## Kindly read this ENTIRE form and fill it out with the requested information. It may seem tedious, but it's even more tedious asking basic questions to ensure I'm not trying to troubleshoot a bug I've already fixed. Help me help you, answer all the questions and follow the steps below before posting.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your issue will be automatically closed._**

```
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Commit hash: 44c46f0ed395967cd3830dd481a2db759fda5b3b
Installing requirements for Web UI
Installing Requirements for Dreambooth
Copying 8Bit Adam files for Windows.


Launching Web UI with arguments: --vae-path models\Stable-diffusion\vae-ft-mse-840000-ema-pruned.pt --api --cors-allow-origins=https://www.painthua.com --xformers
Preloading Dreambooth!
Loading config from: E:\Auto1111\models\Stable-diffusion\768-v-ema.yaml
LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
Loading weights [2c02b20a] from E:\Auto1111\models\Stable-diffusion\768-v-ema.ckpt
Loading VAE weights from: models\Stable-diffusion\vae-ft-mse-840000-ema-pruned.pt
Applying xformers cross attention optimization.
Model loaded.
Loaded a total of 0 textual inversion embeddings.
Embeddings:
Running on local URL:  http://127.0.0.1:7860
```

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yes
**Have you updated Dreambooth to the latest revision?**
yes
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
yes
**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
I do every time I run automatic1111
**Describe the bug**
I am getting an error when I try to train a model, it happens when I uncheck Train Text Encoders, but if I chek I have OUT OF MEMORY error, so I need to uncheck it
(A clear and concise description of what the bug is)

**Provide logs**

```Starting Dreambooth training...
 VRAM cleared.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Loaded model.
 Allocated: 0.0GB
 Reserved: 0.0GB


===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA SETUP: Loading binary E:\Auto1111\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
E:\Auto1111\venv\lib\site-packages\diffusers\utils\deprecation_utils.py:35: FutureWarning: It is deprecated to pass a pretrained model name or path to `from_config`.If you were trying to load a scheduler, please use <class 'diffusers.schedulers.scheduling_ddpm.DDPMScheduler'>.from_pretrained(...) instead. Otherwise, please make sure to pass a configuration dictionary instead. This functionality will be removed in v1.0.0.
  warnings.warn(warning + message, FutureWarning)
The config attributes {'timestep_values': None} were passed to DDPMScheduler, but are not expected and will be ignored. Please verify your scheduler_config.json configuration file.
 Scheduler Loaded
 Allocated: 0.4GB
 Reserved: 0.4GB

  Total target lifetime optimization steps = 3000
 CPU: False Adam: True, Prec: fp16, Prior: True, Grad: True, TextTr: False
 Allocated: 3.6GB
 Reserved: 3.7GB

Steps:   0%|                                                                                  | 0/3000 [00:00<?, ?it/s]Error completing request
Arguments: ('Norav1', 'C:\\Users\\Napal\\Pictures\\Entrenamiento_IA\\Nora_y_Greta\\Por_separado\\512\\Nora\\selecto\\png', 'C:\\Users\\Napal\\Pictures\\Entrenamiento_IA\\regularizacion\\girl', 'noritigr', 'girl', '', '', 1.0, 7.5, 40.0, 300, 512, False, False, 1, 1, 1, 3000, 1, True, 5e-06, False, 'constant', 0, True, 0.9, 0.999, 0.01, 1e-08, 1, 3000, 3000, 'fp16', True, '', False, True, True) {}
Traceback (most recent call last):
  File "E:\Auto1111\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "E:\Auto1111\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "E:\Auto1111\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 265, in start_training
    trained_steps = main(config)
  File "E:\Auto1111\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 769, in main
    encoder_hidden_states = text_encoder(batch["input_ids"])[0]
  File "E:\Auto1111\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Auto1111\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 722, in forward
    return self.text_model(
  File "E:\Auto1111\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Auto1111\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 643, in forward
    encoder_outputs = self.encoder(
  File "E:\Auto1111\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Auto1111\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 574, in forward
    layer_outputs = encoder_layer(
  File "E:\Auto1111\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Auto1111\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 317, in forward
    hidden_states, attn_weights = self.self_attn(
  File "E:\Auto1111\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Auto1111\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 257, in forward
    attn_output = torch.bmm(attn_probs, value_states)
RuntimeError: expected scalar type Half but found Float

Steps:   0%|                                                                                  | 0/3000 [00:02<?, ?it/s]

```
**Environment**

What OS? Windows

If Windows - WSL or native? I run Automatic1111 with  webui-user.bat, so I understand the answer it is... native?

What GPU are you using? 3080 10Gb

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the db_config.json file from /models/dreambooth/MODELNAME/db_config.json

![image](https://user-images.githubusercontent.com/12048931/205503297-2c2cbc0a-05d7-4816-8ca6-456c5120d6c4.png)
![image](https://user-images.githubusercontent.com/12048931/205503308-afdc1420-b585-4179-b785-7821883d9fc1.png)

**Comment by NapalmCandy** [comment]
Please, close it, I was getting error during updates of dreambooth, I deleted the extension and installed again, it works now

**Comment by dali99** [comment]
You can close your own issues
