### ISSUE TITLE
Constant out of memory errors on 12GB rtx 3060 no matter what settings I use.

### ISSUE THREAD

**Issue by Giganoob23** [d8ahazard/sd_dreambooth_extension#43]
Used every single "VRAM saving" setting there is. 8bit adam, dont cache latents, gradient checkpointing, fp16 mixed precision, etc. Even dropped the training resolution to abysmally low resolutions like 384 just to see if it would work. Same out of memory errors.

Isn't this supposed to be working with 12GB cards?

**Comment by rabidcopy** [comment]
Uncheck train text encoder if you haven't tried that.

**Comment by d8ahazard** [comment]
I'd also suggest unchecking "train text encoder". It uses a big chunk of VRAM. You can also set "save checkpoint every" and "save image every" to 0 to ensure that doesn't try to use any VRAM.

**Comment by Giganoob23** [comment]
@d8ahazard @rabidcopy Doesn't even manage to get to the Out of Memory part if I uncheck the train text encoder option. Instead throws out:
Traceback (most recent call last):
  File "C:\StableDif\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "C:\StableDif\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "C:\StableDif\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 265, in start_training
    trained_steps = main(config)
  File "C:\StableDif\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 769, in main
    encoder_hidden_states = text_encoder(batch["input_ids"])[0]
  File "C:\StableDif\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl    return forward_call(*input, **kwargs)
  File "C:\StableDif\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 722, in forward
    return self.text_model(
  File "C:\StableDif\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl    return forward_call(*input, **kwargs)
  File "C:\StableDif\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 643, in forward
    encoder_outputs = self.encoder(
  File "C:\StableDif\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl    return forward_call(*input, **kwargs)
  File "C:\StableDif\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 574, in forward
    layer_outputs = encoder_layer(
  File "C:\StableDif\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl    return forward_call(*input, **kwargs)
  File "C:\StableDif\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 317, in forward
    hidden_states, attn_weights = self.self_attn(
  File "C:\StableDif\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl    return forward_call(*input, **kwargs)
  File "C:\StableDif\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 257, in forward
    attn_output = torch.bmm(attn_probs, value_states)
RuntimeError: expected scalar type Half but found Float

**Comment by zark119** [comment]
same card, same problem

**Comment by rasamaya** [comment]
same problem with 080ti 11GB    tried everything, for that matter cpu doesnt work either.

**Comment by entmike** [comment]
> @d8ahazard @rabidcopy Doesn't even manage to get to the Out of Memory part if I uncheck the train text encoder option. Instead throws out: Traceback (most recent call last): File "C:\StableDif\stable-diffusion-webui\modules\ui.py", line 185, in f res = list(func(*args, **kwargs)) File "C:\StableDif\stable-diffusion-webui\webui.py", line 54, in f res = func(*args, **kwargs) File "C:\StableDif\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 265, in start_training trained_steps = main(config) File "C:\StableDif\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 769, in main encoder_hidden_states = text_encoder(batch["input_ids"])[0] File "C:\StableDif\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "C:\StableDif\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 722, in forward return self.text_model( File "C:\StableDif\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "C:\StableDif\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 643, in forward encoder_outputs = self.encoder( File "C:\StableDif\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "C:\StableDif\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 574, in forward layer_outputs = encoder_layer( File "C:\StableDif\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "C:\StableDif\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 317, in forward hidden_states, attn_weights = self.self_attn( File "C:\StableDif\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "C:\StableDif\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 257, in forward attn_output = torch.bmm(attn_probs, value_states) RuntimeError: expected scalar type Half but found Float

See here https://github.com/d8ahazard/sd_dreambooth_extension/issues/37 for a temp fix.

**Comment by cholinkol** [comment]
same problem, when uncheck the train text encoder option, nothing changed still same

**Comment by AbyszOne** [comment]
I havnt use it yet, but with this GUI https://github.com/smy20011/dreambooth-gui it works well for 3060, even with text encoding ON.

**Comment by mykeehu** [comment]
I get this error under RTX 3060 12 GB, when save ckpt file:

Traceback (most recent call last):
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 265, in start_training
    trained_steps = main(config)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 791, in main
    optimizer.step()
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\accelerate\optimizer.py", line 134, in step
    self.scaler.step(self.optimizer, closure)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 334, in step
    self.unscale_(optimizer)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 279, in unscale_
    optimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, False)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 207, in _unscale_grads_
    raise ValueError("Attempting to unscale FP16 gradients.")
ValueError: Attempting to unscale FP16 gradients.

**Comment by Jonseed** [comment]
I have a RTX3060 12GB, and I'm getting the same OOM and errors...

**Comment by Jonseed** [comment]
After making the file edit noted in #37 to delete "dtype=weight_dtype", restarting server, and unchecking don't cache latents, and switching mixed precision to fp16, and setting generate preview to a really high number, it's finally training! First time I've been able to Dreambooth train locally on my 3060 12GB.

Will take about a half hour to train 2000 steps.

**Comment by mykeehu** [comment]
Szintén hibát kaptam a kép generálásánál:

Exception saving preview: tensors used as indices must be long, byte or bool tensors
 Pipeline cleared...
 Allocated: 3.7GB
 Reserved: 4.5GB

Error completing request
Arguments: ('myprompt', 'H:\\Stable-Diffusion-Automatic\\Dreambooth\\destfront', 'H:\\Stable-Diffusion-Automatic\\stable-diffusion-webui\\models\\dreambooth\\myprompt\\classifiers', 'myprompt', '*', '', '', 1.0, 7.5, 40.0, 0, 512, False, True, 1, 1, 12, 1500, 1, True, 5e-06, False, 'constant', 0, True, 0.9, 0.999, 0.01, 1e-08, 1, 100, 500, 'fp16', False, "[{'instance_prompt': 'myprompt', 'class_prompt': '*', 'instance_data_dir': 'H:\\\\Stable-Diffusion-Automatic\\\\Dreambooth\\\\destfront', 'class_data_dir': 'H:\\\\Stable-Diffusion-Automatic\\\\stable-diffusion-webui\\\\models\\\\dreambooth\\\\myprompt\\\\classifiers'}]", False, True, True) {}
Traceback (most recent call last):
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 265, in start_training
    trained_steps = main(config)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 791, in main
    save_dir = args.output_dir
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\accelerate\optimizer.py", line 134, in step
    self.scaler.step(self.optimizer, closure)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 334, in step
    self.unscale_(optimizer)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 279, in unscale_
    optimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, False)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 207, in _unscale_grads_
    raise ValueError("Attempting to unscale FP16 gradients.")
ValueError: Attempting to unscale FP16 gradients.

**Comment by Slug-Cat** [comment]
> Unfortunately I got a different error at the end of training, after reaching the final training step, about not being able to parse config.json, and unable to connect to huggingface.co... anyone know what that might be about?

I got the same. Training starts successfully after the tweaks but if it pauses or stops for anything (including geenrating sample images) it crashes:
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like E:\stable-diffusion-webui\models\dreambooth\Stolas\working is not the path to a directory containing a config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**Comment by xXAdonesXx** [comment]
> After making the file edit noted in #37 to delete "dtype=weight_dtype", restarting server, and unchecking don't cache latents, unchecking train text encoder, and switching mixed precision to fp16, and setting generate preview to a really high number, set it to save checkpoint at the same number as my training steps, it's finally training! First time I've been able to Dreambooth train locally on my 3060 12GB.
> 
> Will take about a half hour to train 2000 steps.

+check 8bit adam

**Comment by Slug-Cat** [comment]
> 

8bit adam is checked, issue persists

**Comment by tbrebant** [comment]
According to this page https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/4436 there is a way to unload the VAE and save 2+ Gb, but I did not manage to find the setting.

**Comment by Jonseed** [comment]
I want to report that I just completed my first successful training on 3060 12GB... commit c1702f13820984a4dbe0f5c4552a14c7833b277e. So it can be done!

**Comment by d8ahazard** [comment]
> I want to report that I just completed my first successful training on 3060 12GB... commit [c1702f1](https://github.com/d8ahazard/sd_dreambooth_extension/commit/c1702f13820984a4dbe0f5c4552a14c7833b277e). So it can be done!

Could you be so kind as to document your settings here:

https://github.com/d8ahazard/sd_dreambooth_extension/discussions/77

I'd like to create a central place for folks to discuss tuning and setup, and I think your success story might be a good starting point. :D
