### ISSUE TITLE
error running instal.py and missing settings

### ISSUE THREAD

**Issue by Xelgardi** [d8ahazard/sd_dreambooth_extension#430]
**Please find the following lines in the console and paste them below. _If you do not provide this information, your issue will be automatically closed._**
Complete startup log, not containing some of the asked info though:
`
```
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: <none>
Installing requirements for Web UI
Error running install.py for extension extensions\sd_dreambooth_extension.
Command: "D:\Programme\stable-diffusion-2\venv\Scripts\python.exe" "extensions\sd_dreambooth_extension\install.py"
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "D:\Programme\stable-diffusion-2\extensions\sd_dreambooth_extension\install.py", line 62, in <module>
    app_repo = git.Repo(os.path.join(base_dir, "..", ".."))
  File "D:\Programme\stable-diffusion-2\venv\lib\site-packages\git\repo\base.py", line 224, in __init__
    self.working_dir: Optional[PathLike] = self._working_tree_dir or self.common_dir
  File "D:\Programme\stable-diffusion-2\venv\lib\site-packages\git\repo\base.py", line 307, in common_dir
    raise InvalidGitRepositoryError()
git.exc.InvalidGitRepositoryError


Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
Dreambooth API layer loaded
Loading config from: D:\Programme\stable-diffusion-2\models\Stable-diffusion\SD 2.0 768-v-ema.yaml
LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
Loading weights [2c02b20a] from D:\Programme\stable-diffusion-2\models\Stable-diffusion\SD 2.0 768-v-ema.ckpt
Applying cross attention optimization (Doggettx).
Model loaded.
Loaded a total of 0 textual inversion embeddings.
Embeddings:
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
```
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
yes, also started the CMD with the provided webui-user-dreambooth.bat file/code. Starting without gives even more errors.

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes, multiple times with and without the extra arguments. 

**Have you updated Dreambooth to the latest revision?**
Yes, fresh install. 

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes, two hours ago.

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
ok. 

**Describe the bug**
Console reports errors during startup. Not sure if related, but following the guide in the readme I should see "Dataset Directory" and several other settings within the parameter tab. However my list ends with "concepts". 

Clicking on the training wizard I get an "IndexError: tuple index out of range" error. Traceback:

`Traceback (most recent call last):
  File "D:\Programme\stable-diffusion-2\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "D:\Programme\stable-diffusion-2\venv\lib\site-packages\gradio\blocks.py", line 983, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\Programme\stable-diffusion-2\venv\lib\site-packages\gradio\blocks.py", line 913, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:`

Seems like this is related to  missing images, but as stated above I can't define a directory due to the missing settings.

**Provide logs**

No crash, other logs provided above.

**Environment**

Win10 using A1111 UI.

What GPU are you using?
RTX3070

Let me know if you need anything else.

**Comment by HazerLive** [comment]
same, updated the extension and now it doesn't show up in the webui

**Comment by Xelgardi** [comment]
worked for me, thanks for the quick fix :)

**Comment by SimonWang2014** [comment]
Some extensions in the `extensions` directory are not downloaded completely. You can delete and reinstall the extensions.
