### ISSUE TITLE
Error running install.py

### ISSUE THREAD

**Issue by Joedog6503** [d8ahazard/sd_dreambooth_extension#433]
Error running install.py for extension extensions\sd_dreambooth_extension.
Command: "C:\Users\josep\Desktop\stable-diffusion-webui-master\venv\Scripts\python.exe" "extensions\sd_dreambooth_extension\install.py"
Error code: 1
stdout:
#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: 39804ebb2e60751c908e78d4265190d12adfc73a

stderr: Traceback (most recent call last):
  File "C:\Users\josep\Desktop\stable-diffusion-webui-master\extensions\sd_dreambooth_extension\install.py", line 78, in <module>
    print(f"SD-WebUI revision: {app_revision}")
NameError: name 'app_revision' is not defined. Did you mean: 'app_revison'?

Launching Web UI with arguments: --api
No module 'xformers'. Proceeding without it.
Error loading script: api.py
Traceback (most recent call last):
  File "C:\Users\josep\Desktop\stable-diffusion-webui-master\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\Users\josep\Desktop\stable-diffusion-webui-master\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\Users\josep\Desktop\stable-diffusion-webui-master\extensions\sd_dreambooth_extension\scripts\api.py", line 9, in <module>
    from extensions.sd_dreambooth_extension.dreambooth import dreambooth
  File "C:\Users\josep\Desktop\stable-diffusion-webui-master\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 13, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.utils import reload_system_models, unload_system_models, printm, \
  File "C:\Users\josep\Desktop\stable-diffusion-webui-master\extensions\sd_dreambooth_extension\dreambooth\utils.py", line 12, in <module>
    from diffusers import StableDiffusionPipeline, EulerAncestralDiscreteScheduler
ImportError: cannot import name 'EulerAncestralDiscreteScheduler' from 'diffusers' (C:\Users\josep\Desktop\stable-diffusion-webui-master\venv\lib\site-packages\diffusers\__init__.py)

Error loading script: main.py
Traceback (most recent call last):
  File "C:\Users\josep\Desktop\stable-diffusion-webui-master\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\Users\josep\Desktop\stable-diffusion-webui-master\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\Users\josep\Desktop\stable-diffusion-webui-master\extensions\sd_dreambooth_extension\scripts\main.py", line 3, in <module>
    from extensions.sd_dreambooth_extension.dreambooth import dreambooth
  File "C:\Users\josep\Desktop\stable-diffusion-webui-master\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 13, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.utils import reload_system_models, unload_system_models, printm, \
  File "C:\Users\josep\Desktop\stable-diffusion-webui-master\extensions\sd_dreambooth_extension\dreambooth\utils.py", line 12, in <module>
    from diffusers import StableDiffusionPipeline, EulerAncestralDiscreteScheduler
ImportError: cannot import name 'EulerAncestralDiscreteScheduler' from 'diffusers' (C:\Users\josep\Desktop\stable-diffusion-webui-master\venv\lib\site-packages\diffusers\__init__.py)

LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights [6569e224] from C:\Users\josep\Desktop\stable-diffusion-webui-master\models\Stable-diffusion\Anything-V3.0.ckpt
Applying cross attention optimization (Doggettx).
Model loaded.
Loaded a total of 0 textual inversion embeddings.
Embeddings:
Running on local URL:  http://127.0.0.1:7860

I installed dreambooth through the extensions tab but it never gives me a tab for dreambooth.

**Comment by zhangpeng0610** [comment]
venv "F:\stable-diffusion-webui-master\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: <none>
Installing requirements for Web UI
Error running install.py for extension extensions\sd_dreambooth_extension.
Command: "F:\stable-diffusion-webui-master\venv\Scripts\python.exe" "extensions\sd_dreambooth_extension\install.py"
Error code: 1
stdout:
#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: 39804ebb2e60751c908e78d4265190d12adfc73a

stderr: Traceback (most recent call last):
  File "F:\stable-diffusion-webui-master\extensions\sd_dreambooth_extension\install.py", line 78, in <module>
    print(f"SD-WebUI revision: {app_revision}")
NameError: name 'app_revision' is not defined. Did you mean: 'app_revison'?


loading Smart Crop reqs from F:\stable-diffusion-webui-master\extensions\sd_smartprocess\requirements.txt
Checking Smart Crop requirements.

Launching Web UI with arguments:
Error loading script: api.py
Traceback (most recent call last):
  File "F:\stable-diffusion-webui-master\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "F:\stable-diffusion-webui-master\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "F:\stable-diffusion-webui-master\extensions\sd_dreambooth_extension\scripts\api.py", line 9, in <module>
    from extensions.sd_dreambooth_extension.dreambooth import dreambooth
  File "F:\stable-diffusion-webui-master\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 13, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.utils import reload_system_models, unload_system_models, printm, \
  File "F:\stable-diffusion-webui-master\extensions\sd_dreambooth_extension\dreambooth\utils.py", line 12, in <module>
    from diffusers import StableDiffusionPipeline, EulerAncestralDiscreteScheduler
ImportError: cannot import name 'EulerAncestralDiscreteScheduler' from 'diffusers' (F:\stable-diffusion-webui-master\venv\lib\site-packages\diffusers\__init__.py)

Error loading script: main.py
Traceback (most recent call last):
  File "F:\stable-diffusion-webui-master\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "F:\stable-diffusion-webui-master\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "F:\stable-diffusion-webui-master\extensions\sd_dreambooth_extension\scripts\main.py", line 3, in <module>
    from extensions.sd_dreambooth_extension.dreambooth import dreambooth
  File "F:\stable-diffusion-webui-master\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 13, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.utils import reload_system_models, unload_system_models, printm, \
  File "F:\stable-diffusion-webui-master\extensions\sd_dreambooth_extension\dreambooth\utils.py", line 12, in <module>
    from diffusers import StableDiffusionPipeline, EulerAncestralDiscreteScheduler
ImportError: cannot import name 'EulerAncestralDiscreteScheduler' from 'diffusers' (F:\stable-diffusion-webui-master\venv\lib\site-packages\diffusers\__init__.py)

LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights [7460a6fa] from F:\stable-diffusion-webui-master\model.ckpt
Loading VAE weights from: F:\stable-diffusion-webui-master\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt
Applying cross attention optimization (Doggettx).
Model loaded.
Loaded a total of 0 textual inversion embeddings.
Embeddings:
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`

**Comment by d8ahazard** [comment]
Whoops. Typo on my part. Fixed with 69c4773
