### ISSUE TITLE
Error: Inference tensors cannot be saved for backward. 

### ISSUE THREAD

**Issue by trihardseven** [d8ahazard/sd_dreambooth_extension#441]
```
#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: 88cc50ace470580842b519115545b9a08ebe115e
SD-WebUI revision: 44c46f0ed395967cd3830dd481a2db759fda5b3b

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers[torch] version 0.10.0.dev0 installed.
[+] transformers version 4.21.0 installed.
[ ] xformers version 0.0.14.dev0 installed.
[ ] torch version 1.12.1+cu113 installed.
[ ] torchvision version 0.13.1+cu113 installed.
```

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes
**Have you updated Dreambooth to the latest revision?**
Yes
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes
**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
ok
**Describe the bug**
Getting the following error when making samples. It's basically the same issue that I had before.

**Provide logs**
```
Returning [0.9, 0.999, 1e-08, 0.01, 'default', False, '', 1, True, False, True, 1.72e-06, 'constant', 0, 1, 75, 700, 'fp16', True, 234, True, None, 1, 512, 4, False, 700, 100, False, 2, True, True, False, False, True, '', 7.5, 40, '', 'miqote', '', 'Description', 'F:\cutted', 'miqote', '', -1, 1, 0, -1, 7.5, 40, ' lowres, bad anatomy, ((bad hands)), mutated hand, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark,  username, blurry, artist name,text, , censored, bar censor, (bad_prompt:0.5), hiiro h, multiple views', "1girl, blush, bra, braid, breasts, cleavage, closed mouth, collarbone,  white hair, large breasts, long sleeves, looking at viewer, lying, on stomach, purple bra, blue eyes, yellow eyes, miqo'te, miqote, long hair, smile, solo, the pose, underwear, absurdres, highres, on stomach, (holding_controller), dark skin, dark-skinned female, whisker markings, heterochromia, ", '', '', 7.5, 60, '', '', '', 'Description', '', '', '', -1, 1, 0, -1, 7.5, 60, '', '', '', '', 7.5, 60, '', '', '', 'Description', '', '', '', -1, 1, 0, -1, 7.5, 60, '', '', '', 'Loaded config.']
Concept 0 class dir is H:\The Games Folder\AI Image generatore\stable-diffusion-webui\models\dreambooth\ffcatgirlv1\classifiers_0
Starting Dreambooth training...
 Cleanup completed.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Allocated 0.0/2.0GB
 Reserved: 0.0/2.0GB

Initializing dreambooth training...
Patching transformers to fix kwargs errors.
Replace CrossAttention.forward to use default
Checking concept: {'max_steps': -1, 'instance_data_dir': 'F:\\\cutted', 'class_data_dir': '', 'file_prompt_contents': 'Description', 'instance_prompt': 'miqote', 'class_prompt': 'miqote', 'save_sample_prompt': "1girl, blush, bra, braid, breasts, cleavage, closed mouth, collarbone,  white hair, large breasts, long sleeves, looking at viewer, lying, on stomach, purple bra, blue eyes, yellow eyes, miqo'te, miqote, long hair, smile, solo, the pose, underwear, absurdres, highres, on stomach, (holding_controller), dark skin, dark-skinned female, whisker markings, heterochromia, ", 'save_sample_template': '', 'instance_token': '', 'class_token': '', 'num_class_images': 0, 'class_negative_prompt': '', 'class_guidance_scale': 7.5, 'class_infer_steps': 40, 'save_sample_negative_prompt': ' lowres, bad anatomy, ((bad hands)), mutated hand, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark,  username, blurry, artist name,text, , censored, bar censor, (bad_prompt:0.5), hiiro h, multiple views', 'n_save_sample': 1, 'sample_seed': -1, 'save_guidance_scale': 7.5, 'save_infer_steps': 40}
Concept requires 0 images.
 Cleanup completed.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Loaded model.
 Allocated: 0.0GB
 Reserved: 0.0GB

Using magick windows DLL!
CUDA SETUP: Loading binary H:\The Games Folder\AI Image generatore\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
 Cleanup completed.
 Allocated: 0.2GB
 Reserved: 0.2GB

 Scheduler, EMA Loaded.
 Allocated: 5.5GB
 Reserved: 5.6GB

***** Running training *****
INFO:extensions.sd_dreambooth_extension.dreambooth.train_dreambooth:***** Running training *****
  Num examples = 6
INFO:extensions.sd_dreambooth_extension.dreambooth.train_dreambooth:  Num examples = 6
  Num batches each epoch = 3
INFO:extensions.sd_dreambooth_extension.dreambooth.train_dreambooth:  Num batches each epoch = 3
  Num Epochs = 234
INFO:extensions.sd_dreambooth_extension.dreambooth.train_dreambooth:  Num Epochs = 234
  Instantaneous batch size per device = 2
INFO:extensions.sd_dreambooth_extension.dreambooth.train_dreambooth:  Instantaneous batch size per device = 2
  Total train batch size (w. parallel, distributed & accumulation) = 2
INFO:extensions.sd_dreambooth_extension.dreambooth.train_dreambooth:  Total train batch size (w. parallel, distributed & accumulation) = 2
  Gradient Accumulation steps = 1
INFO:extensions.sd_dreambooth_extension.dreambooth.train_dreambooth:  Gradient Accumulation steps = 1
  Total optimization steps = 700
INFO:extensions.sd_dreambooth_extension.dreambooth.train_dreambooth:  Total optimization steps = 700
   Training settings: CPU: False Adam: True, Prec: fp16, Grad: True, TextTr: True EM: True, LR: 1.72e-06
 Allocated: 5.5GB
 Reserved: 5.6GB

Steps:   0%|                                             | 0/700 [00:22<?, ?it/s, loss=nan, lr=1.72e-6, vram=5.5/5.6GB] Step 0 completed.
 Allocated: 5.5GB
 Reserved: 5.6GB

Steps:   1%|▎                                    | 5/700 [00:25<30:03,  2.60s/it, loss=nan, lr=1.72e-6, vram=5.5/5.6GB] Step 5 completed.
 Allocated: 5.5GB
 Reserved: 5.6GB

Generating samples:   0%|                                                                        | 0/1 [00:05<?, ?it/s]
Exception with the stupid image again: [Errno 22] Invalid argument: 'H:\\The Games Folder\\AI Image generatore\\stable-diffusion-webui\\models\\dreambooth\\ffcatgirlv1\\samples\\1girl blush bra braid breasts cleavage closed mouth collarbone  white hair large breasts long sleeves looking at viewer lying on stomach purple bra blue eyes yellow eyes miqote miqote long hair smile solo the pose underwear absurdres highres on stomach holding_controller dark skin dark-skinned female whisker markings heterochromia 901-0.png'
DEBUG:extensions.sd_dreambooth_extension.dreambooth.train_dreambooth:Exception with the stupid image again: [Errno 22] Invalid argument: 'H:\\The Games Folder\\AI Image generatore\\stable-diffusion-webui\\models\\dreambooth\\ffcatgirlv1\\samples\\1girl blush bra braid breasts cleavage closed mouth collarbone  white hair large breasts long sleeves looking at viewer lying on stomach purple bra blue eyes yellow eyes miqote miqote long hair smile solo the pose underwear absurdres highres on stomach holding_controller dark skin dark-skinned female whisker markings heterochromia 901-0.png'
Traceback (most recent call last):
  File "H:\The Games Folder\AI Image generatore\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 885, in save_weights
    s_image.save(
  File "H:\The Games Folder\AI Image generatore\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 2317, in save
    fp = builtins.open(filename, "w+b")
OSError: [Errno 22] Invalid argument: 'H:\\The Games Folder\\AI Image generatore\\stable-diffusion-webui\\models\\dreambooth\\ffcatgirlv1\\samples\\1girl blush bra braid breasts cleavage closed mouth collarbone  white hair large breasts long sleeves looking at viewer lying on stomach purple bra blue eyes yellow eyes miqote miqote long hair smile solo the pose underwear absurdres highres on stomach holding_controller dark skin dark-skinned female whisker markings heterochromia 901-0.png'
[*] Weights saved at H:\The Games Folder\AI Image generatore\stable-diffusion-webui\models\dreambooth\ffcatgirlv1
DEBUG:extensions.sd_dreambooth_extension.dreambooth.train_dreambooth:[*] Weights saved at H:\The Games Folder\AI Image generatore\stable-diffusion-webui\models\dreambooth\ffcatgirlv1
 Cleanup completed.
 Allocated: 10.5GB
 Reserved: 11.0GB

Steps:  14%|█████                              | 101/700 [01:40<25:30,  2.56s/it, loss=nan, lr=1.72e-6, vram=5.5/5.6GB] Exception while training: Inference tensors cannot be saved for backward. To work around you can make a clone to get a normal tensor and use it in autograd.
 Allocated: 10.5GB
 Reserved: 13.1GB

Traceback (most recent call last):
  File "H:\The Games Folder\AI Image generatore\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 956, in main
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "H:\The Games Folder\AI Image generatore\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\The Games Folder\AI Image generatore\stable-diffusion-webui\venv\lib\site-packages\accelerate\utils\operations.py", line 491, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "H:\The Games Folder\AI Image generatore\stable-diffusion-webui\venv\lib\site-packages\torch\amp\autocast_mode.py", line 12, in decorate_autocast
    return func(*args, **kwargs)
  File "H:\The Games Folder\AI Image generatore\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 377, in forward
    sample, res_samples = downsample_block(
  File "H:\The Games Folder\AI Image generatore\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\The Games Folder\AI Image generatore\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 608, in forward
    hidden_states = downsampler(hidden_states)
  File "H:\The Games Folder\AI Image generatore\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\The Games Folder\AI Image generatore\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\resnet.py", line 188, in forward
    hidden_states = self.conv(hidden_states)
  File "H:\The Games Folder\AI Image generatore\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\The Games Folder\AI Image generatore\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "H:\The Games Folder\AI Image generatore\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Inference tensors cannot be saved for backward. To work around you can make a clone to get a normal tensor and use it in autograd.
 CLEANUP:
 Allocated: 10.5GB
 Reserved: 13.1GB

 Cleanup completed.
 Allocated: 10.5GB
 Reserved: 11.0GB

 Cleanup Complete.
 Allocated: 10.5GB
 Reserved: 11.0GB

Steps:  14%|█████                              | 101/700 [01:41<10:02,  1.01s/it, loss=nan, lr=1.72e-6, vram=5.5/5.6GB]
 Training completed, reloading SD Model.
 Allocated: 1.8GB
 Reserved: 7.1GB

Memory output: {}
 Restored system models.
 Allocated: 3.8GB
 Reserved: 7.1GB

Returning result: Training finished. Total lifetime steps: 902

```
**Environment**

What OS?
W10
If Windows - WSL or native?
native
What GPU are you using?
3090
**Screenshots/Config**

![FireShot Capture 005 - Stable Diffusion - 127 0 0 1](https://user-images.githubusercontent.com/54422205/206081747-535095d6-4d94-4baf-9192-79eb008a9f28.png)

**Comment by trihardseven** [comment]
I think the problem was the prompt I used, maybe dreambooth can't read one of the characters? Changing the prompt to made it work.
