### ISSUE TITLE
No module named 'accelerate'

### ISSUE THREAD

**Issue by mykeehu** [d8ahazard/sd_dreambooth_extension#45]
I just installed the dreambooth extension in the Extension tab and after installing it I get this message:

Error loading script: main.py
Traceback (most recent call last):
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\modules\scripts.py", line 170, in load_scripts
    exec(compiled, module.__dict__)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py", line 3, in <module>
    from dreambooth import conversion, dreambooth
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\conversion.py", line 26, in <module>
    from dreambooth.dreambooth import get_db_models
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 10, in <module>
    from dreambooth.train_dreambooth import main
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 20, in <module>
    from accelerate import Accelerator
ModuleNotFoundError: No module named 'accelerate'

Did you miss something in the automatic installation of the extension? I am using an RTX 3060 card, without --xformers.

**Comment by mykeehu** [comment]
Ok, it wasn't in the Extension description that the bat file had to be edited and restarted :) After I ran the torch command and restarted everything, it works. It would be worthwhile to expand the extension description :)
