### ISSUE TITLE
Dreambooth tab fail loading on runpod.io

### ISSUE THREAD

**Issue by flotos** [d8ahazard/sd_dreambooth_extension#450]
## Kindly read this ENTIRE form and fill it out with the requested information. It may seem tedious, but it's even more tedious asking basic questions to ensure I'm not trying to troubleshoot a bug I've already fixed. Help me help you, answer all the questions and follow the steps below before posting.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your issue will be automatically closed._**

Runpod logs start after boot, I can't see these logs, sorry.

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**

yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**

yes

**Have you updated Dreambooth to the latest revision?**

yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**

yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**

OK

**Describe the bug**

I have looked into closed issues, but the problem is still there for me when running from runpod, even after updating automatic and dreambooth extension and restarting the container. Dreambooth extension fail to load, we can see it as there is no tab. Locally it works though, so maybe close as unrelated to your repo ? I wasn't sure about that.

**Provide logs**
```
2022-12-07T20:42:50.339537025Z Error loading script: main.py
2022-12-07T20:42:50.339692615Z Traceback (most recent call last):
2022-12-07T20:42:50.339699635Z   File "/workspace/stable-diffusion-webui/modules/scripts.py", line 184, in load_scripts
2022-12-07T20:42:50.339702955Z     module = script_loading.load_module(scriptfile.path)
2022-12-07T20:42:50.339705675Z   File "/workspace/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
2022-12-07T20:42:50.339708515Z     exec(compiled, module.__dict__)
2022-12-07T20:42:50.339711305Z   File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 8, in <module>
2022-12-07T20:42:50.339714775Z     from extensions.sd_dreambooth_extension.dreambooth.sd_to_diff import extract_checkpoint
2022-12-07T20:42:50.339717485Z   File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/sd_to_diff.py", line 36, in <module>
2022-12-07T20:42:50.339720655Z     from diffusers import (
2022-12-07T20:42:50.339723565Z ImportError: cannot import name 'HeunDiscreteScheduler' from 'diffusers' (/venv/lib/python3.10/site-packages/diffusers/__init__.py)
2022-12-07T20:42:50.339726925Z 
2022-12-07T20:44:14.486640336Z Error loading script: api.py
2022-12-07T20:44:14.486751326Z Traceback (most recent call last):
2022-12-07T20:44:14.486772626Z   File "/workspace/stable-diffusion-webui/modules/scripts.py", line 184, in load_scripts
2022-12-07T20:44:14.486776826Z     module = script_loading.load_module(scriptfile.path)
2022-12-07T20:44:14.486779756Z   File "/workspace/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
2022-12-07T20:44:14.486782686Z     exec(compiled, module.__dict__)
2022-12-07T20:44:14.486785426Z   File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/api.py", line 10, in <module>
2022-12-07T20:44:14.486788916Z     from extensions.sd_dreambooth_extension.dreambooth.sd_to_diff import extract_checkpoint
2022-12-07T20:44:14.486792126Z   File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/sd_to_diff.py", line 36, in <module>
2022-12-07T20:44:14.486811586Z     from diffusers import (
2022-12-07T20:44:14.486814426Z ImportError: cannot import name 'HeunDiscreteScheduler' from 'diffusers' (/venv/lib/python3.10/site-packages/diffusers/__init__.py)
2022-12-07T20:44:14.486817106Z 
2022-12-07T20:44:14.490800819Z Error loading script: main.py
2022-12-07T20:44:14.490846819Z Traceback (most recent call last):
2022-12-07T20:44:14.490856019Z   File "/workspace/stable-diffusion-webui/modules/scripts.py", line 184, in load_scripts
2022-12-07T20:44:14.490859519Z     module = script_loading.load_module(scriptfile.path)
2022-12-07T20:44:14.490862379Z   File "/workspace/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
2022-12-07T20:44:14.490865109Z     exec(compiled, module.__dict__)
```

Reloading modules: modules.ui
Refreshing Model List
Restarting Gradio
Running on local URL:  http://127.0.0.1:7860

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

**Environment**

What OS?

If Windows - WSL or native?

What GPU are you using?

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the db_config.json file from /models/dreambooth/MODELNAME/db_config.json

**Comment by d8ahazard** [comment]
Not sure how this would work on runpod, but you need to specify the requirements file to use when you start the WebUI.

In Linux, this is usually accomplished by doing:

`
export REQS_FILE="./extensions/sd_dreambooth_extension/requirements.txt"
`

In the webui-user.sh file.

**Comment by G-force78** [comment]
Same as prevuious commenter when running collab 
```
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 5, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.diff_to_sd import compile_checkpoint
  File "/content/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/diff_to_sd.py", line 214, in <module>
    def convert_text__enc_state_dict_v20(text_enc_dict: dict[str, torch.Tensor]):
TypeError: 'type' object is not subscriptable
```

**Comment by roperi** [comment]
@G-force78 

That error is triggered by the type hint in the function. Remove it and it should work fine but then you're gonna get another type hint error.  So better follow my instructions here on how to do it:
[https://github.com/TheLastBen/fast-stable-diffusion/issues/914#issuecomment-1349155573](https://github.com/TheLastBen/fast-stable-diffusion/issues/914#issuecomment-1349155573)

And here:
[https://github.com/TheLastBen/fast-stable-diffusion/issues/914#issuecomment-1351107670](https://github.com/TheLastBen/fast-stable-diffusion/issues/914#issuecomment-1351107670)

**Comment by roperi** [comment]
@G-force78 

Also make sure to install and upgrade the following packages. This and the changes to the files with type hints should solve the Dreambooth tab not showing problem.  

`!pip install -U diffusers accelerate transformers`

**Comment by d8ahazard** [comment]
So, I've added __future__ imports in the places where type hints exist to the latest version. Please try again and re-open or create a new issue if you're still having problems.
