### ISSUE TITLE
Dreambooth wont show tab on Automatic1111

### ISSUE THREAD

**Issue by Falaq7** [d8ahazard/sd_dreambooth_extension#454]
## Kindly read this ENTIRE form and fill it out with the requested information. It may seem tedious, but it's even more tedious asking basic questions to ensure I'm not trying to troubleshoot a bug I've already fixed. Help me help you, answer all the questions and follow the steps below before posting.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your issue will be automatically closed._**

`
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: 88cc50ace470580842b519115545b9a08ebe115e
SD-WebUI revision: 44c46f0ed395967cd3830dd481a2db759fda5b3b

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[!] diffusers[torch] version 0.10.0 installed.
[+] transformers version 4.21.0 installed.
[ ] xformers version 0.0.14.dev0 installed.
[ ] torch version 1.12.1+cu113 installed.
[ ] torchvision version 0.13.1+cu113 installed.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes

**Have you updated Dreambooth to the latest revision?**
Yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
Ok (And I've uninstalled and reinstalled everything)

**Describe the bug**

After installing Dreambooth from the extensions tab, and restarting the whole .bat and site, I still don't see the tab pop up. (note on the log it says my transformers is v4.21.0, but checking the version myself, it is the correct version it asks for on the cmd prompt (v4.25.1))

**Provide logs**

venv "C:\Users\super\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 44c46f0ed395967cd3830dd481a2db759fda5b3b
Installing requirements for Web UI

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: 88cc50ace470580842b519115545b9a08ebe115e
SD-WebUI revision: 44c46f0ed395967cd3830dd481a2db759fda5b3b

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[!] diffusers[torch] version 0.10.0 installed.
[+] transformers version 4.21.0 installed.
[ ] xformers version 0.0.14.dev0 installed.
[ ] torch version 1.12.1+cu113 installed.
[ ] torchvision version 0.13.1+cu113 installed.
#######################################################################################################

Launching Web UI with arguments:
Error loading script: api.py
Traceback (most recent call last):
  File "C:\Users\super\stable-diffusion-webui\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\Users\super\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\Users\super\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\api.py", line 9, in <module>
    from extensions.sd_dreambooth_extension.dreambooth import dreambooth
  File "C:\Users\super\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 9, in <module>
    from diffusers.utils import logging as dl
  File "C:\Users\super\stable-diffusion-webui\venv\lib\site-packages\diffusers\__init__.py", line 26, in <module>
    raise ImportError(
ImportError: `diffusers` requires transformers >= 4.25.1 to function correctly, but 4.21.0 was found in your environment. You can upgrade it with pip: `pip install transformers --upgrade`

Error loading script: main.py
Traceback (most recent call last):
  File "C:\Users\super\stable-diffusion-webui\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\Users\super\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\Users\super\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py", line 3, in <module>
    from extensions.sd_dreambooth_extension.dreambooth import dreambooth
  File "C:\Users\super\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 13, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.utils import reload_system_models, unload_system_models, printm, \
  File "C:\Users\super\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\utils.py", line 12, in <module>
    from diffusers import StableDiffusionPipeline, EulerAncestralDiscreteScheduler
  File "C:\Users\super\stable-diffusion-webui\venv\lib\site-packages\diffusers\__init__.py", line 26, in <module>
    raise ImportError(
ImportError: `diffusers` requires transformers >= 4.25.1 to function correctly, but 4.21.0 was found in your environment. You can upgrade it with pip: `pip install transformers --upgrade`

LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights [7460a6fa] from C:\Users\super\stable-diffusion-webui\models\Stable-diffusion\sd-v1-4.ckpt
Applying cross attention optimization (Doggettx).
Model loaded.
Loaded a total of 0 textual inversion embeddings.
Embeddings:
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

**Environment**

What OS?

Windows 11 native

What GPU are you using? 

GTX 3070

**Screenshots/Config**

If it is an issue with the versions, could you tell me how to change the versions of the requirements

Thank you for your help sir :)

**Comment by ocdwolf** [comment]
Same exact issue here. Upgraded to 4.25.1, and error still pops up. Dreambooth tab disappeared.

**Comment by antorio** [comment]
I have this error too. Apparently requirements.txt uninstalls transformer 4.25.1 and install 4.21.0. While diffusers needs 4.25.1
```
Installing collected packages: transformers
  Attempting uninstall: transformers
    Found existing installation: transformers 4.25.1
    Uninstalling transformers-4.25.1:
      Successfully uninstalled transformers-4.25.1
Successfully installed transformers-4.21.0
```


I tried to "pip install transformers --upgrade", the tab showing back, no error log. But after that dreambooth throws **error** when creating a model, not functioning at all. The logs shows _"IndexError: tuple index out of range"_ 

I'm on a 3090 runpod. 
Auto1111 and dreambooth updated to the latest.

**Comment by k99goran** [comment]
Same problem here.

There are quite a number of requirements not met, but I'm pretty sure they weren't met earlier this day either, and Dreambooth worked well then.

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[!] diffusers[torch] version 0.10.0 installed.
[+] transformers version 4.21.0 installed.
[!] xformers NOT installed.
[ ] torch version 1.12.1+cu113 installed.
[ ] torchvision version 0.13.1+cu113 installed.

**Comment by xurze** [comment]
Thanks all for comprehensively nailing the issue. I've been trying to paste 4.25.1 and it keeps getting pushed back to 4.19.x when opening the webui, and then to 4.21.x when dreambooth loads. Tried all kinds of crazy stuff to fix it.

**Comment by wilzamguerrero** [comment]
> I have this error too. Apparently requirements.txt uninstalls transformer 4.25.1 and install 4.21.0. While diffusers needs 4.25.1
> 
> ```
> Installing collected packages: transformers
>   Attempting uninstall: transformers
>     Found existing installation: transformers 4.25.1
>     Uninstalling transformers-4.25.1:
>       Successfully uninstalled transformers-4.25.1
> Successfully installed transformers-4.21.0
> ```
> 
> I tried to "pip install transformers --upgrade", the tab showing back, no error log. But after that dreambooth throws **error** when creating a model, not functioning at all. The logs shows _"IndexError: tuple index out of range"_
> 
> I'm on a 3090 runpod. Auto1111 and dreambooth updated to the latest.

i confirm the same problem.

**Comment by Vaxerino** [comment]
you need to change the version of transformers to 4.25.1 in the requirements.txt inside "\extensions\sd_dreambooth_extension"

**Comment by antorio** [comment]
@Vaxerino Yes, but now it's a "IndexError: tuple index out of range" error problem, when trying to create model. Does this have a correlation?

**Comment by wilzamguerrero** [comment]
> you need to change the version of transformers to 4.25.1 in the requirements.txt inside "\extensions\sd_dreambooth_extension"

Yes is working with this fix thank you so much, later i push create in dreambooth v2.1 and thsi ahppend 
![image](https://user-images.githubusercontent.com/110712636/206574269-9001346e-b505-4ad6-871d-953c2357d2d8.png)

Loading model from checkpoint.
Loading checkpoint...
v2 model loaded.
Creating scheduler...
Converting unet...
Converting vae...
Converting text encoder...
Downloading: 100% 633/633 [00:00<00:00, 482kB/s]
Downloading: 100% 1.36G/1.36G [00:22<00:00, 60.8MB/s]
^C

**Comment by antorio** [comment]
When using 4.25.1 -> create model -> error

Logs:
```
File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/sd_to_diff.py", line 962, in extract_checkpoint
db_config.resolution, \
AttributeError: 'NoneType' object has no attribute 'resolution'
```
Then (I think maybe) it creates gradio postprocess_data error:
`IndexError: tuple index out of range`

**Comment by Vaxerino** [comment]
is your webui the newest version? try pulling and reinstalling the extension

**Comment by k99goran** [comment]
> you need to change the version of transformers to 4.25.1 in the requirements.txt inside "\extensions\sd_dreambooth_extension"

Seems to have solved it for me. Thanks!

**Comment by antorio** [comment]
> is your webui the newest version? try pulling and reinstalling the extension

webui = newest
pulling & reinstalling db extension, done
--> no tab, change the requirements.txt again, ang pip install -r requirements.txt
--> same error, cannot create model

**Comment by xurze** [comment]
> you need to change the version of transformers to 4.25.1 in the requirements.txt inside "\extensions\sd_dreambooth_extension"

fixed. thank you.

**Comment by vis223** [comment]
> you need to change the version of transformers to 4.25.1 in the requirements.txt inside "\extensions\sd_dreambooth_extension"

This works until you update extensions inside automatic1111 which reverts it

**Comment by antorio** [comment]
I moved the "error create model" topic to new issue #461

**Comment by ansonkao** [comment]
Made this PR https://github.com/d8ahazard/sd_dreambooth_extension/pull/464 which resolves the issue, please test and upvote it if it works for you ✨

**Comment by Harvester62** [comment]
This change in the requirements.txt seems to have fixed the issue with Dreambooth. Thank you.

**Comment by Anime4000** [comment]
this happen before, as usual edit `requirements.txt`, I do multi install SD on many PC, so, I make quick script that clone sd-webui and this and run fresh install, once ready, dreambooth tab is there

```batch
@title Stable Diffusion WebUI
@echo off

cd /d "E:\"

if exist "stable-diffusion-webui\" (
	cd /d "stable-diffusion-webui"
) else (
	cmd /c git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui
	cd /d "stable-diffusion-webui\extensions"
	cmd /c git clone https://github.com/d8ahazard/sd_dreambooth_extension

	>  "sd_dreambooth_extension\requirements.txt" echo GitPython==3.1.27
	>> "sd_dreambooth_extension\requirements.txt" echo Pillow==9.2.0
	>> "sd_dreambooth_extension\requirements.txt" echo accelerate==0.14.0
	>> "sd_dreambooth_extension\requirements.txt" echo albumentations==1.3.0
	>> "sd_dreambooth_extension\requirements.txt" echo basicsr==1.4.2
	>> "sd_dreambooth_extension\requirements.txt" echo bitsandbytes==0.35.0
	>> "sd_dreambooth_extension\requirements.txt" echo clean-fid==0.1.29
	>> "sd_dreambooth_extension\requirements.txt" echo git+https://github.com/huggingface/diffusers#egg=diffusers[torch]
	>> "sd_dreambooth_extension\requirements.txt" echo einops==0.4.1
	>> "sd_dreambooth_extension\requirements.txt" echo fairscale==0.4.9
	>> "sd_dreambooth_extension\requirements.txt" echo fastapi==0.87.0
	>> "sd_dreambooth_extension\requirements.txt" echo font-roboto
	>> "sd_dreambooth_extension\requirements.txt" echo fonts
	>> "sd_dreambooth_extension\requirements.txt" echo ftfy==6.1.1
	>> "sd_dreambooth_extension\requirements.txt" echo gfpgan==1.3.8
	>> "sd_dreambooth_extension\requirements.txt" echo gradio==3.9
	>> "sd_dreambooth_extension\requirements.txt" echo inflection==0.5.1
	>> "sd_dreambooth_extension\requirements.txt" echo jsonmerge==1.8.0
	>> "sd_dreambooth_extension\requirements.txt" echo kornia==0.6.7
	>> "sd_dreambooth_extension\requirements.txt" echo lark==1.1.2
	>> "sd_dreambooth_extension\requirements.txt" echo modelcards==0.1.6
	>> "sd_dreambooth_extension\requirements.txt" echo numpy==1.23.3
	>> "sd_dreambooth_extension\requirements.txt" echo omegaconf==2.2.3
	>> "sd_dreambooth_extension\requirements.txt" echo piexif==1.1.3
	>> "sd_dreambooth_extension\requirements.txt" echo pytorch_lightning==1.7.6
	>> "sd_dreambooth_extension\requirements.txt" echo realesrgan==0.3.0
	>> "sd_dreambooth_extension\requirements.txt" echo resize-right==0.0.2
	>> "sd_dreambooth_extension\requirements.txt" echo safetensors==0.2.5
	>> "sd_dreambooth_extension\requirements.txt" echo scikit-image==0.19.2
	>> "sd_dreambooth_extension\requirements.txt" echo tensorboard==2.11.0
	>> "sd_dreambooth_extension\requirements.txt" echo timm==0.6.7
	>> "sd_dreambooth_extension\requirements.txt" echo torch
	>> "sd_dreambooth_extension\requirements.txt" echo torchdiffeq==0.2.3
	>> "sd_dreambooth_extension\requirements.txt" echo torchsde==0.2.5
	>> "sd_dreambooth_extension\requirements.txt" echo tqdm==4.64.1
	>> "sd_dreambooth_extension\requirements.txt" echo transformers==4.25.1

	cd ..
)

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=--xformers --deepdanbooru

git pull

call webui.bat
```

Output, so far so good:
```
Cloning into 'stable-diffusion-webui'...
remote: Enumerating objects: 11801, done.
remote: Total 11801 (delta 0), reused 0 (delta 0), pack-reused 11801
Receiving objects: 100% (11801/11801), 23.99 MiB | 12.94 MiB/s, done.

Resolving deltas: 100% (8256/8256), done.
Cloning into 'sd_dreambooth_extension'...
remote: Enumerating objects: 1346, done.
remote: Counting objects: 100% (456/456), done.
remote: Compressing objects: 100% (147/147), done.
remote: Total 1346 (delta 317), reused 423 (delta 301), pack-reused 890
Receiving objects: 100% (1346/1346), 9.98 MiB | 10.43 MiB/s, done.
Resolving deltas: 100% (856/856), done.
Already up to date.
Creating venv in directory venv using python "C:\Program Files\Python310\python.exe"
venv "E:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Commit hash: 44c46f0ed395967cd3830dd481a2db759fda5b3b
Installing torch and torchvision
Installing gfpgan
Installing clip
Installing open_clip
Installing xformers
Cloning Stable Diffusion into repositories\stable-diffusion-stability-ai...
Cloning Taming Transformers into repositories\taming-transformers...
Cloning K-diffusion into repositories\k-diffusion...
Cloning CodeFormer into repositories\CodeFormer...
Cloning BLIP into repositories\BLIP...
Installing requirements for CodeFormer
Installing requirements for Web UI

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Dreambooth revision: 88cc50ace470580842b519115545b9a08ebe115e
SD-WebUI revision: 44c46f0ed395967cd3830dd481a2db759fda5b3b

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[!] diffusers[torch] version 0.10.0 installed.
[+] transformers version 4.25.1 installed.
[ ] xformers version 0.0.14.dev0 installed.
[ ] torch version 1.12.1+cu113 installed.
[ ] torchvision version 0.13.1+cu113 installed.
#######################################################################################################

Launching Web UI with arguments: --xformers --deepdanbooru
Dreambooth API layer loaded
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights [1a7df6b8] from E:\stable-diffusion-webui\models\Stable-diffusion\Anything-V3.0-pruned-fp32.ckpt
Applying xformers cross attention optimization.
Model loaded.
Loaded a total of 0 textual inversion embeddings.
Embeddings:
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
```
