### ISSUE TITLE
Still getting an OOM error while saving model  with LoRA(6 GB VRAM)

### ISSUE THREAD

**Issue by athu16** [d8ahazard/sd_dreambooth_extension#498]
```
Commit hash: 44c46f0ed395967cd3830dd481a2db759fda5b3b
Python revision: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Dreambooth revision: 196a62ba7b86aa2da6bcd0b0dc065f41f24a0865
SD-WebUI revision: 44c46f0ed395967cd3830dd481a2db759fda5b3b

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.14.dev0 installed.
[+] torch version 1.12.1+cu113 installed.
[+] torchvision version 0.13.1+cu113 installed.
```

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes

**Have you updated Dreambooth to the latest revision?**
Yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
OK

**Describe the bug**

Training the model with LoRA works fine, using 5.9 GB VRAM, however it causes an OOM error while trying to save a checkpoint. I'm using all possible optimizations to reduce VRAM usage as much as possible.

**Provide logs**

```
Initializing dreambooth training...
Replace CrossAttention.forward to use xformers
Checking concept: {'max_steps': -1, 'instance_data_dir': 'C:\\Users\\*****\\Pictures\\datasets\\zombie\\resized', 'class_data_dir': '', 'instance_prompt': 'A photo of zombie', 'class_prompt': '', 'save_sample_prompt': '', 'save_sample_template': '', 'instance_token': 'zombie', 'class_token': 'sks', 'num_class_images': 0, 'class_negative_prompt': '', 'class_guidance_scale': 7.5, 'class_infer_steps': 40, 'save_sample_negative_prompt': '', 'n_save_sample': 1, 'sample_seed': -1, 'save_guidance_scale': 7.5, 'save_infer_steps': 40}
Concept requires 0 images.
 Loaded model.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Scheduler, EMA Loaded.
 Allocated: 4.0GB
 Reserved: 4.1GB

***** Running training *****
  Num examples = 20
  Num batches each epoch = 20
  Num Epochs = 5
  Instantaneous batch size per device = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Gradient Accumulation steps = 1
  Total optimization steps = 100
  Actual steps: 100
   Training settings: CPU: False Adam: True, Prec: fp16, Grad: True, TextTr: False EM: False, LR: 2e-06 LORA:True
 Allocated: 4.0GB
 Reserved: 4.1GB

Steps:   0%|                                                                                                                                                                   | 0/100 [00:04<?, ?it/s, loss=0.538, lr=2e-6, vram=4.0/4.3GB] Step 0 completed.
 Allocated: 4.0GB
 Reserved: 4.3GB

Steps:   5%|███████▊                                                                                                                                                   | 5/100 [00:07<01:38,  1.03s/it, loss=0.575, lr=2e-6, vram=4.0/4.9GB] Step 5 completed.
 Allocated: 4.0GB
 Reserved: 4.9GB

Steps: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:12<00:00,  1.47it/s, loss=1.54, lr=2e-6, vram=4.0/4.9GB] Exception while training: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 6.00 GiB total capacity; 5.19 GiB already allocated; 0 bytes free; 5.28 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 Allocated: 5.2GB
 Reserved: 5.3GB

Traceback (most recent call last):
  File "E:\Windows Games\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1098, in main
    save_weights()
  File "E:\Windows Games\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 858, in save_weights
    s_pipeline = s_pipeline.to(accelerator.device)
  File "E:\Windows Games\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipeline_utils.py", line 270, in to
    module.to(torch_device)
  File "E:\Windows Games\stable-diffusion-webui\venv\lib\site-packages\transformers\modeling_utils.py", line 1682, in to
    return super().to(*args, **kwargs)
  File "E:\Windows Games\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 927, in to
    return self._apply(convert)
  File "E:\Windows Games\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  File "E:\Windows Games\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  File "E:\Windows Games\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "E:\Windows Games\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 602, in _apply
    param_applied = fn(param)
  File "E:\Windows Games\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 925, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 6.00 GiB total capacity; 5.19 GiB already allocated; 0 bytes free; 5.28 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
|===========================================================================|
|                  PyTorch CUDA memory summary, device ID 0                 |
|---------------------------------------------------------------------------|
|            CUDA OOMs: 1            |        cudaMalloc retries: 2         |
|===========================================================================|
|        Metric         | Cur Usage  | Peak Usage | Tot Alloc  | Tot Freed  |
|---------------------------------------------------------------------------|
| Allocated memory      |    5314 MB |    5314 MB |    1206 GB |    1201 GB |
|       from large pool |    5278 MB |    5278 MB |    1146 GB |    1140 GB |
|       from small pool |      36 MB |      55 MB |      60 GB |      60 GB |
|---------------------------------------------------------------------------|
| Active memory         |    5314 MB |    5314 MB |    1206 GB |    1201 GB |
|       from large pool |    5278 MB |    5278 MB |    1146 GB |    1140 GB |
|       from small pool |      36 MB |      55 MB |      60 GB |      60 GB |
|---------------------------------------------------------------------------|
| GPU reserved memory   |    5408 MB |    5408 MB |   15360 MB |    9952 MB |
|       from large pool |    5356 MB |    5356 MB |   15138 MB |    9782 MB |
|       from small pool |      52 MB |      58 MB |     222 MB |     170 MB |
|---------------------------------------------------------------------------|
| Non-releasable memory |   95353 KB |  245734 KB |    1105 GB |    1105 GB |
|       from large pool |   78992 KB |  244367 KB |    1043 GB |    1043 GB |
|       from small pool |   16361 KB |   20785 KB |      62 GB |      62 GB |
|---------------------------------------------------------------------------|
| Allocations           |    2284    |    2284    |  612411    |  610127    |
|       from large pool |     544    |     544    |  219037    |  218493    |
|       from small pool |    1740    |    1781    |  393374    |  391634    |
|---------------------------------------------------------------------------|
| Active allocs         |    2284    |    2284    |  612411    |  610127    |
|       from large pool |     544    |     544    |  219037    |  218493    |
|       from small pool |    1740    |    1781    |  393374    |  391634    |
|---------------------------------------------------------------------------|
| GPU reserved segments |     182    |     184    |     562    |     380    |
|       from large pool |     156    |     156    |     451    |     295    |
|       from small pool |      26    |      29    |     111    |      85    |
|---------------------------------------------------------------------------|
| Non-releasable allocs |      85    |     137    |  329123    |  329038    |
|       from large pool |      41    |      56    |  149085    |  149044    |
|       from small pool |      44    |     102    |  180038    |  179994    |
|---------------------------------------------------------------------------|
| Oversize allocations  |       0    |       0    |       0    |       0    |
|---------------------------------------------------------------------------|
| Oversize GPU segments |       0    |       0    |       0    |       0    |
|===========================================================================|

 CLEANUP:
 Allocated: 4.0GB
 Reserved: 5.3GB

 Cleanup completed.
 Allocated: 4.0GB
 Reserved: 4.1GB

 Cleanup Complete.
 Allocated: 4.0GB
 Reserved: 4.1GB

Steps: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:23<00:00,  1.19it/s, loss=1.54, lr=2e-6, vram=4.0/4.9GB]
 Training completed, reloading SD Model.
 Allocated: 0.0GB
 Reserved: 3.4GB

Memory output: {}
 Restored system models.
 Allocated: 2.5GB
 Reserved: 3.5GB

Returning result: Training finished. Total lifetime steps: 200
```

**Environment**

What OS?
Windows 10 21H2

If Windows - WSL or native?
Native

What GPU are you using?
NVIDIA GeForce RTX 2060 Mobile

**Screenshots/Config**
```
{
    "adam_beta1": 0.9,
    "adam_beta2": 0.999,
    "adam_epsilon": 1e-08,
    "adam_weight_decay": 0.01,
    "attention": "xformers",
    "center_crop": false,
    "concepts_path": "",
    "epoch_pause_frequency": 0.0,
    "epoch_pause_time": 60.0,
    "gradient_accumulation_steps": 1,
    "gradient_checkpointing": true,
    "half_model": true,
    "hflip": true,
    "learning_rate": 2e-06,
    "lr_scheduler": "constant",
    "lr_warmup_steps": 500,
    "max_token_length": 75,
    "max_train_steps": 100,
    "mixed_precision": "fp16",
    "model_dir": "E:\\Windows Games\\stable-diffusion-webui\\models\\dreambooth\\zombie",
    "model_name": "zombie",
    "not_cache_latents": true,
    "num_train_epochs": 5,
    "pad_tokens": true,
    "pretrained_model_name_or_path": "E:\\Windows Games\\stable-diffusion-webui\\models\\dreambooth\\zombie\\working",
    "pretrained_vae_name_or_path": null,
    "prior_loss_weight": 1,
    "resolution": 512,
    "revision": 200,
    "sample_batch_size": 1,
    "save_class_txt": true,
    "save_embedding_every": 500,
    "save_preview_every": 500,
    "save_use_global_counts": true,
    "save_use_epochs": false,
    "scale_lr": false,
    "src": "E:\\Windows Games\\stable-diffusion-webui\\models\\Stable-diffusion\\v2-1_512-ema-pruned.ckpt",
    "shuffle_tags": false,
    "train_batch_size": 1,
    "train_text_encoder": false,
    "use_8bit_adam": true,
    "use_concepts": false,
    "use_cpu": false,
    "use_ema": false,
    "use_lora": true,
    "scheduler": "ddim",
    "v2": true,
    "has_ema": "True",
    "concepts_list": [
        {
            "max_steps": -1,
            "instance_data_dir": "C:\\Users\\*****\\Pictures\\datasets\\zombie\\resized",
            "class_data_dir": "",
            "instance_prompt": "A photo of zombie",
            "class_prompt": "",
            "save_sample_prompt": "",
            "save_sample_template": "",
            "instance_token": "zombie",
            "class_token": "sks",
            "num_class_images": 0,
            "class_negative_prompt": "",
            "class_guidance_scale": 7.5,
            "class_infer_steps": 40,
            "save_sample_negative_prompt": "",
            "n_save_sample": 1,
            "sample_seed": -1,
            "save_guidance_scale": 7.5,
            "save_infer_steps": 40
        }
    ],
    "tokenizer_name": null,
    "epoch": 6,
    "lifetime_revision": 200
}
```

**Comment by Thomas-MMJ** [comment]
Also disabling '-opt-channelslast' reduced frequency of OOM for me in addition to the above.  I think also switching from xformers to flash_attention might save a bit more ram also but is unclear.

**Comment by athu16** [comment]
> Also disabling '-opt-channelslast' reduced frequency of OOM for me in addition to the above. I think also switching from xformers to flash_attention might save a bit more ram also but is unclear.

Could you elaborate what you mean by "disabling -opt-channelslast"? Is it a flag somewhere in the code?
