### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by Gman0909** [d8ahazard/sd_dreambooth_extension#502]
## Kindly read this ENTIRE form and fill it out with the requested information. It may seem tedious, but it's even more tedious asking basic questions to ensure I'm not trying to troubleshoot a bug I've already fixed. Help me help you, answer all the questions and follow the steps below before posting.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your issue will be automatically closed._**

`
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 685f9631b56ff8bd43bce24ff5ce0f9a0e9af490
Installing requirements for Web UI

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: 196a62ba7b86aa2da6bcd0b0dc065f41f24a0865
SD-WebUI revision: 685f9631b56ff8bd43bce24ff5ce0f9a0e9af490

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.14.dev0 installed.
[+] torch version 1.12.1+cu116 installed.
[+] torchvision version 0.13.1+cu116 installed.
#######################################################################################################

`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yes
**Have you updated Dreambooth to the latest revision?**
yes
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
yes
**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
ok
**Describe the bug**

Error when starting training

**Provide logs**

Traceback (most recent call last):
  File "E:\stable-diffusion\stable-diffusion-Automatic\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 356, in start_training
    config, mem_record, msg = main(config, mem_record, use_subdir=use_subdir, lora_model=lora_model_name,
  File "E:\stable-diffusion\stable-diffusion-Automatic\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 943, in main
    progress_bar = tqdm(range(actual_train_steps), disable=not accelerator.is_local_main_process)
TypeError: 'float' object cannot be interpreted as an integer
 Training completed, reloading SD Model.
 Allocated: 0.0GB
 Reserved: 3.8GB

Memory output: {}
 Restored system models.
 Allocated: 2.0GB
 Reserved: 3.8GB

Returning result: Exception training model: 'float' object cannot be interpreted as an integer

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

**Environment**

What OS?

Windows native

What GPU are you using?

2080Ti

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the db_config.json file from /models/dreambooth/MODELNAME/db_config.json

**Comment by sheldonchiu** [comment]
Using the training wizard, training steps per image is set to 125.00000000000003 (may be different for you). 
For now, you can manually remove all the decimal numbers and it will work. 125.00000000000003 -> 125

![image](https://user-images.githubusercontent.com/32926567/207197501-d4fcf01c-d27b-4809-9f9a-ae0b6e00f5d3.png)

**Comment by Thomas-MMJ** [comment]
I have a pull requrest that fixes this,

https://github.com/d8ahazard/sd_dreambooth_extension/pull/511
