### ISSUE TITLE
RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.cuda.FloatTensor) should be the same

### ISSUE THREAD

**Issue by kitoide** [d8ahazard/sd_dreambooth_extension#503]
I have a problem:

`Steps:  17%|█▋        | 501/3000 [11:44<5:08:08,  7.40s/it, loss=0.17, lr=1.72e-6, vram=5.7/13.3GB]Traceback (most recent call last):
2022-12-12T15:10:06.213809869Z   File "/workspace/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 956, in main
2022-12-12T15:10:06.213814599Z     noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
2022-12-12T15:10:06.213817899Z   File "/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
2022-12-12T15:10:06.213821349Z     return forward_call(*input, **kwargs)
2022-12-12T15:10:06.213824389Z   File "/venv/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 375, in forward
2022-12-12T15:10:06.213835629Z     sample = self.conv_in(sample)
2022-12-12T15:10:06.213838819Z   File "/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
2022-12-12T15:10:06.213842219Z     return forward_call(*input, **kwargs)
2022-12-12T15:10:06.213845279Z   File "/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 457, in forward
2022-12-12T15:10:06.213848629Z     return self._conv_forward(input, self.weight, self.bias)
2022-12-12T15:10:06.213851829Z   File "/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 453, in _conv_forward
2022-12-12T15:10:06.213855029Z     return F.conv2d(input, weight, bias, self.stride,
2022-12-12T15:10:06.213858029Z RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.cuda.FloatTensor) should be the same
2022-12-12T15:10:06.387969674Z `

**Comment by d8ahazard** [comment]
This has been fixed in the latest version.
