### ISSUE TITLE
"cannot optimize leaf tensor" on newest version of both base webui & dreambooth

### ISSUE THREAD

**Issue by ethansmith2000** [d8ahazard/sd_dreambooth_extension#509]
## Kindly read this ENTIRE form and fill it out with the requested information. It may seem tedious, but it's even more tedious asking basic questions to ensure I'm not trying to troubleshoot a bug I've already fixed. Help me help you, answer all the questions and follow the steps below before posting.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your issue will be automatically closed._**

`
Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Commit hash: 685f9631b56ff8bd43bce24ff5ce0f9a0e9af490
Installing requirements for Web UI
Skipping dreambooth installation.
Dreambooth revision is 6db38198c90caf8cfd17a2bd4ac0cba31f4b33d9
Diffusers version is 0.10.2
Torch version is 1.12.1+cu116
Torch vision version is  0.13.1+cu116
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yes
**Have you updated Dreambooth to the latest revision?**
yes
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
yes
**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
OK

**Describe the bug**

attempting to train SD2 at 512x512, any combination of parameters resulted in "cannot optimize leaf tensor" at start. Turning on "train ema" also gave an infinite recursive loop error in addition to the prior stated.

**Provide logs**
Initializing dreambooth training...
Replace CrossAttention.forward to use xformers
Checking concept: {'max_steps': -1, 'instance_data_dir': 'C:\\Users\\ethan\\Desktop\\dataset\\t_pose', 'class_data_dir': '', 'instance_prompt': '1@t character tpose', 'class_prompt': '', 'save_sample_prompt': '', 'save_sample_template': '', 'instance_token': '', 'class_token': '', 'num_class_images': 0, 'class_negative_prompt': '', 'class_guidance_scale': 7.5, 'class_infer_steps': 40, 'save_sample_negative_prompt': '', 'n_save_sample': 1, 'sample_seed': -1, 'save_guidance_scale': 7.5, 'save_infer_steps': 40}
Concept requires 0 images.
 Loaded model.
 Allocated: 0.0GB
 Reserved: 0.0GB

Traceback (most recent call last):
  File "C:\Users\ethan\Desktop\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 356, in start_training
    config, mem_record, msg = main(config, mem_record, use_subdir=use_subdir, lora_model=lora_model_name,
  File "C:\Users\ethan\Desktop\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 615, in main
    optimizer = optimizer_class(
  File "C:\Users\ethan\Desktop\stable-diffusion-webui\venv\lib\site-packages\torch\optim\adamw.py", line 91, in __init__
    super(AdamW, self).__init__(params, defaults)
  File "C:\Users\ethan\Desktop\stable-diffusion-webui\venv\lib\site-packages\torch\optim\optimizer.py", line 54, in __init__
    self.add_param_group(param_group)
  File "C:\Users\ethan\Desktop\stable-diffusion-webui\venv\lib\site-packages\torch\optim\optimizer.py", line 296, in add_param_group
    raise ValueError("can't optimize a non-leaf Tensor")
ValueError: can't optimize a non-leaf Tensor
 Training completed, reloading SD Model.
 Allocated: 0.0GB
 Reserved: 0.0GB

Memory output: {}
 Restored system models.
 Allocated: 2.4GB
 Reserved: 2.5GB

Returning result: Exception training model: can't optimize a non-leaf Tensor

<img width="850" alt="Screen Shot 2022-12-12 at 6 00 37 PM" src="https://user-images.githubusercontent.com/98723285/207176152-a6f2d30b-9845-46f1-9ebe-64c4b2d42513.png">

<img width="852" alt="Screen Shot 2022-12-12 at 6 00 27 PM" src="https://user-images.githubusercontent.com/98723285/207176191-80f67c04-c531-451e-9f78-07ea57cd7114.png">

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

**Environment**

What OS?
Windows 10

If Windows - WSL or native?
native

What GPU are you using?
RTX 3090

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the db_config.json file from /models/dreambooth/MODELNAME/db_config.json

**Comment by d8ahazard** [comment]
This is fixed with the latest version.
