### ISSUE TITLE
ValueError: could not convert string to float: 'constant'

### ISSUE THREAD

**Issue by LaikaSa** [d8ahazard/sd_dreambooth_extension#512]
`
Python revision: 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Dreambooth revision: cec6cbcf68c7aa58d85f0c8a6df503e89aaef455
SD-WebUI revision: 685f9631b56ff8bd43bce24ff5ce0f9a0e9af490

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.14.dev0 installed.
[+] torch version 1.12.1+cu116 installed.
[+] torchvision version 0.13.1+cu116 installed.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes
**Have you updated Dreambooth to the latest revision?**
Yes
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes
**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
Ok
**Describe the bug**

Updated to the newest commit and it seems to have a problem with the LR scheduler

**Provide logs**

Traceback (most recent call last):
  File "E:\Stable\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "E:\Stable\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 980, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "E:\Stable\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 891, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "E:\Stable\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 531, in preprocess
    return self._round_to_precision(x, self.precision)
  File "E:\Stable\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 493, in _round_to_precision
    return float(num)
ValueError: could not convert string to float: 'constant'
Please configure some concepts.

**Environment**
Window Native
What GPU are you using?
Nvidia RTX 3090

**Comment by LaikaSa** [comment]
Ok so I just restart the whole thing the problem above go away, seems to be working now.
