### ISSUE TITLE
NameError: name 'str2optimizer8bit_blockwise' is not defined

### ISSUE THREAD

**Issue by a-l-e-x-d-s-9** [d8ahazard/sd_dreambooth_extension#535]
All the information provided:
``` log
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
Commit hash: 685f9631b56ff8bd43bce24ff5ce0f9a0e9af490
Installing requirements for Web UI

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
Dreambooth revision: 9e3584f0edd2e64d284b6aaf9580ade5dcceed9d
SD-WebUI revision: 685f9631b56ff8bd43bce24ff5ce0f9a0e9af490

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.14.dev0 installed.
[+] torch version 1.12.1+cu113 installed.
[+] torchvision version 0.13.1+cu113 installed.
```

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes
**Have you updated Dreambooth to the latest revision?**
Yes
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes
**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
OK
**Describe the bug**
When starting training I see the following exception:

``` log
Traceback (most recent call last):
  File "/home/alex/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1042, in main
    optimizer.step()
  File "/home/alex/stable-diffusion-webui/venv/lib/python3.10/site-packages/accelerate/optimizer.py", line 134, in step
    self.scaler.step(self.optimizer, closure)
  File "/home/alex/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 338, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "/home/alex/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 285, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
  File "/home/alex/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/alex/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/optim/optimizer.py", line 113, in wrapper
    return func(*args, **kwargs)
  File "/home/alex/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/alex/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py", line 265, in step
    self.update_step(group, p, gindex, pindex)
  File "/home/alex/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/alex/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py", line 506, in update_step
    F.optimizer_update_8bit_blockwise(
  File "/home/alex/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/functional.py", line 858, in optimizer_update_8bit_blockwise
    str2optimizer8bit_blockwise[optimizer_name][0](
NameError: name 'str2optimizer8bit_blockwise' is not defined
```
This exception causing the training to fail.
If I run this line before: "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/resolve/libs/", the training is working but I'm getting this issue #534. Please help.

**Provide logs**

``` log
cd ~/stable-diffusion-webui/ && git pull && ./webui.sh --enable-insecure-extension-access --api --test-lora --ckptfix
Already up to date.

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on alex user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
Commit hash: 685f9631b56ff8bd43bce24ff5ce0f9a0e9af490
Installing requirements for Web UI

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
Dreambooth revision: 9e3584f0edd2e64d284b6aaf9580ade5dcceed9d
SD-WebUI revision: 685f9631b56ff8bd43bce24ff5ce0f9a0e9af490

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.14.dev0 installed.
[+] torch version 1.12.1+cu113 installed.
[+] torchvision version 0.13.1+cu113 installed.
#######################################################################################################




Launching Web UI with arguments: --enable-insecure-extension-access --api --test-lora --ckptfix --listen --xformers --force-enable-xformers
Dreambooth API layer loaded
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights [81761151] from /home/alex/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt
Loading VAE weights from: /home/alex/stable-diffusion-webui/models/Stable-diffusion/vae-ft-mse-840000-ema-pruned.vae.pt
Applying xformers cross attention optimization.
Model loaded.
Loaded a total of 1 textual inversion embeddings.
Embeddings: bad_prompt
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Returning [0.9, 0.999, 1e-08, 0.01, 'xformers', False, '', 0.0, 60.0, 1, True, False, True, 1e-05, 2e-05, 2e-05, 'constant', 500, 75, 100, 'fp16', True, 20, True, None, 1, 512, 1, True, 20000, 500, True, False, False, False, 1, True, True, False, False, False, True, '', 7.5, 40, 'ugly, disfigured, overlapping, blurred', 'photo of a beautiful dog', '', '/home/alex/Documents/Stable Diffusion/Dreambooth/TrainingTest/Dog_01/Source/', 'corgidog', '', 10000, 1, 50, -1, 7.5, 40, '', '', '', '', 7.5, 60, '', '', '', '', '', '', -1, 1, 0, -1, 7.5, 60, '', '', '', '', 7.5, 60, '', '', '', '', '', '', -1, 1, 0, -1, 7.5, 60, '', '', '', 'Loaded config.']
Returning [0.9, 0.999, 1e-08, 0.01, 'xformers', False, '', 0.0, 60.0, 1, True, False, True, 1e-05, 2e-05, 2e-05, 'constant', 500, 75, 100, 'fp16', True, 20, True, None, 1, 512, 1, True, 20000, 500, True, False, False, False, 1, True, True, False, False, False, True, '', 7.5, 40, 'ugly, disfigured, overlapping, blurred', 'photo of a beautiful dog', '', '/home/alex/Documents/Stable Diffusion/Dreambooth/TrainingTest/Dog_01/Source/', 'corgidog', '', 10000, 1, 50, -1, 7.5, 40, '', '', '', '', 7.5, 60, '', '', '', '', '', '', -1, 1, 0, -1, 7.5, 60, '', '', '', '', 7.5, 60, '', '', '', '', '', '', -1, 1, 0, -1, 7.5, 60, '', '', '', 'Loaded config.']
Concept 0 class dir is /home/alex/stable-diffusion-webui/models/dreambooth/Dreambooth_test_01_dog/classifiers_0
Starting Dreambooth training...
 Allocated 0.0/2.0GB 
 Reserved: 0.0/2.0GB 

Initializing dreambooth training...
Patching transformers to fix kwargs errors.
/home/alex/stable-diffusion-webui/venv/lib/python3.10/site-packages/transformers/generation_utils.py:24: FutureWarning: Importing `GenerationMixin` from `src/transformers/generation_utils.py` is deprecated and will be removed in Transformers v5. Import as `from transformers import GenerationMixin` instead.
  warnings.warn(
Replace CrossAttention.forward to use xformers
Checking concept: {'max_steps': 10000, 'instance_data_dir': '/home/alex/Documents/Stable Diffusion/Dreambooth/TrainingTest/Dog_01/Source/', 'class_data_dir': '', 'instance_prompt': 'corgidog', 'class_prompt': 'photo of a beautiful dog', 'save_sample_prompt': '', 'save_sample_template': '', 'instance_token': '', 'class_token': '', 'num_class_images': 50, 'class_negative_prompt': 'ugly, disfigured, overlapping, blurred', 'class_guidance_scale': 7.5, 'class_infer_steps': 40, 'save_sample_negative_prompt': '', 'n_save_sample': 1, 'sample_seed': -1, 'save_guidance_scale': 7.5, 'save_infer_steps': 40}
Concept requires 50 images.
Class image dir is not set, defaulting to /home/alex/stable-diffusion-webui/models/dreambooth/Dreambooth_test_01_dog/classifiers_0
Class dir /home/alex/stable-diffusion-webui/models/dreambooth/Dreambooth_test_01_dog/classifiers_0 has 50 images.
 Loaded model. 
 Allocated: 0.0GB 
 Reserved: 0.0GB 

Injecting trainable lora...

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
CUDA SETUP: Loading binary /home/alex/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
 Scheduler, EMA Loaded. 
 Allocated: 3.8GB 
 Reserved: 3.9GB 

***** Running training *****
  Num examples = 5
  Num batches each epoch = 5
  Num Epochs = 20
  Instantaneous batch size per device = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Gradient Accumulation steps = 1
  Total optimization steps = 100
  Actual steps: 100
   Training settings: CPU: False Adam: True, Prec: fp16, Grad: True, TextTr: True EM: False, LR: 1e-05 LORA:True 
 Allocated: 3.8GB 
 Reserved: 3.9GB 

Steps:   0%|                                                                                                                | 0/100 [00:00<?, ?it/s] Exception while training: name 'str2optimizer8bit_blockwise' is not defined 
 Allocated: 3.9GB 
 Reserved: 5.0GB 

Traceback (most recent call last):
  File "/home/alex/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1042, in main
    optimizer.step()
  File "/home/alex/stable-diffusion-webui/venv/lib/python3.10/site-packages/accelerate/optimizer.py", line 134, in step
    self.scaler.step(self.optimizer, closure)
  File "/home/alex/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 338, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "/home/alex/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 285, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
  File "/home/alex/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/alex/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/optim/optimizer.py", line 113, in wrapper
    return func(*args, **kwargs)
  File "/home/alex/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/alex/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py", line 265, in step
    self.update_step(group, p, gindex, pindex)
  File "/home/alex/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/alex/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py", line 506, in update_step
    F.optimizer_update_8bit_blockwise(
  File "/home/alex/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/functional.py", line 858, in optimizer_update_8bit_blockwise
    str2optimizer8bit_blockwise[optimizer_name][0](
NameError: name 'str2optimizer8bit_blockwise' is not defined
|===========================================================================|
|                  PyTorch CUDA memory summary, device ID 0                 |
|---------------------------------------------------------------------------|
|            CUDA OOMs: 0            |        cudaMalloc retries: 0         |
|===========================================================================|
|        Metric         | Cur Usage  | Peak Usage | Tot Alloc  | Tot Freed  |
|---------------------------------------------------------------------------|
| Allocated memory      |    3944 MB |    4714 MB |   30166 MB |   26221 MB |
|       from large pool |    3898 MB |    4671 MB |   29543 MB |   25645 MB |
|       from small pool |      45 MB |      63 MB |     622 MB |     576 MB |
|---------------------------------------------------------------------------|
| Active memory         |    3944 MB |    4714 MB |   30166 MB |   26221 MB |
|       from large pool |    3898 MB |    4671 MB |   29543 MB |   25645 MB |
|       from small pool |      45 MB |      63 MB |     622 MB |     576 MB |
|---------------------------------------------------------------------------|
| GPU reserved memory   |    5134 MB |    5134 MB |    7214 MB |    2080 MB |
|       from large pool |    5066 MB |    5066 MB |    7072 MB |    2006 MB |
|       from small pool |      68 MB |      68 MB |     142 MB |      74 MB |
|---------------------------------------------------------------------------|
| Non-releasable memory |  118495 KB |  515409 KB |   29455 MB |   29339 MB |
|       from large pool |  103632 KB |  514256 KB |   28712 MB |   28610 MB |
|       from small pool |   14863 KB |   14885 KB |     743 MB |     728 MB |
|---------------------------------------------------------------------------|
| Allocations           |    1628    |    1780    |    9122    |    7494    |
|       from large pool |     343    |     402    |    3493    |    3150    |
|       from small pool |    1285    |    1394    |    5629    |    4344    |
|---------------------------------------------------------------------------|
| Active allocs         |    1628    |    1780    |    9122    |    7494    |
|       from large pool |     343    |     402    |    3493    |    3150    |
|       from small pool |    1285    |    1394    |    5629    |    4344    |
|---------------------------------------------------------------------------|
| GPU reserved segments |     158    |     158    |     272    |     114    |
|       from large pool |     124    |     124    |     201    |      77    |
|       from small pool |      34    |      34    |      71    |      37    |
|---------------------------------------------------------------------------|
| Non-releasable allocs |     116    |     124    |    3799    |    3683    |
|       from large pool |      55    |      61    |    1977    |    1922    |
|       from small pool |      61    |      69    |    1822    |    1761    |
|---------------------------------------------------------------------------|
| Oversize allocations  |       0    |       0    |       0    |       0    |
|---------------------------------------------------------------------------|
| Oversize GPU segments |       0    |       0    |       0    |       0    |
|===========================================================================|

 CLEANUP:  
 Allocated: 3.9GB 
 Reserved: 5.0GB 

 Cleanup completed. 
 Allocated: 3.9GB 
 Reserved: 4.0GB 

 Cleanup Complete. 
 Allocated: 3.9GB 
 Reserved: 4.0GB 

Steps:   0%|                                                                                                                | 0/100 [00:02<?, ?it/s]
 Training completed, reloading SD Model. 
 Allocated: 0.0GB 
 Reserved: 3.8GB 

Memory output: {}
 Restored system models. 
 Allocated: 2.0GB 
 Reserved: 3.8GB 

Returning result: Training finished. Total lifetime steps: 5820 
```

**Environment**
What OS?
Ubuntu 22.04
Linux Venus 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
If Windows - WSL or native?
No
What GPU are you using?
RTX 2080 8GB
Driver Version: 525.60.13
CUDA Version: 12.0
**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the db_config.json file from /models/dreambooth/MODELNAME/db_config.json

**Comment by a-l-e-x-d-s-9** [comment]
This issue probably just a setup problem in my system.

**Comment by AshDevFr** [comment]
Hi, 
I am having the exact same issue, were you able to fix yours?

**Comment by a-l-e-x-d-s-9** [comment]
@AshDevFr 
No, I still need to execute "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/resolve/libs/" before using webui.
I suppose I can add it to ".bashrc". 
Now I also have "Could not load dynamic library 'libnvinfer.so.7'" error, but it seems not to influence anything I do, not sure what to do about...

**Comment by thr3a** [comment]
I also faced the same issue and it was resolved by downgrading the CUDA version from 12 to 11.
