### ISSUE TITLE
CPU training "No operator found for this attention: {self}"

### ISSUE THREAD

**Issue by kokakin** [d8ahazard/sd_dreambooth_extension#55]
Hello devs, thank you for this wonderful project!
I installed dreambooth as an extension on the Automatic1111 Web UI on a Windows 11 machine. The machine has a GTX1050ti and a i7 processor. It is not enough to run dreambooth on the GPU, so I am trying the CPU option. I am running webui-user.bat with no arguments and with the pytorch line set as per instructions:

@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS= --xformers --medvram --no-half
set TORCH_COMMAND="pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116"

call webui.bat

I am currently trying to run the program using no mixed precision and CPU training, but I am getting an error. I investigated and I suspect that the program is trying to access my GPU for some reason and throwing the error, even though i checked the CPU option.

Here's the output of the error:
-------------------------------------------------------------------------------------------------------------------------------------------------
Starting Dreambooth training...
 VRAM cleared.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Loaded model.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Scheduler Loaded
 Allocated: 0.0GB
 Reserved: 0.0GB

Steps:   0%|                                                                                  | 0/2100 [00:00<?, ?it/s]Error completing request
Arguments: ('ModelName', 'C:\\GenericPath', '', 'placeholder', 'placeholder', 'placeholder', 'placeholder', 2.0, 7.5, 40.0, 0, 512, False, True, 1, 1, 1, 2100, 4, True, 5e-06, False, 'linear', 0, True, 0.9, 0.999, 0.01, 1e-08, 1, 100, 1000, 'no', True, '', True, False, False) {}
Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "C:\AI\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "C:\AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 265, in start_training
    trained_steps = main(config)
  File "C:\AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 827, in main
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 307, in forward
    sample, res_samples = downsample_block(
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 593, in forward
    hidden_states = torch.utils.checkpoint.checkpoint(
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\utils\checkpoint.py", line 235, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\utils\checkpoint.py", line 96, in forward
    outputs = run_function(*args)
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 586, in custom_forward
    return module(*inputs, return_dict=return_dict)
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\attention.py", line 204, in forward
    hidden_states = block(hidden_states, context=encoder_hidden_states, timestep=timestep)
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\attention.py", line 406, in forward
    hidden_states = self.attn1(norm_hidden_states) + hidden_states
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\attention.py", line 495, in forward
    hidden_states = self._memory_efficient_attention_xformers(query, key, value)
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\attention.py", line 556, in _memory_efficient_attention_xformers
    hidden_states = xformers.ops.memory_efficient_attention(query, key, value, attn_bias=None)
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\xformers\ops.py", line 858, in memory_efficient_attention
    ).op
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\xformers\ops.py", line 726, in op
    raise NotImplementedError(f"No operator found for this attention: {self}")
NotImplementedError: No operator found for this attention: AttentionOpDispatch(dtype=torch.float32, device=device(type='cpu'), k=40, has_dropout=False, attn_bias_type=<class 'NoneType'>, kv_len=4096, q_len=4096, kv=40, batch_size=8, num_heads=1)

Steps:   0%|                                                                                  | 0/2100 [00:09<?, ?it/s]
------------------------------------------------------------------------------------------------------------------------------------------------

I'm sorry for not writing it in markdown as I'm a complete noob, but I hope you can help me regardless...
Thanks again for the wonderful tool!

**Comment by poondoggle** [comment]
I am also getting the same error above. Same settings. Any clue what may be causing the issue?

**Comment by AlUlkesh** [comment]
Maybe this will help finding the issue:

Since the error seems to come from xformers-modules I temporarily renamed the two xformers folders in ...Lib\site-packages\ and started webui without --xformers.

It's working now.

**Comment by kokakin** [comment]
> Maybe this will help finding the issue:
> 
> Since the error seems to come from xformers-modules I temporarily renamed the two xformers folders in ...Lib\site-packages\ and started webui without --xformers.
> 
> It's working now.

Hey, it seemed to work, I'm getting through the first steps now! thanks a lot! I'll keep in mind to disable xformers in the arguments and in the env folder to train with dreambooth.
