### ISSUE TITLE
ImportError: cannot import name 'get_lora_models' after update

### ISSUE THREAD

**Issue by DaveScream** [d8ahazard/sd_dreambooth_extension#555]
I updated extension with web-ui interface and get this error at start, no DreamBooth tab now.

Reloading custom scripts
Dreambooth API layer loaded
Error loading script: main.py
Traceback (most recent call last):
  File "C:\Software\Stable_Diffusion\stable-diffusion-webui\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\Software\Stable_Diffusion\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\Software\Stable_Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py", line 9, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.utils import get_db_models, log_memory, generate_sample_img, \
ImportError: cannot import name 'get_lora_models' from 'extensions.sd_dreambooth_extension.dreambooth.utils' (C:\Software\Stable_Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\utils.py)

Reloading modules: modules.ui
Refreshing Model List
Restarting Gradio
Running on local URL:  http://127.0.0.1:7860

**Comment by DaveScream** [comment]
deleted sd-dreambooth folder in extensions and reinstalled extension. Works good.
