### ISSUE TITLE
PIL error when training with class images

### ISSUE THREAD

**Issue by randaller** [d8ahazard/sd_dreambooth_extension#584]
## Kindly read this ENTIRE form and fill it out with the requested information. It may seem tedious, but it's even more tedious asking basic questions to ensure I'm not trying to troubleshoot a bug I've already fixed. Help me help you, answer all the questions and follow the steps below before posting.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your issue will be automatically closed._**

`
Python 3.10.8 | packaged by conda-forge | (main, Nov 24 2022, 14:07:00) [MSC v.1916 64 bit (AMD64)]
Commit hash: 685f9631b56ff8bd43bce24ff5ce0f9a0e9af490
Installing requirements for Web UI

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.8 | packaged by conda-forge | (main, Nov 24 2022, 14:07:00) [MSC v.1916 64 bit (AMD64)]
Dreambooth revision: c678a431b5d79ba7e1c38d7629ca7e0c79166a1f
SD-WebUI revision: 685f9631b56ff8bd43bce24ff5ce0f9a0e9af490

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.14.dev0 installed.
[+] torch version 1.12.1+cu113 installed.
[+] torchvision version 0.13.1+cu113 installed.
#######################################################################################################

Launching Web UI with arguments: --api --xformers
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes

**Have you updated Dreambooth to the latest revision?**
Yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
OK

**Describe the bug**

When training with LoRA and using class images, training sometimes ok, and sometimes interrupted with error:

PIL.UnidentifiedImageError: cannot identify image file 'D:\\Dev\\NN\\github\\pytorch\\stable-diffusion-webui\\venv\\Lib\\site-packages\\numpy\\core\\tests\\data\\recarray_from_file.fits'

**Provide logs**

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

**Environment**

Windows 10 (server 2022)

If Windows - WSL or native?
Native, Anaconda python

What GPU are you using?
GTX 3070Ti

**Screenshots/Config**
`
    "concepts_list": [
        {
            "max_steps": -1,
            "instance_data_dir": "D:\\Dev\\NN\\github\\pytorch\\stable-diffusion-webui\\datasets\\k2",
            "class_data_dir": "",
            "instance_prompt": "bp, [filewords]",
            "class_prompt": "[filewords]",
            "save_sample_prompt": "a portrait of a bp, trending on artstation, greg rutkowski, 4k",
            "save_sample_template": "",
            "instance_token": "bp",
            "class_token": "",
            "num_class_images": 500,
            "class_negative_prompt": "",
            "class_guidance_scale": 7.5,
            "class_infer_steps": 40,
            "save_sample_negative_prompt": "",
            "n_save_sample": 1,
            "sample_seed": -1,
            "save_guidance_scale": 7.5,
            "save_infer_steps": 40
        }
    ],
`
![screen1](https://user-images.githubusercontent.com/22396871/208420338-0fd255de-e9de-4bde-849a-be122277b33b.jpg)

**Comment by leppie** [comment]
This happens when you dont set the class image path. (it is a bug)

**Comment by randaller** [comment]
But I am never setting path to class images, only setting value around 500 in class img count, and in the most cases training goes well.

**Comment by ekeric13** [comment]
I am hitting this too
```
Exception while training: cannot identify image file '/home/ubuntu/work/stable-diffusion-webui/venv/lib/python3.8/site-packages/numpy/core/tests/data/recarray_from_file.fits' 
```

```
Traceback (most recent call last):
  File "/home/ubuntu/work/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 987, in main
    for step, batch in enumerate(train_dataloader):
  File "/home/ubuntu/work/stable-diffusion-webui/venv/lib/python3.8/site-packages/accelerate/data_loader.py", line 383, in __iter__
    next_batch = next(dataloader_iter)
  File "/home/ubuntu/work/stable-diffusion-webui/venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/home/ubuntu/work/stable-diffusion-webui/venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/ubuntu/work/stable-diffusion-webui/venv/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/work/stable-diffusion-webui/venv/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/work/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/SuperDataset.py", line 270, in __getitem__
    class_image = Image.open(class_data.image)
  File "/home/ubuntu/work/stable-diffusion-webui/venv/lib/python3.8/site-packages/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file '/home/ubuntu/work/stable-diffusion-webui/venv/lib/python3.8/site-packages/numpy/core/tests/data/recarray_from_file.fits'
```

 @leppie what do you mean by "class image path"?
Do you mean this input box?

<img width="477" alt="Screenshot 2022-12-21 at 8 07 23 PM" src="https://user-images.githubusercontent.com/6489651/209053519-e1f82ec8-dd4c-4261-b430-34de7a85f025.png">

I thought it uses a default directory. I see them being created in `stable-diffusion-webui/models/dreambooth/modename`.

It correctly finished generating all the images and then randomly failed when doing the dreambooth diffusion model training

**Comment by art-phony** [comment]
I believe I am experiencing same issue.
It seems fine just after starting the training, but after about 100~1500steps, I get the following error.

```
Exception while training: cannot identify image file 'E:\\AI_Drawing\\automatic1111\\stable-diffusion-webui\\venv\\Lib\\site-packages\\numpy\\core\\tests\\data\\recarray_from_file.fits'
 Allocated: 14.9GB
 Reserved: 22.0GB

Traceback (most recent call last):
  File "E:\AI_Drawing\automatic1111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 987, in main
    for step, batch in enumerate(train_dataloader):
  File "E:\AI_Drawing\automatic1111\stable-diffusion-webui\venv\lib\site-packages\accelerate\data_loader.py", line 383, in __iter__
    next_batch = next(dataloader_iter)
  File "E:\AI_Drawing\automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\dataloader.py", line 681, in __next__
    data = self._next_data()
  File "E:\AI_Drawing\automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "E:\AI_Drawing\automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\AI_Drawing\automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\AI_Drawing\automatic1111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\SuperDataset.py", line 270, in __getitem__
    class_image = Image.open(class_data.image)
  File "E:\AI_Drawing\automatic1111\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file 'E:\\AI_Drawing\\automatic1111\\stable-diffusion-webui\\venv\\Lib\\site-packages\\numpy\\core\\tests\\data\\recarray_from_file.fits'
```

**Comment by ekeric13** [comment]
@art-phony When I set the "Classification Dataset Directory" input to a real value elsewhere on my filesystem it does avoid this error. So I think @leppie is right about it being a bug when it uses its own default directory.

**Comment by art-phony** [comment]
Thank you for advice! I'll try it!

**Comment by d8ahazard** [comment]
This has been fixed with the latest release:

https://github.com/d8ahazard/sd_dreambooth_extension/commit/15244fef18c35864be6f6c2e1c0237dadc5415c1
