### ISSUE TITLE
Extension could not start on google colab TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by ThanapatSornsrivichai** [d8ahazard/sd_dreambooth_extension#593]
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 685f9631b56ff8bd43bce24ff5ce0f9a0e9af490
Installing requirements for Web UI
Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: c678a431b5d79ba7e1c38d7629ca7e0c79166a1f
SD-WebUI revision: 685f9631b56ff8bd43bce24ff5ce0f9a0e9af490

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[ ] xformers version N/A installed.
[+] torch version 1.12.1+cu113 installed.
[+] torchvision version 0.13.1+cu113 installed.
`
Dreambooth extension is not working on google colab but works on local.
I assume it should be the requirement was not install properly on colab.
 
Clean Install and run on (gdrive) local to make sure it works and got the requirement for dreambooth.
After that I open google colab and run on the same directory as tested on local and got this error.

**Provide logs**

Error loading script: api.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/api.py", line 10, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.sd_to_diff import extract_checkpoint
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/sd_to_diff.py", line 36, in <module>
    from diffusers import (
ImportError: cannot import name 'HeunDiscreteScheduler' from 'diffusers' (/usr/local/lib/python3.8/dist-packages/diffusers/__init__.py)

Error loading script: main.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 5, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.diff_to_sd import compile_checkpoint
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/diff_to_sd.py", line 214, in <module>
    def convert_text_enc_state_dict_v20(text_enc_dict: dict[str, torch.Tensor]):
TypeError: 'type' object is not subscriptable

**Environment**

https://colab.research.google.com/drive/1hjOwCfwC3JM5yfd-bY4UnaoGz5B6srPt?usp=sharing
Google colab pro+ on T4 GPU

**Comment by ThanapatSornsrivichai** [comment]
I've tried manually install the requirement with 
pip install -r /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/requirements.txt

Got the prompt saying that runtime need to be restarted. But if I do, colab will just lose all the install I've made.
![image](https://user-images.githubusercontent.com/36567807/208821512-6d8269af-6042-4e1f-8779-542108915725.png)

If I don't restart and try to run the webui I got this error.

Dreambooth API layer loaded
Error loading script: main.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 5, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.diff_to_sd import compile_checkpoint
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/diff_to_sd.py", line 214, in <module>
    def convert_text_enc_state_dict_v20(text_enc_dict: dict[str, torch.Tensor]):
TypeError: 'type' object is not subscriptable

LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Downloading100% 1.71G/1.71G [00:32<00:00, 53.4MB/s]
Loading weights ...

**Comment by ThanapatSornsrivichai** [comment]
I've done these two steps and it works now.
pip install -r /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/requirements.txt

https://github.com/TheLastBen/fast-stable-diffusion/issues/914#issuecomment-1349155573
Having done that you should be left with one last error message :

def convert_text_enc_state_dict_v20(text_enc_dict: dict[str, torch.Tensor]):
TypeError: 'type' object is not subscriptable

This seem to be a Python3.8 problem (i think doesn't happen with Python 3.11). So open the file "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/diff_to_sd.py" and then delete the type hint from the parameter of the function so change def convert_text_enc_state_dict_v20(text_enc_dict: dict[str, torch.Tensor]): to def convert_text_enc_state_dict_v20(text_enc_dict). Also change def convert_text_enc_state_dict(text_enc_dict: dict[str, torch.Tensor]) to def convert_text_enc_state_dict(text_enc_dict):. These two deletions are 100% safe.

**Comment by ThanapatSornsrivichai** [comment]
Now that dreambooth is able to start on webui after I hit train I got this error instead.
![image](https://user-images.githubusercontent.com/36567807/208826911-98580d47-9af4-4473-ae97-66def9a7d6b1.png)

**Comment by ThanapatSornsrivichai** [comment]
Initializing dreambooth training...
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dreambooth.py", line 361, in start_training
    from extensions.sd_dreambooth_extension.dreambooth.train_dreambooth import main
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 359, in <module>
    def main(args: DreamboothConfig, memory_record, use_subdir, lora_model=None, lora_alpha=1.0, lora_txt_alpha=1.0, custom_model_name="") -> tuple[
TypeError: 'type' object is not subscriptable
 Training completed, reloading SD Model. 
 Allocated: 0.0GB 
 Reserved: 0.0GB 

Memory output: {}
 Restored system models. 
 Allocated: 2.2GB 
 Reserved: 2.2GB 

Returning result: Exception training model: 'type' object is not subscriptable
