### ISSUE TITLE
Initializing Dreambooth Fail

### ISSUE THREAD

**Issue by MrKurtzmann** [d8ahazard/sd_dreambooth_extension#599]
Python revision: 3.10.9 (main, Dec 15 2022, 17:11:09) [Clang 14.0.0 (clang-1400.0.29.202)]
Dreambooth revision: 633ca33e8ca3d55a5a09a98b3ea6975bd8ffec29
SD-WebUI revision: 685f9631b56ff8bd43bce24ff5ce0f9a0e9af490

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[ ] xformers version N/A installed.
[+] torch version 1.12.1 installed.
[+] torchvision version 0.13.1 installed.

**Describe the bug**

Hello,
after installing DreamBooth via the Web UI interface and then restarting webui.sh via the terminal as usual, it does not start anymore.

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on luis user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Python 3.10.9 (main, Dec 15 2022, 17:11:09) [Clang 14.0.0 (clang-1400.0.29.202)]
Commit hash: 685f9631b56ff8bd43bce24ff5ce0f9a0e9af490
Installing requirements for Web UI

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.9 (main, Dec 15 2022, 17:11:09) [Clang 14.0.0 (clang-1400.0.29.202)]
Dreambooth revision: 633ca33e8ca3d55a5a09a98b3ea6975bd8ffec29
SD-WebUI revision: 685f9631b56ff8bd43bce24ff5ce0f9a0e9af490

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[ ] xformers version N/A installed.
[+] torch version 1.12.1 installed.
[+] torchvision version 0.13.1 installed.
#######################################################################################################

Error running install.py for extension extensions/sd-dynamic-prompts.
Command: "/opt/homebrew/opt/python@3.10/bin/python3.10" "extensions/sd-dynamic-prompts/install.py"
Error code: 1
stdout: Installing spacy==3.0.8

stderr: Traceback (most recent call last):
  File "/Users/luis/stable-diffusion-webui/extensions/sd-dynamic-prompts/install.py", line 8, in <module>
    launch.run_pip("install spacy==3.0.8", desc='spacy==3.0.8')
  File "/Users/luis/stable-diffusion-webui/launch.py", line 78, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "/Users/luis/stable-diffusion-webui/launch.py", line 49, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install spacy==3.0.8.
Command: "/opt/homebrew/opt/python@3.10/bin/python3.10" -m pip install spacy==3.0.8 --prefer-binary
Error code: 1
stdout: Collecting spacy==3.0.8
  Using cached spacy-3.0.8.tar.gz (989 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

stderr:   error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Error in sitecustomize; set PYTHONVERBOSE for traceback:
      AssertionError:
      Traceback (most recent call last):
        File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 10, in <module>
      ModuleNotFoundError: No module named 'Cython'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

Launching Web UI with arguments: --no-half --use-cpu interrogate
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
No module 'xformers'. Proceeding without it.
Error loading script: evaluate_model.py
Traceback (most recent call last):
  File "/Users/luis/stable-diffusion-webui/modules/scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/Users/luis/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/Users/luis/stable-diffusion-webui/extensions/DreamBoothMac/scripts/evaluate_model.py", line 16, in <module>
    from ldm.data.personalized import PersonalizedBase
ModuleNotFoundError: No module named 'ldm.data.personalized'

Error loading script: inpaint.py
Traceback (most recent call last):
  File "/Users/luis/stable-diffusion-webui/modules/scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/Users/luis/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/Users/luis/stable-diffusion-webui/extensions/DreamBoothMac/scripts/inpaint.py", line 7, in <module>
    from main import instantiate_from_config
  File "/Users/luis/stable-diffusion-webui/extensions/DreamBoothMac/main.py", line 21, in <module>
    from ldm.data.base import Txt2ImgIterableBaseDataset
ModuleNotFoundError: No module named 'ldm.data.base'

Dreambooth API layer loaded
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Error verifying pickled file from /Users/luis/.cache/huggingface/hub/models--openai--clip-vit-large-patch14/snapshots/8d052a0f05efbaefbc9e8786ba291cfdf93e5bff/pytorch_model.bin:
Traceback (most recent call last):
  File "/Users/luis/stable-diffusion-webui/extensions/sd_dreambooth_extension/reallysafe.py", line 88, in check_pt
    with zipfile.ZipFile(filename) as z:
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/zipfile.py", line 1267, in __init__
    self._RealGetContents()
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/zipfile.py", line 1334, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/luis/stable-diffusion-webui/extensions/sd_dreambooth_extension/reallysafe.py", line 142, in load_with_extra
    check_pt(filename, extra_handler)
  File "/Users/luis/stable-diffusion-webui/extensions/sd_dreambooth_extension/reallysafe.py", line 109, in check_pt
    unpickler.load()
_pickle.UnpicklingError: persistent IDs in protocol 0 must be ASCII strings

-----> !!!! The file is most likely corrupted !!!! <-----
You can skip this check with --disable-safe-unpickle commandline argument, but that is not going to help you.

Traceback (most recent call last):
  File "/Users/luis/stable-diffusion-webui/launch.py", line 295, in <module>
    start()
  File "/Users/luis/stable-diffusion-webui/launch.py", line 290, in start
    webui.webui()
  File "/Users/luis/stable-diffusion-webui/webui.py", line 132, in webui
    initialize()
  File "/Users/luis/stable-diffusion-webui/webui.py", line 62, in initialize
    modules.sd_models.load_model()
  File "/Users/luis/stable-diffusion-webui/modules/sd_models.py", line 308, in load_model
    sd_model = instantiate_from_config(sd_config.model)
  File "/Users/luis/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/Users/luis/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 563, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "/Users/luis/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 630, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "/Users/luis/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/Users/luis/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/encoders/modules.py", line 100, in __init__
    self.transformer = CLIPTextModel.from_pretrained(version)
  File "/opt/homebrew/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2258, in from_pretrained
    loaded_state_dict_keys = [k for k in state_dict.keys()]
AttributeError: 'NoneType' object has no attribute 'keys'

**Environment**
Mac OS 13.1 m1 Max

**Comment by MrKurtzmann** [comment]
I waited a few days, tried again and the Installation worked. thx!
