### ISSUE TITLE
Debug tab - generate sample image bug

### ISSUE THREAD

**Issue by mediocreatmybest** [d8ahazard/sd_dreambooth_extension#618]
## Kindly read this ENTIRE form and fill it out with the requested information. It may seem tedious, but it's even more tedious asking basic questions to ensure I'm not trying to troubleshoot a bug I've already fixed. Help me help you, answer all the questions and follow the steps below before posting.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your issue will be automatically closed._**

`
Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Commit hash: ****************************************
Installing requirements for Web UI
Skipping dreambooth installation.
Dreambooth revision is ****************************************
Diffusers version is *.*.*.
Torch version is *.*.*.
Torch vision version is *.*.*.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes

**Have you updated Dreambooth to the latest revision?**
Yes
commit 9bd3ad2c2e97057370fd62d40f9a7aed6539f005
Author: ekeric13 <ekeric13@gmail.com>
commit c5cb58328c555ac27679422b1da940a9b19de6f2 (HEAD -> main, origin/main, origin/HEAD)
Merge: 633ca33 9bd3ad2
Author: d8ahazard <d8ahazard@gmail.com>
Date:   Thu Dec 22 17:38:10 2022 -0600

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
Dreambooth revision: c5cb58328c555ac27679422b1da940a9b19de6f2
SD-WebUI revision: 685f9631b56ff8bd43bce24ff5ce0f9a0e9af490

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.15+7e05e2c.d20221223 installed.
[+] torch version 1.12.1+cu113 installed.
[+] torchvision version 0.13.1+cu113 installed.

#######################################################################################################

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**
Ok

**Describe the bug**
 When using Debug Tab with the SD2.1 model, ([v2-1_768-nonema-pruned.ckpt](https://huggingface.co/stabilityai/stable-diffusion-2-1/blob/main/v2-1_768-nonema-pruned.ckpt)) with the extracted model selection. Trying to generate a sample image with a prompt produces the following error. (After further checking, seems to be produced in both Windows and Linux with SD1.5 and SD2.1)

```
Loading model from /home/machinelearning/stable-diffusion-webui/models/dreambooth/SD21_768nonema/working.
Exception generating sample!
Traceback (most recent call last):
  File "/home/machinelearning/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/utils.py", line 283, in generate_sample_img
    image = pipeline(save_sample_prompt,
  File "/home/machinelearning/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
TypeError: StableDiffusionPipeline.__call__() got an unexpected keyword argument 'scheduler'
 Restored system models.
 Allocated: 5.1GB
 Reserved: 5.1GB

```
This is produced in both Windows and Linux.

(A clear and concise description of what the bug is)

**Provide logs**

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

```
Loading model from /home/machinelearning/stable-diffusion-webui/models/dreambooth/TheMastersV1/working.
Exception generating sample!
Traceback (most recent call last):
  File "/home/machinelearning/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/utils.py", line 283, in generate_sample_img
    image = pipeline(save_sample_prompt,
  File "/home/machinelearning/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
TypeError: StableDiffusionPipeline.__call__() got an unexpected keyword argument 'scheduler'
 Restored system models.
 Allocated: 4.3GB
 Reserved: 4.3GB

Loading model from checkpoint.
Loading checkpoint...
v1 model loaded.
Creating scheduler...
Converting unet...
Converting vae...
Converting text encoder...
Saving diffusers model...
 Restored system models.
 Allocated: 2.0GB
 Reserved: 2.8GB

 Allocated 2.0/2.0GB
 Reserved: 2.8/2.8GB

Checkpoint successfully extracted to /home/machinelearning/stable-diffusion-webui/models/dreambooth/TestEMA/working
 Allocated 0.0/2.0GB
 Reserved: 0.0/2.8GB

Loading model from /home/machinelearning/stable-diffusion-webui/models/dreambooth/TestEMA/working.
Exception generating sample!
Traceback (most recent call last):
  File "/home/machinelearning/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/utils.py", line 283, in generate_sample_img
    image = pipeline(save_sample_prompt,
  File "/home/machinelearning/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
TypeError: StableDiffusionPipeline.__call__() got an unexpected keyword argument 'scheduler'
 Restored system models.
 Allocated: 4.3GB
 Reserved: 4.3GB
```

**Environment**

What OS?
Linux Jammy 

If Windows - WSL or native?

What GPU are you using?
3060 12GB vRAM

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the db_config.json file from /models/dreambooth/MODELNAME/db_config.json

**Comment by glitchyg** [comment]
Wanted to add that I am experience this same issue on M1 Max Mac as well

**Comment by d8ahazard** [comment]
Hello, please update/restart and try with the latest version:

https://github.com/d8ahazard/sd_dreambooth_extension/commit/15244fef18c35864be6f6c2e1c0237dadc5415c1

**Comment by mediocreatmybest** [comment]
Awesome will do. 👍
