### ISSUE TITLE
large concept lists suffers from this pop from empty list issue

### ISSUE THREAD

**Issue by Pychnight** [d8ahazard/sd_dreambooth_extension#624]
## Kindly read this ENTIRE form and fill it out with the requested information. It may seem tedious, but it's even more tedious asking basic questions to ensure I'm not trying to troubleshoot a bug I've already fixed. Help me help you, answer all the questions and follow the steps below before posting.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your issue will be automatically closed._**

`
Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Commit hash: c6f347b81f584b6c0d44af7a209983284dbb52d2
Installing requirements for Web UI
Skipping dreambooth installation.
bitsandbytes version 0.35.0.
diffusers version 0.10.2.
transformers version 4.25.1.
xformers version 0.0.14.dev0.
torch version 1.12.1+cu116.
torchvision version 0.13.1+cu116.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**

Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**

Yes

**Have you updated Dreambooth to the latest revision?**

yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**

yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**

OK

**Describe the bug**

Build a concept list of 10+ items and see what happens.

Having a large concept list causes this pop from empty list issue,

I have double checked the list and ensured all data within that list has valid paths and non-corrupt image files, i have also tried other settings but always get out of memory error. I have managed to  get lucky and fully tain a model with a list of 4 concepts but it seems that was just luck... and can't get it working anymore

Settings

Mixed percision: fp16
Memory: Flash attention

**Provide logs**

```
Traceback (most recent call last):
  File "C:\Users\person\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 987, in main
    for step, batch in enumerate(train_dataloader):
  File "C:\Users\person\Documents\GitHub\stable-diffusion-webui\venv\lib\site-packages\accelerate\data_loader.py", line 383, in __iter__
    next_batch = next(dataloader_iter)
  File "C:\Users\person\Documents\GitHub\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\dataloader.py", line 681, in __next__
    data = self._next_data()
  File "C:\Users\person\Documents\GitHub\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\person\Documents\GitHub\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\war45\Documents\GitHub\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\person\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\SuperDataset.py", line 259, in __getitem__
    instance_data = concept_data.get_instance_image()
  File "C:\Users\person\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\SuperDataset.py", line 66, in get_instance_image
    index = self.instance_indices.pop()
IndexError: pop from empty list
```

**Environment**

What OS?

Windows 11

If Windows - WSL or native?

Native

What GPU are you using?

evga 3080 TI (12 gb)

**Screenshots/Config**

seems to be effected in any model just need a large concept list even effects freshly made models.

**Comment by d8ahazard** [comment]
This should be fixed with the latest version:

https://github.com/d8ahazard/sd_dreambooth_extension/commit/15244fef18c35864be6f6c2e1c0237dadc5415c1
