### ISSUE TITLE
Error "please configure some concepts" when training model

### ISSUE THREAD

**Issue by AllanElleuch** [d8ahazard/sd_dreambooth_extension#630]
## Kindly read this ENTIRE form and fill it out with the requested information. It may seem tedious, but it's even more tedious asking basic questions to ensure I'm not trying to troubleshoot a bug I've already fixed. Help me help you, answer all the questions and follow the steps below before posting.

Hi dear community,

To make it short, I am having the error **"please configure some concepts"** when training my model. However I am filling up everything neccesary for the concept. The error is too general for me to spot the specific issue. Maybe a more trained eyes could help me by watching my configuration. 

See below the screennshot:

![image](https://user-images.githubusercontent.com/19656515/209829742-55ed02de-d90a-44f6-941c-90e18d6cd6f4.png)

**Please find the following lines in the console and paste them below. _If you do not provide this information, your issue will be automatically closed._**

```
Python 3.9.13 (main, Aug 25 2022, 23:26:10) 
Commit hash: 4af3ca5393151d61363c30eef4965e694eeac15e
Installing requirements for Web UI
Skipping dreambooth installation.
Dreambooth revision is c5cb58328c555ac27679422b1da940a9b19de6f2
SD-webui revision is c6f347b81f584b6c0d44af7a209983284dbb52d2
Diffusers version is (where can I find this one?)
Torch version is torch==1.12.1+cu113
Torch vision version is torchvision==0.13.1+cu113
```

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yes
**Have you updated Dreambooth to the latest revision?**
yes
**Have you updated the Stable-Diffusion-WebUI to the latest version?**

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this. Reply 'OK' Below to acknowledge that you did this.**

**Describe the bug**

(A clear and concise description of what the bug is)

**Provide logs**

```
################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on user user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Python 3.9.13 (main, Aug 25 2022, 23:26:10) 
[GCC 11.2.0]
Commit hash: 4af3ca5393151d61363c30eef4965e694eeac15e
Installing requirements for Web UI

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.9.13 (main, Aug 25 2022, 23:26:10) 
[GCC 11.2.0]
Dreambooth revision: c5cb58328c555ac27679422b1da940a9b19de6f2
SD-WebUI revision: 4af3ca5393151d61363c30eef4965e694eeac15e

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[ ] xformers version N/A installed.
[+] torch version 1.12.1+cu113 installed.
[+] torchvision version 0.13.1+cu113 installed.
#######################################################################################################

Launching Web UI with arguments: --port=8888 --listen --enable-insecure-extension-access
No module 'xformers'. Proceeding without it.
Dreambooth API layer loaded
Loading config from: /home/user/stable-diffusion-webui/models/Stable-diffusion/768-v-ema.yaml
LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
Loading weights [2c02b20a] from /home/user/stable-diffusion-webui/models/Stable-diffusion/768-v-ema.ckpt
Applying cross attention optimization (Doggettx).
Model loaded.
Loaded a total of 0 textual inversion embeddings.
Embeddings: 
Running on local URL:  http://0.0.0.0:8888

To create a public link, set `share=True` in `launch()`.
Returning [0.9, 0.999, 1e-08, 0.01, 'default', False, '', '', 0.0, 60.0, 1, True, True, True, 2e-06, 0.0002, 0.0002, 'constant', 0, 75, 0, 'no', True, 100, True, '', 1, 512, 1, True, 500, 500, True, False, False, False, 1, True, False, False, False, False, False, '', 7.5, 60, '', '', '', '', '', '', -1, 1, 0, -1, 7.5, 60, '', '', '', '', 7.5, 60, '', '', '', '', '', '', -1, 1, 0, -1, 7.5, 60, '', '', '', '', 7.5, 60, '', '', '', '', '', '', -1, 1, 0, -1, 7.5, 60, '', '', '', 'Loaded config.']
Please configure some concepts.
Please configure some concepts.


```

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

**Environment**

Linux Ubuntu 20.04
uname -a -> Linux 6f3ac57d-13c1-4e44-a58a-ffb456eb98f7 5.4.0-135-generic #152-Ubuntu SMP Wed Nov 23 20:19:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

What GPU are you using? 
RTX A4000

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the db_config.json file from /models/dreambooth/MODELNAME/db_config.json

![image](https://user-images.githubusercontent.com/19656515/209832657-3b3e07a1-caf9-4212-8eef-71f597f0b763.png)

![image](https://user-images.githubusercontent.com/19656515/209832683-18a400b8-296b-491f-ae60-d2e046870f49.png)

```
(base) user@6f3ac57d-13c1-4e44-a58a-ffb456eb98f7:~/stable-diffusion-webui$ cat models/dreambooth/neil2/db_config.json 
{
    "adam_beta1": 0.9,
    "adam_beta2": 0.999,
    "adam_epsilon": 1e-08,
    "adam_weight_decay": 0.01,
    "attention": "default",
    "center_crop": true,
    "concepts_path": "",
    "custom_model_name": "",
    "epoch_pause_frequency": 0.0,
    "epoch_pause_time": 60.0,
    "gradient_accumulation_steps": 1,
    "gradient_checkpointing": true,
    "half_model": true,
    "hflip": true,
    "learning_rate": 2e-06,
    "lora_learning_rate": 0.0002,
    "lora_txt_learning_rate": 0.0002,
    "lr_scheduler": "constant",
    "lr_warmup_steps": 0,
    "max_token_length": 75,
    "max_train_steps": 0,
    "mixed_precision": "fp16",
    "model_dir": "/home/user/stable-diffusion-webui/models/dreambooth/neil2",
    "model_name": "neil2",
    "not_cache_latents": true,
    "num_train_epochs": 100,
    "pad_tokens": true,
    "pretrained_model_name_or_path": "/home/user/stable-diffusion-webui/models/dreambooth/neil2/working",
    "pretrained_vae_name_or_path": "",
    "prior_loss_weight": 1,
    "resolution": 512,
    "revision": 0,
    "sample_batch_size": 1,
    "save_class_txt": true,
    "save_embedding_every": 500,
    "save_preview_every": 500,
    "save_use_global_counts": true,
    "save_use_epochs": false,
    "scale_lr": false,
    "src": "/home/user/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt",
    "shuffle_tags": false,
    "train_batch_size": 1,
    "train_text_encoder": true,
    "use_8bit_adam": true,
    "use_concepts": false,
    "use_cpu": false,
    "use_ema": false,
    "use_lora": true,
    "scheduler": "ddim",
    "v2": false,
    "has_ema": "True",
    "concepts_list": [],
    "lifetime_revision": 0

```

**Comment by MrKurtzmann** [comment]
Same error.


[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[ ] xformers version N/A installed.
[+] torch version 1.12.1 installed.
[+] torchvision version 0.13.1 installed.

Mac OS M1 Max

**Comment by TheEliteGeek** [comment]
I was also getting this error as well and after a bit of testing, I *think* it's related to the _Save Params_ and _Load Params_ features. 

Based on your logs showing this and because you have a specific model selected from the "Model" dropdown, I can assume you're choosing a model and clicking, "Load Params."

`Returning [0.9, 0.999, 1e-08, 0.01, 'default', False, '', '', 0.0, 60.0, 1, True, True, True, 2e-06, 0.0002, 0.0002, 'constant', 0, 75, 0, 'no', True, 100, True, '', 1, 512, 1, True, 500, 500, True, False, False, False, 1, True, False, False, False, False, False, '', 7.5, 60, '', '', '', '', '', '', -1, 1, 0, -1, 7.5, 60, '', '', '', '', 7.5, 60, '', '', '', '', '', '', -1, 1, 0, -1, 7.5, 60, '', '', '', '', 7.5, 60, '', '', '', '', '', '', -1, 1, 0, -1, 7.5, 60, '', '', '', 'Loaded config.']`

I'm not completely sure, but I think using the _Load Params_ button doesn't seem to actually inject the loaded values properly. No idea why this happens since I haven't dug into it too much, but I'm able to consistently reproduce the error by doing the following:

Go to Dreambooth
Select any previously trained model from "Model" drop-down
Click, _Load Params_
Optional: Check and modify Parameters and Concepts tab as desired
Click _Train_

Nothing seemingly happens and when checking the console, you'll see the message: _Please configure some concepts._

**Comment by MrKurtzmann** [comment]
No unfortunately the probelm for me is somewhere else I think. I do not use load or save params.
I have then tried to use them but without success.
When I try to generate some images in the debug dialog I get this error message. 

> Loading model from /Users/luis/Pictures/AI Stable Diffusion/stable-diffusion-webui/models/dreambooth/testest20221230/working.
Exception generating sample!
Traceback (most recent call last):
  File "/Users/luis/Pictures/AI Stable Diffusion/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/utils.py", line 254, in generate_sample_img
    text_enc_model = CLIPTextModel.from_pretrained(config.pretrained_model_name_or_path,
  File "/Users/luis/Pictures/AI Stable Diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2012, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/Users/luis/Pictures/AI Stable Diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/transformers/models/clip/configuration_clip.py", line 135, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/Users/luis/Pictures/AI Stable Diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/transformers/configuration_utils.py", line 559, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/Users/luis/Pictures/AI Stable Diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/transformers/configuration_utils.py", line 614, in _get_config_dict
    resolved_config_file = cached_file(
  File "/Users/luis/Pictures/AI Stable Diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/transformers/utils/hub.py", line 380, in cached_file
    raise EnvironmentError(
OSError: /Users/luis/Pictures/AI Stable Diffusion/stable-diffusion-webui/models/dreambooth/testest20221230/working does not appear to have a file named text_encoder/config.json. Checkout 'https://huggingface.co//Users/luis/Pictures/AI Stable Diffusion/stable-diffusion-webui/models/dreambooth/testest20221230/working/0' for available files.
 Restored system models. 
 Allocated: 0.0GB 
 Reserved: 0.0GB 




Mac OS 13.1 m1

<img width="615" alt="Bildschirm­foto 2022-12-30 um 21 38 23" src="https://user-images.githubusercontent.com/58439006/210110718-0377932f-27d9-48ad-8482-57d4b0f540eb.png">
<img width="627" alt="Bildschirm­foto 2022-12-30 um 21 38 33" src="https://user-images.githubusercontent.com/58439006/210110721-877426c4-d99d-4361-bf5e-62eac5621aa2.png">
<img width="562" alt="Bildschirm­foto 2022-12-30 um 21 30 29" src="https://user-images.githubusercontent.com/58439006/210110711-89546733-77e7-4aa7-8854-24f937c7ae25.png">
<img width="567" alt="Bildschirm­foto 2022-12-30 um 21 30 40" src="https://user-images.githubusercontent.com/58439006/210110714-95909fc0-0674-4e1b-af0d-71a486608837.png">

**Comment by 4joeknight4** [comment]
@AllanElleuch : It looks like your db_config.json file is incomplete.  ""concepts_list": []," should have data in the square brackets.
based on the info in you screenshots, the db_config should look like this:

```
(base) user@6f3ac57d-13c1-4e44-a58a-ffb456eb98f7:~/stable-diffusion-webui$ cat models/dreambooth/neil2/db_config.json 
{
    "adam_beta1": 0.9,
    "adam_beta2": 0.999,
    "adam_epsilon": 1e-08,
    "adam_weight_decay": 0.01,
    "attention": "default",
    "center_crop": true,
    "concepts_path": "",
    "custom_model_name": "",
    "epoch_pause_frequency": 0.0,
    "epoch_pause_time": 60.0,
    "gradient_accumulation_steps": 1,
    "gradient_checkpointing": true,
    "half_model": true,
    "hflip": true,
    "learning_rate": 2e-06,
    "lora_learning_rate": 0.0002,
    "lora_txt_learning_rate": 0.0002,
    "lr_scheduler": "constant",
    "lr_warmup_steps": 0,
    "max_token_length": 75,
    "max_train_steps": 0,
    "mixed_precision": "fp16",
    "model_dir": "/home/user/stable-diffusion-webui/models/dreambooth/neil2",
    "model_name": "neil2",
    "not_cache_latents": true,
    "num_train_epochs": 100,
    "pad_tokens": true,
    "pretrained_model_name_or_path": "/home/user/stable-diffusion-webui/models/dreambooth/neil2/working",
    "pretrained_vae_name_or_path": "",
    "prior_loss_weight": 1,
    "resolution": 512,
    "revision": 0,
    "sample_batch_size": 1,
    "save_class_txt": true,
    "save_embedding_every": 500,
    "save_preview_every": 500,
    "save_use_global_counts": true,
    "save_use_epochs": false,
    "scale_lr": false,
    "src": "/home/user/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt",
    "shuffle_tags": false,
    "train_batch_size": 1,
    "train_text_encoder": true,
    "use_8bit_adam": true,
    "use_concepts": false,
    "use_cpu": false,
    "use_ema": false,
    "use_lora": true,
    "scheduler": "ddim",
    "v2": false,
    "has_ema": "True",
    "concepts_list": [
        {
            "max_steps": -1,
            "instance_data_dir": "---------your training data directory----------",
            "class_data_dir": "--------your class data directory if applicable----------",
            "instance_prompt": "portrait neil person",
            "class_prompt": "portrait of a man",
            "save_sample_prompt": "",
            "save_sample_template": "",
            "instance_token": "neil",
            "class_token": "a man",
            "num_class_images": ---put number of class training images if neccessary---,
            "class_negative_prompt": "",
            "class_guidance_scale": 7.5,
            "class_infer_steps": 60,
            "save_sample_negative_prompt": "",
            "n_save_sample": 1,
            "sample_seed": -1,
            "save_guidance_scale": 7.5,
            "save_infer_steps": 60
        }
    ],
    "lifetime_revision": 0  
    
`
```
I'd also use a more unique instance token than just "Neil". Something like "NeilLastNameOrWhatever" or something along those lines. I'd also use "man" instead of "a man" for the class token. So your instance token would be "a photo of eilLastNameOrWhatever man" and your class prompt would be "a photo of a man" based on the examples I gave.

**Comment by d8ahazard** [comment]
Try now, I've pushed a major update.

https://github.com/d8ahazard/sd_dreambooth_extension/commit/15244fef18c35864be6f6c2e1c0237dadc5415c1

**Comment by AllanElleuch** [comment]
Hi d8ahazard, 

Thanks for commiting for new year, it is really appreciated :)

What was improved:
- I can now **save the settings** from the **"settings"** tab 
- I was **able to run a training** by using "Use concept list" and adding the path to a json file.

What was doesn't work:
- Using the concept tab in the GUI and pressing **"Save settings"** **will not save my settings**. Therefore the program will still inform me to add some concepts. 

We are getting close to a better solution :)

**Comment by Christoph-ModelMe** [comment]
I had a similar problem. Then I realized that I had a couple of webui windows open. I closed them all, restarted the app and then everything worked as expected

**Comment by Christoph-ModelMe** [comment]
@AllanElleuch I had the same issue. At some point I realized that I had a typo in the path to the directory of the training dirs. I can imagine that this or also other small errors in the settings might cause a reset of the config file
