### ISSUE TITLE
If there is Thumbs.db files it errors out

### ISSUE THREAD

**Issue by psdwizzard** [d8ahazard/sd_dreambooth_extension#64]
I found if the folder has a Thumbs.db files is errors out

Arguments: ('psdwizzard4', 'W:\\PE\\psdwizzard\\New folder', '', 'psdwizzard', '*', '', '', 1.0, 7.5, 40.0, 0, 512, False, True, 1, 1, 1, 600, 1, False, 5e-06, False, 'constant', 0, True, 0.9, 0.999, 0.01, 1e-08, 1, 0, 0, 'fp16', True, '', False, True, True) {}
Traceback (most recent call last):
  File "C:\Users\kloebenberg\Documents\Stable-diffusion\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\kloebenberg\Documents\Stable-diffusion\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "C:\Users\kloebenberg\Documents\Stable-diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 265, in start_training
    trained_steps = main(config)
  File "C:\Users\kloebenberg\Documents\Stable-diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 740, in main
    for step, batch in enumerate(train_dataloader):
  File "C:\Users\kloebenberg\Documents\Stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\accelerate\data_loader.py", line 357, in __iter__
    next_batch = next(dataloader_iter)
  File "C:\Users\kloebenberg\Documents\Stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\dataloader.py", line 681, in __next__
    data = self._next_data()
  File "C:\Users\kloebenberg\Documents\Stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\kloebenberg\Documents\Stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\kloebenberg\Documents\Stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\kloebenberg\Documents\Stable-diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 360, in __getitem__
    instance_image = Image.open(instance_path)
  File "C:\Users\kloebenberg\Documents\Stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file '\\\\MOJOJO\\blender\\PE\\psdwizzard\\New folder\\Thumbs.db'

**Comment by eddjrn** [comment]
[This is linked to #44](https://github.com/d8ahazard/sd_dreambooth_extension/issues/44) a solution by the user it to delete that file. how ever it is generated automatically and in case of Mac OS only is removable by terminal as it is not even searchable.

**Comment by d8ahazard** [comment]
Fixed with b39403f
