### ISSUE TITLE
Imagic function: Exception training model: Input type (torch.cuda.HalfTensor) and weight type (torch.cuda.FloatTensor) should be the same

### ISSUE THREAD

**Issue by henryvii99** [d8ahazard/sd_dreambooth_extension#660]
### Kindly read the entire form below and fill it out with the requested information.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your
issue will be automatically closed._**

`
Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Commit hash: 311354c0bb8930ea939d6aa6b3edd50c69301320
Installing requirements for Web UI
Skipping dreambooth installation.
Dreambooth revision is c5cb58328c555ac27679422b1da940a9b19de6f2

`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**

**Have you updated Dreambooth to the latest revision?**

**Have you updated the Stable-Diffusion-WebUI to the latest version?**

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**

OK 

**Describe the bug**

Tick Train Imagic Only in Debugging tab and returned error, untick will start a perfectly normal dreambooth training session.

**Provide logs**

Using magick windows DLL!
CUDA SETUP: Loading binary C:\git\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
Optimizing embedding:   0%|                                                                    | 0/501 [00:00<?, ?it/s] Optimizing Embedding
 Allocated: 3.2GB
 Reserved: 3.3GB

Optimizing embedding: 100%|██████████████████████████████████████████████| 501/501 [01:46<00:00,  4.69it/s, loss=0.128]
 Saving embedding(s).
 Allocated: 6.4GB
 Reserved: 9.0GB

Fine Tuning:   0%|                                                                             | 0/501 [00:00<?, ?it/s] Fine Tuning
 Allocated: 6.4GB
 Reserved: 9.0GB

Fine Tuning:   0%|                                                                             | 0/501 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\git\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 357, in start_training
    mem_record = train_imagic(config, mem_record)
  File "C:\git\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_imagic.py", line 345, in train_imagic
    train_loop(progress_bar, optimizer)
  File "C:\git\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_imagic.py", line 300, in train_loop
    noise_pred = unet(noisy_latents, timesteps, optimized_embeddings).sample
  File "C:\git\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\git\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 375, in forward
    sample = self.conv_in(sample)
  File "C:\git\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\git\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\git\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.cuda.FloatTensor) should be the same
 Training completed, reloading SD Model.
 Allocated: 0.0GB
 Reserved: 6.9GB

Memory output: {}
 Restored system models.
 Allocated: 2.0GB
 Reserved: 6.9GB

Returning result: Exception training model: Input type (torch.cuda.HalfTensor) and weight type (torch.cuda.FloatTensor) should be the same

**Environment**

What OS?: Windows 11

If Windows - WSL or native?: Native

What GPU are you using? Nvidia 3060 12GB

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the
db_config.json file from /models/dreambooth/MODELNAME/db_config.json

Not applicable

**Comment by FranciscoFornell** [comment]
Hi! I have the same error, with the latest version of both automatic1111 GUI and this extension, on a 3080ti 12GB. I just wanted to confirm that the issue is still there before it gets automatically closed.
