### ISSUE TITLE
Error running install.py

### ISSUE THREAD

**Issue by codestuff001** [d8ahazard/sd_dreambooth_extension#68]
I'm getting this error when starting Automatic1111:
```
Installing requirements for Web UI
Error running install.py for extension sd_dreambooth_extension.
Command: "C:\Apps\Stable Diffusion\stable-diffusion-webui\venv\Scripts\python.exe" "extensions\sd_dreambooth_extension\install.py"
Error code: 1
stdout: Installing Requirements for Dreambooth

stderr: Traceback (most recent call last):
  File "C:\Apps\Stable Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\install.py", line 11, in <module>
    run(f'{python} -m pip install -r "{reqs}"', desc=f"Installing Requirements for {name}", errdesc=f"Couldn't install {name} requirements.")
  File "C:\Apps\Stable Diffusion\stable-diffusion-webui\launch.py", line 34, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install Dreambooth requirements..
Command: C:\Apps\Stable Diffusion\stable-diffusion-webui\venv\Scripts\python.exe -m pip install -r "C:\Apps\Stable Diffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt"
Error code: 1
stdout: <empty>
stderr: 'C:\Apps\Stable' is not recognized as an internal or external command,
operable program or batch file.
```

This is after doing the Dreambooth extension install steps and restarting the webui. 

Is the code missing double-quotes around the location address and reading "C:\Apps\Stable" as a command?

I checked 'install.py' line 11, and this was the code:
`run(f'{python} -m pip install -r "{reqs}"', desc=f"Installing Requirements for {name}", errdesc=f"Couldn't install {name} requirements.")`

**Comment by Dokko21** [comment]
I have exactly the same problem...

**Comment by Iory1998** [comment]
Hello, thank you for the hard work.
I just installed the extension from the webUI and I am getting the same issue eventhough I removed spaces in the path. Is there any fix? On a different note, can I run DB on an RTX3070ti with 8GB of VRAM?

**Comment by Luke2642** [comment]
So what's your error now? It can't still be "stderr: 'C:\Apps\Stable' is not recognized as an internal or external command," surely.

**Comment by d8ahazard** [comment]
> Hello, thank you for the hard work. I just installed the extension from the webUI and I am getting the same issue even though I removed spaces in the path. Is there any fix? On a different note, can I run DB on an RTX3070ti with 8GB of VRAM?

*THEORETICALLY*, if you go through the massive amount of backflips through flaming hoops required to set up WSL2, then install ubuntu, then install the venv, then set up CUDA Toolkit, then install this, then configure accelerate and deepspeed...or if you're just running Linux, then yes, it should be possible to train this on an 8GB GPU.

However, after like a week of trying the above stuff - I still had no success in training with anything but the CPU. In that regard, yes, you can train on CPU, but it's slow AF.

**Comment by Iory1998** [comment]
Thank you @d8ahazard  for your prompt reply. 
I suspected as much. We can't have everything in life, can we? :) I am a windows11 user and I just don't want to go through all the hustle of using Linux since I never used it before and you the learning curve and whatnot. 
So, for now, I'll wait until you guys find a way for DB to be working on an 8GB Vram card or I would just upgrade my card to a more accommodating one.

Thank you!
