### ISSUE TITLE
Training stops halfway through (CUDA+tensor errors)

### ISSUE THREAD

**Issue by Joedog6503** [d8ahazard/sd_dreambooth_extension#684]
### Kindly read the entire form below and fill it out with the requested information.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your
issue will be automatically closed._**

`
Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Commit hash: ****************************************
Installing requirements for Web UI
Skipping dreambooth installation.
Dreambooth revision is ****************************************
Diffusers version is *.*.*.
Torch version is *.*.*.
Torch vision version is *.*.*.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes
**Have you updated Dreambooth to the latest revision?**
Yes
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes
**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**
Ok, I used git pull and redownloaded the 
**Describe the bug**

While training, it will hit a certain point (either 30% or 50% depending on training steps) and will stop training. It has both a CUDA memory error (but I'm using LORA, fp16, xformers, and adam so no clue why this is hapening) and a "tensors cannot be saved for backward" error

**Provide logs**

venv "D:\GitHub\WEBUI\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 2bc86712ec16cada01a2353f1d978c1aabc84dbb
Installing requirements for Web UI

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: 4ca69a904f5ddd5651d87032b3dca515eea505ba
SD-WebUI revision: 2bc86712ec16cada01a2353f1d978c1aabc84dbb

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.14.dev0 installed.
[+] torch version 1.12.1+cu113 installed.
[+] torchvision version 0.13.1+cu113 installed.

#######################################################################################################

Launching Web UI with arguments: --api
No module 'xformers'. Proceeding without it.
SD-Webui API layer loaded
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights [e02601f3] from D:\GitHub\WEBUI\models\Stable-diffusion\AngelaRoseV6_30000.ckpt
Applying cross attention optimization (Doggettx).
Model loaded.
Textual inversion embeddings loaded(0):
Warning: Bad ui setting value: img2img/Mask mode/value: Draw mask; Default value "Inpaint masked" will be used instead.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Exception loading config: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "D:\GitHub\WEBUI\extensions\sd_dreambooth_extension\dreambooth\db_config.py", line 356, in from_file
    config_dict = json.load(openfile)
  File "C:\Users\josep\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\josep\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\josep\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\josep\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Can't load config!
Traceback (most recent call last):
  File "D:\GitHub\WEBUI\venv\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "D:\GitHub\WEBUI\venv\lib\site-packages\gradio\blocks.py", line 1016, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\GitHub\WEBUI\venv\lib\site-packages\gradio\blocks.py", line 945, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range
Exception loading config: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "D:\GitHub\WEBUI\extensions\sd_dreambooth_extension\dreambooth\db_config.py", line 356, in from_file
    config_dict = json.load(openfile)
  File "C:\Users\josep\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\josep\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\josep\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\josep\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Can't load config!
Traceback (most recent call last):
  File "D:\GitHub\WEBUI\venv\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "D:\GitHub\WEBUI\venv\lib\site-packages\gradio\blocks.py", line 1016, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\GitHub\WEBUI\venv\lib\site-packages\gradio\blocks.py", line 945, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range
Exception loading config: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "D:\GitHub\WEBUI\extensions\sd_dreambooth_extension\dreambooth\db_config.py", line 356, in from_file
    config_dict = json.load(openfile)
  File "C:\Users\josep\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\josep\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\josep\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\josep\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Can't load config!
Traceback (most recent call last):
  File "D:\GitHub\WEBUI\venv\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "D:\GitHub\WEBUI\venv\lib\site-packages\gradio\blocks.py", line 1016, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\GitHub\WEBUI\venv\lib\site-packages\gradio\blocks.py", line 945, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range
Loading model from checkpoint.
Loading checkpoint...
v1 model loaded.
Converting unet...
Converting vae...
Converting text encoder...
Saving diffusion model...
Restored system models.
Checkpoint successfully extracted to D:\GitHub\WEBUI\models\dreambooth\TessEralv4\working
Saved settings.
Custom model name is
Starting Dreambooth training...
Initializing dreambooth training...
Replace CrossAttention.forward to use default
Injecting trainable lora...
CUDA SETUP: Loading binary D:\GitHub\WEBUI\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
prepare train images.
769 train images with repeating.
0 reg images.
prepare dataset
Caching latents with buckets...
100%|████████████████████████████████████████████████████████████████████████████████| 769/769 [00:45<00:00, 17.00it/s]
Bucket 0: Resolution (144, 512), Count: 4
Bucket 1: Resolution (208, 512), Count: 6
Bucket 2: Resolution (272, 512), Count: 42
Bucket 3: Resolution (336, 512), Count: 36
Bucket 4: Resolution (400, 512), Count: 40
Bucket 5: Resolution (464, 512), Count: 11
Bucket 6: Resolution (512, 144), Count: 0
Bucket 7: Resolution (512, 208), Count: 0
Bucket 8: Resolution (512, 272), Count: 0
Bucket 9: Resolution (512, 336), Count: 1
Bucket 10: Resolution (512, 400), Count: 1
Bucket 11: Resolution (512, 464), Count: 5
Bucket 12: Resolution (512, 512), Count: 623
Sched breakpoint is 3845
  ***** Running training *****
  Instance Images: 769
  Class Images: 0
  Total Examples: 769
  Num batches each epoch = 769
  Num Epochs = 10
  Batch Size Per Device = 1
  Gradient Accumulation steps = 1
  Total train batch size (w. parallel, distributed & accumulation) = 769
  Total optimization steps = 7690
  Total training steps = 7690
  Resuming from checkpoint: False
  First resume epoch: 0
  First resume step: 0
  Lora: True, Adam: True, Prec: fp16
  Gradient Checkpointing: True, Text Enc Steps: -1.0
  EMA: False
  LR: 2e-06)
Steps:  50%|███████▌       | 3845/7690 [26:47<26:14,  2.44it/s, loss=0.115, loss_avg=0.133, lr=0.0002, vram_usage=11.2]Exception saving sample: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 0; 12.00 GiB total capacity; 10.86 GiB already allocated; 0 bytes free; 11.00 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "D:\GitHub\WEBUI\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 787, in save_weights
    s_image = s_pipeline(c.prompt, num_inference_steps=c.steps,
  File "D:\GitHub\WEBUI\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\GitHub\WEBUI\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 517, in __call__
    noise_pred = self.unet(latent_model_input, t, encoder_hidden_states=text_embeddings).sample
  File "D:\GitHub\WEBUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\GitHub\WEBUI\venv\lib\site-packages\accelerate\utils\operations.py", line 490, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "D:\GitHub\WEBUI\venv\lib\site-packages\torch\amp\autocast_mode.py", line 12, in decorate_autocast
    return func(*args, **kwargs)
  File "D:\GitHub\WEBUI\venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 407, in forward
    sample = upsample_block(
  File "D:\GitHub\WEBUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\GitHub\WEBUI\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 1198, in forward
    hidden_states = torch.utils.checkpoint.checkpoint(
  File "D:\GitHub\WEBUI\venv\lib\site-packages\torch\utils\checkpoint.py", line 235, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "D:\GitHub\WEBUI\venv\lib\site-packages\torch\utils\checkpoint.py", line 96, in forward
    outputs = run_function(*args)
  File "D:\GitHub\WEBUI\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 1191, in custom_forward
    return module(*inputs, return_dict=return_dict)
  File "D:\GitHub\WEBUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\GitHub\WEBUI\venv\lib\site-packages\diffusers\models\attention.py", line 216, in forward
    hidden_states = block(hidden_states, context=encoder_hidden_states, timestep=timestep)
  File "D:\GitHub\WEBUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\GitHub\WEBUI\venv\lib\site-packages\diffusers\models\attention.py", line 484, in forward
    hidden_states = self.attn1(norm_hidden_states) + hidden_states
  File "D:\GitHub\WEBUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\GitHub\WEBUI\extensions\sd_dreambooth_extension\dreambooth\xattention.py", line 40, in forward_default
    hidden_states = self._attention(query, key, value)
  File "D:\GitHub\WEBUI\venv\lib\site-packages\diffusers\models\attention.py", line 614, in _attention
    attention_probs = attention_probs.to(value.dtype)
RuntimeError: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 0; 12.00 GiB total capacity; 10.86 GiB already allocated; 0 bytes free; 11.00 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
D:\GitHub\WEBUI\extensions\sd_dreambooth_extension\dreambooth\utils.py:409: FutureWarning: Dropping of nuisance columns in rolling operations is deprecated; in a future version this will raise TypeError. Select only valid columns before calling the operation. Dropped columns were Index(['Name'], dtype='object')
  all_df_loss = all_df_loss.rolling(smoothing_window).mean()
D:\GitHub\WEBUI\extensions\sd_dreambooth_extension\dreambooth\utils.py:440: FutureWarning: Dropping of nuisance columns in rolling operations is deprecated; in a future version this will raise TypeError. Select only valid columns before calling the operation. Dropped columns were Index(['Name'], dtype='object')
  all_df_ram = all_df_ram.rolling(smoothing_window).mean()
Traceback (most recent call last):
  File "D:\GitHub\WEBUI\extensions\sd_dreambooth_extension\scripts\dreambooth.py", line 569, in start_training
    result = main(config, use_subdir=use_subdir, lora_model=lora_model_name,
  File "D:\GitHub\WEBUI\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1024, in main
    return inner_loop()
  File "D:\GitHub\WEBUI\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 86, in decorator
    return function(batch_size, grad_size, *args, **kwargs)
  File "D:\GitHub\WEBUI\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 888, in inner_loop
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "D:\GitHub\WEBUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\GitHub\WEBUI\venv\lib\site-packages\accelerate\utils\operations.py", line 490, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "D:\GitHub\WEBUI\venv\lib\site-packages\torch\amp\autocast_mode.py", line 12, in decorate_autocast
    return func(*args, **kwargs)
  File "D:\GitHub\WEBUI\venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 381, in forward
    sample, res_samples = downsample_block(
  File "D:\GitHub\WEBUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\GitHub\WEBUI\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 618, in forward
    hidden_states = downsampler(hidden_states)
  File "D:\GitHub\WEBUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\GitHub\WEBUI\venv\lib\site-packages\diffusers\models\resnet.py", line 188, in forward
    hidden_states = self.conv(hidden_states)
  File "D:\GitHub\WEBUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\GitHub\WEBUI\venv\lib\site-packages\torch\nn\modules\conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\GitHub\WEBUI\venv\lib\site-packages\torch\nn\modules\conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Inference tensors cannot be saved for backward. To work around you can make a clone to get a normal tensor and use it in autograd.
Steps:  50%|███████▌       | 3845/7690 [26:52<26:52,  2.38it/s, loss=0.115, loss_avg=0.133, lr=0.0002, vram_usage=11.2]
Training completed, reloading SD Model.
Restored system models.
Returning result: Exception training model: Inference tensors cannot be saved for backward. To work around you can make a clone to get a normal tensor and use it in autograd.

**Environment**

What OS?
windows 10

If Windows - WSL or native?
Native
What GPU are you using?
rtx3080 12gb 
**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the
db_config.json file from /models/dreambooth/MODELNAME/db_config.json

{
    "attention": "default",
    "cache_latents": true,
    "center_crop": false,
    "clip_skip": 1,
    "concepts_path": "",
    "custom_model_name": "",
    "epoch": 5,
    "epoch_pause_frequency": 0.0,
    "epoch_pause_time": 60.0,
    "gradient_accumulation_steps": 1,
    "gradient_checkpointing": true,
    "gradient_set_to_none": true,
    "graph_smoothing": 50.0,
    "half_model": false,
    "hflip": false,
    "learning_rate": 2e-06,
    "learning_rate_min": 1e-06,
    "lora_learning_rate": 0.0002,
    "lora_model_name": "",
    "lora_txt_learning_rate": 0.0002,
    "lora_txt_weight": 1,
    "lora_weight": 1,
    "lr_cycles": 1,
    "lr_factor": 0.5,
    "lr_power": 1,
    "lr_scale_pos": 0.5,
    "lr_scheduler": "constant_with_warmup",
    "lr_warmup_steps": 0,
    "max_token_length": 75,
    "mixed_precision": "fp16",
    "model_dir": "D:\\GitHub\\WEBUI\\models\\dreambooth\\TessEralv4",
    "model_name": "TessEralv4",
    "num_train_epochs": 10,
    "pad_tokens": true,
    "pretrained_model_name_or_path": "D:\\GitHub\\WEBUI\\models\\dreambooth\\TessEralv4\\working",
    "pretrained_vae_name_or_path": "",
    "prior_loss_weight": 1,
    "resolution": 512,
    "revision": 0,
    "sample_batch_size": 1,
    "sanity_prompt": "",
    "sanity_seed": 420420.0,
    "save_ckpt_after": true,
    "save_ckpt_cancel": false,
    "save_ckpt_during": false,
    "save_embedding_every": 25,
    "save_lora_after": true,
    "save_lora_cancel": false,
    "save_lora_during": false,
    "save_preview_every": 5,
    "save_state_after": false,
    "save_state_cancel": false,
    "save_state_during": false,
    "src": "D:\\GitHub\\WEBUI\\models\\Stable-diffusion\\animefinal-full-pruned.ckpt",
    "shuffle_tags": true,
    "train_batch_size": 1,
    "stop_text_encoder": -1.0,
    "use_8bit_adam": true,
    "use_concepts": false,
    "use_ema": false,
    "use_lora": true,
    "use_subdir": true,
    "scheduler": "euler",
    "v2": false,
    "has_ema": "False",
    "concepts_list": [
        {
            "instance_data_dir": "D:\\GitHub\\WEBUI\\models\\dreambooth\\TessiaV5",
            "class_data_dir": "",
            "instance_prompt": "TessEral",
            "class_prompt": "TessEral",
            "save_sample_prompt": "",
            "save_sample_template": "",
            "instance_token": "TessEral",
            "class_token": "TessEral",
            "num_class_images": 0,
            "class_negative_prompt": "",
            "class_guidance_scale": 7.5,
            "class_infer_steps": 40,
            "save_sample_negative_prompt": "",
            "n_save_sample": 1,
            "sample_seed": -1,
            "save_guidance_scale": 7.5,
            "save_infer_steps": 40
        }
    ],
    "lifetime_revision": 0
}

**Comment by FurkanGozukara** [comment]
ye i am also getting a lot of error related stop and i have to restart and resume
