### ISSUE TITLE
args.epoch_pause_time cause TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by AndyLonly** [d8ahazard/sd_dreambooth_extension#696]
### Kindly read the entire form below and fill it out with the requested information.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your
issue will be automatically closed._**

```bat
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 82cfc227d735c140447d5b8dca29a71ee9bde127
Installing requirements for Web UI
Skipping dreambooth installation.
Dreambooth revision is 4ca69a904f5ddd5651d87032b3dca515eea505ba
Diffusers version is 0.10.2
Torch version is 2.0.0.dev20221226+cu117
Torch vision version is 0.15.0.dev20221226+cu117
```

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yes
**Have you updated Dreambooth to the latest revision?**
yes
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
yes
**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**
ok
**Describe the bug**
error at epoch_pause_frequency
webui setting epoch_pause_time is integer,json cfg is float
![image](https://user-images.githubusercontent.com/15814794/210707471-025cbe98-cd23-4f40-a8ae-9815578b9a14.png)
to fix it add int(epoch_pause_frequency ) on save or on read out

**Provide logs**
```py
Giving the GPU a break for 60.0 seconds.
Traceback (most recent call last):
  File "C:\Users\d8ahazard\Downloads\stable-diffusion-webui-master\extensions\sd_dreambooth_extension\scripts\dreambooth.py", line 569, in start_training
    result = main(config, use_subdir=use_subdir, lora_model=lora_model_name,
  File "C:\Users\d8ahazard\Downloads\stable-diffusion-webui-master\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1024, in main
    return inner_loop()
  File "C:\Users\d8ahazard\Downloads\stable-diffusion-webui-master\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 86, in decorator
    return function(batch_size, grad_size, *args, **kwargs)
  File "C:\Users\d8ahazard\Downloads\stable-diffusion-webui-master\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1006, in inner_loop
    for i in range(args.epoch_pause_time):
TypeError: 'float' object cannot be interpreted as an integer
```
If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *
before* the crash occurred.

**Environment**

What OS?
Windows 11

What GPU are you using?
4090

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the
db_config.json file from /models/dreambooth/MODELNAME/db_config.json
```json
{
    "attention": "xformers",
    "cache_latents": false,
    "center_crop": false,
    "clip_skip": 1,
    "concepts_path": "C:\\Users\\d8ahazard\\Downloads\\stable-diffusion-webui-master\\train_set\\d8ahazard.json",
    "custom_model_name": "",
    "epoch": 4,
    "epoch_pause_frequency": 2.0,
    "epoch_pause_time": 60.0,
    "gradient_accumulation_steps": 2,
    "gradient_checkpointing": true,
    "gradient_set_to_none": true,
    "graph_smoothing": 50.0,
    "half_model": false,
    "hflip": true,
    "learning_rate": 2e-05,
    "learning_rate_min": 1e-06,
    "lora_learning_rate": 0.0002,
    "lora_model_name": "",
    "lora_txt_learning_rate": 0.0002,
    "lora_txt_weight": 1,
    "lora_weight": 1,
    "lr_cycles": 1,
    "lr_factor": 0.5,
    "lr_power": 1,
    "lr_scale_pos": 0.5,
    "lr_scheduler": "polynomial",
    "lr_warmup_steps": 0,
    "max_token_length": 300,
    "mixed_precision": "fp16",
    "model_dir": "C:\\Users\\d8ahazard\\Downloads\\stable-diffusion-webui-master\\models\\dreambooth\\d8ahazard",
    "model_name": "d8ahazard",
    "num_train_epochs": 20,
    "pad_tokens": true,
    "pretrained_model_name_or_path": "C:\\Users\\d8ahazard\\Downloads\\stable-diffusion-webui-master\\models\\dreambooth\\d8ahazard\\working",
    "pretrained_vae_name_or_path": "",
    "prior_loss_weight": 1,
    "resolution": 768,
    "revision": 25136,
    "sample_batch_size": 1,
    "sanity_prompt": "",
    "sanity_seed": 420420.0,
    "save_ckpt_after": true,
    "save_ckpt_cancel": false,
    "save_ckpt_during": false,
    "save_embedding_every": 0,
    "save_lora_after": true,
    "save_lora_cancel": false,
    "save_lora_during": false,
    "save_preview_every": 0,
    "save_state_after": false,
    "save_state_cancel": false,
    "save_state_during": false,
    "src": "C:\\Users\\d8ahazard\\Downloads\\stable-diffusion-webui-master\\models\\Stable-diffusion\\d8ahazard.ckpt",
    "shuffle_tags": true,
    "train_batch_size": 2,
    "stop_text_encoder": -1.0,
    "use_8bit_adam": true,
    "use_concepts": true,
    "use_ema": true,
    "use_lora": false,
    "use_subdir": true,
    "scheduler": "ddim",
    "v2": true,
    "has_ema": "True",
```

**Comment by d8ahazard** [comment]
Fixed with eb51824.
