### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by kkiqq22** [d8ahazard/sd_dreambooth_extension#705]
Launching Web UI with arguments: --disable-safe-unpickle --server-name=0.0.0.0 --listen --port=6087
2023-01-06 02:14:00.431996: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-06 02:14:00.655273: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-01-06 02:14:01.606170: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/uqwenf/stable-diffusion-webui/venv/lib/python3.8/site-packages/cv2/../../lib64:/usr/local/cuda-11.7/lib64:
2023-01-06 02:14:01.606371: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/uqwenf/stable-diffusion-webui/venv/lib/python3.8/site-packages/cv2/../../lib64:/usr/local/cuda-11.7/lib64:
2023-01-06 02:14:01.606390: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
No module 'xformers'. Proceeding without it.
Error loading script: api.py
Traceback (most recent call last):
  File "/home/uqwenf/stable-diffusion-webui/modules/scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/home/uqwenf/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/home/uqwenf/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/api.py", line 24, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.finetune_utils import FilenameTextGetter
  File "/home/uqwenf/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/finetune_utils.py", line 257, in <module>
    class ImageBuilder:
  File "/home/uqwenf/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/finetune_utils.py", line 330, in ImageBuilder
    def generate_images(self, prompt_data: list[PromptData]) -> [Image]:
TypeError: 'type' object is not subscriptable

Error loading script: dreambooth.py
Traceback (most recent call last):
  File "/home/uqwenf/stable-diffusion-webui/modules/scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/home/uqwenf/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/home/uqwenf/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/dreambooth.py", line 17, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.finetune_utils import ImageBuilder, PromptData
  File "/home/uqwenf/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/finetune_utils.py", line 257, in <module>
    class ImageBuilder:
  File "/home/uqwenf/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/finetune_utils.py", line 330, in ImageBuilder
    def generate_images(self, prompt_data: list[PromptData]) -> [Image]:
TypeError: 'type' object is not subscriptable

Error loading script: main.py
Traceback (most recent call last):
  File "/home/uqwenf/stable-diffusion-webui/modules/scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/home/uqwenf/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/home/uqwenf/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 9, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.finetune_utils import generate_prompts
  File "/home/uqwenf/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/finetune_utils.py", line 257, in <module>
    class ImageBuilder:
  File "/home/uqwenf/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/finetune_utils.py", line 330, in ImageBuilder
    def generate_images(self, prompt_data: list[PromptData]) -> [Image]:
TypeError: 'type' object is not subscriptable

**Comment by lintonxue00** [comment]
我也遇到这样的问题，这让我不能用colab笔记训练dreambooth

**Comment by hipete19** [comment]
Hey! Also having the same issue, were you able to solve it in the end?

**Comment by d8ahazard** [comment]
The issue was resolved, but I would have closed this regardless, as I don't address issues that are not submitted using the proper form.
