### ISSUE TITLE
Training with 8bit adams errors out, while training witout 8bit adams works fine

### ISSUE THREAD

**Issue by Lesani** [d8ahazard/sd_dreambooth_extension#710]
### Kindly read the entire form below and fill it out with the requested information.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your
issue will be automatically closed._**

`
Python revision: 3.10.7 (main, Nov 24 2022, 19:45:47) [GCC 12.2.0]
Dreambooth revision: df2f3956065ffd2daf0021a136530462b9715f4b
SD-WebUI revision: 874b975bf8438b2b5ee6d8540d63b2e2da6b8dbd

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.15+e163309.d20221228 installed.
[+] torch version 1.12.1+cu113 installed.
[+] torchvision version 0.13.1+cu113 installed.

`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
who would do that ever?
I modified my webui-user.sh with the DB requirements.txt, nothing changed.

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yes

**Have you updated Dreambooth to the latest revision?**
yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**
'OK'

**Describe the bug**

I train a model, if I check the "use 8 bit adams" I get the error below (see log way below in the code tag)
Generation parameters:
  ***** Running training *****
  Instance Images: 31
  Class Images: 0
  Total Examples: 31
  Num batches each epoch = 31
  Num Epochs = 150
  Batch Size Per Device = 1
  Gradient Accumulation steps = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Text Encoder Epochs: 112
  Total optimization steps = 4650
  Total training steps = 4650
  Resuming from checkpoint: False
  First resume epoch: 0
  First resume step: 0
  Lora: False, Adam: True, Prec: bf16
  Gradient Checkpointing: True
  EMA: True
  LR: 2e-06)

if I deselect 8bit adams, and leave everything else the same, I train successfully without an error
Generation parameters:
***** Running training *****
  Instance Images: 31
  Class Images: 0
  Total Examples: 62
  Num batches each epoch = 31
  Num Epochs = 150
  Batch Size Per Device = 1
  Gradient Accumulation steps = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Text Encoder Epochs: 112
  Total optimization steps = 4650
  Total training steps = 4650
  Resuming from checkpoint: False
  First resume epoch: 0
  First resume step: 0
  Lora: False, Adam: False, Prec: bf16
  Gradient Checkpointing: True
  EMA: True
  LR: 2e-06)

**Provide logs**

```
Steps:   0%|                                                                                 | 0/4650 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/lesani/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/dreambooth.py", line 568, in start_training
    result = main(config, use_subdir=use_subdir, lora_model=lora_model_name,
  File "/home/lesani/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 966, in main
    return inner_loop()
  File "/home/lesani/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 86, in decorator
    return function(batch_size, grad_size, *args, **kwargs)
  File "/home/lesani/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 860, in inner_loop
    optimizer.step()
  File "/home/lesani/stable-diffusion-webui/venv/lib/python3.10/site-packages/accelerate/optimizer.py", line 134, in step
    self.scaler.step(self.optimizer, closure)
  File "/home/lesani/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 338, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "/home/lesani/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 285, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
  File "/home/lesani/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/lesani/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/optim/optimizer.py", line 113, in wrapper
    return func(*args, **kwargs)
  File "/home/lesani/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/lesani/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py", line 265, in step
    self.update_step(group, p, gindex, pindex)
  File "/home/lesani/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/lesani/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py", line 506, in update_step
    F.optimizer_update_8bit_blockwise(
  File "/home/lesani/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/functional.py", line 858, in optimizer_update_8bit_blockwise
    str2optimizer8bit_blockwise[optimizer_name][0](
NameError: name 'str2optimizer8bit_blockwise' is not defined
Steps:   0%|                                                                                 | 0/4650 [00:01<?, ?it/s]
Training completed, reloading SD Model.
Restored system models.
Returning result: Exception training model: 'name 'str2optimizer8bit_blockwise' is not defined'.
Steps:   0%|                                                                                 | 0/4650 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/lesani/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/dreambooth.py", line 568, in start_training
    result = main(config, use_subdir=use_subdir, lora_model=lora_model_name,
  File "/home/lesani/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 966, in main
    return inner_loop()
  File "/home/lesani/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 86, in decorator
    return function(batch_size, grad_size, *args, **kwargs)
  File "/home/lesani/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 860, in inner_loop
    optimizer.step()
  File "/home/lesani/stable-diffusion-webui/venv/lib/python3.10/site-packages/accelerate/optimizer.py", line 134, in step
    self.scaler.step(self.optimizer, closure)
  File "/home/lesani/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 338, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "/home/lesani/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 285, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
  File "/home/lesani/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/lesani/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/optim/optimizer.py", line 113, in wrapper
    return func(*args, **kwargs)
  File "/home/lesani/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/lesani/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py", line 265, in step
    self.update_step(group, p, gindex, pindex)
  File "/home/lesani/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/lesani/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py", line 506, in update_step
    F.optimizer_update_8bit_blockwise(
  File "/home/lesani/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/functional.py", line 858, in optimizer_update_8bit_blockwise
    str2optimizer8bit_blockwise[optimizer_name][0](
NameError: name 'str2optimizer8bit_blockwise' is not defined
Steps:   0%|                                                                                 | 0/4650 [00:01<?, ?it/s]
Training completed, reloading SD Model.
Restored system models.
Returning result: Exception training model: 'name 'str2optimizer8bit_blockwise' is not defined'.

```

**Environment**

What OS?
ubuntu

If Windows - WSL or native?
ubuntu 20.04

What GPU are you using?
rtx 4090

**Screenshots/Config**

**Comment by d8ahazard** [comment]
When you go to google an error message, and the only thing that comes back is a link to your own project:

https://pullanswer.com/questions/exception-importing-8bit-adam-libcurand-so-10-cannot-open-shared-object-file-no-such-file-or-directory

I'm stumped. Will have to research a bit. Can you tell me, is there a .dll in /WEBUI/venv/Lib/site-packages/bitsandbytes called libbitsandbytes_cpu.dll or libbitsandbytes_cudaall.dll?
