### ISSUE TITLE
regression in newest version for training, unable to generate class images

### ISSUE THREAD

**Issue by Pychnight** [d8ahazard/sd_dreambooth_extension#711]
### Kindly read the entire form below and fill it out with the requested information.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your
issue will be automatically closed._**

`
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 24e21c07108c0691636c0a54bf3936b847102330
Installing requirements for Web UI
Skipping dreambooth installation.
Dreambooth revision is df2f3956065ffd2daf0021a136530462b9715f4b
Diffusers version is 0.10.2.
Torch version is 1.12.1+cu113.
Torch vision version is 0.13.1+cu113.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
YES

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
YES

**Have you updated Dreambooth to the latest revision?**
YES

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
NO

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**
OK

**Describe the bug**

attempting to generate class images causes this error,

**Provide logs**

  File "C:\Users\pychnight\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\dreambooth.py", line 650, in ui_classifiers
    count, images = generate_classifiers(config, lora_model=lora_model, lora_weight=lora_weight,
  File "C:\Users\pychnight\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\finetune_utils.py", line 871, in generate_classifiers
    new_images = builder.generate_images(prompts)
  File "C:\Users\pychnight\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\finetune_utils.py", line 526, in generate_images
    processed = process_txt2img(p)
  File "C:\Users\pychnight\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\finetune_utils.py", line 669, in process_txt2img
    status.nextjob()
  File "C:\Users\pychnight\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\db_shared.py", line 193, in nextjob
    self.do_set_current_image(False)
  File "C:\Users\pychnight\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\db_shared.py", line 231, in do_set_current_image
    if isinstance(check, numpy.array) or isinstance(check, type(PIL.Image)) or isinstance(check, type(pathlib.Path)):
TypeError: isinstance() arg 2 must be a type, a tuple of types, or a unio

and

Traceback (most recent call last):██████████████████████████████████████████████████▉  | 39/40 [00:08<00:00, 10.26it/s]
  File "C:\Users\Pychnight\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\dreambooth.py", line 568, in start_training
    result = main(config, use_subdir=use_subdir, lora_model=lora_model_name,
  File "C:\Users\Pychnight\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 968, in main
    return inner_loop()
  File "C:\Users\Pychnight\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 116, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "C:\Users\Pychnight\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 235, in inner_loop
    count, instance_paths, class_paths = generate_classifiers(args, lora_model, lora_weight=lora_alpha,
  File "C:\Users\Pychnight\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\finetune_utils.py", line 929, in generate_classifiers
    new_images = builder.generate_images(prompts)
  File "C:\Users\Pychnight\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\finetune_utils.py", line 560, in generate_images
    processed = process_txt2img(p)
  File "C:\Users\Pychnight\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\finetune_utils.py", line 703, in process_txt2img
    status.nextjob()
  File "C:\Users\Pychnight\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\db_shared.py", line 193, in nextjob
    self.do_set_current_image(False)
  File "C:\Users\Pychnight\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\db_shared.py", line 231, in do_set_current_image
    if isinstance(check, numpy.array) or isinstance(check, type(PIL.Image)) or isinstance(check, type(pathlib.Path)):
TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union
  0%|                                                                                           | 0/35 [00:11<?, ?it/s]
Training completed, reloading SD Model.
Restored system models.
Returning result: Exception training model: 'isinstance() arg 2 must be a type, a tuple of types, or a union'.

Using the newest commit

with having generate with text2img

 File "C:\Users\Pychnight\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\dreambooth.py", line 561, in start_training
    result = main(config, use_txt2img=use_txt2img)
  File "C:\Users\Pychnight\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 973, in main
    return inner_loop()
  File "C:\Users\Pychnight\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 116, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "C:\Users\Pychnight\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 229, in inner_loop
    count, instance_paths, class_paths = generate_classifiers(args, use_txt2img=use_txt2img, accelerator=accelerator, ui = False)
  File "C:\Users\Pychnight\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\finetune_utils.py", line 925, in generate_classifiers
    new_images = builder.generate_images(prompts)
  File "C:\Users\Pychnight\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\finetune_utils.py", line 560, in generate_images
    processed = process_txt2img(p)
  File "C:\Users\Pychnight\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\finetune_utils.py", line 703, in process_txt2img
    status.nextjob()
  File "C:\Users\Pychnight\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\db_shared.py", line 194, in nextjob
    self.do_set_current_image(False)
  File "C:\Users\Pychnight\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\db_shared.py", line 232, in do_set_current_image
    if isinstance(check, numpy.array) or isinstance(check, type(PIL.Image)) or isinstance(check, type(pathlib.Path)):

and after it unchecked

Steps: : 0it [00:00, ?it/s]Traceback (most recent call last):
  File "C:\Users\Pychnight\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\dreambooth.py", line 561, in start_training
    result = main(config, use_txt2img=use_txt2img)
  File "C:\Users\Pychnight\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 973, in main
    return inner_loop()
  File "C:\Users\Pychnight\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 116, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "C:\Users\Pychnight\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 807, in inner_loop
    latents = vae.encode(batch["pixel_values"].to(dtype=weight_dtype)).latent_dist.sample()
TypeError: 'NoneType' object is not subscriptable

**Environment**

What OS?

Windows 11

If Windows - WSL or native?

Native

What GPU are you using?

evga 3080 ti

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the
db_config.json file from /models/dreambooth/MODELNAME/db_config.json

tried other configs and models, seems to effect every one, i had made.

**Comment by noimjosh** [comment]
Occurs on native Debian install as well.  Temporary solution was to revert to commit c7b5491:
`git checkout -b old-state c7b5491`

**Comment by Pychnight** [comment]
sadly for me, the new commits tainted the data set for the config, Reverting was the first thing, i tried but if i revert it produces this error

```
Exception generating dataset: integer division or modulo by zero
Traceback (most recent call last):
  File "C:\Users\pychnight\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\dreambooth.py", line 569, in start_training
    result = main(config, use_subdir=use_subdir, lora_model=lora_model_name,
  File "C:\Users\pychnight\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1024, in main
    return inner_loop()
  File "C:\Users\pychnight\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 86, in decorator
    return function(batch_size, grad_size, *args, **kwargs)
  File "C:\Users\war45\Documents\GitHub\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 250, in inner_loop
    count, _, _ = generate_classifiers(args, lora_model, lora_weight=lora_alpha,
ValueError: not enough values to unpack (expected 3, got 2)
Training completed, reloading SD Model.
Restored system models.
Returning result: Exception training model: not enough values to unpack (expected 3, got 2)
```

to work around this, i will likely have to create a entirely new model and reset  the training from zero which will be my last resort.

**Comment by Dasor92** [comment]
you can uncheck "generate class images from text2image tab" to get it work meanwhile

**Comment by Romustach** [comment]
Hi, 

Unable to use Dreambooth since the update too. I get the same error every time: 

Exception training model: ''NoneType' object is not subscriptable

Someone could help ?

**Comment by Pychnight** [comment]
this exception after further testing and debugging might be a result of a typo in one of the file paths within your concept list.

I created a test concept test that points to one directory just for debugging purposes and found the model allows the training to start without any problems. that was with a test concept of 7 concepts.

however older versions of dreambooth did point out typo's and handle them far better then the new versions, I would recommend reverting back to a commit before SD2.0 was implemented just to verify if your concept list has any typo's or invalid paths as for the lora errors, I have not found any work around for that yet or the text2img errors.

hopefully @d8ahazard re-implements valid path checks soon along with fixing the above issue or some one who can create a pull request to implement such checks again.

**Comment by Pychnight** [comment]
just a small follow up, i have fixed the TypeError: 'NoneType' object is not subscriptable errors, there where quite a few regressions over the last few commits.


I found that the detection of invalid paths is not correctly working, so, i modified the code to verify that the paths are valid, I noticed that it was actually already doing that within the code but that section of code was never hit and was not printing out any user friendly messages. after improving that, i was able to verify the following 3 configs below.

So, i created 3 test json files and resolved that one issue by reproducing the issues within the json files.

```
[
	{
		"instance_prompt":		"fire",
		"instance_token":		"fire",
		"class_prompt":			"stylized fire",
		"class_token":          "",
		"instance_data_dir":	"H:\\dataset\\test",
		"class_data_dir":		"H:\\dataset\\test",
				"max_steps": -1,
		"save_sample_prompt": "fire",
        "save_sample_template": "",
        "num_class_images": 30,
		"class_negative_prompt": "",
		"class_guidance_scale": 7.5,
		"class_infer_steps": 40,
		"save_sample_negative_prompt": "",
		"n_save_sample": 1,
		"sample_seed": -1,
		"save_guidance_scale": 7.5,
		"save_infer_steps": 40
	}
]
```

```
[
	{
		"instance_prompt":		"fire",
		"instance_token":		"fire",
		"class_prompt":			"stylized fire",
		"class_token":          "",
		"instance_data_dir":	"H:\\dataset\\tesf",
		"class_data_dir":		"H:\\dataset\\test",
				"max_steps": -1,
		"save_sample_prompt": "fire",
        "save_sample_template": "",
        "num_class_images": 30,
		"class_negative_prompt": "",
		"class_guidance_scale": 7.5,
		"class_infer_steps": 40,
		"save_sample_negative_prompt": "",
		"n_save_sample": 1,
		"sample_seed": -1,
		"save_guidance_scale": 7.5,
		"save_infer_steps": 40
	}
]
```

```
[
	{
		"instance_prompt":		"fire",
		"instance_token":		"fire",
		"class_prompt":			"stylized fire",
		"class_token":          "",
		"instance_data_dir":	"H:/dataset/test",
		"class_data_dir":		"H:/dataset/test",
				"max_steps": -1,
		"save_sample_prompt": "fire",
        "save_sample_template": "",
        "num_class_images": 30,
		"class_negative_prompt": "",
		"class_guidance_scale": 7.5,
		"class_infer_steps": 40,
		"save_sample_negative_prompt": "",
		"n_save_sample": 1,
		"sample_seed": -1,
		"save_guidance_scale": 7.5,
		"save_infer_steps": 40
	}
]
```

Valid, Typo, Wrong path. as you noticed if you use forward slashes / in the json with the recent comments it will cause the NoneType error regardless if the path is valid or not.

So for now adjust all json files to use back slashes \

**Comment by Romustach** [comment]
@Pychnight Thank you very much for your detailed answers. For my part i went back to the previous version, much more stable and simple in my opinion, that works perfectly.
