### ISSUE TITLE
Preventing any extension update due to "git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)"

### ISSUE THREAD

**Issue by Aryetis** [d8ahazard/sd_dreambooth_extension#717]
### Kindly read the entire form below and fill it out with the requested information.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your
issue will be automatically closed._**

`
Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Commit hash: c295e4a2446bcc2663f497ba8afa14cec80de332
Installing requirements for Web UI
Skipping dreambooth installation.
Dreambooth revision is 8e5e48178f1b0a92d798630e3e7cc31a65a63493
Diffusers version is 0.10.2
Torch version is 1.12.1+cu116
Torch vision version is 0.13.1+cu116
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes

**Have you updated Dreambooth to the latest revision?**
Yes (through web-ui untill it was working)

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**
OK

**Describe the bug**

Whenever I try to update my extensions by going : Extensions->Installed->Check for updates
git starts complaining about :
`git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)`
for each installed extension. 

However the moment I uninstall dreambooth extension, everything works fine right back.

Reinstalling dreambooth's extension didn't help.

Bug seems to have already been reported on Auto1111's repo but not here https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/6447

**Provide logs**

(It goes the same for every installed extension, full log available here : https://pastebin.com/ZpDHg4YM)

```
To create a public link, set `share=True` in `launch()`.
Error checking updates for ABG_extension:
Traceback (most recent call last):
  File "D:\outils\stable-diffusion-webui\modules\ui_extensions.py", line 61, in check_updates
    ext.check_updates()
  File "D:\outils\stable-diffusion-webui\modules\extensions.py", line 61, in check_updates
    for fetch in repo.remote().fetch("--dry-run"):
  File "D:\outils\stable-diffusion-webui\venv\lib\site-packages\git\remote.py", line 1007, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress, kill_after_timeout=kill_after_timeout)
  File "D:\outils\stable-diffusion-webui\venv\lib\site-packages\git\remote.py", line 848, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "D:\outils\stable-diffusion-webui\venv\lib\site-packages\git\cmd.py", line 604, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v -- origin --dry-run
  stderr: 'fatal: couldn't find remote ref --dry-run'
```

**Environment**

Windows 11 (native)
with 
MSI RTX 2070 SUPER Ventus OC

**Screenshots/Config**

N/A

**Comment by EriIaz** [comment]
same issue mentioned here.
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/6447

**Comment by d8ahazard** [comment]
Nevermind. I pushed a bumped revision for gitpython. Reverting it fixed the issue.

**Comment by amiremami** [comment]
I also report same bug I guess here: #982 

And someone else in discussion: #981

**Comment by a373648449** [comment]
*** Arguments: ('https://github.com/LonicaMewinsky/gif2gif.git', ['ads', 'localization', 'installed'], 0, '') {}
    Traceback (most recent call last):
      File "/home/sj/stable-diffusion-webui/modules/call_queue.py", line 55, in f
        res = list(func(*args, **kwargs))
      File "/home/sj/stable-diffusion-webui/modules/ui_extensions.py", line 384, in install_extension_from_index
        ext_table, message = install_extension_from_url(None, url)
      File "/home/sj/stable-diffusion-webui/modules/ui_extensions.py", line 354, in install_extension_from_url
        with git.Repo.clone_from(url, tmpdir, filter=['blob:none']) as repo:
      File "/home/sj/stable-diffusion-webui/venv/lib/python3.10/site-packages/git/repo/base.py", line 1308, in clone_from
        return cls._clone(
      File "/home/sj/stable-diffusion-webui/venv/lib/python3.10/site-packages/git/repo/base.py", line 1219, in _clone
        finalize_process(proc, stderr=stderr)
      File "/home/sj/stable-diffusion-webui/venv/lib/python3.10/site-packages/git/util.py", line 419, in finalize_process
        proc.wait(**kwargs)
      File "/home/sj/stable-diffusion-webui/venv/lib/python3.10/site-packages/git/cmd.py", line 604, in wait
        raise GitCommandError(remove_password_if_present(self.args), status, errstr)
    git.exc.GitCommandError: Cmd('git') failed due to: exit code(129)
      cmdline: git clone -v --filter=blob:none -- https://github.com/LonicaMewinsky/gif2gif.git /home/sj/stable-diffusion-webui/tmp/gif2gif
      stderr: 'error: unknown option `filter=blob:none'
    usage: git clone [<options>] [--] <repo> [<dir>]

        -v, --verbose         be more verbose
        -q, --quiet           be more quiet
        --progress            force progress reporting
        -n, --no-checkout     don't create a checkout
        --bare                create a bare repository
        --mirror              create a mirror repository (implies bare)
        -l, --local           to clone from a local repository
        --no-hardlinks        don't use local hardlinks, always copy
        -s, --shared          setup as shared repository
        --recursive           initialize submodules in the clone
        --recurse-submodules  initialize submodules in the clone
        --template <template-directory>
                              directory from which templates will be used
        --reference <repo>    reference repository
        --dissociate          use --reference only while cloning
        -o, --origin <name>   use <name> instead of 'origin' to track upstream
        -b, --branch <branch>
                              checkout <branch> instead of the remote's HEAD
        -u, --upload-pack <path>
                              path to git-upload-pack on the remote
        --depth <depth>       create a shallow clone of that depth
        --single-branch       clone only one branch, HEAD or --branch
        --separate-git-dir <gitdir>
                              separate git dir from working tree
        -c, --config <key=value>
                              set config inside the new repository  



 I have also encountered this problem and cannot solve it at the moment. I can only go locally to do a Git clone
