### ISSUE TITLE
Importing from Hugging Face Fails with error

### ISSUE THREAD

**Issue by mediocreatmybest** [d8ahazard/sd_dreambooth_extension#719]
### Kindly read the entire form below and fill it out with the requested information.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your
issue will be automatically closed._**

```
#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
Dreambooth revision: 8e5e48178f1b0a92d798630e3e7cc31a65a63493
SD-WebUI revision: 151233399c4b79934bdbb7c12a97eeb6499572fb

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.15+e163309.d20221230 installed.
[+] torch version 1.12.1+cu116 installed.
[+] torchvision version 0.13.1+cu116 installed.

#######################################################################################################

```

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**

Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**

Yes

**Have you updated Dreambooth to the latest revision?**

Yes 

**Have you updated the Stable-Diffusion-WebUI to the latest version?**

Yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**

Yes

**Describe the bug**

When importing from hugging face to create a new model the following error message is given.
This is with SD2 Base, this could be specific with SD2 as I haven't checked with 1.5 yet. 

(A clear and concise description of what the bug is)

**Provide logs**

Trying to create SDv2_512 from huggingface.co/stabilityai/stable-diffusion-2-base

```
Loading model from hub.
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 539/539 [00:00<00:00, 269kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 342/342 [00:00<00:00, 242kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 308/308 [00:00<00:00, 252kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 738/738 [00:00<00:00, 588kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.36G/1.36G [02:28<00:00, 9.18MB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 525k/525k [00:01<00:00, 396kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 460/460 [00:00<00:00, 354kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 929/929 [00:00<00:00, 801kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.06M/1.06M [00:01<00:00, 668kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.01k/1.01k [00:00<00:00, 857kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.46G/3.46G [07:43<00:00, 7.48MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 716/716 [00:00<00:00, 417kB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 335M/335M [00:33<00:00, 10.1MB/s]
Fetching 13 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13/13 [11:14<00:00, 51.85s/it]
Exception setting up output: 'torch.device' object has no attribute 'values'
Traceback (most recent call last):
  File "/home/machinelearning/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/sd_to_diff.py", line 905, in extract_checkpoint
    pipe = DiffusionPipeline.from_pretrained(new_model_url, use_auth_token=new_model_token,
  File "/home/machinelearning/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/pipeline_utils.py", line 709, in from_pretrained
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "/home/machinelearning/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/modeling_utils.py", line 496, in from_pretrained
    accelerate.load_checkpoint_and_dispatch(model, model_file, device_map)
  File "/home/machinelearning/stable-diffusion-webui/venv/lib/python3.10/site-packages/accelerate/big_modeling.py", line 373, in load_checkpoint_and_dispatch
    if offload_state_dict is None and "disk" in device_map.values():
AttributeError: 'torch.device' object has no attribute 'values'
Pipeline or config is not set, unable to continue.
Can't load config!
Traceback (most recent call last):
  File "/home/machinelearning/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "/home/machinelearning/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1016, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/home/machinelearning/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 945, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range

```

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *
before* the crash occurred.

**Environment**

What OS?

Linux

If Windows - WSL or native?

What GPU are you using?

Nvidia 3060 12GB vRAM

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the
db_config.json file from /models/dreambooth/MODELNAME/db_config.json

**Comment by mediocreatmybest** [comment]
Also fails with SD1.5 with a different but similar error. 

```
Trying to create SDv15_Test from huggingface.co/runwayml/stable-diffusion-v1-5
Loading model from hub.
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 543/543 [00:00<00:00, 794kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 342/342 [00:00<00:00, 262kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4.72k/4.72k [00:00<00:00, 2.75MB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.22G/1.22G [01:51<00:00, 10.9MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 308/308 [00:00<00:00, 261kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 617/617 [00:00<00:00, 470kB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 492M/492M [00:43<00:00, 11.3MB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 525k/525k [00:01<00:00, 398kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 472/472 [00:00<00:00, 398kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 806/806 [00:00<00:00, 489kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.06M/1.06M [00:01<00:00, 791kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 743/743 [00:00<00:00, 615kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.44G/3.44G [05:09<00:00, 11.1MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 547/547 [00:00<00:00, 477kB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 335M/335M [00:30<00:00, 10.8MB/s]
Fetching 15 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [08:49<00:00, 35.30s/it]
Exception setting up output: 'torch.device' object has no attribute 'values'
Traceback (most recent call last):
  File "/home/machinelearning/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/sd_to_diff.py", line 905, in extract_checkpoint
    pipe = DiffusionPipeline.from_pretrained(new_model_url, use_auth_token=new_model_token,
  File "/home/machinelearning/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/pipeline_utils.py", line 709, in from_pretrained
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "/home/machinelearning/stable-diffusion-webui/venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2379, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/machinelearning/stable-diffusion-webui/venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2442, in _load_pretrained_model
    if device_map is not None and "disk" in device_map.values():
AttributeError: 'torch.device' object has no attribute 'values'
Pipeline or config is not set, unable to continue.

```

**Comment by sebaxakerhtc** [comment]
Same here. There's no problem to create models from ckpt, but from huggingface.

**Comment by d8ahazard** [comment]
I have added support for a much wider array of models from the hub with the latest version.

In the past version, only models that had diffusion weights would work. Now, any model in .ckpt or .safetensors will work as well.

Additionally, you don't need to use the dev/model name standard any more, full URLs will work as well.
