### ISSUE TITLE
Dreambooth doesn't appair

### ISSUE THREAD

**Issue by gigoshubitidze** [d8ahazard/sd_dreambooth_extension#722]
Restarting UI...
Error loading script: api.py
Traceback (most recent call last):
  File "H:\1_AI\stable-diffusion-portable-main\modules\scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "H:\1_AI\stable-diffusion-portable-main\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "H:\1_AI\stable-diffusion-portable-main\extensions\sd_dreambooth_extension\scripts\api.py", line 20, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.db_config import from_file, DreamboothConfig
  File "H:\1_AI\stable-diffusion-portable-main\extensions\sd_dreambooth_extension\dreambooth\db_config.py", line 6, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.db_concept import Concept
  File "H:\1_AI\stable-diffusion-portable-main\extensions\sd_dreambooth_extension\dreambooth\db_concept.py", line 5, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.utils import get_images
  File "H:\1_AI\stable-diffusion-portable-main\extensions\sd_dreambooth_extension\dreambooth\utils.py", line 18, in <module>
    import tensorflow
ModuleNotFoundError: No module named 'tensorflow'

E

**Comment by d8ahazard** [comment]
This issue has been automatically closed. Please use the [appropriate form](https://github.com/d8ahazard/sd_dreambooth_extension/issues/new/choose) when submitting an issue. Thank you.
