### ISSUE TITLE
AttributeError: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by Jonseed** [d8ahazard/sd_dreambooth_extension#73]
After trying many different settings, I was finally able to get it to train on my 3060 12GB, but at the end of training I got this error:

```
Traceback (most recent call last):
  File "F:\repos\auto111\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "F:\repos\auto111\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "F:\repos\auto111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 265, in start_training
    trained_steps = main(config)
  File "F:\repos\auto111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 909, in main
    save_weights(lifetime_step, save_model, save_img)
  File "F:\repos\auto111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 766, in save_weights
    text_enc_model = CLIPTextModel.from_pretrained(args.working_dir, subfolder="text_encoder")
  File "F:\repos\auto111\stable-diffusion-webui\venv\lib\site-packages\transformers\modeling_utils.py", line 1764, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "F:\repos\auto111\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\configuration_clip.py", line 129, in from_pretrained
    if config_dict.get("model_type") == "clip":
AttributeError: 'list' object has no attribute 'get'

Steps: 100%|██████████| 2000/2000 [32:10<00:00,  1.04it/s, loss=0.188, lr=5e-6]
```

It looks like it might be about the text encoder, but I had "train text encoder" unchecked. I will try to check it on my next run to see if that changes anything...

**Comment by d8ahazard** [comment]
If you look in F:\repos\auto111\stable-diffusion-webui\models\dreambooth\YOURMODEL\working - is there a folder called "text_encoder", and what's in it if so?

**Comment by Jonseed** [comment]
config.json
pytorch_model.bin

But I've also now started training with "train text encoder" checked, so not sure if that's affected it...

**Comment by Jonseed** [comment]
So checking "train text encoder" gives me this error now at the end of training...

```
Traceback (most recent call last):
  File "F:\repos\auto111\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "F:\repos\auto111\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "F:\repos\auto111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 265, in start_training
    trained_steps = main(config)
  File "F:\repos\auto111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 909, in main
    save_weights(lifetime_step, save_model, save_img)
  File "F:\repos\auto111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 772, in save_weights
    vae=AutoencoderKL.from_pretrained(
  File "F:\repos\auto111\stable-diffusion-webui\venv\lib\site-packages\diffusers\modeling_utils.py", line 472, in from_pretrained
    set_module_tensor_to_device(model, param_name, param_device, value=param)
  File "F:\repos\auto111\stable-diffusion-webui\venv\lib\site-packages\accelerate\utils\modeling.py", line 106, in set_module_tensor_to_device
    new_module = getattr(module, split)
  File "F:\repos\auto111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ModuleList' object has no attribute '1'

Steps: 100%|████████████████| 1000/1000 [20:11<00:00,  1.21s/it, loss=0.0784, lr=5e-6]
```

**Comment by Jonseed** [comment]
Do I need to recreate the model in between test runs? Or does that not matter?

**Comment by Jonseed** [comment]
Unchecking "train text encoder" and restarting training leaves the text_encoder folder intact, so that is why I ask if I need to recreate the model...

**Comment by d8ahazard** [comment]
> Do I need to recreate the model in between test runs? Or does that not matter?

Nope. Every time you train, the model in /working gets updated. There will always be a text encoder directory, but it only gets updated when "train text encoder" is checked. 

So, the only reason you'd need to re-create the model is if you borked something in the encoder you wanted to get rid of.

**Comment by Jonseed** [comment]
I've tried several different base checkpoints, including the standard 1.4 and 1.5, and they all produce the same errors. One thing I haven't tried yet is setting the "save checkpoints every N steps" to something higher than the training steps. I have always set it as the same number, so it would save a ckpt at the end, but that might be automatic and causing a collision of some kind at the end of training...

**Comment by d8ahazard** [comment]
Give it a whirl now, I added few fixes.

**Comment by Jonseed** [comment]
Yes! I just finished my first successful training on 3060 12GB! commit c1702f13820984a4dbe0f5c4552a14c7833b277e

checked "don't cache latents," checked "train text encoder"
