### ISSUE TITLE
Recent update gives huggingface error

### ISSUE THREAD

**Issue by daniel5984** [d8ahazard/sd_dreambooth_extension#752]
OSError: Can't load tokenizer for 'stabilityai/stable-diffusion-2'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'stabilityai/stable-diffusion-2' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.
Pipeline or config is not set, unable to continue.
Returning ['default', True, True, 1, '', '', 0, 0, 1, True, True, 50, False, False, 5e-06, 1e-06, 0.0001, '', 5e-05, 1.0, 1.0, 1, 0.5, 1.0, 0.5, 'constant_with_warmup', 0, 75, 'fp16', 100, True, '', 1.0, 768, 1, '', 420420, True, False, True, 25, True, False, True, 5, False, False, False, False, 1, False, 1.0, True, False, True, False, False, '', 7.5, 60, '', '', '', '', '', '', 1, 0, 0, -1, 7.5, 60, '', '', '', '', 7.5, 60, '', '', '', '', '', '', 1, 0, 0, -1, 7.5, 60, '', '', '', '', 7.5, 60, '', '', '', '', '', '', 1, 0, 0, -1, 7.5, 60, '', '', '', 'Loaded config.']
Please configure some concepts.
Saved settings.
Saved settings.
Custom model name is 
Starting Dreambooth training...
Initializing dreambooth training...
Replace CrossAttention.forward to use xformers
Instance Bucket 0: Resolution (384, 384), Count: 1
Instance Bucket 1: Resolution (384, 512), Count: 3
Instance Bucket 2: Resolution (384, 576), Count: 4
Instance Bucket 3: Resolution (384, 768), Count: 1
Instance Bucket 4: Resolution (448, 384), Count: 5
Instance Bucket 5: Resolution (448, 448), Count: 13
Instance Bucket 6: Resolution (448, 576), Count: 3
Instance Bucket 7: Resolution (448, 640), Count: 2
Instance Bucket 8: Resolution (448, 704), Count: 1
Instance Bucket 9: Resolution (448, 768), Count: 8
Instance Bucket 10: Resolution (512, 512), Count: 8
Instance Bucket 11: Resolution (512, 640), Count: 4
Instance Bucket 12: Resolution (512, 704), Count: 7
Instance Bucket 13: Resolution (512, 768), Count: 7
Instance Bucket 14: Resolution (576, 448), Count: 2
Instance Bucket 15: Resolution (576, 512), Count: 1
Instance Bucket 16: Resolution (576, 576), Count: 8
Instance Bucket 17: Resolution (576, 640), Count: 2
Instance Bucket 18: Resolution (576, 768), Count: 20
Instance Bucket 19: Resolution (640, 448), Count: 1
Instance Bucket 20: Resolution (640, 640), Count: 3
Instance Bucket 21: Resolution (640, 768), Count: 14
Instance Bucket 22: Resolution (704, 576), Count: 1
Instance Bucket 23: Resolution (704, 704), Count: 1
Instance Bucket 24: Resolution (704, 768), Count: 15
Instance Bucket 25: Resolution (768, 512), Count: 2
Instance Bucket 26: Resolution (768, 576), Count: 1
Instance Bucket 27: Resolution (768, 640), Count: 1
Instance Bucket 28: Resolution (768, 704), Count: 1
Instance Bucket 29: Resolution (768, 768), Count: 218
Target Bucket 0: Resolution (384, 384), Count: 0
Target Bucket 1: Resolution (384, 512), Count: 0
Target Bucket 2: Resolution (384, 576), Count: 0
Target Bucket 3: Resolution (384, 768), Count: 0
Target Bucket 4: Resolution (448, 384), Count: 0
Target Bucket 5: Resolution (448, 448), Count: 0
Target Bucket 6: Resolution (448, 576), Count: 0
Target Bucket 7: Resolution (448, 640), Count: 0
Target Bucket 8: Resolution (448, 704), Count: 0
Target Bucket 9: Resolution (448, 768), Count: 0
Target Bucket 10: Resolution (512, 512), Count: 0
Target Bucket 11: Resolution (512, 640), Count: 0
Target Bucket 12: Resolution (512, 704), Count: 0
Target Bucket 13: Resolution (512, 768), Count: 0
Target Bucket 14: Resolution (576, 448), Count: 0
Target Bucket 15: Resolution (576, 512), Count: 0
Target Bucket 16: Resolution (576, 576), Count: 0
Target Bucket 17: Resolution (576, 640), Count: 0
Target Bucket 18: Resolution (576, 768), Count: 0
Target Bucket 19: Resolution (640, 448), Count: 0
Target Bucket 20: Resolution (640, 640), Count: 0
Target Bucket 21: Resolution (640, 768), Count: 0
Target Bucket 22: Resolution (704, 576), Count: 0
Target Bucket 23: Resolution (704, 704), Count: 0
Target Bucket 24: Resolution (704, 768), Count: 0
Target Bucket 25: Resolution (768, 512), Count: 0
Target Bucket 26: Resolution (768, 576), Count: 0
Target Bucket 27: Resolution (768, 640), Count: 0
Target Bucket 28: Resolution (768, 704), Count: 0
Target Bucket 29: Resolution (768, 768), Count: 0
We need a total of 0 images.
Nothing to generate.
Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/dreambooth.py", line 561, in start_training
    result = main(config, use_txt2img=use_txt2img)
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 973, in main
    return inner_loop()
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 116, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "/notebooks/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 246, in inner_loop
    tokenizer = AutoTokenizer.from_pretrained(
  File "/usr/local/lib/python3.9/dist-packages/transformers/models/auto/tokenization_auto.py", line 582, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/transformers/models/auto/tokenization_auto.py", line 433, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "/usr/local/lib/python3.9/dist-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/usr/local/lib/python3.9/dist-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    validate_repo_id(arg_value)
  File "/usr/local/lib/python3.9/dist-packages/huggingface_hub/utils/_validators.py", line 166, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/notebooks/stable-diffusion-webui/models/dreambooth/pattern3/working/tokenizer'. Use `repo_type` argument if needed.
Training completed, reloading SD Model.
Restored system models.
Returning result: Exception training model: 'Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/notebooks/stable-diffusion-webui/models/dreambooth/pattern3/working/tokenizer'. Use `repo_type` argument if needed.'.

![image](https://user-images.githubusercontent.com/61990796/211627412-3273f55e-953a-4952-abe4-657de9973516.png)

**Comment by cerarslan** [comment]
Same for a while for me. Samething wrong with tokenizer but it is just my thought.

**Comment by cerarslan** [comment]
Did you solve that mate?

**Comment by daniel5984** [comment]
> Did you solve that mate?

nope

**Comment by daniel5984** [comment]
new error while creating model
![image](https://user-images.githubusercontent.com/61990796/211671893-91d0c44b-11d8-4163-bed2-9325e35fc0d1.png)

**Comment by cerarslan** [comment]
Did you try v1.5 model?

**Comment by daniel5984** [comment]
nah will try

**Comment by daniel5984** [comment]
i deleted dreambooth extension and everything went fine, if i install again it outputs errors

**Comment by daniel5984** [comment]
> Output errors?

![image](https://user-images.githubusercontent.com/61990796/211680348-4b68eb9c-52db-44c1-ab96-58cc16eb1fb5.png)

**Comment by cerarslan** [comment]
Same for me

**Comment by daniel5984** [comment]
@d8ahazard

**Comment by daniel5984** [comment]
temporary fix @cerarslan 
%cd /notebooks/stable-diffusion-webui/
!git checkout 552d7b90bf483c160cd20740f7acd7fccbc02e6f

**Comment by cerarslan** [comment]
well.. can you write to me step by step? @daniel5984

**Comment by cerarslan** [comment]
Even ıf I deleted all extension folder it gives me /content/gdrive/MyDrive/sd/stable-diffusion-webui
fatal: reference is not a tree: 552d7b90bf483c160cd20740f7acd7fccbc02e6f
2023-01-11 00:12:50.222127: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-11 00:12:51.271808: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
2023-01-11 00:12:51.271948: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
2023-01-11 00:12:51.271969: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Failed to create model quickly; will retry using slow method.
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
loading stable diffusion model: TypeError
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 338, in load_model
    sd_model = instantiate_from_config(sd_config.model)
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/models/diffusion/ddpm.py", line 563, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/models/diffusion/ddpm.py", line 630, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/modules/encoders/modules.py", line 99, in __init__
    self.tokenizer = CLIPTokenizer.from_pretrained(version)
  File "/usr/local/lib/python3.8/dist-packages/transformers/tokenization_utils_base.py", line 1801, in from_pretrained
    return cls._from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/tokenization_utils_base.py", line 1956, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/clip/tokenization_clip.py", line 328, in __init__
    with open(merges_file, encoding="utf-8") as merges_handle:
TypeError: expected str, bytes or os.PathLike object, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 74, in initialize
    modules.sd_models.load_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 341, in load_model
    sd_model = instantiate_from_config(sd_config.model)
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/models/diffusion/ddpm.py", line 563, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/models/diffusion/ddpm.py", line 630, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/modules/encoders/modules.py", line 99, in __init__
    self.tokenizer = CLIPTokenizer.from_pretrained(version)
  File "/usr/local/lib/python3.8/dist-packages/transformers/tokenization_utils_base.py", line 1801, in from_pretrained
    return cls._from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/tokenization_utils_base.py", line 1956, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/clip/tokenization_clip.py", line 328, in __init__
    with open(merges_file, encoding="utf-8") as merges_handle:
TypeError: expected str, bytes or os.PathLike object, not NoneType


Stable diffusion model failed to load, exiting
