### ISSUE TITLE
Can't launch Stable Diffusion AUTOMATIC1111 after installing dreambooth extension

### ISSUE THREAD

**Issue by lucasblack22** [d8ahazard/sd_dreambooth_extension#754]
### Kindly read the entire form below and fill it out with the requested information.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your
issue will be automatically closed._**

`
venv "C:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: <none>
Installing requirements for Web UI

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: 55880895d6bdf3596db815cb62e22969e9910b7b
SD-WebUI revision:

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.14.dev0 installed.
[+] torch version 1.12.1+cu113 installed.
[+] torchvision version 0.13.1+cu113 installed.

#######################################################################################################

Launching Web UI with arguments: --xformers
SD-Webui API layer loaded
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Failed to create model quickly; will retry using slow method.
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
loading stable diffusion model: TypeError
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\sd_models.py", line 338, in load_model
    sd_model = instantiate_from_config(sd_config.model)
  File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 563, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 630, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\encoders\modules.py", line 99, in __init__
    self.tokenizer = CLIPTokenizer.from_pretrained(version)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1801, in from_pretrained
    return cls._from_pretrained(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1956, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\tokenization_clip.py", line 328, in __init__
    with open(merges_file, encoding="utf-8") as merges_handle:
TypeError: expected str, bytes or os.PathLike object, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\stable-diffusion-webui\webui.py", line 74, in initialize
    modules.sd_models.load_model()
  File "C:\stable-diffusion-webui\modules\sd_models.py", line 341, in load_model
    sd_model = instantiate_from_config(sd_config.model)
  File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 563, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 630, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\encoders\modules.py", line 99, in __init__
    self.tokenizer = CLIPTokenizer.from_pretrained(version)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1801, in from_pretrained
    return cls._from_pretrained(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1956, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\tokenization_clip.py", line 328, in __init__
    with open(merges_file, encoding="utf-8") as merges_handle:
TypeError: expected str, bytes or os.PathLike object, not NoneType

Stable diffusion model failed to load, exiting
Press any key to continue . . .
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes 

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes

**Have you updated Dreambooth to the latest revision?**
Yes
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes (or at least i think so. Installed from github today) 
**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**
Yes

**Describe the bug**

New to stable diffusion.  Installed Automatic1111 UI and Stable Diffusion with no issues. Running fine.  Installed the dreambooth extension from the extensions tab and then closed out of the CMD window and the Browser UI.  On relauch I get the above errors.  Will not launch.  If I remove the Dreambooth extension then Stable Diffusion Webui launches again fine. 

**Provide logs**

Please see above.

**Environment**

What OS?
Windows 10 
If Windows - WSL or native?

What GPU are you using?
Geforce 3090

**Comment by lucasblack22** [comment]
reinstalled everything with no different result.  Did get some updated version info, not sure why it was blank before:
venv "C:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 9cfd10cdefc7b2966b8e42fbb0e05735967cf87b
Installing requirements for Web UI

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: 55880895d6bdf3596db815cb62e22969e9910b7b
SD-WebUI revision: 9cfd10cdefc7b2966b8e42fbb0e05735967cf87b

**Comment by Michu44** [comment]
I have the same issue

**Comment by endrsmar** [comment]
Same issue here

**Comment by rodmenam** [comment]
I am experiencing the same issue

**Comment by nonetrix** [comment]
Same here

**Comment by rodmenam** [comment]
I gave up and got the ckpt document from the Google Colab alternative… I guess it’s a matter of VRAM.

**Comment by nonetrix** [comment]
Error doesn't seem to have anything to do with VRAM

**Comment by lucasblack22** [comment]
Can you elaborate on what you did to resolve? Not familiar with the google colab ckpt. Are you saying you put in a different default model.ckpt and it resolved? If so where did you put it, in the standard stable diffusion model folder?

On Jan 12, 2023, at 6:16 PM, RodrigoMena ***@***.***> wrote:

﻿

I gave up and got the ckpt document from the Google Colab alternative… I guess it’s a matter of VRAM.

**Comment by rodmenam** [comment]
Although it doesn't have too many views, this is the best [Tutorial] I've watched so far. (https://www.youtube.com/watch?v=fyBqkKCIpYU&lc=UgwoiWsSOhQtgG31uax4AaABAg.9kltOdENVF39kmdEndOrK0)

**Comment by lucasblack22** [comment]
> Although it doesn't have too many views, this is the best [Tutorial] I've watched so far. (https://www.youtube.com/watch?v=fyBqkKCIpYU&lc=UgwoiWsSOhQtgG31uax4AaABAg.9kltOdENVF39kmdEndOrK0)

Ah, just for clarification. You didn't get dreambooth working on your computer, you trained a model on google colab with dreambooth and then imported that model to your local computer after you trained it on Google colab, is that what you are saying?

**Comment by rodmenam** [comment]
Indeed, I realized my Graphics card was running short for Dreambooth, so I created the ckpt doc with that tutorial, then ran it on Stable and it's running smooth.
Guess we'll have to retry the steps everytime we're training a new face.

**Comment by lucasblack22** [comment]
> Indeed, I realized my Graphics card was running short for Dreambooth, so I created the ckpt doc with that tutorial, then ran it on Stable and it's running smooth.
> 
> Guess we'll have to retry the steps everytime we're training a new face.

Ok thanks for the clarification. I'm running a RTX 3090 so I should have enough resources for dreambooth. There's got to be some kind of simple installation part I'm missing to resolve these errors. I'll keep digging.

**Comment by endrsmar** [comment]
Finally found solution after digging through the files and adding multiple debug prints.

The issue is that by default (for some reason) Automatic1111 only downloads 2 files from https://huggingface.co/openai/clip-vit-large-patch14 and the rest is missing, and with dreambooth enabled you need the other files as well. Solution is to
```
cd {huggingface_cache_dir}/hub/models--openai--clip-vit-large-patch14/snapshots/8d052a0f05efbaefbc9e8786ba291cfdf93e5bff
rm ./*
GIT_LFS_SKIP_SMUDGE=1 git clone -v https://huggingface.co/openai/clip-vit-large-patch14 . && git lfs pull
```

**Comment by YeloPartyHat** [comment]
> Finally found solution after digging through the files and adding multiple debug prints.
> 
> The issue is that by default (for some reason) Automatic1111 only downloads 2 files from https://huggingface.co/openai/clip-vit-large-patch14 and the rest is missing, and with dreambooth enabled you need the other files as well. Solution is to
> 
> ```
> cd {huggingface_cache_dir}/hub/models--openai--clip-vit-large-patch14/snapshots/8d052a0f05efbaefbc9e8786ba291cfdf93e5bff
> rm ./*
> GIT_LFS_SKIP_SMUDGE=1 git clone -v https://huggingface.co/openai/clip-vit-large-patch14 . && git lfs pull
> ```
> 
> In my case the huggingface_cache_dir is `/home/{user}/.cache/huggingface/`

Great find. What files do I need to get from that huggingface link to get it working again? Do you think you could write a short guide in the meantime while this gets patched for all of us watching on this thread? :)

**Comment by endrsmar** [comment]
> 

I'm not sure which exact files are needed, that's why I'm suggesting to download the entire repository. What I wrote above is pretty much the guide
- install git-lfs
- go to hugging face cache dir, find `hub/models--openai--clip-vit-large-patch14/snapshots/8d052a0f05efbaefbc9e8786ba291cfdf93e5bff` directory and delete it's contents
- clone https://huggingface.co/openai/clip-vit-large-patch14 to this repository and also pull the large files using `git lfs pull`

**Comment by lucasblack22** [comment]
You are awesome!  Great job, Just a heads up in windows the hugging face cache directory is:
C:\Users\{username}\.cache\huggingface\

So the guide to fix for me on windows 10:
1. Install Automatic1111 per the standard way.
2. Install the dreambooth extension from the extensions tab as normal. 
3. close all CMD windows 
4. Browse to Huggingface cache directory in file explorer:   C:\Users\{username}\.cache\huggingface\hub\models--openai--clip-vit-large-patch14\snapshots\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\
5. Delete the contents inside of the directory "8d052a0f05efbaefbc9e8786ba291cfdf93e5bff" (for me it was just 2 .json files)
6. Run a CMD prompt window from that file explorer into the 8d052a0f05efbaefbc9e8786ba291cfdf93e5bff directory (easist way is to just type CMD from that window where you see the path)
7. Run this command: git clone -v https://huggingface.co/openai/clip-vit-large-patch14 . && git lfs pull
8. Once it completes, close window.
9. Launch Automatic1111 the normal way (webui-user.bat) (should work now)
10. Success!
