### ISSUE TITLE
MULTIPLE CONCEPTS give TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by bosbrand** [d8ahazard/sd_dreambooth_extension#768]
### Kindly read the entire form below and fill it out with the requested information.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your
issue will be automatically closed._**

Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 6ffefdcc9f47b66cbc543690d97cbf8327f4ba58

`Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: 17c3864803ebb50615205271de687be96cfc96e8
SD-WebUI revision: 6ffefdcc9f47b66cbc543690d97cbf8327f4ba58

`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yes, both

**Have you updated Dreambooth to the latest revision?**
yep, updated

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
sure thing

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**
OK
**Describe the bug**
 I get  'NoneType' object is not subscriptable exception' when starting training. I filled out the fields just like I did two days ago when it was still working. It seems it starts sorting the datasets and then throws an error. 

(A clear and concise description of what the bug is)

**Provide logs**

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *
before* the crash occurred.

**Environment**

What OS?

windows 11

What GPU are you using?
2080Ti, should do just fine. I've already trained two models using this setup. 

**Screenshots/Config**
If the issue is specific
[db_config.json.txt](https://github.com/d8ahazard/sd_dreambooth_extension/files/10405045/db_config.json.txt)
 to an error while training, please provide a screenshot of training parameters or the
db_config.json file from /models/dreambooth/MODELNAME/db_config.json

**Comment by ExponentialML** [comment]
Hey @bosbrand . Try these two things.

1. Make sure that your instance and data directories are correct.
2. Try to test a directory with just images and without file words.

**Comment by bosbrand** [comment]
Hi @ExponentialML, thank you so much for looking into this. I have checked the directories, I can't find anything at fault with them. One of them I used earlier. I'm trying to teach two concepts. Both have their own instance folder and they share the class images folder (but I also tried using different class folders). I tried without filewords too, nothing changes. I still get the exception with 'nonetype object is not subscriptable'. Nothing I do changes the error.

**Comment by Oncorporation** [comment]
Some of the training fields in the db_config.json file have changed. Compare your file with a version that you just saved. I have a library of training concepts and had to update my json.

In the concepts_list:
num_class_images may be missing
num_class_images_per is new

**Comment by digitaljohn** [comment]
I'm having a similar issue. Fairly standard setup through the UI.

```
File "/home/digitaljohn/Projects/stable-diffusion-webui-new/extensions/sd_dreambooth_extension/dreambooth/finetune_utils.py", line 521, in __init__
    if new_model_info[0] != current_model[0]:
TypeError: 'CheckpointInfo' object is not subscriptable
Training completed, reloading SD Model.
Restored system models.
Returning result: Exception training model: ''CheckpointInfo' object is not subscriptable'.
^CInterrupted with signal 2 in <frame at 0x144b7560, file '/home/digitaljohn/Projects/stable-diffusion-webui-new/webui.py', line 128, code wait_on_server>
```

**Comment by nub2927** [comment]
had the same issue, for some reason putting in .5 in the "Class Images Per Instance Image" allowed the training to continue

**Comment by mexyn** [comment]
> I'm having a similar issue. Fairly standard setup through the UI.
> 
> ```
> File "/home/digitaljohn/Projects/stable-diffusion-webui-new/extensions/sd_dreambooth_extension/dreambooth/finetune_utils.py", line 521, in __init__
>     if new_model_info[0] != current_model[0]:
> TypeError: 'CheckpointInfo' object is not subscriptable
> Training completed, reloading SD Model.
> Restored system models.
> Returning result: Exception training model: ''CheckpointInfo' object is not subscriptable'.
> ^CInterrupted with signal 2 in <frame at 0x144b7560, file '/home/digitaljohn/Projects/stable-diffusion-webui-new/webui.py', line 128, code wait_on_server>
> ```

I have the exact same error when trying to generate class images. 

> had the same issue, for some reason putting in .5 in the "Class Images Per Instance Image" allowed the training to continue
Yes, because in this case class image regeneration won't run and the training just begins without it. Its the same when u put in the value 0. So seems there is a bug in the class image generation, as there were made changes recently

**Comment by art-phony** [comment]
Same error happens for me.
Click "Train" Button or "Generate Class Images" Button cause an error below:

```
Generating class images...
Instance Bucket 0: Resolution (768, 768), Count: 502
Class Bucket 0: Resolution (768, 768), Count: 0
Target Bucket 0: Resolution (768, 768), Count: 2510
We need a total of 2510 images.
Generating 2510 class images for training...
Traceback (most recent call last):
  File "E:\AI_Drawing\automatic1111\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\dreambooth.py", line 635, in ui_classifiers
    count, images = generate_classifiers(config, use_txt2img=use_txt2img, ui=True)
  File "E:\AI_Drawing\automatic1111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\finetune_utils.py", line 900, in generate_classifiers
    builder = ImageBuilder(args, use_txt2img=use_txt2img, lora_model=args.lora_model_name, lora_weight=args.lora_weight,
  File "E:\AI_Drawing\automatic1111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\finetune_utils.py", line 521, in __init__
    if new_model_info[0] != current_model[0]:
TypeError: 'CheckpointInfo' object is not subscriptable
```

**Comment by bosbrand** [comment]
It might still be the dataset. I've trained one concept separately without issue, the other one I get the error. The only difference between both training sessions is the data part. I use the same regularization image folder for both. So I'm not generating any new class images.

**Comment by art-phony** [comment]
I tried another concept, but still same error occurs

```
Generating class images...
Instance Bucket 0: Resolution (768, 768), Count: 104
Class Bucket 0: Resolution (768, 768), Count: 0
Target Bucket 0: Resolution (768, 768), Count: 1040
We need a total of 1040 images.
Generating 1040 class images for training...
Traceback (most recent call last):
  File "E:\AI_Drawing\automatic1111\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\dreambooth.py", line 635, in ui_classifiers
    count, images = generate_classifiers(config, use_txt2img=use_txt2img, ui=True)
  File "E:\AI_Drawing\automatic1111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\finetune_utils.py", line 900, in generate_classifiers
    builder = ImageBuilder(args, use_txt2img=use_txt2img, lora_model=args.lora_model_name, lora_weight=args.lora_weight,
  File "E:\AI_Drawing\automatic1111\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\finetune_utils.py", line 521, in __init__
    if new_model_info[0] != current_model[0]:
TypeError: 'CheckpointInfo' object is not subscriptable
```

```
#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Dreambooth revision: 001836d1b482a65940a794bff5ee09f55e4487e6
SD-WebUI revision: d97f467c0d27695d23edad5e4f8898a57e0ccb00

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.14.dev0 installed.
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.

#######################################################################################################
```

**Comment by gammagoat** [comment]
The main webui changed the module for configs yesterday from a namedtuple to a class. 

https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/a95f1353089bdeaccd7c266b40cdd79efedfe632

**Comment by gammagoat** [comment]
So basically, I think the new_model_info[0] needs to be updated to new_model_info.title

**Comment by art-phony** [comment]
@gammagoat 
Thank you for useful info! I just reverted webui to previous version just before sha256 hash by `git reset --hard a407c9f0147c779865c940cbf62c7019dbc1f7b4`, generating class image function works again!

```
#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Dreambooth revision: 17c3864803ebb50615205271de687be96cfc96e8
SD-WebUI revision: a407c9f0147c779865c940cbf62c7019dbc1f7b4

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[ ] xformers version N/A installed.
[+] torch version 1.12.1+cu113 installed.
[+] torchvision version 0.13.1+cu113 installed.

#######################################################################################################
```

**Comment by Rafakes** [comment]
> @gammagoat Thank you for useful info! I just reverted webui to previous version just before sha256 hash by `git reset --hard a407c9f0147c779865c940cbf62c7019dbc1f7b4`, generating class image function works again!
> 
> ```
> #######################################################################################################
> Initializing Dreambooth
> If submitting an issue on github, please provide the below text for debugging purposes:
> 
> Python revision: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
> Dreambooth revision: 17c3864803ebb50615205271de687be96cfc96e8
> SD-WebUI revision: a407c9f0147c779865c940cbf62c7019dbc1f7b4
> 
> Checking Dreambooth requirements...
> [+] bitsandbytes version 0.35.0 installed.
> [+] diffusers version 0.10.2 installed.
> [+] transformers version 4.25.1 installed.
> [ ] xformers version N/A installed.
> [+] torch version 1.12.1+cu113 installed.
> [+] torchvision version 0.13.1+cu113 installed.
> 
> #######################################################################################################
> ```

how do I do that?

**Comment by bosbrand** [comment]
I fixed my nonetype error by dividing my datset in four, deleting each section and putting it back in if the error persisted (then I knew the error was not in that image selection), until it worked, then put my favorites out of the deleted fourth back in, still worked. So it's training and I'm happy. After searching for the error in other image sorting applications my working hypothesis was that one of my images or txt files was corrupt/wrong byte stream. Big thanks to @ExponentialML who put me on the right track.

**Comment by art-phony** [comment]
I think this problem is solved! Thank you anveo!
