### ISSUE TITLE
[macOS M1 Ultra] AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by Ozcz** [d8ahazard/sd_dreambooth_extension#775]
### Kindly read the entire form below and fill it out with the requested information.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your
issue will be automatically closed._**

`
```
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.9 (main, Dec 15 2022, 10:44:50) [Clang 14.0.0 (clang-1400.0.29.202)]
Dreambooth revision: 17c3864803ebb50615205271de687be96cfc96e8
SD-WebUI revision: 82725f0ac439f7e3b67858d55900e95330bbd326

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[ ] xformers version N/A installed.
[+] torch version 1.12.1 installed.
[+] torchvision version 0.13.1 installed.
```
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
A: YES
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
A: YES
**Have you updated Dreambooth to the latest revision?**
A: YES
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
A: YES
**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**
A: OK
**Describe the bug**

After creating a model, when i go to settings and press the Performance Wizard (WIP) I get this error: AssertionError: Torch not compiled with CUDA enabled. Additionally i'm using tensorflow-macos==2.11.0 in dreamboot requirements.txt as the dreambooth tab did not appeared unless I did this (which I saw in other issue)

**Provide logs**

```
Launching Web UI with arguments: --no-half --use-cpu interrogate
No module 'xformers'. Proceeding without it.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
SD-Webui API layer loaded
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights [81761151] from /Users/nunofeio/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt
Applying cross attention optimization (InvokeAI).
Textual inversion embeddings loaded(0): 
Model loaded in 2.9s (0.7s create model, 1.7s load weights).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Loading weights [a9263745] from /Users/nunofeio/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned.ckpt
Applying cross attention optimization (InvokeAI).
Weights loaded in 3.0s.
Traceback (most recent call last):
  File "/Users/nunofeio/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "/Users/nunofeio/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "/Users/nunofeio/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 856, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Users/nunofeio/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/nunofeio/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Users/nunofeio/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/nunofeio/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/dreambooth.py", line 199, in performance_wizard
    if torch.cuda.is_bf16_supported():
  File "/Users/nunofeio/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 93, in is_bf16_supported
    return torch.cuda.get_device_properties(torch.cuda.current_device()).major >= 8 and cuda_maj_decide
  File "/Users/nunofeio/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 482, in current_device
    _lazy_init()
  File "/Users/nunofeio/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 211, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

**Environment**

What OS?
macOS Ventura 13.1 (Apple M1 Ultra)

Thank you for your attention

**Comment by benjamin-bertram** [comment]
Same here, just macOS Monterey 12.5 (Apple M1 Max)

**Comment by Ozcz** [comment]
They don't care about mac users at the moment, if you want to use dreambooth the best you got is to train it **remotely** on a windows machine, I'd recommend you replicate or huggingface's dreambooth guide to train a .ckp model and then use that trained model on your stable diffusion gui in your macOS, for example using diffusionbee or AUTOMATIC1111 gui. Dreambooth was not trained to perform in apple machines unfortunately for us and it will take some time until we can use it locally in our machines. Good luck!
