### ISSUE TITLE
Dreambooth training fails with "Missing key(s) in state_dict: "up_blocks.0.upsamplers.0.conv.weight""

### ISSUE THREAD

**Issue by NoteToSelfFindGoodNickname** [d8ahazard/sd_dreambooth_extension#777]
### Kindly read the entire form below and fill it out with the requested information.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your
issue will be automatically closed._**

`
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: ce9827a7c51a9f69bf62c634e35d34fa75ee1833
Installing requirements for Web UI

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: 8708eb3c192fed7690176e3bd7dec1106cf3f0c2
SD-WebUI revision: ce9827a7c51a9f69bf62c634e35d34fa75ee1833

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[ ] xformers version N/A installed.
[+] torch version 1.12.1+cu113 installed.
[+] torchvision version 0.13.1+cu113 installed.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes 

**Have you updated Dreambooth to the latest revision?**
Yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**
OK
It updates automatically 

**Describe the bug**
I am trying to train a new model with uberRealisticPornMerge_urpmv12.ckpt. I have tried both safetensor and pickletensor version using this link:
https://civitai.com/models/2661/uber-realistic-porn-merge-urpm
I have also tried v11. 
I have also asked the author, but he is not experienced with training.
Using other models, the training does work.

Using this model however, I get the following error:

Checkpoint C:\Users\test\stable-diffusion-webui\models\Stable-diffusion\uberRealisticPornMerge_urpmv12.ckpt has both EMA and non-EMA weights.
In this conversion only the non-EMA weights are extracted. If you want to instead extract the EMA weights (usually better for inference), please make sure to add the `--extract_ema` flag.
Exception setting up output: Error(s) in loading state_dict for UNet2DConditionModel:
        Missing key(s) in state_dict: "up_blocks.0.upsamplers.0.conv.weight", "up_blocks.0.upsamplers.0.conv.bias", "up_blocks.1.upsamplers.0.conv.weight", "up_blocks.1.upsamplers.0.conv.bias", "up_blocks.2.upsamplers.0.conv.weight", "up_blocks.2.upsamplers.0.conv.bias".
        Unexpected key(s) in state_dict: "up_blocks.0.attentions.2.conv.bias", "up_blocks.0.attentions.2.conv.weight".
Traceback (most recent call last):
  File "C:\Users\test\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\sd_to_diff.py", line 911, in extract_checkpoint
    unet.load_state_dict(converted_unet_checkpoint)
  File "C:\Users\test\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UNet2DConditionModel:
        Missing key(s) in state_dict: "up_blocks.0.upsamplers.0.conv.weight", "up_blocks.0.upsamplers.0.conv.bias", "up_blocks.1.upsamplers.0.conv.weight", "up_blocks.1.upsamplers.0.conv.bias", "up_blocks.2.upsamplers.0.conv.weight", "up_blocks.2.upsamplers.0.conv.bias".
        Unexpected key(s) in state_dict: "up_blocks.0.attentions.2.conv.bias", "up_blocks.0.attentions.2.conv.weight".
Pipeline or config is not set, unable to continue.
Saved settings.
Invalid model name.

I have also downloaded a yaml file and used it alongside with vae-ft-mse-84000000-ema-pruned.ckpt, but webui wouldn't start, so I removed it again.

(A clear and concise description of what the bug is)
I expect the training to start, but it does not and throws the error that I stated above.

**Provide logs**

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *
before* the crash occurred.

**Environment**
Windows 11
What OS?

If Windows - WSL or native?
Native 

What GPU are you using?
3090

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the
db_config.json file from /models/dreambooth/MODELNAME/db_config.json

{
    "attention": "default",
    "cache_latents": true,
    "center_crop": true,
    "clip_skip": 1,
    "concepts_path": "",
    "custom_model_name": "",
    "epoch": 0,
    "epoch_pause_frequency": 0,
    "epoch_pause_time": 0,
    "gradient_accumulation_steps": 1,
    "gradient_checkpointing": true,
    "gradient_set_to_none": true,
    "graph_smoothing": 50,
    "half_model": false,
    "hflip": false,
    "learning_rate": 5e-06,
    "learning_rate_min": 1e-06,
    "lora_learning_rate": 0.0001,
    "lora_model_name": "",
    "lora_txt_learning_rate": 5e-05,
    "lora_txt_weight": 1.0,
    "lora_weight": 1.0,
    "lr_cycles": 1,
    "lr_factor": 0.5,
    "lr_power": 1.0,
    "lr_scale_pos": 0.5,
    "lr_scheduler": "constant",
    "lr_warmup_steps": 0,
    "max_token_length": 75,
    "mixed_precision": "fp16",
    "model_dir": "C:\\Users\\test\\stable-diffusion-webui\\models\\dreambooth\\dp1",
    "model_name": "dp1",
    "num_train_epochs": 100,
    "pad_tokens": true,
    "pretrained_model_name_or_path": "C:\\Users\\test\\stable-diffusion-webui\\models\\dreambooth\\dp1\\working",
    "pretrained_vae_name_or_path": "",
    "prior_loss_weight": 1.0,
    "resolution": 512,
    "revision": 0,
    "sample_batch_size": 1,
    "sanity_prompt": "",
    "sanity_seed": 420420,
    "save_ckpt_after": true,
    "save_ckpt_cancel": false,
    "save_ckpt_during": true,
    "save_embedding_every": 25,
    "save_lora_after": true,
    "save_lora_cancel": false,
    "save_lora_during": true,
    "save_preview_every": 5,
    "save_state_after": false,
    "save_state_cancel": false,
    "save_state_during": false,
    "src": "C:\\Users\\test\\stable-diffusion-webui\\models\\Stable-diffusion\\uberRealisticPornMerge_urpmv12.ckpt",
    "shuffle_tags": false,
    "train_batch_size": 1,
    "stop_text_encoder": 0,
    "use_8bit_adam": true,
    "use_concepts": false,
    "use_ema": true,
    "use_lora": false,
    "use_subdir": false,
    "scheduler": "ddim",
    "v2": false,
    "has_ema": true,
    "concepts_list": [],
    "lifetime_revision": 0
}

**Comment by alexxxzy** [comment]
I have this error too. However, it's noted that this only happens to _some_ models

**Comment by NoteToSelfFindGoodNickname** [comment]
> I have this error too. However, it's noted that this only happens to _some_ models

Confirmed, but I'd need a fix anyways.

**Comment by DJCool1** [comment]
Yeah I keep getting this error with most of my models too

**Comment by cschwarzhw** [comment]
Same error also (plus lots more) - someone fucked with Dreambooth about a week ago and it's been next to useless ever since

**Comment by jsbach-jung** [comment]
Try my workaround and see if it fixes it for you.
https://github.com/d8ahazard/sd_dreambooth_extension/discussions/794
