### ISSUE TITLE
Could not install packages due to an OSError: [WinError 5] Access is denied.. when clicking Install extension via Webui (fresh install)

### ISSUE THREAD

**Issue by zencyon** [d8ahazard/sd_dreambooth_extension#813]
### Kindly read the entire form below and fill it out with the requested information.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your
issue will be automatically closed._**

`
Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Commit hash: ****************************************
Installing requirements for Web UI
Skipping dreambooth installation.
Dreambooth revision is ****************************************
Diffusers version is *.*.*.
Torch version is *.*.*.
Torch vision version is *.*.*.
`
Python revision: 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
Dreambooth revision: c2269b8585d994efa31c6582fc19a890253c804e
SD-WebUI revision: fe7a623e6b7e04bab2cfc96e8fd6cf49b48daee1

the versions are whichever is installed by a fresh clone of webui

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes (but this shouldn't matter relating to this issue)

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Error happens upon clicking Install on the extension, fresh install and boot of webui

**Have you updated Dreambooth to the latest revision?**
installing via webui extension, assume it pull the latest

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**
OK

**Describe the bug**

(A clear and concise description of what the bug is)

I did fresh install (clone) of auto1111 Webui, went to extensions tab, found Dreambooth extension, clicked install
errors showed in console:
...
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'A:\\AI\\stable-diffusion-webui-training\\venv\\Lib\\site-packages\\cv2\\cv2.pyd'
Check the permissions.

(see bug log)

after it failed, i tried shutting it down, went to web extension folder, deleted the extension, tried again, same error.

if i run webui again after shutting down and not deleting, it will appear the dreambooth extension is installed (getting the startup log outputs and it starts to download files i'm guessing (startup is a lot longer) and it posts: 

Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
Dreambooth revision: c2269b8585d994efa31c6582fc19a890253c804e
SD-WebUI revision: fe7a623e6b7e04bab2cfc96e8fd6cf49b48daee1

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.14.dev0 installed.
[+] torch version 1.12.1+cu113 installed.
[+] torchvision version 0.13.1+cu113 installed.

#######################################################################################################

Launching Web UI with arguments: --xformers
SD-Webui API layer loaded
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights [cc6cb27103] from A:\AI\stable-diffusion-webui-training\models\Stable-diffusion\v1-5-pruned-emaonly.ckpt
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0):
Model loaded in 4.6s (0.4s create model, 2.9s load weights).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

I don't know why the log access error occurs, but it looks bad and not sure whether things are correctly installed or not?

expected behavior: 
no errors in console when clicking Install on the extension on clean clone of webui

**Provide logs**

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *
before* the crash occurred.

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
Dreambooth revision: c2269b8585d994efa31c6582fc19a890253c804e
SD-WebUI revision: fe7a623e6b7e04bab2cfc96e8fd6cf49b48daee1

Checking Dreambooth requirements...

stderr: Traceback (most recent call last):
  File "A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\install.py", line 90, in <module>
    run(f'"{sys.executable}" -m pip install -r "{req_file}"', f"Checking {name} requirements...",
  File "A:\AI\stable-diffusion-webui-training\launch.py", line 65, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install Dreambooth requirements..
Command: "A:\AI\stable-diffusion-webui-training\venv\Scripts\python.exe" -m pip install -r "A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt"
Error code: 1
stdout: Collecting accelerate==0.15.0
  Using cached accelerate-0.15.0-py3-none-any.whl (191 kB)
Collecting albumentations==1.3.0
  Using cached albumentations-1.3.0-py3-none-any.whl (123 kB)
Requirement already satisfied: bitsandbytes==0.35.0 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from -r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 3)) (0.35.0)
Collecting diffusers==0.10.2
  Using cached diffusers-0.10.2-py3-none-any.whl (503 kB)
Collecting fastapi==0.87.0
  Using cached fastapi-0.87.0-py3-none-any.whl (55 kB)
Requirement already satisfied: ftfy==6.1.1 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from -r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 6)) (6.1.1)
Collecting modelcards==0.1.6
  Using cached modelcards-0.1.6-py3-none-any.whl (12 kB)
Collecting tensorboard==2.11.0
  Using cached tensorboard-2.11.0-py3-none-any.whl (6.0 MB)
Collecting tensorflow==2.11.0
  Using cached tensorflow-2.11.0-cp310-cp310-win_amd64.whl (1.9 kB)
Requirement already satisfied: tqdm==4.64.1 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from -r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (4.64.1)
Collecting transformers==4.25.1
  Using cached transformers-4.25.1-py3-none-any.whl (5.8 MB)
Collecting discord-webhook==1.0.0
  Using cached discord_webhook-1.0.0-py3-none-any.whl (12 kB)
Requirement already satisfied: torch>=1.4.0 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from accelerate==0.15.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (1.12.1+cu113)
Requirement already satisfied: pyyaml in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from accelerate==0.15.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (6.0)
Requirement already satisfied: packaging>=20.0 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from accelerate==0.15.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (23.0)
Requirement already satisfied: psutil in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from accelerate==0.15.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (5.9.4)
Requirement already satisfied: numpy>=1.17 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from accelerate==0.15.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (1.23.3)
Collecting opencv-python-headless>=4.1.1
  Using cached opencv_python_headless-4.7.0.68-cp37-abi3-win_amd64.whl (38.1 MB)
Requirement already satisfied: scikit-image>=0.16.1 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from albumentations==1.3.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (0.19.2)
Collecting qudida>=0.0.4
  Using cached qudida-0.0.4-py3-none-any.whl (3.5 kB)
Requirement already satisfied: scipy in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from albumentations==1.3.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (1.10.0)
Requirement already satisfied: requests in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from diffusers==0.10.2->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (2.25.1)
Requirement already satisfied: regex!=2019.12.17 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from diffusers==0.10.2->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (2022.10.31)
Requirement already satisfied: huggingface-hub>=0.10.0 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from diffusers==0.10.2->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (0.11.1)
Collecting importlib-metadata
  Using cached importlib_metadata-6.0.0-py3-none-any.whl (21 kB)
Requirement already satisfied: Pillow in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from diffusers==0.10.2->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (9.4.0)
Requirement already satisfied: filelock in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from diffusers==0.10.2->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (3.9.0)
Requirement already satisfied: pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from fastapi==0.87.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 5)) (1.10.4)
Collecting starlette==0.21.0
  Using cached starlette-0.21.0-py3-none-any.whl (64 kB)
Requirement already satisfied: wcwidth>=0.2.5 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from ftfy==6.1.1->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 6)) (0.2.6)
Requirement already satisfied: Jinja2 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from modelcards==0.1.6->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 7)) (3.1.2)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from tensorboard==2.11.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (0.4.6)
Requirement already satisfied: markdown>=2.6.8 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from tensorboard==2.11.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (3.4.1)
Requirement already satisfied: absl-py>=0.4 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from tensorboard==2.11.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (1.4.0)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from tensorboard==2.11.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (0.6.1)
Requirement already satisfied: wheel>=0.26 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from tensorboard==2.11.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (0.38.4)
Requirement already satisfied: google-auth<3,>=1.6.3 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from tensorboard==2.11.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (2.16.0)
Requirement already satisfied: setuptools>=41.0.0 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from tensorboard==2.11.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (63.2.0)
Requirement already satisfied: protobuf<4,>=3.9.2 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from tensorboard==2.11.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (3.19.6)
Requirement already satisfied: grpcio>=1.24.3 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from tensorboard==2.11.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (1.51.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from tensorboard==2.11.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (1.8.1)
Requirement already satisfied: werkzeug>=1.0.1 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from tensorboard==2.11.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (2.2.2)
Collecting tensorflow-intel==2.11.0
  Using cached tensorflow_intel-2.11.0-cp310-cp310-win_amd64.whl (266.3 MB)
Requirement already satisfied: colorama in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from tqdm==4.64.1->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (0.4.6)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from transformers==4.25.1->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 11)) (0.12.1)
Collecting requests
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Requirement already satisfied: anyio<5,>=3.4.0 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from starlette==0.21.0->fastapi==0.87.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 5)) (3.6.2)
Requirement already satisfied: opt-einsum>=2.3.2 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (3.3.0)
Requirement already satisfied: six>=1.12.0 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (1.16.0)
Collecting gast<=0.4.0,>=0.2.1
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
Requirement already satisfied: flatbuffers>=2.0 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (23.1.20)
Requirement already satisfied: libclang>=13.0.0 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (15.0.6.1)
Requirement already satisfied: typing-extensions>=3.6.6 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (4.4.0)
Collecting google-pasta>=0.1.1
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (0.30.0)
Collecting astunparse>=1.6.0
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: termcolor>=1.1.0 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (2.2.0)
Requirement already satisfied: tensorflow-estimator<2.12,>=2.11.0 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (2.11.0)
Collecting h5py>=2.9.0
  Using cached h5py-3.7.0-cp310-cp310-win_amd64.whl (2.6 MB)
Collecting keras<2.12,>=2.11.0
  Using cached keras-2.11.0-py2.py3-none-any.whl (1.7 MB)
Requirement already satisfied: wrapt>=1.11.0 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (1.14.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard==2.11.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (0.2.8)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard==2.11.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (5.2.1)
Requirement already satisfied: rsa<5,>=3.1.4 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard==2.11.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard==2.11.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (1.3.1)
Collecting scikit-learn>=0.19.1
  Using cached scikit_learn-1.2.0-cp310-cp310-win_amd64.whl (8.2 MB)
Requirement already satisfied: charset-normalizer<4,>=2 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from requests->diffusers==0.10.2->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from requests->diffusers==0.10.2->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from requests->diffusers==0.10.2->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from requests->diffusers==0.10.2->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (2022.12.7)
Requirement already satisfied: imageio>=2.4.1 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from scikit-image>=0.16.1->albumentations==1.3.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (2.24.0)
Requirement already satisfied: tifffile>=2019.7.26 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from scikit-image>=0.16.1->albumentations==1.3.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (2022.10.10)
Requirement already satisfied: networkx>=2.2 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from scikit-image>=0.16.1->albumentations==1.3.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (3.0)
Requirement already satisfied: PyWavelets>=1.1.1 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from scikit-image>=0.16.1->albumentations==1.3.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (1.4.1)
Requirement already satisfied: MarkupSafe>=2.1.1 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from werkzeug>=1.0.1->tensorboard==2.11.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (2.1.2)
Requirement already satisfied: zipp>=0.5 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from importlib-metadata->diffusers==0.10.2->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (3.11.0)
Requirement already satisfied: sniffio>=1.1 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from anyio<5,>=3.4.0->starlette==0.21.0->fastapi==0.87.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 5)) (1.3.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard==2.11.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard==2.11.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (3.2.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in a:\ai\stable-diffusion-webui-training\venv\lib\site-packages (from scikit-learn>=0.19.1->qudida>=0.0.4->albumentations==1.3.0->-r A:\AI\stable-diffusion-webui-training\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (3.1.0)
Collecting joblib>=1.1.1
  Using cached joblib-1.2.0-py3-none-any.whl (297 kB)
Installing collected packages: requests, opencv-python-headless, keras, joblib, importlib-metadata, h5py, google-pasta, gast, astunparse, starlette, scikit-learn, discord-webhook, accelerate, transformers, qudida, modelcards, fastapi, diffusers, tensorboard, albumentations, tensorflow-intel, tensorflow
  Attempting uninstall: requests
    Found existing installation: requests 2.25.1
    Uninstalling requests-2.25.1:
      Successfully uninstalled requests-2.25.1

stderr: WARNING: Ignoring invalid distribution -rotobuf (a:\ai\stable-diffusion-webui-training\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (a:\ai\stable-diffusion-webui-training\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (a:\ai\stable-diffusion-webui-training\venv\lib\site-packages)
    WARNING: Ignoring invalid distribution -rotobuf (a:\ai\stable-diffusion-webui-training\venv\lib\site-packages)
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'A:\\AI\\stable-diffusion-webui-training\\venv\\Lib\\site-packages\\cv2\\cv2.pyd'
Check the permissions.

WARNING: Ignoring invalid distribution -rotobuf (a:\ai\stable-diffusion-webui-training\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (a:\ai\stable-diffusion-webui-training\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (a:\ai\stable-diffusion-webui-training\venv\lib\site-packages)

[notice] A new release of pip available: 22.2.2 -> 22.3.1
[notice] To update, run: A:\AI\stable-diffusion-webui-training\venv\Scripts\python.exe -m pip install --upgrade pip

**Environment**

What OS?
Windows 10

If Windows - WSL or native?
native

What GPU are you using?
Nvidia RTX 4090

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the
db_config.json file from /models/dreambooth/MODELNAME/db_config.json

![image](https://user-images.githubusercontent.com/43258551/213887143-bc5dfc0e-ed05-4750-9e7e-362d3a045e6e.png)

**Comment by d8ahazard** [comment]
Close the stable-diffusion webUI entirely and re-start.

**Comment by zencyon** [comment]
as mentioned in the report:

if i run webui again after shutting down and not deleting, it will appear the dreambooth extension is installed (getting the startup log outputs and it starts to download files i'm guessing

the initial installation still shows errors, that is what this report was for, not that 'it doesn't work' 
it doesn't look great and people become unsure if things really work when console reports errors

What's causing this to say it fails to overwrite? why/what is it trying to overwrite? can it be hidden if it's not important?

stderr: ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'A:\\AI\\stable-diffusion-webui-training\\venv\\Lib\\site-packages\\google\\~rotobuf\\internal\\_api_implementation.cp310-win_amd64.pyd'
Check the permissions.

It's still happens even with the new update, just tested clean venv + extension install

cool job on the new update btw! wonderful <3

**Comment by glorydanking** [comment]
I got this problem too.
Anybody has solved this ?

**Comment by allroundHim** [comment]
> as mentioned in the report:
> 
> if i run webui again after shutting down and not deleting, it will appear the dreambooth extension is installed (getting the startup log outputs and it starts to download files i'm guessing
> 
> the initial installation still shows errors, that is what this report was for, not that 'it doesn't work' it doesn't look great and people become unsure if things really work when console reports errors
> 
> What's causing this to say it fails to overwrite? why/what is it trying to overwrite? can it be hidden if it's not important?
> 
> stderr: ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'A:\AI\stable-diffusion-webui-training\venv\Lib\site-packages\google\~rotobuf\internal\_api_implementation.cp310-win_amd64.pyd' Check the permissions.
> 
> It's still happens even with the new update, just tested clean venv + extension install
> 
> cool job on the new update btw! wonderful <3

Me to, still got this
```
stderr: ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'A:\AI\stable-diffusion-webui-training\venv\Lib\site-packages\google\~rotobuf\internal\_api_implementation.cp310-win_amd64.pyd'
Check the permissions.
```

**Comment by glorydanking** [comment]
感谢你的来信，我会尽快回复给您，祝生活愉快，工作顺利~
