### ISSUE TITLE
Cannot create new model after update of extension

### ISSUE THREAD

**Issue by sebaxakerhtc** [d8ahazard/sd_dreambooth_extension#819]
### Kindly read the entire form below and fill it out with the requested information.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your
issue will be automatically closed._**

`
Python revision: 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
Dreambooth revision: fd51c0b2ed20566c60affa853a32ebce1b0a1139
SD-WebUI revision: c98cb0f8ecc904666f47684e238dd022039ca16f

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.14.dev0 installed.
[+] torch version 1.12.1+cu113 installed.
[+] torchvision version 0.13.1+cu113 installed.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes
**Have you updated Dreambooth to the latest revision?**
Yes. From this point the issue was detected.
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes
**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**
OK
**Describe the bug**

(A clear and concise description of what the bug is)
When i try to create a new model there's red text "error" on all lines on WebUI

**Provide logs**

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *
before* the crash occurred.
The terminal output:
```
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1013, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 911, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
IndexError: list index out of range
```
**Environment**

What OS?
Windows
If Windows - WSL or native?
Native
What GPU are you using?
Nvidia Quadro RTX A4000
**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the
db_config.json file from /models/dreambooth/MODELNAME/db_config.json

**Comment by sebaxakerhtc** [comment]
I think the problem is in the new "resolution" checkbox, because after error i go to settings tab and see this
![1](https://user-images.githubusercontent.com/32651506/213926049-0ae07398-3800-4f3f-90d7-bb93ef7517c9.png)

**Comment by HanJammer** [comment]
Same here.

Various combinations of the previous sd_dreambooth_extensions seem to allow the model creation OR training but never the both. Also this issue https://github.com/d8ahazard/sd_dreambooth_extension/issues/660 popups as well...

So the extension currently is pretty much unusable.

**Comment by sebaxakerhtc** [comment]
> model creation OR training but never the both

For me temporary solution was to `git reset --hard f5ae5ee36864fe4ab386ac2f38039d2eef17611d`
Training finished, so i can wait for "issue is solved"

**Comment by sebaxakerhtc** [comment]
Updated to e693070d62885313e67cb49dabe4fa5a510b36a6
The issue still persists

**Comment by caretaker0815** [comment]
Same here. Cannot create model.

**Comment by d8ahazard** [comment]
Sigh...

Reload the web page.

**Comment by HanJammer** [comment]
> Sigh...
> 
> Reload the web page.

Reloading the webpage does absolutely nothing. Why do you close the unresolved issues?

[stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui) c98cb0f8ecc904666f47684e238dd022039ca16f
and latest [d8ahazard](https://github.com/d8ahazard)
/
[sd_dreambooth_extension](https://github.com/d8ahazard/sd_dreambooth_extension) (updated through the extension tab).

**Comment by sebaxakerhtc** [comment]
> Sigh...
> 
> Reload the web page.

If you read carefuly - i have done all the steps before creating the issue. BUT!
When you wrote your absolutely useless answer i installed another browser (f*kin Google Chrome) and it works, but not Firefox!
So... Please, reopen the issue and try to solve it.

**Comment by d8ahazard** [comment]
> > Sigh...
> > Reload the web page.
> 
> If you read carefuly - i have done all the steps before creating the issue. BUT! When you wrote your absolutely useless answer i installed another browser (f*kin Google Chrome) and it works, but not Firefox! So... Please, reopen the issue and try to solve it.

Read this carefully.

If you installed another fucking browser and it works, then the issue is clearly not with the code.

You wanna bitch at somebody about "fixing" the issue, go bitch at Auto1111 for the way his extension system works. I didn't make it so that requirements don't get fully installed when "installing" things, I don't randomly decide to update requirements and change base methods in the web app without warning anybody, and I certainly didn't make it so that you have to press CONTROL AND F5 to force the web cache to reload.

Because if you're getting a "List index out of range' error, it means YOU NEED TO REFRESH THE FUCKING WEB PAGE.

So, no, I will not re-open this, because there is nothing to solve.

"Useless answer". Seriously dude, I have better shit to do than babysit people with a tenuous grasp of basic computing.

**Comment by sebaxakerhtc** [comment]
> I will not re-open this, because there is nothing to solve

Ok, nice guy! If you cannot resolve this - just edit readme for people to know that your perfect code will work in Google Chrome only

**Comment by d8ahazard** [comment]
Have a fabulous day.

**Comment by HanJammer** [comment]
> > Sigh...
> > Reload the web page.
> 
> If you read carefuly - i have done all the steps before creating the issue. BUT! When you wrote your absolutely useless answer i installed another browser (f*kin Google Chrome) and it works, but not Firefox! So... Please, reopen the issue and try to solve it.

I can confirm that in a freshly installed Google Chrome it works... but it doesn't work in Brave I normally use, and this is a Chromium based browser...

> If you installed another fucking browser and it works, then the issue is clearly not with the code.

Wrong. I was a web developer for several years and if I would ever use such argument in the discussions with my clients or team they would laugh at me...

Seriously man, you may want to take a chill pill, why do you take a simple issue ticket as an attack on yourself? Nobody is your enemy here, we appreciate all your work on this extension and we are trying to help so you can make it better. But such behavior on your part doesn't help anybody.

Also @AUTOMATIC1111 please look at this:
> You wanna bitch at somebody about "fixing" the issue, go bitch at Auto1111 for the way his extension system works. I didn't make it so that requirements don't get fully installed when "installing" things, I don't randomly decide to update requirements and change base methods in the web app without warning anybody, and I certainly didn't make it so that you have to press CONTROL AND F5 to force the web cache to reload.

Maybe there is some way you can make it work better.
