### ISSUE TITLE
No Tensorflow installed, but yes

### ISSUE THREAD

**Issue by mykeehu** [d8ahazard/sd_dreambooth_extension#821]
`
Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: e693070d62885313e67cb49dabe4fa5a510b36a6
SD-WebUI revision: c98cb0f8ecc904666f47684e238dd022039ca16f

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.14.dev0 installed.
[+] torch version 1.12.1+cu116 installed.
[+] torchvision version 0.13.1+cu116 installed.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes

**Have you updated Dreambooth to the latest revision?**
Yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**
OK

**Describe the bug**
I just installed the DB from scratch, and it complains about lack of tensorflow under windows... So it's not just for mac, it seems. I deleted the condition in requirements.txt, but it still didn't install...

```
Launching Web UI with arguments: --xformers --ckpt-dir V:\!SDModels --ui-config-file 1my/ui-config-my.json --ui-settings-file 1my/config-my.json --autolaunch --gradio-img2img-tool color-sketch
Error loading script: api.py
Traceback (most recent call last):
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\modules\scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\api.py", line 20, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.db_config import from_file, DreamboothConfig
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\db_config.py", line 9, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.db_concept import Concept
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\db_concept.py", line 7, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.utils import get_images
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\utils.py", line 23, in <module>
    import tensorflow
ModuleNotFoundError: No module named 'tensorflow'

Error loading script: dreambooth.py
Traceback (most recent call last):
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\modules\scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\dreambooth.py", line 15, in <module>
    from extensions.sd_dreambooth_extension.dreambooth import db_config
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\db_config.py", line 9, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.db_concept import Concept
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\db_concept.py", line 7, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.utils import get_images
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\utils.py", line 23, in <module>
    import tensorflow
ModuleNotFoundError: No module named 'tensorflow'

Error loading script: main.py
Traceback (most recent call last):
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\modules\scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py", line 6, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.db_config import save_config, from_file
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\db_config.py", line 9, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.db_concept import Concept
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\db_concept.py", line 7, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.utils import get_images
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\utils.py", line 23, in <module>
    import tensorflow
ModuleNotFoundError: No module named 'tensorflow'
```

I got this for the pip installation:

```
(venv) H:\Stable-Diffusion-Automatic\stable-diffusion-webui>pip install tensorflow==2.11.0
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: tensorflow==2.11.0 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (2.11.0)
Requirement already satisfied: tensorflow-intel==2.11.0 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from tensorflow==2.11.0) (2.11.0)
Requirement already satisfied: termcolor>=1.1.0 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0) (2.2.0)
Requirement already satisfied: wrapt>=1.11.0 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0) (1.14.1)
Requirement already satisfied: protobuf<3.20,>=3.9.2 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0) (3.19.6)
Requirement already satisfied: typing-extensions>=3.6.6 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0) (4.4.0)
Requirement already satisfied: packaging in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0) (23.0)
Requirement already satisfied: h5py>=2.9.0 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0) (3.7.0)
Requirement already satisfied: absl-py>=1.0.0 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0) (1.4.0)
Requirement already satisfied: keras<2.12,>=2.11.0 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0) (2.11.0)
Requirement already satisfied: astunparse>=1.6.0 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0) (1.6.3)
Requirement already satisfied: six>=1.12.0 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0) (1.16.0)
Requirement already satisfied: tensorboard<2.12,>=2.11 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0) (2.11.0)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0) (0.29.0)
Requirement already satisfied: numpy>=1.20 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0) (1.23.3)
Requirement already satisfied: google-pasta>=0.1.1 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0) (0.2.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0) (1.51.1)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0) (0.4.0)
Requirement already satisfied: tensorflow-estimator<2.12,>=2.11.0 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0) (2.11.0)
Requirement already satisfied: setuptools in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0) (63.2.0)
Requirement already satisfied: opt-einsum>=2.3.2 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0) (3.3.0)
Requirement already satisfied: libclang>=13.0.0 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0) (15.0.6.1)
Requirement already satisfied: flatbuffers>=2.0 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0) (23.1.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.11.0->tensorflow==2.11.0) (0.38.4)
Requirement already satisfied: markdown>=2.6.8 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow==2.11.0) (3.4.1)
Requirement already satisfied: requests<3,>=2.21.0 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow==2.11.0) (2.28.2)
Requirement already satisfied: google-auth<3,>=1.6.3 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow==2.11.0) (2.16.0)
Requirement already satisfied: werkzeug>=1.0.1 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow==2.11.0) (2.2.2)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow==2.11.0) (0.4.6)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow==2.11.0) (0.6.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow==2.11.0) (1.8.1)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow==2.11.0) (5.2.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow==2.11.0) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow==2.11.0) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow==2.11.0) (1.3.1)
Requirement already satisfied: idna<4,>=2.5 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow==2.11.0) (2.10)
Requirement already satisfied: charset-normalizer<4,>=2 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow==2.11.0) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow==2.11.0) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow==2.11.0) (1.26.14)
Requirement already satisfied: MarkupSafe>=2.1.1 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from werkzeug>=1.0.1->tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow==2.11.0) (2.1.1)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow==2.11.0) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in h:\stable-diffusion-automatic\stable-diffusion-webui\venv\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow==2.11.0) (3.2.2)
```

**Environment**

What OS? Windows

If Windows - WSL or native? Native

What GPU are you using? RTX 3060 12 GB

**Comment by mykeehu** [comment]
Here's the solution for those who get this error: 
- go to stable-diffusion-webui\venv\Lib\site-packages 
- delete all tensorflow folders 
- start webUI again
