### ISSUE TITLE
Training fails to start just after preparing buckets, error is: "expected Tensor as element 0 in argument 0, but got NoneType"

### ISSUE THREAD

**Issue by raymondgp** [d8ahazard/sd_dreambooth_extension#823]
### Kindly read the entire form below and fill it out with the requested information.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your
issue will be automatically closed._**

`
Python revision: 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]                        
Dreambooth revision: e693070d62885313e67cb49dabe4fa5a510b36a6                                                            
SD-WebUI revision: c98cb0f8ecc904666f47684e238dd022039ca16f                                                                                                                                                                                       [+] bitsandbytes version 0.35.0 installed.                                                                               
[+] diffusers version 0.10.2 installed.                                                                                  
[+] transformers version 4.25.1 installed.                                                                               
[+] xformers version 0.0.14.dev0 installed.                                                                              
[+] torch version 1.12.1+cu116 installed.                                                                                
[+] torchvision version 0.13.1+cu116 installed.                                                                                                                             `

"Checking for accelerate"
"Accelerating"
[15:40:25] WARNING  The following values were not passed to `accelerate launch` and had defaults used     launch.py:1088
                    instead:
                            `--num_processes` was set to a value of `1`
                            `--num_machines` was set to a value of `1`
                            `--mixed_precision` was set to a value of `'no'`
                            `--dynamo_backend` was set to a value of `'no'`
                    To avoid this warning pass in values for each of the problematic parameters or run
                    `accelerate config`.

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yes

**Have you updated Dreambooth to the latest revision?**
yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**

**Describe the bug**

Launching training for SD1.5 moidel will fail with error  "expected Tensor as element 0 in argument 0, but got NoneType". 

The error comes after finishing image prep/buckets prep. Tried with latent caching, without it, same difference. 

**Provide logs**

Found 1120 reg images.
Preparing dataset...
Init dataset!
Preparing Dataset (With Caching)
Bucket 0 (512, 512, 0) - Instance Images:  56 | Class Images:  280 | Max Examples/batch:  112
Bucket 1 (512, 512, 1) - Instance Images:  56 | Class Images:  280 | Max Examples/batch:  112
Bucket 2 (512, 512, 2) - Instance Images:  56 | Class Images:  280 | Max Examples/batch:  112
Bucket 3 (512, 512, 3) - Instance Images:  56 | Class Images:  280 | Max Examples/batch:  112
Total Buckets 4 - Instance Images: 224 | Class Images: 1120 | Max Examples/batch:  448
Caching latents...: 100%|███████████████████████████████████████████████████████████| 1344/1344 [01:54<00:00, 15.90it/s]
Total images / batch: 448, total examples: 448
Caching latents...: 100%|███████████████████████████████████████████████████████████| 1344/1344 [01:54<00:00, 11.74it/s]
Total dataset length (steps): 448
Initializing bucket counter!
  ***** Running training *****
  Num batches each epoch = 448
  Num Epochs = 150
  Batch Size Per Device = 1
  Gradient Accumulation steps = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Text Encoder Epochs: 150
  Total optimization steps = 33600
  Total training steps = 67200
  Resuming from checkpoint: False
  First resume epoch: 0
  First resume step: 0
  Lora: False, Adam: True, Prec: fp16
  Gradient Checkpointing: True
  EMA: False
  UNET: True
  LR: 7e-07
  V2: False
Steps:   0%|                                                                                  | 0/67200 [00:00<?, ?it/s]Traceback (most recent call last):
  File "D:\AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\dreambooth.py", line 455, in start_training
    result = main(config, use_txt2img=use_txt2img)
  File "D:\AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 984, in main
    return inner_loop()
  File "D:\AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 121, in decorator
    return function(batch_size, grad_size, prof, log_file, *args, **kwargs)
  File "D:\AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 825, in inner_loop
    for step, batch in enumerate(train_dataloader):
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\accelerate\data_loader.py", line 383, in __iter__
    next_batch = next(dataloader_iter)
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\dataloader.py", line 681, in __next__
    data = self._next_data()
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "D:\AI\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 400, in collate_fn
    pixel_values = torch.stack(pixel_values)
TypeError: expected Tensor as element 0 in argument 0, but got NoneType
Steps:   0%|                                                                                  | 0/67200 [00:00<?, ?it/s]
Restored system models.
**Environment**

What OS?
Windows 10 Native

What GPU are you using?
RTX 3060 12:GB

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the
db_config.json file from /models/dreambooth/MODELNAME/db_config.json

{
    "attention": "xformers",
    "cache_latents": true,
    "center_crop": false,
    "clip_skip": 1,
    "concepts_path": "D:\\TrainingSources\\everydream\\concepts_list.json",
    "custom_model_name": "",
    "epoch": 0,
    "epoch_pause_frequency": 0.0,
    "epoch_pause_time": 60.0,
    "gradient_accumulation_steps": 1,
    "gradient_checkpointing": true,
    "gradient_set_to_none": true,
    "graph_smoothing": 50.0,
    "half_model": false,
    "hflip": false,
    "learning_rate": 4e-06,
    "learning_rate_min": 1e-06,
    "lora_learning_rate": 0.0002,
    "lora_model_name": "",
    "lora_txt_learning_rate": 0.0002,
    "lora_txt_weight": 1,
    "lora_weight": 1,
    "lr_cycles": 1,
    "lr_factor": 1,
    "lr_power": 1,
    "lr_scale_pos": 0,
    "lr_scheduler": "constant",
    "lr_warmup_steps": 0,
    "max_token_length": 150,
    "mixed_precision": "fp16",
    "model_dir": "D:\\AI\\stable-diffusion-webui\\models\\dreambooth\\",
    "model_name": "",
    "num_train_epochs": 100,
    "pad_tokens": true,
    "pretrained_model_name_or_path": "D:\\AI\\stable-diffusion-webui\\models\\dreambooth\\working",
    "pretrained_vae_name_or_path": "",
    "prior_loss_weight": 1,
    "resolution": 512,
    "revision": 0,
    "sample_batch_size": 1,
    "sanity_prompt": "",
    "sanity_seed": 420420.0,
    "save_ckpt_after": true,
    "save_ckpt_cancel": false,
    "save_ckpt_during": false,
    "save_embedding_every": 25,
    "save_lora_after": true,
    "save_lora_cancel": false,
    "save_lora_during": false,
    "save_preview_every": 0,
    "save_state_after": false,
    "save_state_cancel": false,
    "save_state_during": false,
    "src": "",
    "shuffle_tags": false,
    "train_batch_size": 1,
    "train_imagic": false,
    "stop_text_encoder": 1,
    "use_8bit_adam": true,
    "use_concepts": false,
    "use_ema": true,
    "use_lora": false,
    "use_subdir": true,
    "scheduler": "",
    "v2": "",
    "has_ema": "",
    "concepts_list": [],
    "lifetime_revision": 0
}

**Comment by karolisr** [comment]
Same issue.

**Comment by raymondgp** [comment]
Odd, didn't make a difference for me. I created 4 separate class folders for each of my 4 concepts but I get the same error.  To add to the oddity the error sometimes happens before the first step, but sometimes a few steps in, up to 8 steps in one case. 

The trace does point to training_dreambooth.py at line 400 so this is the function at fault

        def collate_fn(examples):
            input_ids = [example["input_id"] for example in examples]
            pixel_values = [example["image"] for example in examples]
            loss_weights = torch.tensor([example["loss_weight"] for example in examples], dtype=torch.float32)

            pixel_values = torch.stack(pixel_values)
            if not args.cache_latents:
                pixel_values = pixel_values.to(memory_format=torch.contiguous_format).float()
            input_ids = torch.cat(input_ids, dim=0)

            batch_data = {
                "input_ids": input_ids,
                "images": pixel_values,
                "loss_weights": loss_weights.mean()
            }
            return batch_data

**Comment by BigBlueGX** [comment]
I had the same issue happen to me after training multiple times successfully with the same dreambooth version.
The only thing different was that I was watching a youtube video while doing the training.

I restarted the pc and only used it for dreambooth training. The error did not appear and I trained successfully.

**Comment by raymondgp** [comment]
Thank you for the suggestion but a restart didn't do the trick. Still same error message.  I keep having this trouble with concept list, I'll try by filling the concepts individually. I'll report back.

**Comment by karolisr** [comment]
Try this weird thing until the official solution comes:

1. Clean start the web UI.
2. Pick the DB model from the list.
3. Click load config.
4. Click save config.
5. Go to the DreamBooth model folder and open `db_config.json` in text editor.
6. Remove all `"num_class_images": 0,` lines from all concepts.
7. Click train. Make sure to NOT load the config file.

This may be a weird set of steps that have no real connection to the problem, but it appeared to work for me in me testing yesterday.

**Comment by tsngo** [comment]
I created a pull request to address this. Initial testing eliminates this error with both cached and uncached latents. Also, training seems to produce the desire results. I believe this happens due to the caching of captions (input ids) for classification images. If an classification image is picked from one used previously, then the cache value was getting set to None. This accounts for the randomness of when the error occurs since training only crashes when encountering a previously cached image.

**Comment by skunk-ink** [comment]
Hi, I just started getting this exact same error. It just started out of no where. I was having no problems training and all of a sudden this error popped up. Nothing was changed in between training sessions. I've tried everything suggested here to no avail. Does anyone have any other ideas I could try?

**Comment by skunk-ink** [comment]
Nevermind I figured it out. It was because I was trying to train more than one concept. I guess my computer isn't quite up to the task. Dropped it back down to one concept and everything is working again.

**Comment by coopernyc** [comment]
Having the same issue, line 401 of  training_dreambooth.py, torch.stack(xxxx), nothing seems to help
