### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by lvelho** [d8ahazard/sd_dreambooth_extension#833]
### Kindly read the entire form below and fill it out with the requested information.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your
issue will be automatically closed._**

`
Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: ced8f33a0d50b87690d10b9015fae3594582d8d7
SD-WebUI revision: 7b1c7ba87b14da9960d0347269421233f4cb5838

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**

Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**

The error occurs during the installation

**Have you updated Dreambooth to the latest revision?**

Yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**

Yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**

OK

**Describe the bug**

Installation Bug. 

**Provide logs**

Installing collected packages: libclang, flatbuffers, bitsandbytes, zipp, wrapt, threadpoolctl, termcolor, tensorflow-io-gcs-filesystem, tensorflow-estimator, requests, protobuf, opt-einsum, opencv-python-headless, keras, joblib, h5py, google-pasta, gast, astunparse, starlette, scikit-learn, importlib-metadata, discord-webhook, accelerate, transformers, qudida, modelcards, fastapi, diffusers, tensorboard, albumentations, tensorflow-intel, tensorflow
  Attempting uninstall: requests
    Found existing installation: requests 2.25.1
    Uninstalling requests-2.25.1:
      Successfully uninstalled requests-2.25.1
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.0
    Uninstalling protobuf-3.20.0:
      Successfully uninstalled protobuf-3.20.0

stderr: ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'D:\\Workspace\\stable-diffusion-webui\\venv\\Lib\\site-packages\\google\\~rotobuf\\internal\\_api_implementation.cp310-win_amd64.pyd'
Check the permissions.

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *
before* the crash occurred.

**Environment**

What OS?

Windows 10

If Windows - WSL or native?

Native

What GPU are you using?

RTX 3090

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the
db_config.json file from /models/dreambooth/MODELNAME/db_config.json

**Comment by Zuxier** [comment]
can you go `D:\Workspace\stable-diffusion-webui\venv\Lib\site-packages\google\` and manually delete the `~rotobuf` folder?

**Comment by lvelho** [comment]
Hi,

Thanks for the reply!

I followed your instructions and tried to reinstall Dreambooth, but I got a new permission error:

ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'D:\\Workspace\\stable-diffusion-webui\\venv\\Lib\\site-packages\\cv2\\cv2.pyd'
Check the permissions.

Here is the full log:

=============================================================================================================================

Error running install.py for extension D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension.
Command: "D:\Workspace\stable-diffusion-webui\venv\Scripts\python.exe" "D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\install.py"
Error code: 1
stdout:
#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: c544ee11aee0085a7fbb7fdda65898dea2145f0c
SD-WebUI revision: 7b1c7ba87b14da9960d0347269421233f4cb5838

Checking Dreambooth requirements...

stderr: Traceback (most recent call last):
  File "D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\install.py", line 90, in <module>
    run(f'"{sys.executable}" -m pip install -r "{req_file}"', f"Checking {name} requirements...",
  File "D:\Workspace\stable-diffusion-webui\launch.py", line 65, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install Dreambooth requirements..
Command: "D:\Workspace\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install -r "D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt"
Error code: 1
stdout: Ignoring tensorflow-macos: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
Collecting accelerate==0.15.0
  Using cached accelerate-0.15.0-py3-none-any.whl (191 kB)
Collecting albumentations==1.3.0
  Using cached albumentations-1.3.0-py3-none-any.whl (123 kB)
Requirement already satisfied: bitsandbytes==0.35.0 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from -r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 3)) (0.35.0)
Collecting diffusers==0.10.2
  Using cached diffusers-0.10.2-py3-none-any.whl (503 kB)
Collecting fastapi==0.87.0
  Using cached fastapi-0.87.0-py3-none-any.whl (55 kB)
Requirement already satisfied: ftfy==6.1.1 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from -r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 6)) (6.1.1)
Collecting modelcards==0.1.6
  Using cached modelcards-0.1.6-py3-none-any.whl (12 kB)
Collecting tensorboard==2.11.0
  Using cached tensorboard-2.11.0-py3-none-any.whl (6.0 MB)
Collecting tensorflow==2.11.0
  Using cached tensorflow-2.11.0-cp310-cp310-win_amd64.whl (1.9 kB)
Requirement already satisfied: tqdm==4.64.1 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from -r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 11)) (4.64.1)
Collecting transformers==4.25.1
  Using cached transformers-4.25.1-py3-none-any.whl (5.8 MB)
Collecting discord-webhook==1.0.0
  Using cached discord_webhook-1.0.0-py3-none-any.whl (12 kB)
Requirement already satisfied: pyyaml in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from accelerate==0.15.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (6.0)
Requirement already satisfied: psutil in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from accelerate==0.15.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (5.9.4)
Requirement already satisfied: torch>=1.4.0 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from accelerate==0.15.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (1.13.1+cu117)
Requirement already satisfied: packaging>=20.0 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from accelerate==0.15.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (23.0)
Requirement already satisfied: numpy>=1.17 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from accelerate==0.15.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (1.23.3)
Requirement already satisfied: scipy in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from albumentations==1.3.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (1.10.0)
Collecting opencv-python-headless>=4.1.1
  Using cached opencv_python_headless-4.7.0.68-cp37-abi3-win_amd64.whl (38.1 MB)
Requirement already satisfied: scikit-image>=0.16.1 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from albumentations==1.3.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (0.19.2)
Collecting qudida>=0.0.4
  Using cached qudida-0.0.4-py3-none-any.whl (3.5 kB)
Collecting importlib-metadata
  Using cached importlib_metadata-6.0.0-py3-none-any.whl (21 kB)
Requirement already satisfied: Pillow in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from diffusers==0.10.2->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (9.4.0)
Requirement already satisfied: filelock in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from diffusers==0.10.2->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (3.9.0)
Requirement already satisfied: regex!=2019.12.17 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from diffusers==0.10.2->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (2022.10.31)
Requirement already satisfied: requests in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from diffusers==0.10.2->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (2.25.1)
Requirement already satisfied: huggingface-hub>=0.10.0 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from diffusers==0.10.2->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (0.11.1)
Collecting starlette==0.21.0
  Using cached starlette-0.21.0-py3-none-any.whl (64 kB)
Requirement already satisfied: pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from fastapi==0.87.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 5)) (1.10.4)
Requirement already satisfied: wcwidth>=0.2.5 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from ftfy==6.1.1->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 6)) (0.2.6)
Requirement already satisfied: Jinja2 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from modelcards==0.1.6->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 7)) (3.1.2)
Requirement already satisfied: wheel>=0.26 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from tensorboard==2.11.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (0.38.4)
Requirement already satisfied: grpcio>=1.24.3 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from tensorboard==2.11.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (1.51.1)
Requirement already satisfied: absl-py>=0.4 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from tensorboard==2.11.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (1.4.0)
Requirement already satisfied: google-auth<3,>=1.6.3 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from tensorboard==2.11.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (2.16.0)
Requirement already satisfied: setuptools>=41.0.0 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from tensorboard==2.11.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (63.2.0)
Requirement already satisfied: markdown>=2.6.8 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from tensorboard==2.11.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (3.4.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from tensorboard==2.11.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (1.8.1)
Requirement already satisfied: werkzeug>=1.0.1 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from tensorboard==2.11.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (2.2.2)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from tensorboard==2.11.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (0.4.6)
Requirement already satisfied: protobuf<4,>=3.9.2 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from tensorboard==2.11.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (3.19.6)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from tensorboard==2.11.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (0.6.1)
Collecting tensorflow-intel==2.11.0
  Using cached tensorflow_intel-2.11.0-cp310-cp310-win_amd64.whl (266.3 MB)
Requirement already satisfied: colorama in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from tqdm==4.64.1->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 11)) (0.4.6)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from transformers==4.25.1->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 12)) (0.12.1)
Collecting requests
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Requirement already satisfied: anyio<5,>=3.4.0 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from starlette==0.21.0->fastapi==0.87.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 5)) (3.6.2)
Requirement already satisfied: termcolor>=1.1.0 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (2.2.0)
Requirement already satisfied: flatbuffers>=2.0 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (23.1.21)
Collecting gast<=0.4.0,>=0.2.1
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (0.30.0)
Collecting keras<2.12,>=2.11.0
  Using cached keras-2.11.0-py2.py3-none-any.whl (1.7 MB)
Collecting google-pasta>=0.1.1
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Requirement already satisfied: libclang>=13.0.0 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (15.0.6.1)
Requirement already satisfied: typing-extensions>=3.6.6 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (4.4.0)
Collecting opt-einsum>=2.3.2
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Requirement already satisfied: six>=1.12.0 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (1.16.0)
Collecting h5py>=2.9.0
  Using cached h5py-3.8.0-cp310-cp310-win_amd64.whl (2.6 MB)
Requirement already satisfied: wrapt>=1.11.0 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (1.14.1)
Collecting astunparse>=1.6.0
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: tensorflow-estimator<2.12,>=2.11.0 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (2.11.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard==2.11.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (5.3.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard==2.11.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard==2.11.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard==2.11.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (1.3.1)
Collecting scikit-learn>=0.19.1
  Using cached scikit_learn-1.2.0-cp310-cp310-win_amd64.whl (8.2 MB)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from requests->diffusers==0.10.2->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from requests->diffusers==0.10.2->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from requests->diffusers==0.10.2->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from requests->diffusers==0.10.2->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (2022.12.7)
Requirement already satisfied: PyWavelets>=1.1.1 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from scikit-image>=0.16.1->albumentations==1.3.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (1.4.1)
Requirement already satisfied: networkx>=2.2 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from scikit-image>=0.16.1->albumentations==1.3.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (3.0)
Requirement already satisfied: imageio>=2.4.1 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from scikit-image>=0.16.1->albumentations==1.3.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (2.25.0)
Requirement already satisfied: tifffile>=2019.7.26 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from scikit-image>=0.16.1->albumentations==1.3.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (2023.1.23.1)
Requirement already satisfied: MarkupSafe>=2.1.1 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from werkzeug>=1.0.1->tensorboard==2.11.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (2.1.2)
Requirement already satisfied: zipp>=0.5 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from importlib-metadata->diffusers==0.10.2->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (3.11.0)
Requirement already satisfied: sniffio>=1.1 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from anyio<5,>=3.4.0->starlette==0.21.0->fastapi==0.87.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 5)) (1.3.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard==2.11.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard==2.11.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (3.2.2)
Collecting joblib>=1.1.1
  Using cached joblib-1.2.0-py3-none-any.whl (297 kB)
Requirement already satisfied: threadpoolctl>=2.0.0 in d:\workspace\stable-diffusion-webui\venv\lib\site-packages (from scikit-learn>=0.19.1->qudida>=0.0.4->albumentations==1.3.0->-r D:\Workspace\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (3.1.0)
Installing collected packages: requests, opt-einsum, opencv-python-headless, keras, joblib, importlib-metadata, h5py, google-pasta, gast, astunparse, starlette, scikit-learn, discord-webhook, accelerate, transformers, qudida, modelcards, fastapi, diffusers, tensorboard, albumentations, tensorflow-intel, tensorflow
  Attempting uninstall: requests
    Found existing installation: requests 2.25.1
    Uninstalling requests-2.25.1:
      Successfully uninstalled requests-2.25.1

stderr: WARNING: Ignoring invalid distribution -rotobuf (d:\workspace\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (d:\workspace\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (d:\workspace\stable-diffusion-webui\venv\lib\site-packages)
    WARNING: Ignoring invalid distribution -rotobuf (d:\workspace\stable-diffusion-webui\venv\lib\site-packages)
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'D:\\Workspace\\stable-diffusion-webui\\venv\\Lib\\site-packages\\cv2\\cv2.pyd'
Check the permissions.

WARNING: Ignoring invalid distribution -rotobuf (d:\workspace\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (d:\workspace\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (d:\workspace\stable-diffusion-webui\venv\lib\site-packages)

[notice] A new release of pip available: 22.2.1 -> 22.3.1
[notice] To update, run: D:\Workspace\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip

=============================================================================================================================

Best Regards,

-Luiz

**Comment by Zuxier** [comment]
i would probably start from a new venv

**Comment by lvelho** [comment]
You mean, reinstall  Web-ui, manually delete the ~rotobuf folder and then install Dreambooth ?

[]s,

-LV

**Comment by Zuxier** [comment]
if you delete the venv directory it should create a new one

**Comment by lvelho** [comment]
Ok, I will try that..

**Comment by lvelho** [comment]
fixed

**Comment by lvelho** [comment]
Done, thanks!  -LV

**Comment by Tophness** [comment]
Getting the same error. Can't install due to file access denied error on ~rotobuf then cv2 after deleting that.
Deleting venv does nothing.

**Comment by drqux** [comment]
> Getting the same error. Can't install due to file access denied error on ~rotobuf then cv2 after deleting that. Deleting venv does nothing.

What did  you do to fix it?

**Comment by Tophness** [comment]
> > Getting the same error. Can't install due to file access denied error on ~rotobuf then cv2 after deleting that. Deleting venv does nothing.
> 
> What did you do to fix it?
Delete venv, install as normal but update xformers to 0.0.17.dev451.
Without updating xformers, it seemed like the install wasn't working because training a model did nothing to it, which caused me to try a bunch of things to get it to install when you click install before a restart, which is impossible due to all the file access errors above.
