### ISSUE TITLE
generation failed: list index out of range

### ISSUE THREAD

**Issue by yggdrasil75** [d8ahazard/sd_dreambooth_extension#843]
### Kindly read the entire form below and fill it out with the requested information.

`
Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: c544ee11aee0085a7fbb7fdda65898dea2145f0c
SD-WebUI revision: 602a1864b05075ca4283986e6f5c7d5bce864e11

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.14.dev0 installed.
[+] torch version 1.12.1+cu113 installed.
[+] torchvision version 0.13.1+cu113 installed.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yes

**Have you updated Dreambooth to the latest revision?**
yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**
ok. I did. have git pull in the webui-user.bat for webui and this started after a update to dreambooth

**Describe the bug**
starts and then fails to train. 

(A clear and concise description of what the bug is)

**Provide logs**

Error completing request
Arguments: ('wlop', False) {}
Traceback (most recent call last):
  File "D:\creations\imagetraining\automatic\extensions\sd_dreambooth_extension\dreambooth\utils.py", line 200, in f
    res = func(*args, **kwargs)
  File "D:\creations\imagetraining\automatic\extensions\sd_dreambooth_extension\scripts\dreambooth.py", line 423, in start_training
    if not len(config.concepts()):
  File "D:\creations\imagetraining\automatic\extensions\sd_dreambooth_extension\dreambooth\db_config.py", line 154, in concepts
    concepts_list = concepts_from_file(self.concepts_path)
  File "D:\creations\imagetraining\automatic\extensions\sd_dreambooth_extension\dreambooth\db_config.py", line 196, in concepts_from_file
    if os.path.exists(concepts_path) and os.path.isfile(str):
  File "C:\Users\Yggdrasil75\AppData\Local\Programs\Python\Python310\lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not type

Traceback (most recent call last):
  File "D:\creations\imagetraining\automatic\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\creations\imagetraining\automatic\venv\lib\site-packages\gradio\blocks.py", line 1018, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\creations\imagetraining\automatic\venv\lib\site-packages\gradio\blocks.py", line 935, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: list index out of range

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *
before* the crash occurred.

**Environment**

What OS?
windows 10 native os

If Windows - WSL or native?

What GPU are you using?
RTX 3090. this is specified in the commandline params, but I also have a gtx 1080 ti so that I can play graphically intensive games without stopping training.

**Comment by dsully** [comment]
Something in dc8d1f4f8beb546089abd107db3432e03339c9c0 caused this error.

**Comment by geocine** [comment]
Hard Reload browser CTRL+F5 https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7102

**Comment by yggdrasil75** [comment]
this is not on creating a model, this is on training a model. if I create a model it works, and after creating, that new model is trainable, but the old model which I have more training to do on will fail. I could start over with training, but who wants to waste days of training for an empty model?

**Comment by Flonixcorn** [comment]
Traceback (most recent call last):
  File "X:\AI\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "X:\AI\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1013, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "X:\AI\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 911, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
IndexError: list index out of range

Similar error here

**Comment by eftSharptooth** [comment]
@yggdrasil75 
in db_config.py line 196 to :
if os.path.exists(concepts_path) and os.path.isfile(concepts_path):
fixed this for me.
