### ISSUE TITLE
Last update broken offline TRAIN

### ISSUE THREAD

**Issue by ffdown** [d8ahazard/sd_dreambooth_extension#855]
### Kindly read the entire form below and fill it out with the requested information.

`
Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: 9f4d931a319056c537d24669cb950d146d1537b0
SD-WebUI revision: dac59b9b073f86508d3ec787ff731af2e101fbcc
Commit hash: dac59b9b073f86508d3ec787ff731af2e101fbcc

[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[!] transformers version 4.19.2 installed.
[+] xformers version 0.0.14.dev0 installed.
[+] torch version 1.12.1+cu113 installed.
[+] torchvision version 0.13.1+cu113 installed.
`
DB, WebUI - last version

**Describe the bug**

Every train this trouble
not this
set "HF_DATASETS_OFFLINE=1"
set "TRANSFORMERS_OFFLINE=1"

not this
set "HF_DATASETS_OFFLINE=True"
set "TRANSFORMERS_OFFLINE=True"

not worked.

**Provide logs**

```
Traceback (most recent call last):
  File "E:\AI\SDPORT\extensions\sd_dreambooth_extension\scripts\dreambooth.py", line 455, in start_training
    result = main(config, use_txt2img=use_txt2img)
  File "E:\AI\SDPORT\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 989, in main
    return inner_loop()
  File "E:\AI\SDPORT\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 121, in decorator
    return function(batch_size, grad_size, prof, log_file, *args, **kwargs)
  File "E:\AI\SDPORT\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 206, in inner_loop
    text_encoder_cls = import_model_class_from_model_name_or_path(args.pretrained_model_name_or_path, args.revision)
  File "E:\AI\SDPORT\extensions\sd_dreambooth_extension\dreambooth\utils.py", line 520, in import_model_class_from_model_name_or_path
    text_encoder_config = PretrainedConfig.from_pretrained(
  File "E:\AI\SDPORT\venv\lib\site-packages\transformers\configuration_utils.py", line 526, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "E:\AI\SDPORT\venv\lib\site-packages\transformers\configuration_utils.py", line 553, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "E:\AI\SDPORT\venv\lib\site-packages\transformers\configuration_utils.py", line 634, in _get_config_dict
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like E:\AI\SDPORT\models\dreambooth\vlch\working is not the path to a directory containing a config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
Restored system models.
```

**Environment**

Win 10 Wsl
Rhyzen 5 3600
RTX 4090

**Comment by Arilziem** [comment]
There are some models that need to be downloaded from huggingface before you can start training, which are then saved in the .cache folder in your user directory. Once you have them, training should work without an internet connection.

I don't think there is a convenient way to download them for offline right now, other than starting the extension on a computer with internet access and having it download everything. If you are using a separate computer, you can copy the .cache folder.
