### ISSUE TITLE
Preview Prompt button errors due to looking in wrong spot for db_config.json

### ISSUE THREAD

**Issue by jlee2109** [d8ahazard/sd_dreambooth_extension#858]
### Kindly read the entire form below and fill it out with the requested information.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your
issue will be automatically closed._**

`
Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: 9f4d931a319056c537d24669cb950d146d1537b0
SD-WebUI revision: 48a15821de768fea76e66f26df83df3fddf18f4b

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.14.dev0 installed.
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yes

**Have you updated Dreambooth to the latest revision?**
yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**
OK

**Describe the bug**
The "Preview Prompts" button generates errors when clicked, and does not show the prompt.  The console shows the error message below.  It seems like it is looking in the wrong place for the db_config file.  It needs to look 1x directory deeper into the individual model directories (dreambooth/MODELNAME), but for some reason it expects a file in the top-level dreambooth directory.

**Provide logs**

```
Exception loading config: [Errno 2] No such file or directory: 'C:\\Users\\Josh\\Documents\\GIT\\stable-diffusion-webui\\models\\dreambooth\\db_config.json'
Traceback (most recent call last):
  File "C:\Users\Josh\Documents\GIT\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\db_config.py", line 267, in from_file
    with open(config_file, 'r') as openfile:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Josh\\Documents\\GIT\\stable-diffusion-webui\\models\\dreambooth\\db_config.json'
Traceback (most recent call last):
  File "C:\Users\Josh\Documents\GIT\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Josh\Documents\GIT\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "C:\Users\Josh\Documents\GIT\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Josh\Documents\GIT\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Josh\Documents\GIT\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Josh\Documents\GIT\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\Josh\Documents\GIT\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\finetune_utils.py", line 805, in generate_prompts
    os.path.join(config.pretrained_model_name_or_path, "tokenizer"),
AttributeError: 'NoneType' object has no attribute 'pretrained_model_name_or_path'
```

**Environment**

Windows 11 Native
RTX 4090

**Comment by paulstuffs** [comment]
Happens to me as well. Windows 10 with 4090. 

Latest A1111 + latest dreambooth.

**Comment by mfedatto** [comment]
Happens to me as well. Windows 10 with 2060 Super.

Latest A1111 + latest dreambooth.

**Comment by ouijahija** [comment]
Same here... I assumed the path that db_config.py uses to open the file is wrong, because it should be 'C:/[stable_diffusion_path]/models/dreambooth/[model_name]/db_config.json' but it actually uses 'C:/[stable_diffusion_path]/models/dreambooth/db_config.json' without the model name. Trying to figure out why it uses that path instead of the correct one I figured out, that the 'from_file' function gets called twice! First with the correct model_name and a second time with the model_name set to nothing...
I hope this is somewhat helpfull to maybe find a solution

**Comment by mfedatto** [comment]
There was an update available at the extension manager, but no behavior change regarding this issue.

**Comment by ouijahija** [comment]
bump, still not working for me

**Comment by mfedatto** [comment]
Not working here. Pulled the latest version, updated the extension, still doesn't work.

**Comment by d8ahazard** [comment]
This should be resolved with https://github.com/d8ahazard/sd_dreambooth_extension/releases/tag/1.0.11

Feel free to open a new issue if you're still having problems.
