### ISSUE TITLE
TypeError: 'in <string>' requires string as left operand, not list

### ISSUE THREAD

**Issue by DarkAlchy** [d8ahazard/sd_dreambooth_extension#861]
I see DB needed to be updated just now to be met with even more errors, not fixes.

Arguments: ('Chucky', [], 'ddim', False, '', '', False, False, False) {}
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\utils.py", line 200, in f
    res = func(*args, **kwargs)
  File "D:\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\dreambooth.py", line 551, in create_model
    checkpoint_info = get_checkpoint_match(ckpt_path)
  File "D:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\utils.py", line 258, in get_checkpoint_match
    if search_string in info.title or search_string in info.model_name or search_string in info.filename:
TypeError: 'in <string>' requires string as left operand, not list

I tried everything, even going back to 1.5, that I could, but nothing got past that error.

After this error I am met with 

Traceback (most recent call last):
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1018, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 935, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: list index out of range

I figure once the first error (this ticket) is fixed the second will go away because I can't even hard reset f5 to get it working as long as the bug before it is there.

**Comment by DarkAlchy** [comment]
I went looking and the only thing I could find is that on line 258 - https://bobbyhadz.com/blog/python-typeerror-in-string-requires-string-as-left-operand-not-list

**Comment by Flonixcorn** [comment]
Same error here:
Traceback (most recent call last):
  File "X:\AI\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "X:\AI\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1013, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "X:\AI\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 911, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
IndexError: list index out of range

**Comment by eftSharptooth** [comment]
in db_config.py line 196 to : 
    if os.path.exists(concepts_path) and os.path.isfile(concepts_path):
fixed this for me.
