### ISSUE TITLE
Offline not working-RESOVLED

### ISSUE THREAD

**Issue by NansDuval** [d8ahazard/sd_dreambooth_extension#865]
### Kindly read the entire form below and fill it out with the requested information.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your
issue will be automatically closed._**

`
Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Commit hash: ****************************************
Installing requirements for Web UI
Skipping dreambooth installation.
Dreambooth revision is 9f4d931a319056c537d24669cb950d146d1537b0
Diffusers version is  0.10.2
Torch version is  1.13.1+cu117 installed.
Torch vision version is 0.14.1+cu117 installed.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes

**Have you updated Dreambooth to the latest revision?**
Yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes
**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**
OK

**Describe the bug**
Offline not working

(A clear and concise description of what the bug is)
After installing dreambooth and automatic111 online everything goes well, but when I don't have wifi anymore it just dosen't work
I changed both webui-user-dreambooth.bat and webui-user-dreambooth.bat by uncommenting "export DREAMBOOTH_SKIP_INSTALL=True" but it still doesn't work offline. I will post a screenshot showing the files.

And when I am back online it's working just fine (unfortunatly I don't always have internet)
My bug is 

(sdo1) C:\SD\Online\1>webui-user.bat
venv "C:\SD\Online\1\venv\Scripts\Python.exe"
Python 3.10.9 | packaged by conda-forge | (main, Jan 11 2023, 15:15:40) [MSC v.1916 64 bit (AMD64)]
Commit hash: <none>
Installing requirements for Web UI
Traceback (most recent call last):
  File "C:\SD\Online\1\launch.py", line 315, in <module>
    prepare_environment()
  File "C:\SD\Online\1\launch.py", line 264, in prepare_environment
    run_pip(f"install -r {requirements_file}", "requirements for Web UI")
  File "C:\SD\Online\1\launch.py", line 97, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "C:\SD\Online\1\launch.py", line 65, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install requirements for Web UI.
Command: "C:\SD\Online\1\venv\Scripts\python.exe" -m pip install -r requirements_versions.txt --prefer-binary
Error code: 1
stdout: Requirement already satisfied: blendmodes==2022 in c:\sd\online\1\venv\lib\site-packages (from -r requirements_versions.txt (line 1)) (2022)

stderr: WARNING: Ignoring invalid distribution -rotobuf (c:\sd\online\1\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\sd\online\1\venv\lib\site-packages)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001DDD081EB30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/transformers/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001DDD081DE70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/transformers/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001DDD081E350>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/transformers/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001DDD081F1F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/transformers/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001DDD081F730>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/transformers/
ERROR: Could not find a version that satisfies the requirement transformers==4.19.2 (from versions: none)
ERROR: No matching distribution found for transformers==4.19.2
WARNING: Ignoring invalid distribution -rotobuf (c:\sd\online\1\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\sd\online\1\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\sd\online\1\venv\lib\site-packages)

Appuyez sur une touche pour continuer...
![8489](https://user-images.githubusercontent.com/111114859/214855680-6fc803f2-f0ad-4638-aaaf-846236155829.jpg)

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *
before* the crash occurred.

**Environment**
Anaconda

What OS?
Windows 10

If Windows - WSL or native?
No

What GPU are you using?
Geforce RTX 4090

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the
db_config.json file from /models/dreambooth/MODELNAME/db_config.json

**Comment by Arilziem** [comment]
The error message indicates that it wants to install transformers, which you need. So make sure you actually have that installed when you have internet and maybe do a trial run to make sure you also have all those models that need to be downloaded from huggingface.

The actual issue seems to be that you are running webui-user.bat though (judging from your screenshot). You need to copy webui-user-dreambooth.bat into the same folder that has webui-user.bat and then run the dreambooth one. It should then skip dependency checking if you have that line uncommented.

**Comment by NansDuval** [comment]
`The actual issue seems to be that you are running webui-user.bat though (judging from your screenshot). You need to copy webui-user-dreambooth.bat into the same folder that has webui-user.bat and then run the dreambooth one. It should then skip dependency checking if you have that line uncommented.`
It's launching again, thank you!

I think people need to know they need to put webui-user-dreambooth.bat into the main directory and launch it in order to make it work. Unfortunately, it is not written anywhere at the moment, so it can be frustrating for them to get it to work. In any case, thank you! you are doing an amazing job.
