### ISSUE TITLE
Exception training model: 'Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96:

### ISSUE THREAD

**Issue by BrennerLittle** [d8ahazard/sd_dreambooth_extension#871]
### Kindly read the entire form below and fill it out with the requested information.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your
issue will be automatically closed._**

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Dreambooth revision: 9f4d931a319056c537d24669cb950d146d1537b0
SD-WebUI revision: 7a14c8ab45da8a681792a6331d48a88dd684a0a9

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[ ] xformers version N/A installed.
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.

#######################################################################################################

**Describe the bug**

upon trying to train:
```
Exception training model: 'Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'C:\Users\brenn\Desktop\sd\sdw\models\dreambooth\ff\working\tokenizer'.'.
```
**Provide logs**
```
Traceback (most recent call last):
  File "C:\Users\brenn\Desktop\sd\sdw\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\brenn\Desktop\sd\sdw\venv\lib\site-packages\gradio\blocks.py", line 1018, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\brenn\Desktop\sd\sdw\venv\lib\site-packages\gradio\blocks.py", line 947, in postprocess_data
    prediction_value = postprocess_update_dict(
  File "C:\Users\brenn\Desktop\sd\sdw\venv\lib\site-packages\gradio\blocks.py", line 371, in postprocess_update_dict
    update_dict = block.get_specific_update(update_dict)
  File "C:\Users\brenn\Desktop\sd\sdw\venv\lib\site-packages\gradio\blocks.py", line 257, in get_specific_update
    specific_update = cls.update(**generic_update)
TypeError: HTML.update() got an unexpected keyword argument 'choices'
Exception loading config: [Errno 2] No such file or directory: 'C:\\Users\\brenn\\Desktop\\sd\\sdw\\models\\dreambooth\\f\\db_config.json'
Traceback (most recent call last):
  File "C:\Users\brenn\Desktop\sd\sdw\extensions\sd_dreambooth_extension\dreambooth\db_config.py", line 267, in from_file
    with open(config_file, 'r') as openfile:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\brenn\\Desktop\\sd\\sdw\\models\\dreambooth\\f\\db_config.json'
Total VRAM: 8
Exception loading config: [Errno 2] No such file or directory: 'C:\\Users\\brenn\\Desktop\\sd\\sdw\\models\\dreambooth\\f\\db_config.json'
Wizard results:<br>Num Epochs: 100<br>Num instance images per class image: 0
Traceback (most recent call last):
  File "C:\Users\brenn\Desktop\sd\sdw\extensions\sd_dreambooth_extension\dreambooth\db_config.py", line 267, in from_file
    with open(config_file, 'r') as openfile:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\brenn\\Desktop\\sd\\sdw\\models\\dreambooth\\f\\db_config.json'
Initializing dreambooth training...
Pre-processing o: 100%|███████████████████████████████████████████████████████████████| 34/34 [00:00<00:00, 315.30it/s]
Concept requires 0 class images per instance image.
Sorting instance images: 100%|███████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]
Nothing to generate.
Traceback (most recent call last):
  File "C:\Users\brenn\Desktop\sd\sdw\extensions\sd_dreambooth_extension\scripts\dreambooth.py", line 455, in start_training
    result = main(config, use_txt2img=use_txt2img)
  File "C:\Users\brenn\Desktop\sd\sdw\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 989, in main
    return inner_loop()
  File "C:\Users\brenn\Desktop\sd\sdw\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 121, in decorator
    return function(batch_size, grad_size, prof, log_file, *args, **kwargs)
  File "C:\Users\brenn\Desktop\sd\sdw\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 199, in inner_loop
    tokenizer = AutoTokenizer.from_pretrained(
  File "C:\Users\brenn\Desktop\sd\sdw\venv\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 582, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\brenn\Desktop\sd\sdw\venv\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 433, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "C:\Users\brenn\Desktop\sd\sdw\venv\lib\site-packages\transformers\utils\hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "C:\Users\brenn\Desktop\sd\sdw\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    validate_repo_id(arg_value)
  File "C:\Users\brenn\Desktop\sd\sdw\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 172, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'C:\Users\brenn\Desktop\sd\sdw\models\dreambooth\f\working\tokenizer'.
Restored system models.
Loading model from checkpoint.
Loading ckpt...
Exception setting up output: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 8.00 GiB total capacity; 6.70 GiB already allocated; 0 bytes free; 6.80 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "C:\Users\brenn\Desktop\sd\sdw\extensions\sd_dreambooth_extension\dreambooth\sd_to_diff.py", line 1066, in extract_checkpoint
    checkpoint = torch.load(checkpoint_file, map_location=map_location or shared.weight_load_location)
  File "C:\Users\brenn\Desktop\sd\sdw\extensions\sd_dreambooth_extension\reallysafe.py", line 117, in load
    return load_with_extra(filename, *args, **kwargs)
  File "C:\Users\brenn\Desktop\sd\sdw\extensions\sd_dreambooth_extension\reallysafe.py", line 164, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "C:\Users\brenn\Desktop\sd\sdw\modules\safe.py", line 106, in load
    return load_with_extra(filename, extra_handler=global_extra_handler, *args, **kwargs)
  File "C:\Users\brenn\Desktop\sd\sdw\modules\safe.py", line 151, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "C:\Users\brenn\Desktop\sd\sdw\venv\lib\site-packages\torch\serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\brenn\Desktop\sd\sdw\venv\lib\site-packages\torch\serialization.py", line 1131, in _load
    result = unpickler.load()
  File "C:\Users\brenn\Desktop\sd\sdw\venv\lib\site-packages\torch\serialization.py", line 1101, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "C:\Users\brenn\Desktop\sd\sdw\venv\lib\site-packages\torch\serialization.py", line 1083, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "C:\Users\brenn\Desktop\sd\sdw\venv\lib\site-packages\torch\serialization.py", line 1055, in restore_location
    return default_restore_location(storage, str(map_location))
  File "C:\Users\brenn\Desktop\sd\sdw\venv\lib\site-packages\torch\serialization.py", line 215, in default_restore_location
    result = fn(storage, location)
  File "C:\Users\brenn\Desktop\sd\sdw\venv\lib\site-packages\torch\serialization.py", line 187, in _cuda_deserialize
    return obj.cuda(device)
  File "C:\Users\brenn\Desktop\sd\sdw\venv\lib\site-packages\torch\_utils.py", line 80, in _cuda
    untyped_storage = torch.UntypedStorage(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 8.00 GiB total capacity; 6.70 GiB already allocated; 0 bytes free; 6.80 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Pipeline or config is not set, unable to continue.
Restored system models.
Exception loading config: [Errno 2] No such file or directory: 'C:\\Users\\brenn\\Desktop\\sd\\sdw\\models\\dreambooth\\ff\\db_config.json'
Traceback (most recent call last):
  File "C:\Users\brenn\Desktop\sd\sdw\extensions\sd_dreambooth_extension\dreambooth\db_config.py", line 267, in from_file
    with open(config_file, 'r') as openfile:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\brenn\\Desktop\\sd\\sdw\\models\\dreambooth\\ff\\db_config.json'
Can't load config!
Traceback (most recent call last):
  File "C:\Users\brenn\Desktop\sd\sdw\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\brenn\Desktop\sd\sdw\venv\lib\site-packages\gradio\blocks.py", line 1018, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\brenn\Desktop\sd\sdw\venv\lib\site-packages\gradio\blocks.py", line 947, in postprocess_data
    prediction_value = postprocess_update_dict(
  File "C:\Users\brenn\Desktop\sd\sdw\venv\lib\site-packages\gradio\blocks.py", line 371, in postprocess_update_dict
    update_dict = block.get_specific_update(update_dict)
  File "C:\Users\brenn\Desktop\sd\sdw\venv\lib\site-packages\gradio\blocks.py", line 257, in get_specific_update
    specific_update = cls.update(**generic_update)
TypeError: HTML.update() got an unexpected keyword argument 'choices'
Exception loading config: [Errno 2] No such file or directory: 'C:\\Users\\brenn\\Desktop\\sd\\sdw\\models\\dreambooth\\ff\\db_config.json'
Traceback (most recent call last):
  File "C:\Users\brenn\Desktop\sd\sdw\extensions\sd_dreambooth_extension\dreambooth\db_config.py", line 267, in from_file
    with open(config_file, 'r') as openfile:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\brenn\\Desktop\\sd\\sdw\\models\\dreambooth\\ff\\db_config.json'
Total VRAM: 8
Exception loading config: [Errno 2] No such file or directory: 'C:\\Users\\brenn\\Desktop\\sd\\sdw\\models\\dreambooth\\ff\\db_config.json'
Traceback (most recent call last):
  File "C:\Users\brenn\Desktop\sd\sdw\extensions\sd_dreambooth_extension\dreambooth\db_config.py", line 267, in from_file
    with open(config_file, 'r') as openfile:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\brenn\\Desktop\\sd\\sdw\\models\\dreambooth\\ff\\db_config.json'
Custom model name is mx
Initializing dreambooth training...
Pre-processing o: 100%|███████████████████████████████████████████████████████████████| 34/34 [00:00<00:00, 370.20it/s]
Concept requires 0 class images per instance image.
Sorting instance images: 100%|███████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]
Nothing to generate.
Traceback (most recent call last):
  File "C:\Users\brenn\Desktop\sd\sdw\extensions\sd_dreambooth_extension\scripts\dreambooth.py", line 455, in start_training
    result = main(config, use_txt2img=use_txt2img)
  File "C:\Users\brenn\Desktop\sd\sdw\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 989, in main
    return inner_loop()
  File "C:\Users\brenn\Desktop\sd\sdw\extensions\sd_dreambooth_extension\dreambooth\memory.py", line 121, in decorator
    return function(batch_size, grad_size, prof, log_file, *args, **kwargs)
  File "C:\Users\brenn\Desktop\sd\sdw\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 199, in inner_loop
    tokenizer = AutoTokenizer.from_pretrained(
  File "C:\Users\brenn\Desktop\sd\sdw\venv\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 582, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\brenn\Desktop\sd\sdw\venv\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 433, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "C:\Users\brenn\Desktop\sd\sdw\venv\lib\site-packages\transformers\utils\hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "C:\Users\brenn\Desktop\sd\sdw\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    validate_repo_id(arg_value)
  File "C:\Users\brenn\Desktop\sd\sdw\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 172, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'C:\Users\brenn\Desktop\sd\sdw\models\dreambooth\ff\working\tokenizer'.
Restored system models.
```

**Environment**

What OS?
windows 10
If Windows - WSL or native?
windows native
What GPU are you using?
Rtx 3080
**Screenshots/Config**
training parameters do not matter In reproducing this bug

**Comment by BrennerLittle** [comment]
I believe I ran out of GPU memory closing issue
