### ISSUE TITLE
Unable to use the extension: black image during training

### ISSUE THREAD

**Issue by ghost** [d8ahazard/sd_dreambooth_extension#883]
### Kindly read the entire form below and fill it out with the requested information.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your
issue will be automatically closed._**

`
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 2c1bb46c7ad5b4536f6587d327a03f0ff7811c5d
Installing requirements for Web UI

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: 9f4d931a319056c537d24669cb950d146d1537b0
SD-WebUI revision: 2c1bb46c7ad5b4536f6587d327a03f0ff7811c5d

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.16rc425 installed.
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
YES

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
YES

**Have you updated Dreambooth to the latest revision?**
YES

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
YES

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**
OK

**Describe the bug**

Training preview images turn black from about 300 steps during training, no error in the terminal. 

If I try to use the trained model, here is the error I get when generating the image. (NB: I'm not training the model from a weird model, I'm using the official v1.5pruned model):

Traceback (most recent call last):
  File "D:\SD\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\SD\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\SD\stable-diffusion-webui\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "D:\SD\stable-diffusion-webui\modules\processing.py", line 484, in process_images
    res = process_images_inner(p)
  File "D:\SD\stable-diffusion-webui\modules\processing.py", line 626, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "D:\SD\stable-diffusion-webui\modules\processing.py", line 826, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "D:\SD\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 290, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "D:\SD\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 190, in launch_sampling
    return func()
  File "D:\SD\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 290, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "D:\SD\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\SD\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 128, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "D:\SD\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\SD\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 111, in forward
    devices.test_for_nans(x_out, "unet")
  File "D:\SD\stable-diffusion-webui\modules\devices.py", line 156, in test_for_nans
    raise NansException(message)
modules.devices.NansException: A tensor with all NaNs was produced in Unet. This could be either because there's not enough precision to represent the picture, or because your video card does not support half type. Try setting the "Upcast cross attention layer to float32" option in Settings > Stable Diffusion or using the --no-half commandline argument to fix this. Use --disable-nan-check commandline argument to disable this check.

**Environment**

What OS? 

Windows 11

What GPU are you using?

RTX 4090

**Screenshots/Config**

![dreambooth](https://user-images.githubusercontent.com/117512850/215863002-dfaeb1b1-13c6-4cb8-99df-81cff2a6c93a.png)

**Comment by eadnams22** [comment]
I was getting that, I had to roll back xformers, there's a thread for that, or an issue? I'll edit if I can find it.

**Comment by Romustach** [comment]
> I was getting that, I had to roll back xformers, there's a thread for that, or an issue? I'll edit if I can find it.

Thank you, that doesnt really surprise me. I have the feeling that xformers has been doing a hell of a mess since the last update. It's not just limited to Dreambooth. I checked many threads before posting, without solutions for now

**Comment by Mattias-NCVIB** [comment]
Disable xformers and you should be good to go. As a matter of fact, until this issue is resolved, it'd be better if dreambooth defaultet to not using xformers...

**Comment by eadnams22** [comment]
Found the rollback instructions: https://github.com/d8ahazard/sd_dreambooth_extension/issues/859#issuecomment-1404136810

**Comment by Romustach** [comment]
@eadnams22 @Mattias-NCVIB Thank you, but no need to disable xformers, i solved the problem by following this great video. Everything works perfectly and even better than before now : https://www.youtube.com/watch?v=O01BrQwOd-Q

**Comment by eadnams22** [comment]
> @eadnams22 @Mattias-NCVIB Thank you, but no need to disable xformers, i solved the problem by following this great video. Everything works perfectly and even better than before now : https://www.youtube.com/watch?v=O01BrQwOd-Q

I didn’t suggest disabling xformers, that was someone else, I was just keeping it the version that works with the extension. :) 

Glad you got it working!

**Comment by yggdrasil75** [comment]
> @eadnams22 @Mattias-NCVIB Thank you, but no need to disable xformers, i solved the problem by following this great video. Everything works perfectly and even better than before now : https://www.youtube.com/watch?v=O01BrQwOd-Q

why close the issue? the extension still needs updating to work with newer xformers. the video you linked said as much. this remains and issue that should be addressed

**Comment by FurkanGozukara** [comment]
you need to downgrade cuda

xformers above 0.0.14 not supported by dreambooth atm

[8 GB LoRA Training - Fix CUDA Version For DreamBooth and Textual Inversion Training By Automatic1111](https://www.youtube.com/watch?v=O01BrQwOd-Q)
![image.png](https://s3.amazonaws.com/moonup/production/uploads/1](https://youtu.be/O01BrQwOd-Q)674549397099-6345bd89fe134dfd7a0dba40.png)

**Comment by Romustach** [comment]
> you need to downgrade cuda
> 
> xformers above 0.0.14 not supported by dreambooth atm
> 
> [8 GB LoRA Training - Fix CUDA Version For DreamBooth and Textual Inversion Training By Automatic1111](https://www.youtube.com/watch?v=O01BrQwOd-Q) ![image.png](https://camo.githubusercontent.com/73b77bb1973e2c9440c5a31822718dd5da3259130d5fa01b858ff56fec17d3ca/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6d6f6f6e75702f70726f64756374696f6e2f75706c6f6164732f313637343534393339373039392d3633343562643839666531333464666437613064626134302e706e67)

Yes sir just posted your video above, thanks for this one and the others you helped !

**Comment by Essamara** [comment]
I had trouble with the above youtube video

I found out xformers is bust in the new version of 1111

this video has the right commit and a download of the right xformers and torch

https://www.youtube.com/watch?v=usgqmQ0Mq7g

**Comment by d8ahazard** [comment]
This should be resolved with https://github.com/d8ahazard/sd_dreambooth_extension/releases/tag/1.0.11

Feel free to open a new issue if you're still having problems.

**Comment by sweihub** [comment]
I am using the arguments which do not solve the black image problem

export COMMANDLINE_ARGS="--listen --enable-insecure-extension-access --skip-install --upcast-sampling --precision full --no-half --medvram"

I am uisng a A40 card and CUDA11.8,  the dreambooth traing still produce black images, any ideas?
