### ISSUE TITLE
 No module named 'accelerate'

### ISSUE THREAD

**Issue by OoAnikioO** [d8ahazard/sd_dreambooth_extension#89]
**Have you read the Readme?**

yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**

yes

**Have you updated Dreambooth to the latest revision?**

yes

**Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth**

`Dreambooth revision is 3b3a8002da3a780c276934e8bcf308aa822f1e22
Diffusers version is 0.8.0.dev0.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.`

**Describe the bug**

accelerate is installed 

pip install accelerate
Requirement already satisfied: accelerate in c:\users\papa\appdata\local\programs\python\python310\lib\site-packages (0.14.0)
Requirement already satisfied: torch>=1.4.0 in c:\users\papa\appdata\local\programs\python\python310\lib\site-packages (from accelerate) (1.12.1+cu116)
Requirement already satisfied: psutil in c:\users\papa\appdata\local\programs\python\python310\lib\site-packages (from accelerate) (5.9.4)
Requirement already satisfied: packaging>=20.0 in c:\users\papa\appdata\local\programs\python\python310\lib\site-packages (from accelerate) (21.3)
Requirement already satisfied: numpy>=1.17 in c:\users\papa\appdata\local\programs\python\python310\lib\site-packages (from accelerate) (1.23.4)
Requirement already satisfied: pyyaml in c:\users\papa\appdata\local\programs\python\python310\lib\site-packages (from accelerate) (6.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\papa\appdata\local\programs\python\python310\lib\site-packages (from packaging>=20.0->accelerate) (3.0.9)
Requirement already satisfied: typing-extensions in c:\users\papa\appdata\local\programs\python\python310\lib\site-packages (from torch>=1.4.0->accelerate) (4.4.0)

but when i run webui

Closing server running on port: 7860
Reloading extensions
Reloading custom scripts
Error loading script: main.py
Traceback (most recent call last):
  File "C:\Users\Papa\Downloads\stable-diffusion-webui\modules\scripts.py", line 170, in load_scripts
    exec(compiled, module.__dict__)
  File "C:\Users\Papa\Downloads\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py", line 3, in <module>
    from dreambooth import conversion, dreambooth
  File "C:\Users\Papa\Downloads\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\conversion.py", line 26, in <module>
    from dreambooth.dreambooth import get_db_models
  File "C:\Users\Papa\Downloads\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 10, in <module>
    from dreambooth.train_dreambooth import main
  File "C:\Users\Papa\Downloads\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 20, in <module>
    from accelerate import Accelerator
ModuleNotFoundError: No module named 'accelerate'

**Provide logs**
If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *before* the crash occurred.

**Environment**
What OS?
If Windows - WSL or native?

windows 11 native

What GPU are you using?

rtx 2060Ti

**Comment by xiaolxl** [comment]
手动安装accelerate
pip install accelerate

Manually install accelerate
pip install accelerate

**Comment by d8ahazard** [comment]
This is odd. The same bit that sets your diffusers version to 0.8.0.dev is what installs accelerate.

git+https://github.com/ShivamShrirao/diffusers.git#egg=diffusers

When you do (from the root of the SD directory) the following commands, what output do you get?

`
.\venv\scripts\activate.bat
pip install accelerate
`

**Comment by frosta95** [comment]
> This is odd. The same bit that sets your diffusers version to 0.8.0.dev is what installs accelerate.
> 
> git+https://github.com/ShivamShrirao/diffusers.git#egg=diffusers
> 
> When you do (from the root of the SD directory) the following commands, what output do you get?
> 
> ` .\venv\scripts\activate.bat
> 
> pip install accelerate `

So I have the exact same error and it gives me a succesful install at first and after I reopen stable diffusion it gives me the same error again. 

`Error loading script: main.py
Traceback (most recent call last):
  File "D:\AI\Auto1111_WebUI\stable-diffusion-webui\modules\scripts.py", line 170, in load_scripts
    exec(compiled, module.__dict__)
  File "D:\AI\Auto1111_WebUI\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py", line 3, in <module>
    from dreambooth import conversion, dreambooth
  File "D:\AI\Auto1111_WebUI\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\conversion.py", line 26, in <module>
    from dreambooth.dreambooth import get_db_models
  File "D:\AI\Auto1111_WebUI\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 10, in <module>
    from dreambooth.train_dreambooth import main
  File "D:\AI\Auto1111_WebUI\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 20, in <module>
    from accelerate import Accelerator
ModuleNotFoundError: No module named 'accelerate'`

**Comment by d8ahazard** [comment]
Fixed/updated the installer, this should resolve this.
