### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'pretrained_vae_name_or_path'

### ISSUE THREAD

**Issue by Boymerkz** [d8ahazard/sd_dreambooth_extension#928]
Every time i go to Generate class images i get this error, The VAE section is left blank also tried downloading and linkine the 1.5 vae's to no success using Automatics1111 WebUI 

Checkpoint successfully extracted to /notebooks/stable-diffusion/stable-diffusion-webui/models/dreambooth/A-Jay-V1/working
Restored system models.
Exception loading config: [Errno 2] No such file or directory: '/notebooks/stable-diffusion/stable-diffusion-webui/models/dreambooth/db_config.json'
Traceback (most recent call last):
  File "/notebooks/stable-diffusion/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/db_config.py", line 267, in from_file
    with open(config_file, 'r') as openfile:
FileNotFoundError: [Errno 2] No such file or directory: '/notebooks/stable-diffusion/stable-diffusion-webui/models/dreambooth/db_config.json'
Error completing request
Arguments: ([], True) {}
Exception loading config: [Errno 2] No such file or directory: '/notebooks/stable-diffusion/stable-diffusion-webui/models/dreambooth/db_config.json'
Traceback (most recent call last):
  File "/notebooks/stable-diffusion/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/db_config.py", line 267, in from_file
    with open(config_file, 'r') as openfile:
FileNotFoundError: [Errno 2] No such file or directory: '/notebooks/stable-diffusion/stable-diffusion-webui/models/dreambooth/db_config.json'
Traceback (most recent call last):
  File "/notebooks/stable-diffusion/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/utils.py", line 200, in f
    res = func(*args, **kwargs)
  File "/notebooks/stable-diffusion/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/dreambooth.py", line 501, in ui_classifiers
    if config.pretrained_vae_name_or_path == "":
AttributeError: 'NoneType' object has no attribute 'pretrained_vae_name_or_path'

**Comment by d8ahazard** [comment]
Please use the templates when submitting an issue. Thanks.
