### ISSUE TITLE
TypeError: replace_unet_cross_attn_to_default.<locals>.forward_default() got an unexpected keyword argument 'encoder_hidden_states'

### ISSUE THREAD

**Issue by ShunsukeYamamoto** [d8ahazard/sd_dreambooth_extension#954]
Hello, I have an issue about using this extension.
I installed this extension to stable-diffuion-web-ui on Docker.
Created the model and try to run training, then I encountered this error below.
What's going on?
Is there anyone who met this error?
I hope you help me to solve this issue.
Thanks.

```shell
Initializing bucket counter!
  ***** Running training *****
  Num batches each epoch = 20
  Num Epochs = 1000
  Batch Size Per Device = 1
  Gradient Accumulation steps = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Text Encoder Epochs: 1000
  Total optimization steps = 20000
  Total training steps = 20000
  Resuming from checkpoint: False
  First resume epoch: 0
  First resume step: 0
  Lora: False, Adam: False, Prec: no
  Gradient Checkpointing: True
  EMA: False
  UNET: True
  Freeze CLIP Normalization Layers: False
  LR: 2e-06
  V2: True
Steps:   0%|          | 0/20000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/dreambooth.py", line 455, in start_training
    result = main(config, use_txt2img=use_txt2img)
  File "/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 989, in main
    return inner_loop()
  File "/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 121, in decorator
    return function(batch_size, grad_size, prof, log_file, *args, **kwargs)
  File "/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 864, in inner_loop
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 481, in forward
    sample, res_samples = downsample_block(
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/diffusers/models/unet_2d_blocks.py", line 781, in forward
    hidden_states = torch.utils.checkpoint.checkpoint(
  File "/usr/local/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/usr/local/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/usr/local/lib/python3.10/site-packages/diffusers/models/unet_2d_blocks.py", line 774, in custom_forward
    return module(*inputs, return_dict=return_dict)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/diffusers/models/transformer_2d.py", line 265, in forward
    hidden_states = block(
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/diffusers/models/attention.py", line 291, in forward
    attn_output = self.attn1(
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: replace_unet_cross_attn_to_default.<locals>.forward_default() got an unexpected keyword argument 'encoder_hidden_states'
Steps:   0%|          | 0/20000 [00:00<?, ?it/s]

```

### Environment
OS: Ubuntu 20.04.5 LTS
CPU: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
GPU: GeForce RTX3090

**Comment by empty2fill** [comment]
Use xformers memory attention.

Or check diffusers version. 
stable-diffusion-webui# git branch --show-current . | grep -c -E "main|master"
stable-diffusion-webui# source venv/bin/activate
stable-diffusion-webui# pip freeze | grep -c diffusers==0.10.2
stable-diffusion-webui# deactivate

**Comment by ShunsukeYamamoto** [comment]
@empty2fill 
I added --xformers option on CLI_ARGS for stable-diffusion-web-ui and this error was solved!
However, I met another error totally same [this](https://github.com/d8ahazard/sd_dreambooth_extension/issues/874), and I can't solve this error with the wrapper code shown in this issue.
Anyway, the problem can move on the next step!
Thank you for your help.
