### ISSUE TITLE
Dreambooth tab would not show

### ISSUE THREAD

**Issue by aihkla** [d8ahazard/sd_dreambooth_extension#960]
### Kindly read the entire form below and fill it out with the requested information.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your
issue will be automatically closed._**

`
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Commit hash: 65995a2ea38a1a0afd06cb508a4f65fd0d3a1743*
Installing requirements for Web UI
Skipping dreambooth installation.
Dreambooth revision is ****************************************
Diffusers version is *.*.*.
Torch version is *.*.*.
Torch vision version is *.*.*.
`
**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yes
**Have you updated Dreambooth to the latest revision?**
yes
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
yes
**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**
OK
**Describe the bug**
Stable Diffusion webui is running correctly, but everytime I try to install Dreambooth from the extension tab and restart, error would pop and I won't be able to see the tab. I have searched online for answer but in vain, so I come up for help.
(A clear and concise description of what the bug is)

**Provide logs**
Error running install.py for extension extensions\sd_dreambooth_extension.
Command: "C:\Users\2080-Super\stable-diffusion-webui\venv\Scripts\python.exe" "extensions\sd_dreambooth_extension\install.py"
Error code: 1
stdout:
#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Dreambooth revision: 43ae9d55531004f1dedaea7ac2443e9b16739913
SD-WebUI revision: 65995a2ea38a1a0afd06cb508a4f65fd0d3a1743

Checking Dreambooth requirements...

stderr: Traceback (most recent call last):
  File "C:\Users\2080-Super\stable-diffusion-webui\extensions\sd_dreambooth_extension\install.py", line 90, in <module>
    run(f'"{sys.executable}" -m pip install -r "{req_file}"', f"Checking {name} requirements...",
  File "C:\Users\2080-Super\stable-diffusion-webui\launch.py", line 105, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install Dreambooth requirements..
Command: "C:\Users\2080-Super\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install -r "C:\Users\2080-Super\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt"
Error code: 1
stdout: Ignoring tensorflow-macos: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment

stderr: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002821B872740>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /simple/accelerate/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002821B872A70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /simple/accelerate/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002821B871720>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /simple/accelerate/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002821B871C00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /simple/accelerate/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002821B872AA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /simple/accelerate/
ERROR: Could not find a version that satisfies the requirement accelerate==0.15.0 (from versions: none)
ERROR: No matching distribution found for accelerate==0.15.0

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: C:\Users\2080-Super\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip

Launching Web UI with arguments: --enable-insecure-extension-access --xformers
Error loading script: api.py
Traceback (most recent call last):
  File "C:\Users\2080-Super\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\2080-Super\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\2080-Super\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\api.py", line 22, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.db_concept import Concept
  File "C:\Users\2080-Super\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\db_concept.py", line 7, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.utils import get_images
  File "C:\Users\2080-Super\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\utils.py", line 23, in <module>
    import tensorflow
ModuleNotFoundError: No module named 'tensorflow'

Error loading script: dreambooth.py
Traceback (most recent call last):
  File "C:\Users\2080-Super\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\2080-Super\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\2080-Super\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\dreambooth.py", line 13, in <module>
    from diffusers.utils import logging as dl
ModuleNotFoundError: No module named 'diffusers'

Error loading script: main.py
Traceback (most recent call last):
  File "C:\Users\2080-Super\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\2080-Super\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\2080-Super\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py", line 6, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.db_config import save_config, from_file
  File "C:\Users\2080-Super\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\db_config.py", line 9, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.db_concept import Concept
  File "C:\Users\2080-Super\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\db_concept.py", line 7, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.utils import get_images
  File "C:\Users\2080-Super\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\utils.py", line 23, in <module>
    import tensorflow
ModuleNotFoundError: No module named 'tensorflow'

Loading weights [cc6cb27103] from C:\Users\2080-Super\stable-diffusion-webui\models\Stable-diffusion\model.ckpt
Creating model from config: C:\Users\2080-Super\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0):
Model loaded in 5.7s (load weights from disk: 1.6s, create model: 0.5s, apply weights to model: 0.6s, apply half(): 0.9s, move model to device: 0.8s, load textual inversion embeddings: 1.1s).
Running on local URL:  http://127.0.0.1:7860
If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *
before* the crash occurred.

**Environment**

What OS?
Window 10

If Windows - WSL or native?

What GPU are you using?
2080S

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the
db_config.json file from /models/dreambooth/MODELNAME/db_config.json

**Comment by ArrowM** [comment]
tab doesn't appear because there was an error initializing the extension because it failed to install requirements because... pip couldn't connect to the internet?
