### ISSUE TITLE
Class image generate will loop if filename has symbol on Windows

### ISSUE THREAD

**Issue by fullcounterr** [d8ahazard/sd_dreambooth_extension#966]
**Please find the following lines in the console and paste them below. _If you do not provide this information, your
issue will be automatically closed._**

```
Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: 43ae9d55531004f1dedaea7ac2443e9b16739913
SD-WebUI revision: 3715ece0adce7bf7c5e9c5ab3710b2fdc3848f39

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.14.dev0 installed.
[+] torch version 1.12.1+cu116 installed.
[+] torchvision version 0.13.1+cu116 installed.
```

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?** 
Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes

**Have you updated Dreambooth to the latest revision?**
Yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
Yes

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**
OK

**Describe the bug**

I am training on Windows and using [filewords] prepared by the web ui. Some character is messing with the filename (e.g :) and it will loop the generation of class image. The first run will succeed and it will generate class image, but the class image that has colon will get skipped. I stopped training then after I resume the training the missing class image is being generated again (those with filename containing colon) but keep failing because of the filename and went in endless loop. The training won't start and is stuck on loop when generating class image.

**Provide logs**

Here is the the log : 

```
Initializing dreambooth training...
Pre-processing combined_test: 100%███████████████████████████████████████████████████████████████████████ 302/302 [00:01<00:00, 232.91it/s]
Pre-processing classifiers_0: 100%███████████████████████████████████████████████████████████████████████ 268/268 [00:01<00:00, 199.87it/s]
Concept requires 1 class images per instance image.
Sorting instance images: 100%███████████████████████████████████████████████████████████████████████ 1/1 [00:00<00:00, 499.62it/s]
We need a total of 34 class images.
Generating 34 class images for training...
Generating class images 0/34::   0%|                                                                       | 0/34 [00:00<?, ?it/s]Loading model: anything-v4.5
Loading weights [fbcf965a62] from C:\novelaileak_2\stable-diffusion-webui\models\Stable-diffusion\anything-v4.5.ckpt
Creating model from config: C:\novelaileak_2\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: C:\novelaileak_2\stable-diffusion-webui\models\Stable-diffusion\anything-v4.0.vae.pt
Applying xformers cross attention optimization.
Model loaded in 7.3s (load weights from disk: 4.4s, create model: 0.4s, apply weights to model: 0.7s, apply half(): 0.3s, load VAE: 0.8s, move model to device: 0.6s).
100%███████████████████████████████████████████████████████████████████████ 30/30 [00:07<00:00,  3.81it/s]
Exception generating images: [WinError 87] The parameter is incorrect: 'C:\\novelaileak_2\\stable-diffusion-webui\\models\\dreambooth\\momoko4.5v8\\classifiers_0\\1girl, :p, bangs, braid, choker, collarbone, earrings, eyebrows_-72c7beeb.tmp' -> 'C:\\novelaileak_2\\stable-diffusion-webui\\models\\dreambooth\\momoko4.5v8\\classifiers_0\\1girl, :p, bangs, braid, choker, collarbone, earrings, eyebrows_-72c7beeb.tmp'
Traceback (most recent call last):
  File "C:\novelaileak_2\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\finetune_utils.py", line 980, in generate_classifiers
    image_filename = db_save_image(image, pd, custom_name=f"{pd.prompt[0:64]}-{image_base[0:8]}")
  File "C:\novelaileak_2\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\utils.py", line 512, in db_save_image
    os.replace(image_filename, image_filename)
OSError: [WinError 87] The parameter is incorrect: 'C:\\novelaileak_2\\stable-diffusion-webui\\models\\dreambooth\\momoko4.5v8\\classifiers_0\\1girl, :p, bangs, braid, choker, collarbone, earrings, eyebrows_-72c7beeb.tmp' -> 'C:\\novelaileak_2\\stable-diffusion-webui\\models\\dreambooth\\momoko4.5v8\\classifiers_0\\1girl, :p, bangs, braid, choker, collarbone, earrings, eyebrows_-72c7beeb.tmp'
100%███████████████████████████████████████████████████████████████████████ 30/30 [12:54<00:00, 25.82s/it]
Exception generating images: [WinError 87] The parameter is incorrect: 'C:\\novelaileak_2\\stable-diffusion-webui\\models\\dreambooth\\momoko4.5v8\\classifiers_0\\1girl, :p, bangs, bare_shoulders, braid, christmas_ornaments, co-f1e4dbc7.tmp' -> 'C:\\novelaileak_2\\stable-diffusion-webui\\models\\dreambooth\\momoko4.5v8\\classifiers_0\\1girl, :p, bangs, bare_shoulders, braid, christmas_ornaments, co-f1e4dbc7.tmp'
Traceback (most recent call last):
  File "C:\novelaileak_2\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\finetune_utils.py", line 980, in generate_classifiers
    image_filename = db_save_image(image, pd, custom_name=f"{pd.prompt[0:64]}-{image_base[0:8]}")
  File "C:\novelaileak_2\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\utils.py", line 512, in db_save_image
    os.replace(image_filename, image_filename)
OSError: [WinError 87] The parameter is incorrect: 'C:\\novelaileak_2\\stable-diffusion-webui\\models\\dreambooth\\momoko4.5v8\\classifiers_0\\1girl, :p, bangs, bare_shoulders, braid, christmas_ornaments, co-f1e4dbc7.tmp' -> 'C:\\novelaileak_2\\stable-diffusion-webui\\models\\dreambooth\\momoko4.5v8\\classifiers_0\\1girl, :p, bangs, bare_shoulders, braid, christmas_ornaments, co-f1e4dbc7.tmp'
Generating class images 0/34::  83%██████████████████████████████████████████?          | 25/30 [00:07<00:04,  1.19it/s]
 83%██████████████████████████████████████████               | 25/30 [00:16<00:17,  3.56s/it]

?
This will repeat and continue
```

**Environment**

What OS? 
Windows

If Windows - WSL or native? 
Native

What GPU are you using? 
RTX 3080 Ti

**Screenshots/Config**
![image](https://user-images.githubusercontent.com/18608855/220513167-6c89f3bc-e2d5-4feb-bc97-b319ece4e10b.png)

**Comment by d8ahazard** [comment]
This should be resolved with https://github.com/d8ahazard/sd_dreambooth_extension/releases/tag/1.0.11

Feel free to open a new issue if you're still having problems.
