### ISSUE TITLE
When the models directory is symlinked, generating samples causes an error 

### ISSUE THREAD

**Issue by CErratum** [d8ahazard/sd_dreambooth_extension#978]
### Kindly read the entire form below and fill it out with the requested information.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your
issue will be automatically closed._**

`
Python revision: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Dreambooth revision: 43ae9d55531004f1dedaea7ac2443e9b16739913
SD-WebUI revision: 226d840e84c5f306350b0681945989b86760e616

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.16rc425 installed.
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
`

☑ **Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?** 

☑ **Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?** 

☑ **Have you updated Dreambooth to the latest revision?**

☑ **Have you updated the Stable-Diffusion-WebUI to the latest version?**

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**
OK

**Describe the bug**

Samples fail to generate with an error message from genericpath. Model directory is symlinked to a folder on a different drive.

**Provide logs**

Exception generating sample(s): join() argument must be str, bytes, or os.PathLike object, not 'list'
Traceback (most recent call last):
  File "C:\Users\kelvi\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\dreambooth.py", line 290, in sample_loop
    img_builder = ImageBuilder(
  File "C:\Users\kelvi\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\finetune_utils.py", line 467, in __init__
    lora_model_path = os.path.join(db_shared.models_path, "lora", lora_model)
  File "C:\Users\kelvi\AppData\Local\Programs\Python\Python310\lib\ntpath.py", line 143, in join
    genericpath._check_arg_types('join', path, *paths)
  File "C:\Users\kelvi\AppData\Local\Programs\Python\Python310\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'list'

n.b.: lora model directory is symlinked to a folder on another drive

**Environment**

What OS? Windows 10 Pro 21H2

If Windows - WSL or native? Native

What GPU are you using? GTX 1080 Ti 

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the
db_config.json file from /models/dreambooth/MODELNAME/db_config.json

**Comment by ArrowM** [comment]
Please update to the latest version of the extension and report back.

**Comment by jlwinn8** [comment]
I was having a similar issue. Noticed that the "use text2img" box at the bottom of the generate tab was unchecked. checking it solved it for me.

**Comment by ArrowM** [comment]
should be fixed by #1005
