### ISSUE TITLE
Operator not Found Error

### ISSUE THREAD

**Issue by nephi-dev** [d8ahazard/sd_dreambooth_extension#98]
**Have you read the Readme?**
Yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes
**Have you updated Dreambooth to the latest revision?**
Yes
**Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth**

```
Dreambooth revision is c1702f13820984a4dbe0f5c4552a14c7833b277e
Diffusers version is 0.8.0.dev0.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.
```

**Describe the bug**
I'm with this error when trying to train a dreambooth model:
`NotImplementedError: No operator found for this attention: AttentionOpDispatch(dtype=torch.float32, device=device(type='cpu'), k=40, has_dropout=False, attn_bias_type=<class 'NoneType'>, kv_len=4096, q_len=4096, kv=40, batch_size=8, num_heads=1)`

**Provide logs**
```
Traceback (most recent call last):
  File "F:\dev\python\ml_apps\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "F:\dev\python\ml_apps\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "F:\dev\python\ml_apps\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 275, in start_training
    trained_steps = main(config)
  File "F:\dev\python\ml_apps\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 903, in main
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "F:\dev\python\ml_apps\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\dev\python\ml_apps\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 307, in forward
    sample, res_samples = downsample_block(
  File "F:\dev\python\ml_apps\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\dev\python\ml_apps\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 593, in forward
    hidden_states = torch.utils.checkpoint.checkpoint(
  File "F:\dev\python\ml_apps\stable-diffusion-webui\venv\lib\site-packages\torch\utils\checkpoint.py", line 235, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "F:\dev\python\ml_apps\stable-diffusion-webui\venv\lib\site-packages\torch\utils\checkpoint.py", line 96, in forward
    outputs = run_function(*args)
  File "F:\dev\python\ml_apps\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 586, in custom_forward
    return module(*inputs, return_dict=return_dict)
  File "F:\dev\python\ml_apps\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\dev\python\ml_apps\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\attention.py", line 204, in forward
    hidden_states = block(hidden_states, context=encoder_hidden_states, timestep=timestep)
  File "F:\dev\python\ml_apps\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\dev\python\ml_apps\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\attention.py", line 406, in forward
    hidden_states = self.attn1(norm_hidden_states) + hidden_states
  File "F:\dev\python\ml_apps\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\dev\python\ml_apps\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\attention.py", line 495, in forward
    hidden_states = self._memory_efficient_attention_xformers(query, key, value)
  File "F:\dev\python\ml_apps\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\attention.py", line 556, in _memory_efficient_attention_xformers
    hidden_states = xformers.ops.memory_efficient_attention(query, key, value, attn_bias=None)
  File "F:\dev\python\ml_apps\stable-diffusion-webui\venv\lib\site-packages\xformers\ops.py", line 858, in memory_efficient_attention
    ).op
  File "F:\dev\python\ml_apps\stable-diffusion-webui\venv\lib\site-packages\xformers\ops.py", line 726, in op
    raise NotImplementedError(f"No operator found for this attention: {self}")
NotImplementedError: No operator found for this attention: AttentionOpDispatch(dtype=torch.float32, device=device(type='cpu'), k=40, has_dropout=False, attn_bias_type=<class 'NoneType'>, kv_len=4096, q_len=4096, kv=40, batch_size=8, num_heads=1)
```

**Environment**
What OS? Windows
If Windows - WSL or native? Native
What GPU are you using? RTX2060 Super(Actually using CPU)

**Comment by d8ahazard** [comment]
So, I used my super google-fu powers, and found this:

https://www.reddit.com/r/StableDiffusion/comments/xz26lq/comment/irlckyf/?utm_source=reddit&utm_medium=web2x&context=3

The response says you need to compile xformers yourself?

**Comment by nephi-dev** [comment]
I will try to compile it, thanks for the help

**Comment by nephi-dev** [comment]
Still with the error

**Comment by nephi-dev** [comment]
now bitsandbytes is giving me a "...memory error..."

**Comment by nephi-dev** [comment]
And the error still happening

```
 File "F:\dev\python\ml_apps\stable-diffusion-webui\venv\lib\site-packages\xformers\ops.py", line 726, in op
    raise NotImplementedError(f"No operator found for this attention: {self}")
NotImplementedError: No operator found for this attention: AttentionOpDispatch(dtype=torch.float32, device=device(type='cpu'), k=40, has_dropout=False, attn_bias_type=<class 'NoneType'>, kv_len=4096, q_len=4096, kv=40, batch_size=8, num_heads=1)
```

**Comment by satinat** [comment]
I have this same error trying to train with CPU. Both before compiling the xformers and after.  Training on my 8GB RTX 3060ti does not work due to memory requirements so CPU is my only option at this point.  @d8ahazard @nephi-dev

**Comment by d8ahazard** [comment]
> I have this same error trying to train with CPU. Both before compiling the xformers and after. Training on my 8GB RTX 3060ti does not work due to memory requirements so CPU is my only option at this point. @d8ahazard @nephi-dev

It should be possible to train dreambooth on a potato if it has enough RAM using GPU only. I think the trick is to *not* use 8bit adam or FP16, disable Text encoder, ema.

You might also need to install the proper CUDA toolkit for some errors:

https://developer.nvidia.com/cuda-11-6-0-download-archive

**Comment by sampanes** [comment]
same error

**Comment by differentprogramming** [comment]
Almost the same error, but with the device being cuda instead of cpu

I had to compile xformers from source to get them to install.
I installed the same torch and torchvision versions as OP, by hand in venv
When it complained about mismatching versions with cuda, I installed the version of Cuda it told me, 11.7 which may be a mistake because this version of torch doesn't go above 11.6

It can use xformers to generate pictures but when I try to train I get:

Starting Dreambooth training...
 VRAM cleared.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Loaded model.
 Allocated: 0.0GB
 Reserved: 0.0GB


===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA SETUP: CUDA runtime path found: /usr/local/cuda-11.7/lib64/libcudart.so
CUDA exception! Error code: no CUDA-capable device is detected
CUDA exception! Error code: initialization error
CUDA SETUP: Highest compute capability among GPUs detected: None
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so...
 Scheduler Loaded
 Allocated: 0.3GB
 Reserved: 0.3GB

***** Running training *****
  Num examples = 27
  Num batches each epoch = 27
  Num Epochs = 97
  Instantaneous batch size per device = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Gradient Accumulation steps = 1
  Total optimization steps = 2600
Steps:   0%|                                                                                   | 0/2600 [00:00<?, ?it/s]
 Exception while training: No operator found for this attention: AttentionOpDispatch(dtype=torch.float32, device=device(type='cuda', index=0), k=160, has_dropout=False, attn_bias_type=<class 'NoneType'>, kv_len=64, q_len=64, kv=160, batch_size=8, num_heads=1, has_custom_scale=False, requires_grad=True)
 Allocated: 4.0GB
 Reserved: 7.8GB

Traceback (most recent call last):
  File "/home/user/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 963, in main
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 318, in forward
    sample = self.mid_block(sample, emb, encoder_hidden_states=encoder_hidden_states)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/unet_2d_blocks.py", line 401, in forward
    hidden_states = attn(hidden_states, encoder_hidden_states).sample
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/attention.py", line 202, in forward
    hidden_states = block(hidden_states, context=encoder_hidden_states, timestep=timestep)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/attention.py", line 404, in forward
    hidden_states = self.attn1(norm_hidden_states) + hidden_states
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/xattention.py", line 114, in forward
    hidden_states = self._memory_efficient_attention_xformers(query, key, value)
  File "/home/user/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/xattention.py", line 175, in _memory_efficient_attention_xformers
    hidden_states = xformers.ops.memory_efficient_attention(query, key, value, attn_bias=None)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/xformers/ops/memory_efficient_attention.py", line 963, in memory_efficient_attention
    ).op
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/xformers/ops/memory_efficient_attention.py", line 821, in op
    raise NotImplementedError(f"No operator found for this attention: {self}")
NotImplementedError: No operator found for this attention: AttentionOpDispatch(dtype=torch.float32, device=device(type='cuda', index=0), k=160, has_dropout=False, attn_bias_type=<class 'NoneType'>, kv_len=64, q_len=64, kv=160, batch_size=8, num_heads=1, has_custom_scale=False, requires_grad=True)
 Exception while training: No operator found for this attention: AttentionOpDispatch(dtype=torch.float32, device=device(type='cuda', index=0), k=160, has_dropout=False, attn_bias_type=<class 'NoneType'>, kv_len=64, q_len=64, kv=160, batch_size=8, num_heads=1, has_custom_scale=False, requires_grad=True)
 Allocated: 4.0GB
 Reserved: 7.8GB

...repeated many times...
followed by:
 CLEANUP:
 Allocated: 4.0GB
 Reserved: 7.8GB

 Cleanup Complete.
 Allocated: 4.0GB
 Reserved: 4.1GB

Steps:   0%|                                                                                   | 0/2600 [00:54<?, ?it/s]
 Training completed, reloading SD Model.
 Allocated: 0.0GB
 Reserved: 0.0GB

Memory output: {'VRAM cleared.': '0.0/0.0GB', 'Loaded model.': '0.0/0.0GB', 'Scheduler Loaded': '0.3/0.3GB', "Exception while training: No operator found for this attention: AttentionOpDispatch(dtype=torch.float32, device=device(type='cuda', index=0), k=160, has_dropout=False, attn_bias_type=<class 'NoneType'>, kv_len=64, q_len=64, kv=160, batch_size=8, num_heads=1, has_custom_scale=False, requires_grad=True)": '4.0/7.8GB', 'CLEANUP: ': '4.0/7.8GB', 'Cleanup Complete.': '4.0/4.1GB', 'Training completed, reloading SD Model.': '0.0/0.0GB'}
Re-applying optimizations...
Returning result: Training finished. Total lifetime steps: 3

**Comment by differentprogramming** [comment]
If I turn on fp16 and adam8 it works!

**Comment by DoughyInTheMiddle** [comment]
Trying to run CPU (because while stealing my son's 2060 Super to use instead of my *struggling* 1060 is nice, it's still not enough), and it's at this level with me too.

I tried following the various guides to use DeepSpeed, Accelerate, and just keep running into walls. 

Training Steps: 1111
Image Count: 24
Learning rate: 0.000001
Checkpoint Free: 0 (tried 10000 too)
Save Preview: 0 (tried 10000 too)
CPU: TRUE
Gradient Checkpoint: TRUE
Mixed precision: no (throws an error if I don't and I gotta restart)
Text: FALSE
Train EMA: FALSE
8bit Adam: TRUE

```
Traceback (most recent call last):
  File "G:\GitHub\SDWebUI\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 963, in main
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "G:\GitHub\SDWebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "G:\GitHub\SDWebUI\venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 307, in forward
    sample, res_samples = downsample_block(
  File "G:\GitHub\SDWebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "G:\GitHub\SDWebUI\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 593, in forward
    hidden_states = torch.utils.checkpoint.checkpoint(
  File "G:\GitHub\SDWebUI\venv\lib\site-packages\torch\utils\checkpoint.py", line 235, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "G:\GitHub\SDWebUI\venv\lib\site-packages\torch\utils\checkpoint.py", line 96, in forward
    outputs = run_function(*args)
  File "G:\GitHub\SDWebUI\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 586, in custom_forward
    return module(*inputs, return_dict=return_dict)
  File "G:\GitHub\SDWebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "G:\GitHub\SDWebUI\venv\lib\site-packages\diffusers\models\attention.py", line 202, in forward
    hidden_states = block(hidden_states, context=encoder_hidden_states, timestep=timestep)
  File "G:\GitHub\SDWebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "G:\GitHub\SDWebUI\venv\lib\site-packages\diffusers\models\attention.py", line 404, in forward
    hidden_states = self.attn1(norm_hidden_states) + hidden_states
  File "G:\GitHub\SDWebUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "G:\GitHub\SDWebUI\extensions\sd_dreambooth_extension\dreambooth\xattention.py", line 114, in forward
    hidden_states = self._memory_efficient_attention_xformers(query, key, value)
  File "G:\GitHub\SDWebUI\extensions\sd_dreambooth_extension\dreambooth\xattention.py", line 175, in _memory_efficient_attention_xformers
    hidden_states = xformers.ops.memory_efficient_attention(query, key, value, attn_bias=None)
  File "G:\GitHub\SDWebUI\venv\lib\site-packages\xformers\ops.py", line 858, in memory_efficient_attention
    ).op
  File "G:\GitHub\SDWebUI\venv\lib\site-packages\xformers\ops.py", line 726, in op
    raise NotImplementedError(f"No operator found for this attention: {self}")
NotImplementedError: No operator found for this attention: AttentionOpDispatch(dtype=torch.float32, device=device(type='cpu'), k=40, has_dropout=False, attn_bias_type=<class 'NoneType'>, kv_len=4096, q_len=4096, kv=40, batch_size=16, num_heads=1)
 Exception while training: No operator found for this attention: AttentionOpDispatch(dtype=torch.float32, device=device(type='cpu'), k=40, has_dropout=False, attn_bias_type=<class 'NoneType'>, kv_len=4096, q_len=4096, kv=40, batch_size=16, num_heads=1)
 Allocated: 0.0GB
 Reserved: 0.0GB
```

**Comment by d8ahazard** [comment]
This should be resolved. We have multiple options for memory attention now, plus checks and nags for both xformers and cpu-only training.
