### ISSUE TITLE
Cmd('git') failed due to: exit code(128)

### ISSUE THREAD

**Issue by Bug64** [d8ahazard/sd_dreambooth_extension#980]
### Kindly read the entire form below and fill it out with the requested information.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your
issue will be automatically closed._**

```
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Commit hash: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
Installing requirements for Web UI

Ignoring tensorflow-macos: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
Requirement already satisfied: accelerate==0.16.0 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from -r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (0.16.0)
Requirement already satisfied: albumentations~=1.3.0 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from -r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (1.3.0)
Requirement already satisfied: bitsandbytes==0.35.4 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from -r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 3)) (0.35.4)
Requirement already satisfied: diffusers==0.13.1 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from -r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (0.13.1)
Requirement already satisfied: gitpython~=3.1.31 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from -r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 5)) (3.1.31)
Requirement already satisfied: fastapi in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from -r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 6)) (0.90.1)
Requirement already satisfied: ftfy~=6.1.1 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from -r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 7)) (6.1.1)
Requirement already satisfied: modelcards~=0.1.6 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from -r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (0.1.6)
Requirement already satisfied: tensorboard in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from -r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (2.11.0)
Requirement already satisfied: tensorflow==2.11.0 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from -r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (2.11.0)
Requirement already satisfied: tqdm~=4.64.1 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from -r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 12)) (4.64.1)
Requirement already satisfied: transformers~=4.26.1 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from -r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 13)) (4.26.1)
Requirement already satisfied: discord-webhook~=1.1.0 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from -r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 14)) (1.1.0)
Requirement already satisfied: lion-pytorch~=0.0.7 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from -r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 15)) (0.0.7)
Requirement already satisfied: xformers==0.0.17.dev464 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from -r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 16)) (0.0.17.dev464)
Requirement already satisfied: pyyaml in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from accelerate==0.16.0->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (6.0)
Requirement already satisfied: torch>=1.4.0 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from accelerate==0.16.0->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (1.13.1+cu117)
Requirement already satisfied: numpy>=1.17 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from accelerate==0.16.0->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (1.23.3)
Requirement already satisfied: packaging>=20.0 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from accelerate==0.16.0->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (23.0)
Requirement already satisfied: psutil in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from accelerate==0.16.0->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (5.9.4)
Requirement already satisfied: regex!=2019.12.17 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from diffusers==0.13.1->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (2022.10.31)
Requirement already satisfied: filelock in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from diffusers==0.13.1->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (3.9.0)
Requirement already satisfied: importlib-metadata in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from diffusers==0.13.1->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (6.0.0)
Requirement already satisfied: Pillow in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from diffusers==0.13.1->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (9.4.0)
Requirement already satisfied: requests in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from diffusers==0.13.1->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (2.28.2)
Requirement already satisfied: huggingface-hub>=0.10.0 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from diffusers==0.13.1->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (0.12.0)
Requirement already satisfied: tensorflow-intel==2.11.0 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from tensorflow==2.11.0->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (2.11.0)
Requirement already satisfied: pyre-extensions==0.0.23 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from xformers==0.0.17.dev464->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 16)) (0.0.23)
Requirement already satisfied: typing-extensions in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from pyre-extensions==0.0.23->xformers==0.0.17.dev464->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 16)) (4.5.0)
Requirement already satisfied: typing-inspect in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from pyre-extensions==0.0.23->xformers==0.0.17.dev464->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 16)) (0.8.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (1.4.0)
Requirement already satisfied: google-pasta>=0.1.1 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (0.2.0)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (3.3.0)
Requirement already satisfied: setuptools in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (65.5.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (1.14.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (0.30.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (1.6.3)
Requirement already satisfied: flatbuffers>=2.0 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (23.1.21)
Requirement already satisfied: protobuf<3.20,>=3.9.2 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (3.19.6)
Requirement already satisfied: tensorflow-estimator<2.12,>=2.11.0 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (2.11.0)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (0.4.0)
Requirement already satisfied: six>=1.12.0 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (1.16.0)
Requirement already satisfied: libclang>=13.0.0 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (15.0.6.1)
Requirement already satisfied: keras<2.12,>=2.11.0 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (2.11.0)
Requirement already satisfied: h5py>=2.9.0 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (3.8.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (2.2.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 10)) (1.51.1)
Requirement already satisfied: qudida>=0.0.4 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from albumentations~=1.3.0->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (0.0.4)
Requirement already satisfied: opencv-python-headless>=4.1.1 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from albumentations~=1.3.0->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (4.7.0.68)
Requirement already satisfied: scikit-image>=0.16.1 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from albumentations~=1.3.0->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (0.19.2)
Requirement already satisfied: scipy in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from albumentations~=1.3.0->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (1.10.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from gitpython~=3.1.31->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 5)) (4.0.10)
Requirement already satisfied: starlette<0.24.0,>=0.22.0 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from fastapi->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 6)) (0.23.1)
Requirement already satisfied: pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from fastapi->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 6)) (1.10.5)
Requirement already satisfied: wcwidth>=0.2.5 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from ftfy~=6.1.1->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 7)) (0.2.6)
Requirement already satisfied: Jinja2 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from modelcards~=0.1.6->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (3.1.2)
Requirement already satisfied: google-auth<3,>=1.6.3 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from tensorboard->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (2.16.0)
Requirement already satisfied: markdown>=2.6.8 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from tensorboard->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (3.4.1)
Requirement already satisfied: wheel>=0.26 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from tensorboard->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (0.38.4)
Requirement already satisfied: werkzeug>=1.0.1 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from tensorboard->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (2.2.3)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from tensorboard->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (1.8.1)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from tensorboard->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (0.4.6)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from tensorboard->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (0.6.1)
Requirement already satisfied: colorama in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from tqdm~=4.64.1->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 12)) (0.4.6)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from transformers~=4.26.1->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 13)) (0.13.2)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from gitdb<5,>=4.0.1->gitpython~=3.1.31->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 5)) (5.0.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (4.9)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (5.3.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (1.3.1)
Requirement already satisfied: scikit-learn>=0.19.1 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from qudida>=0.0.4->albumentations~=1.3.0->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (1.2.1)
Requirement already satisfied: idna<4,>=2.5 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from requests->diffusers==0.13.1->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from requests->diffusers==0.13.1->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (1.26.14)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from requests->diffusers==0.13.1->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (3.0.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from requests->diffusers==0.13.1->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (2022.12.7)
Requirement already satisfied: tifffile>=2019.7.26 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from scikit-image>=0.16.1->albumentations~=1.3.0->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (2023.2.3)
Requirement already satisfied: networkx>=2.2 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from scikit-image>=0.16.1->albumentations~=1.3.0->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (3.0)
Requirement already satisfied: imageio>=2.4.1 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from scikit-image>=0.16.1->albumentations~=1.3.0->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (2.25.1)
Requirement already satisfied: PyWavelets>=1.1.1 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from scikit-image>=0.16.1->albumentations~=1.3.0->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (1.4.1)
Requirement already satisfied: anyio<5,>=3.4.0 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from starlette<0.24.0,>=0.22.0->fastapi->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 6)) (3.6.2)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from werkzeug>=1.0.1->tensorboard->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (2.1.2)
Requirement already satisfied: zipp>=0.5 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from importlib-metadata->diffusers==0.13.1->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (3.13.0)
Requirement already satisfied: sniffio>=1.1 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from anyio<5,>=3.4.0->starlette<0.24.0,>=0.22.0->fastapi->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 6)) (1.3.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (3.2.2)
Requirement already satisfied: joblib>=1.1.1 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from scikit-learn>=0.19.1->qudida>=0.0.4->albumentations~=1.3.0->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from scikit-learn>=0.19.1->qudida>=0.0.4->albumentations~=1.3.0->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (3.1.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from typing-inspect->pyre-extensions==0.0.23->xformers==0.0.17.dev464->-r C:\stableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 16)) (1.0.0)

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Dreambooth revision: d4e2f7d5dc5c67cc6292c8b8137b688a43247c35
SD-WebUI revision: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8

Checking Dreambooth requirements...
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
[+] bitsandbytes version 0.35.4 installed.
[+] diffusers version 0.13.1 installed.
[+] transformers version 4.26.1 installed.
[+] xformers version 0.0.17.dev464 installed.

#######################################################################################################
```

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes

**Have you updated Dreambooth to the latest revision?**
Yes

**Have you updated the Stable-Diffusion-WebUI to the latest version?**
PS C:\stableDiffusion\stable-diffusion-webui> git pull
Already up to date.

**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**
OK

**Describe the bug**
After installing the DB Extension, update checks for all extensions fail.  
```
Error checking updates for Hypernetwork-MonkeyPatch-Extension:
Traceback (most recent call last):
  File "C:\stableDiffusion\stable-diffusion-webui\modules\ui_extensions.py", line 66, in check_updates
    ext.check_updates()
  File "C:\stableDiffusion\stable-diffusion-webui\modules\extensions.py", line 69, in check_updates
    for fetch in repo.remote().fetch("--dry-run"):
  File "C:\stableDiffusion\stable-diffusion-webui\venv\lib\site-packages\git\remote.py", line 1015, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress, kill_after_timeout=kill_after_timeout)
  File "C:\stableDiffusion\stable-diffusion-webui\venv\lib\site-packages\git\remote.py", line 854, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "C:\stableDiffusion\stable-diffusion-webui\venv\lib\site-packages\git\cmd.py", line 604, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v -- origin --dry-run
  stderr: 'fatal: couldn't find remote ref --dry-run'

```
Appears to be a reincarnation of https://github.com/d8ahazard/sd_dreambooth_extension/issues/717

**Provide logs**
[DB Extension Bug.docx](https://github.com/d8ahazard/sd_dreambooth_extension/files/10861566/DB.Extension.Bug.docx)

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *
before* the crash occurred.

**Environment**
Windows 11 / powershell

What GPU are you using?
RTX 4080

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the
db_config.json file from /models/dreambooth/MODELNAME/db_config.json

**Comment by d8ahazard** [comment]
So, I did bump the gitpython version again, as there's a critical security issue with the version Auto1111 has set for install.

But I'm also (also) running Windows 11/powershell with the same version and not getting an y issues, so I'm not necessarily convinced that reverting it again is the proper solution.

The fact that it's throwing a Nonetype error when you try to do an update on the HyperNetwork... extension makes me curious if like, you installed that manually or something, or if it's not actually a git repo?

**Comment by ArrowM** [comment]
I've ran into this. You're right, the updated GitPython lib broke --dry-run. Try removing "--dry-run" from extension.py.
![image](https://user-images.githubusercontent.com/42418080/222202161-2bd33f3e-7385-4f61-a20d-da976b1738d5.png)

**Comment by eadnams22** [comment]
Thanks @ArrowM ! Was getting this too, even with proper installation. :)

**Comment by Bug64** [comment]
Hi @ArrowM.  I didn't install anything manually and I get the same error on all of the extensions.  For the log I attached, I started by deleting the DB extension.  When I did, I was able to run check w/o any errors.  I then re-installed DB, exited the web app, started it up again and then tried another check and the errors appear.  I've confirmed that if I delete DB, the errors go away again.

**Comment by Bug64** [comment]
Maybe this will resolve it: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8116

**Comment by zefengwangparis** [comment]
> I've ran into this. You're right, the updated GitPython lib broke --dry-run. Try removing "--dry-run" from extension.py. ![image](https://user-images.githubusercontent.com/42418080/222202161-2bd33f3e-7385-4f61-a20d-da976b1738d5.png)

Hello, I have check all the files named extension.py, but I haven't found this "def check_updates(self)...". Could you tell me where it is? Thank you!
![20230503202823](https://user-images.githubusercontent.com/132441346/235915631-013ef2dc-65b9-440c-9b23-84b864c914f6.png)

**Comment by TripleKiller666** [comment]
try to change "for fetch in repo.remote().fetch(dry_run=True):" into
"for fetch in repo.remote().fetch():"
