### ISSUE TITLE
Exception training model: 'type str doesn't define __round__ method'

### ISSUE THREAD

**Issue by jtan-sl** [d8ahazard/sd_dreambooth_extension#996]
### Kindly read the entire form below and fill it out with the requested information.

**Please find the following lines in the console and paste them below. _If you do not provide this information, your
issue will be automatically closed._**

`
Python revision: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
Dreambooth revision: https://github.com/d8ahazard/sd_dreambooth_extension/commit/d4e2f7d5dc5c67cc6292c8b8137b688a43247c35
SD-WebUI revision: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8

Checking Dreambooth requirements...
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.
[+] bitsandbytes version 0.35.4 installed.
[+] diffusers version 0.13.1 installed.
[+] transformers version 4.26.1 installed.
[+] xformers version 0.0.17.dev464 installed.
`

**Have you read the [Readme](https://github.com/d8ahazard/sd_dreambooth_extension#readme)?**
yes
**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
yes
**Have you updated Dreambooth to the latest revision?**
yes
**Have you updated the Stable-Diffusion-WebUI to the latest version?**
yes
**No, really. Please save us both some trouble and update the SD-WebUI and Extension and restart before posting this.
Reply 'OK' Below to acknowledge that you did this.**
OK
**Describe the bug**

Train - failed to start getting this error on the UI 
Exception training model: 'type str doesn't define __round__ method'.

**Provide logs**

Found 315 reg images.
Preparing dataset...
Init dataset!
Preparing Dataset (Without Caching)
Processing images...: 100%|██████████| 336/336 [00:00<00:00, 323156.65it/s]
Traceback (most recent call last):
  File "/home/ubuntu/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 555, in start_training
    result = main(use_txt2img=use_txt2img)
  File "/home/ubuntu/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1133, in main
    return inner_loop()
  File "/home/ubuntu/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 123, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "/home/ubuntu/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 564, in inner_loop
    text_encoder_epochs = round(args.num_train_epochs * stop_text_percentage)
TypeError: type str doesn't define __round__ method

If a crash has occurred, please provide the *entire* stack trace from the log, including the last few log messages *
before* the crash occurred.

**Environment**

What OS? Ubuntu 

If Windows - WSL or native?

What GPU are you using?  
Nvidia T4 (on aws g4dn.xlarge)

**Screenshots/Config**
If the issue is specific to an error while training, please provide a screenshot of training parameters or the
db_config.json file from /models/dreambooth/MODELNAME/db_config.json

**Comment by ef1500** [comment]
Where do you find this setting?

**Comment by ArrowM** [comment]
last 2 comment explain a simple fix. We are aware of the issue and have an actual fix coming.
